### ISSUE TITLE
New and "Easy" Uniforms

### ISSUE THREAD

**Issue by ColdIce1605** [IrisShaders/Iris#1]
uniform float viewWidth;                        viewWidth
uniform float viewHeight;                       viewHeight
uniform float near;                             near viewing plane distance
uniform float far;                              far viewing plane distance
These uniforms should be easy to add and many basic shaders use them for DOF and other effects.

**Comment by coderbot16** [comment]
Those look simple to add, good to know. I've been trying to write detailed documentation about all of the uniforms [here](https://github.com/IrisShaders/ShaderDoc/blob/master/uniforms.md) and hope to use this to implement them, however right *now* I'm just trying to implement the uniforms used by the shaderpacks I'm testing with (currently, Trippy-Shaderpack).

But once I get started testing with more shaderpacks, I'm sure that implementing these will be a priority!

**Comment by ColdIce1605** [comment]
another thing to add that a lot of shaders use are Geometry shaders, this would be little hard to add but this would help too
@coderbot16

**Comment by coderbot16** [comment]
Huh, good to know. Though implementing geometry shaders is probably going to have to happen quite a bit down the line, of course.

**Comment by ColdIce1605** [comment]
I think everything is added from the original issue so I will close this.
