### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by ghost** [IrisShaders/Iris#100]
1. no block outline
2. items on the ground are really bright
all bugs happen with iris, no other mods,

if anyone knows a client side fix pls tell me or something

**Comment by OverlordsIII** [comment]
A lot of features of Iris are missing/not working

**Comment by itsbumble** [comment]
> 
> 
> A lot of features of Iris are missing/not working

makes sense

**Comment by Dragon-Seeker** [comment]
What Shaders pack are you currently using with Iris?

**Comment by coderbot16** [comment]
Closing this because I think these issues have been fixed, but it is not possible to verify this or investigate further given the lack of information (and the fact that the issue reporter deleted their account)
