### ISSUE TITLE
Minecraft Transit RailWay Mod : RailWay Display error

### ISSUE THREAD

**Issue by APPo1102** [IrisShaders/Iris#1007]
### What happened?

Hello, I very like iris mod and shaderpack. But When I play Minecraft Transit RailWay mod, I got a Bug is Display Error,Just like screen shot.I hope I can use iris shader to build my own railways, So if you see this bug report, Please fix this error!Very Thank!

### Screenshots

![image](https://user-images.githubusercontent.com/95098057/143614762-c54830c2-205b-43df-9cc1-928287d7c7aa.png)
![image](https://user-images.githubusercontent.com/95098057/143614797-f2b2360f-c1c5-438f-b8df-d7155bcc7050.png)
![image](https://user-images.githubusercontent.com/95098057/143614819-1145315c-b261-4d68-ae3a-17615fbaa09b.png)

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1080

### Java Version

Java 17.0.1

**Comment by NoComment1105** [comment]
Could you provide a full mods list please?

**Comment by NoComment1105** [comment]
Actually from looking at source the fix is to install [indium](https://modrinth.com/mod/indium/version/uTvfCUBM)

**Comment by APPo1102** [comment]
Sure my mod list is here!
![image](https://user-images.githubusercontent.com/95098057/143616950-2c19f762-655f-4275-923f-a9be041c0c52.png)
![image](https://user-images.githubusercontent.com/95098057/143616964-475db8d1-0b88-4394-a1c4-c22a4caa4449.png)
![image](https://user-images.githubusercontent.com/95098057/143616982-2f859178-d237-40e9-9c98-9164c565c892.png)
![image](https://user-images.githubusercontent.com/95098057/143617004-c8daf998-62f0-419f-95da-14f7d48b72f6.png)
![image](https://user-images.githubusercontent.com/95098057/143617019-0eb35cc1-e738-40c5-bb9f-fe942072ea63.png)
![image](https://user-images.githubusercontent.com/95098057/143617033-8dcbec4e-a76b-4808-a6ee-34c72a977301.png)



And indium I was already install, So mabye not that reason. I'm sorry.

**Comment by NoComment1105** [comment]
Strange

**Comment by NoComment1105** [comment]
Can you try with Sodium only?

**Comment by APPo1102** [comment]
Sure I will try it now !

**Comment by APPo1102** [comment]
You mean Only Sodium and Transit Railway right? Without IRIS?

**Comment by NoComment1105** [comment]
Yes. Regular sodium can be found [here](https://modrinth.com/mod/sodium/version/xuWxRZPd)

**Comment by APPo1102** [comment]
![image](https://user-images.githubusercontent.com/95098057/143617683-09f49907-24e1-4997-a650-07029b269e2e.png)
I try it and it normal.

**Comment by APPo1102** [comment]
I try it and it normal!
![image](https://user-images.githubusercontent.com/95098057/143617757-e997f0c7-1371-42bd-85bb-c42a159f671d.png)

**Comment by NoComment1105** [comment]
And it's not normal with iris?

**Comment by APPo1102** [comment]
Yes,it not  normal with iris. 
![image](https://user-images.githubusercontent.com/95098057/143617901-69bedfa5-2368-4e4c-af8d-850f8b3e1f11.png)

**Comment by APPo1102** [comment]
You can see the railway is flying! Amazing!
![image](https://user-images.githubusercontent.com/95098057/143617964-98d87fab-e3f9-4721-b66e-1bbb0b8a9ca0.png)
And if I use !1 to hide my menu, it will invisible like this 
![image](https://user-images.githubusercontent.com/95098057/143618008-19469c19-2901-4e59-998e-e976cded7f1d.png)

**Comment by NoComment1105** [comment]
Ok thanks this will need further debugging 👍🏼

**Comment by APPo1102** [comment]
OK! I will waiting for your good news! Very Thank You! Have a nice day!

**Comment by IMS212** [comment]
Seems to be fixed in the newest release, please reopen if you still have issues.
