### ISSUE TITLE
Distant black silhouette where fog should be. 

### ISSUE THREAD

**Issue by Tenchei** [IrisShaders/Iris#1008]
### What happened?

Applied VanillAA in the nether with night vision and it creates a black silhouette in the distance.

### Screenshots

![image](https://user-images.githubusercontent.com/95105013/143645930-375ede8f-5f8a-4298-8046-def94704d581.png)

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9 for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 3090

### Java Version

Java 16

**Comment by maximumpower55** [comment]
this is a shaderpack bug not a iris bug

**Comment by maximumpower55** [comment]
can you test on optifine to make sure

**Comment by maximumpower55** [comment]
this will be fixed in the next release

**Comment by coderbot16** [comment]
Fixed in 1.1.3
