### ISSUE TITLE
Crash on world load 1.17.1

### ISSUE THREAD

**Issue by SirKillz** [IrisShaders/Iris#1009]
### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build9 for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Geforce RTX 2070 Super

### Java Version

Java 16

### Reproduction Steps

1. Launch Game 
2. Create new world or select an existing world 
3. Game crashes after world load and immediately says "saving"
[crash-2021-11-27_16.42.20-client.txt](https://github.com/IrisShaders/Iris/files/7612546/crash-2021-11-27_16.42.20-client.txt)

**Comment by AlsoSylv** [comment]
Does the world load in vanilla?
Which shader?
Which launcher?

**Comment by SirKillz** [comment]
The world does load in vanilla.  I am using the default vanilla MC launcher, and I have not even installed a shader as the game crashes prior to actually loading into the world.

**Comment by AlsoSylv** [comment]
Does this happen when running optimize world?
Does this happen when creating a new world?
If first two are no and yes respectively, does it crash with normal sodium?
https://modrinth.com/mod/sodium

**Comment by SirKillz** [comment]
Does not matter if I load a new world or try to join an existing world, the game crashes the same way.  Normal sodium works fine.

**Comment by SirKillz** [comment]
I apologize.  I did not realize this instance was utilizing an old directory and somehow loaded an old unsupported shaderpack I did not even realize I had installed.  I create a fresh install directory with no shaderpacks and the worlds now load and create fine.

**Comment by AlsoSylv** [comment]
No worries! Just glad we could help resolve the issue :)
