### ISSUE TITLE
Weird rendering of debris with physics mod

### ISSUE THREAD

**Issue by maxigator** [IrisShaders/Iris#102]
**ONLY WHEN USING SODIUM COMPAT OR RENDER LAYERS**
Using sodium-compat + sodium (iris fork)
![2021-02-07_17 39 25](https://user-images.githubusercontent.com/22241832/107153237-aaed6080-696c-11eb-875c-e4231c589310.png)

Using render layers:
![2021-02-07_17 43 43](https://user-images.githubusercontent.com/22241832/107153243-b50f5f00-696c-11eb-95bb-7e977fd1ef9a.png)

Using trunk:
![2021-02-07_17 45 58](https://user-images.githubusercontent.com/22241832/107153250-bccf0380-696c-11eb-852e-e73ec30cb98f.png)

**Comment by maxigator** [comment]
But when killing animals with the mod installed and on trunk branch:
![2021-02-07_17 49 57](https://user-images.githubusercontent.com/22241832/107153284-f7d13700-696c-11eb-8f75-a06199af7ae5.png)

**Comment by coderbot16** [comment]
Based on inspecting the code, PhysicsMod is doing its rendering at the end of the rendering of the SOLID terrain layer. This is not at all what Iris expects and obviously causes some problems.

With the current way that PhysicsMod is implemented, it's hard for Iris to tailor a fix for it specifically, but there's probably some better approaches that I could take with regards to mods rendering stuff unexpectedly in general.

**Comment by coderbot16** [comment]
I will attempt a workaround, but since the mod is [closed source and no longer supported by the author](https://github.com/haubna/PhysicsMod), it is not a high priority.

> This mod is no longer maintained. No bugs will be fixed or new features added.
>
> No I will not release the source code. No you are not allowed to use the code and update/maintain it for future/present/past versions of Minecraft. It's not your code, get over it. This is the official bug report site for the Physics Mod on https://www.curseforge.com/minecraft/mc-mods/physics-mod

For the record, I'm not really a big fan of the attitude of the developer, but not much you can do there. Maybe someone will make a replacement with nicer licensing.

**Comment by coderbot16** [comment]
This has been fixed in https://github.com/IrisShaders/Iris/commit/f9159f4e93db11ba6e151eda7694cd02b69ea3f7
