### ISSUE TITLE
Some legacy texture functions are not patched for 1.17

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#1022]
For example, spectrum tries to reference texture3D, which is not supported, causing a compilation failure.

A more complete list is available in this comment: https://github.com/IrisShaders/Iris/issues/775#issuecomment-902966277

**Comment by IMS212** [comment]
Most of these should be added in 1.2.

**Comment by coderbot16** [comment]
1.2.0 is now released, containing most of these functions. Any more should be added in a separate issue.
