### ISSUE TITLE
Player shadow isn't visible when using tweakeroo freecam, and item in player's hand renders while in freecam.

### ISSUE THREAD

**Issue by Sup2303** [IrisShaders/Iris#1036]
### What happened?

1. Install Iris, Sodium, Tweakeroo and Malilib.
2. Enable shaders and freecam.
3. Player shadow isn't visible and items in player's hand render.

### Screenshots

![2021-12-01_16 23 04](https://user-images.githubusercontent.com/77088287/144222467-728f6b9b-0a82-404a-b437-3fddd5a84c1b.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.3 Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1650

### Java Version

Java 16

**Comment by maximumpower55** [comment]
Im pretty sure this is not something iris can fix, tweakeroo will need to set the renderHand variable to false in GameRenderer when freecam is active to fix this

**Comment by coderbot16** [comment]
The https://github.com/hashalite/Freecam mod works with Iris without issues, I suggest using that instead of the Tweakeroo freecam feature. Thanks for the report, but I don't think this is fixable on our side.
