### ISSUE TITLE
Blackscreen for unsupported shaders

### ISSUE THREAD

**Issue by thevicraft** [IrisShaders/Iris#1048]
### What happened?

When i tried to load an unsupported shader, it was BQL, then my pc turned into a blackscreen and i had to unplug it. :(

### Iris and Minecraft Version

iris-mc1.18-1.1.3

### Are you running Sodium along with Iris?

Yes

### Operating System

Debian 10

### What is your GPU?

Intel® UHD Graphics 630 (Coffeelake 3x8 GT2)

### Java Version

11

**Comment by NoComment1105** [comment]
well that's because the shader is currently unsupported, therefore, we will not provide support until the shader is supported
