### ISSUE TITLE
Request: Fix vanilla AO bug with resource packs (bug does not occur with OptiFine)

### ISSUE THREAD

**Issue by Khytwel** [IrisShaders/Iris#1049]
![image](https://user-images.githubusercontent.com/54046029/144714250-dd0a5446-6baf-44cf-a89a-c7bfc4a13040.png)

I know OptiFine fix this problem of the vanilla AO shader. I already spoke with the owner of Complementary Shaders, it could be fixed but ruin the visual quality, so it is not a viable solution. I think it could be useful for Iris to fix this problem directly from the source and that it can benefit to the maximum of the users in the case where it would use resource packs that brings 3D to some elements.

Iris 1.1.3 for Minecraft 1.18 and for the resource pack used it's [Fantasy Ores](https://www.curseforge.com/minecraft/texture-packs/fantasy-ores-by-cesarzorak)

**Comment by coderbot16** [comment]
Moved to Sodium's repository: https://github.com/CaffeineMC/sodium-fabric/issues/1396
