### ISSUE TITLE
Iris sodium compatibility crash on startup

### ISSUE THREAD

**Issue by FlamingScar** [IrisShaders/Iris#105]
iris alone does not crash, neither does sodium alone
heres my crash report
[crash-2021-02-08_17.22.50-client.txt](https://github.com/IrisShaders/Iris/files/5947165/crash-2021-02-08_17.22.50-client.txt)

**Comment by OverlordsIII** [comment]
You are compiling with a higher jdk than you are running minecraft with. Make sure you are compiling with a JDK 8.

**Comment by FlamingScar** [comment]
> You are compiling with a higher jdk than you are running minecraft with. Make sure you are compiling with a JDK 8.

thank you, everything is working nearly perfectly now, only thing i noticed was alot of stutter on the menu
