### ISSUE TITLE
[1.18] White line appears in the skyline using shaders

### ISSUE THREAD

**Issue by SirPonteos** [IrisShaders/Iris#1053]
### What happened?

So when i use any shader pack, old and new, a white line appears in the skyboxs. It only moves horizontaly with were you look. it's both there during day and night, and im not sure if there is a fixable solution or if its a version issue your already aware off.

### Screenshots

![2021-12-05_16 43 01](https://user-images.githubusercontent.com/95580632/144753593-52d4d5e9-e686-449f-ae92-c5b4371feefc.png)
![2021-12-05_16 48 37](https://user-images.githubusercontent.com/95580632/144753596-2b917ca8-1c03-4841-8e38-1941a6ba051a.png)
![2021-12-05_16 48 40](https://user-images.githubusercontent.com/95580632/144753597-2e917c95-83a1-4b9d-a78e-8f868bd2de0a.png)

### Iris and Minecraft Version

iris-mc1.18-1.1.3.jar for minecraft 1.18

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2070 Super

### Java Version

I think 1.18 uses Java 17 if im not mistaken

### Additional context

if any more additional info is needed, please let me know.

I'm not very experienced with getting in-game logs, so if you require them, just give me a crash course on how to.

Here is some additional images of my mods folder, shaders folder and fabric version.
![Udklip](https://user-images.githubusercontent.com/95580632/144753729-9874891b-0af2-486d-8014-2d499148ee79.PNG)
![Udklip](https://user-images.githubusercontent.com/95580632/144753738-a5f43f7d-8043-4d0e-a58f-c9ea5dad787b.PNG)
![Udklip](https://user-images.githubusercontent.com/95580632/144753779-90f51ee0-6a28-43db-813c-4af1355c1635.PNG)

**Comment by coderbot16** [comment]
Does this happen when playing in singleplayer? Does it disappear with a different render distance?

**Comment by TibiNonEst** [comment]
I myself first noticed this issue when playing on a server with a render distance of 6, with my client's render distance set to 16. I decided that it was worth investigating and these are the results of my experimenting:


### Testing Conditions
System: RTX 3060 Ti, Opengl 4.6, Nvidia Proprietary Driver 470.86, Ubuntu 21.10, Java 17.0.1 (OpenJDK)

Running: Minecraft 1.18.1, LWJGL 3.2.2, Fabric Loader 1.12.11

Mods: Iris 1.1.3 for 1.18.1, Sodium 0.4.0 alpha 5 build 9
*Default sodium settings except for: fullscreen, vsync turned off, max fps set to unlimited*

Shaders Tested:
- Complementary v4.3.2
- BSL v8.1.01
- Prismarine v4.0 Rewrite Stage 3
- Sildur's Vibrant v1.31 (all graphical versions)
- Sildur's Enhanced Default v1.13 (fast and fancy)
- SEUS Renewed
- SEUS PTGI E11 and E12
- SEUS PTGI HRR Test 2 and 2.1
- RedHat v34.0 Test 3
- YoFPS Performance Test 2
- Cyanide v1.0

Servers Tested:
- Vanilla 1.18.1
- Paper 1.18.1 build 68
- Fabric 1.18.1 v0.12.11


### General Observations
1) The "line" appears at its largest form as a rectangle when facing a verticle rotation of 0 degrees and a horizontal rotation of around 25, -25, 70, -70, 115, -115, 160, or -160
2) As you rotate the camera in a horizontal direction the "line" grows and shrinks in width, in a verticle direction and it distorts to a seemingly trapezoidal or triangular shape
3) Appears on Complementary, BSL, Prismarine, Seus Renewed (appears translucent), Seus PTGI (all versions), and RedHat
4) Only happens on server render distances 8 and below
5) I was not able to recreate the "line" appearing in a single player world for a "split second" when changing render or simulation distance


### Data
Taken from server render distances 2-8, test with all client render distances 2-32 with multiple (but not all) shaders each

Starting at a server render distance of **2**, the "line" appeared at a client render distance of **6**, and *grew in size until off-screen at 11*

**3**: **6**, *grew in size until off-screen at 11*
**4**: **8**, *grew in size until off-screen at 14*
**5**: **10**, *grew in size until 16*
**6**: **12**, *grew in size until 16*
**7**: **14**, *grew in size until 16*
**8**: **16**, *stayed the same size*

*Server render distances 9 and above did not have the "line"*


### Media
Both videos taken on a Paper server with a render distance of 5 using Complementary shaders

https://user-images.githubusercontent.com/37983572/145665787-4b8f917d-409f-4037-8a9b-576f5432a65c.mp4

https://user-images.githubusercontent.com/37983572/145665793-f46efb64-a522-49e4-9055-b95a54a40da7.mp4

**Comment by coderbot16** [comment]
Should be fixed by https://github.com/IrisShaders/Iris/commit/b66c7dd90dc1abf6f4da956f85cf1102f50dd219
