### ISSUE TITLE
Iris with shaders disabled in addition to Sodium causes a performance drop compared to just Sodium

### ISSUE THREAD

**Issue by theofficialgman** [IrisShaders/Iris#1059]
### What happened?

Comparing on 1.17.1. Test world with no entities present at all (all mobs killed, no item frames, no chests, etc)

sodium 0.3.3 (no iris), gpu usage is at 96% @ 921Mhz (cpu has headroom and can operate as low as 1.58Ghz without fps dropping, max frequency is 2.091Ghz)
resulting fps is 169fps stable

sodium 0.3.3 + iris 1.1.3, gpu usage also 96% @921Mhz (cpu has headroom and can operate as low as 1.58Ghz without fps dropping, max frequency is 2.091Ghz)
resulting fps is 150fps stable

so a 10% performance drop from just adding iris (no settings changed). It seems like iris must be creating additional gpu work (since the gpu is the bottleneck in both cases) even without any shaders present. I think users would expect that disabling shaders would make performance match sodium without iris but this is not the case.

Test system: (linux, nintendo switch - TX1 nvidia)

### Iris and Minecraft Version

iris-mc1.17-1.1.3.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Linux

### What is your GPU?

Nvidia Tegra X1 (maxwell based gpu)

### Java Version

Java 16

**Comment by coderbot16** [comment]
Iris does use the extended vertex format even with shaders disabled, so it would make sense that this could cause additional GPU load.

**Comment by AViewFromTheTop** [comment]
Can confirm for 1.18 as well. Sodium alone has great performance at a render distance of 24, but this is nearly halved when Iris is added (from about 120 to 60.) I also get noticeable when crossing chunk borders- I've tested this with Sodium alone, and it doesn't seem to be an issue.

**Comment by coderbot16** [comment]
@AViewFromTheTop Is that with shaders disabled? That seems like quite a different situation than the 10%-15% performance drop reported here.

**Comment by johalun** [comment]
I'm having extreme lag with sodium + iris (no shaders) on MC 1.18 (zulu aarch64 java jre + binaries built for apple silicon) and a M1 MacBook. Vanilla no problem, only sodium no problem, adding Iris = lots of lag, dropped frames etc. With only sodium I'm over 100 FPS most of the time at my mountain base, more on less demanding terrain.

**Comment by coderbot16** [comment]
@johalun Again, is that with shaders disabled?

**Comment by coderbot16** [comment]
Ah, I see, you stated that already. Sorry for the ping.

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop Is that with shaders disabled? That seems like quite a different situation than the 10%-15% performance drop reported here.

It was with shaders disabled. However, I was high above the ground and looking down, to gauge the impact more. When on the ground, it's much closer to a 10%-15% reduction like you said.

**Comment by AViewFromTheTop** [comment]
> > @AViewFromTheTop Is that with shaders disabled? That seems like quite a different situation than the 10%-15% performance drop reported here.
> 
> It was with shaders disabled. However, I was high above the ground and looking down, to gauge the impact more. When on the ground, it's much closer to a 10%-15% reduction like you said.

Ok, I've tested this again recently and it's randomly working perfectly again, with only a 10-15% decrease even while high up in the sky. Must've been my computer then, because I don't really know why it's acting different.

**Comment by coderbot16** [comment]
Please check if this is resolved on the `trunk` branch with the merge of https://github.com/IrisShaders/Iris/pull/1063. Note that this change hasn't been ported to 1.17/1.18 yet.

**Comment by coderbot16** [comment]
Thanks for the reports, we believe that this has now been resolved in `trunk`, `1.17`, and `1.18` with the above-mentioned fix, and that fix will be released in 1.1.4. Please let us know if the issue persists once 1.1.4 releases.
