### ISSUE TITLE
(1.18) World flickering at world border

### ISSUE THREAD

**Issue by EsserGaming** [IrisShaders/Iris#1066]
### What happened?

I teleported to the world border and then when I move my camera, the world starts flickering.

### Screenshots

List of mods:
![Screenshot 2021-12-07 154804](https://user-images.githubusercontent.com/36900138/145111653-8a1de25b-d271-44be-a3c7-936cb77b1b61.png)
Footage of the world flickering (with F3 open)
http://home.esser.fun/2021-12-07%2015-49-14.mp4

### Iris and Minecraft Version

iris-mc1.18-1.1.3.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD RX480

### Java Version

Java 17

**Comment by coderbot16** [comment]
Please test with just Sodium and without Iris.

**Comment by EsserGaming** [comment]
> Please test with just Sodium and without Iris. -@coderbot16 

Seems to also be flickering with sodium.. Where is the proper sodium repository that I should re-post this issue to?

**Comment by coderbot16** [comment]
https://github.com/CaffeineMC/sodium-fabric, but I believe that your issue has already been reported there.

**Comment by EsserGaming** [comment]
Man, GitHub is cool!
