### ISSUE TITLE
Having trouble building

### ISSUE THREAD

**Issue by RocketSauce28** [IrisShaders/Iris#108]
Im using gradlew to build and I get this error, what am I doing wrong?
**FAILURE: Build failed with an exception.

 What went wrong:
A problem occurred configuring root project 'sodium-fabric-1.16.x-iris'.
> Could not resolve all dependencies for configuration ':modCompile'.
   > Could not find net.coderbot.iris:iris:0.1.0.
     Searched in the following locations:
       - https://libraries.minecraft.net/net/coderbot/iris/iris/0.1.0/iris-0.1.0.pom
       - file:/C:/Users/rocke/.m2/repository/net/coderbot/iris/iris/0.1.0/iris-0.1.0.pom
       - https://jitpack.io/net/coderbot/iris/iris/0.1.0/iris-0.1.0.pom
       - file:/C:/sodium-fabric-1.16.x-iris/build/loom-cache/iris-0.1.0.jar
       - file:/C:/sodium-fabric-1.16.x-iris/build/loom-cache/iris.jar
       - file:/C:/sodium-fabric-1.16.x-iris/.gradle/loom-cache/remapped_mods/iris-0.1.0.jar
       - file:/C:/sodium-fabric-1.16.x-iris/.gradle/loom-cache/remapped_mods/iris.jar
       - https://maven.fabricmc.net/net/coderbot/iris/iris/0.1.0/iris-0.1.0.pom
       - https://repo.maven.apache.org/maven2/net/coderbot/iris/iris/0.1.0/iris-0.1.0.pom
       - https://jcenter.bintray.com/net/coderbot/iris/iris/0.1.0/iris-0.1.0.pom
       - file:/C:/sodium-fabric-1.16.x-iris/.gradle/loom-cache/1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2/iris-0.1.0.jar
       - file:/C:/sodium-fabric-1.16.x-iris/.gradle/loom-cache/1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.1-v2/iris.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by IMS212** [comment]
You need to place a compiled version of the sodium compatible version of iris in sodium-fabric\.gradle\loom-cache

**Comment by RocketSauce28** [comment]
I get this error when trying to build the iris compatibility
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.7.1/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Java\jre1.8.0_261\bin\java.exe -Xmx2G -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\rocke\.gradle\wrapper\dists\gradle-6.7.1-bin\bwlcbys1h7rz3272sye1xwiv6\gradle-6.7.1\lib\gradle-launcher-6.7.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.7.1
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

**Comment by IMS212** [comment]
Try restarting your computer

**Comment by RocketSauce28** [comment]
Same exact error shows up even after restart

**Comment by ImperatorStorm** [comment]
what command did you run to build it?

**Comment by JackDainzh** [comment]
want me to build it for you?

**Comment by SUPERN00Bthefirst** [comment]
You can find build versions of all branches in the actions tab [Here](https://github.com/IrisShaders/Iris/actions).

**Comment by rootalc** [comment]
Working build commands for Linux:

`
git clone -b sodium-compatibility https://github.com/IrisShaders/Iris
`
`
cd Iris && ./gradlew build
`
`
git clone https://github.com/IrisShaders/sodium-fabric
`
`
cd sodium-fabric && ./gradlew build; cp -v ../build/libs/iris-?.?.?.jar ./.gradle/loom-cache/*net.fabricmc.yarn*/ && ./gradlew build
`
`mkdir ~/Iris_Build && cp -v ../build/libs/iris-?.?.?.jar ~/Iris_Build/ && cp -v ./build/libs/sodium-fabric-mc*-IRIS-SNAPSHOT.jar ~/Iris_Build/
`

**Comment by infraispog** [comment]
> want me to build it for you?

I'm getting the same error, would you mind doing it for me as well?

**Comment by JackDainzh** [comment]
> > want me to build it for you?
> 
> I'm getting the same error, would you mind doing it for me as well?

will do it as soon as I am online, that will be about tomorrow.

**Comment by JackDainzh** [comment]
there you can download the zip with the iris and sodium builds: 
https://dropmefiles.com/ebLnQ

**Comment by coderbot16** [comment]
The sodium fork requires a build of the iris sodium-compatibility branch in the mavenLocal repository. Make sure you run `./gradlew --stop` after compiling Iris if your computer does not have much RAM. Closing this for now since it's not an Iris bug.
