### ISSUE TITLE
SEUS Renewed, and other SEUS shaders, having frame drops when underwater. 

### ISSUE THREAD

**Issue by DieuDeGlace** [IrisShaders/Iris#1083]
### What happened?

When I use iris+sodium I experience framerate drops underwater, or near buildings with water in them (where you can look up to the sky while standing below the top i.e. Fish tanks in homes. 

BSL, Complementary, and Sildurs do not seem to replicate this issue. I will assume its possibly just due to SEUS code being a pain and nothing more; however, if there is an issue within iris then I want to make this issue known.

### Screenshots

![2021-12-12_04 08 24](https://user-images.githubusercontent.com/47928395/145708455-39b9ade0-5157-4840-8637-9a7186952523.png)
![2021-12-12_04 08 31](https://user-images.githubusercontent.com/47928395/145708457-0e027517-edce-4fc8-b221-20995f238bb5.png)
![2021-12-12_04 08 35](https://user-images.githubusercontent.com/47928395/145708461-654e6b04-e7f2-4241-a7df-c8e48776ab99.png)

### Minecraft Version

1.18

### Iris Version

iris-mc1.18.1-1.1.3.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1660

### Java Version

Java 8 (JAVA_17 according to logs)

**Comment by DieuDeGlace** [comment]
For some reason the images didnt show framerates. Top image was at 40FPS, the other two were at 60FPS (capped to 60 to conserve some energy on my GPU)

**Comment by coderbot16** [comment]
I think it's unlikely that this is an Iris issue as opposed to a SEUS problem (and one that we can't really do anything about at that).

**Comment by DieuDeGlace** [comment]
Well has the problem been reported before? or is it a new one that popped up?

**Comment by coderbot16** [comment]
I haven't seen the problem before, but it's worth testing on OptiFine to see if you see similar results. Iris doesn't have much control over the effects the shader pack implements and it's likely that SEUS is implementing some slow underwater effects that lower your FPS.

**Comment by DieuDeGlace** [comment]
on optifine the issue doesnt exist. Though seeing how SEUS' underwater effects are buggy on iris ill assume its something that optifine utilizes to do underwater stuff that iris currently does not.

**Comment by DieuDeGlace** [comment]
Seems the latest 1.18 build of iris (build failed on my end but made a prenull.jar that worked?) that was made 1 hour ago, fixed the frame drops.

**Comment by coderbot16** [comment]
Good to know that it's fixed in development, I'll admit that I don't know what we committed that would fix that.

**Comment by DieuDeGlace** [comment]
unsure either lol. If it pops up again ill be sure to mention it.
