### ISSUE TITLE
No correct texture in mod

### ISSUE THREAD

**Issue by Vooxsu** [IrisShaders/Iris#1084]
### What happened?

Hi,
I have been playing Tech Reborn mod for several months and I found a small issue.
When i play without Iris and Soudium mods a textures be ok.

It happens in REI, Inventory, and Creative Inventory

### Screenshots

This in witch Iris and soudium instald.
![image](https://user-images.githubusercontent.com/82597391/145717935-f66f6062-e45b-4ded-83e9-f7d670aae8ea.png)
And this hapend when i'm uninstall Iris and soudium:
![image](https://user-images.githubusercontent.com/82597391/145718081-b5667d64-549f-426d-a948-15e22ebd55e2.png)

### Minecraft Version

from 1.17.1 to now 1.18.1

### Iris Version

1.1.3

### Sodium Version

Current and previous versions: sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

win 10 and win 11

### What is your GPU?

RTX 2080 Super

### Java Version

Current Java 16

### Additional context

- install tech reborn mod
- install Iris and soudium mods
- Run game
- look at the cells and buckets with fluids

I have information that you may not implement the Fabric Rendering API that they used to render dynamic cells and buckets.

**Comment by AlsoSylv** [comment]
Indium is required to use tech reborn with sodium https://modrinth.com/mod/indium

**Comment by Vooxsu** [comment]
It is work fin Thanks :)
