### ISSUE TITLE
Shaders break when too far from x=0 z=0

### ISSUE THREAD

**Issue by MrKoroshiya** [IrisShaders/Iris#1088]
The further away you get from the center of the world, the more the shaders break (applicable for all shaders tested: Sildur's Vibrant, BSL, Complementary).

Water texture rendering fails, waving foliage flickers and blocks stutter when moving.
It looks like the rendering engine loses precision as coordinates get higher.

This did not happen in 1.17.1.
All shaders work as intended in the same conditions using OptiFine.

Screenshot of the issue: https://imgur.com/uIxqU56

**Comment by MrKoroshiya** [comment]
Also, this did not happen in 1.17.1.
Here's a screenshot: https://imgur.com/uIxqU56

**Comment by IMS212** [comment]
This is known and fixed in development builds.

**Comment by MrKoroshiya** [comment]
Duplicate of https://github.com/IrisShaders/Iris/issues/334 and https://github.com/IrisShaders/Iris/issues/423
