### ISSUE TITLE
Iris with sodium compatible crash on startup game

### ISSUE THREAD

**Issue by tengfong00** [IrisShaders/Iris#109]
I tried compile the mod by myself and download from actions. Still, it crashes at startup and the crash report is totally same.

Minecraft version: 1.16.5
Fabric Loader: 0.11.1
Installed Mod :-
  Fabric API 0.30.3+1.16
  Iris Sodium Comptability 0.1.0
  sodium-fabric-mc1.16.3-0.1.0
  
Crash Report: 
[crash-2021-02-17_16.27.56-client.txt](https://github.com/IrisShaders/Iris/files/5994299/crash-2021-02-17_16.27.56-client.txt)

**Comment by tengfong00** [comment]
So I didn't install custom fork of sodium, and I build and put into `mod` folder.
Now there is a new issue came out. 
It runs and it can loading but it crashes when it is finish loading and tries to go into the game menu.
I'm not good at reading the crash report.
At least for me, it seems like it didn't have a mod conflict.

I update the info here
Minecraft version: 1.16.5
Fabric Loader: 0.11.1
Installed Mod :-
Fabric API 0.30.3+1.16
Iris Sodium Comptability 0.1.0
sodium-fabric-mc1.16.4-IRIS-SNAPSHOT

[crash-2021-02-17_18.01.08-client.txt](https://github.com/IrisShaders/Iris/files/5994838/crash-2021-02-17_18.01.08-client.txt)

**Comment by tengfong00** [comment]
I also tried the 1.16.4 and I get console log rather than crash report.
I compare between 1.16.5 and 1.16.4 console log.
Seems like this two version got different error
1.16.4 console log:
https://0bin.net/paste/ocUzcOwU#5HqcME6dYrpKs1RlKlhHdcSQ3DAtB1GDknMcTxhRWDD

1.16.5 console log:
https://0bin.net/paste/AHZYpliy#ZI9i-+ZDd+cKotN8ES4rlUVgpJOlKhRhZ36O//N30AE

Here is the 1.16.4 info
Minecraft version: 1.16.4
Fabric Loader: 0.11.1
Installed Mod :-
fabric-api-0.29.3+1.16
Iris Sodium Comptability 0.1.0
sodium-fabric-mc1.16.4-IRIS-SNAPSHOT

**Comment by coderbot16** [comment]
This is an upstream issue in Sodium that is caused by trying to compile it on a newer Java version than you're running with. If you're running with Java 8 you must compile Sodium with Java 8 too.

**Comment by tengfong00** [comment]
Ok, Thank you. 
Doesn't know why that AdoptOpenJDK didn't replace my JAVA_HOME and still using the newer version of JDK.
Now it is been fixed. Thank you for solving my issues.

**Comment by CraftalotReloaded** [comment]
Overwriting the JAVA_HOME is an option that is by default disabled when installing AdoptOpenJDK

**Comment by coderbot16** [comment]
No problem!

**Comment by SpottyTheTurtle** [comment]
I know this is months later but just wondering, how did you find/get the Iris sodium compatability and IRIS-SNAPSHOT jars? I built the default branch of both but iris throws an error asking for sodium IRIS-SNAPSHOT...
