### ISSUE TITLE
Emmisive Texture Support

### ISSUE THREAD

**Issue by IntoTheVoid-900** [IrisShaders/Iris#1099]
**Is your feature request related to a problem? Please describe.**
There is no Optifine format emmisive texture mods for Fabric. The closest are Continuity (which adds Optifine connected textures) and CTM Fabric (which implements a different format). [When I requested the devs of Continuity](https://github.com/PepperCode1/Continuity/issues/7) implemented emmisive textures, they said they were unable to due to API limitations. With how Iris already works, I think that it can bypass the limitations that the devs mentioned.

**Describe the solution you'd like**
I would like Iris to add support for Optifine Emmisive textures.

**Describe alternatives you've considered**
Using CTM Fabric texture packs.

**Comment by AlsoSylv** [comment]
Iris can not get around these limitations, it would still need to use the same APIs to do what Continuity wants to wait to do properly.
