### ISSUE TITLE
sodium compatibility version crashes on launch

### ISSUE THREAD

**Issue by infraispog** [IrisShaders/Iris#110]
[crash reports](https://github.com/IrisShaders/Iris/files/5998592/crash-2021-02-17_20.57.04-client.txt)
i've seen other people report this issue, but I have compiled and used the same java version (java 15) to run fabric however I can't get it to work. I also can't get the sodium version specifically for iris to compile.

Can anyone help?

EDIT: for the time being, I've decided to use it without sodium, but my shaders won't load

**Comment by OverlordsIII** [comment]
You need to compile a new fork of sodium along with the sodium compat branch of iris

**Comment by infraispog** [comment]
thanks! it works

still confused how to change it off of internal shaders though, can you help?

**Comment by OverlordsIII** [comment]
Edit .minecraft/config/iris.properties and put shaderPack to equal the name of the folder with the shaderpack inside your shaderpacks dir with spaces and .zip if there

**Comment by infraispog** [comment]
thanks for your help!
