### ISSUE TITLE
Entities, items, and players flicker when using iris shaders+shadows with Physics Mod

### ISSUE THREAD

**Issue by wackiestwow** [IrisShaders/Iris#1104]
### What happened?

Whenever I turn on shadows using shaders (bsl, complementary, and sildurs were all tested), entities, items, and players flicker in and out of existence. This is a major drawback in my survival worlds because chests and anything else that is considered an entity is affected. When I use optifine, the shadows work fine. (took me a while to get good screenshots, as it is a very fast flickering)

Steps:

1: turn on sodium and iris

2: turn on shaders

3: enable shadows

4: travel around, and artifacts appear

### Screenshots

![2021-12-16_15 46 38](https://user-images.githubusercontent.com/95980287/146466211-2f2f7bf6-31ce-4a05-b4c5-fffa18245244.png)
![2021-12-16_15 59 18](https://user-images.githubusercontent.com/95980287/146466454-2f28adcb-32fa-4790-b23e-bcd3b0f13268.png)
![2021-12-16_15 59 41](https://user-images.githubusercontent.com/95980287/146466463-2baeb344-0ddf-4b2f-926c-7c79c40953e6.png)

### Minecraft Version

fabric-0.12.11-1.18.1

### Iris Version

iris-mc1.18.1-1.1.4

### Sodium Version

sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.828

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 650

### Java Version

Java 16

**Comment by IMS212** [comment]
Does this happen with no other mods installed? If so, does this happen with Iris 1.1.3?

**Comment by wackiestwow** [comment]
> Does this happen with no other mods installed? If so, does this happen with Iris 1.1.3?

i never thought of it being a conflicting mod, when i removed everything except sodium and iris, it worked fine. thanks for opening my eyes! (sorry if i wasted your time XD)

**Comment by wackiestwow** [comment]
update: it seems physics mod was the issue

**Comment by haubna** [comment]
I assume that this issue is caused by my mod as well. It basically thinks it has the right buffers bound right in this function: BufferUploader.updateVertexSetup which it doesn't have anymore. Seems like a bad practice from Mojang though when there is the GlStateManager._glBindBuffer function which can be called from anywhere else and it doesn't update the local variables of BufferUploader.

**Comment by coderbot16** [comment]
Is this still an issue?

**Comment by haubna** [comment]
Fixed it a while ago! Sorry for not posting it here :o

coderbot ***@***.***> schrieb am So. 6. März 2022 um 20:57:

**Comment by coderbot16** [comment]
Great, thanks for letting me know!

**Comment by O-d-i-n-n** [comment]
I'm not using Physics Mod but this still happens to me.
