### ISSUE TITLE
black world on sodium compatibility - sildurs vibrant extreme vl, extreme and high

### ISSUE THREAD

**Issue by infraispog** [IrisShaders/Iris#111]
when i load up the game with any of the above shaders, my world is black, except for rain, sky and the sun. can anyone help?

**Comment by coderbot16** [comment]
I'll need an F3 screenshot and a log to debug this further, also try this on the latest version of Iris.

**Comment by thedocruby** [comment]
Seems to work relatively fine for me as of the latest merge from trunk, even with quite a few mods installed that mess with rendering.

**Comment by coderbot16** [comment]
Without more information, there is nothing that I can do. If you send an F3 screenshot or similar, I can reopen this issue.
