### ISSUE TITLE
Game Crashes After Loading a World

### ISSUE THREAD

**Issue by Jurgio** [IrisShaders/Iris#1110]
As title says.

Crash logs:
[crash-2021-12-19_00.05.50-client.txt](https://github.com/IrisShaders/Iris/files/7740052/crash-2021-12-19_00.05.50-client.txt)
[latest.log](https://github.com/IrisShaders/Iris/files/7740053/latest.log)

**Comment by IMS212** [comment]
Please update Iris to the 1.18.1 version (the Sodium 1.18 alpha5 is still compatible).
