### ISSUE TITLE
Cannot read field "field_3911" because "this.field_4015.field_1724" is null

### ISSUE THREAD

**Issue by Levelowel** [IrisShaders/Iris#1118]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.1.4-pre+rev.8fec09c.jar

### Sodium Version

sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.835(rev.540d27b).jar

### Operating System

Linux

### What is your GPU?

NVIDIA GeForce RTX 2070

### Java Version

Java 17.0.1

### Reproduction Steps

1. Download or build the latest version of Sodium for 1.18.1
2. Build the latest version of Iris for 1.18.1
3. Launch Minecraft
4. Join a world (both singleplayer and multiplayer crash after a while)

### Crash Report file and latest.log

```shell
https://gist.githubusercontent.com/Levelowel/8ebd191735130bfa309210c585f42b63/raw/ca68eb0edb8747309c619cb9152f90839e4d8f9f/crash-2021-12-20_13.21.46-client.txt

https://gist.githubusercontent.com/Levelowel/8ebd191735130bfa309210c585f42b63/raw/ca68eb0edb8747309c619cb9152f90839e4d8f9f/latest.log
```

### Additional context

Oh and the sodium build also works completely fine without Iris

**Comment by AlsoSylv** [comment]
Github action builds of sodium are not supported, only the latest release.

**Comment by Levelowel** [comment]
Well, it works with Sodium 0.4.0-alpha5+build.9, but I'm pretty sure the conflict is caused by Iris and not Sodium. I guess I will close this issue for now and wait until one of the developers notices this
