### ISSUE TITLE
Mods don't load when using Iris as a standalone installation

### ISSUE THREAD

**Issue by W1ll-Du** [IrisShaders/Iris#1119]
### What happened?

I have mods in the mods folder that dont load using the Iris+sodium installation(0.12.11), but they load with the normal fabric loader(0.12.12)
(1.18.1)

### Minecraft Version

1.18.1

### Iris Version

fabric 0.12.11-1.18.1

### Sodium Version

whatever came with iris

### Operating System

win10

### What is your GPU?

intel hd graphics 620

### Java Version

java 17

**Comment by IMS212** [comment]
This is intended, you must click “Install as Fabric mod” to use other mods.
