### ISSUE TITLE
Don't have permission

### ISSUE THREAD

**Issue by KyleUltimate** [IrisShaders/Iris#112]
![image](https://user-images.githubusercontent.com/68589851/108468066-23371880-72c1-11eb-82e3-d420c230c8bf.png)

**Comment by KyleUltimate** [comment]
![image](https://user-images.githubusercontent.com/68589851/108468132-3ba73300-72c1-11eb-813e-8923383b8039.png)
I already try this.

**Comment by yitzy299** [comment]
"We do not provide support for users who cannot compile the mod themselves"

**Comment by coderbot16** [comment]
Use `./gradlew --stop` after `./gradlew build` to avoid this issue (https://github.com/FabricMC/fabric-loom/issues/369)

**Comment by KyleUltimate** [comment]
to be fair, that rule isn't on the readme when I wrote that

**Comment by TehcJS** [comment]
> to be fair, that rule isn't on the readme when I wrote that

@KyleUltimate It’s on the discord guild.

**Comment by KyleUltimate** [comment]
no.
that rule is written on march first

**Comment by KyleUltimate** [comment]
I commented this on Feb. 19

**Comment by AlsoNiko** [comment]
There's no point in arguing on a closed issue.
