### ISSUE TITLE
[Request] Add some opacity to the buttons on the upcoming GUI

### ISSUE THREAD

**Issue by TBlazeWarriorT** [IrisShaders/Iris#1123]
![transp](https://user-images.githubusercontent.com/25572454/147122151-486469fe-c6d3-4543-8ba0-075399f8fac2.gif)
Hi, if possible, please make the Iris UI buttons darker, I think most people will agree they will look nicer and be significantly more readable with that, otherwise users might have issues in the future on bright backgrounds.
The GIF above should make a comparison of how it is and how it could be
_(Got the screenshot from someone else just as an example and edited it in paint, don't mind it too much)_

**Comment by enagimintas** [comment]
Why using my screenshot XD?

**Comment by TBlazeWarriorT** [comment]
> Why using my screenshot XD?

I assume you're Coder? It was the screenshot that originated the discussion about the UI on the Complementary server and it was the easiest one for me to yoink, so why not?

**Comment by enagimintas** [comment]
Yes, Im Coder, but that was a joke lmao

**Comment by DieuDeGlace** [comment]
how did you even get the shaders option menu? or is this just one of those idea things

**Comment by TBlazeWarriorT** [comment]
> how did you even get the shaders option menu? or is this just one of those idea things

it's being privately tested by the iris developers and admins (not me)

**Comment by DieuDeGlace** [comment]
ah i see.

**Comment by enagimintas** [comment]
> how did you even get the shaders option menu? or is this just one of those idea things

I made this screenshot from dev build of Iris. This build is tested by some of Iris stuff, so I had acess to it

**Comment by coderbot16** [comment]
Opacity has been added, thanks for the suggestion.
