### ISSUE TITLE
java.util.NoSuchElementException: null when joining any world

### ISSUE THREAD

**Issue by FlappyTheBats** [IrisShaders/Iris#1124]
### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18-1.1.3.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Manjaro KDE (Kernel: Linux 5.15.7-1 / linux515)

### What is your GPU?

AMD Radeon HD 7770

### Java Version

Java 17 (openjdk)

### Reproduction Steps

1. Start the game with Iris installed
2. Join any world (singleplayer or multiplayer)
3. Game crashes (even with shaders disabled)

### Crash Report file and latest.log

```shell
latest.log - https://pastebin.com/NMsFdeRF
latest crash report - https://pastebin.com/N9fWsVzx
```

### Additional context

Launcher: MultiMC 5
Mods:
- Effective 1.0
- Fabric API 0.44.0+1.18
- ItemPhysic Lite 1.4.0
- Phosphor 0.8.1
- Physics Mod 2.5.18
- Sodium 0.4.0-alpha5+build.9
- Iris 1.1.3
- Xaero's Minimap 21.22.3.1

**Comment by IMS212** [comment]
Iris for 1.18 does not work in 1.18.1, please update.
