### ISSUE TITLE
Launching installer prompts a blank window on linux

### ISSUE THREAD

**Issue by kStor2poche** [IrisShaders/Iris#1128]
### **Description of the issue :** 
a white window pops up in place of the installer when executing the installer's jar file through bash

### **Steps to reproduce the issue :** 
- input "java -jar Iris-Installer-2.0.3.jar" in the command line in a wayland session (haven't tested if the issue is present when using X11) and press enter
- a blank window pops up

### **System specs :** 
- **OS :** arch linux with kernel 5.15.7-arch1-1
- **DE/WM :** wayland with sway (xwayland is installed for compatibility with x applications).
- **Shell :** bash 5.1.12

## screenshot of the aforementioned issue : 
![screenshot](https://user-images.githubusercontent.com/43518872/147353432-6415b539-b0c1-439c-9ab9-d32fe7396354.png)

Please tell me the steps I have to take in order to provide the information you need.

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris-Installer/issues/9

**Comment by kStor2poche** [comment]
Thanks, solved the issue !
