### ISSUE TITLE
Incompatible with Super Duper Vanilla Shaders (needs custom uniforms) 

### ISSUE THREAD

**Issue by crispytwig** [IrisShaders/Iris#1134]
### What happened?

When playing Super Duper Vanilla Shaders with Iris installed, everything has a dark blue tint and stars as if it's night 24/7. That's pretty much it. No crash logs or anything.

### Screenshots

![image](https://user-images.githubusercontent.com/48872606/147395057-47555bd5-d43f-411d-9e2d-d5c24dcf006a.png)

### Minecraft Version

Minecraft 1.18-1.18.1

### Iris Version

iris-mc1.18.1-1.1.4-rc1, but also applies to previous versions

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

Intel Iris XE Graphics

### Java Version

Java 17

**Comment by coderbot16** [comment]
Merging into the https://github.com/IrisShaders/Iris/issues/1030 mega-issue.
