### ISSUE TITLE
Crash upon joining Hypixel

### ISSUE THREAD

**Issue by PortalTrap-Git** [IrisShaders/Iris#1135]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.1.3.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Windows 10

### What is your GPU?

Intel(R) HD Graphics 520

### Java Version

Java 17

### Reproduction Steps

1. Install a particular [set of mods](https://pastebin.com/f2hn0Xfr)
2. Join `mc.hypixel.net`
3. Game crashes

### Crash Report file and latest.log

```shell
[Crash report](https://bytebin.lucko.me/8MEObfDk2x), [Latest log](https://pastebin.com/UXh16MQN)
```

**Comment by IMS212** [comment]
Please send a crash report without Not Enough Crashes.

**Comment by PortalTrap-Git** [comment]
[A crash report without Not Enough Crashes.](https://pastebin.com/xXCJMWN0)

**Comment by IMS212** [comment]
As I suspected, this is unrelated to Iris and is just NEC blaming Iris. However, a quick search on GH reveals SkinSwapper is the issue (relevant code: https://github.com/cobrasrock/Skin-Swapper/blob/f0f1ecbf10d118caf698f7bafe6026ef9eb16cb5/src/main/java/net/cobrasrock/skinswapper/mixin/MixinPlayerSkinProvider.java)
