### ISSUE TITLE
[MOD COMPATIBILITY] [Galaxies: Parzi's Star Wars Mod] Lightsabers are weird

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1137]
### What happened?

[MOD COMPATIBILITY] [Galaxies: Parzi's Star Wars Mod] Lightsabers are weird

https://user-images.githubusercontent.com/68275908/147412271-f3bbfa68-c76d-4ce0-a4c8-d6b62752b7a8.mp4

### Minecraft Version

Minecraft 1.18

### Iris Version

iris-mc-1.18.1

### Sodium Version

sodium 0.4 alpha 5

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by coderbot16** [comment]
Please test with the latest version of the Iris dev branch. The underlying issue might have been fixed relating to how the mod is rendering its light sabers:

https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/blob/a35726e86d9fb29c06ec51e4b34bb425716c5ff9/src/main/java/com/parzivail/pswg/client/render/entity/EnergyRenderer.java#L18

**Comment by coderbot16** [comment]
Fixed, continuum still has issues but it is probably a continuum bug or different Iris issue that will be fixed separately.
