### ISSUE TITLE
GL_ARB_geometry_shader4 isn't supported fully because the maxVerticesOut directive isn't supported

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#1155]
```
const int maxVerticesOut = 3;                   Set GEOMETRY_VERTICES_OUT_ARB for GL_ARB_geometry_shader4 
```

**Comment by coderbot16** [comment]
Test pack using this from builderb0y: [Geometry_hand_duplication.zip](https://github.com/IrisShaders/Iris/files/10476749/Geometry_hand_duplication.zip)

**Comment by IMS212** [comment]
To my knowledge, this has become obsolete and doesn't even work on Optifine anymore.
