### ISSUE TITLE
Optifine functions

### ISSUE THREAD

**Issue by 44wrw44** [IrisShaders/Iris#1157]
Good afternoon, please add a couple of functions from OpiFine.
By the type of texture by the name of the item and armor, otherwise when I put OpiFabric they conflict.

**Comment by CaioMGT** [comment]
Hello there, Iris only focuses on adding shaders to minecraft, other mods replace optifine's features. I would recommend you to look at this list of optifine replacements: https://lambdaurora.dev/optifine_alternatives/

**Comment by HarvelsX** [comment]
Iris is not intended for this, use https://github.com/SHsuperCM/CITResewn instead, like CaioMGT said, and please close issue.

**Comment by coderbot16** [comment]
Please see the FAQ: https://github.com/IrisShaders/Iris/blob/2f2fdba0eb2b9938d77c1ff45fd2a78d62e94932/docs/faq.md#will-insert-feature-part-of-optifine-be-added-to-iris
