### ISSUE TITLE
Background color issues below Water

### ISSUE THREAD

**Issue by Mithos23** [IrisShaders/Iris#116]
Disclaimer: This Issue was found on AMD with a modified version of Sildur's v1.281 medium with Shadows and TAA disabled in shaders.settings.

Here's a picture of the issue: 
![2021-02-21_02 59 17](https://user-images.githubusercontent.com/54249738/108633290-c596fd80-7473-11eb-9502-7328d0b0d230.png)

it can change color depending on your and the sun's angle:
![2021-02-21_03 00 14](https://user-images.githubusercontent.com/54249738/108633320-f1b27e80-7473-11eb-8b9c-dabf22bc0425.png)
However, it always seems to be one of these two colors.

Here's how it looks with Optifine using the same shaderpack:
![2021-02-21_18 30 25](https://user-images.githubusercontent.com/54249738/108633369-34745680-7474-11eb-80fa-c83885f4db4d.png)

**Comment by IMS212** [comment]
can confirm this is also on nvidia
