### ISSUE TITLE
DoF does not work in the nether

### ISSUE THREAD

**Issue by T3TT3T** [IrisShaders/Iris#1162]
### What happened?

DoF does not work in the nether

### Screenshots

![2022-01-03_23 11 25](https://user-images.githubusercontent.com/94024675/147940577-73fc6abe-6814-47f8-9d1e-d2d286f12abb.png)
![2022-01-03_23 10 05](https://user-images.githubusercontent.com/94024675/147940582-0ddc6d2c-4550-47a8-bb7f-430428a008f9.png)
![2022-01-03_23 10 31](https://user-images.githubusercontent.com/94024675/147940586-5db8ca03-bee2-405c-8433-1bdc8c8632fc.png)

### Minecraft Version

minecraft 1.18.1

### Iris Version

1.2.0 beta1

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

windows 11

### What is your GPU?

rtx 2080

### Java Version

java8

**Comment by IMS212** [comment]
Have you confirmed this does not happen on OptiFine?

**Comment by T3TT3T** [comment]
> Have you confirmed this does not happen on OptiFine?

same
that is shader bug sorry
