### ISSUE TITLE
Verify that image load/store actually works and didn't get broken while merging the PR

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#1166]
Use the following pack by BruceKnowsHow to test:

[image-test-shaders.zip](https://github.com/IrisShaders/Iris/files/7805567/image-test-shaders.zip)

**Comment by maximumpower55** [comment]
Works for me, latest trunk commit with sodium disabled
![2022-01-03_21 45 48](https://user-images.githubusercontent.com/62370320/148014886-9e2a09a6-7b94-4dd3-8c17-aa319e12b386.png)

**Comment by maximumpower55** [comment]
Works with sodium enabled too

**Comment by coderbot16** [comment]
Great, what about 1.17.x / 1.18.x? If those work too this can be closed & I can more confidently say that image load/store should work (aside from the lack of memory barriers which could cause some inconsistency) in the changelog.

**Comment by maximumpower55** [comment]
Works on the latest 1.17 commit with sodium disabled

**Comment by coderbot16** [comment]
Well, thats enough data for me. Thanks for testing!
