### ISSUE TITLE
Excessive OpenGL debug Log Spam when Figura is installed

### ISSUE THREAD

**Issue by dottiekh** [IrisShaders/Iris#1169]
### What happened?

With any shader pack enabled, the log files are constantly being spammed with this message:
`[Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'`

Apparently this has been stated to be a "fake error" in the Discord, however log files are being continuously spammed and filled with this text excessively, which greatly inflates the file size of stored logs. An option to either disable logging or a fix to the excessive spamming of these errors would be appreciated.

### Screenshots

![image](https://user-images.githubusercontent.com/34873184/148311192-1e4e9033-c2fa-49cd-ae96-0a82b75ca029.png)

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-rc2-1.1.3.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5build.9.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060

### Java Version

Java 17

**Comment by IMS212** [comment]
We'll need a debug log, can you replace your version of Iris with [this](https://cdn.discordapp.com/attachments/774354522361299006/928454031326732330/iris-mc1.18.1-1.1.4-rc2rev.ef0621c-dirty.jar) version and see if the issue is either A: fixed or B: has a more verbose log?

**Comment by dottiekh** [comment]
The issue persisted, and for some reason the saved log file is less verbose, only saying "[STDERR]: [LWJGL] OpenGL debug message". MultiMC's log has the full error however, but I am unable to upload it to pastebin. The OpenGL error is replaced with this now:
```[Render thread/INFO]: [STDERR]: [LWJGL] OpenGL debug message
	ID: 0x502
	Source: API
	Type: ERROR
	Severity: HIGH
	Message: GL_INVALID_OPERATION error generated. Depth formats do not match.
	Stacktrace: org.lwjgl.opengl.GL30C.glBlitFramebuffer(Native Method)
              net.coderbot.iris.gl.IrisRenderSystem.blitFramebuffer(IrisRenderSystem.java:73)
              net.coderbot.iris.rendertarget.FramebufferBlitter.copyDepthBufferContent(FramebufferBlitter.java:30)
              net.coderbot.iris.postprocess.FinalPassRenderer.renderFinalPass(FinalPassRenderer.java:177)
              net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.finalizeLevelRendering(NewWorldRenderingPipeline.java:579)
              net.minecraft.class_761.handler$znb000$iris$endLevelRender(class_761.java:6958)
              net.minecraft.class_761.method_22710(class_761.java:1563)
              net.minecraft.class_757.method_3188(class_757.java:1031)
              net.minecraft.class_757.method_3192(class_757.java:811)
              net.minecraft.class_310.method_1523(class_310.java:1117)
              net.minecraft.class_310.method_1514(class_310.java:733)
              net.minecraft.client.main.Main.main(Main.java:238)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
              net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
              net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              java.base/java.lang.reflect.Method.invoke(Method.java:568)
              org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
              org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
              org.multimc.EntryPoint.listen(EntryPoint.java:143)
              org.multimc.EntryPoint.main(EntryPoint.java:34)
```
If you need anything else let me know.

**Comment by IMS212** [comment]
That's what I was looking for, thanks!

**Comment by coderbot16** [comment]
How exactly does one reproduce this issue?

**Comment by dottiekh** [comment]
I have quite a few other fabric mods which may/may not contribute? A friend of mine has a different mod list and the issue persists with them as well and on a different launcher (Default MC Launcher vs my using MultiMC). Aside from that the only thing I really do is play the game. When shaders are enabled the debug message is spammed, when they're disabled it stops. Either way, here's my current fabric modlist:

AppleSkin (mc1.18-2.2.0)
CITResewn (0.8.1-1.18)
Figura (0.0.7-rc.8)
FirspersonModel (2.1.0)
Iris (1.1.3/1.1.4 jar given to me earlier)
Sodium (0.4.0-alpha5+build.9)
NotEnoughAnimations (1.4.0)
Server Pack Unlocker (1.0)
Xaero's Minimap/World Map (21.22.3.1 / 1.18.6.1)

**Comment by coderbot16** [comment]
If the issue does not happen with only Iris + Sodium installed, does it happen with just Iris + Sodium + Figura?

**Comment by TheNukeLore** [comment]
ya this is likely a figura issue, worked with one of the devs and they are currently fixing it

**Comment by ENinja33** [comment]
This issue was brought to my attention a little while ago; it was caused by a conflict between Iris and Figura, because I used a mixin to add a stencil buffer. I've written a fix where this mixin is ignored when you are currently using a shader pack in Iris. Hopefully that fix will be in one of the upcoming Figura pre-releases!

**Comment by dottiekh** [comment]
That's great to know, thanks! Would it also be at all possible to in the future reduce the amount of times the log is alerted to an OpenGL error? I think it's still important see those but just not 20 times a second or so.

**Comment by IMS212** [comment]
This is just OpenGL logging, not something we purposely control. We don't want to silence it.

**Comment by dottiekh** [comment]
Got it, thanks for the info!

**Comment by dottiekh** [comment]
Fixed as of Figura's https://github.com/Blancworks/Figura/commit/70f8971252ad530c82d223e50ddaa578e488544d. I'll go ahead and close the issue.

**Comment by rajm-art** [comment]
> We'll need a debug log, can you replace your version of Iris with [this](https://cdn.discordapp.com/attachments/774354522361299006/928454031326732330/iris-mc1.18.1-1.1.4-rc2rev.ef0621c-dirty.jar) version and see if the issue is either A: fixed or B: has a more verbose log?

For 1.20.1 ?
