### ISSUE TITLE
Blocks above water reflection get reflected when they shouldn't

### ISSUE THREAD

**Issue by Mithos23** [IrisShaders/Iris#117]
Disclaimer: This Issue was found on AMD with a modified version of Sildur's v1.281 medium with Shadows and TAA disabled in shaders.settings.

Example pic:
![2021-02-21_03 21 32](https://user-images.githubusercontent.com/54249738/108633890-1bb97000-7477-11eb-8d01-2e6639861d50.png)

Same location in Optifine:
![2021-02-21_03 32 54](https://user-images.githubusercontent.com/54249738/108633960-6cc96400-7477-11eb-9b90-a9a648f12287.png)

There are edge cases where it's possible to get similar reflection weirdness in OF as well, but not as bad as above.
Example of that in OF:
![2021-02-21_18 55 59](https://user-images.githubusercontent.com/54249738/108634056-190b4a80-7478-11eb-9ac2-57a5e0baa336.png)
Same  location in Iris:
![2021-02-21_18 55 48](https://user-images.githubusercontent.com/54249738/108634069-2aeced80-7478-11eb-9656-0b2c7274369b.png)

**Comment by Mithos23** [comment]
Since this doesn't seem to be fixed, here's a new screenshot and the world download:
![2021-03-01_22 29 48](https://user-images.githubusercontent.com/54249738/109562861-3c20a480-7adf-11eb-89a8-ed2a171dce47.png)
[New World.zip](https://github.com/IrisShaders/Iris/files/6064636/New.World.zip)

**Comment by coderbot16** [comment]
This should *actually* be fixed now. As it turns out, Sildur's Vibrant Shaders relies on internal implementation details of OptiFine (its modifications to the far plane)

I've tested with that world and the behavior now seems to match OptiFine.

**Comment by IMS212** [comment]
The majority of shader developers have decided it's time to move on from intentionally breaking vanilla behavior to support bad code. The workaround has been removed as of today, pending release in 1.6.10.
