### ISSUE TITLE
I am trying to install iris for 1.18.0 not 1.18.1 as our server uses 1.18.0, but the iris installer only has options for 1.16.1, 1.17.1 and 1.18.1, I need an option to install for  1.18.0. Please help me out my fps is soooo bad with optifine

### ISSUE THREAD

**Issue by digikage** [IrisShaders/Iris#1172]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IMS212** [comment]
We purposely do not support 1.18.1, due to it being generally unstable. You can join 1.18 servers with 1.18.1, however.

**Comment by chalkyjeans** [comment]
Don't quote me on this but I think 1.18.1 clients can join 1.18 servers (but it may be the other way around)
Also there's no reason to use 1.18 as a server because 1.18.1 patches a critical security bug

**Comment by DioEgizio** [comment]
Also if it doesn't there's multiconnect
