### ISSUE TITLE
crashed when I was killed by an enderman this mod and two others were potential causes in the log

### ISSUE THREAD

**Issue by Shadowdragon3456** [IrisShaders/Iris#1174]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

1.18.1

### Sodium Version

1.18.1

### Operating System

Windows 10

### What is your GPU?

NVidia Georce GTX 150

### Java Version

java for 1.18.1

### Reproduction Steps

I was just wondering in my world and fought a enderman and when i died the game crashed it said the potential causes were Satin, I ris and requiem (im on fabric).

### Crash Report file and latest.log

```shell
https://bytebin.lucko.me/Nz8tRK7zbW
```

**Comment by IMS212** [comment]
You'll need to update Satin.

**Comment by Shadowdragon3456** [comment]
> You'll need to update Satin.

satin is verison 1.18.1 aswell

**Comment by IMS212** [comment]
No, you have 1.7.0 while 1.7.2 has released. https://www.curseforge.com/minecraft/mc-mods/satin-api/files/3595997

**Comment by Shadowdragon3456** [comment]
> No, you have 1.7.0 while 1.7.2 has released. https://www.curseforge.com/minecraft/mc-mods/satin-api/files/3595997

oh thank you :)
