### ISSUE TITLE
Add support for VanillaPlus shaders

### ISSUE THREAD

**Issue by Pectacular** [IrisShaders/Iris#1177]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.1.4

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

Intel(R) UHD Graphics

### Java Version

Java 17.0.1

### Reproduction Steps

1. Download VanillaPlus shaders
2. Open shaders' selection screen
3. Enable VanillaPlus shaders
4. Enter a world
5. Game crashes

### Crash Report file and latest.log

```shell
https://bytebin.lucko.me/CxJYVLWEyI
```

**Comment by coderbot16** [comment]
Seems to have the same underlying cause as https://github.com/IrisShaders/Iris/issues/937 upon closer investigation.
