### ISSUE TITLE
Block breaking animation is lit incorrectly when near light sources (Iris 1.1.4, Sildur's Vibrant Shaders 1.32)

### ISSUE THREAD

**Issue by akemin-dayo** [IrisShaders/Iris#1180]
### What happened?

When using Iris 1.1.4 with Sildur's Vibrant Shaders 1.32, the block breaking animation is lit incorrectly when the block being broken is near a light source.

This behaviour does not occur when using OptiFine.

To reproduce, simply place a light source near a block and start breaking it in Survival mode (an example is included below in the screenshots).

### Screenshots

Expected behaviour from OptiFine+OptiFabric 1.18.1 HD U H4, Minecraft 1.18.1:
![2022-01-07_13 28 52](https://user-images.githubusercontent.com/1980487/148610258-6531b420-385e-4f02-9ca3-62f1b444bc31.png)

Incorrect behaviour from Iris 1.1.4, Minecraft 1.18.1 (also occurs on 1.17.1 and 1.16.5):
![2022-01-07_13 28 31](https://user-images.githubusercontent.com/1980487/148610245-06e67278-ff7c-4b1b-9a90-24ea9ff06c2d.png)

The testing environment:
![2022-01-07_13 35 01](https://user-images.githubusercontent.com/1980487/148610419-c3ffeb3c-3549-47b0-a2fa-21d8d1cf9322.png)

### Minecraft Version

Minecraft 1.18.1, 1.17.1, and 1.16.5

### Iris Version

1.1.4

### Sodium Version

0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 2060

### Java Version

Java 17

**Comment by OttCS** [comment]
Depending on the shaderpack that you're using, some contain gbuffers_damagedblock files and some don't. It just depends on the author, but this does affect if broken block lines are affected by light or not. I don't think this is an issue with IRIS, most likely the shaderpack.

**Comment by akemin-dayo** [comment]
Yeah, there's no `gbuffers_damagedblock` VSH/FSH anywhere in Sildur's Vibrant.

I suppose that this discrepancy in behaviour between Iris and OptiFine is considered to be not a bug / a won't-fix, then?

**Comment by OttCS** [comment]
I'd still say it's a bug, because IRIS is looking for "Optifine Parity" and it's a difference in behavior. However, I can't speak to how quickly or how high priority it is: if the shaderpack does have the gbuffers_damagedblock, Optifine and IRIS *should* render exactly the same. Without the file, it's the shaderpack author letting the shader mod decide.

**Comment by OttCS** [comment]
Testing Environment:
![2022-01-20_09 43 04](https://user-images.githubusercontent.com/76815426/150360826-1c96f764-62de-4b83-8256-902922287ce0.png)

Block breaking result:
![2022-01-20_09 38 26](https://user-images.githubusercontent.com/76815426/150360986-a1855516-4e65-4152-92f6-1d8d1c35e997.png)

Long story short: Seems to be a specific issue to Sildur's Vibrant Shaders.
Solutions: You could check out writing your own shader so you could add the damagedblock file. Or you could get a different shader. Or avoid having lights around blocks that you're breaking. Basically, this is just up to Sildur to fix in the shader. If you're looking for something similar to Sildur's Vibrant, [GravityShade](https://github.com/OttCS/GravityShade) is a really lightweight option that has decent lighting and reflections that's being updated pretty frequently.

**Comment by akemin-dayo** [comment]
Interesting, I guess it's a bug on Sildur's end, then.

Does having no `gbuffers_damagedblock` result in undefined behaviour, then? (In other words — does this only _happen_ to work correctly on OptiFine?)

Regardless, this issue is so minor that I don't really mind it (definitely not enough to warrant switching away from Sildur's Vibrant), — I just wanted to report the issue to (potentially) help make Iris better / help it reach further parity with OptiFine ;P

**Comment by OttCS** [comment]
According to the [Optifine Documentation](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt), another gbuffers file will take over in this order: terrain, texturedlit, textured. My best guess is that the math that Sildur uses for lighting calculations just gets a little weird with opacity. Sorry that there's not more help I can give, I could whip up some default damagedblock files just to patch it but it's not my place to mess with Sildur's work.

Just out of curiosity, which version of Sildur's Vibrant are you using?

**Comment by akemin-dayo** [comment]
No worries, you don't have to do that ;P

> My best guess is that the math that Sildur uses for lighting calculations just gets a little weird with opacity.

Interesting guess, especially given issue #509 which is yet another OptiFine/Iris discrepancy (this time involving floats) that leads to small visual issues in Sildur's Vibrant.

> Just out of curiosity, which version of Sildur's Vibrant are you using?

1.32 Extreme, but with a custom `shaders.settings` that changes a bunch of settings to match what I use on OptiFine.

(I have verified that this issue still occurs even with a stock copy of Sildur's Vibrant.)

**Comment by coderbot16** [comment]
It's possible that this is caused by either or both of these issues:

- https://github.com/IrisShaders/Iris/issues/773
- https://github.com/IrisShaders/Iris/issues/ 1106

Iris doesn't currently initialize some vertex attributes for the block breaking animation / entity / block entity rendering, and when vertex attributes aren't initialized they get filled with undefined values. It would make sense because the terrain program in Sildur's Vibrant makes use of a number of vertex attributes that are not used in its other programs.

**Comment by coderbot16** [comment]
Discovered some weird undocumented behavior of OptiFine that could be related. If the shader pack does not provide a `gbuffers_damagedblock` program, then block breaking animations are rendered with depth writes disabled and as if the current shader program specified `/* DRAWBUFFERS:0 */` instead of whatever drawbuffers it is currently using.

**Comment by kurigomecha** [comment]
Hi, the issue still seems to reproduce despite the fix.

```
MC 1.21.5
sodium-fabric-0.6.13+mc1.21.5
fabric-api-0.121.0+1.21.5
Iris-Installer-3.2.1
Sildur's Vibrant Shaders v1.52 Extreme-VL
```

In fact, depending on where the player stands, we either get a completely dark breaking pattern or a distorted lit one as shown in the thread

![Image](https://github.com/user-attachments/assets/27de31b2-4670-4669-a1ab-a709fe7c19fd)


I tried looking at fixes in similar threads, but was only able to make the colour a different weird tint using this solution: https://github.com/IrisShaders/Iris/issues/951#issuecomment-1028645395
The comments say that this disables lighting to make it vanilla-like, but this is the result:

![Image](https://github.com/user-attachments/assets/a7b3d010-bd5e-43d2-9622-51fde252237d)

I wonder if some check if not firing in the fix code.
