### ISSUE TITLE
Massive, annoying overlay in multiplayer

### ISSUE THREAD

**Issue by Corsaka** [IrisShaders/Iris#1182]
### What happened?

When playing multiplayer, any time shaders are enabled there is a large box the colour of the night sky that is rendered directly in the middle of the screen on the skybox. It disappears when looking far up/down enough, and when overlaid by the sun. This issue does not occur in singleplayer.

This was tested with BSL, Complementary, and SEUS PTGI shaders.

### Screenshots

I can't easily insert an image of the bug, so here's a youtube video. https://youtu.be/Sfnbkkld53I

### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.1.3

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Win10

### What is your GPU?

Nvidia GeForce GTX 1660

### Java Version

Java 17

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/7834090/latest.log)

**Comment by AlsoSylv** [comment]
Update to iris 1.1.4, this issue was fixed in that release
