### ISSUE TITLE
Particles at full brightness when shadows disabled

### ISSUE THREAD

**Issue by veritronx** [IrisShaders/Iris#1183]
### What happened?

When shadows are disabled particles are rendering at full brightness, noticed instances are block breaking particles for crops, sugarcane.. also there are particles underwater that are full brightness as well.

This happens in iris 1.1.4 and the 1.2.0 config beta 2, does not happen in 1.1.3

### Screenshots

![2022-01-09_11 28 18](https://user-images.githubusercontent.com/85699469/148665983-866ffa87-df71-4d1c-a871-3fbc74b72ff7.jpg)
![2022-01-09_11 34 59](https://user-images.githubusercontent.com/85699469/148665986-a9f23229-6ff7-4a4e-afaa-f3edd6e5c1e9.jpg)
![2022-01-09_11 35 13](https://user-images.githubusercontent.com/85699469/148665987-0d0a5c0b-a566-4ffa-b5a5-b6ca0b94a307.jpg)

### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.1.4.jar and iris-mc1.18.1-1.2.0-prerev.fffb90d-dirty.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Windows 10 21H1

### What is your GPU?

Nvidia GTX 1080ti (497.09)

### Java Version

17.0.1

**Comment by IMS212** [comment]
Seems like particles are somehow inheriting the world border blendFunc when shadows are disabled, causing Complementary to turn the lightmap to max.

**Comment by coderbot16** [comment]
Reopened & tagged as fixed for documentation until the next release.

**Comment by coderbot16** [comment]
1.2.0 is now released, resolving this issue.
