### ISSUE TITLE
Shaderpack options resetting by clicking when holding shift does not works for boolean values.

### ISSUE THREAD

**Issue by devpelux** [IrisShaders/Iris#1192]
### What happened?

The "reset by clicking when holding shift" does not works for boolean values, leaving them untouched even if I click repeatdly.

### Screenshots

I used ComplementaryShaders 4.3.3, minecraft 1.18.1, no mods installed.

The default ComplementaryShaders settings values are these: 

<img src="https://user-images.githubusercontent.com/32025549/148776805-441fc25a-4d3f-489a-8bb4-2971bc66bd2f.png" height="300" />

Then I edited some settings:

<img src="https://user-images.githubusercontent.com/32025549/148776913-448f9fc4-0db9-4a76-9aba-2877ac54e6fc.png" height="300" />

When trying restoring to default values it works correctly for resolution and distance (non boolean values) but does not works for booleans like "Shadow Filtering", also in the txt file the setting remain "false", but it must be "true".

<img src="https://user-images.githubusercontent.com/32025549/148777206-f142922f-50e8-46bd-8792-3dff3d802ae2.png" height="300" />

<img src="https://user-images.githubusercontent.com/32025549/148777219-8c7cadfe-61e3-45d6-a253-d02c7cc67e49.png" />

The reset button however works correctly, but it resets all settings, and I want to reset only one!

### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-beta3.1

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 11

### What is your GPU?

Nvidia RTX 2080

### Java Version

Java 17

---

#### EDIT:  
Tested on beta 3.1.

**Comment by FoundationGames** [comment]
You are using an old version of the Iris 1.2.0 beta
Please update to Beta 3 and check if that will stop the issue from occurring

**Comment by devpelux** [comment]
Updated to 1.2 beta 3.1, it still exists.

PS: The issue happens after applying the settings, if you change the setting without click apply, and then try to rollback by holding shift and clicking it works correctly.

**Comment by coderbot16** [comment]
Fixed in https://github.com/IrisShaders/Iris/pull/1185
