### ISSUE TITLE
Decreased performance when breaking filled chest

### ISSUE THREAD

**Issue by Psojed** [IrisShaders/Iris#1194]
### What happened?

Release notes for 1.1.4 said:
> Fixed a performance drop with shaders disabled compared to base Sodium - Iris with shaders off should no longer measurably decrease performance

Unfortunately, Iris still notably affects performance in disabled state.

My test case is breaking a single chest filled with items and then picking them up. I tested in Singleplayer Creative, standing far enough from the chest so that I don't pick up any of the items right after breaking the chest. Then I ran into the items to pick them up.

1) Water Bottles (ie. a single item per chest slot)
With Sodium, breaking a chest full of Water Bottles wasn't noticeable at all.
Picking them up wasn't noticeable at all.
With Sodium + Iris, breaking a chest full of Water Bottles caused only a small hiccup.
Picking them up also caused a small hiccup.

2) Nether Wart (ie. 64 items per chest slot)
With Sodium, breaking a chest full of Nether Wart caused a small hiccup.
Picking them up also caused a small hiccup.
With Sodium + Iris, breaking a chest full of Nether Wart caused about a 1s lag.
Picking them up literally froze my game for 2 seconds.

### Minecraft Version

1.18

### Iris Version

iris-mc1.18.1-1.1.4.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Windows 7

### What is your GPU?

AMD RX 580

### Java Version

17.0.1.12.1

**Comment by master7720** [comment]
man still uses Windows 7.......

**Comment by IMS212** [comment]
Please avoid talking about user preferences in the issue tracker.

**Comment by master7720** [comment]
why did you delete my comment?

**Comment by master7720** [comment]
just saying update windows dude

**Comment by coderbot16** [comment]
This does not occur at all on 1.16.5, the frame graph stays completely flat. Needs confirmation on 1.17+, might be different there for whatever reason.

**Comment by coderbot16** [comment]
Cannot replicate with just Iris and Sodium.
![image](https://user-images.githubusercontent.com/22420959/166116875-3dae7bfe-a056-4d83-aa0c-f48eeeac8ff9.png)
