### ISSUE TITLE
Requesting Error Messages on Shader Errors

### ISSUE THREAD

**Issue by OttCS** [IrisShaders/Iris#1199]
As an option, error messages should be displayed to help shaderpack developers (and end-users) diagnose and solve errors. Optifine has a similar feature to this, which leads shaderpack developers to use it during development rather than IRIS. Since IRIS gives worlds better performance than Optifine and is gathering a ton of support, modern shaderpacks *should* be designed for IRIS.

**Comment by OttCS** [comment]
![image](https://user-images.githubusercontent.com/76815426/149174136-04592ed0-5851-4c9b-b31c-540d4c86b699.png)
(Screenshot from Optifine)

**Comment by DioEgizio** [comment]
Iris has it but in logs

**Comment by OttCS** [comment]
Got it, thanks so much!
