### ISSUE TITLE
Missing .dlls warn with Colored Lights and other mods

### ISSUE THREAD

**Issue by kxkxrxtx** [IrisShaders/Iris#1203]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.1.4

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1660 SUPER

### Java Version

Java 17

### Reproduction Steps

1. Install mods
2. Game tries to load but then crashes

### Additional context

I've reported this to Colored Lights author and pointed me to report this issue here. I must say it's not Colored Lighrts only, it happened me with other mods too (which I don't remember, but they threw me the same rror). Thanks before hand.

[latest.log](https://github.com/IrisShaders/Iris/files/7871524/latest.log)
[crash-2022-01-14_16.39.22-client.txt](https://github.com/IrisShaders/Iris/files/7871529/crash-2022-01-14_16.39.22-client.txt)
[crash-2022-01-14_16.39.21-server.txt](https://github.com/IrisShaders/Iris/files/7871531/crash-2022-01-14_16.39.21-server.txt)

**Comment by AlsoSylv** [comment]
Does this happen when using sodium standalone? Or is it only adding iris that causes this?

**Comment by kxkxrxtx** [comment]
I'd never tested it but yes, it seems that the cause is Sodium! Gonna report them, thank you!
