### ISSUE TITLE
Incompatible with sodium `0.4.0-alpha6+build.12`

### ISSUE THREAD

**Issue by solonovamax** [IrisShaders/Iris#1204]
### What happened?

When the announcement in caffeinemc was sent that sodium `0.4.0-alpha6` was released, I downloaded it.
When downloading it from modrinth *at that time*, it gave me sodium version `0.4.0-alpha6+build.12`.

I had issues with mods last night but was too lazy to fix them.

This morning, when updating iris, I attempted to run it with version `0.4.0-alpha6+build.12` of sodium.
It did not allow the game to launch with this.

Upon checking the decompiled class file, it is looking for the *exact* sodium version `0.4.0-alpha6+build.14`. Because of this, it seems that it doesn't want to match version `0.4.0-alpha6+build.12`.

After checking the modrinth, it seems that I now download sodium version `0.4.0-alpha6+build.14`. Due to this, I'm inclined to believe that the version on modrinth was updated. I have not checked for curseforge.

A fix for this issue would be to change [`AllowedSodiumVersion.exact("0.4.0-alpha6+build.14")`](https://github.com/IrisShaders/Iris/blob/1.18.x/1.1.5/src/main/java/net/coderbot/iris/compat/sodium/SodiumVersionCheck.java#L9) to `AllowedSodiumVersion.prefix("0.4.0-alpha6")`.

Iris should not depend on a specific build of sodium.
What if someone were to build sodium from source? If they were to do so at the same commit that this requires, it would not be allowed to launch.

### Minecraft Version

1.18.1

### Iris Version

1.1.5

### Sodium Version

0.4.0-alpha6+build.12

### Operating System

Arch Linux 5.15.14-lqx1-1-lqx

### What is your GPU?

NVIDIA RTX 2070

### Java Version

17.0.1 OpenJDK Runtime Environment (build 17.0.1+12)

**Comment by NoComment1105** [comment]
This is an incorrect build that was not intended to be release by CaffieneMC. please use build 14 instead

**Comment by IMS212** [comment]
Build 12 was a bugged version that was pulled in a few minutes due to containing broken code, we will not support it.

**Comment by solonovamax** [comment]
Alright, I'll update my version of sodium.

Though, I believe the issue should be reopened, as currently you cannot run iris with sodium built from source.

**Comment by CaioMGT** [comment]
> Alright, I'll update my version of sodium.
> 
> Though, I believe the issue should be reopened, as currently you cannot run iris with sodium built from source.

we only support release sodium, allowing self-compiled builds would cause way more trouble than its worth

**Comment by IMS212** [comment]
That's a separate issue related to the "next" build of Sodium that will require many changes to support.

**Comment by solonovamax** [comment]
ah, I see. :+1:
