### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by JestemMojzesz** [IrisShaders/Iris#121]
Game is crashing with only Iris + Custom Sodium after loading shaders
[latest.log](https://github.com/IrisShaders/Iris/files/6028495/latest.log)

**Comment by DanielL99** [comment]
Same on 1.16.4 with fabric 0.11.1 loading internal shader
[crash-2021-02-23_13.09.22-client.txt](https://github.com/IrisShaders/Iris/files/6028801/crash-2021-02-23_13.09.22-client.txt)
[latest.log](https://github.com/IrisShaders/Iris/files/6028802/latest.log)

**Comment by coderbot16** [comment]
We figured out the original crash on Discord.

@DanielL99 that is a different issue, you didn't compile Sodium properly. Either compile with Java 8, or run the game with Java 11. Go to the discord server for further support
