### ISSUE TITLE
Detect when Not Enough Crashes is displaying a crash screen, and reset relevant state to avoid breakage.

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#1217]
We can check when setScreen was called with an instance of CrashScreen as an argument. Ideally, we wouldn't have quite so much global state either. NEC resets most vanilla / OpenGL state, but it doesn't (and shouldn't) reset our state.

**Comment by kristibektashi** [comment]
This should definitely be added

**Comment by kristibektashi** [comment]
Why was this closed?

**Comment by IMS212** [comment]
Iris does not support NEC.
