### ISSUE TITLE
iris shaders says that sodium isnt commpatable (see full comment)

### ISSUE THREAD

**Issue by buuv1111** [IrisShaders/Iris#1222]
### **what should i do? i want sodium 1.18.1**
please help me
![welp](https://user-images.githubusercontent.com/88278758/150178056-a220f4b0-9a98-40b4-803e-83d052ac548a.JPG)
![folder](https://user-images.githubusercontent.com/88278758/150178100-89564ee6-fb2a-49af-8b30-a04d63f1b984.JPG)

**Comment by AlsoSylv** [comment]
Update to sodium alpha6
