### ISSUE TITLE
Iris and Bedrockwaters not compatible in new version?

### ISSUE THREAD

**Issue by TheButterbrotMan** [IrisShaders/Iris#1223]
### What happened?

Iris and Bedrockwaters not compatible in new version!

### Screenshots

https://i.imgur.com/UHV8FR4.png

### Minecraft Version

1.18.1

### Iris Version

1.2.0

### Sodium Version

alpha6+build.14

### Operating System

Windows 10

### What is your GPU?

GTX 750 TI

### Java Version

Java 17

**Comment by AlsoSylv** [comment]
Bedrock Waters was marked as incompatible because it doesn't work with sodium, and causes weird rendering bugs such as chunks with water completely disappearing.

**Comment by coderbot16** [comment]
Correct https://github.com/2Retr0/BedrockWaters/issues/10

**Comment by TheButterbrotMan** [comment]
Ops, sorry!
