### ISSUE TITLE
Bad performance on AMD GPU

### ISSUE THREAD

**Issue by rimgro** [IrisShaders/Iris#1226]
### What happened?

Performance on RX 550 with shaders like with Optifine or worse.

### Minecraft Version

Minecraft 1.18.1, 1.17.1, 1.16.5

### Iris Version

any version

### Sodium Version

any version

### Operating System

Windows 10, 11

### What is your GPU?

AMD RX 550 4 gb

### Java Version

Java 16, 17

**Comment by NoComment1105** [comment]
Please come into our discord server, where it will be easier for us to provide support for you. The Github issue tracker isn't a suitable place to provide support.
