### ISSUE TITLE
"Hide GUI" Button

### ISSUE THREAD

**Issue by Turn999** [IrisShaders/Iris#1229]
A button somewhere in the Corner where you can hide the sliders, buttons and borders so you can view the scenery in your current position without going out of the settings menu. Just to make it easier to view the changes without always having to navigate back to shader settings whenever you want to make additional small adjustments.

**Comment by OttCS** [comment]
This would be a great feature! For the mechanic, I'd support "hiding the settings" as long as you're holding down a button (tab, shift, etc.) and they come back up when you let go.

I'm not sure about the feasibility of this, the esc key is usually the only thing used. A button that goes to a "blank screen" and can be exited with the esc key would be good inside the shader settings page (the shader settings background is grayed out AND has buttons all over it, a little tough to see through).

**Comment by douira** [comment]
This issue can probably be closed now since #1657 implemented this feature.
