### ISSUE TITLE
Incompatible Screen

### ISSUE THREAD

**Issue by KingCreeperz** [IrisShaders/Iris#1234]
### What happened?

I launched up multimc with iris shaders but it said that my version of sodium was incompatible for some reason even though I have the latest version of sodium. Could you tell me what version I need or just update to the latest version plz

### Minecraft Version

1.18.1

### Iris Version

1.20

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1660 TI

### Java Version

Java 17.02

**Comment by AlsoSylv** [comment]
That's not the latest version of sodium, alpha 6 is.
