### ISSUE TITLE
Shaders not working together with MC-164001 painting transparency fix

### ISSUE THREAD

**Issue by Skeithh** [IrisShaders/Iris#1237]
### What happened?

Using the transparency fix for paintings (and other textures) from [this mojang issue](https://bugs.mojang.com/browse/MC-164001), I expected to have my paintings that have transparency to well... Do exactly as you'd expect- be transparent.

Unfortunately, when I have shaders on using Iris, transparency completely breaks again. 
I tested this with the following shaders:
-BSL v8.1.02.1
-Prismarine V4.0 
-Beyond Belief Legacy v1.2.1

First image in the lineup is how it looks like with shaders toggled off. Every other image is in the listed testing order.

### Screenshots

![image](https://user-images.githubusercontent.com/74820899/150643126-c5330025-2630-4bd8-a325-fa091aa79b0c.png)
![image](https://user-images.githubusercontent.com/74820899/150643129-226ff6b3-3d29-4cca-9170-e7b19d091b86.png)
![image](https://user-images.githubusercontent.com/74820899/150643133-1a04df53-b4c1-4a30-8118-94d0ade55e08.png)
![image](https://user-images.githubusercontent.com/74820899/150643139-65c524eb-cb4e-4782-bf84-974f95fe930e.png)

### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre.jar

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Operating System

Windows 10

### What is your GPU?

Radeon (TM) RX 480 Graphics

### Java Version

Java 17

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/7918564/latest.log)

**Comment by AlsoSylv** [comment]
This fix is a core shader to make entities transparent, a different fix on the side of iris would be required if someone cares to look into this issue.

**Comment by coderbot16** [comment]
Vanilla core shaders are not supported when using an Iris shader pack, see this issue:

https://github.com/IrisShaders/Iris/issues/1042

**Comment by coderbot16** [comment]
Unfixable, core shaders are not supported.
