### ISSUE TITLE
the textures seem to shift

### ISSUE THREAD

**Issue by EstaLocura** [IrisShaders/Iris#1241]
### What happened?

when the shaders are turned on, the textures seem to shift for the NPC and the actor, when the shaders are turned off, regardless of the resource package, everything falls into place

### Screenshots

![2022-01-23_12 54 47](https://user-images.githubusercontent.com/98257876/150673617-c1e438ea-56da-4021-88b2-39e7bf43e89b.png)
![2022-01-23_12 54 58](https://user-images.githubusercontent.com/98257876/150673624-d9d65560-2b4a-44cf-bf77-480898583938.png)
![2022-01-23_12 55 00](https://user-images.githubusercontent.com/98257876/150673627-e52fcd58-7f98-4e33-b131-b8f02d9b2c63.png)
![2022-01-23_12 55 04](https://user-images.githubusercontent.com/98257876/150673630-47421fdc-fb2c-42b8-9648-e1be3fef4eb4.png)
![2022-01-23_12 55 09](https://user-images.githubusercontent.com/98257876/150673635-186bf558-5d45-48d8-a750-966b6b7769d0.png)

### Minecraft Version

1.16.5

### Iris Version

iris-mc1.16.5-1.2.0-pre

### Sodium Version

sodium-fabric-mc1.16.5-0.2.0+build.4

### Operating System

Win10

### What is your GPU?

AMD Radeon RX 580 8Gb VRAM

### Java Version

build 1.8.0_321-b07

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/7920222/latest.log)

**Comment by coderbot16** [comment]
Please test with only Iris and Sodium, without any other mods installed.

**Comment by coderbot16** [comment]
We can't do anything with this issue report without additional information.
