### ISSUE TITLE
Optifine cape in Iris

### ISSUE THREAD

**Issue by superlopez-real** [IrisShaders/Iris#1248]
**Is your feature request related to a problem? Please describe.**
I once bought an Optifine cape, and i can't use it in Iris, sadly.

**Describe the solution you'd like**
I would like that there is a cape tab like in Optifine so that people can use their Optifine capes in Iris.

**Describe alternatives you've considered**
I have tried a fabric mod called Kappa, but it doesn't show my Optifine cape, instead it shows my migrator cape.

**Comment by AlsoSylv** [comment]
Iris will not be adding optifine capes, to get kappa to work properly you need to disable your migrator cape

**Comment by superlopez-real** [comment]
oooh ok, thanks a lot
