### ISSUE TITLE
Upload artifacts when GH Actions are done.

### ISSUE THREAD

**Issue by pjalsGit** [IrisShaders/Iris#1249]
**Is your feature request related to a problem? Please describe.**
I would like that GH Actions in this repository would upload artifacts.

**Describe the solution you'd like**
Use the [Upload a Build Artifact](https://github.com/marketplace/actions/upload-a-build-artifact) to upload artifacts to GH Actions.

**Describe alternatives you've considered**
None.

**Additional context**
I could make a PR for this.

Related PR: #1250

**Comment by NoComment1105** [comment]
We do not upload builds with our actions on purpose. Action builds are often unstable, and make it a nightmare for our support team to debug, since the bugs will change between every single commit. Your pull request will also be closed for this reason.
