### ISSUE TITLE
Sodium fork not building

### ISSUE THREAD

**Issue by ariature** [IrisShaders/Iris#125]
So, after finally figuring out how to get the sodium compatible iris, as well as the sodium fork, I tried to build the fork. Problem is, unlike every past iris build I did in command prompt, I didn't get a green text telling me it was successful, I got a red text saying `BUILD FAILED` If you know how to fix this or anything, please tell. Edit: here is the error: https://gist.github.com/ariature/5233e5f22ffe9b123d492704e5a54ef8

**Comment by NoComment1105** [comment]
Someone correct me if i'm but i believe this is related to you not having a JDK on your computer. Have you recently update your java version?

**Comment by RDKRACZ** [comment]
No need to open a new issue if you already reported this in discussions although it should be reported here from beginning. You should always include a full error message (if it’s long post it on pastebin-like service, preferably github gist), not just “Build failed”.

**Comment by ariature** [comment]
> Someone correct me if i'm but i believe this is related to you not having a JDK on your computer. Have you recently update your java version?
I got the AdoptOpenJDK version 8 and installed it, restarted my pc, and it was working for other things.

**Comment by ariature** [comment]
> No need to open a new issue if you already reported this in discussions although it should be reported here from beginning. You should always include a full error message (if it’s long post it on pastebin-like service, preferably github gist), not just “Build failed”.

ah ok. sorry i am quite new to using github for more than a quick download but i think this is what you wanted: https://gist.github.com/ariature/5233e5f22ffe9b123d492704e5a54ef8

**Comment by OverlordsIII** [comment]
You will need to compile the [iris sodium compatability branch](https://github.com/IrisShaders/Iris/tree/sodium-compatibility) and then run `./gradlew publishToMavenLocal` on that branch. Then come back to the sodium fork and rerun build. You can also get the sodium compatible version of iris from [actions](https://github.com/IrisShaders/Iris/suites/2085270714/artifacts/42260737) and then take the jar without `-dev` or `-sources` and then put that jar in `.gradle/loom-cache` of your sodium branch. If that does not work, try doing the first thing I said.

**Comment by ariature** [comment]
> You will need to compile the [iris sodium compatability branch](https://github.com/IrisShaders/Iris/tree/sodium-compatibility) and then run `./gradlew publishToMavenLocal` on that branch. Then come back to the sodium fork and rerun build. You can also get the sodium compatible version of iris from [actions](https://github.com/IrisShaders/Iris/suites/2085270714/artifacts/42260737) and then take the jar without `-dev` or `-sources` and then put that jar in `.gradle/loom-cache` of your sodium branch. If that does not work, try doing the first thing I said.

Well thank you! That was what I was missing. It ran correctly and I was able to launch Minecraft without any issues!
