### ISSUE TITLE
Fabric Crash after walking around & looking at the Badger?

### ISSUE THREAD

**Issue by TheButterbrotMan** [IrisShaders/Iris#1255]
### Minecraft Version

1.18.1

### Iris Version

1.2.0-pre

### Sodium Version

0.4.0-alpha6+build.14

### Operating System

Windows 10

### What is your GPU?

GTX 750 TI

### Java Version

Java 17

### Reproduction Steps

1. Spawn '...'
2. look at a certain Mob (Badger?)
3. See error (Crashes)

### Crash Report file and latest.log

```shell
https://crashy.net/Xnd3zSWWXIS3VEDIkJ2Q
```

**Comment by TheButterbrotMan** [comment]
https://github.com/itsmeow/betteranimalsplus/issues/290

**Comment by coderbot16** [comment]
Please remove Iris and see if it still occurs - if so, it might be an issue with the other mod instead.

**Comment by coderbot16** [comment]
If not, this might be a bug with the other mod not being prepared for the world to be rendered twice for the shadow pass.

**Comment by coderbot16** [comment]
This is pointing at https://github.com/Traben-0/EmissiveMod/blob/02469f7c0ed4c643bf280ac4c0288637e9dd9909/src/main/java/traben/entity_texture_features/mixin/client/entity/MIX_LivingEntityRenderer.java

Try removing or updating that mod and see if it persists.

**Comment by TheButterbrotMan** [comment]
I will, probably i should open an issue at EmissiveMod?

**Comment by coderbot16** [comment]
Perhaps - I'm not sure what line in that mixin is triggering a crash, but maybe the author has more information.

**Comment by coderbot16** [comment]
Oh yeah, the mod has an update, try getting it - https://modrinth.com/mod/entitytexturefeatures

**Comment by TheButterbrotMan** [comment]
Just tried it, seems like it work. Thank you.

**Comment by coderbot16** [comment]
You're welcome!
