### ISSUE TITLE
import shader config file breaks minecraft as a window

### ISSUE THREAD

**Issue by idkman2021** [IrisShaders/Iris#1258]
### What happened?

Pressing "import shader config file breaks" made it so that it showed me the selection window, but I couldn't click anything in it as it would revert back to fullscreen minecraft but with an inactive file selection window on top. In particular I couldn't close the window to get out of the situation. Since my cursor didn't work I couldn't exit minecraft. Keyboard worked in minecraft, so by pressing "esc" and navigating back to the game and typing "/kick player" I kicked myself, but that didn't help. So I had to kill minecraft from task manager.

### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre.jar

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Operating System

Windows 11

### What is your GPU?

NVidia GeForce GTX 1650 (intel optimus)

### Java Version

JAVA 16!!!

### Additional context

i have 2 monitors

**Comment by AlsoSylv** [comment]
We need a log and screenshot

**Comment by idkman2021** [comment]
> We need a log and screenshot

log https://gist.github.com/idkman2021/0a6798029f7a2fb56e4b2245f78c2f7e
Screenshot is minecraft with file selection window on top

**Comment by Pectacular** [comment]
How are you using Java 16 with Minecraft 1.18.1?

**Comment by idkman2021** [comment]
> How are you using Java 16 with Minecraft 1.18.1?

I might be wrong, but I use default java and the github issue maker told me 1.18.1 uses java 16

**Comment by Pectacular** [comment]
Do you use the vanilla launcher? If you do, then you're probably using Java 17.0.1

**Comment by idkman2021** [comment]
> Do you use the vanilla launcher? If you do, then you're probably using Java 17.0.1

I use vanilla launcher so probably java 17

**Comment by helpimnotdrowning** [comment]
Still having the same issue in the just-released v1.2.4. 

I clicked on the "export config" button of a shader pack (which opened a file picker) and switched back into (fullscreen) MC. Here, whenever I tried to click anywhere within the Minecraft window, it would flash the file picker before the MC window minimizes itself and the file picker dissapears (doesn't show up in the alt-tab menu). Killing and restarting `explorer` does nothing, the only way to fix this is to close Minecraft. 

While the game is like this, the game still *looks* fine (world progresses like normal, animations, mobs, shaders) and still accepts *most* input, like movement (WASD), chat/commands, and even mouse movements to move the camera/player head. Right clicking, however, will cause it to minimize all over again, making the only ways out of this either:
* press ESC, use TAB and ENTER to navigate menus and close the game
* `taskkill /f /im javaw.exe`

Nothing special is logged:
```
[20:18:54] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIClientPlugin] with 1371 entries, 1597 displays, 1 display visibility predicates, 21 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Anvil, Beacon Base, Beacon Payment, Tilling, Pathing, Waxing, Wax Scraping, Oxidizing, Oxidation Scraping, Information), 4 exclusion zones and 3 overlay deciders in 235ms.
[20:18:54] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIServerPlugin] stage [END], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[20:18:54] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 5ms.
[20:18:54] [Render thread/INFO]: Received secret
[20:18:54] [Render thread/INFO]: Connecting to server: '127.0.0.1:49913'
[20:18:54] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
[20:18:54] [VoiceChatPacketProcessingThread/INFO]: Successfully authenticated player baa0a8cd-2687-4778-bfc4-685dbef98219
[20:18:54] [VoiceChatConnectionThread/INFO]: Server acknowledged authentication
[20:18:54] [VoiceChatConnectionThread/INFO]: Clearing unused audio channels
[20:18:55] [Render thread/INFO]: Refreshing cached entry list texture...
[20:18:55] [Render thread/INFO]: Loaded 0 advancements
[20:18:59] [Render thread/INFO]: [CHAT] Saved screenshot as 2022-04-26_20.18.57.png
// export -> switch back to mc -> problem arises here
[20:19:43] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2004ms or 40 ticks behind
[20:20:01] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3353ms or 67 ticks behind
```

I actually can't use screencapture (OBS) to record this, as it either shows a black screen or this 
![image](https://user-images.githubusercontent.com/35247379/165421627-b45bf978-b062-47ee-9d3c-6b1798280675.png), where it freeze frames on the first frame of the game, though it does show the bugged window (incase I didn't put it in earlier, the file picker never shows up again after going back into MC, except for the quick flash on clicking)

To replicate (written better):
1. Open shader menu
2. Select a shaderpack, go to Shader Pack Settings
3. Click the export button on the top right (the import button will also probably do this)
4. Once it opens the file picker, switch back into Minecraft
5. Attempt to left click anywhere, it will minimize Minecraft, though using keyboard navigation, typing, and looking around with the mouse work just fine.

Using:
* `GPU` PNY GTX 1050
* `OS` Windows 11 | 21H2
* `Java` Eclipse Adoptium/Temurin | 17.0.2 x64
* `Launcher` PolyMC | 1.1.0-9f8983b5
* `MC` 1.18.2
* `Fabric Loader` 0.13.3
* `Fabric API` 0.48.0+1.18.2
* `Sodium` 0.4.1+build.15
* `Iris` 1.2.4-build.38

**Comment by helpimnotdrowning** [comment]
A workaround I've just discovered is: while you are kicked out of MC (it is minimized), right click on the taskbar icon and click "close window"
![image](https://user-images.githubusercontent.com/35247379/165426093-866cc602-7951-4347-afa2-8a84a19c1488.png)
This will fullscreen Minecraft and put the bugged window in the foreground
![image](https://user-images.githubusercontent.com/35247379/165426298-c8740f1d-47eb-4930-a9c6-9a4a8d077447.png)
, where you can now click "cancel" to close the file picker, making Minecraft playable again, no game-restart needed ("close window" doesn't close MC, it just makes the bugged file picker visible)

**Comment by Felix14-v2** [comment]
Have you tried to reproduce this issue with [Borderless Mining](https://modrinth.com/mod/borderless-mining)  installed? I have a hunch that this mod can help.

**Comment by Felix14-v2** [comment]
@coderbot16, is it possible to disable the prevention of import/export settings if any mod installed, implementing borderless mode?  It looks like they are fixing the problem (at least in my case).

**Comment by coderbot16** [comment]
That's potentially an option, but it looks like Borderless Mining allows the borderless mode to be turned off, so detection would be complex.
