### ISSUE TITLE
[All Shaders] Geometry strange holes

### ISSUE THREAD

**Issue by TerminalHash** [IrisShaders/Iris#1266]
### What happened?

Hello!
Yesterday i installed this mod and his work, thanks for this. But, i have some troubles with geometry on all shaders - they have a holes in blocks, steps and other blocks, sometimes don't rendering leaves.

### Screenshots

Stereo's Default
![2022-02-05_13 07 18](https://user-images.githubusercontent.com/64691722/152637861-894e00cb-48dd-4473-8480-07db06a4578a.png)

Sildur's Vibrant
![2022-02-05_13 07 48](https://user-images.githubusercontent.com/64691722/152637867-ac236a29-f52f-47e3-a8df-fc66f5f225ce.png)

Sildur's Enhanced
![2022-02-05_13 08 56](https://user-images.githubusercontent.com/64691722/152637877-a59f823f-0b8c-426b-a9e1-393154eda579.png)

This bug repeating on other like Continium, MakeUp, etc. On Tea 1.5.3 (1.5.6.1 not working) all fine:
![2022-02-05_13 07 29](https://user-images.githubusercontent.com/64691722/152637906-0a0addb9-66d7-4536-800d-42e732c17c85.png)

### Relevant log output

```shell
Logs clear.
```

### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Operating System

Artix Linux

### What is your GPU?

AMD Radeon HD 6750

### Java Version

Java 17

**Comment by coderbot16** [comment]
Can this be reproduced in a singleplayer world with only Iris and Sodium installed?

**Comment by TerminalHash** [comment]
I can try.

**Comment by TerminalHash** [comment]
There are still problems.
Stereo's Default:
![2022-02-19_10 33 58](https://user-images.githubusercontent.com/64691722/154791705-2d8857b1-c411-4371-9bee-c7b17018e177.png)

Sildur's Enhanced Default:
![2022-02-19_10 34 59](https://user-images.githubusercontent.com/64691722/154791716-1a4a0a5a-f077-4a74-85ee-118109cfda76.png)

**Comment by coderbot16** [comment]
Do the issues still occur with shaders disabled?

**Comment by TerminalHash** [comment]
If the shader is turned off, then there are no holes. With Sodium Extra and Indium result is identical.
![2022-02-19_10 44 48](https://user-images.githubusercontent.com/64691722/154791955-bed94f59-c8ca-4a3a-b642-9a47d26c7476.png)

**Comment by coderbot16** [comment]
Does it happen without any resource packs enabled but with shaders enabled? If it continues then I'm not really sure what it could be beyond some driver issue or something.

**Comment by coderbot16** [comment]
I just noticed that you're using Arch Linux, which means you're probably on Mesa drivers. Maybe it's worth a shot switching to a different version of Mesa?

**Comment by TerminalHash** [comment]
If the problem was in Mesa, then the shadows would break (and holes on old version of game) - I already had a similar bug on Optifine. It has nothing to do with the resource pack. The problem is the same everywhere. 
I'll play with Mesa, but it's unlikely that anything will change.

**Comment by TerminalHash** [comment]
Also - on last Sildur's Vibrant i have this bug. Logs are still clean. 
![2022-02-19_11 03 08](https://user-images.githubusercontent.com/64691722/154792564-48a04eea-5297-4ebf-888e-a055422e7888.png)

Is there any way to enable the most advanced graphics debug mode? Maybe the logs are truncated.

**Comment by TerminalHash** [comment]
Apparently, the bug appears only when a custom lighting system is present in the shader - CyanideShaders has one, but does not have any shadows and other effects. 
![2022-02-19_11 13 06](https://user-images.githubusercontent.com/64691722/154792837-2697e582-c2f8-4a9c-9b2d-3c5aa4da6196.png)

**Comment by coderbot16** [comment]
This definitely seems like it could be potentially caused by the whatever Mesa version that Arch is shipping. These issues do not occur when testing on my Intel laptop running an older stable version of Mesa (on Ubuntu), and I haven't seen them reported by anyone else.

Please see if it happens with other versions of Mesa, and ensure you aren't running an outdated experimental Mesa version or something. There's not much that I can do without being able to reproduce this myself.

**Comment by coderbot16** [comment]
Given that you are experiencing multiple issues that have not been reported by anyone else (or at least, as far as I am aware), I'm going to attribute this to a driver bug or other issue relating to nonstandard system configurations. I can't do much with this report without a confirmation on whether or not it affects only certain versions of Mesa or being able to reproduce it myself.

> If the problem was in Mesa, then the shadows would break (and holes on old version of game)

Not necessarily true, with driver bugs you can't make these kinds of assumptions, especially when Minecraft's and Sodium's rendering changes from version to version.
