### ISSUE TITLE
transparency with BSLE

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1268]
### What happened?

transparency with [BSJE](https://github.com/BIOSGraphics/BSJEShader)

### Screenshots

![2022-02-06_15 51 46](https://user-images.githubusercontent.com/68275908/152688783-e112fd74-ce8f-4689-bf46-6177e92c72b0.png)

### Minecraft Version

Minecraft ///

### Iris Version

iris-1.2.0

### Sodium Version

sodium 0.4 alpha 6

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by coderbot16** [comment]
Can you check with the latest trunk version? This might have been resolved with https://github.com/IrisShaders/Iris/pull/1260

**Comment by Lolothepro** [comment]
![2022-02-21_09 25 46](https://user-images.githubusercontent.com/68275908/154916316-1f0f92bd-53f4-4d4c-9334-59c454c1a8ce.png)

**Comment by coderbot16** [comment]
Please test on OptiFine

**Comment by Lolothepro** [comment]
![2022-02-21_17 00 54](https://user-images.githubusercontent.com/68275908/154989983-ad10b595-8565-4271-a969-c5ab32f37900.png)
