### ISSUE TITLE
Crash on Xaeros minimap update notification

### ISSUE THREAD

**Issue by CraftalotReloaded** [IrisShaders/Iris#127]
Whenever the Xaeros minimap notification shows up in the main menu right after loading the sodium compatibility branch and sodium fork for iris will crash without any further info in the logs or a crash report.

Iris build until the following commit:
https://github.com/IrisShaders/Iris/commit/38369df307d8d9720ebf7bc6171048cbe3884b77

Sodium fork build until the following commit:
https://github.com/IrisShaders/sodium-fabric/commit/e88a52f6c5242d5fc516068578d863a8955edefd

**Comment by coderbot16** [comment]
It's unlikely that this is due to the update notification, I'm guessing that this is the AMD crash related to the noise texture. If so, you'll see an `hs_err_pid_####.txt` file somewhere in your `.minecraft` directory, it would be helpful to upload it here for verification.

**Comment by coderbot16** [comment]
It's possible that this would *appear* to be related since Iris begins initializing its rendering pipeline a few seconds after you've reached the title screen, and this is where the AMD crash occurs.

**Comment by CraftalotReloaded** [comment]
I do not have anything AMD and neither do i have that file
It should also be worth nothing that once i selected to not show the update message again after removing iris and the sodium fork and then restarted my game with them again that everything was fine.

**Comment by coderbot16** [comment]
Can you send a log file and/or crash report?

**Comment by coderbot16** [comment]
I will have to investigate this more closely and see if I can reproduce it.

**Comment by CraftalotReloaded** [comment]
As i already said in my first comment no crash report was created and the logs contained nothing special(same stuff as when everything is fine without errors, warnings etc)

**Comment by coderbot16** [comment]
Does a crash appear in the launcher console? If so, can you send a screenshot? It would also still help a bit to have a log file to reproduce on my end

**Comment by CraftalotReloaded** [comment]
Nothing at all mentions any issues.
In regards to the log i wouldn't know which log is the right one anymore but i can try to trigger it again later today or tomorrow or so.

**Comment by coderbot16** [comment]
I will try to reproduce but it will be very difficult to debug this if I am unable to.

**Comment by CraftalotReloaded** [comment]
Just managed to trigger it again by changing the config to not ignore this update again.
[latest.log](https://github.com/IrisShaders/Iris/files/6064641/latest.log)
However, i don't believe it contains anything special.

**Comment by coderbot16** [comment]
Just want to verify, does this still happen with the latest commits?

**Comment by CraftalotReloaded** [comment]
Yes it does.
However, now instead of immediately exiting it freezes, so if you want i could hook up visualVM and see where it hangs.

**Comment by coderbot16** [comment]
Sure, would be interesting to see.

**Comment by CraftalotReloaded** [comment]
It appears to have become very inconsistent, only occurring sometimes anymore if i click on the loading screen while it is in fullscreen.
Problem for VisualVM is that if i click its window to select what process to watch and then click back in the loading screen i fail to trigger it.

**Comment by coderbot16** [comment]
The latest version of trunk no longer loads shaders when you hit the main menu, but now only when you enter a world. Perhaps that fixes this?

**Comment by CraftalotReloaded** [comment]
This appears to solve the issue 👍

**Comment by coderbot16** [comment]
Good to know, thanks!
