### ISSUE TITLE
Stained Glass broken with SEUS Renewed

### ISSUE THREAD

**Issue by C-Stew** [IrisShaders/Iris#1279]
### What happened?

Stained Glass **Panes** have proper coloring of the world behind them, but Stained Glass **Blocks** have improper coloring, most noticeable with the sky being discolored.

To replicate:
- Enable the latest version of SEUS Renewed
- Place stained glass or tinted glass **blocks**, look through them, and voila! They're broken!

*I've included a <4MB video below showing the issue.*

### Screenshots

https://user-images.githubusercontent.com/51380437/153733167-c0805c6e-5c8b-435b-b967-39d4dbecd792.mp4

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre.jar

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Operating System

Windows 10 Pro 21H1

### What is your GPU?

Nvidia GTX 1660-Ti (Mobile)

### Java Version

jdk-17.0.1.12-hotspot from Adoptium

### Additional context

Glass behaves properly with the latest version of OptiFine.

**Comment by NoComment1105** [comment]
We have had another confirmation of this issue in the Discord server. Can be found [here](https://discord.com/channels/774352792659820594/849360601267830825/944547310380122173)

**Comment by zax71** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/8102017/latest.log)
Log for debugging purpouses

**Comment by cawong89** [comment]
This bug does not seem to occur in older versions of Iris.
