### ISSUE TITLE
weird sky issue with select shaders not found in optifine

### ISSUE THREAD

**Issue by Kawesome06** [IrisShaders/Iris#1286]
### What happened?

weird sky issue on SUES and BSL shaders respectively...

seems to work okay on optifine so I don't think it's the shaders.
could also be a sodium issue???

### Screenshots

[seus](https://cdn.discordapp.com/attachments/752564498593742948/945388731186176000/2022-02-21_13-33-33_Trim.mp4)
[bsl (more obvious)](https://cdn.discordapp.com/attachments/752564498593742948/945390654530408478/2022-02-21_13-34-08_Trim.mp4)

### Minecraft Version

Minecradt 1.18.1

### Iris Version

iris-mc1.18.1-1.1.3.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 3060 Ti

### Java Version

Java 16

**Comment by Lolothepro** [comment]
I advise you to update Iris and Sodium.

**Comment by coderbot16** [comment]
Your Iris version is very outdated and is missing a huge number of bug fixes from 1.1.4 and 1.2.0. Please update. If the issue persists let me know and this can be reopened.
