### ISSUE TITLE
(I know someone requested this) Can you add pbr support? Preferably reflections first?

### ISSUE THREAD

**Issue by googlescientificnameforapig** [IrisShaders/Iris#1296]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by coderbot16** [comment]
Please look at the pinned issues.

**Comment by googlescientificnameforapig** [comment]
Are you still developing the feature cause the pbr request was like a year ago

**Comment by TheNukeLore** [comment]
There are more important focuses atm
