### ISSUE TITLE
Iris and Distant Horizons throw a tantrum when trying to comprehend a sheep's existence together :bruhmoment:

### ISSUE THREAD

**Issue by LonelySauce** [IrisShaders/Iris#1299]
### Minecraft Version

1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre.jar

### Sodium Version

 sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Operating System

Windows 10

### What is your GPU?

NVidia GTX 1660 SUPER

### Java Version

Java-17.0.1

### Reproduction Steps

1. Import these mods into whatever program you use to manage your MC Instances (I'm using the Curseforge app):
[Perf Test 1.zip](https://github.com/IrisShaders/Iris/files/8176464/Perf.Test.1.zip)

2. Create a new world or join one you've already made
3. Spawn in some sheep (3-5 should do it)
4. Game should crash upon reopening the world OR while you're in the world placing the sheep

### Crash Report file and latest.log

```shell
Crash Report: https://pastebin.com/Hb78rp5G
Latest.log: https://pastebin.com/hUUNTk19

I refuse to put both of those into a single window, that just looks fucking awful and is annoying to read through. I would know since I've had to deal with this before when trying to help one of my friends -_-
```

### Additional context

Settings for all mods are set to their defaults for this to occur. No shaders were enabled during this crash either, not even "_Fabulous_" graphics.

"NOOO YOU CAN'T JUST CRASH ON MEEE!!1!1!" -Some kid probably

**Comment by LonelySauce** [comment]
Damn, so close to issue #1300 :(

**Comment by coderbot16** [comment]
Iris isn't compatible with FREX currently. You need to remove it. I don't see distant horizons in the crash log at all.

**Comment by LonelySauce** [comment]
Well shit.
