### ISSUE TITLE
PBR textures are not supported

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#130]
- [X] At the very least, we should bind textures containing the default specular / normal maps to prevent issues. (Done)

Proper support for PBR is being done in #1401.

**Comment by NoComment1105** [comment]
Not yet. Any updates can be found through the Discord server, or the GitHub releases section.

**Comment by itsTyrion** [comment]
what about POM?

**Comment by LizIsTired** [comment]
POM (Parallax Occlusion Mapping) is included under PBR, so as of yet, nothing new.

**Comment by alex99ata** [comment]
Hi, Iris is doing a great job so far, but there are some really cool resource packs over there that need the PBR/POM support in order to give Mc an incredible look. Is there any aproximate date when this feature will be implemented? Thanks

**Comment by AlsoSylv** [comment]
ETAs for features aren't provided because they can always change

**Comment by Trainer0072** [comment]
Hi, I'm also curious about when would pbr be included. It's only about how do you feel it mqy be avaiable. 2 weeks? Month? Half a year? Or maybe a whole year?

**Comment by TheNukeLore** [comment]
Sometime between now and the heat death of the universe

**Comment by Trainer0072** [comment]
> Sometime between now and the heat death of the universe

😆

**Comment by alex99ata** [comment]
![devs_PBR_Iris](https://user-images.githubusercontent.com/30976907/164519086-295f0205-a9b9-45a3-9045-25b26da52ae9.png)

**Comment by CloudyWhale** [comment]
The pbr works in inventory but when you place the block down it does not

**Comment by NotJansel** [comment]
pbr is being worked on. For proper support please get the PBR Beta Build in the [Discord](https://discord.gg/irisshaders) and get the build in #public-test-builds. The ascociated Thread is Support given.
