### ISSUE TITLE
Game Crash with any shaders

### ISSUE THREAD

**Issue by TreeV2** [IrisShaders/Iris#1305]
When i use any shaders its crash
Here log:
[crash-2022-03-05_21.13.41-client.txt](https://github.com/IrisShaders/Iris/files/8191392/crash-2022-03-05_21.13.41-client.txt)

**Comment by IMS212** [comment]
This is an issue with OK Zoomer, not Iris.

**Comment by IMS212** [comment]
https://github.com/EnnuiL/OkZoomer/issues/53
