### ISSUE TITLE
fancyPants Support

### ISSUE THREAD

**Issue by Tanerx** [IrisShaders/Iris#1309]
Hello.
Most of us started using custom armor sets for vanilla Minecraft. Thanks to fancyPants make this possible starting with Minecraft 1.17. Iris doesn't support right. Supporting fancyPants will be good feature. 

https://github.com/Ancientkingg/fancyPants

Shaders off:

https://i.imgur.com/PAM9mDZ.png

If any shader enabled with Irıs: 

https://i.imgur.com/zcbBGOX.png

**Comment by LizIsTired** [comment]
This will never be supported due to core shaders being unsupported

**Comment by AlsoSylv** [comment]
See issue #1042
