### ISSUE TITLE
Shadow Alpha test settings not applied to every shadow program

### ISSUE THREAD

**Issue by gri573** [IrisShaders/Iris#1314]
### What happened?

When setting `alphaTest.shadow=off` in shaders.properties, it doesn't apply to all shadow gbuffers programs. Specifically, it doesn't apply to `shadow_terrain_cutout`.

the attached shaderpack demonstrates this by drawing all triangles in the shadow pass to three large triangles with transparency going from 0 to 1 along the x axis. the topmost triangle consists of translucent blocks, the middle one of cutout blocks, the bottom one of solid ones.
beware, it runs very poorly and scales badly with increasing render distance.

[shadow_alpha_test.zip](https://github.com/IrisShaders/Iris/files/8221411/shadow_alpha_test.zip)
.

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.2.1.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

linux (ubuntu 21.10)

### What is your GPU?

AMD vega 8

### Java Version

java 16 (bundled)

**Comment by coderbot16** [comment]
This has been fixed on 1.16.5. It will need to be replicated for 1.17.1

**Comment by IMS212** [comment]
Can someone confirm if this is fixed on 1.17.1?

**Comment by coderbot16** [comment]
Seems like the fix is confirmed on 1.17.1+:
![image](https://user-images.githubusercontent.com/22420959/166083259-42e55115-bd79-47bb-9210-6c75550ee373.png)
