### ISSUE TITLE
Could not load configuration file (after Sodium+Iris install)

### ISSUE THREAD

**Issue by didier** [IrisShaders/Iris#1319]
### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

macOS Monterey 12.2.1

### What is your GPU?

Apple M1 Pro

### Java Version

Java 16

### Reproduction Steps

1. Start the game from the Sodium profile in the Minecraft launcher.
2. Game Crashes with this screen:
![CleanShot 2022-03-13 at 17 50 22](https://user-images.githubusercontent.com/9499859/158070241-fb28b28b-dfbc-480a-a3a1-38ca185f2801.png)

### Additional context

Note: 'restore defaults' does *not* work, and crashes the game.

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/blob/dc417f4b65648f7e17ad021fb71db72969193140/docs/usage/drivers.md?plain=1#L17

**Comment by coderbot16** [comment]
You need to attach a crash report and/or log file.
