### ISSUE TITLE
Help. What can I do to stop ptgi shaders from having the vanilla textures on Iris

### ISSUE THREAD

**Issue by whenthedoodoo** [IrisShaders/Iris#1321]

**Comment by IMS212** [comment]
Please stop making new issues on this.

**Comment by whenthedoodoo** [comment]
My bad.

**Comment by whenthedoodoo** [comment]
Still. I still want to figure out how to solve the issue. Apparently the
shader isn’t even being used although I am enabling the shader. When I
check the f3 menu, it says I’m using no shaders, but when I go to my shader
page, I see the shader is enabled.
