### ISSUE TITLE
Transparent Shulker Head Texture

### ISSUE THREAD

**Issue by wsesrdtf** [IrisShaders/Iris#1329]
### What happened?

I am using iris with sodium for 1.18.2 version.

If the shulker head texture is made transparent, 
the shulker head will come out black instead of transparent.

When I tested the same shader in Optifine, 
there were no problems.
Therefore, I think it is a bug of Iris and report it here.

### Screenshots

![2022-03-20_04 58 39](https://user-images.githubusercontent.com/101512862/159140995-9773cc48-17d9-4642-b062-ca83429758b1.png)
![2022-03-20_04 58 40](https://user-images.githubusercontent.com/101512862/159140996-6e464029-d02b-4bac-9132-42b1c343278f.png)
↑ Using shaders with iris

![2022-03-20_05 00 24](https://user-images.githubusercontent.com/101512862/159141001-3b42cf0d-18bb-45c8-bbdf-1fbf4df55d03.png)
↑ Shaders off

### Relevant log output

```shell
https://drive.google.com/file/d/1soIPeXNw9MeWFSLN4jhZOw8NWwfpMyTA/view?usp=sharing
```

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 10

### What is your GPU?

AMD RX580 8GB

### Java Version

Version 8 Update 321 Build 1.8.0_321-b07

**Comment by coderbot16** [comment]
Closing due to no response.
