### ISSUE TITLE
Remove the shadow from the free camera

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1347]
Remove the shadow from the [free camera](https://www.curseforge.com/minecraft/mc-mods/free-cam), Because normally it is invisible

![2022-04-03_14 43 04](https://user-images.githubusercontent.com/68275908/161428628-4b4281aa-30c2-4f3d-a726-d0db6b72d563.png)

![2022-04-03_14 44 45](https://user-images.githubusercontent.com/68275908/161428705-70288245-6c68-4111-acdf-0d50875cc395.png)

**Comment by AlsoSylv** [comment]
This doesn't actually describe the requested feature, this is just a statement that would require use to download and test the mod to understand

**Comment by Lolothepro** [comment]
Yes, but this is not a bug, nor a crash.

**Comment by AlsoSylv** [comment]
You still need to describe the request in detail.

**Comment by AlsoSylv** [comment]
This doesn't follow the feature request form, either, redo it to follow the form, or the issue will be closed

**Comment by coderbot16** [comment]
https://github.com/hashalite/Freecam/blob/main/src/main/java/net/xolt/freecam/util/FreeCamera.java

**Comment by coderbot16** [comment]
This should be fixed in the other mod. https://github.com/hashalite/Freecam/issues/19
