### ISSUE TITLE
Rain is broken on Sildur's Vibrant Shaders

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#135]
Related to https://github.com/IrisShaders/Iris/issues/61

**Comment by IMS212** [comment]
This is easily fixed by clearing buffer 7.

**Comment by iMoobert** [comment]
Sorry to resurrect an old thread, but what is 'buffer 7', and how do I clear it?

I'm not familiar with coding, and googling "Minecraft shaders how to clear buffer 7" doesn't help at all.

Are you talking about clearing your GPU's shader cache, or does it have to do with minecraft files specifically?

Also, I assume this is what @coderbot16 was talking about with broken rain,
![2024-01-14_15 58 21](https://github.com/IrisShaders/Iris/assets/55117135/b5a571a0-0558-4101-ada7-4beaf79648c2)

But on the off-chance it wasn't, is there any way to fix this issue? The rain has no texture so it appears grey, and it's super distracting against darker backgrounds

**Comment by IMS212** [comment]
This is a bug in Sildur's itself, and is unrelated.

**Comment by iMoobert** [comment]
Ah, so there's no way of fixing it? If I want to use Sildur's I'll have to deal with this forever then?

**Comment by Xtrye34** [comment]
@IMS212 @iMoobert  sorry i dont get anything of what you said,  what is clearing buffer 7? i have a bug with this shaders and i dont know if i can fix it.

here is an example of what happened with my game 

![bug rain](https://github.com/IrisShaders/Iris/assets/173972314/3150e4d9-cb78-49cf-9d67-a9405313ebcb)

**Comment by voywaw** [comment]
> [@IMS212](https://github.com/IMS212) [@iMoobert](https://github.com/iMoobert) sorry i dont get anything of what you said, what is clearing buffer 7? i have a bug with this shaders and i dont know if i can fix it.
> 
> here is an example of what happened with my game
> 
> ![bug rain](https://github.com/IrisShaders/Iris/assets/173972314/3150e4d9-cb78-49cf-9d67-a9405313ebcb)

Do you have ars noveau in your mods folder? if you have it, try to delete this mod and summon rain to see again if this works
