### ISSUE TITLE
The water in Shaders Disabled mode is solid-looking when VanillaTweaks's Clearer Water Resource Pack is installed.

### ISSUE THREAD

**Issue by melechdaviid** [IrisShaders/Iris#1353]
### What happened?

When the Vanilla Tweaks Clearer Water Resource Pack is installed, the water turns solid. Also, Waving Leaves and Waves on the water do not work. 

### Screenshots

![2022-04-07_20 28 11](https://user-images.githubusercontent.com/103229195/162345528-d0d1ba8b-f8cf-4b65-8afb-1152861856bc.png)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

Nvidia GEForce RTX 2060

### Java Version

Java 16

**Comment by coderbot16** [comment]
VanillaTweaks is using core shaders, which are not compatible with Sodium (when applied to terrain) or Iris (when a shader pack is active). This isn't something we can sensibly fix.

**Comment by melechdaviid** [comment]
Ah. I’d sent the issue to the VT team before reading this, so they know too.
