### ISSUE TITLE
Some particles are transparent (SEUS V11)

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1358]
### What happened?

Some particles are transparent 

https://user-images.githubusercontent.com/68275908/162610150-ce3283cb-f39d-42b6-8b16-9c8b36ca9308.mp4

### Minecraft Version

Minecraft 1.18.2/22w14a

### Iris Version

Iris 1.2.2/Iris 1.2.3

### Sodium Version

sodium 0.4.1

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by coderbot16** [comment]
Please test on OptiFine and show that it does not happen there

**Comment by Lolothepro** [comment]
This does not happen with Optifine

**Comment by coderbot16** [comment]
Screenshot?

**Comment by Lolothepro** [comment]
Iris or Optifine or both?

**Comment by coderbot16** [comment]
OptiFine to see how it renders the particles

**Comment by Lolothepro** [comment]
No

https://user-images.githubusercontent.com/68275908/162627496-00f07fd6-d33b-4316-99b2-c8d7fbe330b5.mp4

**Comment by coderbot16** [comment]
This should be fixed in recent Iris versions due to https://github.com/IrisShaders/Iris/commit/25305e9931a15ccab11c6f524da174abf9fb7873.
