### ISSUE TITLE
Regular Crash due to shader linking

### ISSUE THREAD

**Issue by WoMspace** [IrisShaders/Iris#1359]
### Minecraft Version

Minecraft 1,18,2

### Iris Version

iris-mc1.18.2-1.2.2-build.32.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 11

### What is your GPU?

Radeon RX 5700 XT

### Java Version

Adoptium Java 17

### Reproduction Steps

1. Load a world, either server or singleplayer.
2. Enable any of the unsupported shaders.
3. Expect shaders to be disabled.
4. Game hard crashes.

### Additional context

LATEST.LOG
https://gist.github.com/WoMspace/544d51a24a911148c23d1b8d7fe70f24

CRASH REPORT
https://gist.github.com/WoMspace/dcd8aacbffce282c91e7b94d10d25eb9

**Comment by coderbot16** [comment]
I'm seeing some #include issues with Continuum 2.1 Alpha which might be fixed in the dev branch, some issues with loading Epoch which seem to be some sort of Epoch issue, and this final fatal crash with SoftVoxels appears to be a case of https://github.com/IrisShaders/Iris/issues/937.

**Comment by coderbot16** [comment]
Yep, seems like that's the error message that happens when multiple fragment shader color outputs are bound to the same location, so closing this in favor of the other issue.

**Comment by WoMspace** [comment]
Ok Thank you!
