### ISSUE TITLE
1.18.2 crashed when shaders got applied

### ISSUE THREAD

**Issue by KB-Q** [IrisShaders/Iris#1379]
### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.2-build.32

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

Intel UHD graphics 620, Nvidia GeForce MX150

### Java Version

Java 17

### Reproduction Steps

Game crashed when trying to apply MakeUp-UltraFast-7.03b shaders.

### Crash Report file and latest.log

[crash-2022-04-24_16.56.56-client.txt](https://github.com/IrisShaders/Iris/files/8549555/crash-2022-04-24_16.56.56-client.txt)
[latest.log](https://github.com/IrisShaders/Iris/files/8549557/latest.log)

**Comment by IMS212** [comment]
Could you send a log file with debugging on? (Go to .minecraft/config/iris.properties, open it with a text editor, and set enableDebug to true while the game is off)

**Comment by coderbot16** [comment]
Caused by https://github.com/IrisShaders/Iris/issues/937
