### ISSUE TITLE
Missing information about how to install the Shaderpacks

### ISSUE THREAD

**Issue by SirPytan** [IrisShaders/Iris#139]
I found this section in the IrisConfig file, but I have no clue what the right path is, to work, or if I need unzip it and so on.
`	public IrisConfig() {
		shaderPackName = "../shaderpacks/Sildurs Vibrant Shaders v1.283 High.zip";
		propertiesPath = FabricLoader.getInstance().getConfigDir().resolve("iris.properties");
	}`

**Comment by CraftalotReloaded** [comment]
Sildurs Vibrant Shaders v1.283 High.zip
Without any quotes should work

**Comment by SirPytan** [comment]
First thanks for the quick response.
Second without any quotes I get compiler errors.

**Comment by SirPytan** [comment]
Where do I need to place the shaderpack? In the default shaderfolder?

**Comment by CraftalotReloaded** [comment]
This is all there should be in your config aside from some comments:
shaderPack=Sildurs Vibrant Shaders v1.283 High.zip

**Comment by SirPytan** [comment]
When I do that, the compiler complains, I will try it and post it here.

**Comment by CraftalotReloaded** [comment]
Don't upload it here if it's large, upload it to pastebin or similar instead

**Comment by SirPytan** [comment]
> Configure project :
Fabric Loom: 0.5.43 Build(release #43)
:setting up loom dependencies
:setting up mappings (yarn 1.16.4+build.6)

> Task :compileJava
D:\MINECRAFT\1.16.x\Mods\Fabric\Iris-sodium-compatibility\src\main\java\net\coderbot\iris\config\IrisConfig.java:24: error: ';' expected
                shaderPackName = Sildurs Vibrant Shaders v1.283 High.zip;
                                        ^
D:\MINECRAFT\1.16.x\Mods\Fabric\Iris-sodium-compatibility\src\main\java\net\coderbot\iris\config\IrisConfig.java:24: error: ';' expected
                shaderPackName = Sildurs Vibrant Shaders v1.283 High.zip;
                                                        ^
D:\MINECRAFT\1.16.x\Mods\Fabric\Iris-sodium-compatibility\src\main\java\net\coderbot\iris\config\IrisConfig.java:24: error: not a statement
                shaderPackName = Sildurs Vibrant Shaders v1.283 High.zip;
                                                         ^
D:\MINECRAFT\1.16.x\Mods\Fabric\Iris-sodium-compatibility\src\main\java\net\coderbot\iris\config\IrisConfig.java:24: error: ';' expected
                shaderPackName = Sildurs Vibrant Shaders v1.283 High.zip;
                                                           ^
D:\MINECRAFT\1.16.x\Mods\Fabric\Iris-sodium-compatibility\src\main\java\net\coderbot\iris\config\IrisConfig.java:24: error: not a statement
                shaderPackName = Sildurs Vibrant Shaders v1.283 High.zip;
                                                                    ^
5 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception

**Comment by IMS212** [comment]
That’s not what they meant. You shouldn’t be changing the source code, but rather the config\iris.properties file in the .minecraft folder.

**Comment by SirPytan** [comment]
Oh, ok.

**Comment by SirPytan** [comment]
Thats, why there should be instructions about this.

**Comment by IMS212** [comment]
> If you are not a developer or familiar with compiling and running Minecraft mods from source, OptiFine is likely the better choice in the immediate moment. Once Iris is ready for more widespread use, precompiled builds will be published and distributed.
Iris basically isn’t really meant for use at the moment by the general user. Giving instructions would only encourage more use of it, and more people complaining about no shadows and such when it’s clearly stated lots of stuff is missing.

**Comment by SirPytan** [comment]
Yes, I understand, but this mod is listed everywhere as a good Optifine/Optifabric alternative, but there is no video or detailed information on how to use it yet. I know it is still very early, but because it is open source, showing it more to the public would help to get more people to help on the development.

**Comment by IMS212** [comment]
sadly once that happens I believe the majority of users will be people who don’t know much about mods, and will eventually come here complaining about no shadows and stuff because they didn’t read the README. Maybe I’m wrong, but that’s what I personally think will happen

**Comment by SirPytan** [comment]
I now use Sodium, Lithium and Starlight (also still in early development) and Iris, in that way I have a very good base of speed to add more performance heavy mods on it.

But, yes, maybe, I think the best is to put a big Disclaimer ontop of it, to prevent normal people from complaining about it.

**Comment by SirPytan** [comment]
I might make a video about it, if I have some time, because getting Sodium with Shaders to work is not so easy, there are basically no options except this mod. There might be still that Canvas mod, but it is not compatible with the Optifine shaders.

**Comment by IMS212** [comment]
Yes, canvas is intended to be a brand new shader system, and is more stable in general along with having some nice shaders with shadows and such, and it is recommended to use it over Iris for now. Nevertheless, I honestly see iris as a transitionary mod, to let the optifine userbase switch to open source while canvas matures and gains more shader support. However, if you do eventually plan to make a video on Iris, I’d recommend you put a disclaimer at the beginning so people know what they’re getting into.

**Comment by RDKRACZ** [comment]
Canvas is a great project but it probably won’t even be compatible with Sodium so I wouldn’t call Iris just a transitionary mod

**Comment by IMS212** [comment]
I mean... canvas doesn’t need to be compatible with sodium to still become the main mod. Besides, canvas still has a very different goal atm of giving authors more control over shaders

**Comment by SirPytan** [comment]
I mean, after Iris works with all Optifine shaders, more controll options for Programmers could be integrated and in that way, they only need to dedect if it is used by Optifine or Fabric and could disable certain features for one version, in this way they don't have much more work, to bring a shader to both systems. So I think, Iris will first have a happy co-existence and maybe later make cavas concurrence or it could team up with canvas maybe.

**Comment by IMS212** [comment]
Possibly, it is explained in the README that there could be collaborations in the future.

**Comment by coderbot16** [comment]
Iris is not really ready for normal use yet. In the future there will be a configuration screen to remove the need to edit config files.
