### ISSUE TITLE
Significant Performance drop when looking away from sun/moon

### ISSUE THREAD

**Issue by Blue-Drive** [IrisShaders/Iris#1393]
### What happened?

Framerate when looking away from sky light source is significantly lower then when it's on screen/nearly on screen. I've tested with only Iris+sodium, with both Sildur's and Complementary shaders, and in both 1.18 and 1.17. In one scene it went from 130 to 77fps, and in another lower resolution test it began at 243 and was lowered to 139 with the sun behind the player. I'm aware this might just be how Iris or shadow frustrum culling works, I don't know that much about it.

### Screenshots

![20220427185027_1](https://user-images.githubusercontent.com/91779460/165749206-e1192c96-fd7c-4ac0-9a75-8b0b08b13e49.jpg)
![20220427185041_1](https://user-images.githubusercontent.com/91779460/165749219-134cd94c-cb5e-4edb-a06a-00a317a622fb.jpg)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.4-build.38.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3080

### Java Version

Java 17

**Comment by AlsoSylv** [comment]
This is because of how shadow culling works, less shadows are in the players view when looking at the sun then when away from the sun.
