### ISSUE TITLE
Font breaks when shader is on

### ISSUE THREAD

**Issue by issac4892** [IrisShaders/Iris#1399]
### What happened?

I'm not really sure, but i think it's a iris bug
When I turn on the Shader, fonts break.

### Screenshots

![image](https://user-images.githubusercontent.com/56223465/166108797-7da92d8d-acfe-4048-a3a6-a835613b488f.png)
![image](https://user-images.githubusercontent.com/56223465/166108804-09d6a1c5-928e-4891-b1a0-a4e96b5edf35.png)

### Minecraft Version

1.18.2

### Iris Version

1.2.2-build.32

### Sodium Version

0.4.1+build.15

### Operating System

windows 11

### What is your GPU?

amd rx 5700

### Java Version

17

**Comment by AlsoSylv** [comment]
What resource pack are you using for fonts?

**Comment by issac4892** [comment]
> What resource pack are you using for fonts?
[Mc둥근모.zip](https://github.com/IrisShaders/Iris/files/8597103/Mc.zip)

**Comment by coderbot16** [comment]
Cannot replicate the issue. Ensure you are on Iris 1.2.4, and if the issue still happens, you'll need to ensure you're testing with only Iris and Sodium. If you can provide a consistent way to replicate this issue, please let me know and I will reopen the issue.

![image](https://user-images.githubusercontent.com/22420959/166116639-2903e616-2712-4fbe-88b7-f05e8a6e2ffa.png)
