### ISSUE TITLE
Can't disable vanilla fog

### ISSUE THREAD

**Issue by kingarthur0975** [IrisShaders/Iris#1402]
### What happened?

I'm attempting to use Iris with Distant Horizons, a mod that renders a low-quality version of the world outside of render distance. The mod is supposed to disable vanilla fog (I'm playing with shaders disabled) but because of Iris it does not. There also isn't an option to disable fog in video settings.

### Minecraft Version

Minecraft 1.18.0

### Iris Version

iris-mc1.18.1-1.2.0.pre.jar

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1660

### Java Version

Java 17

**Comment by kingarthur0975** [comment]
If necessary I can provide screenshots.

**Comment by IMS212** [comment]
Distant Horizons itself is not compatible with Iris for *many* reasons, see #1289.

**Comment by coderbot16** [comment]
This seems like a separate issue from conflicts with shaders enabled... I wouldn't expect Iris in a disabled state to actively conflict with other mods. I think we'd need input from the DH devs on why this might happen, though.

**Comment by coderbot16** [comment]
Actually, I think I know what this is, and I think I might have actually just fixed it on accident while trying to fix an issue with FabricSkyboxes... We're always rendering the fog-colored horizon box even with shaders disabled. So making it only render with shaders enabled will solve that problem.

**Comment by coderbot16** [comment]
This should be fixed in the next release. Thanks for the report.

**Comment by kingarthur0975** [comment]
Thanks. Just wondering, will the next release of Iris be compatible with all version of 1.18, or only 1.18.2? I ahve a big fabric modpack thats 1.18.0 and I dont wanna update all of them

**Comment by coderbot16** [comment]
The last release of Iris supporting 1.18.1 was Iris 1.2.0. We only generally support the latest minor version of any given Minecraft version, and intend to only officially support 1.18.2, 1.17.1, and 1.16.5 in the next release.

**Comment by kingarthur0975** [comment]
Damn. Well, thanks for fixing the issue!

**Comment by coderbot16** [comment]
Reopening since this technically hasn't made it into a release - it will be closed once Iris 1.2.5 is released.
