### ISSUE TITLE
Transparency issue with water 

### ISSUE THREAD

**Issue by WhiteYeeyeeMan** [IrisShaders/Iris#1407]
### What happened?

Any water flowing from a source block going down gives me this weird "border" like effect that disturbs the transparency of the water
Shader used: 
Complementary Shaders_v4.0.2
Same issue repeated with other shaders and 
ComplementaryShaders_v4.0.2

Mods:
BetterF3-1.2.4-Fabric-1.18.2
cloth-config-6.2.57-fabric
fabric-api-0.51.1+1.18.2
FPS-Monitor-1.18.2-1.2.1
iris-mc1.18.2-1.2.4-build.38
lazydfu-0.1.2
lithium-fabric-mc1.18.2-0.7.9
logical_zoom-0.0.14
malilib-fabric-1.18.2-0.12.1
minihud-fabric-1.18.2-0.22.0
modmenu-3.0.1
phosphor-fabric-mc1.18.x-0.8.1
sodium-fabric-mc1.18.2-0.4.1+build.15

### Screenshots

![image](https://user-images.githubusercontent.com/104828733/166431484-2f28d939-70c1-4744-962a-8519eb166e79.png)
![image](https://user-images.githubusercontent.com/104828733/166431514-6c79a0d1-82e1-4a18-becf-b60a3e15f663.png)

### Relevant log output

```shell
N/A
```

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.4-build.38

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

RTX 2060 Super

### Java Version

Java 8

**Comment by Xyphyn** [comment]
Same issue.

**Comment by coderbot16** [comment]
This is a bug in Sodium, there's nothing that Iris can do about it: https://github.com/CaffeineMC/sodium-fabric/issues/38
