### ISSUE TITLE
The liquid behind the glass is rendered incorrectly

### ISSUE THREAD

**Issue by shenjackyuanjie** [IrisShaders/Iris#1413]
### What happened?

The liquid behind the glass is rendered incorrectly

### Screenshots

https://www.bilibili.com/video/BV1TF41177RF/

### Relevant log output

```shell
no log, just render bug
```

### Minecraft Version

fabric 1.16.5

### Iris Version

iris 1.2.4 build 36

### Sodium Version

1.16.5 2.0.0+rev.f24b4ca (by replaymod.com

### Operating System

win10 x64

### What is your GPU?

AMD RX550 4G

### Java Version

java17.0.3

**Comment by coderbot16** [comment]
This is not an Iris bug: https://github.com/CaffeineMC/sodium-fabric/issues/38
