### ISSUE TITLE
Reflections on Seus PTGI HRR 2.1 (Glass and Water) break when using textures above x16 resolution

### ISSUE THREAD

**Issue by Vir7ualll** [IrisShaders/Iris#1418]
### What happened?

When looking at reflections through glass or water on HRR 2.1 while using texture packs higher than the vanilla x16, the reflections break and zoom on what appears to just be a corner of the texture. 

### Screenshots

![2022-05-12_13 59 18](https://user-images.githubusercontent.com/89110960/168141553-f60bc5c5-8019-41d5-a658-03df82fa7849.png)
This is the reflection using just vanilla block textures. They reflect properly, whole texture.
![2022-05-12_14 00 21](https://user-images.githubusercontent.com/89110960/168141646-0cfe323a-0cfe-485e-8415-9eb8234a39af.png)
This is using Compliance/Faithful x64 (https://faithfulpack.net/), you can visibly see the crude zooming in on the texture in the reflection
![2022-05-12_14 01 29](https://user-images.githubusercontent.com/89110960/168141855-888879b8-2e5b-4485-b37f-ff4e0d1c829d.png)
This is using LPBR Reload
![2022-05-12_14 06 36](https://user-images.githubusercontent.com/89110960/168142989-335182ac-61f0-4987-9ae8-ddf8895e1517.png)
This is a water reflection using Complementary 4.4 and Compliance/Faithful x64, the textures render properly in the reflection (did not take a glass one as it is hard getting a good looking glass reflection on Complementary)

### Minecraft Version

1.18.2

### Iris Version

Iris 1.18.2 1.1.4

### Sodium Version

1.18.2 0.4.1 build 15

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1650ti

### Java Version

Java 17.0.1

### Additional context

Optifine is interesting in its behaviour as well. Water reflections appear to be proper when not viewing them directly but break when looking directly. Glass reflections also have what I can describe as more breakage
_No response
![2022-05-12_14 35 24](https://user-images.githubusercontent.com/89110960/168145299-310d7f55-0ecf-4f8c-82bd-1bc3830f8819.png)
![2022-05-12_14 35 28](https://user-images.githubusercontent.com/89110960/168145306-47d6ee0d-00cb-4290-8dbd-0a49a1c7d5a7.png)
Here is the glass reflection screenshot
![2022-05-12_14 33 36](https://user-images.githubusercontent.com/89110960/168145452-e06e3594-d803-4f28-9edf-873270c78e42.png)
These were taken using Optifine U H7 for 1.18.2
_

**Comment by PercentBoat4164** [comment]
I do not believe this is a bug. This is intended behavior for SEUS PTGI. There is a setting for texture pack resolution. Make sure you change it to the correct resolution, then textures should reflect properly.
![Screenshot from 2022-05-12 23-08-11](https://user-images.githubusercontent.com/51725924/168203659-c05078e6-aad8-4ee2-bee6-5b54ffa4fbca.png)

**Comment by Vir7ualll** [comment]
this indeed helped! Sorry for the issue I really had no clue about this
