### ISSUE TITLE
Fishing rod hooks to other users' rods

### ISSUE THREAD

**Issue by orvitpng** [IrisShaders/Iris#1428]
### What happened?

Inside of multiplayer (tested on LAN and Spigot), Iris will connect fishing rods with other rods creating multiple lines.

To reproduce, just use your fishing rod right next to someone else and they will connect.

### Screenshots

![Screenshot from 2022-05-15 12-53-56](https://user-images.githubusercontent.com/55005263/168486942-3c3050a2-a347-4849-8e27-fff91ed8cf42.png)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.4-build.38.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Arch Linux

### What is your GPU?

Nvidia GeForce RTX 3060

### Java Version

Java 17

**Comment by IMS212** [comment]
#1055 duplicate

**Comment by orvitpng** [comment]
Hmm I did a GitHub search for anything containing "fishing" and didn't find anything, interesting.
