### ISSUE TITLE
Glass is WATER

### ISSUE THREAD

**Issue by KpauMupa** [IrisShaders/Iris#143]
Haha glass goes squish-squish
![изображение](https://user-images.githubusercontent.com/76217453/109549240-c583a700-7ade-11eb-90f6-feba1cd1d2b3.png)
![изображение](https://user-images.githubusercontent.com/76217453/109549264-ccaab500-7ade-11eb-9f54-accc1fdb9cea.png)
This is really fun =)
I'm a linux user now btw! Did not test this on windows... Sildur's Vibrant Lite ONLY iris.
With iris-sodium compatibility+modded sodium there is no such issue.

 (Btw, Coderbot, i've downloaded the latest sodium iris-compat., but i can't build it! As usual, 'gradlew build', and... error! Same on windows! I still can compile the regular Iris/Iris sodium-compat mod :/)

**Comment by KpauMupa** [comment]
I can't provide any videos, but trust me - the glass is water. it's animated and reflections are the same as on the water =)))

**Comment by IMS212** [comment]
This is known and on purpose, trunk sets all translucent objects to water since mc_entity is not implemented yet. This is solved when using sodium and the sodium compatibility branch.

**Comment by IMS212** [comment]
For building sodium, you need to place a compiled Iris sodium-compatibility jar in sodium-fabric\.gradle\loom-cache\remapped-mods, replacing sodium-fabric with where the sodium source code is.

**Comment by coderbot16** [comment]
IMS is correct. This root issue here is being tracked in #144

**Comment by KpauMupa** [comment]
> For building sodium, you need to publish the Iris sodium-compatibility jar to the local maven otherwise it will give an error.

Oh, i really forgot about this since i compiled the mod last time! Thank you!

**Comment by KpauMupa** [comment]
> For building sodium, you need to publish the Iris sodium-compatibility jar to the local maven otherwise it will give an error.

Uh, oh... Excuse me, but where do i need to put my generated iris sodium-compat. mod version in the sodium-fabric-1.16.x folder?
![изображение](https://user-images.githubusercontent.com/76217453/109555030-18ad2800-7ae6-11eb-990a-cc59fe6288c9.png)

**Comment by KpauMupa** [comment]
> For building sodium, you need to publish the Iris sodium-compatibility jar to the local maven otherwise it will give an error.

Uh, oh... Excuse me, but where do i need to put my generated iris sodium-compat. mod version in the sodium-fabric-1.16.x folder?

**Comment by zeta-xenia** [comment]
> > For building sodium, you need to publish the Iris sodium-compatibility jar to the local maven otherwise it will give an error.
> 
> Uh, oh... Excuse me, but where do i need to put my generated iris sodium-compat. mod version in the sodium-fabric-1.16.x folder?
> ![изображение](https://user-images.githubusercontent.com/76217453/109555030-18ad2800-7ae6-11eb-990a-cc59fe6288c9.png)

I remember there is a gradle task named `publishToMavenLocal', running `gradle publishToMavenLocal' under the root directory of a compiled sodium-compatible branch Iris repository will do the job (probably) and then go compile the iris-compatible sodium.
