### ISSUE TITLE
Separate entity batching

### ISSUE THREAD

**Issue by HyperSoop** [IrisShaders/Iris#1430]
The entity batching optimization is really useful in scenarios like minigame lobbies, bringing a 1.5x and more FPS increase. The thing it, it does not really belong to Iris. 
It would be better to release it as a separate optimization mod, in case it's needed alone without the shaders functionality.

**Comment by LizIsTired** [comment]
Why does it need to be seperate? Iris has negligible performance downsides when not using shaders so I don't see why you would want one and not the other? You can just disable shaders?

**Comment by coderbot16** [comment]
You've stated two sizable claims:

> it [Batched Entity Rendering] does not really belong to Iris.

> It would be better to release it as ... separate

But, I don't think you've really justified them adequately. Here's some reasons why I would disagree with them:

- Iris is dependent on the optimizations in Batched Entity Rendering for its shadow pass to perform well. If we were to not include BER in Iris, then either people would have to download it separately like with Sodium, or it would be optional and people might miss out on the optimization for no particularly good reason.
- Iris currently interfaces somewhat closely with implementation details of Batched Entity Rendering to enable the current implementations of certain features in shader-based rendering. This is possible to fix, but would be extra work.
- I'm not aware of anyone outside of the Iris development team interested in maintaining Batched Entity Rendering, so there wouldn't be the usual development benefit (allowing devs to work on separate features in parallel) to having it as a separate mod.
- Iris is a very common mod in Fabric / Quilt mod packs, so including things like Batched Entity Rendering, particle rendering fixes, mipmapping fixes, and similar things in Iris ensures that they'll reach many people. When left as separate mods, it's less likely that people will benefit.
- As Liz stated, Iris is designed to have minimal performance impact with shaders disabled, so if Batched Entity Rendering is desired without shaders, you can just run Iris with shaders disabled.

**Comment by coderbot16** [comment]
If you're asking about releasing Batched Entity Rendering as a separate mod in addition to keeping it in Iris, that would just be additional maintenance work that I'm not interested in. Since Iris & BER are under LGPLv3, someone else could go through the process of maintaining separate mod releases for BER if they really wanted to. But with what I've stated above, I'm not sure if it would be worth their while.
