### ISSUE TITLE
Shader options?

### ISSUE THREAD

**Issue by RealFX-Code** [IrisShaders/Iris#1433]
**Is your feature request related to a problem? Please describe.**
Welp, I'm finally writing this. Hey, I'd like to see a "Shaders options" button which allows you to change a specific shaderpack's options. I've seen forks of iris do that, But they're all outdated now.

**Describe the solution you'd like**
I'd like a button to be added where you can change shaderpack options like in optifine.

**Describe alternatives you've considered**
I've considered changing back to the old fork of iris, Starline. But that isn't supported on 1.18.2 so I won't download it.

**Additional context**
Welp, Is there any more context to this?

**Comment by AlsoSylv** [comment]
This is already in the latest release of iris

**Comment by RealFX-Code** [comment]
> This is already in the latest release of iris

Guess it's time to update then. I though it'd say when there was an update available, But I guess not.

Thanks for the answer!

**Comment by AlsoSylv** [comment]
An update checker is in the works already :)
