### ISSUE TITLE
Pipe crash (modern dynamics, carpet, redstone spam)

### ISSUE THREAD

**Issue by FluffyBumblebees** [IrisShaders/Iris#1441]
### Minecraft Version

1.18.2

### Iris Version

1.2.4

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

windows 10

### What is your GPU?

Nvidia 1660ti

### Java Version

java 17

### Reproduction Steps

1. Get linkage of item transfer pipe from modern dynamics
2. Have pushable tile entities ON
3. use complementary shaders
4. keep spamming piston to move a pipe
5. try to place a pipe in the way of the piston push
6. crash (nullpointerexception)

### Crash Report file and latest.log

```shell
https://gist.github.com/FluffyBumblee/48c915989a589a94738b2160c46ee89a
```

**Comment by FluffyBumblee** [comment]
Why did I do this? I tried to intentionally cause some weird bug lol.

**Comment by coderbot16** [comment]
Please test without NotEnoughCrashes, it's known to cause a lot of problems with Iris since it leaves the game in an inconsistent state.
