### ISSUE TITLE
More working shaders to add to supportedshaders.md

### ISSUE THREAD

**Issue by mutageneral** [IrisShaders/Iris#1448]
I tried a lot of shaders and ended up finding 5 shaders packs that seems to work well under Iris that were not listed in [Iris/docs/supportedshaders.md](https://github.com/IrisShaders/Iris/blob/trunk/docs/supportedshaders.md#a-the-following-shaders-have-been-tested-and-work-well)
I tested the latest version of all listed shaders with the Fabric 1.18.2 and the latest Iris version.

[SORA Shaders](https://www.curseforge.com/minecraft/customization/sora-shaders): Has a message saying it is compatible with Iris in the curseforge description.
![SORA_2022-05-21_18 52 04](https://user-images.githubusercontent.com/62779748/169672940-73277db5-4887-4309-ab11-e37d2d74867a.jpg)

[Simplicissimus Shader](https://www.curseforge.com/minecraft/customization/simplicissimus-shader):
![Simplicissimus_2022-05-21_18 47 53](https://user-images.githubusercontent.com/62779748/169672944-9eab16fa-b765-42e9-8941-01f03aa5b791.png)

[Beyond Belief Shaders](https://www.curseforge.com/minecraft/customization/beyond-belief-shaders): Based of SEUSv11
![Beyond_Belief_2022-05-21_18 54 55](https://user-images.githubusercontent.com/62779748/169672946-b46d8888-1baf-4e33-a2df-6e41fc8380ed.png)

[Oceano Shaders 3.0](https://www.curseforge.com/minecraft/customization/oceano-shaders):
![Oceano Shaders 3 0](https://user-images.githubusercontent.com/62779748/169672958-fbf296f8-8137-484e-b71a-a0078ece9c48.png)

[RRe36's Shader](https://www.curseforge.com/minecraft/customization/rre36s-shader): This shader is discontinued and will not have new updates, but RRe36's newer shaders all don't work in Iris. (Other than Simplicissimus, but I already listed it, and they look very different.)
![RRe36's Shader](https://user-images.githubusercontent.com/62779748/169672960-5905755e-9820-470e-b1da-54d320492690.png)

**Comment by coderbot16** [comment]
Thanks for the investigation. SORA and Oceano were already listed, I added Beyond Belief and RRe36's Shader in https://github.com/IrisShaders/Iris/commit/70f57b62ed75bb92c4c625eac555d5b8a07c1720, but Simplicissimus Shader doesn't work on current Iris:

![image](https://user-images.githubusercontent.com/22420959/169675828-8358a000-a53b-462a-9eb0-7116ced89fdc.png)
