### ISSUE TITLE
[IMMERSIVE PORTAL] When the fallback system is only active in the Nether and a Nether portal is in the field of view, hand rendering is not activated.

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1450]
### What happened?

[IMMERSIVE PORTAL] When the fallback system is only active in the Nether and a Nether portal is in the field of view, hand rendering is not activated.

(reproducible with Beyond Belief Shaders)

https://www.veed.io/view/2f58fd81-67a7-43c0-8a99-fed6b8a5c195?sharingWidget=true

### Screenshots

![2022-05-22_10 05 33](https://user-images.githubusercontent.com/68275908/169685094-3941d3c0-465e-4842-90ac-f54be1fe022f.png)

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc-1.18.2

### Sodium Version

sodium 0.4.1

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by maximumpower55** [comment]
This is really not fixable by us nor immersive portals

**Comment by maximumpower55** [comment]
Since iris is not designed to have mutiple pipelines being used at the same time
