### ISSUE TITLE
Text on signs with glow ink doesn't appear correctly

### ISSUE THREAD

**Issue by Raphoulfifou** [IrisShaders/Iris#1452]
### What happened?

The signs where the text is glowing appears black

### Screenshots

What it looks llike
![2022-05-22_14 35 02](https://user-images.githubusercontent.com/81476169/169695605-e5e1144c-1c1b-4dc5-b061-8f3010057928.png)
What it should look like
![2022-05-22_14 35 09](https://user-images.githubusercontent.com/81476169/169695623-3a3df8a7-126d-4d88-8a45-e40d21798ad6.png)

### Minecraft Version

1.118.2

### Iris Version

1.2.5-pre-nogit

### Sodium Version

0.4.1+build.15

### Operating System

Windows 11

### What is your GPU?

Nvidi GeForce GTX 1050

### Java Version

Java 17

**Comment by IMS212** [comment]
Can you reproduce this with Complementary Shaders? (This shader is known to have support for glow signs.)

**Comment by Raphoulfifou** [comment]
This is (the 1st picture) with complementary

**Comment by Raphoulfifou** [comment]
The bug doesn't appear on newer dev versions, so I'm gonna close the issue

**Comment by Raphoulfifou** [comment]
The bug doesn't appear on newer dev versions, so I'm gonna close the issue
