### ISSUE TITLE
1.18.2 Enchantment Glint and World Border not rendering (Sildurs Enhanced Default / TEA Shaders)

### ISSUE THREAD

**Issue by Flohp2** [IrisShaders/Iris#1454]
### What happened?

Was using TEA shaders and found this issue with the enchant glint and world border not being visible, so I switched to Sildurs as it was listed as supported and found the same issue there. Just wanted to send it in, as I'm sure it isn't too hard a fix and someone may possibly tell me how to fix it myself, which would rule

### Screenshots

![2022-05-22_15 32 38](https://user-images.githubusercontent.com/106035357/169714728-30d668c1-98d2-4039-89da-b9e8fa9b9eed.png)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.4-build.38

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 3070 Ti

### Java Version

Version 8 Update 333

**Comment by coderbot16** [comment]
You can try the Iris 1.2.5 test build on the Discord server in #public-test-builds and see if that fixes it

**Comment by Flohp2** [comment]
> You can try the Iris 1.2.5 test build on the Discord server in #public-test-builds and see if that fixes it

This was indeed fixed on that version. Thank you very much

**Comment by coderbot16** [comment]
Thanks for the confirmation. Since Iris 1.2.5 is now released, this should be fixed.
