### ISSUE TITLE
Iris 1.2.5 made texture that uses RenderType.eyes() a bit darker

### ISSUE THREAD

**Issue by SteveKunG** [IrisShaders/Iris#1458]
### What happened?

After updated to Iris 1.2.5 I noticed mob glowing eyes looks a bit darker. I added comparison pictures to see what actually looks like.

### Screenshots

This is a comparison between Iris 1.2.4 and Iris 1.2.5

![spider_1](https://user-images.githubusercontent.com/6128413/170035291-a313cec4-cbe0-4c5f-81b4-a397bc02c449.png)
![spider_2](https://user-images.githubusercontent.com/6128413/170035306-3cdd448d-2a51-4d60-b078-1033c3393365.png)

![dragon_1](https://user-images.githubusercontent.com/6128413/170035518-5f6954fb-d6eb-4028-8af3-5de7e96c74a6.png)
![dragon_2](https://user-images.githubusercontent.com/6128413/170035522-947d32a6-4d82-4f36-bb81-90b045ad3360.png)

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.2.4-build.38 and iris-mc1.18.2-1.2.5-beta.1

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

Palit GTX 1050Ti

### Java Version

Java 17

### Additional context

This is my custom mod that I created to test out the `RenderType.eyes()`. It looks a bit darker if you zoom close enough.

![steve1](https://user-images.githubusercontent.com/6128413/170035559-b723d053-b271-4395-bb0e-a104b8b1e927.png)
![steve2](https://user-images.githubusercontent.com/6128413/170035565-1a32bf80-a896-4fc0-97bc-2b46d66549e1.png)

**Comment by maximumpower55** [comment]
Im pretty sure this is a placebo, they look the exact same to me, i will compare the rgb values later

**Comment by SteveKunG** [comment]
Here it is, it quite hard to see the difference.

![rgb1](https://user-images.githubusercontent.com/6128413/170263343-831c1cb5-e1bc-4be1-a85b-a9601f418cd7.png)
![rgb2](https://user-images.githubusercontent.com/6128413/170263351-509565fa-2b98-4ec9-beb3-e9f3f1719669.png)

**Comment by coderbot16** [comment]
This is caused by https://github.com/IrisShaders/Iris/blob/trunk/src/main/java/net/coderbot/iris/mixin/rendertype/MixinRenderType_FixEyesTranslucency.java.

We should probably use a BlendModeOverride when shaders are enabled (similar to how the shadow program works) and similar instead of changing the render type.
