### ISSUE TITLE
Weird rendering issues with entities near water

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#146]
![image](https://user-images.githubusercontent.com/22420959/109571932-3dcb7780-7aa1-11eb-9599-ebc726888c6e.png)

![image](https://user-images.githubusercontent.com/22420959/109572003-5b004600-7aa1-11eb-8eac-a0f4274fb15c.png)

![image](https://user-images.githubusercontent.com/22420959/109572040-681d3500-7aa1-11eb-9e1f-d33e335ef20a.png)

**Comment by coderbot16** [comment]
This is because Iris is rendering things in the wrong order normally, due to the way that rendering has been reworked in 1.15. Here is an annotated part of `WorldRenderer#render` for an explanation:

```java
// this is where Iris commits the non-translucent depth texture
// all calls after this point should only be for translucent things
profiler.swap("translucent");
// this is where water is rendered
this.renderLayer(RenderLayer.getTranslucent(), matrices, d, e, f);
// this is where most entity stuff is rendered (including distinctly non-translucent things)
immediate.draw(RenderLayer.getLines());
immediate.draw();
```

**Comment by thedocruby** [comment]
Would this at all happen to be related to issue #19 ?

**Comment by coderbot16** [comment]
While the underlying causes are similar (Blaze3D drawing entities to the screen much later than when the entity rendering calls actually happen), the effects are unrelated with Sildur's Vibrant Shaders. Sildur's Vibrant Shaders only makes use of those uniforms to identify lightning and beacon beams in the shadow pass (to prevent them from casting a shadow)

**Comment by thedocruby** [comment]
> ... The effects are unrelated with Sildur's Vibrant Shaders. Sildur's Vibrant Shaders only makes use of those uniforms to identify lightning and beacon beams in the shadow pass (to prevent them from casting a shadow)

Cool. Now I know. Thanks!

**Comment by coderbot16** [comment]
More issues, this time with squids.

![image](https://user-images.githubusercontent.com/22420959/109899222-6347b500-7c4a-11eb-9595-255dfb8e0dcb.png)

![image](https://user-images.githubusercontent.com/22420959/109899232-66db3c00-7c4a-11eb-8014-ac3c1ee0b911.png)

**Comment by thedocruby** [comment]
This also happens near stained glass, ice, and other various translucents, all of which render like water in the most recent trunk build, which i thought had been fixed.

Ice:
![huge_2021-03-06_16 50 51_0000](https://user-images.githubusercontent.com/76263371/110222029-71d9da80-7e9d-11eb-9c9e-933c993c798d.jpg)
Stained glass:
![huge_2021-03-06_16 53 54_0000](https://user-images.githubusercontent.com/76263371/110221953-f7a95600-7e9c-11eb-9a84-45929f2e2289.png)
Slime Blocks:
![huge_2021-03-06_16 52 25_0000](https://user-images.githubusercontent.com/76263371/110222146-2aa01980-7e9e-11eb-929a-8ac406ae7f7f.jpg)
Also, it seems to only happen when you *arent* looking at anything (hwyla shown for demonstration):
![huge_2021-03-06_16 54 08_0000](https://user-images.githubusercontent.com/76263371/110221992-448d2c80-7e9d-11eb-949a-8cac71d396a5.png)
![huge_2021-03-06_16 54 14_0000](https://user-images.githubusercontent.com/76263371/110222079-b796a300-7e9d-11eb-8fbb-2b66464978af.jpg)
![huge_2021-03-06_16 54 02_0000](https://user-images.githubusercontent.com/76263371/110222117-fcbad500-7e9d-11eb-916a-e4b31f06a8fa.jpg)

**Comment by IMS212** [comment]
The rendering as water has only been fixed in sodium compat, which has vertex extensions.

**Comment by thedocruby** [comment]
> The rendering as water has only been fixed in sodium compat, which has vertex extensions.

Ah okay, thats why i wasnt used to it. Thanks!

**Comment by thedocruby** [comment]
> Here is an annotated part of `WorldRenderer#render` for an explanation:
@coderbot16 Is this decompiled code from the game?? If so, how would I access it for myself? If not, how do I figure out what the game is doing under the hood, to better mixin Iris?

**Comment by coderbot16** [comment]
It's decompiled code, generally you access it by using something like IntelliJ IDEA when developing the game, or genSources with Loom. That's probably a better question for something like the Fabric Discord since it relates more to general Fabric mod development, however.

**Comment by coderbot16** [comment]
This can actually happen with entity to entity interaction as well, I'm guessing that one entity is being drawn before translucents and one is being drawn afterwards:

Sildur's Vibrant Shaders:

![image](https://user-images.githubusercontent.com/22420959/110880685-e0e77280-8293-11eb-87de-521a718b0c6f.png)
![image](https://user-images.githubusercontent.com/22420959/110880691-e5ac2680-8293-11eb-9bfa-9c461eea2fcb.png)

Internal shaders:

![image](https://user-images.githubusercontent.com/22420959/110880734-ef358e80-8293-11eb-951f-8a73f8d128c5.png)
