### ISSUE TITLE
Iris 1.2.5 causes weird dots with the xali's Enhanced Vanilla resource pack

### ISSUE THREAD

**Issue by Sea-Kerman** [IrisShaders/Iris#1460]
### What happened?

These dots appear with certain overlays with the xali's Enhanced Vanilla resource pack when using Iris 1.2.5, it does not occur with Iris 1.2.4

### Screenshots

![2022-05-24_23 21 13](https://user-images.githubusercontent.com/41390862/170195255-43485421-e9e3-4b46-bdfb-ea4a918193c8.png)

### Minecraft Version

1.18.2

### Iris Version

1.2.5

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

RTX 3060 Mobile

### Java Version

Java 17

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/8768491/latest.log)

**Comment by coderbot16** [comment]
Should be fixed in latest 1.2.5 beta 👍
