### ISSUE TITLE
Something is wrong with the transition between the fallback system and continuum 2.0.4.

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1469]
### What happened?

Something is wrong with the transition between the fallback system and continuum 2.0.4.

https://www.veed.io/view/22f8e723-faef-4945-9810-6fb9e0eb814b?sharingWidget=true

### Minecraft Version

Minecraft 1.19 rc 2

### Iris Version

Iris 1.2.4/1.2.5

### Sodium Version

sodium 0.4.1

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by coderbot16** [comment]
Please use a different video host, or just upload the video directly on to GitHub:

![image](https://user-images.githubusercontent.com/22420959/180613846-356438c2-1e32-40c0-a7db-e3eae0c519bc.png)

**Comment by Lolothepro** [comment]
This is fixed with Iris 1.2.6
