### ISSUE TITLE
Iris + sodium crashes before startup on 1.19

### ISSUE THREAD

**Issue by minecat10904** [IrisShaders/Iris#1475]
### What happened?

Whenever I try launching the most recent version of iris + sodium on 1.19, it crashes on startup, leaving me with an error code of -1073740791 and a logfile that provides little information other than the fact that it appears to crash immediately after selecting LWJGL version 3.3.1. I've confirmed that this does not appear to be an issue with something else in the .minecraft folder as I gutted it of everything but saves, screenshots, resource packs, and shader packs prior to my second attempt. I am using the microsoft store launcher, although the legacy launcher makes no difference.

### Relevant log output

```shell
[18:04:28] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.6
[18:04:28] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 3.0.4+9ff28f4057 recommends any version of fabric-textures-v0, which is missing!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[18:04:28] [main/INFO]: Loading 12 mods:
	- fabric-api-base 0.4.8+e62f51a357 via sodium
	- fabric-key-binding-api-v1 1.0.11+54e5b2ecd2 via iris
	- fabric-rendering-data-attachment-v1 0.3.11+9ff28f4057 via sodium
	- fabric-rendering-fluids-v1 3.0.4+9ff28f4057 via sodium
	- fabric-resource-loader-v0 0.5.2+9e7660c657 via sodium
	- fabricloader 0.14.6
	- iris 1.2.5
	- java 17
	- minecraft 1.19
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- sodium 0.4.2+build.16
[18:04:28] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/jbrae/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:04:28] [main/INFO]: Compatibility level set to JAVA_16
[18:04:28] [main/INFO]: Compatibility level set to JAVA_17
[18:04:28] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[18:04:28] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[18:04:29] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[18:04:29] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[18:04:33] [main/INFO]: Building optimized datafixer
[18:04:36] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[18:04:36] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:04:37] [Render thread/INFO]: Setting user: Minecat10904
[18:04:37] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
```

### Minecraft Version

1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2build.16

### Operating System

Windows 11

### What is your GPU?

AMD Radeon 6600 XT

### Java Version

Java 17

### Additional context

As a final clarification, I've tried both the iris installer and using the respective versions of Iris + Sodium with the stock fabric loader and Fabric API--both produce the same result.

**Comment by minecat10904** [comment]
Okay, I forgot that I'm on a windows 11 insider build and thus keep getting bad drivers

**Comment by sebEFN** [comment]
> Okay, I forgot that I'm on a windows 11 insider build and thus keep getting bad drivers

ohh thats the problem I hope they fix it soon. it makes much more sense

**Comment by minecat10904** [comment]
I'm unsure, I can't check the version whenever it downloads because it breaks the AMD software (and thus I've grown to habitually uninstall these random updates and replace it with the production driver and since I do change my settings I never bothered to check device manager) although I'm assuming it's the preview build for the next driver version because I've only had this issue while within the insider program. That, or it's some weird driver from Microsoft that windows update decided I needed. Strangely,  however, this only seemed to affect the 1.19 build of iris and sodium? The 1.18 build (same version of iris for that matter) launched just fine. Granted, I'm unsure if the 1.18 package of iris-sodium had the same build of sodium as well. Granted,  the fix for this seems to just be to not use any drivers that break the Radeon software.

**Comment by LennDoMations** [comment]
> I'm unsure, I can't check the version whenever it downloads because it breaks the AMD software (and thus I've grown to habitually uninstall these random updates and replace it with the production driver and since I do change my settings I never bothered to check device manager) although I'm assuming it's the preview build for the next driver version because I've only had this issue while within the insider program. That, or it's some weird driver from Microsoft that windows update decided I needed. Strangely, however, this only seemed to affect the 1.19 build of iris and sodium? The 1.18 build (same version of iris for that matter) launched just fine. Granted, I'm unsure if the 1.18 package of iris-sodium had the same build of sodium as well. Granted, the fix for this seems to just be to not use any drivers that break the Radeon software.

the crashing is due Radeon graphics driver most likely

**Comment by LennDoMations** [comment]
i had the same exact crash and the fix was to downgrade to 22.5.1 because 22.5.2 is optional and uses new OpenGL Pipeline wich IRIS doesnt like

**Comment by LennDoMations** [comment]
+ i would suggest you to try NimeZ´s Radeon drivers. They are more stable and have a better working AMD Settings app (Radeon UI)

**Comment by LennDoMations** [comment]
You can also disable windows driver auto updates using its installer

**Comment by LennDoMations** [comment]
30.0.15021.11005
is the driver version of 22.5.1 in device manager.
if you have different version number tell me the driver date from Device Manager

**Comment by minecat10904** [comment]
Even so 22.5.2 released in May and I know I reinstalled to the latest (released) drivers after the 17th--which would've been 22.5.2--since I usually go with latest over recommended because I have a nasty habit of playing god so I either did something different than usual and am misremembering, the drivers from windows update are some weird generic ones from Microsoft, or it was something newer than 22.5.2. Or maybe OpenGL didn't update for some weird reason as it's reporting back as 4.6 with a driver version of 29.20.11000,14800

**Comment by minecat10904** [comment]
I'll be honest, I only realized it was a drivers issue after posting the issue (as detailed by the first comment) so I wasn't paying much attention to versioning (and drivers take way too long for me to experiment without feeling much of a need) and since doing my usual driver-fixing procedure fixed it I didn't bother to look much further than that.

**Comment by minecat10904** [comment]
Windows wants to pull an insider right now, actually, so I'll surrender my soul to Microsoft real quick and if my drivers break report back-if not I'm not sure how important this conversation is and may just close it.

**Comment by minecat10904** [comment]
No update, no real grounds for testing, although the change in opengl seems like a potential issue down the line. Since these seem like a specific situation to myself, I'll just close this for now.
