### ISSUE TITLE
Strange line on ice 

### ISSUE THREAD

**Issue by slahieur** [IrisShaders/Iris#1477]
### What happened?

I don't know if it's a bug or not but the ice has a strange line

### Screenshots

![2022-06-09_22 12 20](https://user-images.githubusercontent.com/91540404/172939238-3f13baf1-0dd6-4d26-8af6-66b20748f8bb.png)
![2022-06-09_22 18 33](https://user-images.githubusercontent.com/91540404/172939391-8f6cd95f-bcfd-4b5f-9569-346560b1e93d.png)

### Minecraft Version

1.19

### Iris Version

iris-mc1.19-1.2.5-pbr-beta.6-ddb2fcdd-dirty

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

windows 10 

### What is your GPU?

GTX1050ti  LP 

### Java Version

java 17

**Comment by AlsoSylv** [comment]
I believe this is a sodium bug that has already been reported

**Comment by slahieur** [comment]
> I believe this is a sodium bug that has already been reported

oh im sorry
