### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by indig0F10w** [IrisShaders/Iris#1479]
**Is your feature request related to a problem? Please describe.**
I downloaded "Universal JAR" installer. It detected Minecraft and offered to install Iris & Sodium, 1.19, in .minecraft folder. Didn't select install as Fabric Mod. Performance dropped to unplayable 5-10 FPS.

**Describe the solution you'd like**
Running installer again should detect current installation and offer uninstallation.

**Describe alternatives you've considered**
Manually deleting files which I don't know where Iris put them.

**Additional context**
I am using Tlauncher with Fabric installation out of the box.

I see that there is now a new version added in \.minecraft\versions\iris-fabric-loader-0.14.6-1.19
There is also a folder \.minecraft\iris-reserved and \.minecraft\config\iris.properties

I have deleted them all and I'm not sure if it is needed to delete something else.

**Comment by AlsoSylv** [comment]
TLauncher breaks a lot of things by patching the game in ways that it should not. This has not been reported aith a legitimate copy of the game, and uninstalling is as simple as deleting the iris-reserved folder in your .minecraft directory.

**Comment by indig0F10w** [comment]
> TLauncher breaks a lot of things by patching the game in ways that it should not. This has not been reported aith a legitimate copy of the game, and uninstalling is as simple as deleting the iris-reserved folder in your .minecraft directory.

If you have read the whole post you would notice that the installer makes these folders/files which should be deleted if you want to uninstall Iris:
.minecraft\versions\iris-fabric-loader-0.14.6-1.19
.minecraft\iris-reserved
.minecraft\config\iris.properties

This is not a bug report but a uninstaller feature request.
