### ISSUE TITLE
Incompatible with Gradle v7.0

### ISSUE THREAD

**Issue by thedocruby** [IrisShaders/Iris#148]
When building Iris with Gradle, I receive the following message, and the build fails:
![image](https://user-images.githubusercontent.com/76263371/109574401-d4a62d00-7abd-11eb-9744-bd0592e6780e.png)
Upon running with the `--warning-mode all` option, the build is successful, but I still receive the following message:
![image](https://user-images.githubusercontent.com/76263371/109574750-86ddf480-7abe-11eb-91a9-a0d78e53a0dc.png)
Hope this helps.

**Comment by OverlordsIII** [comment]
I think this is a loom thing, it happens for me when compiling all fabric mods

**Comment by thedocruby** [comment]
Nice, good to know

**Comment by coderbot16** [comment]
This would probably be fixed by upgrading to Loom 0.6 (we're currently using Loom 0.5)
