### ISSUE TITLE
[feature request] Uninstaller

### ISSUE THREAD

**Issue by indig0F10w** [IrisShaders/Iris#1480]
**Note for admin who doesn't read posts to the end before answering/closing:**
If you have read the whole post you would notice that the installer makes these folders/files which should be deleted if you want to uninstall Iris:
.minecraft\versions\iris-fabric-loader-0.14.6-1.19
.minecraft\iris-reserved
.minecraft\config\iris.properties

This is not a bug report but a uninstaller feature request.

Is your feature request related to a problem? Please describe.
I downloaded "Universal JAR" installer. It detected Minecraft and offered to install Iris & Sodium, 1.19, in .minecraft folder. Didn't select install as Fabric Mod. Performance dropped to unplayable 5-10 FPS.

Describe the solution you'd like
Running installer again should detect current installation and offer uninstallation.

Describe alternatives you've considered
Manually deleting files which I don't know where Iris put them.

Additional context
I am using Tlauncher with Fabric installation out of the box.

I see that there is now a new version added in .minecraft\versions\iris-fabric-loader-0.14.6-1.19
There is also a folder .minecraft\iris-reserved and .minecraft\config\iris.properties

I have deleted them all and I'm not sure if it is needed to delete something else.

**Comment by NoComment1105** [comment]
Removing the jar uninstalls the mod. If you really care that much, go in and delete the files yourself. You could have done so in the time it took you to write this useless issue.

**Comment by indig0F10w** [comment]
The only useless things are you salty devs responding without reading.

**Comment by Miss-Corruption** [comment]
> The only useless things are you salty devs responding without reading.
I speak for everyone when I say:
1. We do not support piracy. Buy Minecraft legitimately or no support will be given.
2. An uninstaller for a Minecraft mod, which adds a few KB files, if even + one JAR is unnecessary. If a user truly wanted to remove these files they could delete them on their own.
3. Simply because it is a feature request, on the wrong repository, mind you, doesn't mean it will be considered.
