### ISSUE TITLE
Is iris possible for mc 1.7.10 / 1.12.2 ?

### ISSUE THREAD

**Issue by TataTawa** [IrisShaders/Iris#1484]
**Is your feature request related to a problem? Please describe.**
iris is a great mod ! 1.7.10 / 1.12.2 is the most modded version, in quality and quantites, some large mod / modpacks is still being actively developed.  performance/shaders is needed for these large modpacks

**Comment by chalkyjeans** [comment]
No. Iris won't be backported to either of those versions - namely because Iris is a Fabric/Quilt mod and neither of those exist for those versions. Also, maintaining multiple versions is difficult, and Sodium (what Iris depends on for good performance) does not exist for Forge for those versions.
