### ISSUE TITLE
shader does not support modded dimensions on 1.18 1.19

### ISSUE THREAD

**Issue by NullExistence1994** [IrisShaders/Iris#1486]
### What happened?

world5/7 dimension TwilightForest is not work
and any other modded world like eden ring,abyssalcraft,atum,midnight,etc
cant custom shader for each dimensions
Is there any solution?
Or is it now only possible to use the generic vanilla overworld set?

### Minecraft Version

1.19

### Iris Version

iris 1.2.5 for 1.19

### Sodium Version

mc1.19-0.4.2+build.16

### Operating System

windows11

### What is your GPU?

1070ti

### Java Version

java17

**Comment by IMS212** [comment]
This is an issue with how the Optifine spec works post 1.13, not Iris. Preferably, this would be resolved for Optifine first,however we are looking into alternatives for the future if nothing changes.
