### ISSUE TITLE
Mining Causes Flickering

### ISSUE THREAD

**Issue by astrocake82** [IrisShaders/Iris#1489]
### What happened?

Whenever I mine it causes flickering. I am using Seus renewed pack. ill attach my mod list. I do not believe any of them should conflict. If there is a known issue, please let me know. Thank you!

There is an oddity where if I click on the same block again the flickering substantially decreases. Shown in GIF (please watch till end).

### Screenshots

https://imgur.com/a/UEeJIdH

![mod list](https://user-images.githubusercontent.com/98564612/173631460-9599d4f7-aaf5-4485-83c3-5dac8492aecc.png)

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.5

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 11

### What is your GPU?

RTX 3070

### Java Version

Whatever 1.18.2 uses.

**Comment by coderbot16** [comment]
Please ensure that Always Defer Chunk Updates is disabled and that the issue does not happen with only Iris removed.
