### ISSUE TITLE
Weird rendering of some blocks using Sildur's+Vibrant+Shaders+v1.32+Lite

### ISSUE THREAD

**Issue by Funtimes909** [IrisShaders/Iris#1490]
### What happened?

Some blocks like smooth basalt have weird collections of white dots that appear when looked at from certain angles

### Screenshots

![image](https://user-images.githubusercontent.com/68979259/173985818-599b775b-e11a-4b1f-afad-3996aa944614.png)

### Minecraft Version

1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

Windows 10

### What is your GPU?

Nvidia 1660 Ti

### Java Version

JDK 17

**Comment by coderbot16** [comment]
This is a feature of the shader pack. Those dots are actually the smooth basalt roughly reflecting the light from the lantern.
