### ISSUE TITLE
Broken lighting with shadow lines.

### ISSUE THREAD

**Issue by Sodarrific** [IrisShaders/Iris#1495]
### What happened?

I'm on 1.18.1 fabric with sodium 0.4.0 and iris 1.2.0. The bug causes shadows to become lines on the screen for **every** single shader pack and resource pack. However the effects are different for each. If motion blur is enabled on Sildurs, it creates cuts in the blur. However, if motion blur is enabled on BSL, objects within the cuts are blurred. This only occurs on 1.18.1. When I went to 1.19, it was perfectly fine. I am unsure on how to recreate this.

### Screenshots

Shadows on Sildurs
![2022-06-16_14 45 13](https://user-images.githubusercontent.com/97543528/174178343-7734f248-ab9e-4f9c-b7f2-b0a862073cfa.png)
Blur on Sildurs
![2022-06-16_15 06 21](https://user-images.githubusercontent.com/97543528/174185153-4652c903-df0f-4729-ab7e-8d8402965287.png)
Blur on BSL
![2022-06-16_15 10 14](https://user-images.githubusercontent.com/97543528/174185205-6f438120-ad16-4c57-8cae-47a398527272.png)

### Minecraft Version

Minecraft 1.18.1

### Iris Version

iris-mc1.18.1-1.2.0-pre

### Sodium Version

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 970

### Java Version

Java 17

**Comment by IMS212** [comment]
This is an issue with the newest NVIDIA driver, either downgrade to 512 or use Iris 1.2.5 on 1.18.2.

**Comment by Sodarrific** [comment]
oof alrighty

**Comment by coderbot16** [comment]
Thanks for the detailed report. As IMS says, this should not affect Iris 1.2.5 on 1.18.2. We don't officially support 1.18.1 anymore and this should not affect newer Iris versions so I will be closing this. If it happens on Iris 1.2.5 then this can be reopened.
