### ISSUE TITLE
CITResewn compatibilty broken 1.19

### ISSUE THREAD

**Issue by Columbam1998** [IrisShaders/Iris#1496]
### What happened?

when loading in shaders with CIT installed we get the following effect.
if I load a shaderpack before installing it runs fine with CIT only when loading

### Screenshots

![2022-06-17_08 38 55](https://user-images.githubusercontent.com/36681633/174240762-db5742b3-a70f-489b-b17d-d98a869b4205.png)

### Relevant log output

```shell
log is 1gb filled with this
[08:42:34] [Render thread/INFO]: OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.'
```

### Minecraft Version

1.19

### Iris Version

1.2.5

### Sodium Version

1.19-0.4.2

### Operating System

Windows 10

### What is your GPU?

RTX 3090

### Java Version

Java 17.0.3

### Additional context

Contacted CITResewn's bug report as well but this one is more detailed.

**Comment by coderbot16** [comment]
Can you capture a log file in the broken configuration before loading a world?

**Comment by coderbot16** [comment]
Closing due to no response.
