### ISSUE TITLE
Weird rendering of podzol with LambdaBetterGrass

### ISSUE THREAD

**Issue by nak5124** [IrisShaders/Iris#1502]
### What happened?

Even though shader is disabled, rendering of podzol is not correct.
If I remove Iris, the issue goes away.

### Screenshots

![image](https://user-images.githubusercontent.com/4178778/174460393-33cb0024-cca6-45d5-af81-536b8c87cbbc.png)

### Minecraft Version

1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

Windows 11

### What is your GPU?

NVIDIA Geforce RTX 3080

### Java Version

Java 17

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/8934524/latest.log)

**Comment by nak5124** [comment]
This seems resource pack compatibility issue.
1. The issue occurs.
![image](https://user-images.githubusercontent.com/4178778/174461519-de2f9e40-b3a3-4f14-bce7-c260ea545ef7.png)

2. The issue goes away.(Changed the order of resource packs.)
![image](https://user-images.githubusercontent.com/4178778/174461541-8c0dd62c-5366-4f57-9e13-da53e0195a05.png)

3. The issue goes away.(Removed SpawnEgg3D.)
![image](https://user-images.githubusercontent.com/4178778/174461595-a0cdef5d-865f-45c1-989a-5ea1ec8a62b7.png)

VanillaTweaks_r285994 includes below packs.
	DarkOakSaturation
	SofterWool
	RedIronGolemFlowers
	BetterParticles
	EndlessEndRods
	CrimsonerCrimson
	SmootherWarpedPlanks
	BrighterNether
	OreBorders
	BuddingAmethystBorders
	FullAgeAmethystMarker
	Age25Kelp
	InvisibleTotem
	WitherHearts
	ItemStitchingFix
	PixelConsistentBat
	PixelConsistentElderGuardian
	PixelConsistentGhast
	PixelConsistentWither
	TripwireHookFix
	PixelConsistentSigns
	PixelConsistentXPOrbs
	PixelConsistentBeaconBeam
	PixelConsistentGuardianBeam
	IronBarsFix
	DoubleSlabFix
	CatFix
	HoeFix
	ItemHoldFix
	FullAgeCropMarker
	DifferentStems

You can download [1.19]Glass+++++++++ from here https://www.dropbox.com/sh/fm57am9tke0q1bs/AACqaloqgdwc6aAR8ocDT_mqa

I'm sorry if this is not Iris issue, but removing Iris fixes it.

**Comment by coderbot16** [comment]
Related to https://github.com/IrisShaders/Iris/issues/1678
