### ISSUE TITLE
Shadows causing weird lagging issue

### ISSUE THREAD

**Issue by cappytm** [IrisShaders/Iris#1505]
This is going to be a little tough to explain but here it goes. I have a storage system with redstone, hoppers, and water. So when I turn on shaders (any shaderpack) its drops my fps from 80-100 ish down too 29-40 fps while looking at my contraption. While out in the wild away from it I get 100+ fine. I narrowed all the settings down turning them off one by one seeing what was causing it. So when I turn off shadows only (All other settings in 5 different shaders had no effect on FPS) I get around 60+ fps in the redstone storage area. I might just be dumb.

Relevant log output
No response

Minecraft Version
1.19

Iris Version
iris-mc1.19-1.2.5

Sodium Version
sodium-fabric-mc1.19-0.4.2+build.16

Operating System
Windows 10

What is your GPU?
NVIDIA Geforce RTX 1080

Java Version
Java 17

![2022-06-21_20 11 26](https://user-images.githubusercontent.com/76675239/174922430-81ea26f4-2f6e-4ed8-bcc6-5c74dcf747db.png)
(shadows on) inside storage
![2022-06-21_20 14 03](https://user-images.githubusercontent.com/76675239/174922538-72a8a504-a6b8-44e9-988d-01a631e0d0c5.png)
(shadows on) outside
![2022-06-21_20 17 20](https://user-images.githubusercontent.com/76675239/174922878-f051b3b9-3763-4a51-b230-e851f5b2dc7c.png)
(shadows off)

**Comment by AlsoSylv** [comment]
This is due to how the shadow pass works. 

The shadow pass has to render chunks a second time to determine what is and isn't casting a shdow, and as such has a higher performance impact than other settings.

The number of chests on screen also affects FPS quite heavily in this situation.
