### ISSUE TITLE
Shadows disappearing and reappearing with Sildur's vibrant shaders.

### ISSUE THREAD

**Issue by NoSkillPureAndy** [IrisShaders/Iris#1506]
### What happened?

Shadows seem to disappear and reappear depending on where I am, as shown in this screenshot. It gets a lot worse in crowded areas like forests. Also, entities sometimes like to disappear and reappear, but I don't have footage of that right now

https://user-images.githubusercontent.com/72871450/175107491-8a9b41db-fdb7-47de-894d-c8632d9ff4f7.mp4

.

### Relevant log output

```shell
https://mclo.gs/ERjwQ4H
```

### Minecraft Version

Minecraft 1.19.0

### Iris Version

iris-mc1.19-1.2.5.jar

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1660

### Java Version

Java 16

**Comment by coderbot16** [comment]
This happens from the Max Shadow Distance slider being set to 0. Set it to 32 for normal behavior.

**Comment by NoSkillPureAndy** [comment]
Thanks, sorry about that.
