### ISSUE TITLE
How do I set the render and shadow resolution multiple times？

### ISSUE THREAD

**Issue by xjj0124** [IrisShaders/Iris#1509]
On my 4k display, I want to adjust the render resolution multiple times of the shaderpacks to 0.66x or other multiples to get better performance. Can Iris be able to do it simply through a txt file or a gui like optifine?

**Comment by coderbot16** [comment]
This feature request is being tracked in https://github.com/IrisShaders/Iris/issues/757, but for now you can install the resolution control+ mod. It hasn't been updated in some time, I'm not sure how best to run it on the current game version. We'd like to have a feature like this integrated into Iris at some point though.
