### ISSUE TITLE
Looking at JourneyMap waypoint labels causes entities to render wrongly

### ISSUE THREAD

**Issue by Sinuce** [IrisShaders/Iris#1510]
### What happened?

When looking directly at a Waystone which has a JourneyMap waypoint label, nearby entity model faces render wrongly.
See e.g. attached screenshot where a painting renders in front of a villager.

### Screenshots

![issue-pic-1](https://user-images.githubusercontent.com/5788348/175782567-8886340b-ad28-4ff4-b4e0-50ae2a7bf3a8.jpg)
![issue-pic-2](https://user-images.githubusercontent.com/5788348/175782569-5100e856-7d91-4c07-ad8d-179469748877.jpg)

### Relevant log output

```shell
None
```

### Minecraft Version

1.19

### Iris Version

iris-mc1.19-1.2.5.jar

### Sodium Version

sodium-fabric-mc1.19-0.4.2build.16.jar

### Operating System

Windows 10 64bit

### What is your GPU?

Nvidia GeForce RTX 2070 Super

### Java Version

Don't know - haven't touched it... maybe v8 Update 331 Build 1.8.0?

### Additional context

**Other versions:**
ComplementaryReimagined r1.1_dev1 ([not at fault](https://github.com/ComplementaryDevelopment/ComplementaryDevelopment.github.io/issues/4))
Minecraft 1.19
Fabric API 0.56.3
Fabric Loader 0.14.8
[JourneyMap 1.19-5.8.5rc2](https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3830663)
[Fabric Waystones 3.0.1](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones/files/3841562)

**Comment by coderbot16** [comment]
Please remove Iris and confirm that the issue goes away. If it does, see if it happens with shaders disabled.

**Comment by Sinuce** [comment]
Hi coderbot,

Thanks for your advice.
I followed your suggestion, disabled Iris and shaders, respectively.
It does seem, however, that the issue may be Iris-related.

**With Iris disabled:**
✅ No issue.

![iris-disabled-OK](https://user-images.githubusercontent.com/5788348/175799917-a9981b53-33f0-4041-b7ff-a2c87c2f3465.png)
---


**With Iris enabled, but shaders disabled:**
❌ Render issue persists.

![iris-enabled-no-shaders](https://user-images.githubusercontent.com/5788348/175799922-7908edd7-32a9-44e6-991d-d9f86a142d17.png)

Thank you for your time.
Have a nice weekend.

**Comment by coderbot16** [comment]
Thanks for your response. Based on the test results, this is most likely related to the Batched Entity Rendering optimization that is always active when Iris is installed.

**Comment by Lolothepro** [comment]
https://user-images.githubusercontent.com/68275908/175811045-fe609f3e-af2a-40ba-8f33-ae054a50591d.mp4

**Comment by Sinuce** [comment]
**SOLVED**

Thank you @coderbot16 and @Lolothepro for the explanation and video guide.

You nailed it.
Fiddling with the beam/beacon settings under Server Admin solved the rendering issue.
I take it, that this is not a real bug then?

Kind of you to spend time on this.
Hopefully others experiencing the same problem will reach this GitHub issue.

Cheers

**Comment by coderbot16** [comment]
This might be a bug in JourneyMap in that case. It's worth reporting it there, perhaps... I think they might have some cleanup necessary in their rendering code.

**Comment by Lolothepro** [comment]
https://github.com/TeamJM/journeymap/issues/473#issuecomment-1196749307

**Comment by mysticdrew** [comment]
> This might be a bug in JourneyMap in that case. It's worth reporting it there, perhaps... I think they might have some cleanup necessary in their rendering code.

yea, when shadering beacons, I needed to do some things if the beacons are not getting rendered. It will be resolved for 1.18.2 and 1.19.1 when I release 5.9.0.
