### ISSUE TITLE
Frame time issues without shaders

### ISSUE THREAD

**Issue by oknacupZero** [IrisShaders/Iris#1513]
### What happened?

When im exploring ancient city i notices a stutter, the stuttering also occur when im near a big building that have a lot of blocks.

### Minecraft Version

Minecraft 1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

Windows 10

### What is your GPU?

AMD RX 580

### Java Version

Java 17

### Additional context

https://spark.lucko.me/jzXDONG1KW 
only iris sodium fabric api and spark for performance profiling is in the mod folder.
it might not be the blocks but something else.

**Comment by oknacupZero** [comment]
it was my driver

**Comment by oknacupZero** [comment]
reopened as upgrading driver doesnt help.
https://spark.lucko.me/5o5H2lqYVu
looks like it only happen on smp server with my friends.
the stutter will only occur after sometime.
rejoining the server doesnt fix the issue. i need to reopen the game in order to fix it.

**Comment by oknacupZero** [comment]
this is issue with sodium.

**Comment by oknacupZero** [comment]
after fixing the issue on sodium part and installing iris again the issue continues.
[https://cdn.discordapp.com/attachments/990180697786425395/991285061041274980/unknown.png](url)
can this be fixed or its a problem with my gpu?

**Comment by pjalsGit** [comment]
Why did you close this, did you fix it?
If you did fix it, please tell us the solution, people might need it!

**Comment by coderbot16** [comment]
FullyBufferedMultiBufferSource shouldn't be showing up in a GUI rendering code path... Something is probably wrong here in the Iris code.

**Comment by coderbot16** [comment]
This seems to be related to your hotbar content, so it might appear to be SMP-only if you have a hotbar full of detailed item models on the SMP.

**Comment by oknacupZero** [comment]
I tested it without any item in the inventory and also a new java runtime, it seems like it doesnt do anything.
https://spark.lucko.me/Z0A1LA7a7B

**Comment by oknacupZero** [comment]
Issue is fixed with 22.7.1 driver
