### ISSUE TITLE
Piston Flickering while Returning when only Shader On (Blinking in split second)

### ISSUE THREAD

**Issue by ardissaps** [IrisShaders/Iris#1519]
### What happened?

Piston Flickering while Returning when only Shader On most (Blinking in split second) most of the time (little chance that it wouldnt happened). Tried on Complementary 4.5 and SEUS Renewed still the same.

### Screenshots

Hard to screenshot as it only happen in split second.

### Relevant log output

```shell
https://paste.atlauncher.com/view/51e9cbd6-deeb-462b-a759-19f9fac3e511
```

### Minecraft Version

1.18.2

### Iris Version

1.2.5

### Sodium Version

0.4.1+build.15

### Operating System

Windows 11

### What is your GPU?

Nvidia GTX 980 Ti

### Java Version

Adoptium Terumin 17.03+7

### Additional context

It does not happen when turned off shader.

**Comment by coderbot16** [comment]
Assuming that this is the same as https://github.com/IrisShaders/Iris/issues/1524 - merging into that one since it has more detail.
