### ISSUE TITLE
text renders weird

### ISSUE THREAD

**Issue by Mari023** [IrisShaders/Iris#152]
Text looks a bit weird ![Screenshot](https://user-images.githubusercontent.com/38946771/110017839-f0f8d280-7d26-11eb-8e27-a61a92e0670d.png)

This also happens in the option menu, but not for the names of keybindings 
![Screenshot](https://user-images.githubusercontent.com/38946771/110018605-bc394b00-7d27-11eb-9870-79d55b64d341.png)

Version:
I compiled 49aca308ecc58d7a2e22b5e29f7b996ef18b96fb (trunk, at the time of writing the latest commit)

[Debug crashlog](https://github.com/IrisShaders/Iris/files/6086085/crash-2021-03-04_20.17.33-client.txt)

**Comment by coderbot16** [comment]
This appears to be a case of #46, I'll close this issue in favor of the other one. I've added the first image to the other report though since it is helpful however.

**Comment by coderbot16** [comment]
To work around this, you can remove Xaero's Worldmap for now, but I would like to fix the issue at some point.
