### ISSUE TITLE
shaders dont work

### ISSUE THREAD

**Issue by edowski** [IrisShaders/Iris#1520]
[latest.log](https://github.com/IrisShaders/Iris/files/9033211/latest.log)
im using iris 1.2.5
im on 1.18.2
shaders dont work and it says in chat "shaders toggled to off [check the logs]" but i checked them and i dont understand whats wrong with them and if some shaders manage to turn on they are broken blocks are invisible or my screen is duplicated they worked before but recently none of them work

**Comment by IMS212** [comment]
A: Figura does not work with Iris, you must remove it.
B: We do not support Feather Client.
