### ISSUE TITLE
Moving_piston renders black in various shaderpacks

### ISSUE THREAD

**Issue by Enfission** [IrisShaders/Iris#1524]
### What happened?

I tried to record my contraption with iris on, but i wasn't able to do it because of ugly rendering in various shaderpacks.

### Screenshots

![image](https://user-images.githubusercontent.com/30197605/177835048-ee235a36-1207-46d7-bc1f-4bc5ffe9b819.png)
![image](https://user-images.githubusercontent.com/30197605/177835124-266bcab1-bddd-4afe-b7ab-674cc341abc9.png)
![image](https://user-images.githubusercontent.com/30197605/177835279-033f69f7-28ec-4fd4-8c4d-9d6019862a51.png)
![image](https://user-images.githubusercontent.com/30197605/177835314-58cfee87-442a-4c80-ba56-123a04413443.png)

### Minecraft Version

Minecraft 1.19

### Iris Version

iris-mc1.19-1.2.5

### Sodium Version

sodium-fabric-mc1.19-0.4.2 (replaymod compatible)

### Operating System

Windows 10

### What is your GPU?

Intel UHD Graphics 630

### Java Version

Java 17

### Additional context

1 screen is ComplementaryReimagined_r1.1.1
2 screen is Sildur's+Vibrant+Shaders+v1.32+Lite
3-4 is BSL_v8.1

**Comment by coderbot16** [comment]
Does not happen on 1.16.5, must be 1.17+ only.

**Comment by IMS212** [comment]
Fixed in next release. There's still an issue relating to moving blocks randomly going invisible, but it seems unrelated.

**Comment by coderbot16** [comment]
> There's still an issue relating to moving blocks randomly going invisible, but it seems unrelated.

@IMS212 Has a separate issue been opened to track this yet? Though are you sure that isn't just chunk updates?

**Comment by IMS212** [comment]
It has not, and I’m not confident it’s an Iris issue to begin with.
