### ISSUE TITLE
Support for Minecraft 1.16.4

### ISSUE THREAD

**Issue by axty666** [IrisShaders/Iris#1527]
**Is your feature request related to a problem? Please describe.**
When I use Iris to start up Minecraft 1.16.4, It tell me please use Minecraft 1.16.5.
But update for Minecraft 1.16.5 need reinstall much, such as fabric.

**Describe the solution you'd like**
A  version support Minecraft 1.16.4 . 

**Describe alternatives you've considered**
Update Minecraft verision from 1.16.4 to 1.16.5, But it's very difficult (need update much things)

**Additional context**
[Minecraft 1.16.5](https://minecraft.fandom.com/wiki/Java_Edition_1.16.5)

![X9R9M77O)31HO{ 57OYBW77](https://user-images.githubusercontent.com/76648930/178088864-80f4af0b-fdd0-49ea-bb60-9d1217be5ef8.png)

(English is not my native language; please excuse typing errors.)

**Comment by IMS212** [comment]
1.16.5 is a single dupe fix, all 1.16.4 mods should work.

**Comment by axty666** [comment]
> 1.16.5 is a single dupe fix, all 1.16.4 mods should work.

![image](https://user-images.githubusercontent.com/76648930/178089872-a64a1b57-13c0-4c45-a68a-3697eb33b46c.png)

so why?

**Comment by IMS212** [comment]
We specifically don’t want to support people using unsupported versions (such as 1.16.3/2, which will break).

**Comment by axty666** [comment]
> We specifically don’t want to support people using unsupported versions (such as 1.16.3/2, which will break).

no, it not 1.16.3/2, it's 1.16.4

**Comment by IMS212** [comment]
I know. there’s no reason to support any other 1.16.x version because of that

**Comment by TheNukeLore** [comment]
why not just use 1.16.5? all 1.16.4 mods should work fine on 1.16.5

**Comment by axty666** [comment]
> why not just use 1.16.5? all 1.16.4 mods should work fine on 1.16.5

yes, it looks that, but when i use 1.16.5, it has crash and no reason
