### ISSUE TITLE
RFC: How to handle invalid paths in Optifine texture packs

### ISSUE THREAD

**Issue by IMS212** [IrisShaders/Iris#1534]
Optifine allows normally invalid paths in PBR/textures. How should this be resolved? Should we be allowing all invalid paths, or only allowing those used by Iris?

Blocking 1.3.

**Comment by steameand** [comment]
Iris doesn't seem to support PBR textures if I remember correctly

**Comment by IMS212** [comment]
This is for the PBR beta…

**Comment by IMS212** [comment]
This has been solved in 1.3. If anyone has a different request for this, please make a discussion.
