### ISSUE TITLE
GH Actions should not upload artifacts

### ISSUE THREAD

**Issue by pjalsGit** [IrisShaders/Iris#1539]
### What happened?

According to https://github.com/IrisShaders/Iris/issues/1249, the GH Actions setup should not upload artifacts, while in https://github.com/IrisShaders/Iris/actions/runs/2659997640 I can very clearly see them.

### Screenshots

![image](https://user-images.githubusercontent.com/25231103/178683137-087f0b5f-55eb-4b7b-aebd-f1e878b20d4e.png)

**Comment by pjalsGit** [comment]
It looks like this change was made on https://github.com/IrisShaders/Iris/commit/0e8639ba3b8d0851a4ec11905bd5bb4344d3a6ed, I'm surprised *this* PR got merged but not mine?

**Comment by NotJansel** [comment]
I quote coderbot from the last mentioned commit https://github.com/IrisShaders/Iris/commit/5568b643d3bf8288f2802149bfc523995fb87db6:

> In the past we prevented this to avoid spurious issue reports. But it is clear now that it is more important to continuously be testing our development branches to ensure that bad bugs aren't popping up and not getting spotted until later.

so the actions were enabled again on purpose

**Comment by pjalsGit** [comment]
> I quote coderbot from the last mentioned commit [5568b64](https://github.com/IrisShaders/Iris/commit/5568b643d3bf8288f2802149bfc523995fb87db6):
> 
> > In the past we prevented this to avoid spurious issue reports. But it is clear now that it is more important to continuously be testing our development branches to ensure that bad bugs aren't popping up and not getting spotted until later.
> 
> so the actions were enabled again on purpose

![image](https://user-images.githubusercontent.com/25231103/178686016-de998580-0c69-4167-b71b-b5b408f6a519.png)

I don't see that anywhere in the commit message

**Comment by NotJansel** [comment]
sorry i mentioned the wrong commit, this is the correct one https://github.com/IrisShaders/Iris/commit/6ee89c89949514d61819beb8246254e523788e66

**Comment by coderbot16** [comment]
This was a recent decision change, encouraged by some of the regressions that popped up during 1.2.5's development.
