### ISSUE TITLE
Issue with block outlines when looking at the sky

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#155]
![image](https://user-images.githubusercontent.com/22420959/110199264-7f934f80-7e0c-11eb-89ff-b9be9fc2360b.png)

**Comment by IMS212** [comment]
Could this be related to #146?

**Comment by coderbot16** [comment]
Certainly possible, since block outlines are drawn using the same system as entities and block entities... seems like that underlying issue is causing a lot of problems!
