### ISSUE TITLE
When water reflections are enabled in Sildur's Vibrant Shaders and the player is in a column of water surrounded by air, world geometry will completely fail to render in Minecraft 1.19, 1.18.2 and 1.17.1 (but NOT 1.16.5) in combination with pretty much every modern version of Iris, including Iris 1.2.5

### ISSUE THREAD

**Issue by akemin-dayo** [IrisShaders/Iris#1551]
### What happened?

(Sorry for the really long issue title, it was a challenge trying to summarise the bizarre nature of this bug ;P)

When water reflections are enabled in Sildur's Vibrant Shaders and the player is in a column of water surrounded by air, world geometry will completely fail to render.

The following Minecraft + Iris version combinations are **affected**:
* Minecraft 1.19 + Iris 1.2.5
* Minecraft 1.18.2 + Iris 1.2.5
* Minecraft 1.18.2 + Iris 1.2.4-build.38
* Minecraft 1.18.2 + Iris 1.2.3-build.35
* Minecraft 1.17.1 + Iris 1.2.5
* Minecraft 1.17.1 + Iris 1.2.4-build.37
* Minecraft 1.17.1 + Iris 1.2.3-build.34
* Minecraft 1.17.1 + Iris 1.2.2-build.31
* **Minecraft 1.17.1 + Iris 1.2.1-rc1-90bdb008**

The following Minecraft + Iris version combinations are **NOT affected**:
* **Minecraft 1.18.1 + Iris 1.2.0-pre**
* **Minecraft 1.17.1 + Iris 1.2.0-pre**
* MInecraft 1.16.5 + Iris 1.2.5
* MInecraft 1.16.5 + Iris 1.2.4-build.36
* MInecraft 1.16.5 + Iris 1.2.3-build.33
* MInecraft 1.16.5 + Iris 1.2.2-build.30
* MInecraft 1.16.5 + Iris 1.2.1-rc1-20f1aa54
* MInecraft 1.16.5 + Iris 1.2.0-pre

※ I _tried_ to test these Minecraft + Iris version combinations in an attempt to further bisect this issue to make your lives easier, but I can't remember the correct combination of Sodium + Fabric API versions required to get these old builds to work and not immediately crash at startup. If you guys keep that documentation around, these versions may possibly be worth exploring to try to bisect the issue.
* Minecraft 1.18.2 + Iris 1.2.2-build.32
* Minecraft 1.18.2 + Iris 1.2.1-rc2-0cc372f0-dirty

---

Given the above test results, it seems _very_ likely to me that the breaking change was introduced _somewhere_ between Iris 1.2.0-pre and Iris 1.2.1-rc1-90bdb008.

I am not sure why Minecraft 1.16.5 is unaffected by this issue ー perhaps that may help clue you guys in on where the issue is occurring.

This issue goes away when water reflections (configuration key `waterRefl`, or simply comment out `#define waterRefl` in `shaders.settings`) is disabled.

---

### Screenshots

Expected behaviour from Minecraft 1.19 + OptiFine+OptiFabric 1.19 HD U H8:
![2022-07-23_03 13 42](https://user-images.githubusercontent.com/1980487/180499399-f7469bf9-0e79-478d-9354-69ea0813f38b.png)

Incorrect behaviour from Minecraft 1.19 + Iris 1.2.5:
![2022-07-23_03 16 30](https://user-images.githubusercontent.com/1980487/180499795-8c4dff12-6ced-47c2-a6c1-bf0d58a8dcf6.png)

Another example of incorrect behaviour from Minecraft 1.19 + Iris 1.2.5:
![2022-07-23_03 17 03](https://user-images.githubusercontent.com/1980487/180499873-e5b3e7ee-e4b7-4d70-9cf3-6e41b19cc8b5.png)

---

### Operating System

Windows 10 19044.1826 21H2 and macOS 12.4 21F79

---

### What is your GPU?

NVIDIA RTX 2060 (NVGRD 512.95, DCH) and Apple G13J

**Comment by coderbot16** [comment]
Potentially related commit in the bisect range: https://github.com/IrisShaders/Iris/commit/3d2a4c3cbecac091576974c4ff8c24c26a31a52b

**Comment by coderbot16** [comment]
https://github.com/IrisShaders/Iris/compare/1.17.x/v1.2.0...1.17.x-v1.2.1

**Comment by IMS212** [comment]
Should be fixed in https://github.com/IrisShaders/Iris/commit/45dc976477fb2845438285d5ff3e7d5baa690e3d

**Comment by akemin-dayo** [comment]
I just a local copy of 45dc976477fb2845438285d5ff3e7d5baa690e3d and I can confirm that it does indeed fix this issue on 1.17.1!

**Comment by IMS212** [comment]
Nice!

**Comment by akemin-dayo** [comment]
Closing this issue as 1.2.6 is now public stable, and the issue is resolved now.
