### ISSUE TITLE
Lack of custom uniform support in Iris breaks the biome temperature checks used for rain reflections in Sildur's Vibrant Shaders.

### ISSUE THREAD

**Issue by akemin-dayo** [IrisShaders/Iris#1553]
### What happened?

(Apologies for the second bug report in such a short timespan. ;P)

The biome temperature parameter used for rain reflections in Sildur's Vibrant Shaders is broken (or possibly completely unimplemented…?) on Iris.

The relevant GLSL code can be found in `composite1.fsh`:
```glsl
	#ifdef BiomeCheck
		bool isRaining = (BiomeTemp >= 0.15) && (BiomeTemp <= 1.0) && iswet > 0.01 && land && !transparency && isEyeInWater == 0.0;
	#else
		bool isRaining = iswet > 0.01 && land && !transparency && isEyeInWater == 0.0;
	#endif
```

`BiomeTemp` is defined in `shaders.properties` as:
```glsl
# Biome temperature
uniform.float.BiomeTemp=temperature
```

---

I've confirmed that this behaviour occurs on the following Minecraft + Iris version combinations:
* Minecraft 1.19 + Iris 1.2.5
* Minecraft 1.18.2 + Iris 1.2.5
* Minecraft 1.18.1 + Iris 1.2.0-pre
* Minecraft 1.17.1 + Iris 1.2.5
* MInecraft 1.16.5 + Iris 1.2.5

It seems likely to me that this feature never worked correctly on Iris, and it just so happens that no one had noticed until now.

---

### Workaround

Users can work around this issue by disabling biome temperature checks entirely, either by setting the configuration key `BiomeCheck=false`, or simply commenting out `#define BiomeCheck` in `shaders.settings`.

**※ NOTE:** Using this workaround will result in rain reflections rendering in dry biomes you wouldn't expect them to, such as deserts.

---

### Screenshots

Expected behaviour from Minecraft 1.19 + OptiFine+OptiFabric 1.19 HD U H8 (※ Ignore the fact that the beacons aren't rendering, that's a separate bug with OptiFabric+Debugify):
![optifabric-reference-2022-07-23_21 52 13](https://user-images.githubusercontent.com/1980487/180605793-66ce105e-75c6-4c12-99e2-d28887ec4409.png)

Incorrect behaviour from Minecraft 1.19 + Iris 1.2.5 (`BiomeCheck` is present / enabled):
![irysodium-biomecheckPresent-2022-07-23_21 49 30](https://user-images.githubusercontent.com/1980487/180605838-534b0c2d-b4fc-412d-86ae-0e4ebba62971.png)

Workaround to get rain reflections to render on Minecraft 1.19 + Iris 1.2.5 (`BiomeCheck` is commented out / disabled):
![irysodium-biomecheckComment-2022-07-23_21 44 42](https://user-images.githubusercontent.com/1980487/180605870-d41b27c9-f6b0-40f9-b33b-868890df5264.png)

---

### Operating System

Windows 10 19044.1826 21H2 and macOS 12.4 21F79

---

### What is your GPU?

NVIDIA RTX 2060 (NVGRD 512.95, DCH) and Apple G13J

**Comment by Lolothepro** [comment]
#222 ?

**Comment by coderbot16** [comment]
This is indeed another symptom of https://github.com/IrisShaders/Iris/issues/1027.

**Comment by akemin-dayo** [comment]
Closing this issue as the hard-coded `BiomeTemp` uniform that was added in 492b786657cbe3e227b970193fd44092f9f948f1 fixes this functionality at least specifically for Sildur's Vibrant Shaders.
