### ISSUE TITLE
Added PBR texture and parallax support!!! We need it!!!

### ISSUE THREAD

**Issue by steameand** [IrisShaders/Iris#1554]
Didn't you say that you want to be compatible with all of Optifine's shaderpacks?  The problem is that the shaderpack also has a highlight map normal map and parallax, but IRIS doesn't seem to have one.
I wrote a plugin to support PBR maps, but unfortunately it is too demanding for computers and I don't think it will make it into the home

**Comment by IMS212** [comment]
If you were on our Discord, you would know we are actively working on it and have public betas.

**Comment by VL4DST3R** [comment]
> If you were on our Discord

Or this info could be posted on Curse or Modrinth and thus avoid getting useless tickets like this one ¯\\\_(ツ)\_/¯

**Comment by Felix14-v2** [comment]
There is a pinned issue with information about PBR support, imho this is more than enough for an attentive person.

**Comment by VL4DST3R** [comment]
This should at least be included in the FAQ, if not on the curseforge page itself (where most people will actually see it) since it's one of the biggest aspects of shaders.
