### ISSUE TITLE
Settings menu broken language

### ISSUE THREAD

**Issue by itsdinkd** [IrisShaders/Iris#1555]
### What happened?

All shaders I have are showing broken language for the setting field names, not sure whats going on here. I've tried 8 different shaders, all look like this when entering the settings menu.

### Screenshots

![image](https://user-images.githubusercontent.com/35115304/180618154-2984d81c-e596-47cd-92fa-68e8dafaec5c.png)

### Log output

https://gist.github.com/itsdinkd/2db179befa59812925ddbcfbd821e3f5

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.5

### Operating System

W11 (Happens on any OS in AQM2)

### What is your GPU?

rtx 2080

**Comment by coderbot16** [comment]
Not an Iris bug https://github.com/devs-immortal/Incubus-Core/issues/13
