### ISSUE TITLE
Entity water reflections in the distance turn pink

### ISSUE THREAD

**Issue by Mithos23** [IrisShaders/Iris#156]
Tested on: AMD, Sildurs v1.283 Medium, shadows disabled
Iris: 
![2021-03-06_14 47 38](https://user-images.githubusercontent.com/54249738/110209997-d130ee00-7e8f-11eb-9801-9f43130ad6e5.png)
Optifine:
![2021-03-06_15 18 02](https://user-images.githubusercontent.com/54249738/110210021-edcd2600-7e8f-11eb-92e3-c95b4242e447.png)

**Comment by coderbot16** [comment]
Another example
![image](https://user-images.githubusercontent.com/22420959/110216164-6b7a3d00-7e62-11eb-8193-91120099546e.png)
