### ISSUE TITLE
[1.18.2] crash using complementary shader

### ISSUE THREAD

**Issue by TobiPeterG** [IrisShaders/Iris#1560]
### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.2.6-pbr-beta.7-097b8c38-dirty.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1080

### Java Version

default 1.18.2 java version

### Reproduction Steps

1. start game
2. set tine to night
3. go through the world
4. crash

### Crash Report file and latest.log

```shell
https://gist.github.com/TobiPeterG/28c96b8edf79ff9a92dfc295114275f9
```

### Additional context
The game closed without even opening the launcher again

**Comment by IMS212** [comment]
This looks like a mod classload issue unrelated to Iris.
