### ISSUE TITLE
some ting to do whit lighting idk 

### ISSUE THREAD

**Issue by davidCMs** [IrisShaders/Iris#1565]
### Minecraft Version

1.19

### Iris Version

iris-mc1.19.1-1.2.6

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16

### Operating System

win 10

### What is your GPU?

nvidia geforce gtx 1650

### Java Version

idk im on ver 1.19

### Reproduction Steps

i was playing on a minecraft server cube craft  in the minigame tower defence i went in to a portal multiple times and it crashed
[crash-2022-07-26_21.53.52-client.txt](https://github.com/IrisShaders/Iris/files/9192989/crash-2022-07-26_21.53.52-client.txt)
[2022-07-26-3.log](https://github.com/IrisShaders/Iris/files/9193008/2022-07-26-3.log)
 

### Additional context

i think it is some thing whit the light rendering

**Comment by davidCMs** [comment]
it wont let me upload the crash in to the Crash Report file and latest.log

**Comment by Lolothepro** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/1016

**Comment by coderbot16** [comment]
This is a Sodium issue, not an Iris issue.
