### ISSUE TITLE
"Warning" for updated Iris for 1.19

### ISSUE THREAD

**Issue by FeedTheChunk** [IrisShaders/Iris#1566]
### What happened?

I'm running 1.18.2 and every time I log into the server I get a notice that Iris for 1.19 has been updated.  That's all great but the server is 18.2.

### Minecraft Version

MC 1.18.2

### Iris Version

iris-mc1.18.2-1.2.5.jar

### Operating System

Win10

### What is your GPU?

R9

**Comment by IMS212** [comment]
Iris 1.2.6 has both 1.18.2 and 1.19 versions. If the update doesn't have a version for your Minecraft version, it won't show.
