### ISSUE TITLE
Iris loweres FPS with EBE + Entity Culling.

### ISSUE THREAD

**Issue by kirmerk1** [IrisShaders/Iris#1572]
### What happened?

27 of June I noticed a weird thing. Iris lowers FPS with EBE (Enhanced Block Entities) and Entity Culling mods.
All tests was made on RestWorld map from same angles. 
Here's the results:
Sodium + Iris = 150 FPS.
Sodium + Iris + EBE = 165 FPS.
Sodium + Iris + Entity Culling = 195 FPS.
Sodium + Entity Culling + EBE = 280 FPS.
Sodium + Iris + Entity Culling + EBE = 150 FPS.

Today I updated my GPU drivers and the results are way better, but FPS drop is still noticeable:
Sodium + Entity Culling + EBE = 420 FPS.
Sodium + Iris + Entity Culling + EBE = 285 FPS.

### Screenshots

![With_Iris](https://user-images.githubusercontent.com/83837475/181919907-59529034-fe91-4340-9332-b9129ccc90ac.png)
![Without_Iris](https://user-images.githubusercontent.com/83837475/181919909-bb19309d-6c43-4bf4-b6a9-1c276becf91c.png)

### Log output

[With_Iris.log](https://github.com/IrisShaders/Iris/files/9226709/With_Iris.log)
[Without_Iris.log](https://github.com/IrisShaders/Iris/files/9226710/Without_Iris.log)

### Minecraft Version

1.19

### Iris Version

1.2.6

### Operating System

Windows 10

### What is your GPU?

RX570 4GB

**Comment by Taiyou06** [comment]
could you send the map i wanna try it on nvidia card as well

**Comment by Mangoiz** [comment]
can also confirm, 416 fps with iris, 475 without (ebe and entity culling installed on both tests)

**Comment by a-anthei** [comment]
dont have exact numbers but iris does decrease my fps.

**Comment by IMS212** [comment]
Should be fixed with https://github.com/IrisShaders/Iris/commit/8ea02d4802269df928621ce2f3052802a11635f3. We haven't confirmed this fix is proper; please test!

**Comment by Disguys** [comment]
@IMS212 Compile the fix version for 1.19.2, just there is a version only for 1.16.5 and 1.18.2

**Comment by kirmerk1** [comment]
> Should be fixed with [8ea02d4](https://github.com/IrisShaders/Iris/commit/8ea02d4802269df928621ce2f3052802a11635f3). We haven't confirmed this fix is proper; please test!

Can you please explain what should I do with this. No idea how GitHub or building works.

**Comment by Taiyou06** [comment]
> > Should be fixed with [8ea02d4](https://github.com/IrisShaders/Iris/commit/8ea02d4802269df928621ce2f3052802a11635f3). We haven't confirmed this fix is proper; please test!
> 
> Can you please explain what should I do with this. No idea how GitHub or building works.

> @IMS212 please give compiled the fix version for 1.19.2, there is a version only for 1.16.5 and 1.18.2

it's in iris discord public-test-builds but there you go https://cdn.discordapp.com/attachments/1015349762804949032/1015379693509279934/iris-mc1.19.2-1.3.0-beta.2-9260f756-dirty.jar

**Comment by Disguys** [comment]
Thanks

**Comment by kirmerk1** [comment]
Everything works fine now. FPS are almost indentical. Thank you.
