### ISSUE TITLE
The shader can't work with Iris on m1 macbook air

### ISSUE THREAD

**Issue by void-512** [IrisShaders/Iris#1577]
### What happened?

I enable the shaderpack with iris 1.2.6, sodium 0.2.0, with mods lithium 0.6.5, phosphor 0.8.0, and replaymod 2.6.6 loaded by fabric, however, the shader seems no change from vanilla. 

### Screenshots

<img width="854" alt="截屏2022-08-02 01 02 01" src="https://user-images.githubusercontent.com/76515053/182204829-5de58a40-4571-42bb-b602-111a32bde5c7.png">
<img width="854" alt="截屏2022-08-02 01 02 08" src="https://user-images.githubusercontent.com/76515053/182204852-14939bf2-ddc9-4da0-bf99-7dac1d3643ce.png">

### Minecraft Version

1.16.5

### Iris Version

iris-mc1.16.5-1.2.6

### Operating System

macOS 12.5

### What is your GPU?

7 cores m1

**Comment by IMS212** [comment]
Most shaders do not work on M1, including PTGI.
