### ISSUE TITLE
1.16.5(+): DOF-Shaderpack does not work properly if a shader has been loaded before.

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1578]
### What happened?

DOF-Shaderpack does not work properly if a shader has been loaded before.

### Screenshots

![2022-08-02_13 05 21](https://user-images.githubusercontent.com/68275908/182360037-8ae44352-8034-4fca-a743-85db8673c5b4.png)

### Minecraft Version

Minecraft 1.16.5+

### Iris Version

Iris 1.2.7pre

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Additional context

https://canary.discord.com/channels/774352792659820594/774354522361299006/1003740599054245929

**Comment by coderbot16** [comment]
1.16.5 is no longer supported, so this 1.16-only issue will no longer be tracked.
