### ISSUE TITLE
PTGI HRR 3 FPS is significantly lowered with 1.2.6 update.

### ISSUE THREAD

**Issue by Taiyou06** [IrisShaders/Iris#1584]
### What happened?

There's a significant fps drop in 1.2.6 compared to 1.2.5.
When i check it from RTSS (riva tuner) 1.2.6 draw so much less power.
Driver: 516.59

### Screenshots

1.2.6
![image](https://user-images.githubusercontent.com/77050201/183248666-95260cb8-7a64-49ee-8ab8-470b454cd37a.png)

1.2.5
![image](https://user-images.githubusercontent.com/77050201/183248633-fd23c0cf-184c-41b2-9795-920f5ccb4960.png)

### Log output

1.2.6
[latest.log](https://github.com/IrisShaders/Iris/files/9274995/latest.log)
1.2.5
[latest.log](https://github.com/IrisShaders/Iris/files/9275010/latest.log)

### Minecraft Version

1.19.1

### Iris Version

1.2.6

### Operating System

Windows 10

### What is your GPU?

RTX 2060 

### Additional context

other than ptgi hrr 3 there's weird utilization issue issue with sildur's vibrant ,solas shaders and comp as well. 
It shows %100 utilization but my fps is lower then 1.2.5 might be because of #1572

**Comment by SuperNoobYT** [comment]
I can reproduce this issue

With SEUS PTGI HRR 3
Iris 1.2.5
![PTGI HRR 3 iris 1 2 5](https://user-images.githubusercontent.com/79205494/183252147-145ad4a2-b4a1-42e0-bcc1-273355242601.png)
Iris 1.2.6
![PTGI HRR 3 Iris1 2 6](https://user-images.githubusercontent.com/79205494/183252154-9767aece-812b-463f-a91f-96326537b205.PNG)

Complementary shader V4.5.1 work fine
Iris 1.2.5
![iris_1 2 5](https://user-images.githubusercontent.com/79205494/183252332-f53b70c5-ff4f-4d08-bcd1-ff4056d540d2.PNG)
Iris 1.2.6
![iris_1 2 6](https://user-images.githubusercontent.com/79205494/183252335-74a64fe1-ab96-4f5c-8990-37e1a56eebcd.PNG)

Log 1.2.6 :
[latest.log](https://github.com/IrisShaders/Iris/files/9275185/latest.log)


Minecraft : 1.19
OS : Window 10
GPU : GTX 1060 (3GB)
Launcher : MultiMC

**Comment by Taiyou06** [comment]
found another weird thing in hrr 3 with 1.2.6
![image](https://user-images.githubusercontent.com/77050201/184834198-ddcc97af-b441-42a7-9be3-a04816d5a45c.png)
im in a cave and there's no GI, but SSGI works
![image](https://user-images.githubusercontent.com/77050201/184834333-5de8b2ce-a82d-4748-885f-6e0a7a19dc8f.png)

**Comment by SuperNoobYT** [comment]
still happen on iris 1.2.8

**Comment by IMS212** [comment]
Should be fixed with 1.3. If this still happens, please tell me.
