### ISSUE TITLE
Firework particles change colour when rendering in front of water

### ISSUE THREAD

**Issue by yitzy299** [IrisShaders/Iris#160]
![image](https://user-images.githubusercontent.com/66269211/110242619-c4270400-7f4e-11eb-8ffd-8c60879b8739.png)
As you can see here, the particles are much darker when rendering in front of the lake. Using the latest version of sildurs lite. Have not checked on trunk, but testing this on the sodium compat branch

**Comment by coderbot16** [comment]
The issue here seems to be that firework particles are translucent, which causes them to potentially blend with the water. It's worth checking whether this happens on OptiFine (both 1.16 and 1.14) as well, and if so, I'm not sure if there's much that can be done on the side of Iris.

**Comment by Mithos23** [comment]
doesn't happen on optifine 1.16
![2021-03-07_17 52 08](https://user-images.githubusercontent.com/54249738/110248068-94d4bf00-7f6f-11eb-995a-727a0f5c7cfb.png)
but it does happen on 1.14
![2021-03-07_18 02 30](https://user-images.githubusercontent.com/54249738/110248085-a28a4480-7f6f-11eb-8fd2-0bb6d5f72fbb.png)

**Comment by coderbot16** [comment]
That's interesting, good to know.

**Comment by IMS212** [comment]
If I remember correctly particle rendering is quite broken on 1.15/16 anyway, any 1.14 and lower packs needed an update and any 1.15+ packs stopped working with particles (might be remembering wrong)

**Comment by yitzy299** [comment]
I’m using the latest version of sildurs, from his website

**Comment by coderbot16** [comment]
Yeah, Iris has tried to fix some of the issues with particle rendering. I guess the question is whether a given behavior is "correct" - or if this is even an Iris issue to begin with? (as opposed to a Sildur's issue)

**Comment by coderbot16** [comment]
I've implemented somewhat of a special-case fix for this. As it turns out, firework spark particles are actually opaque, so it's possible to render them with other opaque particles. This is mostly a Sildur's issue that happens to have a simple workaround in Iris.

**Comment by yitzy299** [comment]
Ah great to hear, thanks
