### ISSUE TITLE
Toggled shaders to (off) [Fallback, check your logs for details]!

### ISSUE THREAD

**Issue by ToastConcern** [IrisShaders/Iris#1602]
### What happened?

so it just no longer enabled the shaders and idk why

### Screenshots

![image](https://user-images.githubusercontent.com/94580243/186520597-8f419c0c-c549-4c03-9fd6-9dcdd93bd5a7.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9419318/latest.log)

### Minecraft Version

Minecraft 1.19

### Iris Version

iris-mc1.19.1-1.2.6.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3060

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/blob/trunk/docs/supportedshaders.md

**Comment by ToastConcern** [comment]
:l ok thanks
