### ISSUE TITLE
Screen turns black when trying to load any type of shaders

### ISSUE THREAD

**Issue by 0JemOnTop** [IrisShaders/Iris#1605]
### What happened?

screen just goes black, you can see NOTHING and its not my pc, i have an i9 11th gen, a 3060 and 32 gigs of ram and it just turns the screen black, do you know how to fix this bc alll yt vids on it just show it like its night time not black screeen

### Minecraft Version

1.18.2

### Iris Version

1.18.1 1.2.6

### Operating System

windows 11

### What is your GPU?

rtx 3060

**Comment by coderbot16** [comment]
There's nowhere near enough information needed to help. Please join [the Discord server](https://discord.gg/jQJnav2jPu) and open a thread in `#iris-support`, or create a new issue report and include a log file and screenshot with F3 open.
