### ISSUE TITLE
Game keep crashing when joining the server

### ISSUE THREAD

**Issue by Austin1912** [IrisShaders/Iris#1608]
### Minecraft Version

1.19.2

### Iris Version

1.2.7

### Sodium Version

normal 0.4.2, Reeses 1.4.7, extra 0.4.7

### Operating System

Windows 11

### What is your GPU?

RTX 3070 laptop GPU

### Java Version

Java 8

### Reproduction Steps

1. joining a server
2. instantly crashed

### Additional context

the crash has no crash log or anything it's just crash

**Comment by IMS212** [comment]
Update Sodium Extra/Reese’s Sodium Options, and Sodium itself.
