### ISSUE TITLE
on 1.19.2 Iris 1.2.7 and Sodium 0.4.2+build.16 entering game crashes

### ISSUE THREAD

**Issue by Linguardium** [IrisShaders/Iris#1609]
### Minecraft Version

1.19.2

### Iris Version

1.2.7

### Sodium Version

0.4.2+build.16

### Operating System

Win 10

### What is your GPU?

GeForce RTX 3080

### Java Version

Java 17

### Reproduction Steps

launch game
Enter world (single player or multiplayer)
crash due to client.player being null

### Crash Report file and latest.log

```shell
https://mclo.gs/2nYTLog
This is the last crashlog the user submitted but we tested without origin and the same issue occurred (origin is not 1.19.2 compatible)
```

### Additional context

It appears the minimum sodium version may have changed in 1.2.7 and if so it would be good to indicate that in the fabric.mod.json or something
0.4.2 is marked as 1.19.2 compatible but i assume the 1.2.7 version was released for 0.4.3 that came out an hour earlier

**Comment by Linguardium** [comment]
https://mclo.gs/TWdlSbY - another log with just fapi, iris, and sodium. appears to be a different crash
https://mclo.gs/jmWpfqz - another log without fapi as neither iris nor sodium require it
https://mclo.gs/CDpLsbO - log with 0.4.3 sodium and 1.2.7 iris (this works fine)
https://mclo.gs/up13o1h - log with 0.4.2 sodium and 1.2.6 iris (this also works fine)

**Comment by NotJansel** [comment]
to my testing it appears that iris 1.2.7 and sodium 0.4.2 appear to have some sort of incompability bc a mixin couldnt be injected. IMS or any other person with more knowledge may feel free to correct me.

**Comment by Linguardium** [comment]
Thanks, i updated the OP to be clearer as to what crashes (entering a world, not entering the game)

**Comment by empirebuilder1** [comment]
I believe it has been updated to Sodium 0.4.3 but did not have version dependencies set correctly. If it *must* have 0.4.3 instead of 0.4.2 Fabric should send up a warning, but does not. Updating to Sodium 0.4.3 resolves the issue.

**Comment by IMS212** [comment]
Yes, this is a mistake on my side. An updated version will be released shortly.
