### ISSUE TITLE
Frame rate anomaly problem

### ISSUE THREAD

**Issue by TC-MOXUN** [IrisShaders/Iris#1610]
### What happened?

A bug happened!I'm using iris shader with ComplementaryShaders, in some cases, when the view moves to a certain place, it will be forced down and locked to 30 fps, when the view moves away from that area, it will be back to the 60 fps limit I set, what is the cause of this ah, when I turn off the shading this situation will not occur.

### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.1-1.2.6.jar

### Operating System

Win 11

### What is your GPU?

GTX 1070 ti

**Comment by StormDragon-64** [comment]
pretty sure the thing you are looking at is just rendering more, and it isn't caused by a bug in the mod. Maybe change the settings or get a less performance eating shader.

**Comment by coderbot16** [comment]
This is just vsync - VSync will drop you to 30 FPS if you can't consistently hit 60 FPS to keep your framerate stable. It only happens with shaders because shaders are putting much more load on your system and it is no longer able to consistently hit 60 FPS.
