### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EysseW** [IrisShaders/Iris#1615]
### Minecraft Version

1.19(.0)

### Iris Version

1.2.6 - 1.2.7 (both tested)

### Sodium Version

0.4.2+build.16

### Operating System

Base Arch + Hyprland + Pipewire

### What is your GPU?

AMD RX 580

### Java Version

Java 17 openjdk

### Reproduction Steps

1. Join specifically my SMP (ran on fabric)
2. Game Crashes

### Crash Report file and latest.log

```shell
https://www.mediafire.com/file/z3ve5s3wzvfcofi/latest.log/file
```

**Comment by NotJansel** [comment]
for the Iris 1.2.7 and Sodium 0.4.2 Combo, there is already a crash known (#1609) and will be fixed with sodium 0.4.4 and Iris 1.2.8, releasing in max a week to my knowledge. for a crash with Iris 1.2.6 and Sodium 0.4.2 there is no crash specifially known.
