### ISSUE TITLE
1.17+: Breaking animation is broken with some shaders

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1620]
### What happened?

Breaking animation is broken with some shaderspacks

### Screenshots

https://user-images.githubusercontent.com/68275908/187669167-8da7b53c-ab4f-4870-a1f7-76053a8f5ad3.mp4

### Minecraft Version

Minecraft 1.19.2

### Iris Version

Iris 1.2.8

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

**Comment by Lolothepro** [comment]
Iris 1.2.3...

**Comment by coderbot16** [comment]
What shader packs?

**Comment by Lolothepro** [comment]
[Werrus Shaders Original](https://werrusshaders.wordpress.com/download/)

**Comment by Lolothepro** [comment]
fixed with Iris 1.6.2 and Sodium 0.4.11
