### ISSUE TITLE
Replay mod recording button overriding incompatibility screen

### ISSUE THREAD

**Issue by seallz** [IrisShaders/Iris#1622]
### What happened?

When I open Minecraft launcher with replay mod and its sodium compatible version, I have an incompatibility screen (I think I just have to update sodium for that issue), but it doesn't just have the "download sodium" and the "quit game" options, it has the replay viewer button from replay mod in it. You can get out of the "incompatibility screen" by just clicking it then exiting out of it. But the game crashes if you try to log onto a server or join a world, so it's not a huge issue.

### Screenshots

![2022-09-02_16 35 30](https://user-images.githubusercontent.com/112729702/188231987-e24629cf-473a-4ca8-8f8e-8743c71cb892.png)
![2022-09-02_16 35 35](https://user-images.githubusercontent.com/112729702/188231992-ff924f97-6f7a-4ab1-9d8a-e4b2007214ab.png)
![2022-09-02_16 35 38](https://user-images.githubusercontent.com/112729702/188231997-445c0555-b616-46d0-9735-a65ea5aed491.png)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.2.8.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce GTX 1060 core i5

**Comment by coderbot16** [comment]
This seems like an issue in Replay Mod - it shouldn't be adding buttons to our `ConfirmScreen` that we create to show the incompatibility error: https://github.com/IrisShaders/Iris/blob/6363bcadb0f1dfa84c5e44759ebcb8ad02e036dc/src/main/java/net/coderbot/iris/mixin/MixinTitleScreen.java

Could you please report it to Replay Mod and link this issue?

**Comment by coderbot16** [comment]
This appears to be a case of https://github.com/ReplayMod/ReplayMod/issues/621, which will need to be fixed in ReplayMod. Thanks for letting us know!
