### ISSUE TITLE
1.16.5: Shadows are weird with some shaders.

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1623]
### What happened?

Shadows are weird with some shaders.

### Screenshots

Iris:
![image](https://user-images.githubusercontent.com/68275908/188285548-61008ae2-8a6d-4998-9a96-a1bcb1791ece.png)
Iris & Sodium:
![image](https://user-images.githubusercontent.com/68275908/188285554-88724f1c-525e-4c11-9329-925766010ef0.png)

### Minecraft Version

Minecraft 1.16.5

### Iris Version

Iris 1.2.7

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Additional context

https://github.com/Lana-chan/maples-retro-extravaganza
+
```
#Sat Sep 03 21:10:51 CEST 2022
Dither=false
CRT=false
s_palette_id=13
Scanlines=false
pixel_size=0
Preprocess=false
Pixel=false
```

**Comment by coderbot16** [comment]
Appears to be fixed as of https://github.com/IrisShaders/Iris/commit/5952101b14ea5dabbfc50129dc2d200170834418
