### ISSUE TITLE
All shaders are not working

### ISSUE THREAD

**Issue by N0tTxch** [IrisShaders/Iris#1624]
### What happened?

Whenever I select a shader it just doesnt do anything. When I tried MakeUp - UltraFast everything just goes black. When I tried Sildur's shaders it only just made wood lighter and nothing else. Anyone know a fix?

### Screenshots

![image_2022-09-04_112728890](https://user-images.githubusercontent.com/112794818/188299688-7e42bd9a-ded3-43a7-9de8-49561d8acaff.png)
![2022-09-04_11 25 24](https://user-images.githubusercontent.com/112794818/188299772-64839a6f-059d-486c-893e-62c0ee60eaef.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9484112/latest.log)

### Minecraft Version

Minecraft 1.16.5

### Iris Version

iris-mc1.16.5-1.2.7

### Operating System

Windows 10

### What is your GPU?

AMD ATI FirePro V8700 (FireGL)

### Additional context

It said "Failed to create shader pipeline, Disabling shaders! in the logs

**Comment by IMS212** [comment]
Your GPU is too old to support shaders/Iris.

**Comment by N0tTxch** [comment]
> Your GPU is too old to support shaders/Iris.

No, It worked earlier

**Comment by N0tTxch** [comment]
This issue began 5 days ago, it was doing fine earlier idk why this happened
