### ISSUE TITLE
F3 Reduction/Cleanup

### ISSUE THREAD

**Issue by TheNukeLore** [IrisShaders/Iris#1627]
**Is your feature request related to a problem? Please describe.**
The debug screen can get extremely cluttered in a modded environment, one of the bigger causes is iris and its entity batching/shadow debug info.

**Describe the solution you'd like**
It would be extremely helpful to have some sort of toggle to remove the extra unneeded debug info contributing to the "f3 pollution".(but also keeping the iris version and shaderpack info on the f3 menu often does not show any immediate issues and can be helpful for the support team and debugging so might as well be keeped).

**Describe alternatives you've considered**
I am unsure of what could be done in a clean, simple, non intrusive way to do this so I might just leave it up to the developers stances. A potential solution for cleaning up the f3 menu is compressing the shadow debug info down extremely. I was thinking of a similar system of what vanilla does to reduce screen space clutter in the f3 menu, specifically the system where the value is shortened down to a single letter "A: 'value' ", doing this method could potentially allow compressing the multiple lines of debug info into one or two lines which may be harder to understand to the average user but will still be easy to understand for the developers and support team.

**Additional context**
Maybe potentially moving the iris version info to be right below the sodium versioning(as in the next line) for organization reasons.

**Comment by toomuchcodehelp** [comment]
another idea might be to put the ability to see the f3 as an option in the config

**Comment by alison-gravley** [comment]
> another idea might be to put the ability to see the f3 as an option in the config

I was just digging through every screen and FAQ I could find to turn it off! The text from Iris on the F3 screen is overflowing and hiding text I am trying to read on the righthand side. Please add a way to disable it!
