### ISSUE TITLE
Iris 1.3, Create and Origins incompatibility

### ISSUE THREAD

**Issue by nebulazorua** [IrisShaders/Iris#1630]
### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.3.0.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 3050

### Java Version

Java 17

### Reproduction Steps

1. Install Iris, Origins, Indium and Create together 
2. Make a singleplayer world and join it
3. Get booted

**Comment by nebulazorua** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/9538859/latest.log)
I couldn't upload it to the issue itself, so here's the latest.log

**Comment by johannesmateboer** [comment]
+1 Same bug. Log attached.
[2022-09-10-4.log](https://github.com/IrisShaders/Iris/files/9540324/2022-09-10-4.log)

**Comment by nebulazorua** [comment]
Because I figure this'd be useful: This doesnt happen with just Iris and Origins, or just Iris and Create
It only happens with all 3

**Comment by IMS212** [comment]
This seems to be an issue with something using an invalid path, and Iris allowing it due to how PBR textures have to be handled. We can't fix this on our side if this is the case.

**Comment by johannesmateboer** [comment]
At least a pointer? Different texturepack? Or mods acting up?

1.2.7 worked perfectly, this version doesn't. What's the rabbithole for us developers to dig into?

**Comment by IMS212** [comment]
Working on it actively, may have found a clue.

**Comment by IMS212** [comment]
Mods were providing u0001 instead of an empty string, and Iris allowed this even though it shouldn't. Mods should really fix this on their side, but I've put a temporary workaround in Iris.

**Comment by nebulazorua** [comment]
> Gonna test it right now
> 
> What's the best way to get this update?
> 
> ...or maybe have a build ready for download to test?
I assume github actions work, so probably from there?

**Comment by nebulazorua** [comment]
> > Gonna test it right now
> > What's the best way to get this update?
> > ...or maybe have a build ready for download to test?
> 
> Try the most recent build in github actions

Gonna try https://github.com/IrisShaders/Iris/actions/runs/3028522188
If you wanna try it, download the artifact

**Comment by nebulazorua** [comment]
I compiled from the 1.18.2 branch with a bunch of mods, joined a server, and got this
I'll go through and try to figure out what combination of mods is causing this a bit later
[latest.log](https://github.com/IrisShaders/Iris/files/9541095/latest.log)

**Comment by allanf181** [comment]
Same with shaders compiled from 1.18.2 branch

[latest.log](https://github.com/IrisShaders/Iris/files/9541236/latest.log)
