### ISSUE TITLE
Conduit power "water vision" effect does not update properly

### ISSUE THREAD

**Issue by thedocruby** [IrisShaders/Iris#164]
When moving from conduit-powered water to air and back again, the "water vision" effect does not properly update, and takes a very long and highly variable time to update properly. See [this video](https://www.mediafire.com/file/4l9pgf6duyamcmf/2021-03-07_20-51-13.mkv/file) for details.

**Comment by coderbot16** [comment]
This is almost certainly a Sildur's issue, you should observe the same behavior on OptiFine as well.

**Comment by coderbot16** [comment]
Essentially, the issue appears to be that Sildur's Vibrant treats night vision as something that can be 0 *or* 1, not as something that can take on any value between 0 and 1. There's not really anything for Iris to do here I don't think.
