### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by Guitarman051120** [IrisShaders/Iris#1648]
### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.3.1

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18

### Operating System

Windows 11

### What is your GPU?

AMD Radeon RX 5700XT

### Java Version

Java 17

### Reproduction Steps

1. Try to go through a portal to another dimension
2. Game Crash 

(Shader: Seus Renewed)

**Comment by AlsoSylv** [comment]
We need a log file to help debug the issues.

**Comment by Guitarman051120** [comment]
> 

Since I installed Iris i can't find the log files anymore

**Comment by AlsoSylv** [comment]
Logs are saved in `.minecraft/logs`

**Comment by Guitarman051120** [comment]
Well they are completly unreadable

‹      ÿµV[SÛ8~^føgŸØÝÈ81<ÃC€^Ò…ÀÄ-t†édûØØ’G’Ódý9IÃ-)¥Ý‡\tû¾ó›tãwÃà ìø_à¦äBzýÁÛ‹/!œ)ž™Á¹kžZð™ÈÚðUØÞò±q³	5ì2?`‡Û[7ßÁê@©noýÖ‚´A(î¸é[>áà¸¿å#æõøQ¥d†—ê+jLà¼ÿ¹?€¨›™±XÂj#”<Úe]¶ ‘ªuŒG©(0ôNBï“¡eï£*Gg^¯ªN¹åÞPq"Ï<öÍ¯cÍµ@ãI´ÞÜø2öLÃÜ*Å”¬!>
þj¬a{°ÞzºÎn¹†õDIÿHe½…cßÈÉÑÉYÿÍàãJu{©úº7ê%S‘Õš[R 1
ÛlNn aÈÙôks.AIerÁ*­*Ô–t€ó -¸íÜ˜ŠÛü×²qçÂblk?@<
ïq-Š&TeE)þ¥'¦TLQ¯NÐ©!J—N6×È“åqò¥ÐJ–(É\^Ûü½2öh'·¶2¡ç¹Ê	jVª[.3«rçoàq¬jiÍ£Ý•x¸Í qÙõp×bò9X3ös°Ëd[nYœ¼Ä£ËáÅéÎJmwÚ­u¾ª	%„wµ°\—\Žv÷|ÿÇy|Gó0Ï÷Õîõ‡wg0™×tX‡ù
z—Ñû‹Uníux®)e”^BJÿ§û˜:&‰&­‹bMH^ 7ÄbÑK†hšJ>ç’gNê)¦¼.ì
dï	È"•ÏE‡ €”:ƒpÒ$Ç·„”µ%Ë·£\iÉª‚Ï~
0
…5ÐÌÄtØ5æHFcÝ­Xö×ùà¢BÙ;!…¼hÊ"“ Ë™åb¤¨mÒì•¢ÉsDK(½z
}YÕþ¸:nõêD¨‡ëŸ>ÃU¯ñç
lˆ…(3†RÌÞßÚc'4 !ø»í`Ú|÷œcqêZ…ñ¸¥®à
ßVÉ¬ÕLüA{oê·»›àÈä+ÑË÷üöFë¹”¨GÔÚÈ¹ÿ'uZ,’Ÿ$rþrŸ
<qŽÆ¾Ý)øú“Wšþp“×Åc¬¦ø,ËÓËcQÒQÞ<Pt³fgŽæ<²šKSÔ1
GXºÂŸÐe¦ê"ºÇéŠ£ú0¼¬
:í:xÑ|Ô¦Êmn>Sa,RA+fNB7d¦yÉ6™µNüîzñU'½´^*|]fldÒ]:?ÁàjuC©Æ#LSzJ<ËqH×JSˆ[ÇJYCÁ©Zþ’(hw;pº|1,_ÍCÆ€Uêü èq*ŠB¤·M²Äînºi­ª*RýûöÖþ°dÕE

**Comment by AlsoSylv** [comment]
Upload the log titled "latest.log" as a file

**Comment by Guitarman051120** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/9641346/latest.log)

**Comment by coderbot16** [comment]
There isn't a crash in that log file. If you still get the crash, please play a game session when you get the crash, and right after that upload the log file. Otherwise, we can't really do anything here. If you get the crash again, let us know and this can be reopened.
