### ISSUE TITLE
Custom Entity Models (CEM) support on Iris

### ISSUE THREAD

**Issue by SirDank** [IrisShaders/Iris#1651]
**Is your feature request related to a problem? Please describe.**
CEM enabled resource packs like https://www.curseforge.com/minecraft/texture-packs/fresh-animations do not work on Iris

**Describe the solution you'd like**
Adding CEM Support

**Describe alternatives you've considered**
https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem

**Comment by TheNukeLore** [comment]
Iris is for shaders and shaders only, currently there are no plans for other optifine alternative features.
