### ISSUE TITLE
Help when developing for OptiFine shader compatibility

### ISSUE THREAD

**Issue by thedocruby** [IrisShaders/Iris#167]
It would help tremendously to add a clone/fork of [OptiFineDoc](https://github.com/sp614x/optifine) to the project to make it easy to develop Iris for maximum compatibility with established OptiFine shaderpacks. I did not know until recently that such a repository existed, and made an instant leap forward in progress as well as confidence once I started using it as a resource. Having this available in a similar manner to ShaderDoc would aid new potential contributors, because I for one remember that one of the first things I did on Iris was read through all the available documentation (which was sadly not much at the time) before starting development.

**Comment by coderbot16** [comment]
OptiFineDoc is ARR, and preferably we'd write our own documentation at some point. However, I've added links to this documentation in our docs dir.
