### ISSUE TITLE
Bugged Texture on Bottom of Water

### ISSUE THREAD

**Issue by Deebz96** [IrisShaders/Iris#1678]
### What happened?

The underside of water blocks has a bugged texture. This can happen with only Sodium and Iris installed, no other mods needed to reproduce. It does not happen with only Sodium installed. This is visible without shaders, and with (at least) any shaders that use vanilla water textures in some way, such as Complementary Reimagined.

### Screenshots

![2022-10-05_19 48 10](https://user-images.githubusercontent.com/23617228/194183984-00be4b6a-996e-4642-8a55-d81e8687eaae.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9719625/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.3.1

### Operating System

Windows 11

### What is your GPU?

Nvidia RTX 3090

**Comment by IMS212** [comment]
Cannot replicate on the latest build.
![2022-10-05_17 34 25](https://user-images.githubusercontent.com/31803019/194187958-0fbc9ab8-f8d3-4b6b-920e-39362d0faeea.png)

**Comment by Deebz96** [comment]
Doing some more investigating, it seems related to resource packs. However, there is nothing specific in these resource packs which is causing it. It seems like just simply having a resource pack (or multiple packs) with enough stuff will cause it.

I have attached an example resource pack, with a collection of things from a few different packs that cause this issue when loaded together. No issues are present without Iris. It's almost as if there is some kind of memory overflow? If you delete a few random files from this resource pack (particularly blockstate files), the issue goes away. Does not particularly matter which files.

[TestPack.zip](https://github.com/IrisShaders/Iris/files/9720130/TestPack.zip)

**Comment by Dummiesman** [comment]
Tested with the above resource pack. Albeit on an older version of Minecraft (1.19) and an older version of Iris 

![image](https://user-images.githubusercontent.com/10748421/194196347-1944d34b-f35e-406a-917e-7cda6ce20477.png)

**Comment by Deebz96** [comment]
What's more is that we have found that if you also have this mod installed, the issue goes away with the above resource pack still loaded. The mod does not function correctly, as it is incompatible with sodium, but nevertheless... strange bug.

https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass

**Comment by coderbot16** [comment]
@Deebz96 Could you send us a zip of the mods & resource pack folder that reproduces the bug, in addition to a screenshot of your resource pack selection screen when the bug is happening? It appears that this is a bug dependent on the exact version of Minecraft, exact loaded mods and resource packs, and exact ordering of resource packs in the resource pack screen, which has made it very difficult to isolate outside of large modded environments, but it seems like you've isolated it in a vanilla environment with just a few resource packs. Thanks!

**Comment by coderbot16** [comment]
Preferably, if you have a Discord account, you could share the file through a private message to myself or IMS, to avoid reposting copyrighted material.

**Comment by Deebz96** [comment]
> @Deebz96 Could you send us a zip of the mods & resource pack folder that reproduces the bug, in addition to a screenshot of your resource pack selection screen when the bug is happening? It appears that this is a bug dependent on the exact version of Minecraft, exact loaded mods and resource packs, and exact ordering of resource packs in the resource pack screen, which has made it very difficult to isolate outside of large modded environments, but it seems like you've isolated it in a vanilla environment with just a few resource packs. Thanks!

I already did in a comment above. TestPack.zip

**Comment by coderbot16** [comment]
Sorry, somehow I missed that. That pack was extremely helpful in reproducing the issue, thanks for attaching it! This allowed me to debug the issue over the course of a few hours, eventually uncovering a Sodium bug that was over a year and a half old (which was then aggravated by an Iris patch from June this year):

> This fixes a Sodium flaw that existed in its source code since February 2021 that became much easier to observe due to an Iris atlas stitching optimization released in June 2022. The bug was related to texture sprites allocated to the bottom and right edges of the texture atlas, which only occurs for a very small number of blocks. It also only affected large texture atlases, which were only likely with large mod packs or large combinations of resource packs, or water/lava when the water and lava textures somehow end up on the edge.
> 
> Though this is a Sodium flaw, it needs to be patched in Iris on Minecraft versions below 1.19 because Sodium only supports 1.19 and above.
