### ISSUE TITLE
Double numbers lost precision

### ISSUE THREAD

**Issue by Jack253-png** [IrisShaders/Iris#1679]
### What happened?

Shaders cloud render bugged.

### Screenshots

![image](https://user-images.githubusercontent.com/83895170/194268176-5f97cdc0-e9ee-4c83-9a2d-e41728cf92f8.png)
![image](https://user-images.githubusercontent.com/83895170/194268323-d00d2a07-cab6-4969-9390-6abb29094558.png)

### Log output

[16:54:07] [Render thread/WARN] (GlProgram) Program link log for sodium:chunk_shader_for_shadow: Geometry info
-------------
0(77) : warning C7050: "zrEuGoMOCd" might be used before being initialized

[16:54:07] [Render thread/WARN] (GlProgram) Program link log for sodium:chunk_shader_for_shadow: Geometry info
-------------
0(77) : warning C7050: "zrEuGoMOCd" might be used before being initialized

[16:54:07] [Render thread/WARN] (GlProgram) Program link log for sodium:chunk_shader_for_gbuffers_terrain: Vertex info
-----------
0(2665) : warning C7050: "tangent" might be used before being initialized
0(2666) : warning C7050: "binormal" might be used before being initialized
0(2655) : warning C7050: "preDownscaleProjPos" might be used before being initialized

[16:54:07] [Render thread/WARN] (GlProgram) Program link log for sodium:chunk_shader_for_gbuffers_terrain_cutout: Vertex info
-----------
0(2665) : warning C7050: "tangent" might be used before being initialized
0(2666) : warning C7050: "binormal" might be used before being initialized
0(2655) : warning C7050: "preDownscaleProjPos" might be used before being initialized

[16:54:07] [Render thread/WARN] (GlProgram) Program link log for sodium:chunk_shader_for_gbuffers_water: Vertex info
-----------
0(131) : warning C7050: "preDownscaleProjPos" might be used before being initialized
0(135) : warning C7050: "tangent" might be used before being initialized
0(136) : warning C7050: "binormal" might be used before being initialized

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.3.1.jar

### Operating System

Windows 10 1903 version 18362.53

### What is your GPU?

Nvidia Geforce GTX 1050

### Additional context

double range: -1.79E+ 308~-1.79E+308
current pos: (16777216, 180, 16777216)

**Comment by Jack253-png** [comment]
Shader: SEUS PTGI HRR Test 2.1

**Comment by coderbot16** [comment]
Appears to be a duplicate to https://github.com/IrisShaders/Iris/issues/1679

**Comment by coderbot16** [comment]
Oops - wrong link, the right link is https://github.com/IrisShaders/Iris/issues/1544
