### ISSUE TITLE
Constant crash with enabled shaders

### ISSUE THREAD

**Issue by Afloofyfemboy** [IrisShaders/Iris#1695]
### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.4.0.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 860m

### Java Version

Java 19

### Reproduction Steps

1. Launch into a map
2. Turn on shaders
3. Game crashes

### Additional context

I had none of these issues in the past, i was using Silbur's high shaders getting an average of 60fps on my laptop. This happens in new and existing worlds ever since updating to 1.40

**Comment by LizIsTired** [comment]
Sorry to hear you're having issues in the new update! Could you post either a crash report or a regular log please?

**Comment by JayLeet** [comment]
I'm having a similar issue related to this I believe, I join any server, and then the game kicks me out due to a connection reset, turning off the shaders fixes the problem.

**Comment by Afloofyfemboy** [comment]
> Sorry to hear you're having issues in the new update! Could you post either a crash report or a regular log please?

I only ever got the error code once, I'm unsure why but the minecraft launcher fails to relaunch after minecraft crashes

**Comment by Afloofyfemboy** [comment]
> I'm having a similar issue related to this I believe, I join any server, and then the game kicks me out due to a connection reset, turning off the shaders fixes the problem.

From the one error code i did get it was some sort of issue with sodium that only happened with shaders enabled

**Comment by Afloofyfemboy** [comment]
Heres the crash log
[crash-2022-10-10_13.54.05-client.txt](https://github.com/IrisShaders/Iris/files/9749247/crash-2022-10-10_13.54.05-client.txt)

**Comment by IMS212** [comment]
Immersive Portals for 1.18 and below will not work for now. You must use Immersive Portals 2.2.5, which for now only exists on 1.19.
