### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by MOOOOs** [IrisShaders/Iris#1696]
### What happened?

After updating to 1.4 from 1.3.1 im getting low fps issues and stutter alot also got crash first time i logged into my save it froze. also shaders are off at this time. with 1.3.1 it was buttery smooth 60 fps gameplay after world is loaded

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9746081/latest.log)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.4.0.jar

### Operating System

Windows 10

### What is your GPU?

MSI GTX 1050 Ti

**Comment by coderbot16** [comment]
Meteor client is not supported and is known to cause issues with Iris. If the issue occurs with only Iris and Sodium installed, please open a new issue.
