### ISSUE TITLE
What the hell happened

### ISSUE THREAD

**Issue by Bipbip2109** [IrisShaders/Iris#1698]
### What happened?

Since 1.3.1 for 1.19.2 :

-PBR doesn't work anymore (no logs or anything it simply doesn't work)
-Performance got annihilated into oblivion for some unknown reason
-Half of my shaders don't work anymore (white screen or fallback)

Using latest drivers and tried removing other mods, changing ressourcepacks, reinstalling, nothing changes.

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.4.jar

### Operating System

Windows 11 Home Insider

### What is your GPU?

 NVIDIA GeForce RTX 2060 SUPER

### Additional context

Yeah that's it. See ya.

**Comment by coderbot16** [comment]
We can't really help you without logs, screenshots, or anything. As stated in the issue template:

> The log file instantly tells us important information like the versions of any other installed mods or if there are errors so it is very very important that you include it in your report.
