### ISSUE TITLE
Horse armor does not render on a horse's body

### ISSUE THREAD

**Issue by SplendidAlakey** [IrisShaders/Iris#1708]
### What happened?

When you equip any armor on a horse, the body part of it appears invisible. On Fabric it can only be observed when you open the inventory, while riding, no matter what other mods are present. On Quilt, the same issue is present, however, if you have some other mods (I couldn't pinpoint which ones, but [Dye All The Things](https://modrinth.com/mod/dyeallthethings) is one of them), then that part of armor becomes invisible in game as well (~~this does not happen on Fabric~~ turns out it does, I just screwed up during testing).

Removing Iris completely solves the issue. Let me know if it's important to find out the mod combination to reproduce the bug in game, rather than only on the inventory screen, otherwise I'm only attaching logs with Iris alone, since that's enough to reproduce the issue.

### Screenshots

Quilt/Fabric and Iris alone, golden horse armor
![2022-10-17_14 48 35](https://user-images.githubusercontent.com/86702831/196182808-624ef46f-42d1-4fc4-ab44-006c1be9b0bf.png)

Quilt/Fabric modpack with Iris, golden horse armor
![2022-10-17_15 31 45](https://user-images.githubusercontent.com/86702831/196190379-90ebc6fc-d6dc-43c2-934a-1ac5b3fe6efa.png)

### Log output

https://gist.github.com/SplendidAlakey/9352c72790ff2f49a3609c5feddb64b0

### Minecraft Version

1.19.2

### Iris Version

1.4.0

### Operating System

W10

### What is your GPU?

GTX980

### Additional context

Could be related to https://github.com/IrisShaders/Iris/issues/1365

**Comment by Thanos1716** [comment]
I am also experiencing this, however it doesn't affect the horse in-world, only in the horse GUI for me.

**Comment by SplendidAlakey** [comment]
I can no longer reproduce this on 1.19.2 with Sodium 0.4.4-build.18 and Iris 1.6.1, so I assume this got fixed.

Reopen the issue if I'm wrong.
