### ISSUE TITLE
Release says for 19.1 but the installer has only 19 and 19.2

### ISSUE THREAD

**Issue by mrjoshuak** [IrisShaders/Iris#1709]
### What happened?

The title says it all.  There simply isn't a 19.1 option for the installer as linked by the release. 

### Screenshots

![Capture](https://user-images.githubusercontent.com/80540/197316212-4379c4f0-59ea-4e50-a918-6073324c4e1c.PNG)

### Minecraft Version

1.19.1

### Iris Version

Iris-Installer-2.0.5.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 3090 FE

### Additional context

Installer 2.0.5 is what is provided by this repo via the link in release labeled "Iris 1.4 for Minecraft 1.19.1." If this is the intended behavior then more documentation should be provided to clarify how this installer is to be used to install Iris 1.4 for Mincecraft 1.19.1.

**Comment by IMS212** [comment]
This was a misprint, Iris 1.4 is indeed for 1.19.2 only.

(1.19.2 is 1.19.1 with a critical bug fix, so all mods should work.)
