### ISSUE TITLE
1.16.5: Cannot use Complementary V4.6 with Iris 1.4.0 on Intel HD 3000 (Mesa)

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1710]
### What happened?

Cannot use Complementary V4.6 with Iris 1.4.0

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9845119/latest.log)
[OL.log](https://github.com/IrisShaders/Iris/files/9845120/OL.log)

### Minecraft Version

Minecraft 1.16.5

### Iris Version

Iris 1.4.0

### Operating System

Kubuntu 22.04

### What is your GPU?

Intel HD 3000 (Mesa)

### Additional context

Appears to be caused by b33b342b8c85c98adc2e08eee6574c76f71d3e35

**Comment by IMS212** [comment]
This seems to be an issue with the Intel Mesa drivers not properly supporting DSA on the compatibility profile, we cannot fix this.
