### ISSUE TITLE
raw texture not supported

### ISSUE THREAD

**Issue by rhjdvsgsgks** [IrisShaders/Iris#1711]
### What happened?

some "indescribable" shader using raw texture to load [Precomputed Atmospheric Scattering](https://hal.inria.fr/inria-00288758). everything will become foggy and sky will become black when texture unable to load

### Log output

```
Custom texture directive for stage composite, sampler colortex9.0 contains more parts than we expected: texture/Cs2_n4.bin TEXTURE_3D RGBA32F 512 128 32 RGBA FLOAT
Custom texture directive for stage composite, sampler colortex10 contains more parts than we expected: texture/Ir2_n4.bin TEXTURE_2D RGBA32F 64 16 RGBA FLOAT
Custom texture directive for stage composite, sampler colortex11 contains more parts than we expected: texture/Ts2.bin TEXTURE_2D RGBA32F 256 64 RGBA FLOAT 
```

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.4.0-ce18337c

### Operating System

linux

### What is your GPU?

intel igpu

**Comment by IMS212** [comment]
Duplicate, will be fixed in 1.5.
