### ISSUE TITLE
Visual chunk border bug.

### ISSUE THREAD

**Issue by HeGamingYT** [IrisShaders/Iris#1718]
### What happened?

This happens between every chunk, where there is a cut, within water or glass, most likely between the water surface the slice also appears. And glass whenever placed diffrently, and looking at them at a angle with them having multiple on corsair, you will also see multiple cuts.

### Screenshots

![image](https://user-images.githubusercontent.com/66083811/198672085-63457bc4-3388-4f34-9928-10abec0021c3.png)
![image](https://user-images.githubusercontent.com/66083811/198672132-173a77e6-f0f6-4786-a395-7d454b9689eb.png)
![image](https://user-images.githubusercontent.com/66083811/198672165-92515188-73b5-45a7-9af9-afe8b07433c1.png)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.3.1

### Operating System

Windows 10

### What is your GPU?

NVIDIA GTX 1050 Ti

### Additional context

It is kinda distracting, and mostly not fitting, but especialy it just makes glass visualy buggy.

**Comment by coderbot16** [comment]
This is indeed almost certainly that Sodium bug. If it goes away when only using Sodium and not using Iris, let us know and this can be reopened.
