### ISSUE TITLE
brightness is blinking

### ISSUE THREAD

**Issue by 1GodRage** [IrisShaders/Iris#1719]
### What happened?

I noticed that when I move, the brightness varies a lot on: chests, shulkerboxes, and varies less but still varies on normal blocks.

Video to show the problem: https://www.youtube.com/watch?v=mlAjaT0IuNI
Sodium only, no iris = no blinking: https://www.youtube.com/watch?v=bhTBWozjg5U

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9894261/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.4.0.jar

### Operating System

Win 10

### What is your GPU?

GeForce RTX 3050

**Comment by IMS212** [comment]
Fixed by https://github.com/IrisShaders/Iris/commit/bc08b62cb3ec9767ce6dc54f4d10b3e22e6aa386.

**Comment by IMS212** [comment]
yes, 1.4.2 does not contain this fix. When a release containing it is out, we will close this.
