### ISSUE TITLE
Weird holes within edges

### ISSUE THREAD

**Issue by Mentalgen** [IrisShaders/Iris#172]
Instead of talking within the discord, I'll start making bug reports here. 

Using the Sodium Compat branch with Compact Vertex Format being off, there's still these jarring random dots that will appear now and again. It's small but I figure it should be worth mentioning. I just went into paint to highlight the areas since they are so small 

:v

![2021-03-10_00 37 50](https://user-images.githubusercontent.com/35643551/110582964-f72deb00-813a-11eb-9174-3954c2b7e6e6.png)
![2021-03-10_00 40 28](https://user-images.githubusercontent.com/35643551/110582972-f7c68180-813a-11eb-8df4-13fb534de758.png)
![2021-03-10_00 40 39](https://user-images.githubusercontent.com/35643551/110582975-f85f1800-813a-11eb-8310-d70b1c95bbc7.png)
![2021-03-10_00 40 54](https://user-images.githubusercontent.com/35643551/110582976-f85f1800-813a-11eb-9c54-0c23d470e549.png)
![2021-03-10_00 42 05](https://user-images.githubusercontent.com/35643551/110582978-f8f7ae80-813a-11eb-90b3-bc2fd1884c83.png)

**Comment by coderbot16** [comment]
It's possible that this is a result of Iris forcing the compact vertex format to be enabled at all times - I never implemented the "standard" extended vertex format, so if you see issues with the compact vertex format normally, that's probably the cause.

**Comment by Mentalgen** [comment]
I should also add turning off Sildur's actually fixes the issue

**Comment by coderbot16** [comment]
It's possible that this is a vanilla issue exposed by the recent merge of the CVF fixes to the sodium fork: https://github.com/CaffeineMC/sodium-fabric/issues/578

I wonder if this happened before that merge?

**Comment by coderbot16** [comment]
I don't think that there's anything that Iris can feasibly do about this, this is a [vanilla bug](https://bugs.mojang.com/browse/MC-175333). Sodium might fix it at some point though https://github.com/CaffeineMC/sodium-fabric/issues/578
