### ISSUE TITLE
unable to get some internal texture on 1.16.5

### ISSUE THREAD

**Issue by rhjdvsgsgks** [IrisShaders/Iris#1721]
### What happened?

got "a plane of 1" when trying to get alpha channel of `minecraft:textures/font/ascii.png`

### Log output

no error/warning

### Minecraft Version

1.16.5

### Iris Version

1.4

### Operating System

linux

### What is your GPU?

intel igpu

### Additional context

works fine on iris 1.4 for minecraft 1.18.2

**Comment by IMS212** [comment]
Is there a specific shader/mod combination this happens with?

**Comment by Lolothepro** [comment]
1.16.5 is no longer updated and supported.

**Comment by IMS212** [comment]
We need an actual shader zip to confirm this.

**Comment by coderbot16** [comment]
Iris for 1.16.5 is no longer supported.
