### ISSUE TITLE
Iris causes rendering errors (Mod Incompatibility???)

### ISSUE THREAD

**Issue by ConqAra** [IrisShaders/Iris#1726]
### What happened?

Certain blocks are just completely not being rendered right. This changes depending on the mod I add too. In this instance I added a mod called [Another Furniture Mod](https://github.com/starfish-studios/AnotherFurniture/issues/28) and ran into this issue with Iris.

This seems to be random depending on what mods (mainly ones that add new blocks to the game) I take out from the pack and what I put in. Even vanilla minecraft blocks are like Bluch Orchid or Vines will just not render correctly. The worst part is that it's completely up to the combinations of mods I add into my modpack for what renders incorrectly.

### Screenshots

Screenshot of farmer's delight mod's "Wild Onions" being rendered incorrectly.
![image](https://user-images.githubusercontent.com/76233356/199591644-a84e4bca-bc63-4e70-b142-4a51a94fc49a.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9923842/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.4.0

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3080

### Additional context

I am using BSL Shaders, this problem occurs even with shaders off though until I actually take iris out of the modpack.
I am also using Quilt Loader with Quilted Fabric API.

**Comment by ConqAra** [comment]
Fixed

**Comment by ConqAra** [comment]
Still have this problem, going to do further test and wait.

**Comment by ConqAra** [comment]
Still having this problem with newest version of iris...
![2022-11-18_05 08 41](https://user-images.githubusercontent.com/76233356/202677081-9ee06297-cebf-4ac1-8bd6-6c051d1bc2b9.png)

[Log](https://paste.ee/p/ImCCP)

**Comment by ConqAra** [comment]
Interesting Enough, they disappear now when I disable my shaders instead of having to remove iris completely to get rid of them. 
![2022-11-18_05 25 55](https://user-images.githubusercontent.com/76233356/202680603-d8e641f8-e6a0-4e1a-b654-1933a7e37270.png)
![2022-11-18_05 25 58](https://user-images.githubusercontent.com/76233356/202680609-6a672e15-b9e3-4ab2-8246-06b9308bb61e.png)

**Comment by IMS212** [comment]
Found the issue, 1.4.2 is releasing to fix it.

**Comment by ConqAra** [comment]
haven't seen an issue since the update, will reopen if i come into again!
