### ISSUE TITLE
1.16.5: Chromatic aberration is broken with Lux.

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1727]
### What happened?

Chromatic aberration is broken with Lux.

### Screenshots

![2022-11-03_13 19 12](https://user-images.githubusercontent.com/68275908/199718725-c20aaf72-6a16-4bdd-8a18-c2d1ee603653.png)

### Minecraft Version

1.16.5

### Iris Version

Iris-1.4.1pre

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Additional context

Camera Settings -> Chromatic Abberation

**Comment by coderbot16** [comment]
What is it supposed to look like?

**Comment by Lolothepro** [comment]
Iris:
![2022-11-03_17 51 47](https://user-images.githubusercontent.com/68275908/199784766-911badc9-4c11-4597-820f-127975168199.png)
Optifine:
![2022-11-03_17 53 05](https://user-images.githubusercontent.com/68275908/199784817-a2f7ebff-a6a7-4c43-b634-472a68321908.png)
