### ISSUE TITLE
Iris does not work on systems that lack OpenGL 3 support on 1.16.5

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#173]
It should be possible to use the ARB or EXT extensions for framebuffer object management to get around this.

**Comment by thedocruby** [comment]
I believe that this wou't be fixed for 1.17, with the OpenGL updates to vanilla, but afaik it still remains an issue for 1.16.5

**Comment by coderbot16** [comment]
This was only ever a theoretical issue. Closing.
