### ISSUE TITLE
Physics mod wont work

### ISSUE THREAD

**Issue by Milopk11** [IrisShaders/Iris#1730]
### What happened?

So i've been trying for hours to run physics mod on iris but it never shows up on the mod menu and i've tried every method of installation and every single possible installation location. I have lost hours of my time trying to get a minecraft mod working with shaders and i am desperate now. Please help.

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.4.0

### Operating System

Windows 10

### What is your GPU?

Unknown

**Comment by toomuchcodehelp** [comment]
the physics mod doesn't have a mod menu GUI, look for it in the pause menu
