### ISSUE TITLE
NVIDIA Reflex support for Iris

### ISSUE THREAD

**Issue by Atirtra** [IrisShaders/Iris#1732]
Shaders usually use 99% of your GPU when framerate is uncapped. This introduces huge amounts of input lag and the only practical counter for it currently is capping the framerate.

It would be such a good quality of life improvement to have NVIDIA Reflex implemented into Iris as it syncs the GPU and CPU loads to mitigate the input lag. I'm not too sure if it supports OpenGL or if it's even possible to implement as a mod although I believe it has been modded for Skyrim for example.

It would simply be awesome to always be able to play the game with the highest possible framerate and smoothness without any hinder.

**Comment by IMS212** [comment]
After reviewing this, there are 2 reasons why this is not viable:
1: Reflex only exists for DX12 and Vulkan.
2: Reflex requires heavy modding to the base game code, which would be too invasive for Iris to pull off.
