### ISSUE TITLE
BufferUnderflowException with sodium.

### ISSUE THREAD

**Issue by Keoxxa** [IrisShaders/Iris#1736]
### Minecraft Version

1.9.2

### Iris Version

iris-mc1.19.2-1.4.1.jar

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060

### Java Version

Java 16? Whichever one comes with 1.9.2, never touched the one in the launcher.

### Reproduction Steps

1. Having Sodium and Iris installed.
2. Load up complementary shaders 4.6 (or don't)
3. Explore around.
4. Game Crashes.

### Crash Report file and latest.log

```shell
Crashlog:
https://pastebin.com/kKmWiebk

Latest log (shorted, file too large due to [Render thread/ERROR]: 65539: Invalid key -1 spam, not related to this issue or mod, if anyone could tell me what's causing it that'd be swell tho.)
https://pastebin.com/fmZXx2NZ
```

### Additional context

Disabling Iris fixes the crashes.
With both sodium and iris installed the server will crash consistently around the same chunk once it does, sometimes even instantly if inside the chunk.

**Comment by IMS212** [comment]
Caused by CullLeaves 3.0, a fix will likely come soon.
