### ISSUE TITLE
Iris fails to scale the rendering of overlays with FOV when the HUD is rendered for certain mods

### ISSUE THREAD

**Issue by truepurpledino** [IrisShaders/Iris#1737]
### What happened?

Rendering of certain overlays from other mods (e.g.: FTB Ultimine and waypoint beacons from FTB chunks mod) break when FOV is not default and the HUD is displayed. When the HUD is not displayed, FTB Ultimine renders correctly. You can reproduce this with an instance only consisting of Fabric 0.14.10, Sodium 0.4.4+build.18, FTB Ultimine 1902.3.5-build.65 and it's dependencies.

### Screenshots

[Video of the rendering issue with Iris.](https://youtu.be/9RHTBrL8omM)

[Video of correct rendering without Iris.](https://youtu.be/YL8ETV2DnQE)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10044018/latest.log)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.4.2.jar

### Operating System

Windows 10

### What is your GPU?

RTX 3070

### Additional context

I personally have not had this issue happen in 1.18.2 with Iris, but someone else told me that they did. It happened with the same mods.

**Comment by truepurpledino** [comment]
Just tested it on iris-1.5.0-custom-uniforms-beta.1-22ff1101-dirty.jar and the issue still occurs.

**Comment by truepurpledino** [comment]
With shaders, it breaks even more and puts it completely off of its original position.
![image](https://user-images.githubusercontent.com/75775263/202786823-271dbb74-2049-4d57-8d0e-08baa4fb04f2.png)

Without the HUD, it renders correctly.
![image](https://user-images.githubusercontent.com/75775263/202786947-011f2b50-f9ef-40b7-8e30-f17c8a5f103f.png)

**Comment by IMS212** [comment]
This seems to be FTB Ultimine's fault, using a completely incorrect world render event for what should probably be part of the GUI/not in-world. https://github.com/FTBTeam/FTB-Ultimine/blob/31663d742f2f2da14cee5d2bc82b53d666c8cee1/fabric/src/main/java/dev/ftb/mods/ftbultimine/fabric/FTBUltimineFabric.java

**Comment by truepurpledino** [comment]
I will report this to the FTB Team, but why would this only happen when Iris is installed?

**Comment by IMS212** [comment]
Can't replicate this on the latest commit of 1.19.2.

**Comment by IMS212** [comment]
![2022-11-19_11 43 53](https://user-images.githubusercontent.com/31803019/202868654-982e7104-bdca-464a-bfb8-b4e1845fc777.png)
