### ISSUE TITLE
NullPointerException while rendering

### ISSUE THREAD

**Issue by Janfel** [IrisShaders/Iris#1738]
### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.4.2.jar

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Manjaro Linux

### What is your GPU?

Nvidia GeForce GTX 960

### Java Version

Java 19.0.1

### Reproduction Steps

I don’t know how to reliably reproduce the crash from a clean instance. With my current configuration the process is like this.

1. Load into world
2. Wait a few seconds
3. Game Crashes

I have made a backup of the world to send it to you, but I don’t know where I can upload it.

### Crash Report file and latest.log

```shell
Initial crashlog: https://mclo.gs/Sfpe5QI
latest.log: https://mclo.gs/p52D679
```

### Additional context

Shaders: Complementary Shaders 4.6

The crash initially occurred when I was entering new terrain and thereby generating new chunks. After the first occurrence, the game crashes shortly after loading into the world. I assume the world generation has created some problematic block or entity, and Iris fails to render it and crashes.

As stated above, I have made a backup of the world in this problematic state. I just need to know where I can upload it.

**Comment by IMS212** [comment]
What seems to have actually happened:
Game crashed another way
Not Enough Creashes attempted to "rectify" the issue
The player ended up getting one more frame of render possibly in the main menu

Iris cannot handle shaders in the main menu/without a real player, so it immediately crashed.

Can you replicate this without Not Enough Crashes?

**Comment by Janfel** [comment]
Thanks for the quick reply, I’ll try that right away. I’ve removed the note about version `1.4.1` since it was incorrect.

**Comment by IMS212** [comment]
OK, after looking at the log a bit more, this seems to have been the chain of events.

Player logged out (not sure if you did it, you were kicked or something?)
NEC attempted to rectify the logout by cleaning after itself
 
NEC does a terrible job at cleaning after itself, and decides to load an `ExtendedShader` of Iris to render the dirt screen

Iris cannot handle using an `ExtendedShader` for a screen, so it immediately bails out

NEC can not recover from a crash that it itself has caused, so it bails out too

**Comment by Janfel** [comment]
I could reproduce the crash without NEC, and now I have an actual crashlog. See https://mclo.gs/ilOMayh. From a first glance, the actual crash seems to be in `mythicmounts`/`geckolib`.

**Comment by IMS212** [comment]
Thanks. This is a Geckolib issue, so I recommend posting it there.

We're currently discussing adding a screen to tell users to remove Not Enough Crashes, as it causes many issues.

**Comment by Janfel** [comment]
Thanks for pointing me in the right direction. I have upgraded to `mythic-mounts-1.19.2-7.1.jar` and can now render the offending entity without problems.

**Comment by IMS212** [comment]
Sounds good!
