### ISSUE TITLE
Auto Workstations Incompatibility

### ISSUE THREAD

**Issue by 12MBTT** [IrisShaders/Iris#1739]
### Minecraft Version

1.19.2

### Iris Version

1.4.2

### Sodium Version

0.4.4 build 18

### Operating System

Windows 10

### What is your GPU?

GTX 1650

### Java Version

Java 17.0.3

### Reproduction Steps

1.I place workstations from Auto Workstations mod (https://www.curseforge.com/minecraft/mc-mods/auto-workstations-fabric)
2.I look to them from upper distance for few seconds
![2022-11-19_09 27 44](https://user-images.githubusercontent.com/117925144/202838049-bdfdf0ca-63fb-4858-b910-583e128484d9.png)
3.And it crashes

### Crash Report file and latest.log

```shell
[latest.log](https://github.com/IrisShaders/Iris/files/10046301/latest.log)
[crash-2022-11-19_09.29.03-client.txt](https://github.com/IrisShaders/Iris/files/10046302/crash-2022-11-19_09.29.03-client.txt)
```

**Comment by IMS212** [comment]
This is indeed a problem with Iris and will be fixed in the next release.

**Comment by 12MBTT** [comment]
ty so much!
