### ISSUE TITLE
Iris doesn't work with new 21w10a Rendering (OpenGL 3.2 Core)

### ISSUE THREAD

**Issue by IsaacMarovitz** [IrisShaders/Iris#174]
Even after heavy tweaking, I couldn't get Iris to work in 21w10a. Several mappings have changed between 1.16.5 and 21w10a and Minecraft's OpenGL version has changed to 3.2 Core, and all rendering is now done through shaders.

**Comment by coderbot16** [comment]
This is known, major internal refactors will need to take place first. It is certainly possible, but it will be a difficult port.
