### ISSUE TITLE
Iris 1.4.2 cannot detect player and mob

### ISSUE THREAD

**Issue by Plohtes** [IrisShaders/Iris#1740]
### What happened?

Iris 1.4.0-1.4.2 with shadder cannot see player and mob, only see block . ( I use sodium 0.4.4 and fabric loader 0.14.10-1.19.2 )
Already try to remove all mod except iris and sodium.
but it work fine with iris v1.2.5 (minecraft 1.19) with same PC spec

### Screenshots

![2022-11-19_14 46 07](https://user-images.githubusercontent.com/118598918/202844593-858cb0b2-4e22-41fd-9671-315bceff3797.png)

![2022-11-19_14 46 15](https://user-images.githubusercontent.com/118598918/202844765-547dbb75-da32-4439-987b-1873042b6d35.png)
![2022-11-19_16 41 40](https://user-images.githubusercontent.com/118598918/202844776-aa3bc869-f651-4568-9300-189c31547e75.png)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.4.2

### Operating System

Win 8

### What is your GPU?

Intel(R) HD Graphics 2500

**Comment by Plohtes** [comment]
Any solution?

**Comment by IMS212** [comment]
We need a log file and F3.

**Comment by IMS212** [comment]
Nevermind, saw the F3. Intel HD Graphics 2500 is too old to use shaders.

https://github.com/IrisShaders/Iris/blob/trunk/docs/usage/drivers.md
