### ISSUE TITLE
JDK crash while trying to enter a nether portal

### ISSUE THREAD

**Issue by Woodgoldtwo** [IrisShaders/Iris#1747]
### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.4.2.jar

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1660 Ti with Max-Q Design

### Java Version

Java 17

### Reproduction Steps

I have no idea of how to reproduce this as i don't really know what happened

I just entered a nether portal on a survival world using: AstraLex v69.1
(my fps was **really** low (saying this just in case it's relevant))

### Additional context

No crash-report was created, instead this text file appeared informing about a JDK crash:
[hs_err_pid1608.log](https://github.com/IrisShaders/Iris/files/10094189/hs_err_pid1608.log)

**Comment by Woodgoldtwo** [comment]
*this is very concerning*

**Comment by IMS212** [comment]
This is a known bug with NVIDIA drivers above 522.

**Comment by Woodgoldtwo** [comment]
what do i do

**Comment by IMS212** [comment]
Downgrade your drivers to 522.
