### ISSUE TITLE
Preprocessor directives in block.properties and similar are not handled

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#176]
This means that things won't wave by default on Sodium + Iris unless you edit the shaderpack.

**Comment by Kroppeb** [comment]
> This means that things won't wave by default on Sodium + Iris unless you edit the shaderpack.

So is this an issue that only applies when Sodium is installed?

**Comment by coderbot16** [comment]
At the time this issue was created, it was only relevant for Sodium + Iris because trunk did not support vertex format extensions. But now that it does, this issue is relevant when Sodium is not installed too.

**Comment by coderbot16** [comment]
This was fixed when https://github.com/IrisShaders/Iris/pull/186 was merged.
