### ISSUE TITLE
Broken Textures for glass

### ISSUE THREAD

**Issue by InFloencer** [IrisShaders/Iris#1763]
### What happened?

Glas on Chunk borders looks really wierd when its layered

### Screenshots

![2022-12-02_22 57 31](https://user-images.githubusercontent.com/117830590/205397464-1bcd87c3-087b-4c9d-bb18-412029bef7ee.png)
![2022-12-02_22 57 17](https://user-images.githubusercontent.com/117830590/205397476-3db6d226-cff6-47d4-86ce-5e1bff858f48.png)

### Minecraft Version

1.19.2

### Iris Version

v1.4.2

### Operating System

windows 10

### What is your GPU?

GeForce RTX3060

**Comment by IMS212** [comment]
Known issue in Sodium, please do not report it to them. For more info see CaffeineMC/sodium-fabric#38.
