### ISSUE TITLE
Crumbling overlay doesn't work properly. (BSL; AstraLEX; etc...)

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1764]
### What happened?

 Breaking animation doesn't work properly.

https://user-images.githubusercontent.com/68275908/205444693-c608bf5d-316c-47f8-b15e-edaa0f246768.mp4

### Screenshots

![2022-12-03_15 01 34](https://user-images.githubusercontent.com/68275908/205444629-46b05e1b-3157-4ece-bb0a-161864911639.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10146546/latest.log)

### Minecraft Version

1.16.5

### Iris Version

Iris 1.4.3

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Additional context

(https://github.com/IrisShaders/Iris/compare/1.16.x-v1.2.4...1.16.x-v1.2.5)
This also seems to happen randomly with the AstraLEX.
Seems to occur from version 1.2.5 of Iris

**Comment by Lolothepro** [comment]
SEUS PTGI HRR 2.1:

https://user-images.githubusercontent.com/68275908/208258396-42c5a35c-f23e-4dde-bbfe-58582f68cd6b.mp4

**Comment by Lolothepro** [comment]
Ok, this bug seems to affect also the Iris versions for Minecraft 1.17+.

**Comment by Lolothepro** [comment]
Why did IMS close this bug report?

**Comment by IMS212** [comment]
It had the fixed in next release label; removing

**Comment by Lolothepro** [comment]
I should have notified that this bug is still not fixed X)

**Comment by coderbot16** [comment]
It was fixed but you seem to have effectively reverted the fix to avoid a crash.

**Comment by Lolothepro** [comment]
fixed
