### ISSUE TITLE
Garbage perfomance on shaders

### ISSUE THREAD

**Issue by thefurnaceguy** [IrisShaders/Iris#1766]
### What happened?

Hello, i was watching how many YouTubers use shaders with sodium and iris at a lot of FPS. But when i tested it, it was a bad experience.

**Expectation:**
Better FPS with shader
**Reality:**
20 fps...

**PC Specs**
AMD Athlon 3000G with Radeon Vega Graphics  3.50 GHz
16 GB Ram
64 bits system with Windows 10
- I don't have any clue why does this happen, if you find any solution please comment here. Also using Optifine i get 70 FPS! But in sodium 20 fps... (Using Complementary Reimagined)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-fabric-loader-0.14.10-1.19.2

### Operating System

Windows 10

### What is your GPU?

AMD Athlon 3000g with Radeon Vega Graphics

**Comment by IMS212** [comment]
We need both an F3 photo of Optifine and Iris, and a log file. Otherwise, we cannot provide any help.

**Comment by wereretot** [comment]
Based on the information you have left, the lack of expected performance is because you are using an integrated graphics chip, these chips are not known for their fast performance.
Iris works best with a dedicated graphics card.

**Comment by douira** [comment]
Do current versions of Iris and Sodium still have this issue for you?

**Comment by ghost** [comment]
sorry for not anwsering this issue i've reported, but it seems that my pc is kinda bad for some shaders.
but hey, in the latest version of iris using the fabulously optimized modpack, i can run some shaders at 60 fps in 720p!
i'm closing this becuase what i reported didn't make sense and i didn't share anything. apologies for not knowing about this before.
