### ISSUE TITLE
Why bad perfomance and sodium and iris?

### ISSUE THREAD

**Issue by thefurnaceguy** [IrisShaders/Iris#1773]
### What happened?

A strange fps bug happened, in optifine i get 70-80 fps max, but in sodium and iris i only get 20 fps, can't even at least reach 30 fps. You know, that's a huge difference for me. (i used mc's 1280x720 display for better perfomance)
These are my PC Specs:
Processor: AMD Athlon 3000G with Radeon Vega Graphics 3.50 GHz
Memory: 16,0 GB (13,2 GB usable)
SSD 240 GB Disk
64 bits system
DirectX 12
(I use optifabric with optimization mods, should i remove them to make compatible iris and sodium?)
. I have the enough info so you can help me fixing this or atleast giving me a solution.

### Screenshots

![optifine fps](https://user-images.githubusercontent.com/114253576/205985607-d033bc10-0fd8-49a1-b3a8-a0a66dd5e478.png)
![iris sodium fps](https://user-images.githubusercontent.com/114253576/205985614-d53fd0b8-be2c-4fa1-bb53-6438c97cb43e.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10169025/latest.log)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-fabric-loader-0.14.10-1.19.2

### Operating System

Windows 10

### What is your GPU?

AMD Athlon 3000G with Radeon Vega Graphics 3.50 GHz

**Comment by chesman35** [comment]
yeah iris doesnt play well with some shaders, 9 times out of 10, they discriminate against amd gpus, which you have. best bets are just for you to wait until ether amd or iris try and fix something in their interlocking spagetti code

**Comment by douira** [comment]
Do current versions of Iris and Sodium still have this issue for you?
