### ISSUE TITLE
Release 1.4.5 for 1.19.2 tagged as 1.19.3 on CurseForge

### ISSUE THREAD

**Issue by koelle25** [IrisShaders/Iris#1781]
### What happened?

The 1.4.5 release for 1.19.2 is falsely tagged as 1.19.3 on CurseForge. See also attached screenshot.

Direct link to this file on CurseForge: https://www.curseforge.com/minecraft/mc-mods/irisshaders/files/4143801

### Screenshots

![2022-12-08_11-11](https://user-images.githubusercontent.com/915514/206420045-48f11664-24f3-462a-ad11-346a7b36c79c.png)

### Minecraft Version

1.19.2

### Iris Version

1.4.5

### Operating System

N/A

### What is your GPU?

N/A

**Comment by IMS212** [comment]
Fixed.
