### ISSUE TITLE
Versioning with `1.19.x` breaks semver so mod updaters don't work properly

### ISSUE THREAD

**Issue by ChristopherHaws** [IrisShaders/Iris#1785]
### What happened?

When I use PrismLauncher or Packwiz to try and update my mods, iris keeps trying to downgrade from 1.4.5 to 1.4.2. The reason is that in modrinth, the **version number** of 1.4.2 is `1.19.x-v1.4.2` and the **version number** of 1.4.5 is `1.19.2-v1.4.5`. When using semver to pick the latest version, the 1.4.2 version wins.

My recommendation would be to swap the game version and the iris versions so that it is `v1.4.2-1.19.x` and `v1.4.5-1.19.2`. Using this scheme, the versions should sort properly with semver.

### Minecraft Version

1.19.2

### Iris Version

1.4.5

### Operating System

N/A

### What is your GPU?

N/A

**Comment by ChristopherHaws** [comment]
@Prospector True. Thanks for pointing that out. I can confirm this is how Fabric API is versioned: https://modrinth.com/mod/fabric-api/versions

**Comment by IMS212** [comment]
This has been done.
