### ISSUE TITLE
Minecraft crashes whenever I disable shaders

### ISSUE THREAD

**Issue by KoalaMistico** [IrisShaders/Iris#1793]
### Minecraft Version

Minecraft 1.19 and 1.19.2

### Iris Version

iris-mc1.19-1.2.5.jar and iris-mc1.19.2-1.4.5.jar respectively

### Sodium Version

sodium-fabric-mc1.19-0.4.2+build.16.jar and sodium-fabric-mc1.19.2-0.4.4+build.18.jar respectively

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1070

### Java Version

Java 17

### Reproduction Steps

1. Enable any shaderpack (if not enabled already)
2. Disable it using the shortcut key or the Shader Menu
3. Crashes Instantly

### Additional context

[latest.log](https://github.com/IrisShaders/Iris/files/10242033/latest.log)

[hs_err_pid4944.log](https://github.com/IrisShaders/Iris/files/10242038/hs_err_pid4944.log)

The Crash report and latest logs are from the 1.19.2 crash.

**Comment by IMS212** [comment]
Downgrade your NVIDIA drivers to 522.
