### ISSUE TITLE
OptiFine compatible ColorMaps

### ISSUE THREAD

**Issue by x35gaming** [IrisShaders/Iris#1795]
Some Texture packs use Colormaps for colored blocks (e.g faithful PBR by PapaChef), which causes colored wool/concrete to render without its designated color.

The colorMap format seems to be stored as a file located in `[base_dir]/minecraft/optifine/colormap/blocks/[block_name].properties`
```properties
format=fixed
color=[Hex_code]
```

i don't know how ColorMaps work in-depth, but a reasonable assumption is that OF tints the final texture to `color=[Hex_code]`.

### Using **OptiFine**
![2022-12-18_17 03 18](https://user-images.githubusercontent.com/44137552/208384554-244abe81-5c2f-4679-9519-ba0b6c9a1b27.png)
### Using **Iris**
![2022-12-19_16 44 22](https://user-images.githubusercontent.com/44137552/208384602-8ecaaa63-5161-468a-b30b-2260fb67943e.png)

**Comment by IMS212** [comment]
The Colormatic mod should handle this.

**Comment by mrzenc** [comment]
> The Colormatic mod should handle this.

It supports versions up to 1.19.2 only, 1.19.3+ not working.

Anyways, I've made a little script that removes all the colormaps and recolors blocks itself. Works fine with PapaChef's Faithful PBR
It is avaiable here: https://github.com/mrzenc/cmfixer
