### ISSUE TITLE
Api to allow mod devs to register their blocks into iris easily.

### ISSUE THREAD

**Issue by FluffyBumblebees** [IrisShaders/Iris#1800]
**Is your feature request related to a problem? Please describe.**
Shaderpacks seem to be heavily restricted to vanilla blocks. This solution aims to resolve that.

**Describe the solution you'd like**
An interface that mod devs can implement. This interface does not do anything besides get an identifier for what type of block it should be registered as. Examples of this would be {new Identifier("iris", "reflective") & {new Identifier("iris", "pbr")}.  At registry-time, it  everyblock would be added to a hashmap, where each tag would have its corresponding list attached to it, with all the blocks of that tag in it.
This value is then accessible in every shaderpacks' block.properties file as "iris:generic_reflective". While not perfect, it can serve as a way for mod devs to add a registry-based tag, and gives leniency for shader pack devs to add their own implementation for what a tag of that sort would render as.

**Describe alternatives you've considered**
Normal tags but they are server based.

**Additional context**
N/A

**Comment by IMS212** [comment]
This is not optimal for many reasons.

First, this is just intrusive and building upon a bad system already.

Second, a better solution already exists, in the form of PBR materials. Mods are able to provide PBR materials and PBR packs will use them.

And finally,block.properties can’t be modified per-fragment. This insanely limits what any such mod could do, and is outright worse than any form of PBR materials.

**Comment by FluffyBumblebees** [comment]
Fair enough.
