### ISSUE TITLE
Disable Not Enough Crashes detection

### ISSUE THREAD

**Issue by sternschnaube** [IrisShaders/Iris#1802]
Hello, it is nicee that **Iris** warns me about to not use **Not Enough Crashes**.
Seeing it one time is fine and helpful - but why is there no config option to disable this warning message?

It really interrupts the loading process. As of version **iris-mc1.19.3-1.4.6** there is no possibility for this.

It's just annoying - let the player decide what they want to use or not.
Pushing a message like this, without the ability to disable it, pushes the player in a "**not fancy way**" to not use the mod...

![2022-12-21_17 01 06](https://user-images.githubusercontent.com/120551916/208949377-ed645aa2-0f42-47c5-bb10-18519e1849b5.png)

**Comment by IMS212** [comment]
The player's choice to use the mod has a direct impact on mod developers and their ability to maintain mods.

Not Enough Crashes has a history of masking logs unintentionally, or sometimes just pretending errors do not exist for the purpose of making the game "nicer".

We have put this message so people stop using NEC, and by extension put less burden on our and other dev's support teams.

Adding a "don't view again" button would nullify this purpose, as it would be entirely ignored.

**Comment by sternschnaube** [comment]
With this, Iris takes a lot of freedom in it's position. 
And also a provision about another mod.

Too bad.

**Comment by IMS212** [comment]
Yes.

Crashes exist to prevent more unwanted behavior.

What NEC is doing is intentionally blocking crash code that is in place to *prevent* issues, and trying to pretend these issues did not take place.

The reason we recommend these other mods is because they do what NEC does without this behavior, and in a way more friendly to developers.

**Comment by sternschnaube** [comment]
I understand your points. Still, it's not fancy and it just "**takes over it**".
At least **Iris** was not intentionally made incompatible, if **Not Enough Crashes** is detected.

Greetings.

**Comment by ErrorNoInternet** [comment]
I still think there should be an option to disable this (even if it's not in the GUI). There are lots of people complaining (https://www.curseforge.com/minecraft/mc-mods/crafty-crashes).
