### ISSUE TITLE
Issue with Iris and ad astra

### ISSUE THREAD

**Issue by Aces-and-Jacks** [IrisShaders/Iris#1805]
### What happened?

Not really sure what the bug is but caused my game to crash when using iris with ad astra.

### Log output

https://mclo.gs/sx6tpx4

### Minecraft Version

1.19.2

### Iris Version

1.4.5

### Operating System

Mac os

### What is your GPU?

Apple M1 Pro chip

### Additional context

I wasn't sure if this issue was still open on another post or closed since someone in https://github.com/terrarium-earth/Ad-Astra/issues/35 said it was fixed in 1.4.1 and if it was still opened what it would be called. I made an issue [here](https://github.com/terrarium-earth/Ad-Astra/issues/104) originally

**Comment by IMS212** [comment]
This issue is on the server, and not related to Iris.
