### ISSUE TITLE
Crash after boot (255) Sodium-compat

### ISSUE THREAD

**Issue by KpauMupa** [IrisShaders/Iris#181]
I've successfully built Iris-sodium-compat, published to mavenlocal and successfully built sodium-iris-compat mod with it.
When i created new instance in MultiMC with only fabric, fabric API, sodium-iris-compat and iris-sodium-compat and launched it, the game booted into main menu and immediately crashed with exit code 255.
Same issue with no fabric API.
Did not test it with the official launcher.

Crash report file:
[crash-2021-03-18_03.25.00-client.txt](https://github.com/IrisShaders/Iris/files/6160562/crash-2021-03-18_03.25.00-client.txt)
Added crash report file properly XD

**Comment by coderbot16** [comment]
Can you upload a crash report?

**Comment by KpauMupa** [comment]
> Can you upload a crash report?

file:///home/anonimous/.local/share/multimc/instances/Iris/.minecraft/crash-reports/crash-2021-03-18_03.25.00-client.txt

**Comment by KpauMupa** [comment]
[crash-2021-03-18_03.25.00-client.txt](https://github.com/IrisShaders/Iris/files/6160558/crash-2021-03-18_03.25.00-client.txt)
bruh sorry!

**Comment by coderbot16** [comment]
That's better, thanks. You are compiling Sodium with Java 9+ and running on Java 8. You either need to compile with Java 8 or run with Java 9+. It is an issue in Sodium due to its use of Unsafe, so there's not much that we can do to work around it.

**Comment by coderbot16** [comment]
(to clarify: Iris would have the same issue but it has set up its build script to avoid the issue, but Sodium cannot do this easily due to its use of Unsafe.)
