### ISSUE TITLE
Iris fails to load with Sodium's workaround for RTX drivers

### ISSUE THREAD

**Issue by JustPixeled** [IrisShaders/Iris#1812]
### What happened?

When loading Iris with Sodium Version 1.4.7 and you have an RTX card Iris does not detect that Sodium is running

### Screenshots

![2022-12-31_17 20 52](https://user-images.githubusercontent.com/56881532/210151135-ca55b67f-b10c-4163-ba95-13e2e7ac7391.png)
![image](https://user-images.githubusercontent.com/56881532/210151170-fe2a2360-e3b4-49f0-a3e8-b338079b3fcd.png)

### Log output

MultiMC log: https://mclo.gs/qloswe8
Latest.log: [latest.log](https://github.com/IrisShaders/Iris/files/10327720/latest.log)

### Minecraft Version

1.19.3

### Iris Version

1.4.6

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 2060

### Additional context

The sodium devs implemented a workaround for a crash on start up that affects RTX cards, I think this is what is causing the issue

**Comment by IMS212** [comment]
no, Iris is not compatible with Sodium 0.4.7. An update will be released shortly to solve this.

**Comment by JustPixeled** [comment]
I know, that's why I submitted a bug report
