### ISSUE TITLE
People with 6gb of ram crash sometimes when loading into a world

### ISSUE THREAD

**Issue by here0not0to0code** [IrisShaders/Iris#1815]
### Minecraft Version

1.18.2

### Iris Version

Iris 1.4.5

### Sodium Version

0.4.1

### Operating System

Windows 10

### What is your GPU?

AMD RX 560

### Java Version

(build 1.8.0_341-b10

### Reproduction Steps

load into your world of choice with an intel core I5-3570 (or close) 6 GB DDR3 of ram (or lower) then load up. it has a 1/3 chance of crashing because not enough ram. It is more often on servers that a crash may happen like Highpixle pr Kitpvp when first booting up or Switching Internal servers. keep in mind that even tho Minecraft 1.18.2 can crash even tho nothing is open. last u

### Crash Report file and latest.log

I looked at crash reports and could not find the file. Frick me 

### Additional context

on the prv version, it worked fine but when I updated it to 1.4.5 you guys most likely increased the ram usage too.   keep in mind that even tho Minecraft 1.18.2 can crash even tho nothing is open. In the last update, I could have firefox open and still play without issue.
I'm fine if my hardware becomes unsupported in the future. I need a new PC anyway

**Comment by Timolino456** [comment]
Iris 1.4.5 only fixed a crash caused by opening the inventory with a enchanted item in-hand. It shouldn't have changed anything regarding RAM usage.

**Comment by 212112111zwl** [comment]
Perhaps you can add mods that reduce ram usage to solve the issue. 6GB of ram _is_ a little small for playing Minecraft with shaders
