### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [IrisShaders/Iris#1818]
### Minecraft Version

1.19.2

### Iris Version

1.5.0

### Sodium Version

0.4.4+build.18

### Operating System

macOS

### What is your GPU?

M1

### Java Version

java 17

### Reproduction Steps

1. launch game
2. load world
3. activate nostalgia shaders 4.0a
4. crash

### Crash Report file and latest.log

```shell
https://mclo.gs/80c5hCr
```

**Comment by IMS212** [comment]
Nostalgia is not compatible with M1 macs.

**Comment by Aces-and-Jacks** [comment]
untrue. v3.1 of nostalgia is compatible
