### ISSUE TITLE
Iris Failing to load with sodium 0.4.7 and straight up crashing with 0.4.6

### ISSUE THREAD

**Issue by SladeIsTaken** [IrisShaders/Iris#1820]
### Minecraft Version

1.19.3

### Iris Version

iris-mc1.19.3-1.1.5.jar

### Sodium Version

sodium 1.19.3 0.4.7 and also sodium 1.19.3 0.4.6

### Operating System

windows 11

### What is your GPU?

Intel iris XE graphics

### Java Version

Java 17.04

### Reproduction Steps

1. drag latest version of fabric api into mod folder
2. drag latest version of iris (downloaded from curseforge) into mod folder
3. Drag either sodium 0.4.6 or sodium 0.4.7 into the mods folder
4. with sodium 0.4.7 mc says "iris failed to load, your version of sodium is outdated" quit game or download sodium"
5. it will tell you to download sodium 0.4.6 
6. with sodium 0.4.6 downloaded the game will fail to load, "exit code 1"
7. without iris installed the game will run fine

### Crash Report file and latest.log

```shell
i am not on the computer that it crashed on cannot provide crash report
```

### Additional context

i have two texture packs installed
better leaves Motchen or something
and faithful 32x faithful
my game was running fine this morning with sodium, iris and xero's minimap, then i used my elytra and it said game crashed exit code 1
after that the game would open with sodium 0.4.7 without iris but with iris it would say iris failed to load
with iris 0.4.6 the game, when it should have been showing the red mojang screen was just white then it would crash
i have tried launching without xero's minimap to no avail
PLZ FIX THIS

**Comment by IMS212** [comment]
You are using an old version of Iris, please update it.
