### ISSUE TITLE
Crashing while using iris shaders 1.19.2 fabric with mods

### ISSUE THREAD

**Issue by knivesbow** [IrisShaders/Iris#1821]
### Minecraft Version

1.19.2

### Iris Version

 iris-mc1.19.2-1.4.2.jar

### Sodium Version

 sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Operating System

Windows 10 (amd64) version 10.0

### What is your GPU?

NVIDIA GeForce RTX 2060

### Java Version

not sure

### Reproduction Steps

it will play for a while like 5-10min and crash it seems to happen on single player on the sever I haven't had a crash yet 
[crash-2022-12-28_12.07.14-client.txt](https://github.com/IrisShaders/Iris/files/10332887/crash-2022-12-28_12.07.14-client.txt)
[crash-2022-12-31_09.19.51-client.txt](https://github.com/IrisShaders/Iris/files/10332889/crash-2022-12-31_09.19.51-client.txt)
 and crash it seems to happen on single player on the sever I haven't had a crash yet

**Comment by Lolothepro** [comment]
update Iris
