### ISSUE TITLE
Intel : Many shaders are not usable

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1824]
### What happened?

Stracciatella is not usable

### Log output

https://mclo.gs/ZntnFD7

### Minecraft Version

Minecraft 1.19.3

### Iris Version

Iris 1.5.0

### Operating System

Windows 11

### What is your GPU?

Intel XXXXXX

**Comment by Lolothepro** [comment]
update Intel drivers to the latest version fixes log spam

**Comment by notLily72** [comment]
This bug appears to occur on new intel drivers. 

This is with Intel GPU driver version 31.0.101.4255. This driver was released March 29th 2023
![2023-04-07_11 14 22](https://user-images.githubusercontent.com/86197720/230633049-71f4eac8-803a-40ec-af17-11056d1d717b.png)

https://mclo.gs/f51YF39
