### ISSUE TITLE
Minecraft* (Version hidden from driver).

### ISSUE THREAD

**Issue by Chiboski** [IrisShaders/Iris#1825]
Hello!

As of writing this I have updated to iris 1.5.1 and Sodium 0.4.8. I am able to open up Minecraft just fine but I keep seeing "Minecraft* (Version hidden from driver)" on the top bar of the tab.

Whenever I go any iris version before 1.5 (same with sodium) it does not happen. I'm not sure if this is something I should worry about. any info will be helpful! :D
P.S. I'll try to provide any logs if needed.

PC Specs:
OS: Windows 11 Pro 64-bit
CPU: 11th Gen Intel Core i9-11900KF
GPU: Nvidia GeForce RTX 3070

![javaw_0rvqpSKYkg](https://user-images.githubusercontent.com/61901977/210358820-e371f8f1-3a2a-4ba2-a4d4-2b267ae96474.png)

Sorry if the screenshot has bad quality.

**Comment by AlsoSylv** [comment]
This is intentional behavior in sodium 0.4.7+ to work around issues caused by the latest Nvidia drivers
