### ISSUE TITLE
iris shaders

### ISSUE THREAD

**Issue by chadjesus** [IrisShaders/Iris#1835]
hello, am a big noobs in all these shaders instalations i got a problem with turning the shaders on,
i managed to install the shaders to minecraft but when i activate it, i cant see, i can move, place blocks but i cant see what im doing,
when i desactived it everything turned back to normal, can i get some help please?

**Comment by TheNukeLore** [comment]
You were likely using a shader iris didn’t support. What iris version and Minecraft version do you use?

**Comment by chadjesus** [comment]
for iris i used the 1.18.2 version and for minecraft i used 1.19.3  i fought they were compatible

**Comment by Timolino456** [comment]
You need to use the Iris version for the respective Minecraft version, of course it's not going to work otherwise.

**Comment by chadjesus** [comment]
yeah ill do that sorry for the stupid question
