### ISSUE TITLE
Blocky clouds cannot be selected

### ISSUE THREAD

**Issue by Glinckey** [IrisShaders/Iris#1836]
### What happened?

Whatever the setting are, you can't choose to have blocky clouds with shaders and every time you try to it just disables the whole thing

### Screenshots

Uploading clouds bad lol.mov…

https://user-images.githubusercontent.com/105798654/211211639-915c65e6-70de-4bec-97b0-6400d28a4491.mov

### Log output

[2023-01-08-3.log.gz](https://github.com/IrisShaders/Iris/files/10369127/2023-01-08-3.log.gz)

### Minecraft Version

1.19.3

### Iris Version

1.5.1

### Operating System

11

### What is your GPU?

Nvidia GeForce 1650

**Comment by Lolothepro** [comment]
It's a shader bug

**Comment by Lolothepro** [comment]
[fixed](https://github.com/javiergcim/MakeUpUltraFast/commit/ce4baa7a7f5d83a52ced7cee13babaa1bc7df46a)
