### ISSUE TITLE
Enchanted armor z-fighting with internal shaders

### ISSUE THREAD

**Issue by Justsnoopy30** [IrisShaders/Iris#184]
![image](https://user-images.githubusercontent.com/33374736/112013925-72f34480-8af8-11eb-8c0f-0c817223033e.png)

**Comment by coderbot16** [comment]
Successfully reproduced on the current version of Iris trunk:
![image](https://user-images.githubusercontent.com/22420959/112553057-0fc81300-8d81-11eb-81f0-d5d2816034eb.png)

**Comment by coderbot16** [comment]
Internal shaders are removed, so this is no longer an issue.

This issue was caused by discrepancies between vertex transformations between the fixed-function pipeline and the internal shaders. If they used ftransform this issue wouldn't have occurred.
