### ISSUE TITLE
Text on signs appear as boxes in Chocapic13_V9.1_Extreme_beta_5.zip

### ISSUE THREAD

**Issue by Ninjatintin** [IrisShaders/Iris#1843]
### What happened?

When looking at a sign, it's text just shows as boxes.

### Screenshots

![image](https://user-images.githubusercontent.com/96634530/212514695-a94919ea-bcfd-496c-90b1-178a99b5c90e.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10419307/latest.log)

### Minecraft Version

Minecraft 1.19.3

### Iris Version

iris-mc1.19.3-1.5.1

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2070 SUPER/PCIe/SSE2

### Additional context

The shader pack I'm using is Chocapic13_V9.1_Extreme_beta_5

**Comment by throwaway69420lol** [comment]
I have the same problem did u find a fix?

**Comment by IMS212** [comment]
Fixed in 1.5.2.
