### ISSUE TITLE
Iris suddenly lagging

### ISSUE THREAD

**Issue by thecinnabonmanager** [IrisShaders/Iris#1849]
### What happened?

Shortly after the Launcher update, and after I was downloading mods trying to get a resource pack working, I uninstalled all of them to play survival. On my Superflat worlds with shaders on my FPS was fine. And with the same settings on a world I'd been playing with shaders enabled for months now, I was suddenly getting <60 FPS. It was definitely on a supported shaderpack (Sildur's Vibrant Shaders Extreme), and it was the latest versions of all my Sodium mods and Iris. I had gotten rid of all those resource pack mods, and I've downloaded Sodium Extra and Sodium Options, as well as checking Task Manager for some RAM or CPU Hogs, but nothing was there other than Minecraft itself. Please help!

### Screenshots

![2023-01-25_21 12 55](https://user-images.githubusercontent.com/108702530/214743313-e62e6d3e-f05e-4653-93dc-4166ee84e180.png)
With shaders
![2023-01-25_21 13 08](https://user-images.githubusercontent.com/108702530/214743316-93e19914-5f95-45c1-b7c3-6a713c33e388.png)
Without shaders

### Minecraft Version

Minecraft 1.19.3

### Iris Version

iris-mc1.19.3-1.5.1jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1650

### Additional context

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 8 GB RAM
I would add the log but I don't know if there's any personal info on them.

**Comment by thecinnabonmanager** [comment]
I would add the log but idk if there's any personal info on them.

**Comment by coderbot16** [comment]
Diagnosing something like this extremely difficult, but make sure you've clicked on the battery icon and scrolled the power mode to Best Performance. You should also check whether it was caused by updating mods. One of the support team members might be able to be more helpful

**Comment by thecinnabonmanager** [comment]
I haven't updated any mods, but I will try turning up the power mode.

**Comment by thecinnabonmanager** [comment]
I think it worked.
