### ISSUE TITLE
The far plane modifications implemented to replicate OptiFine cause some clouds to be cut off incorrectly

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#185]
![image](https://user-images.githubusercontent.com/22420959/112022916-f65c6800-8aef-11eb-8b43-634641267110.png)

Look at the center right for an example of a cloud that is half cut-off. So, as it turns out, there is a reason for the far plane being 4 times the render distance in vanilla.

**Comment by coderbot16** [comment]
This isn't really feasible to fix at this time, because fixing this would bring back #117. Since many shaderpacks override vanilla clouds, they aren't affected, and bringing back fog would probably hide the issue as well.

I've made it so that the far plane isn't tweaked when shaders are disabled, however, which should make things look normal with vanilla rendering.

**Comment by IMS212** [comment]
This modification has been removed, see #117 for details.
