### ISSUE TITLE
Game crashes when turning shaders on

### ISSUE THREAD

**Issue by kingarthur0975** [IrisShaders/Iris#1850]
### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.5.0

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 3050

### Java Version

Java 17

### Reproduction Steps

1. enable any Shader pack
2. game gets a red screen, then crashes to desktop

I saw no other place to attach my crash report and log files, so I'll just put them here:
[crash-2023-01-25_21.40.58-client.txt](https://github.com/IrisShaders/Iris/files/10506383/crash-2023-01-25_21.40.58-client.txt)
[latest.log](https://github.com/IrisShaders/Iris/files/10506385/latest.log)

**Comment by kingarthur0975** [comment]
(there was no "attach file" prompt under Crash Report file and latest.log)

**Comment by coderbot16** [comment]
Immersive Portals is using Iris internals, so it broke with Iris 1.5. You'll need to update Immersive Portals for it to work with Iris.

**Comment by coderbot16** [comment]
Looking again, it looks like the updated version of Immersive Portals might only be available for 1.19.3, so you might need to update your Minecraft version as well.
