### ISSUE TITLE
Iris causing missing texture with certain animated textures

### ISSUE THREAD

**Issue by EltoCode** [IrisShaders/Iris#1851]
### What happened?

# Current behavior
The missing texture appears instead of the regular animated texture.

# Expected behavior 
An animated texture with a green orb should appear.

# Steps to reproduce

- Load the iris mod.   
- join the server at `play.wynncraft.com`
- load the server provided resource pack
- click on the compass in the hotbar
- the item marked `skill crystal` will have the missing texture. 

# Possible causes
It might be an issue with the predicate system for overwriting textures, or it might be caused by the mcmeta file animating the twinkle effect on the ball

Attached is the resource pack from the server  

[wynn_rp.zip](https://github.com/IrisShaders/Iris/files/10508725/wynn_rp.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/45271085/214824073-6993faba-1895-4f68-adf6-a2f77a423782.png)

### Minecraft Version

1.19.3

### Iris Version

iris-mc1.19.3-1.5.1

### Operating System

Win 10

### What is your GPU?

AMD Radeon T530

**Comment by IMS212** [comment]
This is due to how PBR is handled post-1.19.3, with `_n` and `_s` textures being interpreted as normal and specular.

**Comment by IMS212** [comment]
Should be fixed with #1852.
