### ISSUE TITLE
C13 V9: The world maps are broken when they are in the player's hands.

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1855]
### What happened?

The world cards are broken when they are in the player's hands.

### Screenshots

![2023-01-28_19 52 17](https://user-images.githubusercontent.com/68275908/215285598-8677937d-f2f9-4245-971e-8ad4bccdd37c.png)

### Minecraft Version

1.19.3

### Iris Version

1.5.1

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

**Comment by IMS212** [comment]
Fixed on 1.19.3 with 1.5.2. A backport may be made.

**Comment by Lolothepro** [comment]
> Fixed on 1.19.3 with 1.5.2. A backport may be made.

No
