### ISSUE TITLE
Performance not where it should be in 1440p?

### ISSUE THREAD

**Issue by KevinCCucumber** [IrisShaders/Iris#1856]
### What happened?

I have a 4070 TI, 5800x, 32 gb ram and I play on a Fabric server. When I am alone ~100 fps is the best when playing in 1440p. When the server is freshly started that is.

I have attached debug screenshots with and without as well as my settings and it makes no difference if I am in a village or If I am in the wild.

When activating shaders, the performance drops even more.
CPU and Graphics card are not sweating either.

Performance does not really change in singleplayer mode, so I think its not the server causing issues.

### Screenshots

![2023-01-28_22 28 47](https://user-images.githubusercontent.com/49205361/215292839-3397e28b-cd0f-4ad0-8628-1288fbe003c0.png)
![2023-01-28_22 33 25](https://user-images.githubusercontent.com/49205361/215292840-7bd99c36-30cc-45da-a3d0-115b3676bf4b.png)
![2023-01-28_
![2023-01-28_22 58 12](https://user-images.githubusercontent.com/49205361/215292958-84396e62-f68c-499e-9c99-f195efe4af1b.png)
22 33 28](https://user-images.githubusercontent.com/49205361/215292842-72cf4517-a5bc-4095-a7ce-8f3d8f82ac65.png)
![2023-01-28_22 33 29](https://user-images.githubusercontent.com/49205361/215292846-9a2dbde4-58be-4c8f-91bb-6d4b850bf669.png)
![2023-01-28_22 33 31](https://user-images.githubusercontent.com/49205361/215292847-24c96b61-900d-4a8d-91cf-ec8b3bae6e24.png)
![2023-01-28_22 28 28](https://user-images.githubusercontent.com/49205361/215292848-19ad25e9-5515-4db1-ad86-5ceaa5fccb44.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10528375/latest.log)

### Minecraft Version

1.19.2

### Iris Version

1.5.0

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 4070 TI

**Comment by coderbot16** [comment]
Can you test performance with *only* Iris and Sodium? We can't really guess what's wrong when 170 mods are loaded.

**Comment by KevinCCucumber** [comment]
Sure. I created a testworld and tried to look for an empty area. I will upload the samples.
_This is an empty world without mods._
![2023-01-29_01 12 30](https://user-images.githubusercontent.com/49205361/215297049-6d6a4ec6-2c78-4fdd-9a73-ed69555b7c73.png)
![2023-01-29_01 12 36](https://user-images.githubusercontent.com/49205361/215297053-c5a1feb0-4c04-4505-97ed-a22f34cb362c.png)
![2023-01-29_01 13 05](https://user-images.githubusercontent.com/49205361/215297056-b980b0c8-85d6-43bb-9312-3f7f03ef9e35.png)
[latest.log](https://github.com/IrisShaders/Iris/files/10528647/latest.log)

_And this is with mods:_
![2023-01-29_01 21 22](https://user-images.githubusercontent.com/49205361/215297244-5db0c3fe-3cb2-4d21-ac15-cee79bb5fc29.png)
![2023-01-29_01 20 53](https://user-images.githubusercontent.com/49205361/215297245-d2a48154-015c-46bd-a82b-3617451f779e.png)
![2023-01-29_01 21 14](https://user-images.githubusercontent.com/49205361/215297247-bba1a63d-6284-40ef-b990-69acd9291f6e.png)
[latest.log](https://github.com/IrisShaders/Iris/files/10528656/latest.log)

**Comment by coderbot16** [comment]
So as expected your performance is significantly improved with a fresh world and a non-voxelizing shaderpack. This is likely a combination of the voxelized shaderpack (Rethinking Voxels), the lack of Flywheel integration in Iris (https://github.com/IrisShaders/Iris/issues/1414), and entity rendering just being plain slow which would realistically need to be addressed in Sodium most likely.
