### ISSUE TITLE
Iris Mod not working

### ISSUE THREAD

**Issue by TheGamerBoi69** [IrisShaders/Iris#1858]
Everytime I use Iris, my performance drops to 15-20 fps while with optifine I get 35-40 fps.
I've tried just sodium but that doesn't work either and gives the same performance

my cpu- Ryzen 7 3750H
my gpu- Nvidia GTX 1650....Radeon RX vega 10 (integrated gpu)
ram- 8gb
please help

**Comment by douira** [comment]
Nvidia has caused some issues with sodium, maybe this is an instance of that? I'm guessing that if it's the nvidia sodium issue, Iris has nothing to do with this. See https://github.com/CaffeineMC/sodium-fabric/issues/1830
