### ISSUE TITLE
crashes when I enable BSL shaders

### ISSUE THREAD

**Issue by Aces-and-Jacks** [IrisShaders/Iris#1861]
### Minecraft Version

1.19.2

### Iris Version

1.5.0

### Sodium Version

0.4.4+build.18

### Operating System

MacOS

### What is your GPU?

M1

### Java Version

Java 17

### Reproduction Steps

1. I load up instance
2. Enable BSL shader
3. Load into world
4. game crashes

### Crash Report file and latest.log

```shell
https://mclo.gs/Bw5CzYu
```

### Additional context

On a fresh instance it works fine, so maybe a mod or resource pack is somehow conflicting but I don't know what it may be. I can look it'd just take a while

**Comment by Aces-and-Jacks** [comment]
It was chunks fade in

**Comment by coderbot16** [comment]
ChunksFadeIn is injecting into Iris and is accessing internal code, so all bets are off for compatibility with it. We can't do anything about this issue.
