### ISSUE TITLE
iris not working, even when downgrading

### ISSUE THREAD

**Issue by En1gmaTrash** [IrisShaders/Iris#1877]
### What happened?

new sodium update, also iris. no matter even if i downgrade everything my game wont start up. just saying i need a compatible version of sodium. no version works for me, even when i downgrade sodium

### Minecraft Version

1.19

### Iris Version

any

### Operating System

windows 11

### What is your GPU?

3060

**Comment by IMS212** [comment]
Iris doesn’t support 1.19, only 1.19.2.
