### ISSUE TITLE
Kappa 5.0 enters fallback in Nether and End

### ISSUE THREAD

**Issue by Vir7ualll** [IrisShaders/Iris#1890]
### What happened?

Using the latest Iris and Sodium for 1.19.3, Kappa 5.0 falls back when entering the nether or end where the game renders them as if no shaders are on even when refreshed, entering the settings for shaders confirms the fallback when the title of the shader mentions its in fallback state. Other shaders work fine like SEUS PTGI or Complementary, and this was tested on Quilt and Fabric with the only mods being Iris and Sodium (and Essential which shouldn't affect shading or graphics at all), to the same result. The shader was tested with its default presets as well such as Low and High to the same result. I tried updating my Nvidia drivers which still had not fixed the issue.

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10746786/latest.log)

### Minecraft Version

1.19.3

### Iris Version

iris-mc1.19.3-1.5.2.jar

### Operating System

Windows 10

### What is your GPU?

RTX 3080

### Additional context

The log included is made using only the three mods mentioned before (iris, sodium, essential) on Quilt for 1.19.3.

**Comment by IMS212** [comment]
This is a known issue, and will be fixed on Kappa's side.
