### ISSUE TITLE
Tripwire doesn't cast shadow, as it should be like in Optifine

### ISSUE THREAD

**Issue by camelovaty** [IrisShaders/Iris#1892]
### What happened?

Tripwire has layer.cutout_mipped=tripwire
Tested also layer.cutout=tripwire
Both properties are working fine with Optifine, but not Sodium/Iris

Of course I use CIT Resewn

### Screenshots

![image](https://user-images.githubusercontent.com/102817128/219510673-90a83dc8-c355-40d7-a2fc-3b9914cca48c.png)

### Minecraft Version

1.19.2

### Iris Version

iris-1.19.2.temp , but version may not matter

### Operating System

Windows 10

### What is your GPU?

RTX 2070

**Comment by IMS212** [comment]
The "tripwire" layer does not exist on modern Sodium.
