### ISSUE TITLE
1.19.4 branches, unable to close after opening Shader

### ISSUE THREAD

**Issue by vlssu** [IrisShaders/Iris#1896]
### What happened?

1.19.4 branches 9679ba2efb4e6f6404762bfe8ba1cdb6ef3a7ab2, cannot be closed after opening Shader
But the shortcut key "K" can disable the light and Shader

### Screenshots

![image](https://user-images.githubusercontent.com/43847794/220013573-c8bfd1da-ddc8-49ed-a45b-9485efa49888.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10779762/latest.log)

### Minecraft Version

23w07a

### Iris Version

9679ba2efb4e6f6404762bfe8ba1cdb6ef3a7ab2

### Operating System

windows 11

### What is your GPU?

RTX 2070S

### Additional context

https://github.com/vlssu/Iris/tree/1.19.4

**Comment by Lolothepro** [comment]
Fixed
