### ISSUE TITLE
blockEntityId and entityId uniforms are almost certainly broken

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#19]
Minecraft renders block entities and regular entities substantially differently in 1.15+ compared to previous versions. As such, it's much harder to track exactly what entity is currently being rendered, since entities are often drawn to the screen whenever a *different* entity starts being rendered.

The reason for this is how `VertexConsumerProvider.Immediate` works: with the exception of a few special render layers, whenever entity render layers are switched the content of the previous layer is immediately drawn to the screen.

It's unclear whether uniforms even work here anymore. Maybe attributes will need to be used? That would require some pretty hacky code changes to shaders however.

**Comment by coderbot16** [comment]
This probably also applies to `entityColor` as well.

**Comment by thedocruby** [comment]
Is it possible that this issue has been fixed or in some way averted by the recent changes to entity rendering?
