### ISSUE TITLE
Crash when generating portal with Immersive portals

### ISSUE THREAD

**Issue by machinesmith42** [IrisShaders/Iris#190]
https://paste.gg/p/anonymous/6eecb2fc634b43a787eec9c42d4af4a0

**Comment by machinesmith42** [comment]
Potential for fix?

**Comment by coderbot16** [comment]
Not super likely in the near term, though there has been preparatory work... Immersive Portals compatibility isn't trivial to say the least

**Comment by qouteall** [comment]
PR: https://github.com/IrisShaders/Iris/pull/425

@machinesmith42 I've seen your sodium fork and appreciated your efforts, however, I am going to remake my sodium fork on the iris sodium fork now so you don't need to work on that.

**Comment by IMS212** [comment]
This _should_ be fixed with the merge of #425.
