### ISSUE TITLE
Compatibility for 1.8.9

### ISSUE THREAD

**Issue by Save14** [IrisShaders/Iris#1901]
**Surprise! 1.8.9 is still in use and not everyone uses optifine.**
Personally, I'd like 1.8.9 Iris, I know minecraft 1.8.9 is completely different, but it's still opengl, try it!
Maybe make it for forge, I'd really appreciate that!

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris#but-wheres-the-forge-version
&&
https://github.com/IrisShaders/Iris/issues/1484#issuecomment-1153140223

**Comment by IMS212** [comment]
No.

**Comment by douira** [comment]
In case you were hoping for an elaboration on why there is no 1.8.9 port: It's very hard and nobody is interested in investing that time and effort. See the explanation in the readme https://github.com/IrisShaders/Iris#but-wheres-the-forge-version and the linked comment https://github.com/IrisShaders/Iris/issues/1484#issuecomment-1153140223. TLDR: you are invited to do it yourself, we aren't interested nor is it feasible.

**Comment by PumpkinXD** [comment]
they wont backport Iris for PVP nerds
 and versions before 1.13 are using lwjgl2 not 3(and forge not fabric)
