### ISSUE TITLE
Broken textures with shaders

### ISSUE THREAD

**Issue by Energobro** [IrisShaders/Iris#1903]
### What happened?

When using a custom texture pack on armor, the texture breaks and cannot be fixed in any way. Everything works fine without shaders, I think the problem is in Iris

### Screenshots

![image](https://user-images.githubusercontent.com/61550676/221378645-5b39dd6e-0b7e-4eac-b473-ba7b66a34bfc.png)
![image](https://user-images.githubusercontent.com/61550676/221378658-53b3379b-ac75-4def-8342-ba76956775b4.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/10832253/latest.log)

### Minecraft Version

1.19.2

### Iris Version

Iris 1.6.0-beta.2

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 3050 TI Laptop GPU

**Comment by TheCaJlaT** [comment]
I have same problem at 1.19.4

**Comment by coderbot16** [comment]
This is most likely related to core shaders being used on armor - please confirm whether or not core shaders are in use.

**Comment by TheCaJlaT** [comment]
> This is most likely related to core shaders being used on armor - please confirm whether or not core shaders are in use.

I hope this video will be useful.
Video card: 1660 super 6GB
Processor: Ryzen 5 5500
Ram: 16 GB Crucial 3200
All this custom armor is leather.
1:38 - Video Settings and f3
https://www.youtube.com/watch?v=5zr315zE7uM
