### ISSUE TITLE
Iris for 1.19/1.19.1 and Sodium compatibility

### ISSUE THREAD

**Issue by DelofJ** [IrisShaders/Iris#1904]
### What happened?

If you download Iris 1.5.2 for 1.19/1.19.1 and the latest Sodium version (0.4.2), it will ask for a newer Sodium version, even if there is none

### Minecraft Version

1.19 - 1.19.1

### Iris Version

Iris 1.5.2

### Operating System

Windows 10

### What is your GPU?

AMD RX 6650 XT

**Comment by douira** [comment]
This issue can be closed as it's only relevant to old versions.
