### ISSUE TITLE
Square around sun and moon on Simplicissimus

### ISSUE THREAD

**Issue by Juesto** [IrisShaders/Iris#1906]
### What happened?

When selecting Simplicissimus_v1.2.zip in shader packs the sun and moon have a square around it, see screenshots.
I've verified this happens on a clean state without mods as well.

### Screenshots

![2023-03-05_17 15 54](https://user-images.githubusercontent.com/12691160/222983580-986fbca9-9b01-4514-b0d7-7216b05b6d8b.png)
![2023-03-05_17 17 17](https://user-images.githubusercontent.com/12691160/222983628-de5a032b-5773-4f01-bb78-04c0f36898ad.png)
![2023-03-05_17 19 32](https://user-images.githubusercontent.com/12691160/222983740-9c9d7fe5-84dc-45b6-9984-f3d02cb6b790.png)

### Log output

very noisy session 
[latest.log](https://github.com/IrisShaders/Iris/files/10892860/latest.log)

### Minecraft Version

1.19.2

### Iris Version

1.5.2

### Operating System

Windows

### What is your GPU?

NVIDIA GeForce GTX 1660

**Comment by IMS212** [comment]
Fixed in an upcoming version of Simplicissimus.
