### ISSUE TITLE
Consider allowing shaders to interface properly with colored light mods

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#191]
While it would ultimately be up to the shader to actually use the colored light data, this would be nice to have in general.

**Comment by coderbot16** [comment]
Here's one colored lights mod for MC 1.17: https://github.com/Gegy/colored-lights

**Comment by DarkShadow44** [comment]
Interesting, though this approach is radically different. Maybe I'll come around one day to finish my idea... Not sure how exactly an interface for colored lights would work though, I'll start with a plain fork of Iris.

**Comment by coderbot16** [comment]
Closing this due to there not really being any viable colored light mods that are compatible with Sodium at this time.
