### ISSUE TITLE
Broken "center" parameter in pregeneration process - 2 bugs

### ISSUE THREAD

**Issue by lukipukix** [IrisShaders/Iris#1913]
### What happened?

I just discovered that setting "center=10,10" in pregeneration process is actually moving coordinates (+/- ofc) from 0,0 to 5120,5120. **one unit = 512 block**

Another bug with this thing: **second position of "center" parameter in pregeneration process doesn't change anything at all**. (btw this is most important thing for me xd)

Image below shows left upper corner (first) and right down corner (second) coordinates with different center positions on pregenerated maps with radius=1000. I checked this by moving world to singleplayer and entering on it with Xaero's World Map mod installed so I could see rendered terrain.

### Screenshots

![image](https://user-images.githubusercontent.com/98988597/224636143-d292d8db-4918-4742-a9be-a3d118f057c2.png)

### Log output

[2023-03-12-5.log](https://github.com/IrisShaders/Iris/files/10954734/2023-03-12-5.log)

### Minecraft Version

1.19.3

### Iris Version

Iris-2.4.2-1.19.3.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 3060TI

**Comment by lukipukix** [comment]
On image I entered "center" values with space bar but I didn't entered space bars in command ofc ;)

**Comment by IMS212** [comment]
I think you're on the wrong "Iris" mod, this is a shaders mod.
