### ISSUE TITLE
Campanion tent previews are rendered incorrectly

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#192]
![image](https://user-images.githubusercontent.com/22420959/112390888-3c622900-8cb4-11eb-8dea-ebcf057c12a4.png)

**Comment by coderbot16** [comment]
Relevant code: https://github.com/TerraformersMC/Campanion/blob/f67cc0bf1373b7afa6b4f2de5eb6927a75963e33/src/main/java/com/terraformersmc/campanion/mixin/client/MixinWorldRenderer.java

**Comment by thedocruby** [comment]
Something similar used to happen with Litematica schematics, but now this happens: #358 
Someone should verify that this still occurs the same way in the most recent release.

**Comment by coderbot16** [comment]
Confirmed as fixed in the bulletproof-state-tracking branch:

![image](https://user-images.githubusercontent.com/22420959/162607025-719802e0-0aa5-49fa-a913-2b24adae130e.png)
