### ISSUE TITLE
iris crashing on MacOS

### ISSUE THREAD

**Issue by babispice2002** [IrisShaders/Iris#1925]
### Minecraft Version

1.19.4

### Iris Version

1.19.4

### Sodium Version

N/A

### Operating System

macOS 

### What is your GPU?

Apple M1 13.2.1 

### Java Version

java version 8, update 361

### Reproduction Steps

I was able to run Iris once and but now when I try to launch the game from "Iris & Sodium for 1.19.4" it crashes and says "Exit Code 6". I even downloaded Java just to try to run this program. My MacBooks system software is up to date, alongside my Minecraft launcher. 

### Crash Report file and latest.log

```shell
https://gist.github.com/babispice2002/78cd428822681ed682f21b4ae18ebb46
```

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/blob/1.18.2/docs/usage/drivers.md

**Comment by purple512** [comment]
It's not a mod issue, it's an Apple issue. As the link above says, M1 Macs are not supported due to pitiful OpenGL support on ARM.
