### ISSUE TITLE
{1.19.4} Certain shaders crashing my game

### ISSUE THREAD

**Issue by Pinecone6442** [IrisShaders/Iris#1927]
### What happened?

I was playing with a shader I made, and this shader specifically freezes the game after a bit. It might be my computer but the shader is built off of gl4es.

### Screenshots

no screenshots. just goes black for a second.

### Log output

couldn't find logs.

### Minecraft Version

Minecraft 1.19.4

### Iris Version

1.5.2 (1.19.4)

### Operating System

Windows 11

### What is your GPU?

Intel(R) Iris(R) Xe Graphics

### Additional context

pls fix its my favorite shader, had this since 1.19.3

**Comment by Pinecone6442** [comment]
Actually here is a screenshot of it if that helps 
![2023-03-30_21 39 39](https://user-images.githubusercontent.com/111191736/229193970-7ef10274-1491-4900-82a1-7b65cf76fbf8.png)

**Comment by Lolothepro** [comment]
Can you give the log file?

**Comment by Pinecone6442** [comment]
> Can you give the log file?
> 
> > How to get a log file:
> > Game logs can be found in the logs sub-directory in .minecraft on clients, or the logs sub-folder of the server directory for servers. We're probably interested in the file named latest.log, which you can drag and drop into Github.

this is happening on my friends multiplayer server, and any server that it multiplayer, so how???

**Comment by IMS212** [comment]
go to .minecraft on your pc, not the server. you can get a log there.

**Comment by Pinecone6442** [comment]
[2023-03-31-5.log.gz](https://github.com/IrisShaders/Iris/files/11127925/2023-03-31-5.log.gz)
i think this is it
