### ISSUE TITLE
Bufferunderflow when rendering

### ISSUE THREAD

**Issue by thegatesdev** [IrisShaders/Iris#1930]
### Minecraft Version

Minecraft 1.19.3

### Iris Version

iris-mc1.19.3-1.5.2

### Sodium Version

mc1.19.3-0.4.9+build.23

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1060 6GB

### Java Version

Java 17

### Reproduction Steps

I am not able to reproduce this crash a second time myself.
I have tried rejoining the same world with no changes made and it worked fine after that.

### Crash Report file and latest.log

```shell
Crash report couldn't be pasted here because of character limit, nor uploaded since it's a code field so I put it in Additional Context
```

### Additional context

Crash report file:
[crash-2023-04-01_20.22.19-client.txt](https://github.com/IrisShaders/Iris/files/11130312/crash-2023-04-01_20.22.19-client.txt)
Session log file:
[2023-04-01-7.log](https://github.com/IrisShaders/Iris/files/11130305/2023-04-01-7.log)

This crash occurred when using Complementary Reimagined 2.0.3 Shaderpack

**Comment by Lolothepro** [comment]
remove cull leaves

**Comment by thegatesdev** [comment]
> remove cull leaves

Is this a known fix? It's quite hard to test since it happens on rare occasions, if so I'll close the issue
