### ISSUE TITLE
Asynchronous Reprojection

### ISSUE THREAD

**Issue by ExecuteOrd66** [IrisShaders/Iris#1931]
**Is your feature request related to a problem? Please describe.** 
Low FPS can be frustrating, but implementing Asynchronous Reprojection in Iris could make low-fps gameplay “feel” much smoother than it actually is (inspired by a recent Linus Tech Tips video).

**Describe the solution you’d like I would like**
Asynchronous Reprojection to be implemented in Iris.

**Describe alternatives you’ve considered**
FSR (preferably FSR 2.1) could also be added, but I see an active thread has already been opened for this.

**Additional context**
Here’s a link to the video that inspired me: https://www.youtube.com/watch?v=IvqrlgKuowE

I apologise if this thread lacks the necessary context or knowledge of the field. I'm not a developer.

**Comment by IMS212** [comment]
OpenGL does not support this functionality.
