### ISSUE TITLE
Banner Rendering Bugged

### ISSUE THREAD

**Issue by Awsome-Creeper9** [IrisShaders/Iris#1941]
### What happened?

Banners are all glitched out (in Iris 1.6.0)

### Screenshots

![RethinkingVoxelsBanners](https://user-images.githubusercontent.com/62125559/231035975-4f7f9e04-00b7-46a2-bcb4-40feae9ded74.png)

### Minecraft Version

1.19.2

### Iris Version

1.6.0

### Operating System

Windows 11

### What is your GPU?

RTX 3070

### Additional context

Sodium is included in my mods folder

**Comment by DEAFG0AT** [comment]
I have the same issue, and wrongly assumed it was one of the banner mods I was using and submitted a bug report there. Here it is:

https://github.com/Darkhax-Minecraft/AdditionalBanners/issues/38#issue-1663235932

**Comment by RealTabman** [comment]
Same problem, just want to add my system specs.
Switching back to version 1.5.2 renders banner correctly again. 
To me it looks as if the order of the banner layers is rendered in the wrong order.

**Minecraft Version**
1.19.2

**Iris Version**
1.6.0

**Operating System**
Windows 10

**What is your GPU?**
Nvidia GTX 1660

**Comment by Lolothepro** [comment]
This bug also occurs in Minecraft 1.19.4 without Sodium

**Comment by IMS212** [comment]
Fixed in 1.6.1.
