### ISSUE TITLE
Iris 1.6.0: Broken lead textures

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1942]
### What happened?

\

### Screenshots

![image](https://user-images.githubusercontent.com/68275908/231221692-72c5cce5-f4ec-4c90-9ff4-a9d43c214812.png)

### Minecraft Version

1.19.4

### Iris Version

1.6.0

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

**Comment by 0xENDER** [comment]
Same thing happening here (GTX 1650)
