### ISSUE TITLE
Don't support unsupported versions of Minecraft

### ISSUE THREAD

**Issue by mrjasonn** [IrisShaders/Iris#1945]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please do not support unsupported versions of Minecraft such as 1.18.2 and only support the ones that mojang supports.

**Describe alternatives you've considered**
Not applicable

**Additional context**
A way to determine if mojang has unsupported that version is checking if realms work on [insert version].

**Comment by Timolino456** [comment]
Why though

**Comment by DmanMC** [comment]
what would this even do to benefit anyone (other than ims :trollface: )

**Comment by IMS212** [comment]
Older versions will be dropped when it is deemed too hard to support.
