### ISSUE TITLE
Crash on startup, possible cross-mod incompat issue

### ISSUE THREAD

**Issue by ChromaPIE** [IrisShaders/Iris#1946]
### Minecraft Version

1.19.2

### Iris Version

1.6.1

### Sodium Version

0.4.4+build.18

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1650

### Java Version

Java 17

### Reproduction Steps

1. Have the mods shown in the log provided below
2. Start the game

### Crash Report file and latest.log

```shell
Too long. See Additional context for link
```

### Additional context

https://mclo.gs/1WzLRQF

**Comment by An-thracene** [comment]
The same problem with you.  I think it's the problem of Chunks fade in, Memory Leak Fix and Iris.
log:
[latest.log](https://github.com/IrisShaders/Iris/files/11239146/latest.log)

**Comment by IMS212** [comment]
Fade In Chunks does unsafe injections into Iris. They must fix this.
