### ISSUE TITLE
Texts are black when shaderpack enabled

### ISSUE THREAD

**Issue by charlie-moomoo** [IrisShaders/Iris#1947]
### What happened?

I just updated to Iris 1.6.1, when I joined my server, I soon noticed all texts were black, including the scoreboard, pause menu, etc.

What did I expect to happen: All texts are original colors
What did I do to trigger the bug:
1. Update to Iris 1.6.1
2. Enable a shaderpack
3. Join a world/server
4. All texts were black

### Screenshots

![image](https://user-images.githubusercontent.com/65603222/232258091-153ea3d3-06dd-4ef5-80ed-6bec21a95254.png)
![image](https://user-images.githubusercontent.com/65603222/232258100-f3156789-e3f1-44b6-adcd-7b9ee9a0a356.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/11240873/log.txt)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

Iris 1.6.1

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce GTX 1650

### Additional context

```
[07:05:30] [Render thread/INFO]: Hardware information:
[07:05:30] [Render thread/INFO]: CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
[07:05:30] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1650/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 516.91)
[07:05:30] [Render thread/INFO]: OS: Windows 10 (10.0)
```
I'm using Windows 11, not Windows 10.

**Comment by charlie-moomoo** [comment]
Edit: without the shaders, it looks like this
![image](https://user-images.githubusercontent.com/65603222/232258213-47100aa9-478b-453c-9401-d0d014ac2a78.png)

**Comment by IMS212** [comment]
This is caused by ImmediatelyFast, please update it.
