### ISSUE TITLE
Iris 1.6.1 1.19-1.19.2 version requires Sodium 0.4.10 for 1.19.4

### ISSUE THREAD

**Issue by Sukasa** [IrisShaders/Iris#1960]
### What happened?

Trying to get Iris working on MC 1.19 (it's to match a server).  Iris has a version on Modrinth available supporting 1.19-1.19.2, but requires Sodium 0.4.10 which is only available for 1.19.4

### Minecraft Version

Minecraft 1.19

### Iris Version

Iris 1.6.1-1.19.2

### Operating System

Windows 10

### What is your GPU?

GeForce RTX 3080 Ti

**Comment by IMS212** [comment]
I don't think that's possible. Could I get a log file?

**Comment by Sukasa** [comment]
Absolutely.  Log file, and screenshot of what shows up when I run it
https://paste.ee/p/L6CbX
![IrisError](https://user-images.githubusercontent.com/1186656/233817737-073b8ded-ffab-42db-aae9-28ac4ee31450.png)

**Comment by Sukasa** [comment]
Also even on Modrinth it shows as needing 0.4.10
![Modrinth](https://user-images.githubusercontent.com/1186656/233817761-7c4ae114-80fe-410d-b01a-ccd1eae03cf9.png)

**Comment by Sukasa** [comment]
Okay I worked this and as it turns out, this version only needs Sodium 0.4.4.  *that* version of Sodium is marked as 1.19.2 only but it does appear to be working fine, when testing with KappaPT

**Comment by IMS212** [comment]
Fixed
