### ISSUE TITLE
Banners are rendering wrong side & banner item is only rendering first pattern

### ISSUE THREAD

**Issue by charlie-moomoo** [IrisShaders/Iris#1963]
### What happened?

Since the last time, I found an all-text black bug ( #1947 ), I have downgraded the Iris version to 1.6.0. Soon I entered the game, I opened my ender chest and noticed the item was only rendering the first pattern. I took out the banner and placed it down, I notice the banner patterns were rendered at the backside.

What did I expect to happen: The banner's patterns are rendering at the front side & banner item is rendering all patterns
What did I do to trigger the bug:
1. Get a banner with some patterns on it
2. Look at the item
3. Place down the banner & look at the backside

### Screenshots

![image](https://user-images.githubusercontent.com/65603222/234001211-79bcbb8f-7abc-4a86-97b5-6e2afb37af14.png)
![image](https://user-images.githubusercontent.com/65603222/234001258-8b31d9ac-dcb2-4887-bf5b-5e49a1315914.png)
![image](https://user-images.githubusercontent.com/65603222/234002306-3c675918-8ee8-45ff-9bee-a8992c968a7a.png)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

Iris 1.6.0

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce GTX 1650

**Comment by IMS212** [comment]
This bug was fixed in 1.6.1.
