### ISSUE TITLE
Names rendering as black on Mesa

### ISSUE THREAD

**Issue by thehellrocc** [IrisShaders/Iris#1969]
### What happened?

Names aren't rendering properly on Mesa 23.0.3 (and latest mesa-git on AUR) on an AMD card when any shader pack is enabled on Iris (including latest public test build). This only seems to be happening on Mesa (both RadeonSI and zink), as I couldn't reproduce this on Windows 11 using latest Adrenaline.

### Screenshots

![immagine](https://user-images.githubusercontent.com/33247035/234875935-ff51d835-1bed-4e0b-811a-be75d37a8856.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/11344002/latest.log)

### Minecraft Version

1.19.4

### Iris Version

1.6.1

### Operating System

Arch Linux

### What is your GPU?

RX 6800 XT

**Comment by Lolothepro** [comment]
Note: This does not happen with Iris 1.5.2.

**Comment by Kichura** [comment]
Can confirm, also applies to any texts that exist in the world itself. *(Example; Signs)*

**Comment by Kichura** [comment]
This is solved in iris 1.6.2 RC 2 now.

**Comment by thehellrocc** [comment]
Just tried it, can confirm. Great!
