### ISSUE TITLE
Iris not detecting sodium

### ISSUE THREAD

**Issue by 0PandaDEV** [IrisShaders/Iris#1977]
### What happened?

I installed the newest version of iris and sodium and also a few other mods and every time I start minecraft it says “Iris failed to load. Install Sodium for iris to work."

### Screenshots

![image](https://user-images.githubusercontent.com/70103896/235634021-92c4703b-9ffd-4aa3-b9e1-f150579a4b68.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/11371846/latest.log)

### Minecraft Version

1.19.3

### Iris Version

iris-mc1.19.3-1.5.2

### Operating System

Windows 10

### What is your GPU?

Intel HD Graphics 520

**Comment by purple512** [comment]
Iris 1.5.2 requires Sodium 0.4.9 and doesn't support Sodium 0.4.11.

At the moment that's your only option as Iris 1.6.x dropped support for 1.19.3, but it looks like there may be a one time backport of Iris 1.6.2 for 1.19.3 that does support Sodium 0.4.11. There's a test build on the discord at the moment, release TBD, or you can just install Sodiu 0.4.9.
