### ISSUE TITLE
Crash on rendering bee nest

### ISSUE THREAD

**Issue by variety754** [IrisShaders/Iris#1979]
### Minecraft Version

1.19.3

### Iris Version

iris-mc1.19.3-1.5.2.jar

### Sodium Version

 sodium-fabric-mc1.19.3-0.4.9+build.23.jar

### Operating System

Windows 11

### What is your GPU?

RTX 3080 Laptop GPU

### Java Version

16

### Reproduction Steps

1. Break bee hive with Wilder Wild, Clear Despawn and Iris Shaders with project luma shaders on
2. See the crash

### Crash Report file and latest.log

```shell
https://mclo.gs/gOrkzOW
```

**Comment by IMS212** [comment]
This doesn't seem related to Iris, please ask the Wilder Wild's devs.
