### ISSUE TITLE
No enchantment glint on Enhanced Default

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#198]
Reproduced on the current version of standalone Iris

![image](https://user-images.githubusercontent.com/22420959/112552835-afd16c80-8d80-11eb-9a8e-b85e12eec029.png)

![image](https://user-images.githubusercontent.com/22420959/112552858-b95ad480-8d80-11eb-9882-2cc72a579cb0.png)

**Comment by coderbot16** [comment]
If you manually chance the brightness in options.txt, you can see the enchantment glints:

```
gamma:100.0
```

![image](https://user-images.githubusercontent.com/22420959/112553707-3d618c00-8d82-11eb-9174-1cbf00d2c09d.png)

**Comment by tedhong9** [comment]
This seems to be related with Sodium and is tracked here: https://github.com/CaffeineMC/sodium-fabric/issues/231

**Comment by coderbot16** [comment]
The bugs may be related, though I got the above images when running with no mods other than Iris. Interesting.

**Comment by coderbot16** [comment]
This appears to be caused by the lightmap coordinates not being set when rendering enchantment glints on modern versions of the game.

**Comment by GRUI72** [comment]
How to Fix:
Open sildurs enhanced default settings (if you use iris without settings download iris with settings in iris discord)
Go to "colors"
Toogle on setting "custom lightmap" and set "red" "green" and "blue" to 1.0
Enjoy!
If this not working, sorry.
