### ISSUE TITLE
When I disable my shader game crashes 

### ISSUE THREAD

**Issue by zcexq** [IrisShaders/Iris#1980]
### Minecraft Version

minecraft 1.19.2 fabric

### Iris Version

iris-mc1.19.2-1.6.1

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18

### Operating System

windows 11

### What is your GPU?

Nvidia GeForce RTX 3060

### Java Version

Java 19 (im playing 1.19.2 if that helps)

### Reproduction Steps

1. Have your shaders enabled
2. Disable the shaders
3. Game crashes 
OR
1. Press K to enable shaders
2. Game crashes

**Comment by IMS212** [comment]
We need a log file.
