### ISSUE TITLE
Incompatible with More Block Predicates

### ISSUE THREAD

**Issue by NaiNonTH** [IrisShaders/Iris#1981]
### Minecraft Version

Minecraft 1.19.4

### Iris Version

iris-mc1.19.4-1.6.2.jar

### Sodium Version

sodium-fabric-mc1.19.4-0.4.11+build.26.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1060 6GB

### Java Version

Default for 1.19.4

### Reproduction Steps

1. Install Iris and Sodium mod with MBP
2. Launch the game
3. Game crashes

### Crash Report file and latest.log

```shell
N/A
```

## Logs
[latest.log](https://github.com/IrisShaders/Iris/files/11399571/latest.log)

**Comment by IMS212** [comment]
Upgrade to Iris 1.6.3 and downgrade Sodium to 0.4.10.

**Comment by Poopooracoocoo** [comment]
also tracked in https://github.com/omoflop/MoreBlockPredicates/issues/19
