### ISSUE TITLE
i cant turn off shaders

### ISSUE THREAD

**Issue by jcomprendpa** [IrisShaders/Iris#1984]
### What happened?

A bug happened! when i turn off sharders i literally cant see anything expect entities..

### Screenshots

![image](https://user-images.githubusercontent.com/132729287/236597253-e8e729b4-5593-42cd-b8b4-bd4bf62bc285.png)
![image](https://user-images.githubusercontent.com/132729287/236597265-0e2c990e-1658-485d-8d8e-526519db75fb.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/11411207/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.6.2

### Operating System

Windows 10

### What is your GPU?

NVidia Geforce 960

**Comment by coderbot16** [comment]
Update Sodium to resolve this likely issue with disabling fog if you have not already.
