### ISSUE TITLE
no sodium version warning for invalid version

### ISSUE THREAD

**Issue by Inormal-human** [IrisShaders/Iris#1986]
### What happened?

A bug happened!

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/11412531/latest.log)

### Minecraft Version

1.19.4

### Iris Version

iris-mc1.19.4-1.6.1

### Operating System

win 11

### What is your GPU?

Nvidia GeForce gtx 1650

### Additional context

vivecraft  was used when the thing happened with a oculus quest connect with a cable

**Comment by Lolothepro** [comment]
update Iris

**Comment by IMS212** [comment]
Fixed in https://github.com/IrisShaders/Iris/commit/31ea0e297a647628284fddd3acf60a1427696386.
