### ISSUE TITLE
Fullscreen resolution is smaller than monitor's native resolution

### ISSUE THREAD

**Issue by BossAydan** [IrisShaders/Iris#1987]
### What happened?

I've recently had a problem where the resolution of my client isn't the same as my monitor. And because there's no
way to change resolution, I don't have an idea of what's causing this.

### Minecraft Version

1.19.2

### Iris Version

Iris 1.19.2

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce 1660 Super

**Comment by BossAydan** [comment]
Nevermind, I didn't know Vanilla settings were accessible because there's nothing in Iris that mentions Shift+P.

**Comment by douira** [comment]
that's a thing sodium does, not Iris.
