### ISSUE TITLE
Incorrect no sodium warning, game crashes on joining any world

### ISSUE THREAD

**Issue by cootshk** [IrisShaders/Iris#1988]
### Minecraft Version

1.19.3

### Iris Version

1.5.2

### Sodium Version

0.4.11 beta (build 25)

### Operating System

Windows 11 Home (x86)

### What is your GPU?

Nvidia RTX 3060

### Java Version

Java 17 (OpenJDK)

### Reproduction Steps

Launch game
You get an incorrect `No Sodium!` warning (it still shows up in modmenu)
there is no shader packs button in Minecraft settings
joining any world or server crashes the game

### Crash Report file and latest.log

https://mclo.gs/en2mqG1 logs
https://mclo.gs/9P3RwXz crash report

### Additional context

Using the replay mod replay viewer button to get around the no sodium screen

**Comment by purple512** [comment]
Iris 1.5.2 is not compatible with Sodium 0.4.11. These two mods are highly paired and have specific requirements. The valid combinations are:

Iris 1.6.2 + Sodium 0.4.11

OR

Iris 1.5.2 + Sodium 0.4.9

Note: Iris 1.6.2 for Minecraft 1.19.3 has not been released, but there is a test build available on the discord. It should be released in the near future. Or you can use MC 1.19.4.

**Comment by cootshk** [comment]
Thanks, that fixed it.
