### ISSUE TITLE
Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: entity_translucent

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#199]
I haven't been able to reproduce this myself, but I've seen it popping up in a few logs. Some help in finding out what is needed to trigger this message would be nice.

**Comment by thedocruby** [comment]
Could someone confirm that this still happens since the changes to buffered entity rendering?

**Comment by NoComment1105** [comment]
This has happened again with a new issue opened (#722)

**Comment by coderbot16** [comment]
Removing the "more information needed" tag since this whole system will be removed in a future refactor.
