### ISSUE TITLE
iris breaking text after todays update

### ISSUE THREAD

**Issue by blaxcrowl** [IrisShaders/Iris#1993]
### What happened?

After updating Iris today, my Text ingame is appearing just as squares.
Iris is the only mod that updated, but when I tried to use one of the old versions, it still isn't working.
I tried to open my World with the squares, but it crashed.

### Screenshots

![Minecraft 10_05_2023 20_28_17](https://github.com/IrisShaders/Iris/assets/132266660/2a98f51b-65da-4b6a-951c-29ed7d80cd0e)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/11444979/latest.log)

### Minecraft Version

Minecraft 1.19.4

### Iris Version

1.6.3

### Operating System

Windows 10

### What is your GPU?

Nvidia 2060

**Comment by Pee-bag** [comment]
How did you fix this? I'm having the same problem.

**Comment by IMS212** [comment]
This is caused by a too recent Indium or Sodium version.

**Comment by Pee-bag** [comment]
So i need to get an earlier version of those mods?

**Comment by IMS212** [comment]
Yes.
