### ISSUE TITLE
Offer hotkeys for adjusting render distance

### ISSUE THREAD

**Issue by mk-pmb** [IrisShaders/Iris#1999]
**Is your feature request related to a problem? Please describe.**
When using the pie chart to locate mob spawners, I need to click a lot of buttons or press lots of keys each time I want to increase the render distance by one. Even when I automate this using my macro recorder, I then need almost as many interactions to see the numeric value of the render distance that turned out to be correct.

**Describe the solution you'd like**
In the key bindings, I can set keys for "Render distance +1" and "Render distance -1".
Even better if I can use a three-key combination rather than a single key. (Others might prefer less or more.)
Iris would then log to ingame chat a message like "Render distance is now 4."

**Describe alternatives you've considered**
[My bash script to send the required keystrokes via xdotool.](https://github.com/mk-pmb/minecraft-nether-roof-biomes-marker/blob/master/util/set_render_distance.sh)

**Additional context**

**Comment by IMS212** [comment]
This was in Vanilla, but then removed for an unknown reason. Iris probably won't readd it.

**Comment by mk-pmb** [comment]
I see. I'll extend my script then to guess current value by tracking its own invocations. Does anyone know a mod that adds the hotkeys back?
