### ISSUE TITLE
text breaks when launching minecraft

### ISSUE THREAD

**Issue by Idk-A-Username** [IrisShaders/Iris#2003]
### What happened?

when minecraft opens the text is broken and just has a bunch of rectangles like in mysticats vid when he deleted the text file for minecraft but when i get rid of iris it fixes itself

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/96555042/fb161163-bf31-4a43-8e10-25403e23214d)

### Minecraft Version

Minecraft 1.19.4

### Iris Version

iris-mc1.19.4-1.6.3.jar

### Operating System

Windows 11

### What is your GPU?

Intel(R) UHD Graphics 620

**Comment by Idk-A-Username** [comment]
also it gave this

Error: java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null

the exit code is:
-1

**Comment by purple512** [comment]
Most likely you have the wrong version of Sodium. The Iris version you have (1.6.3) requires Sodium 0.4.10. Any other version will cause the kind of issues you're seeing. You should post a game log, it's the best way to convey all the technical details required.

**Comment by Idk-A-Username** [comment]
> Most likely you have the wrong version of Sodium. The Iris version you have (1.6.3) requires Sodium 0.4.10. Any other version will cause the kind of issues you're seeing. You should post a game log, it's the best way to convey all the technical details required.

so idk how to reply to you but when i

**Comment by Idk-A-Username** [comment]
when i try using 0.4.10 it says i need 0.4.11 sodium, which i installed straight from github since its not on modrinth

**Comment by purple512** [comment]
What screen is telling you that you need 0.4.11? Is it in-game? Or in your launcher? That shouldn't be the case, as Iris 1.6.3 was specifically released to be compatible with Sodium 0.4.10. Verify that you're really using 1.6.3.

Posting a game log (`logs\latest.log` under your minecraft game dir) would be a big help too.

**Comment by Idk-A-Username** [comment]
fabric loader 0.14.20 is saying:
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Replace mod 'Sodium' (sodium) 0.4.10+build.24 with version 0.4.11.
the error it lets me copy is:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.10+build.24 with version 0.4.11.
Unmet dependency listing:
	 - Mod 'Indium' (indium) 1.0.17+mc1.19.4 requires version 0.4.11 of mod 'Sodium' (sodium), but only the wrong version is present: 0.4.10+build.24!
	 - Mod 'Fastload Fabric-api Forwarding' (fastload_fapi_forward) 1.0.2 requires version 1.20 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
and also how do i post a game log? im in .minecraft in the logs folder what do i do now?

**Comment by purple512** [comment]
Oh, that's Indium complaining. You need to downgrade Indium to 1.0.15, and then Sodium 0.4.10 should work.

The same applies to any other mod that depends on the internals of Sodium.

**Comment by Idk-A-Username** [comment]
wow that was it! Thanks!
