### ISSUE TITLE
Enchantment glint z-fighting on Sildur's Vibrant Shaders Lite

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#201]
I wasn't able to reproduce this myself, but saving it here in case someone else does manage to reproduce it.

> was just walking around in the nether on lite and seems like enchantment glints have z-fighting

![image](https://user-images.githubusercontent.com/22420959/112559648-aa7b1e80-8d8e-11eb-9075-8a6b07564a97.png)

![image](https://user-images.githubusercontent.com/22420959/112559640-a51dd400-8d8e-11eb-87f4-9df1054f479d.png)

**Comment by edwloef** [comment]
I am able to reproduce it, it seems to only happen with certain camera angles

**Comment by edwloef** [comment]
This may be due to Sodium's Compact Vertex Format?

**Comment by coderbot16** [comment]
I wasn't able to reproduce this with Iris standalone, it would be worth trying it with just Iris and confirming if it's an issue that only happens with Sodium installed

**Comment by coderbot16** [comment]
I couldn't reproduce it before because I was testing in the overworld, but this bug only happens in the nether and end. This appears to be a shaderpack bug, not an Iris bug: https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/158

I'm going to create a documentation file to track common shader pack bugs like this that seem like Iris bugs. They don't belong on the issue tracker, but keeping a list to reference would be good.
