### ISSUE TITLE
Blocks wont load/render when i turn off shaders.

### ISSUE THREAD

**Issue by TugeyWugey** [IrisShaders/Iris#2010]
### What happened?

Entitys and block data loads, like item frames, mob entities and sign data, but blocks have no texture and is just void as you can see in the image. I have updated to the newest version of the mod and its still broken, not too sure (im on feather, and its 1.19.2. Ive had no problems with it in the past few weeks untill now)

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/135239352/3266b195-6d39-4ef5-8820-fadd9726651b)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.6.2 

### Operating System

Windows 11

### What is your GPU?

Geforce 1650

**Comment by coderbot16** [comment]
Not enough information is present to say for sure, but this is likely caused by some incompatibility between Sodium and mods used to remove fog. If you are still facing this problem after updating all mods please open a new issue with more information.
