### ISSUE TITLE
In ColorSpace option, SRGB is not spelled as sRGB (spelling issue)

### ISSUE THREAD

**Issue by mrjasonn** [IrisShaders/Iris#2016]
### What happened?

In ColorSpace option, SRGB is not spelled as sRGB which is a spelling issue.

### Minecraft Version

Minecraft Java 1.20

### Iris Version

Iris 1.6.4 mc1.20

### Operating System

Not applicable (spelling issue)

### What is your GPU?

Not applicable (spelling issue)

**Comment by IMS212** [comment]
minor spelling mistake

**Comment by Lolothepro** [comment]
fixed
