### ISSUE TITLE
Make ColorSpace have an Auto option

### ISSUE THREAD

**Issue by mrjasonn** [IrisShaders/Iris#2018]
**Is your feature request related to a problem? Please describe.**
Yes, because not everyone might know their screen's colour space or get confused with it and they might want to use their screen's colour space.

**Describe the solution you'd like**
Make ColorSpace have an Auto option which automatically detects your screen's colour space and uses it so the problems above will be solved.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No additional context

**Comment by IMS212** [comment]
Not possible with current access to system in Java, GLFW doesn't allow this yet.
