### ISSUE TITLE
The graveyard : Skeleton creeper incorrect animation with Fresh Animations

### ISSUE THREAD

**Issue by blinker44** [IrisShaders/Iris#2021]
### What happened?

The animation does not work for a regular creeper, but it works for a skeleton creeper when there is a regular one nearby

Resource pack:
Fresh Anmations 1.8

Mods:
• sodium-fabric-mc1.19.2-0.4.4+build.18
• sodium-extra-0.4.16+mc1.19.2-build.90
• CITResewn-1.1.2+1.19.2
• continuity-2.0.2+1.19
• entity_model_features_fabric_1.19.2-0.2.9
• entity_texture_features_fabric_1.19.2-4.4.4
• fabric-api-0.76.0+1.19.2
• geckolib-fabric-1.19-3.1.40
• indium-1.0.9+mc1.19.2
• modmenu-4.2.0-beta.2
• moonlight-1.19.2-2.2.38-fabric
• starlight-1.1.1+fabric.ae22326
• supermartijn642corelib-1.1.9d-fabric-mc1.19.2
• supplementaries-1.19.2-2.3.17-fabric

• !!! The_Graveyard_2.3.3_(FABRIC)_for_1.19.2 !!!
• !!! iris-mc1.19.2-1.6.4 !!!

1. When there are no regular creepers nearby, spawn a skeleton creeper;
2. Spawn an regular creeper;
3. Move an regular creeper yourself or wait until he starts moving on his own;
4. See the dependence of the skeleton creeper animation on the regular one.

bug is not reproduced without iris

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.6.4

### Operating System

Windows 10

### What is your GPU?

RTX 2060

**Comment by IMS212** [comment]
Iris does not do animations.
