### ISSUE TITLE
Fix the correct translucent sorting.

### ISSUE THREAD

**Issue by surfishs** [IrisShaders/Iris#2023]
### What happened?

Many translucent materials fail because of incorrect translucent sequencing, such as the failures mentioned in (https://github.com/tr7zw/FirstPersonModel/issues/359).
I hope you can fix this bug, it's a long-standing problem.

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/96485650/2d04e4e9-9d4b-435c-be60-015d74875a49)
![image](https://github.com/IrisShaders/Iris/assets/96485650/3912e1e5-7891-4a48-a4c0-6f1dabd9a055)

### Minecraft Version

Minecraft1.20

### Iris Version

1.6.2

### Operating System

windows10

### What is your GPU?

RTX3060

### Additional context

https://github.com/tr7zw/FirstPersonModel/issues/359

**Comment by douira** [comment]
As you describe, this bug is caused by the lack of translucency sorting. Translucency sorting is up to Sodium to implement and the maintainers of Sodium are well aware of this situation.
