### ISSUE TITLE
The text turns black after i turn on shader

### ISSUE THREAD

**Issue by MoTao233** [IrisShaders/Iris#2024]
### What happened?

i update iris from 1.5.2 to 1.6.4, but i have some problem. the text turns black after i turn on shader

### Screenshots

![2023-06-14_21 11 20](https://github.com/IrisShaders/Iris/assets/136603340/141da6e1-aca2-4f99-9e46-68955b74f3f0)

### Minecraft Version

1.19.4

### Iris Version

1.6.4

### Operating System

win11

### What is your GPU?

4060 Laptop

**Comment by IMS212** [comment]
Caused by Feather Client.
