### ISSUE TITLE
Crash with shaderpack, PBR resource pack and Create

### ISSUE THREAD

**Issue by TheFurryDevil** [IrisShaders/Iris#2033]
### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.6.4

### Sodium Version

sodium-fabric-mc1.19.2-0.4.4+build.18

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1060 6GB

### Java Version

Java 17

### Reproduction Steps

1. Install Iris and Create
2. Activate shaderpack and resource pack
3. Create new world
4. Place Create fluid tank and steam engine
5. Game crashes

### Crash Report file and latest.log

[crash-client.txt](https://pastebin.com/Sjm9mMEL), [latest.log](https://pastebin.com/gQ51ZJ3n)

### Additional context

The resource and shaderpacks can be found here: [Create-PBR](https://modrinth.com/resourcepack/create-pbr/version/7), [Complementary Reimagined](https://modrinth.com/shader/complementary-reimagined/version/r2.2).
Tested with `create-fabric-0.5.1-b-build.1079+mc1.19.2` as well as the version mentioned in the logs.
I wasn't sure if this would need to be fixed in Create, the resource or shaderpack or Iris, but the latter made most sense to me. Sorry if that's wrong.

**Comment by diarm56** [comment]
Hmmmm. Seems like an issues with flywheel compat. A compatibility layer between iris and create integrated in create. 
Might be better to checks directly on their side.
Btw does it happens without Iris?

**Comment by TheFurryDevil** [comment]
No, it only happens when the shaderpack and resource pack are both active. I tested Complementary and Complementary Reimagined shaders, but ultimately it happens as soon as the resource pack is added. It does, however, not happen if I disable shaders, place the Create steam engine, and then enable shaders again. Haven't tested Optifine if that's what you mean.

**Comment by TheFurryDevil** [comment]
I'm doing more testing and now it crashed after disabling the resource pack before loading into a world and placing a Create steam engine, but then after restarting the game with it still disabled it did not crash. So somehow it didn't like that the resource pack was enabled in that instance?

**Comment by diarm56** [comment]
Hmmm. That's a bit strange. Could you try with a different ressource pack?

**Comment by TheFurryDevil** [comment]
I did have a lot of other resource packs enabled while playing before I even tried investigating this, some of them were PBR textures for vanilla blocks (Embrace Pixels, Vanilla PBR), others just normal resource packs. I haven't run into any issues with those. Just tried some random Create resource pack and that was fine too, so it's just the Create PBR pack that causes issues.

**Comment by diarm56** [comment]
Okay. Honestly I have no idea why. ^^'

**Comment by TheFurryDevil** [comment]
I narrowed it down to the `/assets/minecraft/optifine/texture.properties` in the resouce pack. Removing it seems to fix the crash, and the pack works as expected. It's still related to shaders since it only crashes with a shaderpack active, but honestly this works for me.

**Comment by TheFurryDevil** [comment]
I guess enabling shaders in Iris makes it use that file, and it is faulty or something. I'm not familiar with those assets.
