### ISSUE TITLE
Iris conflicts With Physics Mod

### ISSUE THREAD

**Issue by SkyTheNerd** [IrisShaders/Iris#204]
I don't know if you can fix it because Physics mod got closed sourced a few weeks ago. You can try if you want.

**Comment by coderbot16** [comment]
Iris has been compatible with physicsmod for a while now, and I specifically implemented code for compatibility... please provide more information on what you mean.

**Comment by coderbot16** [comment]
Could you please provide a log, a screenshot, or a crash report, anything that shows what you mean by "conflicts"?

**Comment by coderbot16** [comment]
Cannot reproduce. Until you provide more information, I cannot investigate this issue further.

![image](https://user-images.githubusercontent.com/22420959/112916811-212d5a00-90b6-11eb-9a2c-63e864bd3409.png)

**Comment by SkyTheNerd** [comment]
I can't load into the game with these two mods installed. :/
I was using this Sodium compatible version
[Compiled artifacts for Iris Shaders.zip](https://github.com/IrisShaders/Iris/files/6255443/Compiled.artifacts.for.Iris.Shaders.zip)
I got this message when I launched the game.
![Why does this have to happen to me](https://user-images.githubusercontent.com/79011616/113522957-baef7e00-9572-11eb-8002-7947914dacf6.PNG)

**Comment by IMS212** [comment]
You are using an extremely old version of Iris without the physics mod compatibility, please build the latest sodium compatibility code and try again.

**Comment by SkyTheNerd** [comment]
o

**Comment by cawoodm** [comment]
Noob here, googling how to get Iris+Sodium+PhysicsMod lands me (and others presumably) here. Would anyone mind posting exactly *how* one adds mods like PhysicsMod to Iris? Just adding `physics-mod-2.9.7-mc-1.18.2-forge.jar` to `.minecraft\mods` does not seem to do anything.

PS: The [irisshaders.net](https://irisshaders.net/) site, while gourgeous, doesn't really explain to newbies what it is. Is it a mod loader? Is it a mod? Is it a shader loader? There is also no "Getting Started" section, at least not that I found.

**Comment by Lolothepro** [comment]
> Noob here, googling how to get Iris+Sodium+PhysicsMod lands me (and others presumably) here. Would anyone mind posting exactly _how_ one adds mods like PhysicsMod to Iris? Just adding `physics-mod-2.9.7-mc-1.18.2-forge.jar` to `.minecraft\mods` does not seem to do anything.
> 
> PS: The [irisshaders.net](https://irisshaders.net/) site, while gorgeous, doesn't really explain to newbies what it is. Is it a mod loader? Is it a mod? Is it a shader loader? There is also no "Getting Started" section, at least not that I found.



https://github.com/IrisShaders/Iris/blob/1.18.2/docs/guide.md#manual-installation

**Comment by TheZogle** [comment]
i've got this

**Comment by TheZogle** [comment]
i've got this.

**Comment by JunnA85** [comment]
> i've got this. ![image](https://private-user-images.githubusercontent.com/165183626/317329744-e0963a95-f398-4ed6-bd31-df15d8a63c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTU5MTAsIm5iZiI6MTcxMTc1NTYxMCwicGF0aCI6Ii8xNjUxODM2MjYvMzE3MzI5NzQ0LWUwOTYzYTk1LWYzOTgtNGVkNi1iZDMxLWRmMTVkOGE2M2M1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQyMzQwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGNiMjYzY2Y4ODNjNDVkNWNiMTRlMjVkNmRkZThiZDA0NzY3MTM1OTY1NzBlYTI1YmViNzhlNTE4ZDdlMmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NrDCeHk7NoegGtDL2OtMDg84SC7w__TRe01_j_Lft6A)

Same

**Comment by FedotovDev8801** [comment]
> i've got this. ![image](https://github.com/IrisShaders/Iris/assets/165183626/e0963a95-f398-4ed6-bd31-df15d8a63c5e)

same

**Comment by GeassKnightmare** [comment]
So physics mod are not compatible anymore? because I got the same issue.


<img width="662" height="151" alt="Image" src="https://github.com/user-attachments/assets/8cb4d771-b830-4ae8-8e14-e3ecb6c525c5" />
