### ISSUE TITLE
All GUI Text turns black when using shaders

### ISSUE THREAD

**Issue by radstevee** [IrisShaders/Iris#2046]
### What happened?

All GUI Text turns black when using shaders. When using gamma (tweakGammaOverride by Tweakeroo or Gamma Utils) above 2.5/5 (needs testing) everything works. But that's like the whole point of shaders, to have lighting.

### Screenshots

![2023-07-08_21 11 20](https://github.com/IrisShaders/Iris/assets/96977790/8b38b1f4-4cf4-4236-9c72-000d00342865)
![2023-07-08_21 11 16](https://github.com/IrisShaders/Iris/assets/96977790/2b656501-8816-40d9-bfdb-de47ab1c1944)

### Log output

https://0x0.st/H1U7.txt

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20-1.6.4.jar

### Operating System

GNU/Linux

### What is your GPU?

GeForce GTX 1050 Ti

### Additional context

Mod list can be found in the log

Not using Feather client

Does work with gamma above 2.5/5 (needs testing)

**Comment by Reber01Good** [comment]
Looks similar to my problem, where lines turn black: https://github.com/IrisShaders/Iris/issues/2045

**Comment by Lolothepro** [comment]
> Looks similar to my problem, where lines turn black: #2045

They're not related.

**Comment by kaprutt** [comment]
I have the exact same problem, it's really annoying.

**Comment by radstevee** [comment]
> I have the exact same problem, it's really annoying.

If you use Feather Client, that's the reason

**Comment by kaprutt** [comment]
> > I have the exact same problem, it's really annoying.
> 
> If you use Feather Client, that's the reason

How does that make any sense?

**Comment by douira** [comment]
you have a very large amount of mods. If you figure out which of these mods causes the issue, it would be possible to debug it

**Comment by radstevee** [comment]
> > > I have the exact same problem, it's really annoying.
> > 
> > 
> > If you use Feather Client, that's the reason
> 
> How does that make any sense?

Feather is known to have Issues with Iris.

**Comment by Kaze977** [comment]
I had the same problem, finally it was caused by this mod: ImmediatelyFast

**Comment by radstevee** [comment]
> I had the same problem, finally it was caused by this mod: ImmediatelyFast

I have it disabled....

**Comment by radstevee** [comment]
Seems to be working when updating all mods and using Iris 1.6.4 (haven't tried 1.6.5 yet...)
