### ISSUE TITLE
Corrupted render

### ISSUE THREAD

**Issue by Jack253-png** [IrisShaders/Iris#2049]
### What happened?

Shader pack: IterationT 3.0.0
there is some render bugs when I use this pack

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/83895170/c4d84479-785e-449f-8ad9-116d42f9b162)
![image](https://github.com/IrisShaders/Iris/assets/83895170/3f5db693-a820-4b32-bef0-ebd02cccdb32)
![image](https://github.com/IrisShaders/Iris/assets/83895170/b57c85b1-91d2-4442-90d9-201eeaa47469)
![image](https://github.com/IrisShaders/Iris/assets/83895170/35652662-e875-48b0-8c74-a9a6abe154f7)

### Log output

null

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.6.4.jar

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce 1050

### Additional context

null

**Comment by misaka10384** [comment]
关闭泛光可临时修复

**Comment by Jack253-png** [comment]
itt3关泛光会有什么影响吗？



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月28日 08:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [IrisShaders/Iris] Corrupted render (Issue #2049) |

关闭泛光可临时修复

**Comment by IMS212** [comment]
IterationT is not supported.
