### ISSUE TITLE
Spam in log file "Profiler tick ended before path was fully popped (remainder: 'root'). Mismatched push/pop?"

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#2050]
### What happened?

Spam in log file "Profiler tick ended before path was fully popped (remainder: 'root'). Mismatched push/pop?"

### Minecraft Version

Minecraft 1.20.1

### Iris Version

Iris 1.6.4

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Additional context

Switch to spectator mode
Apply shaders (Comp Reim)
Press F3+Shift

**Comment by douira** [comment]
Does this https://github.com/IrisShaders/Iris/commit/1d385c5afddf77fdc08b340a88fbba75edc9aab8 fix the issue?

**Comment by Lolothepro** [comment]
> Does this [1d385c5](https://github.com/IrisShaders/Iris/commit/1d385c5afddf77fdc08b340a88fbba75edc9aab8) fix the issue?

Yes
