### ISSUE TITLE
`IrisTextVertexSink` uses wrong vertex offsets when shaders are disabled

### ISSUE THREAD

**Issue by SquidDev** [IrisShaders/Iris#2053]
### What happened?

 - Install Sodium, Iris, and ComputerCraft in a fresh instance.
 - Configure Iris with the default settings (i.e. no shaders)
 - Place down a computer and a monitor next to it.
 - Write something to the monitor (e.g. `monitor left paint a`).
 - Observe the monitor is very dark.

A similar issue was reported back in April (https://github.com/IrisShaders/Iris/issues/1959), and marked fixed. It's not clear if this is another regression, or if the bug was only fixed in the case of shaders.

### With shaders
![A screenshot of a ComputerCraft monitor displaying the paint program.](https://github.com/IrisShaders/Iris/assets/4346137/4aefed7e-3768-49bd-93c0-92b22c936cb7)

### Without shaders
![A screenshot of a ComputerCraft monitor displaying the paint program. The monitor is dark, almost appearing blank.](https://github.com/IrisShaders/Iris/assets/4346137/1b5b0e25-d936-48f1-90fb-bd99faaf779e)

### Log output

https://mclo.gs/Mfr0e2k

### Minecraft Version

Minecraft 1.19.4

### Iris Version

iris-mc1.19.4-1.6.4

### Operating System

Linux, but I've had reports on Windows too.

### What is your GPU?

AMD Ryzen 7 Pro 4750U, confirmed on other GPUs

### Additional context

See also https://github.com/cc-tweaked/CC-Tweaked/issues/1502 and https://github.com/cc-tweaked/cc-restitched/issues/148 for related issues.

**Comment by SquidDev** [comment]
Finally sat down with RenderDoc and looked at this.

Inspecting the input of the vertex shader, we can see that UV2 set is set to (0, 10), when we'd expect it to be fullbright. This causes the output colour to be incredibly dark.

![A screenshot of a table with columns titled "Idx", "Colour", "UV0", "UV2". All rows in UV2 are equal to (0, 10)](https://github.com/IrisShaders/Iris/assets/4346137/4abba938-4e6d-4f76-b712-86d19c588ff6)

Looking at the VBO itself, we can see that UV2 has an offset of 24, while `IrisTextVertexSinkImpl` hard-codes an offset of 28.

![A screenshot of the various attributes in our VBO. The last one, UV2, has an offset of 24.](https://github.com/IrisShaders/Iris/assets/4346137/0f3096d8-9868-422f-9c2b-3c4c2eea2b9f)

https://github.com/IrisShaders/Iris/blob/77b3ea225d87fae9257eda774e59fb5430ae60a0/src/main/java/net/coderbot/iris/vertices/IrisTextVertexSinkImpl.java#L43

I'm assuming what's going on here is that the Iris hard codes the offsets for `IrisVertexFormats.ENTITY`. However, because shaders aren't active, [this code](https://github.com/IrisShaders/Iris/blob/1.20.1/src/main/java/net/coderbot/iris/mixin/vertices/MixinVertexFormat.java#L20-L29) is skipped and so we're actually rendering with the default `POSITION_COLOR_TEX_LIGHTMAP` vertex format.

**Comment by Vol1t** [comment]
Recently I came across this problem on ATM9, and discovered that the problem was on Oculus/Iris, I just removed it, if you are not going to use Shaders I highly recommend removing it from your mod pack, the monitors return to normal almost than immediately.

**Comment by douira** [comment]
IMS pushed a commit that fixed this issue as you can see in the history here
