### ISSUE TITLE
Enchant glint adjustments are not applied when shaders are enabled

### ISSUE THREAD

**Issue by mpar-22** [IrisShaders/Iris#2054]
### What happened?

The enchantment glint intensity setting (found under accessibility settings) is not applied when shaders are enabled. I have linked a video showcasing the issue (pay attention to the sword on the right).

### Screenshots

https://medal.tv/games/minecraft/clips/1j9QwjyLxgrcPn/d1337pfc5i0v?invite=cr-MSxjT3osMzU5Nzg3MjAs

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/12034426/latest.log)

### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20-1.6.4.jar

### Operating System

Windows 11 22H2

### What is your GPU?

AMD Radeon 6600 XT

### Additional context

I initially brought this up in the complementary shader discord, but they suggested I bring it here especially since its not relegated to a single shader.

**Comment by BlueJayofEvil** [comment]
I'm having the same issue. Tested with various different shader packs, only works fine when shaders are disabled.

**Comment by IMS212** [comment]
The shader must support `gl_Color.a` for glint intensity to work.

**Comment by mpar-22** [comment]
I talked with Emin, he's said he's implemented what you have mentioned, but the issue still persists on the latest version of Iris (1.6.8) and Complementary Reimagined (r2.3). I think this should be looked into more, as something isn't working properly.
