### ISSUE TITLE
Shader wont work in the nether

### ISSUE THREAD

**Issue by nicogb2007** [IrisShaders/Iris#2058]
### What happened?

A bug happened!

### Screenshots

When i entered the nether my shader disabeled

this is the debug message : 
Pass sizes must match for drawbuffers [0, 5]
Original width: 1920 New width: 256 Original height: 1017 New height: 384

### Log output

[2023-07-19-1.log.gz](https://github.com/IrisShaders/Iris/files/12089521/2023-07-19-1.log.gz)

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20-1.6.4.jar

### Operating System

windows 10

### What is your GPU?

RTX 2060

**Comment by IMS212** [comment]
Update Kappa.
