### ISSUE TITLE
Iris shaders Cant work with Vulkan renderer mod

### ISSUE THREAD

**Issue by Whydoesthishappen** [IrisShaders/Iris#2059]
### What happened?

A bug happened! It inmediately crashes and cant start minecraft.

### Minecraft Version

1.19.2

### Iris Version

iris mc 1.19.3 1.5.2

### Operating System

Windows 10 

### What is your GPU?

Intel UHD Graphics 600

### Additional context

btw the gpu may not appear if you search it in google

**Comment by Timolino456** [comment]
That's normal and not a bug, Iris doesn't work with Vulkanmod and won't in the near future, if ever
