### ISSUE TITLE
Textures Not Loading

### ISSUE THREAD

**Issue by Solace615** [IrisShaders/Iris#2071]
### What happened?

I've noticed sometimes whenever I look downwards the textures for some chunks will just disappear out of nowhere.

### Screenshots

![2023-08-03_23 16 42](https://github.com/IrisShaders/Iris/assets/141384785/0ad1acba-4047-411d-8cb3-6423676c6e31)

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20-1.6.4

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3070

**Comment by coderbot16** [comment]
Not an Iris bug. This is a well-known chunk culling bug in Sodium that has been worked on and should be resolved in the latest versions of Sodium
