### ISSUE TITLE
New update message doesn't have the correct link

### ISSUE THREAD

**Issue by MinecraftNight4** [IrisShaders/Iris#2076]
### What happened?

When the game loads a world o servers, this message appears.
"[CHAT] Iris 1.6.5 has released, with performance improvements and bug fixes, along with some minor features. Download it at: **the Iris Installer**"

The problem with this is that when you click on **the Iris Installer**, it shows the link "https://irisshaders.net", instead of "https://irisshaders.dev"

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/42017416/19dd87d4-7ea1-432a-b98e-972f3325c636)
![image](https://github.com/IrisShaders/Iris/assets/42017416/02b58791-b366-491d-adb2-15f4668b90f5)

Connection Rejected:
![image](https://github.com/IrisShaders/Iris/assets/42017416/cd33dbe7-896f-43c6-98ef-d535fb7a39cf)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/12267611/latest.log)

### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-fabric-loader-1.14.21-1.20.1/fabric/Fabric

### Operating System

Windows 10

### What is your GPU?

NULL

**Comment by IMS212** [comment]
Fixed, remove the cached update files in .minecraft or wait a day to see the change.
