### ISSUE TITLE
LS RenderPearl crashes since Iris 1.6.5

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#2077]
```Shader compilation log for iris:sodium-terrain-shadow.vsh: 0(39) : error C1503: undefined variable "Chunks"```
https://mclo.gs/bMCcc8U

**Comment by kolgushev** [comment]
Replicated the issue fairly easily with Renderpearl 1.7 (https://mclo.gs/EeN9Che) and confirmed it with [a dev build of my own shaderpack](https://github.com/IrisShaders/Iris/files/12296614/Pixel-Perfect-Latest.zip) (https://mclo.gs/IWFCiG0).

I think the problem arises when a shader declares the varying vaPosition with `in vec3 vaPosition;` - glsl-transformer replaces any references to it with `Chunks[_draw_id].offset.xyz + _vert_position` but doesn't declare `Chunks` anywhere (and for that matter, doesn't remove the `vaPosition` declaration).

**Comment by IMS212** [comment]
Already fixed in dev branches.

**Comment by IMS212** [comment]
*Should* be fixed in 1.6.6.
