### ISSUE TITLE
Crash with immersive portals after latest compatability updates

### ISSUE THREAD

**Issue by NovaXe** [IrisShaders/Iris#2078]
### Minecraft Version

1.20.1

### Iris Version

1.6.5

### Sodium Version

0.5.0

### Operating System

WIndows 10

### What is your GPU?

RTX 3070

### Java Version

Java 17

### Reproduction Steps

Run game with the latest iris, immersive portals and sodium at the time of writing.
Enable shaders
Create new world
press k to disable shaders
witness crash
[crash-2023-08-05_16.13.01-client.txt](https://github.com/IrisShaders/Iris/files/12268098/crash-2023-08-05_16.13.01-client.txt)

### Additional context

Running on quilt with Quilted Fabric API

**Comment by drakosoldier298** [comment]
can confirm this happens on normal fabric as well.

**Comment by LunarPidgeon** [comment]
Happening to me as well.

(github should really add a "me too" button if there isnt already)

**Comment by douira** [comment]
GitHub lets you react to the issue with a thumbs up emoji, which is generally regarded as "I also have this issue" or "I also want this issue to be fixed". However, there isn't any more UI around it in the issue list. (though additional comments also only add to the number on the right)

**Comment by IMS212** [comment]
Immersive Portals must fix this.
