### ISSUE TITLE
Render distance forced to 2 when shaders are disabled.

### ISSUE THREAD

**Issue by IAmLexica** [IrisShaders/Iris#2080]
### What happened?

Render distance is inconsistent and depends on whether shaders are disabled or not. When enabled, the render distance option works as intended. When disabled, chunk rendering will always act as if it were set to 2 chunks, some view culling in the sky such as clouds does seem to function normally however.

### Screenshots

I don't have screenshots, but I did record it. https://youtu.be/YzjeiiWb3O4

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/12283011/latest.log)

### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.5

### Operating System

Win 11

### What is your GPU?

Nvidia GeForce RTX 3080 10GB

### Additional context

This seems like something that would have definitely been spotted before being released, so I will be searching for mod incompatibilities that might be the cause.

**Comment by coderbot16** [comment]
This is an issue between Sodium and your no fog mod. Updating your mod versions should fix it.
