### ISSUE TITLE
Shaders doesn't work in custom dimensions?

### ISSUE THREAD

**Issue by molor** [IrisShaders/Iris#2083]
### What happened?

If you play on 3rd-party server that have custom worlds (e.g. created via `Bukkit#createWorld()`, for example with key `minecraft:future`), moving to that world via teleport from overworld (`minecraft:overworld`, or any other vanilla world) with shaders enabled (in that case I'm using `Complementary Reimagined`) the game looks like shaders is just disabled.

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/19989717/330e5609-7cac-4566-b0a2-803ed89e79d4)
![image](https://github.com/IrisShaders/Iris/assets/19989717/0a885fd5-aeea-4203-9ee0-7310dc30f5b1)

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20.1-1.6.5.jar

### Operating System

W10

### What is your GPU?

RTX 2080 Super

### Additional context

Everything worked fine in every dimension/world before I'm updated `Sodium` to v5 and `Iris` to support new `Sodium` version.
I'm unsure that this is an `Iris` issue, so if not, please tell me the project whose developers I need to contact. Thanks!

**Comment by IMS212** [comment]
We are aware of this bug. A fix will be coming in Iris 1.6.6.

**Comment by Lolothepro** [comment]
fixed?
