### ISSUE TITLE
Playing with Iris and Sodium = 20 fps

### ISSUE THREAD

**Issue by Esperanzitozitozito** [IrisShaders/Iris#2089]
### What happened?

A bug happened!

### Screenshots

![2023-08-11_13 33 20](https://github.com/IrisShaders/Iris/assets/141989890/2958b4c3-5076-4806-83b7-9be12cd0fd43)
![2023-08-11_13 33 05](https://github.com/IrisShaders/Iris/assets/141989890/a448f8ef-94a6-4911-a089-47826e06ac88)
![image](https://github.com/IrisShaders/Iris/assets/141989890/98ced6f8-15bc-4777-897f-14389db45715)

### Minecraft Version

Minecraft 1,20,1

### Iris Version

1.20.1-1.6.5

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2070 super

### Additional context

When I try to play with Iris and Sodium, i get 20 fps just for walking, also, when i add mods in Fabric, and start a nerw wolrd, my game crash. Idk what to do.

**Comment by Darknesek** [comment]
Maybe try allocate more ram to the game, because from the screenshot I see you are only using 2 gb ram for minecraft. In my opinion this amount of ram is to small. Maybe try allocate like 6 gb or 4 gb for minecraft.

**Comment by Darknesek** [comment]
Oh and what mods do you tried to add or you are using for playing?

**Comment by Darknesek** [comment]
https://youtu.be/Ql4ANOdnIls Maybe this will help and also download sodium extra mod, because this mod will give you more extra settings to change in sodium. Hope this will help you

**Comment by IMS212** [comment]
This gives us literally no info.
