### ISSUE TITLE
Iris is considered optifabric for some reason

### ISSUE THREAD

**Issue by sm8925** [IrisShaders/Iris#2094]
### Iris is considered Optifabric by Labymod?
So I'm using labymod with fabric loader and it list some mods saying that they're incompatible with optifabric. I was confused when I saw that since I had never used optifabric, but the top of the list said that deleting Iris could solve the issue. I did that and all my mods worked fine after that, is there anyway to use iris without is being considered as optifabric and stopping some mods from working?

### Screenshots

https://imgur.com/a/16RxDyb

### Minecraft Version

1.20.1

### Iris Version

Iris 1.6.5

### Operating System

Endeavouros

### What is your GPU?

4070 TI

**Comment by IMS212** [comment]
The error says Iris is incompatible with OptiFabric, not that Iris is OptiFabric.

**Comment by sm8925** [comment]
yeah but removing it solves the optifabric thing

**Comment by douira** [comment]
the screenshot indicates that optifabric is indeed present. We cannot further diagnose the issue unless you post your log file, which you have omitted.

**Comment by sm8925** [comment]
https://paste.labymod.net/kicubaqure

Sorry for being late, but this should be the log
