### ISSUE TITLE
Crucial optimizations are disabled

### ISSUE THREAD

**Issue by andreasdc** [IrisShaders/Iris#2102]
### What happened?

What's the point in disabling crucial optimizations from Sodium? If this can't be fixed users should be heavily informed, because it takes A LOT from performance.

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20.1-1.6.7.jar

### Operating System

windows 10

### What is your GPU?

1060

**Comment by IMS212** [comment]
The only optimizations being disabled are fog culling (incompatible with shaders) and occlusion culling (only for the shadow pass). If there’s anything else I’m unaware of please tell me.

**Comment by andreasdc** [comment]
https://github.com/IrisShaders/Iris/blob/1b9467be2d48ee685f3b191849bacb97a5c5f2cc/src/main/resources/fabric.mod.json#L62

**Comment by IMS212** [comment]
Not disabled, we just copy them and make slight edits to better fit shaders.

**Comment by andreasdc** [comment]
I think I see better performance without Iris.
