### ISSUE TITLE
Invisible terrain and weird squares when using some shaders

### ISSUE THREAD

**Issue by motyI** [IrisShaders/Iris#2117]
### What happened?

Whenever I switch to a shader which does not change the shadows of the game, the terrain becomes invisible and random square patches appear in some places. Affected shaders are for example CPHSBC, Cinematic Color Correction and NoShader. I only have sodium with sodium extra and reese's sodium options, iris, modmenu, and fabric api installed.

### Screenshots

![2023-09-02_12 56 52](https://github.com/IrisShaders/Iris/assets/83429505/1ca276cf-8968-4112-8553-137d46c347c6)
![2023-09-02_13 05 53](https://github.com/IrisShaders/Iris/assets/83429505/b2435355-6bec-48da-a141-cf31c6044158)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/12503823/latest.log)

### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.8.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3060 Ti

**Comment by IMS212** [comment]
Fixed.
