### ISSUE TITLE
Enabling a color space other than sRGB causes a grid to appear

### ISSUE THREAD

**Issue by notLily72** [IrisShaders/Iris#2120]
### What happened?

If you enable any of the other color spaces than sRGB then a grid of pixels will appear on the screen.

### Screenshots

![Screenshot from 2023-09-04 11-40-10](https://github.com/IrisShaders/Iris/assets/86197720/d4c8705b-00ab-4818-9bd1-bad063c70495)
![Screenshot from 2023-09-04 11-40-22](https://github.com/IrisShaders/Iris/assets/86197720/6dfca881-60d3-4c62-9e39-f4b7cd7e2b8f)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/12515102/latest.log)

### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.8.jar

### Operating System

Arch Linux

### What is your GPU?

Intel Iris XE 80eu

**Comment by IMS212** [comment]
Seems like a compute related bug; may have to disable that pipeline and go fragment only. Shouldn't hurt performance too much.

**Comment by IMS212** [comment]
"Fixed"(?)
