### ISSUE TITLE
Iris redirects sodium's fluid renderer for seemly no reason, Making it incompatible with Hephaestus

### ISSUE THREAD

**Issue by AlphaMode** [IrisShaders/Iris#2121]
### What happened?

Iris seems to just redirects sodium's fluid renderer here https://github.com/IrisShaders/Iris/blob/bf8f51ac47192fe74e3bc28cc724e1ae76931dfc/src/sodiumCompatibility/java/net/coderbot/iris/compat/sodium/mixin/block_id/MixinChunkRenderRebuildTask.java#L89
Which prevents me from implementing my fluid models so that my mods fluids don't break when sodium is installed.
Here is my mixin which also redirects sodium's fluid renderer so I can support my fluid models https://github.com/AlphaMode/Star/blob/5b512b9837cf2a9a5740f208721d8a808a627345/src/main/java/me/alphamode/star/mixin/indium/ChunkBuilderMeshingTaskMixin.java#L29

### Minecraft Version

1.20.1

### Iris Version

1.6.8

### Operating System

Kubuntu

### What is your GPU?

Nvidia RTX 3070

**Comment by IMS212** [comment]
irrit fixed
