### ISSUE TITLE
subchunk outline

### ISSUE THREAD

**Issue by Noda-dalad** [IrisShaders/Iris#2125]
### What happened?

iris mod affects the color of the subchunk outline
make it invisible

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/100498670/727f792c-ae16-4e94-83e1-ccd75165a828)
![image](https://github.com/IrisShaders/Iris/assets/100498670/ac8b6d29-5af4-41c1-9d4a-9a45c6f7f607)

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20.1-1.6.8

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce RTX 2070 Max-Q

**Comment by hu-ja-ja** [comment]
Any update on this issue?
I'm still encountering it in version 1.8.0-beta.3+mc1.21.1.
![2024-08-28_03 14 19](https://github.com/user-attachments/assets/ee92324e-9612-4366-a027-0f1d4490621c)
