### ISSUE TITLE
Suggestion: Add a loading screen for shaders

### ISSUE THREAD

**Issue by NVGAT** [IrisShaders/Iris#2128]
**Is your feature request related to a problem? Please describe.**
Not a big problem, but it's kind of frustrating to have my game completely freeze upon enabling a shaderpack.

**Describe the solution you'd like**
It would be nice if a loading screen was there instead of a freeze, similar to how OptiFine does it by implementing the Mojang screen.

**Describe alternatives you've considered**
OptiFine does this quite well, as stated before

**Additional context**

**Comment by IMS212** [comment]
OptiFine does not have a loading screen for shaders. The loading screen seen is reloading resources, which is something Iris does not need to do.

**Comment by NVGAT** [comment]
> OptiFine does not have a loading screen for shaders. The loading screen seen is reloading resources, which is something Iris does not need to do.

Still, it could be nice not to have my game freeze upon enabling shaders.

**Comment by IMS212** [comment]
This isn't possible, because as shaders compile they take the thread normally used for... displaying the game.

**Comment by NVGAT** [comment]
> This isn't possible, because as shaders compile they take the thread normally used for... displaying the game.

Ah, i see. Thanks for clearing that up.
