### ISSUE TITLE
Fast Leaves support for internal shaders

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#2130]
Vanilla:
![2023-09-17_15 19 33](https://github.com/IrisShaders/Iris/assets/68275908/6375dfc3-8983-4aa6-85a0-b70dfa34f039)
Internal:
![2023-09-17_15 19 14](https://github.com/IrisShaders/Iris/assets/68275908/c1469a19-089b-49b1-907d-88ea653c3545)

**Comment by Lolothepro** [comment]
that was just an example, but it affects all shaders, Kappa, etc...

**Comment by IMS212** [comment]
Not a bug; if a pack does manual discards, this is working as intended.
