### ISSUE TITLE
Color saturation / vibrancy slider

### ISSUE THREAD

**Issue by not-holar** [IrisShaders/Iris#2135]
**Is your feature request related to a problem? Please describe.**
Minecraft looks pretty bleak and gray without shaders, i've seen questions about a saturation slider for the game for a while all over the internet.

**Describe the solution you'd like**
A vibrancy slider next to the brightness slider we already have. Ideally it would work both with and without shaders enabled.

**Describe alternatives you've considered**
There exist some programs that utilize the built-in vibrancy settings of graphics drivers, but they affect the whole system. Some constantly check which program is in the foreground, but this detection isn't always perfect and even when it works, it affects GUI, menus and other stuff.

**Additional context**
I've requested this in Sodium, but it got rejected as out-of-scope, hope this fits here

**Comment by IMS212** [comment]
This is up to the shader to add.

**Comment by not-holar** [comment]
why make people fill out all these fields for requests if you don't even read them

**Comment by IMS212** [comment]
Adding vibrancy to an existing shader via post processing ruins the shader look generally, because most shaders are tonemapped. It doesn't make sense in the context of HDR rendering.
