### ISSUE TITLE
Lightning strikes look wrong on Sildur's Vibrant Shaders

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#214]

**Comment by maxigator** [comment]
![2021-03-28_21 38 04](https://user-images.githubusercontent.com/22241832/112765552-f687c680-900d-11eb-8ac5-35103952ebd5.png)
![2021-03-28_21 38 06](https://user-images.githubusercontent.com/22241832/112765553-f7205d00-900d-11eb-84e7-fdd6b7fe6333.png)
![2021-03-28_21 38 09](https://user-images.githubusercontent.com/22241832/112765554-f7b8f380-900d-11eb-8487-4097d0143c5a.png)
![2021-03-28_21 38 10](https://user-images.githubusercontent.com/22241832/112765555-f7b8f380-900d-11eb-9d7f-cfa2ffcb7bf3.png)
(examples)
