### ISSUE TITLE
SEUS PTGI not working

### ISSUE THREAD

**Issue by SJK9906** [IrisShaders/Iris#2141]
### What happened?

iris can not load all SEUS PTGI

to reproduce isues:
install shades
[SEUS PTGI HRR 3.zip](https://github.com/IrisShaders/Iris/files/12838622/SEUS.PTGI.HRR.3.zip)
[SEUS PTGI E12.zip](https://github.com/IrisShaders/Iris/files/12838623/SEUS.PTGI.E12.zip)
select the shader SEUS PTGIR12 or SEUS PTGI HRR 3

### Screenshots

<img width="960" alt="image" src="https://github.com/IrisShaders/Iris/assets/129201282/e87cae3b-05ba-43cd-8fd7-b808d33b6776">

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/12838660/latest.log)

### Minecraft Version

minecraft 1.02.1

### Iris Version

iris-MC 1.6.9

### Operating System

windows 11 22H2

### What is your GPU?

geforce RTX 3060

**Comment by Lolothepro** [comment]
TLauncher is not supported, buy Minecraft
