### ISSUE TITLE
Enabling shaders causes buzzing in right audio channel

### ISSUE THREAD

**Issue by rooooose-b** [IrisShaders/Iris#2142]
### What happened?

Enabling a shader pack causes my right audio channel to constantly produce a buzzing sound. 

I can't seem to find which in-game volume slider it's connected to - none of the stop the noise, and even muting Minecraft in the Windows volume mixer entirely still doesn't stop it. However, I have not experienced it in any other scenario - it's only when I am in a loaded world/server with a shaderpack loaded. 

As soon as I disable the shaderpack the noise disappears, and when I enable it again the noise comes back. I have also tried several different shaderpacks, and the noise is there with all of them.

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/12847264/latest.log)

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20.1-1.6.9.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2060 SUPER

**Comment by douira** [comment]
That sounds like something in the shader pack is making the GPU produce electromagnetic interference that's getting into your audio. I don't think there's anything Iris can do here really. It might become less if you use a less intensive shader pack or limit the frame rate. Ultimately, in the case of interference is to separate the circuits better. I've had similar issues and the solution was to either use an external usb audio device or a different motherboard/gpu that happened to produce less interference. You can find more advice on reducing interference online.

**Comment by Dragon-Mom** [comment]
Getting the same issue weirdly enough. Specifically with Iris and Super Duper Vanilla causes it but not some of the more intensive shaders, and it changes depending on the direction I look.

**Comment by coderbot16** [comment]
As above, this is indeed likely caused by the various loads that Iris with shaders places on your graphics card. There is nothing we can do code-wise for this most likely.
