### ISSUE TITLE
No view bobbing with shaders enabled.

### ISSUE THREAD

**Issue by Slayer5934** [IrisShaders/Iris#2160]
### What happened?

Enable shaders, no view bobbing or hand bobbing.

### Screenshots

https://tekxit.lol/videos/2023-11-04%2017-54-44.mp4

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/13257814/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.6.11

### Operating System

EndeavourOS / Arch Linux

### What is your GPU?

RX 6700

### Additional context

[Mod list](https://docs.getgrist.com/rBtpTVAH7bTY/Tekxit)
I tried to disable mods that mention modifying the viewport like create, but was unable to find out any mod interfering..

**Comment by IMS212** [comment]
Does this happen with absolutely no other mods?

**Comment by SlayerTheChikken** [comment]
@IMS212 After hours of testing, this seems to be a conflict between Iris and Light Within

**Comment by SlayerTheChikken** [comment]
(forgot to mention shaders must be enabled)
