### ISSUE TITLE
Black flashing on Linux

### ISSUE THREAD

**Issue by peppidesu** [IrisShaders/Iris#2162]
### What happened?

Enabling any shaders causes black screen flickering. 

- The flickering is always present when navigating UI
- The flickering is worsened by running the game at a high refresh rate (165hz)
- The issue seems to be somewhat correlated to mouse movement and other input events.
- The flickering is at its worst right after enabling shaders, and when getting out of the menu it slowly gets better over time (but never disappears when running at 165hz)
- Sometimes the flickering is not black, but just dimmed.

I will provide more information after i give this a go on Xorg.

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/13260128/latest.log)

### Minecraft Version

1.20.2

### Iris Version

iris-mc1.20.2-1.6.10

### Operating System

Arch Linux

### What is your GPU?

Nvidia GeForce RTX 2060 SUPER

### Additional context

OS: Arch Linux x86_64
Kernel: 6.5.9-arch2-1
DE: Hyprland (hyprland-nvidia 0.31.0-2)
CPU: Ryzen 5 5600X
GPU: Nvidia GeForce RTX 2060 SUPER

I have nvidia DRM enabled.

**Comment by LarveyOfficial** [comment]
I have the exact same issue on EndeavorOS with KDE Wayland, but it seems that it also can happen without shaders. Unsure what is causing the problem...

**Comment by Averyfrog** [comment]
i have the same issue on hyprland
it seems to be whenever the game can’t render a frame in time, it just displays nothing instead of keeping the previous frame

**Comment by Hbarniq** [comment]
I had a similar issue that showed up after updating to Nvidia 545.29.02 drivers
same black flashing screen on Wayland, with or without shaders
for me turning on VRR (variable refresh rate) fixed the issue (which is now possible on Wayland after this driver update)

Iris and Sodium dont seem related as I had the same flicker on vanilla

_I'm not an expert on this just trying to help :]_

**Comment by Ai-Kiwi** [comment]
From my understanding towards this, this is an issue with the new NVIDIA drivers. You can find more info about this here : https://www.reddit.com/r/hyprland/comments/17y4s7o/screen_flickering_in_minecraft/ . This Issue happens in vanilla as well and is not a problem with iris. 

As a fix you can roll back your drivers to before this was an issue (described how todo in reddit post) however there is a fair chance this will brick your system as it did mine lmao (had to rollback to new ones lol)

**Comment by Averyfrog** [comment]
> As a fix till NVIDIA fixes this you can roll back your drivers to before this was an issue

this worked for me, luckily didn't brick my system either!
thanks :D

**Comment by IMS212** [comment]
well, we have our answer

fuck you Nvidia

**Comment by IMS212** [comment]
Update: I've started getting this issue too, and I've found a weird fix that involves changing Iris itself. I'll hide it under a hidden config option in the next release.

**Comment by IMS212** [comment]
If you want to fix it yourself, you need to install https://github.com/DanShaders/minecraft-wayland/tree/one-nineteen (to /usr/lib/libglfw.so), set prism to use native GLFW, and set __GL_THREADED_OPTIMIZATIONS=0

**Comment by ItzDerock** [comment]
Running into this same issue. The second shaders get enabled, the game is unplayable. Main menu and settings worked fine for me except the keybinds menu.

Minecraft 1.20.4 

System:
- NVIDIA driver 550.40.07 w/ 2070 SUPER
- Hyprland (built from source)
- Linux kernel 6.1.82, NixOS 23.11

After installing [WayGL](https://modrinth.com/mod/waygl) and [Wayland Fixes](https://modrinth.com/mod/wayland-fixes), the issue seems to be resolved.

**Comment by campfirelena** [comment]
The above fix worked for me too, NixOS Hyprland with 545.29.02. Cursors were duplicated until I disabled virtual cursor in WayGL. After disabling it keeps the mouse on the window with chat and inventories but not with pause screen. Not an issue for me but I thought it would help to put it here.

**Comment by cachandlerdev** [comment]
I seem to also be having this issue in X11. Given that the proposed solutions look like they're targetted at Wayland users, does anybody have any suggestions? The issue vanishes when I press `k` to disable shaders.

Edit: I was able to solve this issue by disabling G-Sync on my monitor.

**Comment by netcodedev** [comment]
> Running into this same issue. The second shaders get enabled, the game is unplayable. Main menu and settings worked fine for me except the keybinds menu.
> 
> Minecraft 1.20.4
> 
> System:
> 
> * NVIDIA driver 550.40.07 w/ 2070 SUPER
> * Hyprland (built from source)
> * Linux kernel 6.1.82, NixOS 23.11
> 
> After installing [WayGL](https://modrinth.com/mod/waygl) and [Wayland Fixes](https://modrinth.com/mod/wayland-fixes), the issue seems to be resolved.

Can confirm. This fixes the issue

**Comment by IMS212** [comment]
Installing 555 and the latest XWayland will fix this problem fully.

**Comment by 123happily** [comment]
Just fixed this issue by removing '-f' from my gamescope arguments. I tested other variables (iris/oculus, shaders, fullscreen, vsync, mouse capture/raw settings, possible conflicting mods, framerate/SDR/immediate-flips settings, TAA/motion blur settings, using WayGL as mentioned) and this was the only thing that worked lol

Update: there's still the occasional flicker (just one frame every few minutes). It's playable at least, so I don't overly mind. Just know this isn't a total fix.
