### ISSUE TITLE
Odd checkering pattern in BSL and Opal shaders with Iris 1.16.10

### ISSUE THREAD

**Issue by cryolithic** [IrisShaders/Iris#2165]
### What happened?

Using BSL or Opal shaders causes an unintended pattern to appear. On BSL it looks like it is a weird artifact of the tree leaves, but opal it is more pronounced. On BSL you can get rid of the issue by using the UIltra preset. This is not the case with Opal.

### Screenshots

![2023-11-12_06 54 11](https://github.com/IrisShaders/Iris/assets/11305845/c1b961ee-0e1a-43a0-8310-5d31cb671aa1)
![2023-11-12_06 53 41](https://github.com/IrisShaders/Iris/assets/11305845/2668f644-ce1c-40c8-b05a-2506417e838c)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/13328427/latest.log)

### Minecraft Version

1.20.2

### Iris Version

1.16.10

### Operating System

Windows 11

### What is your GPU?

6950 XT

### Additional context

New world, using fabulously optimized modpack. I can retest with just the most basic required mods if needed.

**Comment by IMS212** [comment]
This is a known issue with the newest drivers, and I will be getting a card in the near future to figure out the bug.

**Comment by cryolithic** [comment]
@IMS212 I'm an SE, though I haven't done much with graphics, or java...but I've got titles shipped on 4 generations of consoles. Anything I can do to help?

**Comment by IMS212** [comment]
Fixed in latest beta.
