### ISSUE TITLE
Load multiple shaders at simultaneously.

### ISSUE THREAD

**Issue by Cyclopropinon** [IrisShaders/Iris#2168]
**Is your feature request related to a problem? Please describe.**
I always wanted to have special effects on my screen for videos. 
like for example: [Rethinking Voxels](https://modrinth.com/shader/rethinking-voxels) kombined with [Sinus Shader](https://modrinth.com/shader/sinus-shader).

**Describe the solution you'd like**
Being able to load two or multiple shaders at once.

**Describe alternatives you've considered**
Get the wobbly (and other effects) using a fabric mod. Didn't find anything tho.

**Additional context**
I'm trying to use these shaders with replay mod.

**Comment by IMS212** [comment]
This is not how shaders work. Shaders are programs that run on the GPU, and no GPU can handle two shaders at once.
