### ISSUE TITLE
Adding mod support for Distant Horizons

### ISSUE THREAD

**Issue by DerClown03** [IrisShaders/Iris#2169]
Iris currently doesnt support the [Distant Horizons](https://gitlab.com/jeseibel/distant-horizons) mod, I'd love to see those mods to be compatible.
Currently when you try to enable Shaders with Distant Horizons enabled the DH Chunks just wont render.

**Comment by tajnymag** [comment]
Already tracked by https://github.com/IrisShaders/Iris/issues/1289
