### ISSUE TITLE
entityId doesn't get patched if the fragment shader isn't using a compatibility version

### ISSUE THREAD

**Issue by BalintCsala** [IrisShaders/Iris#2174]
### What happened?

If you use a core glsl version with iris, the entityId uniform doesn't get replaced by the proper reference.

### Minecraft Version

all

### Iris Version

all

### Operating System

Windows 11

### What is your GPU?

RTX 4070

**Comment by IMS212** [comment]
Fixed in 1.6.11 (soontm)
