### ISSUE TITLE
the Color Space setting breaks the fire overlay

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#2175]
### What happened?

the Color Space setting breaks the fire overlay

### Screenshots

sRGB:
![2023-11-24_21 47 04](https://github.com/IrisShaders/Iris/assets/68275908/54837e92-6bed-4cee-83a0-1477e45851e1)
other: 
![2023-11-24_21 47 07](https://github.com/IrisShaders/Iris/assets/68275908/a54304f9-69a6-4f34-81f0-9def351c358c)
![2023-11-24_21 47 08](https://github.com/IrisShaders/Iris/assets/68275908/c876e5a7-b7da-470e-98ba-5ce240ec02ab)
![2023-11-24_21 47 10](https://github.com/IrisShaders/Iris/assets/68275908/36d076ac-399d-4d58-a820-ed74aa0374b6)
![2023-11-24_21 47 11](https://github.com/IrisShaders/Iris/assets/68275908/751c3c09-1ade-4662-ba9d-475391944c10)

### Minecraft Version

Minecraft 1.20.2

### Iris Version

Iris 1.6.10

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

**Comment by IMS212** [comment]
Fixed in 1.6.11.
