### ISSUE TITLE
Can't use PBR resourcepacks on HUD Graphics

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [IrisShaders/Iris#2176]
### What happened?

When I use PBR resourcepacks and enable the PBR option of shaders, the game doesn't stuck, but the video stucks on the "Shader Packs" screen.
Game GPU usage: 0%

### Screenshots

When the bug happens, I change the window size several times, and then...
<img width="641" alt="aaa" src="https://github.com/IrisShaders/Iris/assets/102716584/af4c669b-b690-4bdf-b0cb-053ae734bc74">

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/13463498/latest.log)

### Minecraft Version

Minecraft 1.20.2

### Iris Version

iris-mc1.20.2-1.6.10

### Operating System

Windows 10

### What is your GPU?

Intel HUD Graphics

**Comment by IMS212** [comment]
1.20.2 is no longer supported; please reopen if this occurs on 1.20.4 or 1.20.6.
