### ISSUE TITLE
Crash on Startup 1.6.11 on version 1.20.1 Quilt

### ISSUE THREAD

**Issue by NolanHewitt** [IrisShaders/Iris#2181]
### What happened?

Crashes on start up

### Log output

[crash-2023-12-06_05.40.33-client.txt](https://github.com/IrisShaders/Iris/files/13582138/crash-2023-12-06_05.40.33-client.txt)
[2023-12-05-6[1].log](https://github.com/IrisShaders/Iris/files/13582154/2023-12-05-6.1.log)

### Minecraft Version

1.20.1

### Iris Version

1.6.11

### Operating System

windows 11

### What is your GPU?

AMD 7900XTX

### Additional context

1.6.10 doesn't crash

**Comment by IMS212** [comment]
Caused by Iris Flywheel Compat mod
