### ISSUE TITLE
Iris installer not working with Linux flatpak

### ISSUE THREAD

**Issue by MaKraMc** [IrisShaders/Iris#2186]
### What happened?

Iris installer installs to wrong .minecraft directory.
When using the [flatpak version of Minecraft](https://flathub.org/de/apps/com.mojang.Minecraft) on Linux the .minecraft folder is in the following path due to flatpak sandboxing: \
`~/.var/app/com.mojang.Minecraft/.minecraft`
However Iris installer will always try to install to `~/.minecraft` no matter what directory is choosen in the install dialog.

### Log output

Launching installer...
Installing 1.20.4 with fabric 0.14.24 to launcher WIN32
Could not find launcher_profiles

### Minecraft Version

All

### Iris Version

All

### Operating System

Arch Linux / Ubuntu Linux

### What is your GPU?

AMD RX 5700xt

### Additional context

GUI Installer says installation completed but versions can not be found in launcher because of the wrong path.

I am using `openjdk 19.0.2 2023-01-17` on my Ubuntu machine and `openjdk 21 2023-09-19` on Arch Linux.

I also found a possible workaround that solves the problem:
Create a symlink to `~/.var/app/com.mojang.Minecraft/.minecraft` at `~/.minecraft`. After doing this it was installed in the right directory with no further issues and I was able to play just fine. :)

**Comment by MaKraMc** [comment]
Sorry, will create this bug report on the right repo.

**Comment by boyoung3100** [comment]
How did you sym link ? I am having same issue.

**Comment by MaKraMc** [comment]
@boyoung3100 
> How did you sym link ? I am having same issue.

`ln -s ~/.var/app/com.mojang.Minecraft/.minecraft ~/.minecraft`
