### ISSUE TITLE
Iris 1.6.10 does not support Distant Horizons

### ISSUE THREAD

**Issue by artyrabbit** [IrisShaders/Iris#2190]
### What happened?

I have seen a few posts talking about this and a few developers saying this has been fixed, but for some reason, it's not for me!
I use complementary reimagined with iris, and for some reason it's limiting how far distant horizons will load.

### Screenshots

![2023-12-12_23 44 11](https://github.com/IrisShaders/Iris/assets/132223193/c618f2c3-7a55-487f-9981-a8ad7bb5736f)
![2023-12-12_23 44 06](https://github.com/IrisShaders/Iris/assets/132223193/9c9b5cf6-fe89-44db-9e79-36d4fb3a7efc)

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20.1-1.6.10

### Operating System

windows 10

### What is your GPU?

AMD radeon RX 5700 xt

**Comment by Aces-and-Jacks** [comment]
Pretty sure Iris doesn't have full support for DH

**Comment by artyrabbit** [comment]
> Pretty sure Iris doesn't have full support for DH
is there a different shader loader I could use then? :(

**Comment by Aces-and-Jacks** [comment]
> > Pretty sure Iris doesn't have full support for DH
> 
> is there a different shader loader I could use then? :(
> 
> 

Other than optifine probably not

**Comment by daddypalpatine** [comment]
in the iris discord there is an experimental dh build and a custom version of complementary shaders to work with it

**Comment by TheNukeLore** [comment]
The discord build is no longer needed, release iris has the compatibility now

**Comment by mbentity** [comment]
You are using the wrong Iris version, update Iris to 1.6.11 and DH should be working properly

**Comment by Physchh** [comment]
> You are using the wrong Iris version, update Iris to 1.6.11 and DH should be working properly

literally doesnt
