### ISSUE TITLE
Possibly add tests

### ISSUE THREAD

**Issue by ColdIce1605** [IrisShaders/Iris#22]
We've already have had multiple bugs pop up. Maybe its a good idea to have tests.

**Comment by ColdIce1605** [comment]
kek

**Comment by IMS212** [comment]
kek

**Comment by NatoBoram** [comment]
Could the tests be ran on a specific shaderspack?

**Comment by ColdIce1605** [comment]
yes that should be possible tho of limited use

**Comment by ColdIce1605** [comment]
oops I should close this
