### ISSUE TITLE
metal blocks render black with metallic reflections enabled in sildur's vibrant lite

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#220]
![Screenshot (200)](https://user-images.githubusercontent.com/75493688/112980372-16c49c00-915a-11eb-92d3-ca9fbb9ab165.png)

**Comment by edwloef** [comment]
Also affects polished blocks with polished reflections enabled

**Comment by coderbot16** [comment]
Does this happen on Iris trunk without any other mods installed? If you've used starline to edit the config options, you'll need to edit things in shaders.settings manually instead in order to test on trunk.

**Comment by edwloef** [comment]
Oh sorry, this is a starline only issue.
