### ISSUE TITLE
Crashing on launch when switched to a newer ver. (1.6.10 -> 1.6.11), potential incompatibility issue with NotEnoughCrashes

### ISSUE THREAD

**Issue by acerola0rion598** [IrisShaders/Iris#2203]
### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.11.jar

### Sodium Version

sodium-fabric-mc1.20.1-0.5.3.jar

### Operating System

Windows 11 23H2 22631.2861

### What is your GPU?

Nvidia GeForce RTX 4060 (mobile)

### Java Version

Java JRE 17 (Eclipse Adoptium)

### Reproduction Steps

Game crashes on startup with notenoughcrashes-4.4.6+1.20.1-fabric.jar included. This is true for Iris ver. 1.6.11, but not 1.6.10.
Also I dont'get neither a crash report, nor a pop-up window from nec. But if I try to launch the whole modpack, I at least get this report from nec (attaching it and logs from both launches).
[logs-from-clean-launch.log](https://github.com/IrisShaders/Iris/files/13763317/logs-from-clean-launch.log)
[logs-from-full-modpack-launch.log](https://github.com/IrisShaders/Iris/files/13763318/logs-from-full-modpack-launch.log)
[nec-crash-report.txt](https://github.com/IrisShaders/Iris/files/13763319/nec-crash-report.txt)

**Comment by coderbot16** [comment]
Not our bug - Not Enough Crashes is tampering with Iris internals (SilentNEC.java from NEC mixing in to Iris.java in Iris) and we changed our code. Please follow up with NEC instead.

**Comment by natanfudge** [comment]
This has been fixed in NEC 4.4.7-1.20.2.
