### ISSUE TITLE
Ask for your permission

### ISSUE THREAD

**Issue by DSLZL** [IrisShaders/Iris#2205]
Hello, IrisShaders creators.
I'm DSLZL, and I'm sorry for opening a new issue on your project that is completely unrelated, but I can only contact you on GitHub in China.
I'd like to ask if I can put this IrisShaders you made into my modpack and publish it in modrinth, because I don't know much about licenses, so I'm here to ask for your opinions, and if my actions violate your rights, I'm very sorry and delete the modpack and apologize as soon as I see your reply.
The modpack link in modrinth is: [only-optimized](https://modrinth.com/modpack/only-optimized), if you don't see it, it's because it's still under review.
Sorry to interrupt you, but please forgive me for any inconvenience I may have if I do not obtain your permission.
(This passage is supported by Microsoft Translator, if you agree with my behavior, please do not delete this issue, so that I can provide evidence if I need it)
Thank you so much.

**Comment by IMS212** [comment]
No, that’s completely fine, don’t worry. Iris’s license just requires that if you modify it, you need to post the source code as well.

**Comment by DSLZL** [comment]
> No, that’s completely fine, don’t worry. Iris’s license just requires that if you modify it, you need to post the source code as well.

Thank you for your reply
