### ISSUE TITLE
Incompatibility on quilt

### ISSUE THREAD

**Issue by Feliks-WR** [IrisShaders/Iris#2207]
### Minecraft Version

1.20.1

### Iris Version

1.20.1-1.6.11

### Sodium Version

mc1.20.1-0.5.3

### Operating System

Windows 11

### What is your GPU?

Intel UHD Graphics 630

### Java Version

17?

### Reproduction Steps

Run mods [here](https://modrinth.com/modpack/better-experiences).
Start Minecraft
There will be a quilt loader "Complex solver issue"

### Crash Report file and latest.log

```shell
https://mclo.gs/kNy9ryu
```

**Comment by EntityinArray** [comment]
log ends abruptly at the point where mods get listed
could you check if you copied everything from the logs?
