### ISSUE TITLE
Quilt 1.20.1 Startup Crash

### ISSUE THREAD

**Issue by RoY7x** [IrisShaders/Iris#2213]
### Minecraft Version

1.20.1 - Quilt 0.23.0

### Iris Version

1.6.11

### Sodium Version

0.5.3

### Operating System

Windows 11

### What is your GPU?

Nvidia 3070 laptop edition

### Java Version

Java 17 (I believe)

### Reproduction Steps

Been updating my personal modpack, and went from the prior stable version to now this one, and it no longer boots, crashing every time. Have done a binary check and it seems that this is the only change I've done that's now caused crashing.

### Crash Report file and latest.log

```shell
Crash report is too long apparently? Here is a pastebin: https://pastebin.com/WLPDJFru
```

### Additional context

Unsure if this is also anything to do with this guy's [issue](https://github.com/IrisShaders/Iris/issues/2207#issue-2061437954) however after recently updating to the latest Iris shader version I can't get Minecraft to boot now.

**Comment by Lolothepro** [comment]
remove notenoughcrashes, not related to Quilt
