### ISSUE TITLE
shader doesn't work on AMD windows drivers

### ISSUE THREAD

**Issue by hyxl520** [IrisShaders/Iris#2220]
[minecraft-exported-logs-2024-01-23T17-00-54.log](https://github.com/IrisShaders/Iris/files/14021219/minecraft-exported-logs-2024-01-23T17-00-54.log)
I tried to load the shader but when it was done loading, the vanilla graphics were still there, no shader.
I have an AMD RX 580

**Comment by Skote2** [comment]
It may not just be Windows driver for AMD
I haven't been able to get it to work on Linux either. I'm using a Fury X on Arch.

I'd be happy to provide logs as well if the devs want them.

**Comment by itsTyrion** [comment]
it's _probably_ fixed in a later version of Iris, but you're on 1.16.5 with an Iris version from December 2022
