### ISSUE TITLE
Unable to load shaders.

### ISSUE THREAD

**Issue by F-alling** [IrisShaders/Iris#2224]
### What happened?

Im using Iris 1.6.14 and Sodium 0.5.5, and whenever I try to load a shader I get. `net.minecraft.class_2973: Invalid shaders/core/basic.json: The validated expression is false`

### Log output

net.minecraft.class_2973: Invalid shaders/core/basic.json: The validated expression is false

### Minecraft Version

1.20.4

### Iris Version

Iris 1.16.14

### Operating System

Windows 10 

### What is your GPU?

RTX 3060 ti

**Comment by Luracasmus** [comment]
Could you please send the whole log file? Also try updating your Iris and other mods to the latest versions

**Comment by F-alling** [comment]
Bro this is from january 💀 your a bit late

**Comment by Luracasmus** [comment]
Just noticed no-one had responded so thought I'd check the issue if it was still active

Good that it seems to have been solved 👍

**Comment by f-urinaa** [comment]
what was the solution?

**Comment by F-alling** [comment]
I don't remember anymore
