### ISSUE TITLE
Shaders can't be used

### ISSUE THREAD

**Issue by snlaf** [IrisShaders/Iris#2229]
### What happened?

When i'm trying to activate any of shaders, nothing works. 

### Screenshots

![eapmvyD](https://github.com/IrisShaders/Iris/assets/81318197/5878d5d1-006e-4629-ac1e-a5b3dc22bcf9)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/14104969/latest.log)

### Minecraft Version

1.20.1

### Iris Version

1.6.11

### Operating System

Windows 11

### What is your GPU?

GTX 1080

### Additional context

It happened after I updated from win10 to win11 and restored mods and shaders folders. I tried to reinstall Iris, but with no result

**Comment by ShrikerChestTree** [comment]
> ### What happened?
> When i'm trying to activate any of shaders, nothing works.
> 
> ### Screenshots
> ![eapmvyD](https://private-user-images.githubusercontent.com/81318197/300977148-5878d5d1-006e-4629-ac1e-a5b3dc22bcf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTU4MzcsIm5iZiI6MTcwNzg1NTUzNywicGF0aCI6Ii84MTMxODE5Ny8zMDA5NzcxNDgtNTg3OGQ1ZDEtMDA2ZS00NjI5LWFjMWUtYTViM2RjMjJiY2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDIwMTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYThmNWYzNTk2ZDY5NWRlMGQxMTY4YjljZjU5NWY2MzQ1YzlmNmE3MzRkMDg3ZGYzNWM2MDA0ZDMzNTZmZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Je8tVOAlQeTN3HDW40teFNc6Z_iCY4chMIhGXLxyGcY)
> 
> ### Log output
> [latest.log](https://github.com/IrisShaders/Iris/files/14104969/latest.log)
> 
> ### Minecraft Version
> 1.20.1
> 
> ### Iris Version
> 1.6.11
> 
> ### Operating System
> Windows 11
> 
> ### What is your GPU?
> GTX 1080
> 
> ### Additional context
> It happened after I updated from win10 to win11 and restored mods and shaders folders. I tried to reinstall Iris, but with no result

Perhaps Iris does not support an older version of Complementary...

**Comment by snlaf** [comment]
> Perhaps Iris does not support an older version of Complementary...

Yeah, I thought about that and tested the same mods AND shaders on different devices, and it worked absolutely fine. Also, other shaders on the screenshot aren't working

**Comment by snlaf** [comment]
Fixed by deleting some other soft on pc
