### ISSUE TITLE
Allow shaderpacks to detect when the camera is submerged in powdered snow

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#223]

**Comment by ColdIce1605** [comment]
🚀

**Comment by coderbot16** [comment]
When was this fixed?

**Comment by AlsoNiko** [comment]
This was fixed here https://github.com/IrisShaders/Iris/commit/0c61a5653417672717405c16f6e8d021b5a349cb

**Comment by coderbot16** [comment]
Okay, thanks for linking the commit. It's best to link to a commit when closing bugs as fixed.

**Comment by IMS212** [comment]
Oh, sorry. Couldn't find the commit where it was fixed at the time.
