### ISSUE TITLE
Allow users to use the default color space on their display without selecting one

### ISSUE THREAD

**Issue by mrjasonn** [IrisShaders/Iris#2234]
**Is your feature request related to a problem? Please describe.**
Very annoying that you have to know in order to get the best color quality with shaders

**Describe the solution you'd like**
To make it so that there is an option in that setting to use the default color space on your display and not transform your display into a different one

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by IMS212** [comment]
The reason that option exists at all is because Iris does not know the default.
