### ISSUE TITLE
Iris 1.6.15 is not on Modrinth

### ISSUE THREAD

**Issue by mrjasonn** [IrisShaders/Iris#2241]
See the picture below:
<img width="1199" alt="Screenshot 2024-02-07 at 2 56 17 PM" src="https://github.com/IrisShaders/Iris/assets/120269221/724c586b-a17c-444b-b33f-08f7264621cb">
But it is on Github Releases (jars missing):
<img width="1199" alt="Screenshot 2024-02-07 at 2 57 43 PM" src="https://github.com/IrisShaders/Iris/assets/120269221/1b3bb03e-b39f-4cfe-ba15-69385213c803">

**Comment by Pouri-Shoon** [comment]
Same here

**Comment by VentureStudios** [comment]
Idem

**Comment by Nyaacinth** [comment]
Seems like they reverted the commit and also the release.

<img width="1105" alt="image" src="https://github.com/IrisShaders/Iris/assets/80994270/3e487ac2-2615-4d0e-903f-c29f080e9719">

**Comment by IMS212** [comment]
Iris has a major performance problem with Sodium 0.5.8, and the release was reverted. A new release will be made alongside Sodium 0.5.9, which fixes this.

**Comment by LightslicerGP** [comment]
> Iris has a major performance problem with Sodium 0.5.8, and the release was reverted. A new release will be made alongside Sodium 0.5.9, which fixes this.

is there any release date for 0.5.9?
