### ISSUE TITLE
Update to the newest Sodium Versions

### ISSUE THREAD

**Issue by szunakabeats** [IrisShaders/Iris#2242]
**Is your feature request related to a problem? Please describe.**
Iris is only compatible with certain sodium versions.

**Describe the solution you'd like**
A update to newer versions. Maybe you can make iris generally compatible with sodium. that it only needs to detect sodium and not a specific version of sodium.

**Describe alternatives you've considered**
not playing with iris at the moment.

**Additional context**

**Comment by IMS212** [comment]
see #2241
