### ISSUE TITLE
Incompatible mods even though its compatible

### ISSUE THREAD

**Issue by alertPudding9** [IrisShaders/Iris#2243]
### What happened?

I just trying to install Iris shader but it said that it isnt compatible, i tried all sodium version and still the same error...

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/156921297/b000c149-689d-42d6-84b6-64a824894d6d)

### Minecraft Version

1.20.1

### Iris Version

iris 0.5.8+mc1.20.1

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce GT 645

**Comment by RealmKebab** [comment]
iris 1.6.11 doesn't support 0.5.8

**Comment by GameJunkie333** [comment]
I had the same issue. I tried the version IRIS was asking for and still didn't work. So then tried other versions of Sodium but still no joy. I did a lot of troubleshooting with uninstalling and re-installing both mods.

What worked for me was turning off two programs running in the background. They were **MSI Afterburner** running with **RivaTuner Statistics Server**. The RivaTuner one was really the issue. For convenience I just turned both off.
So I suggest you look to see if you have these running and turn them off and try the IRIS and Sodium installs again.

Hope this was helpful.

**Comment by alertPudding9** [comment]
> I had the same issue. I tried the Sodium version IRIS was asking for and still didn't work. So then tried other versions of Sodium but still no joy. I did a lot of troubleshooting with uninstalling and re-installing both mods.
> 
> What worked for me was turning off two programs running in the background. They were _**MSI Afterburner**_ running with _**RivaTuner Statistics Server**_. The RivaTuner one was really the issue. For convenience I just turned both off. So I suggest you look to see if you have these running and turn them off and try the IRIS and Sodium installs again.
> 
> Hope this was helpful.

Its noting to do with the msi afterburner, its just the version is wrong

**Comment by alertPudding9** [comment]
Btw its fixed now
