### ISSUE TITLE
Blindness uniform not set when it's infinite, or with the Darkness effect

### ISSUE THREAD

**Issue by Sarund9** [IrisShaders/Iris#2250]
### What happened?

The blindness uniform value in shaders is not set if the blindness effect duration is set to Infinite via a command:
```mcfunction
effect give Sarund9 minecraft:blindness infinite
```
It also doesn't work for the darkness effect (This may be unrelated I don't know how that effect works)

### Minecraft Version

Minecraft 1.20.1

### Iris Version

iris-mc1.20.1-1.6.11

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce 1080

### Additional context

I was making my shaders and used the `float blindness` uniform in `composite`, then gave myself blindness with the command from before. I didn't see any effects, I tested other shaderpacks and they had the same problem.
Then I used the command with just 10s and it worked perfectly, in fact, it works perfectly with any duration as long as it's not Infinite

**Comment by tylermasci16** [comment]
I can confirm

**Comment by IMS212** [comment]
Fixed in 1.7.0.
