### ISSUE TITLE
NeoForge port

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#2254]
soon?

**Comment by ed522** [comment]
Look into Oculus, which is an *unofficial* port to (Neo)Forge. You could use it with Embeddium/Rubidium instead of Sodium for performance. They're both available on Modrinth/CurseForge.

**Comment by whystars** [comment]
Is it almost finished?
I need it in Minecraft 1.21!(NeoForge Port)

**Comment by xbxbxb123** [comment]
I heard the port is functioning and available here somehow, but not published elsewhere yet. I would also like to know when it will be fully ready, I'm very excited for it! Though I also understand if it is not possible to give an ETA or is not as close to done as it sounded like it was

**Comment by pekochan069** [comment]
> Is it almost finished?
> I need it in Minecraft 1.21!(NeoForge Port)

sodium is not yet ready for neoforge. until then you should just stick with existing forge port like embedium.

**Comment by xbxbxb123** [comment]
I see, though unfortunately that means no shaders

**Comment by whystars** [comment]
So that means there aren't any shaders that support 1.21 NeoForge...

**Comment by whystars** [comment]
## There are alpha versions of Iris and Sodium available for all the mod loaders on Discord!
### Including Fabric, Forge, and NeoForge!
![image](https://github.com/IrisShaders/Iris/assets/111120870/bb961277-4f76-437a-b607-28fe8326efc8)
![image](https://github.com/IrisShaders/Iris/assets/111120870/8f09abea-9268-470d-a999-9256dc3443cc)
