### ISSUE TITLE
Disable Occlusion Culling in shaders.properties

### ISSUE THREAD

**Issue by jbritain** [IrisShaders/Iris#2260]
Sometimes, when moving large portions of terrain in the vertex shader, terrain which is now visible to the player is culled because the occlusion culling is calculated before the vertex offsets.

It would be nice if it was possible to disable occlusion culling to prevent this.

I have disabled block face culling and fog occlusion, and in the shader code disabled frustum culling, leaving only occlusion culling to be a possible explanation for this.

This obviously isn't something you'd use in normal gameplay and would be a big performance hit but in the same vein as the ability to disable frustum culling, it would be nice to have.

**Comment by IMS212** [comment]
Added key occlusion.culling.
