### ISSUE TITLE
iris Shaders breaks the mechanics of ESP mapping through the SHADERS function in meteor client

### ISSUE THREAD

**Issue by LimonTH** [IrisShaders/Iris#2263]
### What happened?

The problem exists in two cases, 1) When trying to look at an entity at close range, its model is enlarged on the screen as a 2D image, 2) When you turn on this function in cheats with iris shaders enabled, it does not work (it does not show the selection of the mob, screenshot 1./2.).

### Screenshots

1. ![2024-03-01_19 19 22](https://github.com/IrisShaders/Iris/assets/158569619/74c0bcbf-cf5a-4819-80dd-59c430f817f4)  without shaders.
2. ![2024-03-01_19 18 51](https://github.com/IrisShaders/Iris/assets/158569619/afd2878f-489b-4dfb-8fbe-f05e02349202) with shaders.

### Log output

none

### Minecraft Version

Minecraft Fabric 1.20.4

### Iris Version

iris-mc-1.20.4-1.6.17

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2060 Super

### Additional context

Please correct this misunderstanding.

**Comment by Lolothepro** [comment]
Meteor Client is not a cracked client?
