### ISSUE TITLE
Error upon loading shader

### ISSUE THREAD

**Issue by LatiBlueLatios** [IrisShaders/Iris#2271]
### What happened?

When attempting to load the shader pack "Shrimple" on an Apple Silicon MacBook Pro, this error occurs:

> Shader storage buffers/immutable buffer storage is not supported on this graphics card, however the shaderpack requested them? This shouldn't be possible.

### Screenshots

<img width="621" alt="Screenshot 2024-03-10 at 7 17 07 PM" src="https://github.com/IrisShaders/Iris/assets/65719723/c77cbfb7-f407-4838-b2f1-21440b9791e0">

### Log output

https://mclo.gs/qPOJFU8

### Minecraft Version

1.20.4

### Iris Version

1.20.4-1.6.17

### Operating System

MacOS

### What is your GPU?

M1 chip with an integrated 8-core GPU

**Comment by IMS212** [comment]
> is not supported on this graphics card

This isn't a bug; complain to Apple. They've put an arbitary limit.
