### ISSUE TITLE
Custom Entity Textures

### ISSUE THREAD

**Issue by ly-nxs** [IrisShaders/Iris#2277]
When I want to fully utilize datapacks and rescoure packs like incendium and stellarity it causes errors and the mobs don't work

The custom textures work with optifine, but I use lunar

Optifine but forge is bad for fps

**Comment by LizIsTired** [comment]
CEM will never be implemented in Iris, and afaik nor Oculus.

On Fabric there is [CEM](https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem) which handles it

**Comment by Lolothepro** [comment]
use [EMF](https://modrinth.com/mod/entity-model-features) and [ETF](https://modrinth.com/mod/entitytexturefeatures), CEM is broken and old
this feature will never be added in Iris.
