### ISSUE TITLE
 Incompatible with voxy in ver1.7.0

### ISSUE THREAD

**Issue by iekiekkeikei** [IrisShaders/Iris#2278]
### Minecraft Version

1.20.4

### Iris Version

1.7.0snapshot

### Sodium Version

0.5.8

### Operating System

windows11

### What is your GPU?

GTX1650

### Java Version

Java17

### Reproduction Steps

1. add voxy mod
2. load or create world
3. Game Crashes

### Crash Report file and latest.log

```shell
Crash Report https://mclo.gs/6fVHns2
latest.log https://mclo.gs/3oREGLk
```

### Additional context

[Modlist]
Cloth Config API
Fabric API
Iris
Sodium
voxy

**Comment by Lolothepro** [comment]
It's normal

**Comment by Lolothepro** [comment]
People shouldn't report incompatibilities between mods and Iris 1.7.0

**Comment by iekiekkeikei** [comment]
OK.
I I'll be careful next time

**Comment by iekiekkeikei** [comment]
> ### Minecraft Version
> 1.20.4
> 
> ### Iris Version
> 1.7.0snapshot
> 
> ### Sodium Version
> 0.5.8
> 
> ### Operating System
> windows11
> 
> ### What is your GPU?
> GTX1650
> 
> ### Java Version
> Java17
> 
> ### Reproduction Steps
> 1. add voxy mod
> 2. load or create world
> 3. Game Crashes
> 
> ### Crash Report file and latest.log
> ```shell
> Crash Report https://mclo.gs/6fVHns2
> latest.log https://mclo.gs/3oREGLk
> ```
> 
> ### Additional context
> [Modlist] Cloth Config API Fabric API Iris Sodium voxy

Tried with the release version with similar results.
https://mclo.gs/nLfwC3P

**Comment by Lolothepro** [comment]
Voxy bug...

**Comment by DefomCode** [comment]
This is not a voxy error. The console shows that the problem is primarily due to incompatibility with iris. Because with me, not my beloved Distant horizons, there is absolutely the same problem

**Comment by Ayush-Bara** [comment]
I am facing the same issue. did you find a fix ?

**Comment by Ascend-910** [comment]
It is already said above that it won't be fixed. Please stop
