### ISSUE TITLE
Error message "pack doesn't have DH sup" is unreadable

### ISSUE THREAD

**Issue by NatoBoram** [IrisShaders/Iris#2281]
### What happened?

**What happened**

The error message "pack doesn't have DH sup" is unreadable.

**What should happen**

The error message should be in the chat so we can read it

**Steps**

1. Install a shaderspack that doesn't support Distant Horizons
2. Open a game

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/10495562/05d25650-a7f4-4b7d-9c64-e9f143d21dc4)

### Log output

> **pack doesn't have DH sup**
> orizons (DH) chunks won't shot up. This isn't a bug, get another

### Minecraft Version

1.20.1

### Iris Version

iris-1.7.0-snapshot+mc1.20.1-7edecd1.jar

### Operating System

Pop!_OS 22.04 LTS x86_64

### What is your GPU?

AMD ATI Radeon RX 6700 XT

### Additional context

* According to @cola98765 [here](https://gitlab.com/jeseibel/distant-horizons/-/issues/655#note_1829007330), the error message is caused by Iris instead of Distant Horizons.
* It seems like this is a warning instead of an error. The text should probably be yellow to indicate that it's a normal and supported behaviour and not a bug.
* Sometimes, one may want to switch between DH packs and non-DH packs. One reason for this is that there's no good DH shaderspack yet, so switching between Bliss+DH/Shrimple+DH and Complementary is kind of a necessity if you want to see what you're doing but still have shaders. Having the message take the entire screen for 10 seconds in a bit inconvenient.

**Comment by IMS212** [comment]
This message is exclusive to the beta, and will not exist in the final release.
