### ISSUE TITLE
Invisible creeper on latest version.

### ISSUE THREAD

**Issue by Sovcat0608** [IrisShaders/Iris#2284]
### What happened?

After moving from **iris-mc1.20.4-1.6.17** to **1.7.0-snapshot+mc1.20.4-482321c**, creepers are no longer visible whilst using a resource pack, specifically with "Patrix". Downgrading back to 1.6.17 solves the issue. This seems to be in relation to Entity Model Features, but is only affected by the **Iris version**.

### Minecraft Version

1.20.4

### Iris Version

iris-1.7.0-snapshot+mc1.20.4-482321c

### Operating System

Windows 11

### What is your GPU?

RTX 4080

**Comment by Lolothepro** [comment]
EMF probably uses Iris modifications. And it's normal that Iris 1.7.0 is incompatible with mods.
