### ISSUE TITLE
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 19 samplers

### ISSUE THREAD

**Issue by zestysoft** [IrisShaders/Iris#2285]
### What happened?

The shaderpack failed to load! Please report the error to the shader developer. Copy Info

### Screenshots

<img width="849" alt="Screenshot 2024-03-31 at 6 45 44 PM" src="https://github.com/IrisShaders/Iris/assets/742554/682447ee-5c9d-4d95-9109-ccb91aa711e6">

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/14818445/latest.log)

### Minecraft Version

1.20.4

### Iris Version

iris-1.7.0-snapshot+mc1.20.4-482321c.jar

### Operating System

MacOS Sonoma 14.4.1

### What is your GPU?

M3 Max

### Additional context

I used the Iris-Installer-3.2.0.jar downloaded from https://irisshaders.dev

Mod files in mods:
```
DistantHorizons-fabric-2.0.2-a-dev-1.20.4.jar fabric-api-0.96.11+1.20.4.jar                 indium-1.0.30+mc1.20.4.jar                    iris-1.7.0-snapshot+mc1.20.4-482321c.jar      sodium-fabric-0.5.8+mc1.20.4.jar
```

shaderpacks:
```
Bliss-Shader-DH.zip
```

I know here be dragons, so just fyi.

**Comment by zestysoft** [comment]
I also tried wiping everything from the mods folder and using 1.20.2 non-beta stuff and also had trouble:

[latest.log](https://github.com/IrisShaders/Iris/files/14819002/latest.log)

however the java exception is different:

`java.lang.IllegalStateException: No more available texture units while activating sampler shadowtex1`

**Comment by IMS212** [comment]
Many shaders are not supported on macOS; this isn't a bug.

**Comment by zestysoft** [comment]
Any idea what this is about then? Seems weird to complain about a platform that has no support in the first place?
https://x.com/IrisShaders/status/1768825389747781884?s=20
![Uploading Screenshot 2024-04-01 at 6.22.02 PM.png…]()

**Comment by IMS212** [comment]
Not supported by *many shaders*. Iris supports it; this limit is dependent on the shader.

**Comment by zestysoft** [comment]
If that's the case, why would you close this issue before discovering which shader I've got installed?

Here, it's the shader that the iris installer installed:  Bliss-Shader-DH.zip

**Comment by Lolothepro** [comment]
> If that's the case, why would you close this issue before discovering which shader I've got installed?
> 
> Here, it's the shader that the iris installer installed: Bliss-Shader-DH.zip

The name of the shader you're using is in the log file...

**Comment by lashan** [comment]
I more or less am having the same issue, on Mac OS 14.4, Minecraft 1.20.4, etc. Here's the error that it's throwing for me when I click the "Copy Info" link in the chat/console that shows up.

```
composite2: composite2: WARNING: Could not find vertex shader attribute 'at_tangent' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_midTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'UV0' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'iris_Entity' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'at_midBlock' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_Entity' to match BindAttributeLocation request.
WARNING: Output of vertex shader 'iris_FogFragCoord' not read by fragment shader
WARNING: Output of vertex shader 'zMults' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 19 samplers
```

**Comment by zestysoft** [comment]
@IMS212 implied there was at least one shader that did work?

**Comment by IMS212** [comment]
Yes, BSL.
