### ISSUE TITLE
Languages not being changed via resourcepack

### ISSUE THREAD

**Issue by seriousfreezing** [IrisShaders/Iris#2286]
### What happened?

I'm trying to change the en_us language via resourcepack and it's not working

### Minecraft Version

Minecraft 1.20.4

### Iris Version

Iris-mc1.20.4-1.6.17

### Operating System

Windows 11

### What is your GPU?

RTX 3050 Laptop

**Comment by IMS212** [comment]
Can you provide a test?

**Comment by seriousfreezing** [comment]
Of course, but if I'm not mistaken there's already been a discussion within your own discord server and there's been no solution

**Comment by seriousfreezing** [comment]
https://discord.com/channels/774352792659820594/774352792659820598/1224502871597252628

**Comment by seriousfreezing** [comment]
Solution: Modify the lines in Iris' own lang document, but transfer the changes to Minecraft's lang folder.
