### ISSUE TITLE
PTGI GFME/NostalgiaVX type path traced shaders have issues

### ISSUE THREAD

**Issue by Taiyou06** [IrisShaders/Iris#2293]
### What happened?

In PTGI GFME none of the light sources work and slabs/trapdoors are fully dark
In NostalgiaVX only the voxelization shapes are broken (i.e slab/trapdoor)

### Screenshots

PTGI GFME
![image](https://github.com/IrisShaders/Iris/assets/77050201/d9f92881-451f-4970-9ad8-4a03559c793f)
![image](https://github.com/IrisShaders/Iris/assets/77050201/62171b1d-6a4b-4fe2-a732-7bfdebdaff54)

### Minecraft Version

1.20.4

### Iris Version

iris-mc1.20.4-1.6.17.jar

### Operating System

Win 10

### What is your GPU?

RTX 2060

**Comment by Bedokee** [comment]
Happy to report that this has been resolved in Iris 1.7

**Comment by Taiyou06** [comment]
Yup, it is fixed
