### ISSUE TITLE
Armourer's Workshop rendering bug

### ISSUE THREAD

**Issue by Szedann** [IrisShaders/Iris#2299]
### What happened?

when shaders are enabled with iris 1.7.0, armourer's workshop, the custom models appear at the position and rotation of the camera

### Screenshots

shaders disabled:
![without shaders](https://github.com/IrisShaders/Iris/assets/65607498/b48e5eac-3a7c-4e8c-b76f-d57e7965ec4c)
shaders enabled:
![with shaders](https://github.com/IrisShaders/Iris/assets/65607498/b85bc4cc-992a-4c07-afdb-937b117ed1e7)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/15138993/latest.log)

### Minecraft Version

1.20.1

### Iris Version

iris-1.7.0+mc1.20.1

### Operating System

Windows 11

### What is your GPU?

MSI Geforce RTX 3070

**Comment by IMS212** [comment]
Armorer's Workshop is doing some insane patches to Iris shaders. We can't support it.
