### ISSUE TITLE
Might have found redundent code

### ISSUE THREAD

**Issue by mrjasonn** [IrisShaders/Iris#2300]
In the class `net.irisshaders.iris.compat.sodium.mixin.copyEntity.cull`, it is exactly the same as Sodium's `EntityRendererMixin` class except that the Iris one uses Mojmap for mappings. This has been found in Iris 1.7.0.

If these exist for a good reason, why is that?

**Comment by IMS212** [comment]
This was needed in the past; and may still be needed soon. so I kept it. If it's causing a problem, I can remove it.
