### ISSUE TITLE
Failed to get entry for 10303

### ISSUE THREAD

**Issue by PotatoSlayer56** [IrisShaders/Iris#2301]
### What happened?

When trying to load AstraLex shaders it throws the following error: `Failed to get entry for 10303`

### Minecraft Version

Fabric 1.20.4

### Iris Version

1.7.0+1.20.4

### Operating System

Windows 11

### What is your GPU?

RTX 4060

**Comment by armandopazzo** [comment]
have you found a solution? because the same thing happens to me

**Comment by gabrypala99** [comment]
No but if you install the updated version it still gives the error but you
can use astralex shader

Il giorno dom 12 mag 2024 alle ore 09:45 ArmandoPazzo_YT <
***@***.***> ha scritto:
