### ISSUE TITLE
Suggestion embedium neo forge compat

### ISSUE THREAD

**Issue by Thunderrock424242** [IrisShaders/Iris#2302]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] so I know embedium is just like sodium and I know iris is porting to neo forge in the future so it would be really nice for neo forge iris to be compatible with embedium cause embedium is amazing and has great addons. 

**Describe the solution you'd like**
To make iris and embedium compatible 
**Describe alternatives you've considered**

**Additional context**

**Comment by IMS212** [comment]
Iris and Sodium will be getting official NeoForge support; Embeddium will not be needed or compatible.

**Comment by NoaHimesaka1873** [comment]
> Iris and Sodium will be getting official NeoForge support; Embeddium will not be needed or compatible.

Though Sodium changed license to one with noncompete clause, which makes it not open source nor free. So it would be nice to be able to use Embeddium (which still uses LGPL) on Fabric/NeoForge (yes, there's Embeddium on Fabric now) instead.
