### ISSUE TITLE
After adding "Iris & Oculus Flywheel Compat", I can't enter the game.

### ISSUE THREAD

**Issue by lostmyself8** [IrisShaders/Iris#2304]
### What happened?

Installing Iris 1.6.11 on the 1.19.2 fabric and then "Iris&Oculus Flywheel Compat" will keep getting stuck in the game loading interface (and will not crash).,but lowering the Iris version to 1.6.10 or below can solve this problem.I don't know if this is a bug, but it didn't crash the game, so I can only send bug feedback.

### Screenshots

<img width="1280" alt="2024-04-30" src="https://github.com/IrisShaders/Iris/assets/133753655/a659ccb5-0cb9-4be2-b21b-ac0f8a99a589">
After starting the game, it will continue to loop and load on this interface.

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/15160444/latest.log)

### Minecraft Version

Minecraft 1.19.2

### Iris Version

iris-mc1.19.2-1.6.11.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3060 LapTop

**Comment by mrjasonn** [comment]
This issue should not be reported here, instead in their issue tracker.
