### ISSUE TITLE
Iris 1.7.0 (1.20.1) iris does not want to work with latest Distant Horizens for 1.20.1

### ISSUE THREAD

**Issue by ghost** [IrisShaders/Iris#2311]
### What happened?

Iris 1.7.0 (1.20.1) iris does not want to work with the latest Distant Horizons for 1.20.1 because it thinks it is 2.0.1 and later, not 2.0.1-a. 

All Iris version are made like this 2.0.1-a
While Iris thinks that DH versions are 2.0.1 **without the -a**

_I tried changing the version for fabric on DH, however gradle 7.6 didn't want to build midway through and I don't want to bother with fixing that._

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/79378716/c4800b1f-6e2e-4d3f-b317-2f1bf187caed)

### Log output

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Distant Horizons' (distanthorizons) 2.0.1-a (C:\Users\PC\AppData\Roaming\com.modrinth.theseus\profiles\removed\mods\DistantHorizons-2.0.1-a-1.20.1.jar).
	 - Remove mod 'Distant Horizons' (distanthorizons) 2.0.1-a (C:\Users\PC\AppData\Roaming\com.modrinth.theseus\profiles\removed\mods\DistantHorizons-2.0.1-a-1.20.1.jar).
More details:
	 - Mod 'Iris' (iris) 1.7.0+mc1.20.1 is incompatible with version 2.0.1 or earlier of mod 'Distant Horizons' (distanthorizons), but a matching version is present: 2.0.1-a!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Minecraft Version

1.20.1

### Iris Version

DistantHorizons-2.0.1-a-1.20.1.jar

### Operating System

Windows 11

### What is your GPU?

Asus Nvidia 4070 ti OC

### Additional context

Just fix the required version of Distant Horizens.

**Comment by ghost** [comment]
Never mind, just compiled the Distant Horizen gitlab, just follow instructions. You will get a 1.20.1 2.0.4-a.dev version that works with IRIS, just make sure do not update when it prompts you.
https://gitlab.com/jeseibel/distant-horizons#compiling

**Comment by SamuelUlep** [comment]
Can you share the compiled version of it?

**Comment by ghost** [comment]
[DistantHorizons-2.0.4-a-dev-1.20.1.zip](https://github.com/IrisShaders/Iris/files/15357962/DistantHorizons-2.0.4-a-dev-1.20.1.zip)
^^^^^^
idk if this is the latest version or not, this was the version I complied 2 weeks ago.
make sure u have the distant horizons compatible version of Iris

> Can you share the compiled version of it?

**Comment by FullMetalMaster** [comment]
> darealblack

yo could you compile a 1.21 version what works with iris?

**Comment by SamuelUlep** [comment]
Heya so for the people who don't know they have a [discord](discord.com/invite/xAB8G4cENx) under #links-n-downloads has the latest versions of distant horizons that work with iris. @FullMetalMaster

**Comment by FullMetalMaster** [comment]
invite is down but ty

**Comment by SamuelUlep** [comment]
Oh if the link doesn't works they have their discord link in curseforge and modrinth
