### ISSUE TITLE
Report Bug while loading Voyager shaders

### ISSUE THREAD

**Issue by DiscFragment** [IrisShaders/Iris#2313]
### What happened?

**I tried to load _Voyager Shaders 2.0.7 version_ and i saw the screenshot**

### Screenshots

![لقطة شاشة 2024-05-05 161526](https://github.com/IrisShaders/Iris/assets/120102029/204ac6de-b989-4e09-8183-4143bd733515)

### Log output

```
Failed to get entry for 2001
``` 

### Minecraft Version

1.20.1

### Iris Version

iris-1.7.0+mc1.20.1.jar

### Operating System

Windows 10

**Comment by IMS212** [comment]
Update the shader.
