### ISSUE TITLE
JITPACK: Build failed, 404 for install-jdk.sh

### ISSUE THREAD

**Issue by ByThePowerOfScience** [IrisShaders/Iris#2318]
### What happened?

https://jitpack.io/com/github/IrisShaders/Iris/1.18.x~v1.2.0/build.log

In [jitpack.yml](https://github.com/IrisShaders/Iris/blob/c3c199ef7490f30bde69e7b7eafd359fd08dd940/jitpack.yml), `https://github.com/sormuras/bach/raw/master/install-jdk.sh` is an invalid link, causing the Jitpack build to default back to Java 8 and fail to compile.

### Minecraft Version

N/A

### Iris Version

N/A

### Operating System

N/A

### What is your GPU?

N/A

**Comment by IMS212** [comment]
Jitpack isn't supported; the file is legacy and will be removed.

**Comment by ByThePowerOfScience** [comment]
What should we be building off of then?
