### ISSUE TITLE
Adding Nvidium Compatibility 

### ISSUE THREAD

**Issue by unatried** [IrisShaders/Iris#2320]
**Is your feature request related to a problem? Please describe.**
Always when I use shader while having Nvidium installed it switches itself off, because it isn't compatible with shaders.

**Describe the solution you'd like**
Adding compatibility with Nvidium so you can have higher FPS and have shaders so it still looks nice. (If you have a 1060 or higher,)

**Describe alternatives you've considered**

**Additional context**
htttps://github.com/MCRcortex/Nvidium

**Comment by IMS212** [comment]
no

**Comment by vermillion-excl** [comment]
💀

**Comment by Delivator** [comment]
Why not?

**Comment by IMS212** [comment]
because it’s not possible
