### ISSUE TITLE
Nicknames/Holograms reflecting weirdly

### ISSUE THREAD

**Issue by Jajcoob** [IrisShaders/Iris#2326]
### What happened?

Holograms and Nicknames of players reflect in very weird position in the camera.

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/170115168/8a5d0034-b0c2-45bb-b4a5-3c44f0eaa970)
![image](https://github.com/IrisShaders/Iris/assets/170115168/8e4ce817-d821-4454-abf7-7d4715d719f1)

### Log output

[2024-05-20-6.log](https://github.com/IrisShaders/Iris/files/15380195/2024-05-20-6.log)

### Minecraft Version

1.20.4

### Iris Version

Iris Shaders v1.7.0+1.20.4

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3070

### Additional context

BUG **DOESN'T** HAPPEN ON **v1.6.17+1.20.4** (Tried many other shaders, and it still happens on v1.7.0)

**Comment by IMS212** [comment]
Feather Client is not supported.
