### ISSUE TITLE
Issue with AstraLex Shader

### ISSUE THREAD

**Issue by Reznc** [IrisShaders/Iris#2327]
### What happened?

The shaderpack simply didn't load when I got into a Minecraft server.

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/15411864/latest.log)

### Minecraft Version

Minecraft 1.20.4

### Iris Version

iris-1.7.0+mc1.20.4.jar

### Operating System

Windows 10

### What is your GPU?

AMD Radeon RX 580 Series

### Additional context

Failed to get entry for 10303

**Comment by IMS212** [comment]
Update the shader.
