### ISSUE TITLE
Shader pack failed to load - MC-Retro

### ISSUE THREAD

**Issue by samppajii** [IrisShaders/Iris#2328]
### What happened?

When attempting to load the MC-Retro shader a "Shader pack failed to load" message is sent to chat, and no shader is loaded

### Log output

final.vsh: final.vsh: 0(3) : error C5514: 'varying' is deprecated and removed from this profile, use 'in/out' instead
0(5) : error C7616: global variable gl_MultiTexCoord0 is removed after version 140
0(6) : error C7616: global function ftransform is removed after version 140

### Minecraft Version

1.20.4

### Iris Version

iris-1.7.0+mc1.20.4.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 3070

**Comment by IMS212** [comment]
This is a shader bug.
