### ISSUE TITLE
Incompatibility of clouds with settings

### ISSUE THREAD

**Issue by xbxct** [IrisShaders/Iris#2337]
### What happened?

Shaders (Maybe not everything) do not respond to cloud shutdown. The Better clouds mod fixes this issue.

### Screenshots

"Just the presence of clouds"

### Log output

The crash was not caused

### Minecraft Version

1.20.1

### Iris Version

1.7.0

### Operating System

Windows 10

### What is your GPU?

gtx1660

**Comment by xbxct** [comment]
Makeup-ultrafast-6.51

**Comment by xbxct** [comment]
a really serious approach

**Comment by IMS212** [comment]
Not sure why my comment didn’t post; this is intended behavior. Shaders have the ability to forcefully override your settings.

**Comment by xbxct** [comment]
But there is no plugin in iris that overrides this override, and in better clouds there is compatibility even with the compatibility setting turned off. For you, this is part of the code, for users there is less than 1 unnecessary cosmetic mod.

**Comment by IMS212** [comment]
The shader dev has intentionally chosen to do this. You can ask them to remove the override, but the shader dev usually knows better about why it’s there.

**Comment by xbxct** [comment]
The shaders offer a vanilla view of clouds as in the game and the fact that they simply cannot be disabled if there are no settings in the shader, when the shader is old/unfinished, this is problematic.
