### ISSUE TITLE
Possible MC 1.19.2 backport for Iris 1.7?

### ISSUE THREAD

**Issue by le0-VV** [IrisShaders/Iris#2343]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Iris 1.7.0 made available for Minecraft 1.19.2 or earlier

**Describe alternatives you've considered**
Updating to Minecraft 1.20+, which a lot of the mods I use don't support, also means updating a server shared with my friends, which has plugins that don't have proper 1.20 support, and updating my friends' Minecraft, which is tedious

**Additional context**
None needed

**Comment by IMS212** [comment]
no

**Comment by TLiG98** [comment]
> no

Could you clarify why this isn’t working? Is it a matter of feasibility or simply a lack of effort?  
What would it take to make this happen?

**Comment by le0-VV** [comment]
Maybe they just don’t want to, and for an open source project, is a totally valid reason

**Comment by TLiG98** [comment]
That is entirely understandable. I was just curious about the reasons.
