### ISSUE TITLE
[Feature Request] Add Linux support

### ISSUE THREAD

**Issue by LFRon** [IrisShaders/Iris#2347]
**Is your feature request related to a problem? Please describe.**

I try to boot iris from fabic,but it failed.I have tried many Minecraft versions but it still cannot boot.I think this module don't add support for Linux (Mesa) yet😂

**Additional context**
My computer configuration is as follows:
Linux Distro:Kubuntu 24.04
CPU:AMD Ryzen 7 8845HS
GPU:AMD Radeon RX 7600M XT

Could developer add Linux support?Thanks!😍

**Comment by 9182736450typist** [comment]
It works on Mac. Why not linux?

**Comment by famellad** [comment]
What versions are you running? Of Minecraft, Fabric, Sodium, and Iris? Because I've had absolutely no trouble running this on my Linux Machine (Arch Linux, with a Radeon RX 7800XT)

**Comment by IMS212** [comment]
Iris is solely developed on Arch Linux. So yes, it does have support.

**Comment by LFRon** [comment]
> What versions are you running? Of Minecraft, Fabric, Sodium, and Iris? Because I've had absolutely no trouble running this on my Linux Machine (Arch Linux, with a Radeon RX 7800XT)

I'm sorry that I found it is my problem.After I updated the linux-firmware.It could work😭
