### ISSUE TITLE
Crashed when facing gravel

### ISSUE THREAD

**Issue by PaRHaM-M0** [IrisShaders/Iris#2365]
### Minecraft Version

1.21

### Iris Version

1.71

### Sodium Version

0.5.9

### Operating System

Windows 11

### What is your GPU?

RTX 2060

### Java Version

Java 8 Update 411

### Reproduction Steps

1. When you remove a gravel
2. when gravel start falling
3. Game Crashes

### Additional context

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

**Comment by IMS212** [comment]
get Indium
