### ISSUE TITLE
Duplicate field exception when building with Iris dependency

### ISSUE THREAD

**Issue by Goby56** [IrisShaders/Iris#2387]
### What happened?

When building a project with Iris as `modCompileOnly` dependency the following error is thrown:
```
Execution failed for task ':remapJar'.
> java.lang.RuntimeException: duplicate field net/irisshaders/iris/mixin/vertices/MixinBufferBuilder/vertexCount;;I in inputs
```

### Minecraft Version

Minecraft 1.21

### Iris Version

1.7.1+1.21

### Operating System

Windows 11

### What is your GPU?

Nvidida GeForce GTX 1070

**Comment by IMS212** [comment]
Fixed in 1.7.2.
