### ISSUE TITLE
Rename MixinBufferBuilder#vertexCount to avoid yarn mappings conflict

### ISSUE THREAD

**Issue by Qendolin** [IrisShaders/Iris#2389]
In yarn mappings `BufferBuilder#vertices` is also called `vertexCount` which causes an issue when having Iris as a dependency.

`duplicate field net/irisshaders/iris/mixin/vertices/MixinBufferBuilder/vertexCount;;I in inputs`
is the error that is generated when remapping Iris because both the `@Unique` field `private int vertexCount;` and the `@Shadow` field `private int vertices;` will have the same name under yarn mappings.

The two fields in question:

https://github.com/IrisShaders/Iris/blob/a3540b83886bb6c4bae83bb4f7b2656dbc39a867/src/main/java/net/irisshaders/iris/mixin/vertices/MixinBufferBuilder.java#L76-L77

https://github.com/IrisShaders/Iris/blob/a3540b83886bb6c4bae83bb4f7b2656dbc39a867/src/main/java/net/irisshaders/iris/mixin/vertices/MixinBufferBuilder.java#L64-L65

I suggest to rename `vertexCount` to something else to avoid the conflict.

**Comment by IMS212** [comment]
Fixed in Iris 1.7.2.
