### ISSUE TITLE
TAA creates weird effect on player skins

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#239]
https://user-images.githubusercontent.com/75493688/114453041-69ca3480-9bd9-11eb-90bc-fd88175d71cb.mp4

Really odd TAA bug, watch the eyes on my skin

tested with starline and sodium-compat on Sildur's Vibrant Shaders Lite

**Comment by coderbot16** [comment]
I think this might be a shaderpack issue, can you test on OptiFine?

**Comment by edwloef** [comment]
Ah, this is indeed a shaderpack issue.

**Comment by coderbot16** [comment]
Good to know, thanks.
