### ISSUE TITLE
Incompatible with Noxesium

### ISSUE THREAD

**Issue by kispintyi** [IrisShaders/Iris#2390]
### What happened?

Iris isn't compatible with Noxesium 1.2.2 causing the game to crash!

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/116653691/9e46a6ea-0523-4c03-be32-9f65345c9388)

### Log output

Vanilla:
https://mclo.gs/q1mP6iu
https://mclo.gs/Kh7OXyG

Lunar Client:
https://mclo.gs/FLq9JUl

### Minecraft Version

Minecraft 1.20.4

### Iris Version

iris-mc1.7.1+1.20.4

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce GTX 1650

### Additional context

This incompatibility issue causes Lunar and other Clients not to function properly if Iris gets updated to the latest version! They're considered compatible when they aren't and this causes a crash!

**Comment by kispintyi** [comment]
https://github.com/Noxcrew/noxesium/issues/82

**Comment by IMS212** [comment]
Lunar Client is not supported; please reopen this only if you can reproduce without Lunar Client.

**Comment by kispintyi** [comment]
Yes, I can reproduce without Lunar Client! My logs are attached! I just updated it right now!

**Comment by kispintyi** [comment]
Additional logs:
https://mclo.gs/0H1fumZ
https://mclo.gs/9nnTpbx

**Comment by IMS212** [comment]
Fixed in Iris 1.7.2, releasing later today.

**Comment by kispintyi** [comment]
Thank you!
