### ISSUE TITLE
Grass becomes dark when shaders enabled on 1.21 version

### ISSUE THREAD

**Issue by ElvinGH** [IrisShaders/Iris#2393]
### What happened?

When I turn on shaders grass gets darker. This bug happens with any shader.

### Screenshots

![2024-06-30_12 02 20](https://github.com/IrisShaders/Iris/assets/139709317/017127e6-b4df-41ca-b7d5-89803f9f8a5d)
Shaders on

![2024-06-30_12 02 32](https://github.com/IrisShaders/Iris/assets/139709317/c5cefac2-2f09-46c5-abaf-f7f0abf66b92)
Shaders off

### Log output

[latest.log](https://github.com/user-attachments/files/16043812/latest.log)

### Minecraft Version

Minecraft 1.21

### Iris Version

iris-1.7.2+mc1.21.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 3060 Ti

**Comment by xafmo7a** [comment]
I'll try to fix it!

**Comment by IMS212** [comment]
This isn't a bug with "any shader", only VanilAA and other non 1.21 compatible packs. In 1.20.3, `grass` was changed to `short_grass`, so any packs made before 1.20.3 are broken. This is not an Iris bug.
