### ISSUE TITLE
strange issue with Complementary shaders

### ISSUE THREAD

**Issue by Zimber106** [IrisShaders/Iris#2394]
### Discussed in https://github.com/orgs/IrisShaders/discussions/2392

<div type='discussions-op-text'>

<sup>Originally posted by **Zimber106** June 30, 2024</sup>
So I had a few issues getting the shaders to load in the end today where i hadnt had any previously, and it gave me a log file to give to the lovely folks in their discord, and i followed their instructions, and it was deduced that the issue was with iris itself, not the shader. here are all related logs, attached, hope someone can figure this out. probably operator error, knowing me
[latest.log](https://github.com/user-attachments/files/16043787/latest.log)
[2024-06-30-7.log.gz](https://github.com/user-attachments/files/16043789/2024-06-30-7.log.gz)
[2024-06-30-6.log.gz](https://github.com/user-attachments/files/16043790/2024-06-30-6.log.gz)

</div>

**Comment by IMS212** [comment]
Please attempt to update your drivers.

**Comment by Zimber106** [comment]
> Please attempt to update your drivers.

i updated my drivers, the issue remains

[latest.log](https://github.com/user-attachments/files/16047445/latest.log)

**Comment by Zimber106** [comment]
i was running a slightly outdated version and had ACL enabled which my computer cannot support, thank you magnificent folks for all the hard work you do!
