### ISSUE TITLE
Bro i swear to god

### ISSUE THREAD

**Issue by Jacob824e** [IrisShaders/Iris#2403]
### What happened?

It just doesn't work for me  no matter what i try no matter what mod to help run it just won't work

### Screenshots

![2024-07-06_20 58 27](https://github.com/IrisShaders/Iris/assets/174901688/3579a693-398f-4a49-9514-7367f43b68b2)

### Minecraft Version

Minecraft 1.21

### Iris Version

iris-1.7.1+mc1.21.jar

### Operating System

Win 10

### What is your GPU?

Nvidia GeForce RTX 2070

**Comment by Jacob824e** [comment]
If im just stupid let me know

**Comment by Connor-GH** [comment]
You need a shader pack in order for it to take effect.

**Comment by whystars** [comment]
> ### What happened?
> It just doesn't work for me no matter what i try no matter what mod to help run it just won't work无论我尝试什么，它都对我不起作用，无论什么模组来帮助运行它，它都不起作用
> 
> ### Screenshots
> ![2024-07-06_20 58 27](https://private-user-images.githubusercontent.com/174901688/346293258-3579a693-398f-4a49-9514-7367f43b68b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjA1NzMsIm5iZiI6MTcyMDY2MDI3MywicGF0aCI6Ii8xNzQ5MDE2ODgvMzQ2MjkzMjU4LTM1NzlhNjkzLTM5OGYtNGE0OS05NTE0LTczNjdmNDNiNjhiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwMTExMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmQzMTNhM2RkOWFjNjY1ZjI5ODM0NDE5ODgyYmU4NmFjN2Y1ZGI1ZTMzOWZlMGI3YTRhNDliZDdmYTMwYjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qF1w7ytvkoRjqtWjtyaJBLxDChmtFL2a7jndXKffoiI)
> 
> ### Log output
> _No response_
> 
> ### Minecraft Version
> Minecraft 1.21
> 
> ### Iris Version
> iris-1.7.1+mc1.21.jar
> 
> ### Operating System
> Win 10
> 
> ### What is your GPU? 你的 GPU 是什么？
> Nvidia GeForce RTX 2070 英伟达GeForce RTX 2070
> 
> ### Additional context 其他背景信息
> _No response_

Iris requires a shader pack to work.
Such as ComplementaryUnbound, BSL, and Bliss. 
These are the shader packs.
