### ISSUE TITLE
my shaders not loading

### ISSUE THREAD

**Issue by Tomekigierki7** [IrisShaders/Iris#2404]
### What happened?

i loaded a sharder and error poped up : 
deferred.fsh: deferred.fsh: 0(57) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(57) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(58) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(59) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"

### Screenshots

![obraz_2024-07-07_134231200](https://github.com/IrisShaders/Iris/assets/174940647/ab369815-5f53-4f68-95b4-6f7bbed634d3)

### Log output

deferred.fsh: deferred.fsh: 0(57) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(57) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(58) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(59) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"

### Minecraft Version

1.20.1 fabric

### Iris Version

1.7.2 mc-1.20.1

### Operating System

windows 11

### What is your GPU?

Nvidia Geforce RTX 3060ti

**Comment by Luracasmus** [comment]
That looks like it could be an error in the shader itself

What shader pack are you trying to load?

**Comment by Luracasmus** [comment]
I believe this should be fixed by Iris 1.8

**Comment by 033-Y0urn4meee** [comment]
deferred.fsh: deferred.fsh: ERROR: 0:232: 'frameFract' : undeclared identifier
