### ISSUE TITLE
Shaders incompatible with FRAPI

### ISSUE THREAD

**Issue by winkado** [IrisShaders/Iris#2405]
**Is your feature request related to a problem? Please describe.**
Multiple mods make use of the Fabric Rendering API to, well, render things. An example is Baritone's pathfinding render which is completely disabled upon enabling shaders.

**Describe the solution you'd like**
I would like for Iris' renderer to support FRAPI so that shaders can be used in combination with FRAPI utilizing mods, such as Baritone.

**Describe alternatives you've considered**
I've considered using renderers such as Canvas or just sticking to Indigo. However, I feel there are no real alternatives to Iris and that it is the only good shader mod.

**Additional context**

**Comment by IMS212** [comment]
Iris supports FRAPI (see Continuity and similar); this is likely an unrelated issue.
