### ISSUE TITLE
Can't load shaders

### ISSUE THREAD

**Issue by ghost** [IrisShaders/Iris#2426]
### What happened?

Unexpected error while creating framebuffer: Draw buffers [0, 1, 2] Status: 36061

### Minecraft Version

1.21

### Iris Version

1.7.1+mc1.21

### Operating System

Ubuntu Linux 24.04

### What is your GPU?

Nvidia Geforce GTX 1060

**Comment by Luracasmus** [comment]
Probably a similar issue to https://github.com/IrisShaders/Iris/issues/2410

**Comment by Beaninator** [comment]
found a similar issue
