### ISSUE TITLE
[1.20.3+] Wrong grass ID mapping

### ISSUE THREAD

**Issue by Sunset-NotFound** [IrisShaders/Iris#2433]
### What happened?

Starting from Minecraft1.20.3, Mojang changed the name of _**grass**_ to  _**short_grass**_ This resulted in all shaders packages being unable to recognize grass, Users cannot solve the problem by modifying the properties file either.

Okay, I haven't looked at the source code and I don't know the actual situation, but currently it's really impossible to fix this issue through the properties file.

### Minecraft Version

1.20.3 to 1.20.6

### Iris Version

iris-1.7.2+mc1.20.6.jar

### Operating System

Windows 10

### What is your GPU?

RTX 2070

### Additional context

It has been confirmed by one of my friends that this issue needs modifying the class files to fix and cannot be fixed by modifying properties file in shaders packs.

**Comment by SpacEagle17** [comment]
This should be fixable via the properties file though, just add the new name

**Comment by IMS212** [comment]
This is intentional; Iris does not plan to rename it.
