### ISSUE TITLE
No daylight cycle with BSL shaders

### ISSUE THREAD

**Issue by okrorero** [IrisShaders/Iris#244]
(I'm aware that the focus is mainly on Sildur's shaders right now but I thought it'd be a good idea to put this here.)
When using bsl shaders (or other shaders based on that) the sun seems to be stuck at this sunrise position. The color also remains on a gradient but when its midnight it becomes slightly darker. In these pictures I was using Complementary shaders which is based on BSL.

![2021-04-16_01 20 38](https://user-images.githubusercontent.com/82604339/114950346-7fe72780-9e5b-11eb-9241-134e7cfdb9f1.png)
**Midnight on Iris**

![2021-04-16_01 27 56](https://user-images.githubusercontent.com/82604339/114950547-013eba00-9e5c-11eb-8dd6-c8efc5e15834.png)
**Midnight on Optifine**

![2021-04-16_01 20 48](https://user-images.githubusercontent.com/82604339/114950597-1582b700-9e5c-11eb-938c-9f0de830c9f0.png)
**Noon on Iris**

![2021-04-16_01 28 06](https://user-images.githubusercontent.com/82604339/114950615-1f0c1f00-9e5c-11eb-9a29-c773da8edd65.png)
**Noon on Optifine**

I was curious whether this gradient could be recreated on Optifine so I tried to find the closest time value that matched the gradient and the closest I got was 50:

![2021-04-16_01 19 10](https://user-images.githubusercontent.com/82604339/114951128-254ecb00-9e5d-11eb-9e4d-1a633f4155ac.png)
**/time set 50  On optifine**

**Comment by Kroppeb** [comment]
Know issue, this is cause custom uniforms aren't implemented yet. We are working on it but will take some time.

**Comment by coderbot16** [comment]
This was fixed with https://github.com/IrisShaders/Iris/commit/8cbd393d71f136c92e6ad734145d206cf211d646
