### ISSUE TITLE
mc_midTexCoord not patched in core profile

### ISSUE THREAD

**Issue by GeForceLegend** [IrisShaders/Iris#2442]
### What happened?

In compatibility profile, mc_midTexCoord will get patched by `vec4 iris_MidTex = vec4(mc_midTexCoord.xy * 3.0517578E-5f, 0.0f, 1.0f);`. But when shader is using core profile, Iris will leave the `mc_midTexCoord` without patch it, causing it's value 32768x than expected.

### Minecraft Version

1.20.6

### Iris Version

iris-1.7.3+mc1.21.jar

### Operating System

Windows10 Home 22H2 19045.4529

### What is your GPU?

NVIDIA GeForce RTX 4070

**Comment by IMS212** [comment]
Should be fixed in Iris 1.8.
