### ISSUE TITLE
No more available texture units while activating sampler depthtex0

### ISSUE THREAD

**Issue by Dazhixiong** [IrisShaders/Iris#2443]
### What happened?

I was playing minecraft with fabric and distant horizons mod. I downloaded Iris and put the Iris jar into my mod folder. Whenever I try to load a shader pack, it always says there is an issue with it and I have to report it. This is the error message I got when trying to load the Bliss shader pack: "No more available texture units while activating sampler depthtex0". 

### Screenshots

<img width="516" alt="Screenshot 2024-08-08 at 11 33 11 PM" src="https://github.com/user-attachments/assets/51d501a9-2f6e-4a56-96b6-cbd63713f3e6">

### Minecraft Version

launcher is fabric 1.21.1, but mods inside are ALL 1.21

### Iris Version

iris-1.7.3+mc1.21.jar

### Operating System

MacOS Sonoma 14.5

### What is your GPU?

Apple M3 Pro

**Comment by IMS212** [comment]
The shaderpack you are trying to use is not compatible with macOS. This is not an Iris bug.
