### ISSUE TITLE
Weird bug when turning on some shaders

### ISSUE THREAD

**Issue by VictorBonassina** [IrisShaders/Iris#2444]
### What happened?

I've been using the complementary shaders pack for the past few days until, for some reason, it started basically crashing my pc while playing on a server (this does not happen on single player), and because of that I was trying out different shaders to see if the problem was the shaders or my pc, but when I downloaded 2 other packs (insanity and pastel) both of them had a different problem as you can see in the screenshot.

Any ideas for a fix for any of the 2 problems?

specs:
-RX 5700 XT
-Ryzen 5 5600X
-16GB ddr4 of ram (4 allocated to minecraft)

Things I've tried:
-disabling all mods exept sodium and iris, turning on/off any settings in video settings and I tried with more than 1 shader pack.

### Screenshots

No shader

![normal](https://github.com/user-attachments/assets/ae8b76e5-be35-4af1-835e-0824c285c7a4)

Complementary Reimagined shaders

![reima](https://github.com/user-attachments/assets/4e727e33-dd30-43c2-ab32-17ff010df2f3)

Pastel shaders

![bug](https://github.com/user-attachments/assets/c8c920bc-93b7-437a-a816-15f8997e6b58)

### Log output

[latest.log](https://github.com/user-attachments/files/16591495/latest.log)

### Minecraft Version

1.21

### Iris Version

iris-1.7.3+mc.21

### Operating System

Arch linux

### What is your GPU?

RX 5700 XT

**Comment by CorneliusCornbread** [comment]
Experiencing this same issue with some texture packs having two triangles making up the entire view on Fedora 40 Mesa 24.1.5

**Comment by IMS212** [comment]
Update to Mesa 24.2.
