### ISSUE TITLE
sushi shaders is broken

### ISSUE THREAD

**Issue by SuperLavaHair1** [IrisShaders/Iris#2448]
### What happened?

sushi shaders is broken in 1.21 plz fix im stuck on 1.20 cuz of this bug i am using lunar client that might help

### Minecraft Version

1.21

### Iris Version

1.7.3+mc1.21

### Operating System

windows 10

### What is your GPU?

evga rtx 2070 xc ultra

### Additional context

every time i load my shaders it says it failed to load and it doesnt do it in 1.20 there isnt a log file i can go off of but here is the thing in the chat it said
composite.fsh: composite.fsh: 0(213) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(213) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(214) : error C0000: syntax error, unexpected ')', expecting "::" at token ")"
0(215) : error C1503: undefined variable "sprojpos"
0(216) : error C0000: syntax error, unexpected ')', expecting "::" at token ")"
0(217) : error C1503: undefined variable "dist"
0(369) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(369) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(370) : error C0000: syntax error, unexpected '*', expecting "::" at token "*"

**Comment by Luracasmus** [comment]
Seems to be a similar problem as in https://github.com/IrisShaders/Iris/issues/2404 and https://github.com/IrisShaders/Iris/issues/2399#issuecomment-2240934828

**Comment by Luracasmus** [comment]
Can confirm this also occurs on my system (MC 1.21.2, Iris 1.7.3, Windows 11, RTX 4070)

![image](https://github.com/user-attachments/assets/b3c5300e-6c8c-41e6-979b-e034331fd86e)
I believe the error is caused by Iris patching the shader to a GLSL version where `sample` is a keyword without renaming variables with the same name

**Comment by SuperLavaHair1** [comment]
does that mean its possible to fix with a mod update or do i have to update the shader myself as it isnt being updated anymore

**Comment by Luracasmus** [comment]
A workaround for the problem (which is in Iris itself) is to simply to find-replace `sample` with any unused name

I've made a fork of the shader pack which does exactly this, and should work perfectly :)
https://github.com/Luracasmus/Sushi-Shader-Iris-Sample-Workaround

**Comment by SuperLavaHair1** [comment]
there are no downloads so i tried editing the files in notepad and couldnt find half of the things im meant to replace with samp so im kinda stuck at the moment

**Comment by SuperLavaHair1** [comment]
yea theres no downloads for it from what my peanut brain can tell so i tried finding all the sample things to replace them with samp and i couldnt find half of them

**Comment by Luracasmus** [comment]
Apologies for the late reply
You should be able to download the entire repository as a ZIP archive, which you can then extract the shader pack (the folder containing the folder named `shaders`) from

![image](https://github.com/user-attachments/assets/eb75e2c3-48cc-4568-8de5-1f97903f8657)

![image](https://github.com/user-attachments/assets/95596f85-b906-4c6d-aeda-d811dc6ecbc0)

**Comment by IMS212** [comment]
Sorry for not responding either; Iris 1.8 fixes this too, if you want to update.

**Comment by Luracasmus** [comment]
> Sorry for not responding either; Iris 1.8 fixes this too, if you want to update.

Oh, it's fixed already? Awesome!

**Comment by Luracasmus** [comment]
That should probably close these as well:
https://github.com/IrisShaders/Iris/issues/2404
https://github.com/IrisShaders/Iris/issues/2399#issuecomment-2240934828
https://github.com/IrisShaders/Iris/issues/2431

**Comment by SuperLavaHair1** [comment]
i know this post is closed but when i enable ssao it says lava isnt a variable and is this the same pack cuz it looks so different and the settings are organized
