### ISSUE TITLE
Latest version of Distant Horizons on 1.20.1 incompatible with Latest version of Iris on 1.20.1.

### ISSUE THREAD

**Issue by SmallbutDeadly** [IrisShaders/Iris#2453]
### What happened?

The latest version of Distant Horizons incompatible with Latest version of Iris on 1.20.1, which is the latest version of minecraft that the Create mod supports. I get this error on startup.

### Log output

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Iris' (iris) 1.7.2+mc1.20.1 (C:\Other Games\ATlauncher\instances\FabulouslyOptimizedCreateMod\mods\iris-1.7.2+mc1.20.1.jar).
More details:
	 - Mod 'Distant Horizons' (distanthorizons) 2.2.0-a is incompatible with version 1.7.4 or earlier of mod 'Iris' (iris), but a matching version is present: 1.7.2+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Minecraft Version

1.20.1

### Iris Version

iris-1.7.2+mc1.20.1.jar

### Operating System

Windows 11

### What is your GPU?

7900 XT

**Comment by Plasman888** [comment]
Same

**Comment by gededo** [comment]
Yeah so the new version of DH needs iris version 1.8, but iris 1.8 is only available for 1.21 apparently, so i don't know why they even let you download the latest DH version for 1.20.1, since it's impossible to run.

**Comment by IMS212** [comment]
Distant Horizons supports more versions than Iris does. As Iris updates, Distant Horizons versions will slowly become incompatible.

**Comment by SmallbutDeadly** [comment]
I would like to add that the previous Distant Horizons version has a crash with that mod that happens after playing Minecraft for an hour or two, unrelated to having Iris run alongside it. The update that came from Distant Horizons (2.2.0-a) fixes that crash.

By not supporting 1.20.1 with at the very least some sort of hotfix, you're denying any Create mod user from running a stable game with Iris and Distant Horizons both installed. I at the very least ask that you please consider giving 1.20.1 a newer version of Iris.
