### ISSUE TITLE
The shaderpack failed to load error

### ISSUE THREAD

**Issue by ghost** [IrisShaders/Iris#2455]
### Minecraft Version

1.21.1

### Iris Version

iris-1.7.3+mc1.21

### Sodium Version

sodium-fabric-0.5.11+mc1.21

### Operating System

windows 11

### What is your GPU?

gtx650

### Java Version

Java 21

### Reproduction Steps

1. load shaderpack "Tea_V2.0.0_Dev7"
2. game shows error in chat "The shader pack failed to load! Copy Info"

This is what the "copy info" button said:

deferred.fsh: deferred.fsh: 0(67) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(67) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(68) : error C0000: syntax error, unexpected "*=", expecting "::" at token "*="
0(69) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(70) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"
0(72) : error C0000: syntax error, unexpected '=', expecting "::" at token "="
0(73) : error C0000: syntax error, unexpected "*=", expecting "::" at token "*="
0(74) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(75) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"

**Comment by Luracasmus** [comment]
Probably the same issue as:
https://github.com/IrisShaders/Iris/issues/2448
https://github.com/IrisShaders/Iris/issues/2404
https://github.com/IrisShaders/Iris/issues/2399#issuecomment-2240934828
https://github.com/IrisShaders/Iris/issues/2431

All of these should be fixed and closed by Iris 1.8

If the shader pack still doesn't work after upgrading to the Iris 1.8 beta, please send your full log file
> Usually this is found at .minecraft/logs/latest.log. If you are not sure how to find .minecraft, please see this article: https://minecraft.wiki/w/.minecraft#Locating_.minecraft. Please do not upload a compressed (.log.gz) file, they are very difficult for us to read when viewing issue reports. The log file instantly tells us important information like the versions of any other installed mods or if there are errors so it is very very important that you include it in your report.

**Comment by ghost** [comment]
Yep the shaders started working when i loaded up Iris 1.8

**Comment by 033-Y0urn4meee** [comment]
deferred.fsh: deferred.fsh: ERROR: 0:232: 'frameFract' : undeclared identifier
