### ISSUE TITLE
Version of Iris higher than 1.7.4 for game version 1.20.1

### ISSUE THREAD

**Issue by SmallbutDeadly** [IrisShaders/Iris#2456]
**Is your feature request related to a problem? Please describe.**

The latest version of Iris that is AVAILABLE FOR 1.20.1 is incompatible with Distant Horizons 2.2.0-a, the latest and most stable version of Distant Horizons available for 1.20.1. The Create mod for Fabric has it's latest minecraft version at 1.20.1, and going to any later version will remove the ability to use that mod on Fabric. To use Create, Shaders and Distant Horizons in a stable state would mean having to switch to Forge over Fabric.

The Previous version of Distant Horizons was compatible with Iris, but had a bug that induced crashing every hour. The latest version of Distant Horizons fixes that bug, but introduced changes that only later versions of Iris would be compatible with (1.7.4+).

**Describe the solution you'd like**

Give an update to Iris on 1.20.1 to a version of at least 1.7.4 or above. Iris is the only mod from which this issue can be fixed, and it should be a very simple one at that. Please just update the mod for 1.20.1.

**Comment by Batuking1111** [comment]
same problem in 1.20.4 iris

**Comment by Luracasmus** [comment]
I think this would require Sodium 0.6.0 to first be ported to these versions

**Comment by adamiola** [comment]
pls do this

**Comment by nukularpower** [comment]
Man, what a headache this has made for me.   There is a Sodium/Iris 1.8.0 version on discord, but of COURSE, that one breaks the Physics mod, which worked fine with older versions, but those don't work with Distant Horizons.  Always gotta be something.

**Comment by Kalikars** [comment]
Bumping this. The changelog for 2.2.0-a states "Mark Iris 1.7.4 and below as incompatible" in the Breaking Changes section, but there are no versions of Iris available above 1.7.4 (except for 1.8.0 betas, only available for 1.21). 

This is especially problematic because the auto-updater doesn't take this into consideration, so anyone unaware of this will circle back to this issue and duplicate this report.

**Comment by AugustSaintFreytag** [comment]
That whole dependency chain has been a disaster for months now. Some mods have never been updated from 1.20.1. Distant Horizons has made great progress but new versions need at least 1.7.4 which doesn't support 1.20.1. The only version there is is alpha/beta 1.8.0 but that in turn seems to have other incompatible mods. Then there's also Sodium 0.5.11 (public) which is generally incompatible with everything vs. the 0.6.0 alpha release.

I'm still looking but so far, absolutely nothing is working and I was looking forward to play with a new DH version.

**Comment by JansenNye** [comment]
> Man, what a headache this has made for me. There is a Sodium/Iris 1.8.0 version on discord, but of COURSE, that one breaks the Physics mod, which worked fine with older versions, but those don't work with Distant Horizons. Always gotta be something.

Where can I get this version?

**Comment by Anthonyg5005** [comment]
> > Man, what a headache this has made for me. There is a Sodium/Iris 1.8.0 version on discord, but of COURSE, that one breaks the Physics mod, which worked fine with older versions, but those don't work with Distant Horizons. Always gotta be something.
> 
> Where can I get this version?

in unstable releases within the discord server

**Comment by AugustSaintFreytag** [comment]
The authors posted a 1.7.5 build of Iris for Minecraft 1.20.1 for the impatient on the Discord, just a few days ago. I've tested it with the *latest* Distant Horizons and it's working, even without having to upgrade Sodium to the in-development version. The build when I downloaded it was `iris-1.7.5-snapshot+mc1.20.1-258522d-dirty`.

**Comment by IMS212** [comment]
Iris 1.7.5 has been released for 1.20.1. No other versions are planned to be updated.
