### ISSUE TITLE
Seeing all white wile using IterationT v3.0.0 

### ISSUE THREAD

**Issue by Dimetro25** [IrisShaders/Iris#2465]
### What happened?

When I switch to the shader I see all white. The settings are all to default.

Shader: IterationT v3.0.0

### Screenshots

![image_2024-09-04_151132152](https://github.com/user-attachments/assets/c32a077f-74b7-4df7-8c1b-3ec6c7fa5f27)

### Minecraft Version

1.21.1

### Iris Version

v1.8.0-beta.3+mc1.21.1

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 3060TI

**Comment by IMS212** [comment]
IterationT is not supported.
