### ISSUE TITLE
Iris breaks TACZ scopes

### ISSUE THREAD

**Issue by PlayerXYT** [IrisShaders/Iris#2467]
### What happened?

See [TACZ issue #199](https://github.com/MCModderAnchor/TACZ/issues/199)

### Minecraft Version

1.20.1

### Iris Version

1.7.2+1.20.1

### Operating System

Linux

### What is your GPU?

Nvidia GeForce RTX 3080Ti

**Comment by IMS212** [comment]
This seems to be fixed in an unreleased version of TACZ? Not sure.
