### ISSUE TITLE
Crash on startup: VertexSerializerRegistry

### ISSUE THREAD

**Issue by KB-Q** [IrisShaders/Iris#2473]
### Minecraft Version

1.21

### Iris Version

1.8.0-beta.4+mc1.21.1

### Sodium Version

0.6.0-beta.1+mc1.21

### Operating System

mac OS Sonoma 14.6.1

### What is your GPU?

-

### Java Version

21

### Reproduction Steps

Crash on startup:

[crash-2024-09-16_13.13.08-client.txt](https://github.com/user-attachments/files/17009825/crash-2024-09-16_13.13.08-client.txt)

**Comment by Vescusia** [comment]
Yeah, I have the same problem on neoforge with just Iris and Sodium installed. 
[latest.log](https://github.com/user-attachments/files/17011534/latest.log) and [crash-client.txt](https://github.com/user-attachments/files/17011568/crash-2024-09-16_12.27.33-client.txt)

**Comment by devensr88** [comment]
I had this issue, but solved it by updating to the latest Sodium version 0.6.0 beta 2 alongside Iris 1.8.0 beta 4

**Comment by sniffercraft34** [comment]
Happens with me too

**Comment by IMS212** [comment]
Wrong Sodium version.
