### ISSUE TITLE
at_midBlock.w is always 0 on 1.8.0 betas

### ISSUE THREAD

**Issue by ASaull** [IrisShaders/Iris#2474]
### What happened?

at_midBlock.w seems to always return 0 even though the BLOCK_EMISSION_ATTRIBUTE feature flag is still set.

This is used by Bliss Shaders to add the light from light blocks when using Flood Fill, and no longer works as of the 1.8.0 beta builds.

Light blocks do work in Photon shaders, however, since Photon uses the vanilla lightmap to add the light from light blocks.

### Screenshots

1.8.0 Beta 4 (and I also tested Beta 1, same issue)
![2024-09-18_00 38 36](https://github.com/user-attachments/assets/b8bb4e9c-b799-4a79-a0db-8fbfb3500e7f)
1.7.3
![2024-09-18_00 40 39](https://github.com/user-attachments/assets/b8dd7d84-2f81-441e-9a08-b6bdffa57a87)

### Minecraft Version

1.21.1

### Iris Version

1.8.0-beta.4+1.21-fabric.jar

### Operating System

Windows 11

### What is your GPU?

RTX 3070

### Additional context

This is the relevant section of Bliss Shader code.
                
		voxelId = uint(mc_Entity.x + 0.5);

		#ifdef IRIS_FEATURE_BLOCK_EMISSION_ATTRIBUTE
			if (voxelId == 0u && at_midBlock.w > 0) voxelId = uint(BLOCK_LIGHT_1 + at_midBlock.w - 1);
		#endif

		if (voxelId == 0u) voxelId = 1u;

		originPos += at_midBlock.xyz/64.0;
		
at_midblock.xyz works as expected, but at_midblock.w is always 0.

**Comment by IMS212** [comment]
Note: This bug is specific to light blocks.
