### ISSUE TITLE
weird floating water and colored glass pane bug with PBR and astralex

### ISSUE THREAD

**Issue by Jdesign35** [IrisShaders/Iris#2475]
![2024-09-20_20 24 27](https://github.com/user-attachments/assets/7d08a986-f484-4c78-91c6-c83a1289f787)
![2024-09-20_20 24 24](https://github.com/user-attachments/assets/1c3caa7f-033c-4d12-a72f-30058cdd721a)
![2024-09-20_20 24 05](https://github.com/user-attachments/assets/b2fcc22f-34dd-4eb2-b2ad-2fbf3df49992)
![2024-09-20_20 24 08](https://github.com/user-attachments/assets/52c01ab1-0aa1-4827-8328-91db0377410c)

the glitch is the water and glass pane flying outta place and also on astralex (LexBoost option)

### _**1.16.5 ON FABRIC!!**_

**Comment by IMS212** [comment]
1.16.5 is not supported
