### ISSUE TITLE
[1.21.1] MC games does not load the Menu with Iris enabled 

### ISSUE THREAD

**Issue by Periam** [IrisShaders/Iris#2478]
### What happened?

A bug happened after installing the latest version on neoforge the game does not show the menu screen anymore.
neoforge-21.1.62

### Screenshots

![image](https://github.com/user-attachments/assets/1ca3eb9c-2e21-4a0f-bf0c-4eda881983b4)

### Log output

[latest.log](https://github.com/user-attachments/files/17168073/latest.log)

### Minecraft Version

Minecraft 1.21.1

### Iris Version

iris-neoforge-1.8.0-beta.4+mc1.21.1

### Operating System

Windows 11

### What is your GPU?

Nvidia RTX 2080

**Comment by CaptBK13** [comment]
temporary, you can change to 21.1.61 is working

**Comment by Lolothepro** [comment]
update Iris

**Comment by Periam** [comment]
I have installed the latest version available and now the game is loading, thanks
