### ISSUE TITLE
Failed Injection Check

### ISSUE THREAD

**Issue by desagas** [IrisShaders/Iris#2479]
### Minecraft Version

1.21.1

### Iris Version

1.8.0-beta.4

### Sodium Version

0.6.0-beta.2

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3080

### Java Version

Defaults for Curseforge Neoforge 1.21.1, thus, I believe it is Java 21?

### Reproduction Steps

Put the mods I am using in my log file together in a pack, and launch it.

The main line is this: 
```
Critical injection failure: Callback method changeId(Lcom/mojang/blaze3d/vertex/PoseStack;Lnet/minecraft/client/renderer/MultiBufferSource;Lnet/minecraft/world/entity/LivingEntity;Lnet/minecraft/world/entity/EquipmentSlot;ILnet/minecraft/client/model/HumanoidModel;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/item/ArmorItem;)V in mixins.iris.json:entity_render_context.MixinHumanoidArmorLayer from mod iris failed injection check, (0/1) succeeded. Scanned 0 target(s). No refMap loaded.
```

Latest Log:
[latest.log](https://github.com/user-attachments/files/17174844/latest.log)

Debug Log:
[debug.log](https://github.com/user-attachments/files/17174845/debug.log)

Crash Log:
[crash-2024-09-28_09.00.48-client.txt](https://github.com/user-attachments/files/17174847/crash-2024-09-28_09.00.48-client.txt)

### Crash Report file and latest.log

```shell
See above;
```

**Comment by Lolothepro** [comment]
update Iris

**Comment by desagas** [comment]
So far, so good. Crash appears to be gone, I will update after testing a little bit.

**Comment by desagas** [comment]
Works perfectly, now! Thank you!
