### ISSUE TITLE
Mod 'Iris' (iris) 1.6.11 requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present

### ISSUE THREAD

**Issue by carsupper665** [IrisShaders/Iris#2492]
### Minecraft Version

Fabric minecraft 1.20

### Iris Version

iris-mc1.20.1-1.6.11.jar

### Sodium Version

sodium-fabric-mc1.20-0.4.10+build.27.jar

### Operating System

Windows 10

### What is your GPU?

RTX 4070

### Java Version

jdk-17.0.3.1

### Reproduction Steps

I donwload this mod from https://modrinth.com/mod/iris/versions?g=1.20
crash says requires version 0.5.3 of mod 'Sodium'
but sodium-fabric-mc1.20.1-0.5.3 is for 1.20.1, i can't find Sodium version 0.5.3 that is compatible with minecraft 1.20

IDK what to do, if someone know, I'd really appreciate it.
Sorry for my bad english :D

**Comment by Poopooracoocoo** [comment]
There's no reason to use Minecraft 1.20. Update to Minecraft 1.20.1. 1.20.1 was just a hotfix.

You can then install the latest versions of Sodium and Iris for 1.20.1:
https://modrinth.com/mod/sodium/versions?g=1.20.1&l=fabric
https://modrinth.com/mod/iris/versions?g=1.20.1&l=fabric
