### ISSUE TITLE
unable to load on neoforge server (1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [IrisShaders/Iris#2498]
### Minecraft Version

1.21.1

### Iris Version

latest

### Sodium Version

latest

### Operating System

Arch Linux

### What is your GPU?

6750xt

### Java Version

21

### Reproduction Steps

add the mod to server mods folder

### Crash Report file and latest.log

https://mclo.gs/gmEFB1C

### Additional context

https://mclo.gs/gmEFB1C

**Comment by IMS212** [comment]
Iris and Sodium are client mods.

**Comment by VaporeonScripts** [comment]
yes but u should add the code part to skip them :D

**Comment by VaporeonScripts** [comment]
![Image](https://github.com/user-attachments/assets/a4d3f583-1afc-43de-bb68-3ff716e4a404)
 just like this
