### ISSUE TITLE
Mipmap of block atlas texture inconsistent in deferred pipeline

### ISSUE THREAD

**Issue by GeForceLegend** [IrisShaders/Iris#2501]
### What happened?

While using block atlas texture in deferred pipeline, like `texture.composite.colortex6 = minecraft:textures/atlas/blocks.png`, mipmap level of block atlas texture changes with objects in last draw.

### Screenshots

Directly set program output to `texture(colortex6, texcoord, 4.0)` in composite.fsh (colortex6 has been set to block atlas texture in shaders.properties).
Hold a transparent block:
![Image](https://github.com/user-attachments/assets/cc4413a8-a436-4f32-8aa1-217040809d24)
Hold nothing:
![Image](https://github.com/user-attachments/assets/705165e2-6f35-4cc4-8623-746b5437ed26)

### Log output

Looks nothing useful in log

### Minecraft Version

Minecraft 1.21.1

### Iris Version

iris-fabric-1.8.0-beta.3+mc1.21.1.jar

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 4070

**Comment by IMS212** [comment]
This should match Optifine behavior. The last mipmap state will be used for the texture.

Should mipmaps always be on?

**Comment by GeForceLegend** [comment]
I guess yes, as in Optifine, cutout and cutout_mipped blocks are rendered together with mipmap on

**Comment by GeForceLegend** [comment]
Optifine will fix this in next preview. According to [sp614x's comment](https://github.com/sp614x/optifine/issues/7786#issuecomment-2493658362), block atlas mipmaps in deferred/composite/final should be enabled
