### ISSUE TITLE
Entity PBR is broken on 1.21.4

### ISSUE THREAD

**Issue by ShulkerSakura** [IrisShaders/Iris#2506]
### What happened?

A bug happened!
Entity PBR is still not working in proper.

### Screenshots

![Image](https://github.com/user-attachments/assets/d9c55b5a-3d3a-44c9-b262-ce4dd2997d67)

### Minecraft Version

1.21.4

### Iris Version

iris-fabric-1.8.4-snapshot+mc1.21.4-build.5504

### Operating System

Windows 11

### What is your GPU?

NVIDIA RTX 3060 laptop

**Comment by IMS212** [comment]
user error (non updated pack)

**Comment by ShulkerSakura** [comment]
Request reopen until you fix this
