### ISSUE TITLE
Oculus 1.7 1.20.1 for latest embeddium

### ISSUE THREAD

**Issue by User-124564** [IrisShaders/Iris#2508]
**Is your feature request related to a problem? Please describe.**
When I place block from create( block like brass funnel or smart observer) the game turns black

**Describe the solution you'd like**
The problem above should be fixed with oculus supporting latest embeddium for forge  1.20.1

**Describe alternatives you've considered**
none

**Additional context**
for now nothing

**Comment by Lolothepro** [comment]
This is the Iris repo, not the Oculus repo.
