### ISSUE TITLE
Block breaking animation is lit incorrectly when near light sources (Iris v1.7.3+mc1.21, Sildur's Vibrant Shaders v1.52 Extreme-VL)

### ISSUE THREAD

**Issue by IcoMakCore** [IrisShaders/Iris#2509]
### What happened?

I find the block-breaking animation that lights up near light sources in Minecraft 1.21, when using the Lunar Client with sildurs vibrant shader, to be annoying and visually unappealing. I think this effect is meant to add realism by integrating dynamic light effects, but it actually feels excessive and distracting. The fluctuating brightness and contrast can be particularly jarring, especially during long play sessions or in darker in-game environments. If this is a issue, please resolve it. I've searched everywhere for a solution.

### Screenshots

![Image](https://github.com/user-attachments/assets/c3227102-9dc2-49fe-bd9b-c280bdc0ff62)
![Image](https://github.com/user-attachments/assets/4bfe5403-90f2-4eb8-970d-b062661f7fc3)
![Image](https://github.com/user-attachments/assets/0b8225a2-55d6-41c9-b521-27feb0c97eaa)
![Image](https://github.com/user-attachments/assets/b976b5ad-7021-4a20-b8f2-7a38e01623dc)

### Minecraft Version

Lunar Client Fabric 1.21

### Iris Version

iris-1.7.3+mc1.21.jar

### Operating System

Windows 11

### What is your GPU?

Radeon RX 6750 XT

### Additional context

I see this problem only with this shader, all others work perfectly

**Comment by IMS212** [comment]
We don’t control Lunar Client.
