### ISSUE TITLE
Shaders stops working whenever changing dimensions

### ISSUE THREAD

**Issue by pinn3apple** [IrisShaders/Iris#2522]
### What happened?

They randomly gets disable and i am not able to reenable them without a restart

### Screenshots

![Image](https://github.com/user-attachments/assets/48784a80-4ff0-4679-9e65-77af7049bba2)

### Log output

[latest.log](https://github.com/user-attachments/files/17705384/latest.log)

### Minecraft Version

1.21.1

### Iris Version

iris-neoforge-1.8.0-beta.8+mc1.21.1

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 2050

**Comment by zzhou42** [comment]
Same issues for me as well after updating to Craftoria 1.7, this has been a recurring issue.

**Comment by IMS212** [comment]
Disable advanced cover rendering in Mekanism Covers.
