### ISSUE TITLE
[Bug] Minecraft Black Screen with Iris and Sodium Mods After Several Minutes of Play (1.20.1)

### ISSUE THREAD

**Issue by yukke6174** [IrisShaders/Iris#2529]
### What happened?

I am experiencing an issue where the screen randomly turns black after several minutes to half an hour of play in Minecraft 1.20.1. The game continues running (I can hear sound), but the screen remains black. No crash report is generated. I have to manually shut down my PC and restart it. This issue also happens even when only using the Sodium and Iris mods together.

**Mods**:  
- Iris Shaders (installed via Iris installer)
- Sodium
- Other performance-enhancing mods (Indium, LTHum, Nvidium, etc.)
**Java Version**: OpenJDK 17

**Steps to Reproduce**:
1. Install Minecraft version 1.20.1.
2. Install Fabric version fabric-loader-0.16.9-1.20.1.
3. Install Iris Shaders and Sodium using the respective installers.
4. Play the game with shaders enabled and render distance set to 32 chunks or higher.
5. After several minutes to half an hour, the screen turns black, but the game continues to run with sound.

### Log output

[15:53:08] [Thread-33/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. <attachment> does not specify a valid attachment for the default framebuffer.'

### Minecraft Version

fabric-loader-0.16.9-1.20.1

### Iris Version

iris-1.7.2+mc1.20.1.jar

### Operating System

Windows 10

### What is your GPU?

NVIDIA RTX 3080

### Additional context

- RAM: 32GB

**What I've Tried**:
1. Switching Java versions (Java 8, Java 17)
2. Adjusting Iris and Sodium settings
3. Modifying OpenGL settings (`-Dorg.lwjgl.opengl.display.allowSoftwareOpenGL=true`)
4. Updating GPU drivers

**Expected Behavior**:  
The game should not show a black screen and should run without issues.

**Additional Information**:  
The issue happens randomly after anywhere between 6 to 36 minutes of gameplay. It occurs even with only the Sodium and Iris mods. The mods were installed using their respective installers (Iris from the official Iris installer).

The shader used is ComplementaryUnbound_r5.3.

Thank you for your time and help in resolving this issue. I appreciate the hard work that the development team puts into making this mod possible.

**Comment by Poopooracoocoo** [comment]
How'd you resolve this?

**Comment by jab0on** [comment]
> How'd you resolve this?

so i had the same issue today and i solved it.
the issue was because of a mod called natural motion blur, i turned it off and it goes back to normal.
so you can either toggle it off or just remove it from your mods folder.
hope this helps
