### ISSUE TITLE
Weird black lines when render distance is above 25 chunk render distance 

### ISSUE THREAD

**Issue by QPCrummer** [IrisShaders/Iris#253]
32 Chunk Render
![2021-04-28_19 56 50](https://user-images.githubusercontent.com/66036033/116486715-3edc1380-a85c-11eb-8f97-d08d2e092992.png)
25 chunk
![2021-04-28_19 57 01](https://user-images.githubusercontent.com/66036033/116486744-50252000-a85c-11eb-8f0d-1d891e24cde1.png)
Latest version of Foundaton's Iris GUI fork
Latest (non-failing) Sodium-iris fork

**Comment by PhantomGaming27229** [comment]
I mentioned this the other day in the discord, it seems to only happen when iris loads a shader, internal or a pack. I am unsure of what causes it but it affects the mainline sodium fork and starline. I have also noticed the lines get worse the higher the render distance is made.

**Comment by QPCrummer** [comment]
They do get worse. When I loaded sildur’s, the lines were gone. I also see those lines around players. It could from them standing by water and it is trying to render their reflection, but it looks really weird. Other than that, it was a smooth transition to iris 3.0 (besides the performance hit of 100FPS, but you can’t wish for everything).

**Comment by thedocruby** [comment]
I also have noticed this, but it doesn't seem to occur on all shaderpacks, or with shaders off. Also happens on Starline with Shadows and Starline with Custom Uniforms.

In addition, I seem to remember this occurring at render distances of 20 and 24, but I may be mistaken. I will verify this later today if i get the chance
