### ISSUE TITLE
[Sodium fork] Task :compileJava FAILED - Could not find tools.jar

### ISSUE THREAD

**Issue by RDKRACZ** [IrisShaders/Iris#254]
```
> ./gradlew build

> Configure project :
Fabric Loom: 0.6.57 Build(release #57)
Using project based jar storage

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

```

I tried to switch Java to another I have installed by adding `org.gradle.java.home=/usr/lib/jvm/zulu16-ca-amd64/bin/java` in the `gradle-wrapper.properties` file but it still tried to compile with the default one. 

OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.10-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

OpenJDK Runtime Environment Zulu16.30+15-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+15-CA (build 16.0.1+9, mixed mode, sharing)

**Comment by RDKRACZ** [comment]
Seems like the download link (https://adfoc.us/39232277326748) from https://sildurs-shaders.github.io/downloads/ doesn't work. Probably temporary but maybe someone can upload a file (preferably the Medium version) somewhere for me?

**Comment by qtquwu** [comment]
This seems to be more of a compiling issue on your end rather than an issue with Iris itself

**Comment by IMS212** [comment]
You are attempting to use a JRE to compile. you need a JDK.

**Comment by ImperatorStorm** [comment]
from discord:
```
5. Do not ask for support on compiling Iris, and refrain from providing this support.
There is sufficient information for people who know what they're doing to compile the mod themselves without help. The fact that compiled builds are only distributed to Patrons is intentional, and is intended to keep the support burden manageable.

**Comment by coderbot16** [comment]
This isn't an Iris issue. There are many places to get help on getting Gradle to recognize your JDK location, but this isn't one.
