### ISSUE TITLE
Floating extra name tag

### ISSUE THREAD

**Issue by Helpful-Neko** [IrisShaders/Iris#2543]
### What happened?

A bug happened!

Updated to iris-fabric-1.8.0+mc1.21.1
With sodium-fabric-0.6.0+mc1.21.1

I get a double name tag. One will float in the air and spin around when I attempt to run regardless of what shader I use. I think it will drive me insane 

### Screenshots

![Image](https://github.com/user-attachments/assets/0e307791-4f5f-453c-92dc-5d36f64e7343)

### Minecraft Version

Minecraft 1.21.1/Fabric

### Iris Version

iris-fabric-1.8.0+mc1.21.1

### Operating System

Windows 10 pro

### What is your GPU?

AMD Radeon RX 5600 XT

### Additional context

Edit I think this is a incompatibility with something I will try to figure out with what

**Comment by Helpful-Neko** [comment]
After 4-5 hours of testing I found the culprit. It's MoreCosmetics ( https://modrinth.com/mod/morecosmeticsmod ) that causes this bug.

To fix this issue remove MoreCosmetics, Relaunch Minecraft, Issue solved.

**Comment by Singecku** [comment]
Just letting you know I spent the same amount of time researching and found this.  THANK YOU SO MUCH ! Incredible

**Comment by gwynkoop6-dev** [comment]
You can actually fix this by turning off Show name and Show nametags in the MoreCosmetics settings

<img width="876" height="553" alt="Image" src="https://github.com/user-attachments/assets/9686df30-7b9d-4253-91a7-bb1fa0a7de31" />
