### ISSUE TITLE
Crash loading shader

### ISSUE THREAD

**Issue by Unleashed75** [IrisShaders/Iris#2544]
### Minecraft Version

1.21

### Iris Version

iris-fabric-1.8.0+mc1.21.1.jar

### Sodium Version

sodium-fabric-0.6.0-beta.2+mc1.21.1.jar

### Operating System

Windows 10

### What is your GPU?

RX 6800 XT

### Java Version

Java 21

### Reproduction Steps

With only Fabric, Iris and Sodium mods installed and "Mellow" shader pack. (fabric 1.21)
When it trying to load the shader (in game), the game crashes, it can be reloaded but then it will not let me load any worlds, single or multiplayer.

### Crash Report file and latest.log

```shell

```

### Additional context

Again going over the details. With only these mods installed;

Fabric loader 1.21 0.16.9
fabric-api-0.102.0+1.21.jar
iris-fabric-1.8.0+mc1.21.1.jar
sodium-fabric-0.6.0-beta.2+mc1.21.1.jar

Shaderpack where the issue was found;
Mellow Shader v1.5.2.zip

Go into any world, single or Multiplayer and load the Mellow shaderpack. The game crashes.

Reloading the game straight after a crash works fine but now you can not join any worlds, single or multiplayer without it crashing again.

The game will reload ok straight after a crash but to stop it from still crashing, you must do either;

1) Disable the shader or change to another pack within the video settings before trying to open world or join a server.

2) Disable or remove both, the shader pack and Iris from the system folders. If you try to remove or disable only the shader pack from shader folder, the game will still crash. At this point, both the shader pack and Iris need to be disabled or removed, the game reloaded, then you can reload the game once again with Iris installed.

As of right now, I have only found the issue to happen with this one shader pack. I tried it with some of the others I had installed at the time but I didn't try all of them or others.

I shall add a report to Sodium too, because the log file mentions that mod a few times but I know little. with it being shader issue, it makes sense to be a iris related problem.

I would like to point towards the video settings having a visual issue too, where buttons are not labelled or are faded too much to see.
![Image](https://github.com/user-attachments/assets/b56e5768-0cf1-43c5-adba-07581b5318f2)

Sodium Report
https://github.com/CaffeineMC/sodium/issues/2894

[crash-2024-11-26_01.08.37-client.txt](https://github.com/user-attachments/files/17911270/crash-2024-11-26_01.08.37-client.txt)

[latest.log](https://github.com/user-attachments/files/17911287/latest.log)

**Comment by Poopooracoocoo** [comment]
Outdated version of Sodium. Update Sodium and see if the issue still occurs.

https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.0-fabric

From https://modrinth.com/mod/sodium/versions?g=1.21.1&g=1.21&l=fabric

There's no reason to use 1.21 anyway. You should be using 1.21.1. A [dependency override](https://wiki.fabricmc.net/tutorial:dependency_overrides) will allow you to run mods that depend only on 1.21

**Comment by Unleashed75** [comment]
It is the latest version showing up on the Modrinth App
And as for "I should be using 1.21.1....
NO, I should be using the version of Minecraft that I want to play. One that lets me play on the server that is set for Minecraft 1.21

It shouldn't come down to "Dependency overrides". If Modrinth only shows mods for 1.21, then those mods should work for that version. A user should not have to understand adding newer versions that do not show up on a list of compactable mods.

If it's not on the list, then it needs adding...

**Comment by Poopooracoocoo** [comment]
Sodium 0.6.0 will work on 1.21 without a dependency override. I let the Sodium folks know that they should change the metadata of the Modrinth and CurseForge releases of 0.6.0. 

https://discord.com/channels/602796788608401408/752637878462578778/1310779939989229610 via https://caffeinemc.net/discord

> And as for "I should be using 1.21.1....
NO, I should be using the version of Minecraft that I want to play. One that lets me play on the server that is set for Minecraft 1.21

My point was that 1.21.1 was just a hotfix that fixed 2 bugs. 1.21.1 clients can connect to 1.21 servers. (Yes, _without_ ViaFabricPlus!)

**Comment by Unleashed75** [comment]
Ok, I guess this issue can be closed. It looks like a me problem and Modrinth. Thanks for your time
