### ISSUE TITLE
Crashes when using Wind Charge.

### ISSUE THREAD

**Issue by Pigcrafter1112** [IrisShaders/Iris#2552]
### Minecraft Version

1.21.4

### Iris Version

iris-fabric-1.8.2+mc1.21.4.jar

### Sodium Version

sodium-fabric-0.6.2+mc1.21.4.jar

### Operating System

Windows 11

### What is your GPU?

RTX 2070

### Java Version

21.0.3

### Reproduction Steps

1. Use Wind Charge
2. Game Crashes

[crash-2024-12-03_23.57.37-client.txt](https://github.com/user-attachments/files/18000351/crash-2024-12-03_23.57.37-client.txt)
[latest.log](https://github.com/user-attachments/files/18000352/latest.log)

### Crash Report file and latest.log

```shell

```

### Additional context

Further testing shows it's specificaly the explosion_emitter particle that causes the crash

**Comment by AngryFIlly888** [comment]
This is now fixed in Iris 1.8.3
