### ISSUE TITLE
Explosions and Fireworks

### ISSUE THREAD

**Issue by AngryFIlly888** [IrisShaders/Iris#2553]
### Minecraft Version

Minecraft 1.21.4

### Iris Version

iris-fabric-1.8.2+mc1.21.4.jar

### Sodium Version

sodium-fabric-0.6.2+mc1.21.4.jar

### Operating System

Linux Mint 22 Cinnamon

### What is your GPU?

NVIDIA Corporation TU106 [GeForce RTX 2060 12GB]

### Java Version

Java 21.0.3

### Reproduction Steps

1. TNT, TNT Mine Cart, Creeper, Charged Creeper, End Crystal, Wither charge up, and Colored Fireworks Explosion cause crash right before exploding.
2. Firework trails are showing items instead of the normal trail particles.
3. Setting off multiple of the above will continue to crash the game when trying to load the world until all explosions have ceased. 

### Crash Report file and latest.log

```shell
[crash-2024-12-03_18.15.41-client.txt](https://github.com/user-attachments/files/18000833/crash-2024-12-03_18.15.41-client.txt)

[latest.log](https://github.com/user-attachments/files/18000836/latest.log)
```

### Additional context

Ghastfire balls do NOT cause crashes. Nor do the skulls the wither shoots.
Being far enough away does not cause crash. ( returned mixed results. Whether it is not looking at it while it explodes at a certain distance or being that distance away, I don't know. Only tested with TNT block. )

**Comment by davidjcannon** [comment]
Has this been fixed? I'm still having the issue.

**Comment by AngryFIlly888** [comment]
> Has this been fixed? I'm still having the issue.

What version of Iris are you using?
