### ISSUE TITLE
The latest “iris” shader crashes on Mac os

### ISSUE THREAD

**Issue by HarryH2O** [IrisShaders/Iris#2555]
### What happened?

A bug happened! My “iris” shader crashes, but the game starts fine after uninstalling!
I want my game to launch normally!

Steps to reproduce the bug:
1. Use the HMCL-3.6.11 launcher
2. Install 1.21.3 + Fabric 16.0.8 + fabric API - 0.106.1
3. Start the game in the same environment as me and observe the phenomenon

Related information:
My compurer: 2020 Macbook Pro M1 8+256
OS: macOS 14.7.1 (23H222) on MacBookPro17,1 (arm64)
Processor: 8 cores, Apple M1
Memory: 8G physical memory, 4G swap space
Java: JDK 23.0.1
Minecraft version: 1.21.3 (official)
Iris module version: 1.8.1+mc1.21.3 fabric
Loader: Fabric 16.0.8 + Fabric API - 0.106.1 + 1.21.3
Minecraft Launcher: HMCL-3.6.11

Other Mods:

### Log output

[1.21.3.json](https://github.com/user-attachments/files/18010723/1.21.3.json)
[crash-2024-12-04_23.13.04-client.txt](https://github.com/user-attachments/files/18010722/crash-2024-12-04_23.13.04-client.txt)
[hmcl.log](https://github.com/user-attachments/files/18010721/hmcl.log)
[hs_err_pid56347.log](https://github.com/user-attachments/files/18010724/hs_err_pid56347.log)
[latest.log](https://github.com/user-attachments/files/18010720/latest.log)
[minecraft.log](https://github.com/user-attachments/files/18010725/minecraft.log)

### Minecraft Version

Minecraft 1.21.3

### Iris Version

iris 1.8.1

### Operating System

macOS 14.7.1 (23H222) on MacBookPro17,1 (arm64)

### What is your GPU?

Apple M1

### Additional context

The game throws 'ExceptionInInitializerError' on initialization
The error involves a failed Mixin conversion of the 'net.caffeinemc.mods.sodium.client.render.immediate.CloudRenderer' class.
It may have something to do with Shader loading or Mixin configuration.

**Comment by IMS212** [comment]
Piracy is not supported.
