### ISSUE TITLE
No more available texture units while activating sampler depthtex0

### ISSUE THREAD

**Issue by sussyboiiii** [IrisShaders/Iris#2567]
### What happened?

When loading shaders other than BSL or Complementary they dont work. 

I tested Bliss, Rethinkin Voxels, Shrimple and Solas shaders

also Distant Horizons will not work with any supported shaders.

### Screenshots

![Image](https://github.com/user-attachments/assets/f63169b6-1fcb-4f74-a4eb-840b2d953b39)
<img width="309" alt="Image" src="https://github.com/user-attachments/assets/a592fb50-6ea5-4fcc-b912-bba84019baf4" />

### Log output

[latest.log](https://github.com/user-attachments/files/18135185/latest.log)

### Minecraft Version

1.21.1

### Iris Version

iris-fabric-1.8.1+mc1.21.1

### Operating System

MacOS 15.2

### What is your GPU?

M1 Pro

**Comment by IMS212** [comment]
This is normal. Many shaders are not supported by macOS.

**Comment by bewe3** [comment]
I got the error while using Bliss + Distant Horizons, while just Bliss on its own works fine. BSL + DH works, as does Complementary + DH and a few others

MacOS does support the shaders we're trying to use, but there was an Iris issue when combining Distant Horizons with said shaders

I'm on an M1 Max myself
