### ISSUE TITLE
Shader button isnt working

### ISSUE THREAD

**Issue by sixtysixx** [IrisShaders/Iris#2568]
### What happened?

Using Prism 9.1:

Join Server
Go to Settings
Go to Video Settings
Click on Shader Packs
Nothing Happens.

Same thing happens in title menu, no luck either.

ModList:

3d-Skin-Layers [1.7.4] 
AppleSkin [3.0.6+mc1.21.3] 
Architectury [15.0.1] 
Balm [21.4.1] 
Better Mount HUD [1.2.5] 
Blur+ [5.0.2] 
CICADA [0.9.1+1.21.2-and-above] 
Capes [1.5.4+1.21.4] 
Chat Heads [0.13.8] 
ClientSort [1.1.1+1.21.3] 
Cloth Config v17 [17.0.144] 
Crafting Tweaks [21.4.1] 
Cubes Without Borders [3.0.0+mc1.21.3] 
Do a Barrel Roll [3.8.1] 
Dynamic FPS [3.7.7] 
EntityCulling [1.7.2] 
Fabric API [0.112.0+1.21.4] 
Fabric Language Kotlin [1.13.0+kotlin.2.1.0] 
Fabrishot [1.14.2] 
Falling Leaves [1.16.6] 
Fast IP Ping [1.0.5] 
FerriteCore [7.1.1] 
Forge Config API Port [21.4.1] 
ImmediatelyFast [1.3.3+1.21.4] 
Iris [1.8.4+mc1.21.4] 
Jade [17.1.0+fabric] 
Journeymap [1.21.4-6.0.0-beta.32] 
Krypton [0.2.8] 
LambDynamicLights [4.0.1+1.21.4] 
Language Reload [1.7.2+1.21.4] 
Lithium [0.14.3+mc1.21.4] 
Main Menu Credits [1.2.0] 
MixinTrace [1.1.1+1.17] 
Mod Menu [13.0.0-beta.1] 
Model Gap Fix [1.21.3-1.10] 
More Chat History [1.3.1] 
More Culling [1.2.2] 
Mouse Tweaks [2.27] 
NetherPortalFix [21.4.1] 
No Chat Reports [1.21.4-v2.11.0] 
NotEnoughAnimations [1.8.2] 
OptiGUI [2.3.0-beta.7+1.21.2] 
Packet Fixer [1.5.0] 
Puzzle [2.0.4] 
Reese's Sodium Options [1.8.1+mc1.21.4] 
Replanter Plus [2.3.2] 
Resourcify [1.6.0] 
Roughly Enough Items [18.0.796] 
Sodium [0.6.3+mc1.21.4] 
Sodium Extra [0.6.1+mc1.21.4] 
ViaFabricPlus [3.6.1] 
YOSBR [0.1.2] 
YetAnotherConfigLib [3.6.2+1.21.4-fabric] 
Zoomify [2.14.2+1.21.3] 
e4mc [5.2.1] 
spark [1.10.121]

### Screenshots

https://github.com/user-attachments/assets/ba930989-6028-4897-8af5-6c6a3fe7f450

### Log output

https://mclo.gs/D0VuY7D
https://api.mclo.gs/1/raw/D0VuY7D

### Minecraft Version

1.21.4

### Iris Version

1.8.4+mc1.21.4

### Operating System

Win 11

### What is your GPU?

Nvidia Geforce RTX 4080 Super

**Comment by Excederus** [comment]
This is caused by Reese's Sodium Options. Apparently clicking above the "k" of "Shader Packs..." works or you can use the Shader Selection Screen keybind if you want to keep the mod. Otherwise disable/remove Reese's Sodium Options.

**Comment by sixtysixx** [comment]
Okay, thank you for your assistance.
