### ISSUE TITLE
Please make prebuilt versions

### ISSUE THREAD

**Issue by MaxBr5** [IrisShaders/Iris#257]
<pre>Gradle hates me so please make prebuilt versions and I would be the happiest person in the world.</pre>

**Comment by squishycat92** [comment]
> That being said... If you want to test out compiled alpha builds of the mod, please consider becoming a Patron, which will give you access to compiled downloads. Alternatively, developers who know what they are doing can compile the mod themselves.
no

**Comment by Guardian259** [comment]
How does this help development in any form or way?

**Comment by IMS212** [comment]
Please post the issue you are having with gradle, instead of asking for compiled builds. It is clearly stated in the readme that as of right now, compiled builds will not be distributed.

**Comment by MaxBr5** [comment]
<pre>Gradle detests me.</pre>

**Comment by MaxBr5** [comment]
<pre>Besides, I am only a child</pre>

**Comment by IMS212** [comment]
That is not a crash report or log file. If you cannot figure out how to compile it, you likely should not use this mod in it's current state.

**Comment by coderbot16** [comment]
This isn't the place to receive support for compiling the mod.

**Comment by MaxBr5** [comment]
<pre>Just compile it for yourself then.</pre>

**Comment by Guardian259** [comment]
> Gradle detests me.
> Besides, I am only a child.

neither of these are legitament reasons for requesting prebuilts, you obviously didnt bother to read the Readme that states this is in alpha and not ready for the public and that, if you don't know what your doing you shouldn't be working with iris at the time

**Comment by MaxBr5** [comment]
Drat.

**Comment by squishycat92** [comment]
> Just compile it for yourself then.
What is the point of this comment? You can easily make a batch script that automagically builds and puts Iris in your `/mods` folder. In addition, the readme clearly states that distributed builds are given to patrons only. If you'd like to use Iris without donating, simply compile it yourself.

**Comment by MaxBr5** [comment]
Just do gradle build

**Comment by MaxBr5** [comment]
<pre>Just do gradlew build</pre>
