### ISSUE TITLE
Iris 1.8.1 not tagged for 1.21 game version tag on Modrinth

### ISSUE THREAD

**Issue by davepusey** [IrisShaders/Iris#2573]
Iris 1.8.1 is missing the 1.21 game version tag on Modrinth.

This means that when updating mods Prism will update Sodium to 0.6.5 but does not find the required Iris 1.8.1 dependency, resulting in a broken installation that cannot launch.

Installing manually from https://modrinth.com/mod/iris/version/1.8.1+1.21.1-fabric will work but this is obviously not ideal from a UX perspective.

Please can the Iris 1.8.1 be correctly tagged as being compatible with BOTH 1.21 and 1.21.1 on Modrinth.

Thank you.

**Comment by IMS212** [comment]
1.21 will not be supported officially. I have marked this specific Fabric release as compatible, but future releases will not.
