### ISSUE TITLE
gradlew build

### ISSUE THREAD

**Issue by MaxBr5** [IrisShaders/Iris#258]
<pre>I may have just leaked the secret to compiling iris, just do gradlew build.</pre>

**Comment by thedocruby** [comment]
If you have an issue with Iris, please state the issue clearly and in detail so we may assist you.. Otherwise, this GitHub issue page should be closed. Thank you!

**Comment by DragonEggBedrockBreaking** [comment]
This issue report should also be deleted, so that steps to compile iris do not exist publicly in an easily accessible location - this is arguably easier than github actions considering that you can just search up the title on google for more info
