### ISSUE TITLE
Cannot access the shaderpacks GUI without Shift+P on Sodium

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#262]
We should consider changing up the keybinds here and/or adding a temporary button in the Sodium video settings screen that opens the current Iris shaderpacks screen.

**Comment by DragonEggBedrockBreaking** [comment]
Firstly, this would be in the sodium fork, not in iris, right? Secondly, it would be nice to be able to access the config menu from a button in ModMenu, like many other mods.

**Comment by coderbot16** [comment]
Yes, modifying the fork will probably be needed. I track issues with the sodium fork here since generally there's things to be done on both sides - you'll notice that the issue tracker isn't enabled on the sodium fork.

A modmenu config button would be helpful, though.

**Comment by Ex4byte** [comment]
https://pastebin.ubuntu.com/p/wsJ7HwKDgm/ I uploaded it here since the character size is too big for github and pastebin.

**Comment by IMS212** [comment]
Should be solved by IrisShaders/sodium-fabric#13
