### ISSUE TITLE
Shader pack selection UI includes the .minecraft/shaderpacks folder as an option if there is a non-zip shader pack installed

### ISSUE THREAD

**Issue by FoundationGames** [IrisShaders/Iris#268]
If you have a non-zip shaderpack installed, the shaderpack selection UI shows `shaderpacks` as an available option since `.minecraft/shaderpacks` contains a `shaders` folder in its file tree and was never checked for.

To reproduce:
- Add a folder to `.minecraft/shaderpacks` which contains a `shaders` folder, or add a `shaders` folder to `.minecraft/shaderpacks`
- Open shader pack selection UI

**Comment by coderbot16** [comment]
Fixed in #269
