### ISSUE TITLE
mc crashing when using seus v11

### ISSUE THREAD

**Issue by kleinermob** [IrisShaders/Iris#271]
[crash-2021-05-14_21.10.48-client.txt](https://github.com/IrisShaders/Iris/files/6480758/crash-2021-05-14_21.10.48-client.txt)

**Comment by ColdIce1605** [comment]
Shader compilation failed!
:P

**Comment by OverlordsIII** [comment]
If you send the full latest.log in `.minecraft/logs` you can see how the shader crashed there.

**Comment by kleinermob** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/6487546/latest.log)

**Comment by Moranic** [comment]
This appears to be the relevant part of the log:

> [16:07:38] [main/WARN]: [<sodium shaders>] Unsupported uniform: mat4 u_ModelViewMatrix
> [16:07:38] [main/WARN]: [<sodium shaders>] Unsupported uniform: mat4 u_NormalMatrix
> [16:07:38] [main/WARN]: [<sodium shaders>] Unsupported uniform: vec3 u_ModelScale
> [16:07:38] [main/WARN]: [<sodium shaders>] Unsupported uniform: vec2 u_TextureScale
> [16:07:38] [main/WARN]: [<sodium shaders>] Unsupported uniform: (unknown:35667) atlasSize
> [16:07:38] [main/INFO]: [STDERR]: No uniform exists with name: u_ModelViewProjectionMatrix (got index -1)
> [16:07:38] [main/INFO]: [STDERR]: No uniform exists with name: u_BlockTex (got index -1)
> [16:07:38] [main/INFO]: [STDERR]: No uniform exists with name: u_LightTex (got index -1)
> [16:07:39] [main/WARN]: [gbuffers_basic] Unsupported uniform: int fogMode
> [16:07:39] [main/WARN]: Program link log for gbuffers_textured_lit: error: fragment shader varying distance not written by vertex shader

After this the crash happens:
> [16:07:39] [main/FATAL]: Unreported exception thrown!
> java.lang.RuntimeException: Shader compilation failed!
> 	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.createPass(DeferredWorldRenderingPipeline.java:350) ~[iris-0.4.0-pre.jar:?]
> 	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_202]
> 	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.<init>(DeferredWorldRenderingPipeline.java:104) ~[iris-0.4.0-pre.jar:?]
> 	at net.coderbot.iris.Iris.createPipeline(Iris.java:324) ~[iris-0.4.0-pre.jar:?]
> 	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:41) ~[iris-0.4.0-pre.jar:?]
> 	at net.minecraft.class_761.handler$zcd000$iris$beginWorldRender(class_761.java:5132) ~[intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
> 	at net.minecraft.class_761.method_22710(class_761.java) ~[intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
> 	at net.minecraft.class_757.method_3188(class_757.java:727) ~[intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
> 	at net.minecraft.class_757.method_3192(class_757.java:546) ~[intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
> 	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
> 	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
> Caused by: java.lang.RuntimeException: Shader program linking failed, see log for details
> 	at net.coderbot.iris.gl.shader.ProgramCreator.create(ProgramCreator.java:36) ~[iris-0.4.0-pre.jar:?]
> 	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:62) ~[iris-0.4.0-pre.jar:?]
> 	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.createPass(DeferredWorldRenderingPipeline.java:346) ~[iris-0.4.0-pre.jar:?]
> 	... 18 more

**Comment by thedocruby** [comment]
Could someone please verify that this still happens with the release version of Iris?

**Comment by kleinermob** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/6640178/latest.log)
still not working, but it works on windows tho

**Comment by AlsoNiko** [comment]
Are you using amd on Linux?

**Comment by DestinyTheGreat** [comment]
SEUS doesn't work on Macs either FYI

**Comment by kleinermob** [comment]
> Are you using amd on Linux?

yes, rx 570 with mesa

**Comment by AlsoNiko** [comment]
That's probably the issue, Mesa drivers have been giving issues

**Comment by kleinermob** [comment]
it works on linux with amds proprietary drivers
![Screenshot_20210611_200459](https://user-images.githubusercontent.com/42699035/121730790-6f1c0080-caf0-11eb-883e-4d73df2cc3ea.png)

**Comment by AlsoNiko** [comment]
Known issue with Mesa drivers
