### ISSUE TITLE
opening a world with chocopic v9 low causes a CTD

### ISSUE THREAD

**Issue by hackaholic5069** [IrisShaders/Iris#279]
[crash-2021-05-21_07.48.39-client.txt](https://github.com/IrisShaders/Iris/files/6525372/crash-2021-05-21_07.48.39-client.txt)

**Comment by coderbot16** [comment]
You need to post your log file as well.

**Comment by coderbot16** [comment]
I can't reproduce this crash on the current version, and I can't really investigate this otherwise without a latest.log file.

**Comment by coderbot16** [comment]
Please test and see if the crash happens without Sodium as well.

**Comment by coderbot16** [comment]
This is likely a shader compilation error, which shouldn't cause a CTD anymore.
