### ISSUE TITLE
Stained glass is generally broken on SEUS v10/v11 and SEUS Renewed

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#286]
SEUS v10:

![SEUS v10 Bug - 2021-05-26_16 30 53](https://user-images.githubusercontent.com/22420959/119750708-b8145980-be4e-11eb-9245-dd1cd42a2f62.png)

SEUS Renewed:

![SEUS Renewed Bug - 2021-05-26_16 23 40](https://user-images.githubusercontent.com/22420959/119750712-b9458680-be4e-11eb-86bc-b9639bd6fdb3.png)

SEUS v11 (the glass has moving waves in it???):

https://user-images.githubusercontent.com/22420959/119750715-b9de1d00-be4e-11eb-81e2-92cfa67524cf.mp4

**Comment by AlsoNiko** [comment]
This is my fault for forgetting to make the issue, but the first screenshot is mislabeled as v11 when it should be v10

**Comment by coderbot16** [comment]
Oh, SEUS v10 works now? Neat, it was super broken before last time I checked. Anyways, I've updated the issue.

**Comment by AlsoNiko** [comment]
Yep, Seus 10 is mostly working on the shadows branch as far as I can tell

**Comment by AlsoNiko** [comment]
Another thing with SEUS renewed glass, the ground flickers when looking through it

https://user-images.githubusercontent.com/64978191/119924901-6b11af80-bf42-11eb-99e2-4a3f5bdf7dfa.mp4

**Comment by AlsoNiko** [comment]
Looking further, every version of seus has a similar bug, just without the flickering (Screenshots go iris then optifine)

SEUS v10
![2021-05-27_23 23 33](https://user-images.githubusercontent.com/64978191/119925391-5c77c800-bf43-11eb-86a0-9cec087104c7.png)
![2021-05-27_23 26 13](https://user-images.githubusercontent.com/64978191/119925400-61d51280-bf43-11eb-94b2-1a4e80a758e2.png)

SEUS v11
![2021-05-27_23 25 29](https://user-images.githubusercontent.com/64978191/119925415-6a2d4d80-bf43-11eb-834f-996353e178a1.png)
![2021-05-27_23 25 39](https://user-images.githubusercontent.com/64978191/119925437-74e7e280-bf43-11eb-940b-44e514edbc00.png)

**Comment by coderbot16** [comment]
This should be fixed with f321b894cf6c2b2506636655234767013afc7eb0 and e3efabc8d8d3dea546594beda5e1aade57ec85d9
