### ISSUE TITLE
Weather is broken on many shaderpacks

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#289]
Complementary Shaders (rain is visible if you look closely)
![image](https://user-images.githubusercontent.com/22420959/119752296-9c5e8280-be51-11eb-91a0-f271c66fa710.png)

**Comment by CodingRays** [comment]
I was unable to reproduce the issue with the 1.0 release or the 1.1pre build with or without sodium.
Is it fixed by now?

**Comment by coderbot16** [comment]
This should be mostly resolved actually, there were a few related bugs causing most shader packs to have issues with weather in the past. The weather Sildur's, BSL, and Complementary seems to work fine now.
