### ISSUE TITLE
Fog density is not supported on 1.17

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#294]
This causes many issues with shaderpacks that rely on the fog values, including Enhanced Default.

**Comment by IMS212** [comment]
#227 should have fixed the fog color uniform.

**Comment by coderbot16** [comment]
fogDensity is a separate value from fogColor

**Comment by IMS212** [comment]
This has been fixed with 1.16, but 1.17 is still missing it. (1.17 seems to use linear fog in all cases, so is this uniform needed?)
