### ISSUE TITLE
Weird grass effect with the Conquest resource pack

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#297]
First we should probably figure out if it's even our fault. Apparently it doesn't happen on OptiFine... but how?
![image](https://user-images.githubusercontent.com/22420959/119763309-231c5b00-be64-11eb-8044-5db6d30eabcf.png)

**Comment by Guardian259** [comment]
Thus dies occur both in Iris and Vanilla. Optifine is correcting or fixing some form of Vanilla bug/rendering error to rectify this. A lead for this may be that Conquest makes use of an overlay atop of grass blacks themselves, about a pixel above the block, and gives the block a unique texture and possibly rendering requirements

**Comment by coderbot16** [comment]
I wonder if OptiFine is making the overlay render with a custom layer like CUTOUT instead of CUTOUT_MIPPED or similar. You could test to see if there's a shimmer effect in the distance like with tall grass to see if that's the case.

**Comment by thedocruby** [comment]
Something similar happens with vanilla textures in vanilla at very low resolutions, where the texture on the side of a grass block sometimes renders with a black bar between the grassy part and the dirt part. This problem does however disappear when mipmap levels are set to zero, it would be interesting to see if this is also the case for the resource pack textures.
