### ISSUE TITLE
shader options?

### ISSUE THREAD

**Issue by arceuss** [IrisShaders/Iris#299]
im trying to get pbr on complementary shaders but it seems theres no way to
![image](https://user-images.githubusercontent.com/28229451/119888548-b603d680-bef2-11eb-9c59-3c639d0d802f.png)

**Comment by AlsoNiko** [comment]
This is a known thing, there is no config menu yet

**Comment by heymanMC** [comment]
Yep, its a PR waiting to be merged. https://github.com/IrisShaders/Iris/pull/168

**Comment by arceuss** [comment]
huh

**Comment by AlsoNiko** [comment]
Iris is currently in the alpha stages, and as such isn't fully featured

**Comment by DisaKzionda** [comment]
This have shader options https://github.com/HyperCubeMC/Iris
![image](https://user-images.githubusercontent.com/53359732/120093120-6411b980-c15b-11eb-997b-6ea2d3509b73.png)

**Comment by IMS212** [comment]
That fork isn't official and should not be used if you do not know what you are doing.

**Comment by Rajbir98** [comment]
can u give me the download link of the forked iris

**Comment by AlsoNiko** [comment]
If you can't find the download link on this page you should not be using the fork, and do not abuse github issues for requests like this
