### ISSUE TITLE
Duplicated uniforms are not caught or typechecked properly

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#300]
This is because we insert into the locations / uniformNames map without checking whether they already have something with the given key

**Comment by elwinmartin** [comment]
This looks like this is still an issue, is it worth doing this?

I have made some changes to check the hashmap on a branch and was wondering if it was worth opening a PR for this.

**Comment by coderbot16** [comment]
Reopening until we release 1.1.4 with this fix.
