### ISSUE TITLE
Water has streaks down it

### ISSUE THREAD

**Issue by AlsoSylv** [IrisShaders/Iris#301]
Iris water :
![2021-05-27_21 29 51](https://user-images.githubusercontent.com/64978191/119916597-d2bffe80-bf32-11eb-99cf-a50bccb7a5e7.png)

Optifine water : 
![2021-05-27_21 32 13](https://user-images.githubusercontent.com/64978191/119916780-2894a680-bf33-11eb-8e4a-5993c2a83b94.png)

Both are using Sildurs extreme 

I have attached the logs from iris
[latest.log](https://github.com/IrisShaders/Iris/files/6557595/latest.log)

**Comment by yitzy299** [comment]
Is this with or without sodium?

**Comment by AlsoNiko** [comment]
Without, shadows branch and regular iris

**Comment by CodingRays** [comment]
I was able to reproduce the issue however for me optifine has the same behaviour.
![2021-06-27_23 27 46](https://user-images.githubusercontent.com/3766898/123559922-663d5700-d79f-11eb-8c0c-7ff0395e1358.png)

**Comment by coderbot16** [comment]
If that's the case, this doesn't seem like an Iris issue - but more like a shader pack issue.
