### ISSUE TITLE
Parse `const`-style directives from shader source files properly

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#31]
OptiFine/ShadersMod both allow shaderpacks to supply directives and configuration by declaring constants in the shader files. Here is an example: https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L388

```glsl
const float shadowDistance = 160.0f;
```

ShadersMod uses the following logic to locate that directive on each line:

1. Match any number of space/tab characters (including zero)
2. A `const` literal
3. Match any number of space/tab characters (including zero)
4. A `float` literal
    * Naturally this will differ for directives of different types - it could be `bool`, `int`, `vec4`, etc.
5. Match any number of space/tab characters (including zero)
6. A literal containing the name of the directive, in this case `shadowDistance`
    * Again, this will differ for each directive
7. Match any number of space/tab characters (including zero)
8. A literal `=` character
9. Match any number of space/tab characters (including zero)
10. Optionally match a negative sign (`-`), since these values can be negative
11. Any digit or `.` character. There must be at least one digit for the directive to be valid.
    * Technically ShadersMod will match `const float shadowDistance = .;` as well but obviously that isn't valid. It's okay for Iris to ignore that case.
12. Optionally match a float type suffix (`f`), for example the `f` in `160.0f`
    * Naturally this will differ for directives of different types. 
13. A literal `;` character
14. Any character (ShadersMod doesn't care about anything that comes after the semicolon)

Of course, the above logic is tailored to float values. Boolean, integer, vec4, and other types directives will need slightly different logic.

The above logic could be implemented as a regular expression, however it is also possible to implement it without regex. It's possible that an implementation that doesn't use regex could be more readable and understandable.

**Comment by OverlordsIII** [comment]
Are these restricted by type?
For example would optifine recognize any const that is named `shadowDistance` or would it have to specifically be a float?

**Comment by coderbot16** [comment]
ShadersMod appears to restrict by type, but I'm not sure what the behavior of OptiFine is. Perhaps shaders.txt has some information?

**Comment by OverlordsIII** [comment]
When they are explained in [shaders.properties](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L156-L190) they are not given a type but when shown in `Fragment Shader Configuration` in [shaders.txt](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L445-L494) it does have the specific type displayed, so it probably is?

**Comment by coderbot16** [comment]
Resolved in https://github.com/IrisShaders/Iris/commit/f1e27ad856bf11c0d4e988dd3589ac61c795f747
