### ISSUE TITLE
Correctly handle entries in block.properties involving blockstates

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#32]
OptiFine supports block states (instead of just blocks) in block.properties, we should too. This causes a lot of logspam with Sildur's and similar packs otherwise.

It's not 100% clear how to make this work seamlessly, consider the following examples:

```
block.0 = minecraft:stone_slab[half=top]
block.1 = minecraft:stone_slab[half=bottom]
```

```
block.0 = minecraft:stone_slab
```

We'll need to support both cases, because sometimes shaderpacks choose to differentiate based on state and sometimes they do not depending on the given block.

**Comment by OverlordsIII** [comment]
Sometimes pack's also use a colon to seperate the state from the block such as in sildurs, for example
`double_plant:half=upper` (taken directly from sildurs)

**Comment by coderbot16** [comment]
That's probably the correct syntax, I just guessed with the `[half=top]` based on how vanilla does it.

**Comment by OverlordsIII** [comment]
Also just noticed that optifine has `variants` for blocks as a specific blockstate, so you could do something like `double_stone_slab:variant=sandstone` in a shaderpack

**Comment by coderbot16** [comment]
That's only for pre-1.13, since that was how things worked before the Flattening.
