### ISSUE TITLE
Astralex, BSL, and Complementary do not work on MacOS with Sodium + Iris

### ISSUE THREAD

**Issue by DestinyTheGreat** [IrisShaders/Iris#324]
instacrash when I try these shaders:
- Astralex v20.0
- BSL v8.0.01
- Complementary v4.0.2

hs pid logs:

for Complementary   [hs_err_pid8579.log](https://github.com/IrisShaders/Iris/files/6612408/hs_err_pid8579.log)

for BSL   [hs_err_pid8808.log](https://github.com/IrisShaders/Iris/files/6612412/hs_err_pid8808.log)

for Astralex   [hs_err_pid8878.log](https://github.com/IrisShaders/Iris/files/6612415/hs_err_pid8878.log)

**Comment by coderbot16** [comment]
You should test with just Iris, and then also test with OptiFine, to see if the crash is only triggered by iris + sodium.

**Comment by DestinyTheGreat** [comment]
I tested with Iris being the only mod loaded, issue is still there

**Comment by DestinyTheGreat** [comment]
I'm closing this because it seems to be M1-only
