### ISSUE TITLE
Batched Entity Rendering causes snow villagers to become buff

### ISSUE THREAD

**Issue by heymanMC** [IrisShaders/Iris#325]
It seems the newest compile of iris (0.5.0-pre, compiled 6 hours ago) is causing my villagers to be "buff" (no sleeves). It even happens with no shaderpack selected, and only Iris as the mod (addition of sodium does not affect it). See screenshot and logs below.
**Screenshot:**
![2021-06-07_21 06 23](https://user-images.githubusercontent.com/38384673/121116840-6798e680-c7d4-11eb-93d9-d48531dce121.png)

**Log:**
https://paste.ee/p/YxcM0

**Comment by coderbot16** [comment]
Did this happen before https://github.com/IrisShaders/Iris/commit/b2ac8e0eef6769561162ecdab5c57b9d0d11fa73 ?

**Comment by coderbot16** [comment]
Another commit to test is https://github.com/IrisShaders/Iris/commit/95c42b0b8cf49da2d345e1dd30b3633ffffa3a3f, since that made changes to the order entity stuff is rendered in. If it only happens starting with that commit, then I'll probably need to give a much closer look to the rendering order of entities

**Comment by heymanMC** [comment]
> Did this happen before [b2ac8e0](https://github.com/IrisShaders/Iris/commit/b2ac8e0eef6769561162ecdab5c57b9d0d11fa73) ?

Reverting to this commit fixed the issue.
![2021-06-07_21 28 25](https://user-images.githubusercontent.com/38384673/121118653-7634cd00-c7d7-11eb-9516-9e5a8b2d2dc0.png)

**Comment by coderbot16** [comment]
Do you mean that reverting to the commit before https://github.com/IrisShaders/Iris/commit/b2ac8e0eef6769561162ecdab5c57b9d0d11fa73 fixes the issue, or reverting to https://github.com/IrisShaders/Iris/commit/b2ac8e0eef6769561162ecdab5c57b9d0d11fa73 itself fixes the issue?

**Comment by heymanMC** [comment]
> Do you mean that reverting to the commit before [b2ac8e0](https://github.com/IrisShaders/Iris/commit/b2ac8e0eef6769561162ecdab5c57b9d0d11fa73) fixes the issue, or reverting to [b2ac8e0](https://github.com/IrisShaders/Iris/commit/b2ac8e0eef6769561162ecdab5c57b9d0d11fa73) itself fixes the issue?

Reverting to https://github.com/IrisShaders/Iris/commit/b2ac8e0eef6769561162ecdab5c57b9d0d11fa73 fixes the issue

**Comment by heymanMC** [comment]
Also,


> Another commit to test is [95c42b0](https://github.com/IrisShaders/Iris/commit/95c42b0b8cf49da2d345e1dd30b3633ffffa3a3f), since that made changes to the order entity stuff is rendered in. If it only happens starting with that commit, then I'll probably need to give a much closer look to the rendering order of entity content

Reverting to https://github.com/IrisShaders/Iris/commit/95c42b0b8cf49da2d345e1dd30b3633ffffa3a3f does not fix the issue.

**Comment by coderbot16** [comment]
What about https://github.com/IrisShaders/Iris/commit/fc51335b1290d684c0f21b13f145aebffa48d805, the commit before the entity rendering changes?

**Comment by CrazyChaoz** [comment]
Is this Bug related?
![grafik](https://user-images.githubusercontent.com/19308955/123861353-5b153300-d927-11eb-9f1b-4510ad15bec2.png)
