### ISSUE TITLE
Many shaders do not work on MacOS

### ISSUE THREAD

**Issue by FwuffyPetsOwO** [IrisShaders/Iris#329]
On commit https://github.com/IrisShaders/Iris/tree/ff0f62e667e7193e6c99e6be167a7b0f27e307c6, shaders such as Xordev's DOF and Skylec worked properly. On commit https://github.com/IrisShaders/Iris/tree/2a74949a7e59a013b1495657fdb919bdacd571b4 and any later commit, trying to use these shaders results in this:

![2021-06-08_16 27 50](https://user-images.githubusercontent.com/65428450/121270415-8a7bd700-c876-11eb-9e50-585220fe564b.png)

**Comment by DestinyTheGreat** [comment]
Note that this does not occur when using Rosetta2 on M1

**Comment by coderbot16** [comment]
Issues with Iris on Apple M1 are no longer being investigated, we do not officially support Apple M1: https://github.com/IrisShaders/Iris/blob/trunk/docs/usage/drivers.md
