### ISSUE TITLE
Add "Old Hand Lighting" or similar option for Iris

### ISSUE THREAD

**Issue by heymanMC** [IrisShaders/Iris#331]
This option allows shaders with built-in hand lighting to work in the off-hand. Some users on the discord reported this option doesn't always work on optifine, so perhaps Iris could just implement a way for shaders to use the off-hand as well for built-in hand lighting.

**Comment by EminGT** [comment]
I think the main problem is that Iris doesn't support shaders on hand right now. So they end up looking incorrect in some situations. Especially with shaderpacks that do shader-based dynamic handheld lighting. The hand stays dark even when we are holding a light source
![image](https://user-images.githubusercontent.com/52270338/121430601-fa768400-c980-11eb-8507-451a3c72d287.png)

**Comment by heymanMC** [comment]
Hand lighting currently works in off-hand now.

**Comment by IMS212** [comment]
Implemented proper old hand lighting in https://github.com/IrisShaders/Iris/commit/f94c308b910cc8b2d3c81ea3389915b8040cdad8.
