### ISSUE TITLE
TAA can cause everything to vibrate starting from commit 4118057

### ISSUE THREAD

**Issue by williambl** [IrisShaders/Iris#332]
In Iris 1.0.0-rc1 with Sodium, everything appears to be very slightly vibrating. The problem appears worse when standing still.

These videos have other mods installed, but I have reproduced this with only Iris+Sodium (Iris alone seems to do it even worse, and shadows look patchy)

Shaders: Sildurs Vibrant Shaders v1.283 Extreme

https://user-images.githubusercontent.com/5115825/121354146-20b70800-c91e-11eb-8603-fd011ca873be.mp4

https://user-images.githubusercontent.com/5115825/121354152-23b1f880-c91e-11eb-9b0c-29cb753e1910.mp4

**Comment by gri573** [comment]
If your shader has an option for TAA, disable it

**Comment by williambl** [comment]
> If your shader has an option for TAA, disable it

Thanks, that fixes it.

**Comment by williambl** [comment]
A `git bisect` suggests that 4118057 is the first commit affected.

**Comment by gri573** [comment]
this looks more like a consequence of currently unimplemented non-clearing buffers to me

**Comment by coderbot16** [comment]
This might be because the Iris SwapPass (needed for some non-clearing things) only copies the base texture level, and not the other mipmap levels, which would explain why it only appeared after mipmap support was added. Not sure how to easily copy the mipmap levels though.

**Comment by coderbot16** [comment]
I've been debugging this locally and was curious why it only seemed to happen with Sodium, then I remembered that it's just because Sodium is giving me way better FPS (the jitter is based on the frame counter)

**Comment by sachk** [comment]
I had this issue on BSL v8.0.01, but on v8.1 one of the TAA changes seems to have prevented this from happening.

**Comment by emmatebibyte** [comment]
turning off TAA doesn't fix this for me on 1.1.2 (1.17.1).
