### ISSUE TITLE
When using the replay mod, the rendered video will crash

### ISSUE THREAD

**Issue by law4x** [IrisShaders/Iris#333]
Iris:  1.16.5 rc-1
replaymod:  replaymod-1.16.4-2.5.2
It will crash with or without sodium
（The iris version without shadows works fine）
[crash-2021-06-09_20.40.24-client.txt](https://github.com/IrisShaders/Iris/files/6623827/crash-2021-06-09_20.40.24-client.txt)

**Comment by coderbot16** [comment]
This appears to be an issue with running replaymod on java 16, and not a bug in Iris: https://github.com/ReplayMod/ReplayMod/issues/520
