### ISSUE TITLE
Some things in the world are not rendered with the correct shader programs

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#34]
* [x] Particles
* [ ] Entities
* [ ] Block entities
* [x] Water
* [ ] ItemPickupParticle
* [ ] Selection boxes
* [ ] Clouds
* [ ] Rain
* (I'm probably forgetting things, but these come to mind)

**Comment by IMS212** [comment]
water? last I checked that wasn’t working right

**Comment by coderbot16** [comment]
Fixed in newer versions of Iris
