### ISSUE TITLE
Unimplemented: "seperateAo" setting in shaders.properties

### ISSUE THREAD

**Issue by EminGT** [IrisShaders/Iris#340]

**Comment by EminGT** [comment]
This causes quite a bit of issues in Complementary, thanks to it's IntegratedPBR relying on specific texture colors

Anvils get water shading
![image](https://user-images.githubusercontent.com/52270338/121442093-a0cb8500-c993-11eb-9a26-f25de2b67399.png)

Nether stems get weird emission
![image](https://user-images.githubusercontent.com/52270338/121442118-b17bfb00-c993-11eb-9d09-7e5f9f82b1be.png)

Grass block sides get weird sun reflections (I might workaround this one on my end though)
![image](https://user-images.githubusercontent.com/52270338/121442132-b771dc00-c993-11eb-80bd-ed7223400d95.png)

**Comment by thedocruby** [comment]
Also discussed in #222
