### ISSUE TITLE
Time jumps from 23200 to a weird time state until 24000

### ISSUE THREAD

**Issue by EminGT** [IrisShaders/Iris#344]
Condition: 1.16.5 Iris + Sodium + Complementary

It's hard to describe the problem without screenshots.

Here I am watching the sunrise at time 23200:
![image](https://user-images.githubusercontent.com/52270338/121440799-4b8e7400-c991-11eb-9d1e-39d1582b8d86.png)

Here is what I'm seeing exactly two seconds after the first screenshot:
![image](https://user-images.githubusercontent.com/52270338/121440835-5812cc80-c991-11eb-9e12-0df3731311bd.png)

**Comment by Justsnoopy30** [comment]
Fixed by #433
