### ISSUE TITLE
Chunks are incorrectly culled from the shadow program during sunrise/sunset at the direction of the sun

### ISSUE THREAD

**Issue by EminGT** [IrisShaders/Iris#345]
Conditions: 1.16.5 Iris + Sodium + Complementary
Render Distance: 16, Time: 1

Chunks seem to be culled from the shadow program a bit too much when the sun angle is pretty low

Iris:
![image](https://user-images.githubusercontent.com/52270338/121441489-965cbb80-c992-11eb-8118-4ed436bfc9d6.png)

Optifine:
![image](https://user-images.githubusercontent.com/52270338/121441531-abd1e580-c992-11eb-96b3-319b21a7b139.png)

**Comment by AlsoNiko** [comment]
Sounds like it would be fixed in the same way #317 would be, marking it the same way

**Comment by thedocruby** [comment]
This actually seems like it might be related to Iris's temporary shadow render distance restrictions, in which case it should be fixed as soon as possible.

**Comment by coderbot16** [comment]
> This actually seems like it might be related to Iris's temporary shadow render distance restrictions

Iris does not currently have any of that code anymore.

I'll give the frustum culling code a closer look. Maybe its interacting weirdly with the distortion that many shader packs do to the shadow map.

**Comment by coderbot16** [comment]
This was fixed in https://github.com/IrisShaders/Iris/compare/6949d4c0ebce%5E...4cb84d6c57fa, a fixed version of shadow culling will be coming in Iris 1.1.2.
