### ISSUE TITLE
[1.17] player is transparent and very colorful

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [IrisShaders/Iris#346]
I am using the 1.17 release of Iris (installed from the iris loader) and sildurs extreme volatile lighting, and the player is rendered somewhat transparent with some color glitching. Here are some images showing this effect:

![image](https://user-images.githubusercontent.com/66212375/121442170-1bc37a00-c959-11eb-8def-c8d637e26079.png)

![image](https://user-images.githubusercontent.com/66212375/121442264-41508380-c959-11eb-8e29-345e2cda4688.png)

![image](https://user-images.githubusercontent.com/66212375/121442287-5200f980-c959-11eb-916a-23f03540cafb.png)

**Comment by DUDEbehindDUDE** [comment]
also is an issue with items entities are holding
![image](https://user-images.githubusercontent.com/66212375/121448372-82e72b80-c965-11eb-9047-82dd79871038.png)

**Comment by Reeses-Puffs** [comment]
LSD players and items should be a feature :yeefuckinhaw:

**Comment by coderbot16** [comment]
Closing in favor of https://github.com/IrisShaders/Iris/issues/819 which contains more information.
