### ISSUE TITLE
Shaders are not able to be disabled in the menu.

### ISSUE THREAD

**Issue by AlsoNiko** [IrisShaders/Iris#351]
There have been quite a few reports of the disable button being broken. Possibly due to the recent pr? Not sure but adding it to the github to make sure it gets addressed

**Comment by Quizer9O8** [comment]
I can confirm this too as I'm unable as well to do this with shaders in general.

**Comment by thedocruby** [comment]
I can also confirm this, and I will work on finding the cause asap

**Comment by coderbot16** [comment]
Afaik Justsnoopy30 might have figured it out?
