### ISSUE TITLE
error with 1.16.5

### ISSUE THREAD

**Issue by LOLBRUHNICE** [IrisShaders/Iris#355]
when i run iris with 1.16.5 i got this err:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'!
Exit Code: -1

**Comment by AlsoNiko** [comment]
Please provide a log and crash report

**Comment by LOLBRUHNICE** [comment]
[crash-2021-06-10_15.01.12-client.txt](https://github.com/IrisShaders/Iris/files/6629040/crash-2021-06-10_15.01.12-client.txt)

**Comment by thetek42** [comment]
You have the wrong version of Sodium installed. (`Caused by: java.lang.IllegalStateException: You do not have a compatible version of Sodium installed! You have 0.1.0 but 0.2.0_IRIS-SNAPSHOT is expected`).

Iris needs a custom fork of Sodium to work, and you have the regular Sodium installed.

**Comment by LOLBRUHNICE** [comment]
ok, tysm
