### ISSUE TITLE
Shadows that shouldn't appear when rendering with litematica

### ISSUE THREAD

**Issue by Sanluli36li** [IrisShaders/Iris#358]
Only the shadow of the schematic is rendered, not the schematic
It should be said that both the schematic and the shadow should be rendered, or neither should be rendered, or only the schematic should be rendered

![2021-06-10_16 48 55](https://user-images.githubusercontent.com/5201743/121495055-de6bf480-ca0b-11eb-92a6-d2e601c70796.png)
![2021-06-10_16 49 15](https://user-images.githubusercontent.com/5201743/121495080-e166e500-ca0b-11eb-8385-f9b5b0a8c825.png)

Mods:
iris-mc1.17-1.0.0-beta1.jar
litematica-fabric-1.17.0-0.0.0-dev.20210608.211719.jar
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1.jar

**Comment by Sanluli36li** [comment]
in 1.16.5: the content of the schematic is not visible, the border of the schematic is visible, and the shadow is not visible

iris-mc1.16.5-1.0.0.jar with built-in sodium
litematica-fabric-1.16.4-0.0.0-dev.20210420.200000.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.6.jar

**Comment by cm-360** [comment]
Can confirm the issue still exists in 1.18.

Sodium Only
![image](https://user-images.githubusercontent.com/31625347/145333252-51ae1296-547b-49da-a909-7c2730eb29da.png)
Iris + Complementary Shaders v4.3.2
![image](https://user-images.githubusercontent.com/31625347/145333330-6be7cec9-0d9f-49ec-908e-e39aa6dd5193.png)
Iris + Sildurs Vibrant Shaders High v1.29
![image](https://user-images.githubusercontent.com/31625347/145333422-3bb28ea2-c60c-4c90-bfd5-348ef3abdece.png)
Iris + No Shaders (Before refreshing Litematica rendering)
![image](https://user-images.githubusercontent.com/31625347/145333498-1d4c7c90-b8a6-4202-8a2e-53a2bcff5160.png)
Iris + No Shaders (After refreshing Litematica rendering)
![image](https://user-images.githubusercontent.com/31625347/145333525-e70bc270-112e-4497-b541-d1591b3b4977.png)

Note: Images have been downscaled to fit within the GitHub 10MB limit.

Mod versions:
iris-mc1.18-1.1.3.jar
litematica-fabric-1.18.0-0.0.0-dev.20211203.013300.jar
malilib-fabric-1.18.0-0.10.0-dev.26.jar
sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

**Comment by coderbot16** [comment]
This should be fixed on 1.17+ as of Iris 1.2.4 with the inclusion of https://github.com/IrisShaders/Iris/commit/4ba30d226d84f200c5d04431639b519d8e63cf84. Let me know if it still happens.
