### ISSUE TITLE
Lighting issue on Sildurs Extreme VL

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#36]
The light moves when you move

**Comment by maxigator** [comment]
It only moves when using view bobbing and walking on the ground

**Comment by coderbot16** [comment]
I think this needs to be re-tested—I recall a similar issue with view bobbing + walking on the ground that I fixed with BSL recently.

**Comment by coderbot16** [comment]
This also happens on Extreme (non VL) and is fixed when view bobbing is disabled.
