### ISSUE TITLE
End portals do not render correctly

### ISSUE THREAD

**Issue by Skyterix1991** [IrisShaders/Iris#361]
Beacons using Sildur's Vibrant shaders v1.29 Extreme-VL are missing the beams.

![2021-06-10_13 45 32](https://user-images.githubusercontent.com/33985207/121519637-3a298400-c9f2-11eb-9e0e-18e48c6b71b6.png)
![2021-06-10_13 45 41](https://user-images.githubusercontent.com/33985207/121519641-3ac21a80-c9f2-11eb-82e8-137f4d12abc6.png)

**Comment by Skyterix1991** [comment]
End portals are also missing, both in overworld and end.

![2021-06-13_13 21 47](https://user-images.githubusercontent.com/33985207/121805247-b9b19000-cc4a-11eb-9ce1-6872b5d1e003.png)
![2021-06-13_13 23 54](https://user-images.githubusercontent.com/33985207/121805250-bae2bd00-cc4a-11eb-9474-db8e28706208.png)

**Comment by CrazyChaoz** [comment]
Beacons don't work at all for me as soon as any shader is applied.

![grafik](https://user-images.githubusercontent.com/19308955/123121406-6ce96880-d445-11eb-9e7c-7d404afbaef2.png)
![grafik](https://user-images.githubusercontent.com/19308955/123121469-7a065780-d445-11eb-876c-fb37f70e4767.png)
![grafik](https://user-images.githubusercontent.com/19308955/123121569-8d192780-d445-11eb-9cb3-bb4399c01ada.png)

**Comment by ruvaldak** [comment]
![2021-06-23_11 18 42](https://user-images.githubusercontent.com/15901769/123123464-da30d580-d414-11eb-89b9-adbf411f16e1.png)

No issue here.

**Comment by CrazyChaoz** [comment]
What version are you on ?

**Comment by IMS212** [comment]
End portals (and possibly beacon beams) are already fixed in the latest 1.17 commit.

**Comment by coderbot16** [comment]
End portals aren't fully fixed still, but they should be in a similar state to 1.16

**Comment by amitojsingh366** [comment]
what's the status on this?

**Comment by AlsoNiko** [comment]
Beacon beams should work just fine in 1.16 but neither version renders end portals correctly

**Comment by IMS212** [comment]
Fixed by https://github.com/IrisShaders/Iris/commit/f943eeea8731b609d1632e9f99f8b4e10514ceb8. End portals still don't render correctly on many shaders, but they usually become a solid color instead of completely invisible.

**Comment by IMS212** [comment]
This should be solved by now, with the blockEntityId addition.
