### ISSUE TITLE
When I try to create a new world, my game crashes and says this: java.lang.NullPointerException: Unexpected error Exit Code: -1

### ISSUE THREAD

**Issue by JoseBlackYT** [IrisShaders/Iris#363]
Crash log when trying to create new world:

https://pastebin.com/ajYmKhWA

**Comment by AlsoNiko** [comment]
hi! could you provide a log and mods list?

**Comment by JoseBlackYT** [comment]
Hey! I provided a log, but here it is: https://pastebin.com/ajYmKhWA

I am also just using sodium and iris!

**Comment by TheRealM18** [comment]
> Hey! I provided a log, but here it is: https://pastebin.com/ajYmKhWA
> 
> I am also just using sodium and iris!

you are not providing any helpful information there.  there is no mod list, no reference to iris, and all it says is using fabric....that is a broken up crash log, that you have edited because the crash logs should show a lot more information.

**Comment by JoseBlackYT** [comment]
Hey, i'm closing this soon but i did not edit anything, i just clicked the "view crash report" button in minecraft. Do not say I edited it, because i'd have no idea how to
