### ISSUE TITLE
crash while launching the game(without custom launcher):  The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'iris'! Exit Code: -1 (crash log in comments)

### ISSUE THREAD

**Issue by JoseBlackYT** [IrisShaders/Iris#365]
Version: 1.16.5

Mods used: Sodium, Phosphor, Lithium and Iris.

Specs: Core i3, 4 gb ram and intel hd graphics 620

Crash log:

https://pastebin.com/sSa2F2FX

**Comment by AlsoNiko** [comment]
Hey, please don't provide duplicate tickets. We need more than just a crash log to help with this, please provide the latest.log file from when this happened

**Comment by TheRealM18** [comment]
That is not a full crash log.  A full crash log shows a lot more detail than that.  If you want full support to figure out what is wrong, provide a full one, not a edited one.  If you would like to see an example of a crash log, I could try to overload my ram, and provide you with an example.

**Comment by JoseBlackYT** [comment]
Yes, I'd like an example. I just clicked on the "crash log" button on the crash popup.

**Comment by AlsoNiko** [comment]
in your .minecraft folder there will be a sub folder called "logs" there will be a file named "latest.log" at the top or bottom that we need

**Comment by JoseBlackYT** [comment]
Alright, will get it in pastebin in no time, ty.

**Comment by JoseBlackYT** [comment]
Not sure if it should have more lines, but I did as you said. https://pastebin.com/Gnfi2qMX

**Comment by AlsoNiko** [comment]
You have sodium 0.1 installed, please remove it and rerun the installer, you don't need to add sodium, the installer does it for you

**Comment by JoseBlackYT** [comment]
Oh, thank you. I'll try that and keep you updated

**Comment by JoseBlackYT** [comment]
Hey! It works but it still crashes when I click on the video settings. Latest log: https://pastebin.com/EfdyYUBj

**Comment by JoseBlackYT** [comment]
Alright, will try

**Comment by JoseBlackYT** [comment]
Accidentally closed, mb

**Comment by JoseBlackYT** [comment]
Nope. Didn't work, do you need the latest.log?

**Comment by AlsoNiko** [comment]
No, I'm not sure why it's not working, it seems I can't help with that part

**Comment by AlsoNiko** [comment]
It doesn't require fabric api

**Comment by JoseBlackYT** [comment]
Alright. Thank you anyways, i'll try to figure it out
