### ISSUE TITLE
Lots of 3D models cause java.lang.IllegalArgumentException: Not enough space in destination buffer

### ISSUE THREAD

**Issue by xieve** [IrisShaders/Iris#376]
I discovered this while having [Default 3D High](https://beta.know2good.com/packs/high) enabled, which has 3D models for cobblestone. Moving by a tiny bit in regions with lots of cobble caused heavy lags and then this crash. I know this is an edge case, and I have removed the resource pack for now. However, this crash doesn't occur on Vanilla, which seems to lag less even with slow movement. If I move fast, Vanilla freezes, but way later than this crash had occurred. I think Iris doesn't cull 3d faces currently, correct? Another really useful albeit probably more tedious measure would be a kind of LOD system for 3D resource packs.
[crash log](https://github.com/IrisShaders/Iris/files/6641972/crash-2021-06-12_11.15.45-client.txt)

**Comment by coderbot16** [comment]
This appears to be a bug in Sodium, I've forwarded the report there.

**Comment by DragonEggBedrockBreaking** [comment]
https://github.com/CaffeineMC/sodium-fabric/commit/d43017e95dc0507d16b4475b5ddaa6ae09daf67f

**Comment by IMS212** [comment]
Should be fixed in the fork, closing. Feel free to reopen if you are able to reproduce on the latest commit
