### ISSUE TITLE
[BUG] Game crashes after changing windows in 1.17

### ISSUE THREAD

**Issue by Mr-Waterscout** [IrisShaders/Iris#382]
This has occurred at least two times for me now, when I switch to discord the game crashes when I attempt to switch back to the game.

**Comment by NoComment1105** [comment]
Do you have a crash report?

**Comment by Mr-Waterscout** [comment]
no, I'll get one

**Comment by Mr-Waterscout** [comment]
![image](https://user-images.githubusercontent.com/73510808/121793243-0b5a0c00-cbb2-11eb-8b48-5eaee5bf39fb.png)
This was all I got, I didn't see a way to open the crash report.

**Comment by NoComment1105** [comment]
Please look in #iris-support in the discord

**Comment by NoComment1105** [comment]
https://fabricmc.net/wiki/player:tutorials:logs_ml:windows

**Comment by Mr-Waterscout** [comment]
[crash-2021-06-12_12.24.42-client.txt](https://github.com/IrisShaders/Iris/files/6643174/crash-2021-06-12_12.24.42-client.txt)

**Comment by IMS212** [comment]
You have to use the fork of sodium (or remove sodium if using the version of iris on curseforge/modrinth)

**Comment by IMS212** [comment]
Looking at it again, Iris doesn’t support sodium on 1.17 currently.

**Comment by Mr-Waterscout** [comment]
Wrong report then, I wasn't using sodium

**Comment by Mr-Waterscout** [comment]
I guess it didn't make a report, because that was the only crash report I had today.

**Comment by NoComment1105** [comment]
Could you try getting a log instead?
same place just the logs folder instead

**Comment by Mr-Waterscout** [comment]
[2021-06-12-7.log.gz](https://github.com/IrisShaders/Iris/files/6643182/2021-06-12-7.log.gz)

**Comment by NoComment1105** [comment]
Could you upload latest.log instead?

**Comment by Mr-Waterscout** [comment]
yeah

**Comment by Mr-Waterscout** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/6643184/latest.log)

**Comment by AlsoNiko** [comment]
Hi! Do you mind me asking which shader you're trying to use?

**Comment by AlsoNiko** [comment]
Nevermind

**Comment by AlsoNiko** [comment]
Can you try loading into a world with shaders disabled and see what happens?

**Comment by Mr-Waterscout** [comment]
It still crashed when I only quit from the title screen, but I'll try it

**Comment by Mr-Waterscout** [comment]
I tried it, same thing
[latest.log](https://github.com/IrisShaders/Iris/files/6643197/latest.log)

**Comment by AlsoNiko** [comment]
Hmm, I'm gonna need a crash report instead of a log, I can't seem to find any errors, so unless this is an exit code 0 it should have more info in the crash report

**Comment by Mr-Waterscout** [comment]
This is an exit code 0

**Comment by AlsoNiko** [comment]
hmmm, try removing everything (including fabric api) that isn't iris and see if it still happens

**Comment by Mr-Waterscout** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/6643208/latest.log)
Removed everything else, still happens

**Comment by AlsoNiko** [comment]
Hmmm, I'm gonna have to mark this as a bug for now, because I can't figure out the error

**Comment by coderbot16** [comment]
Are you sure that this doesn't happen with vanilla? Your launcher_log.txt might contain more information, but I'm not seeing any clear evidence that this is an Iris bug.

**Comment by Mr-Waterscout** [comment]
This does not happen with vanilla 1.17

**Comment by valetzx** [comment]
> This does not happen with vanilla 1.17

plz where you download the iris1.17 or the install？ when i opened the install it says my Internet not connected，can you upload a cloud and share with me？ thanks

**Comment by NoComment1105** [comment]
This is not the place for that. Take it to the discord or another location please.

**Comment by Mr-Waterscout** [comment]
I was able to get a crash report somehow
[hs_err_pid26024.log](https://github.com/IrisShaders/Iris/files/6651518/hs_err_pid26024.log)

**Comment by Mr-Waterscout** [comment]
It fixed itself, closing issue now
