### ISSUE TITLE
Weird "line" in water with some shaders

### ISSUE THREAD

**Issue by heymanMC** [IrisShaders/Iris#388]
![2021-06-14_11 02 18](https://user-images.githubusercontent.com/38384673/121931226-9517ef80-cd00-11eb-918c-1961c13e2d1a.png)

Shaders that cause this (not exhaustive):
- Beyond Belief
- SEUS Renewed
- SEUS v11

Here is the log when enabling Beyond Belief:
[BB.txt](https://github.com/IrisShaders/Iris/files/6650114/BB.txt)

**Comment by satyrnsstuff** [comment]
Not sure, but it might have to do with the lack of support of seperateAo, as it's caused similar issues on different blocks for me.
