### ISSUE TITLE
opening video settings crashes minecraft

### ISSUE THREAD

**Issue by Malavolence** [IrisShaders/Iris#392]
i have about 20 other mods installed. when i open video settings (both in start menu and in game) it crashes.
[crash-2021-06-15_18.48.13-client.txt](https://github.com/IrisShaders/Iris/files/6657334/crash-2021-06-15_18.48.13-client.txt)

Mods:

- (i think it might be one of these):

- Better F3
- Iris (could be the mod itself, idk)
- lamb dynamic lights
- mod menu
- phosphor
- lithium
- sodium-extra

- (probably none of these):

- actually unbreaking
- ambient environment
- biomes you'll go + addon
- carpet + extra
- complete bone meal
- consistency+
- darkness
- dawn
- disable custom worlds advice
- dungeonsarise
- chunk pregen
- identity
- mo structures
- okzoomer
- particle rain
- replanter
- repurposed structures
- timber
- valhesia structures
- vanilla plus biomes
- world edit

**Comment by NoComment1105** [comment]
You may have an outdated version of sodium extra that is incompatible with the Iris fork. Please look at updating

**Comment by AlsoNiko** [comment]
The most consistent and tested fork of sodium extra is pinned in #iris-support in the iris discord
