### ISSUE TITLE
"Very Low" shadow resolution on Enhanced Default creates these weird lines on blocks

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#393]
![2021-06-15_18 54 53](https://user-images.githubusercontent.com/75493688/122093341-486d0b00-ce0b-11eb-9207-03c6515043a4.png)

**Comment by C-Stew** [comment]
This is an issue with the shaderpack itself and not with Iris. It happens when using Optifine as well.

**Comment by edwloef** [comment]
Oh alright, I wasn't aware of this.
