### ISSUE TITLE
Simplicissimus shader doesn't render most terrain.

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#394]
https://www.curseforge.com/minecraft/customization/simplicissimus-shader
![2021-06-15_19 42 06](https://user-images.githubusercontent.com/75493688/122099070-e19f2000-ce11-11eb-857f-a113e2ad2a62.png)

**Comment by coderbot16** [comment]
Superseded by https://github.com/IrisShaders/Iris/issues/1030
