### ISSUE TITLE
Inverted colour box placed over mod mob

### ISSUE THREAD

**Issue by JoeyHamlet** [IrisShaders/Iris#395]
Graphical bug (box with inverted colours) appears when using most shaders around the Firefly mob from Better Nether. Only exception I found so far was Sildur's Enhanced Default. As the bug concerns modded mobs I doubt it'll be high on priorities to fix but asked around and people told me I should report it regardless. Not sure how to get ahold of logs atm but if people need them to delve deeper into the issue let me know and I'll figure it out.

Sildur's Enhanced Default (v1.12):
![2021-06-16_16 31 19](https://user-images.githubusercontent.com/43111443/122238304-50d34d80-cec0-11eb-9460-6b967ffde332.png)

Sildur's Vibrant Shaders Extreme-VL (v1.283):
![2021-06-16_16 07 16](https://user-images.githubusercontent.com/43111443/122237786-e4f0e500-cebf-11eb-88cb-36b2aa15a0ef.png)

**Comment by pajicadvance** [comment]
Relevant line in the log:
`[main/WARN]: Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: firefly`

**Comment by AlsoNiko** [comment]
Fixed in latest commits
