### ISSUE TITLE
Black screen with nostalgia shaders

### ISSUE THREAD

**Issue by Diztend** [IrisShaders/Iris#399]
nothing appears when using nostalgia shaders

**Comment by Mr-Waterscout** [comment]
Nostalgia isn't supported yet, but the black screen is weird, because when I try nostalgia, it loads the game without shaders.

**Comment by AlsoNiko** [comment]
That's likely because of the shader fall back system, it's there to try and prevent people from crashing and seeing black screens from unsupported shaders.

**Comment by Mr-Waterscout** [comment]
Yeah I used to get a black screen, but with the starline fork it just loads without the shaders with unsupported shaders

**Comment by AlsoNiko** [comment]
That isn't starline specific, it was just added to both branches last night

**Comment by Mr-Waterscout** [comment]
Oh okay

**Comment by farhan403** [comment]
chocapic13's shaders aren't supported yet. but v5 and v6 should work properly.

**Comment by coderbot16** [comment]
Superseded by https://github.com/IrisShaders/Iris/issues/1030
