### ISSUE TITLE
No fog with Sildur's

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#40]
Should figure out what's going on

**Comment by coderbot16** [comment]
Apparently it is broken in OptiFine too after 1.14.

**Comment by hYdos** [comment]
concern

**Comment by IMS212** [comment]
concen

**Comment by coderbot16** [comment]
Iris now appears to support fog in Sildur's. It doesn't have the same chunk-hiding fog like vanilla, but it's more of a subtle effect.
