### ISSUE TITLE
Feature request: loading shaders from resource packs

### ISSUE THREAD

**Issue by undnull** [IrisShaders/Iris#405]
Would be cool to have an option to load shaders from active resource packs along with a separate shaderpack system...  

_It is a resource pack after all, it should and does change how the game looks and feels_

**Comment by coderbot16** [comment]
Sorry, but I don't think we will be implementing this. Shader packs are intentionally separated from the resource pack system for fast reloading times, and tying ourselves to the resource pack system would prevent us from maintaining that separation. Also, it would be awkward to mix our shader selection GUI with the vanilla resource pack system. Finally, unlike resource packs, shader packs cannot be combined - only one shader pack can be loaded at a time. Given these reasons, I don't think it would make sense for us to implement this - though others are free to investigate it on their own time.

**Comment by undnull** [comment]
Aye fair enough
