### ISSUE TITLE
Iris renders Minecraft's default shadows in addition to the shaderpacks shadows

### ISSUE THREAD

**Issue by Firlaev-Hans** [IrisShaders/Iris#407]
![2021-06-19_14 37 59](https://user-images.githubusercontent.com/61254500/122643783-119c3b00-d112-11eb-919e-0f185f8b9141.png)
As you can see in this picture, on the right there's the shadow rendered by the shader pack (Sildurs Enhanced Default in this case), while on the left there's the shadow of the same structure, which looks like the default Minecraft lighting system.

I am using Arch Linux and an AMD RX580 GPU and the open source Mesa 21.1.2 drivers (RadeonSI), OpenJDK 16, MultiMC 0.6.12, Fabric 0.11.6.
I might try this later on another computer which also runs Linux but has an NVIDIA GPU (GTX 1060) with proprietary drivers.

I noticed the same issue on:
- different shaderpacks: Sildurs Enhanced Default, Sildurs Vibrant shaders, SEUS Renewed
- Different versions of Iris: The 1.0.0 release on Github with and without Sodium, the latest build of Iris and Sodium for MC 1.16.5, the latest build of Iris for MC 1.17.
- With or without these additional mods: Indium, Lithium, Phosphor (and Sodium of course)
- With the Mesa 21.1.2 drivers and Mesa-git as well as the latest proprietary AMDGPUPRO OpenGL drivers
- With and without the environment variable `force_glsl_extensions_warn=true` that is required for some shaders with Mesa

However, the same shaderpacks work just fine in Optifine.

Here's the log:
[latest.log](https://github.com/IrisShaders/Iris/files/6680769/latest.log)
(Edit: I just looked at the log again, you can probably ignore most OpenGL errors up to line 2023 because apparently I started the game with SEUS PTGI, which isn't known to work correctly anyways and had totally different issues, and only at line 2023 did I switch to SEUS Renewed which is supposed to work fine but doesn't for me)

**Comment by Old-Mo2021** [comment]
We all know how bad AMD graphics are in optifine, so hopefully Iris will optimize for AMD graphics

**Comment by edwloef** [comment]
This happens to me with Enhanced Default on a GTX 950M as well, so it's definitely not AMD-specific.
![2021-06-20_19 38 22](https://user-images.githubusercontent.com/75493688/122683388-1854ac00-d1ff-11eb-861f-d0d0c094ac94.png)

**Comment by edwloef** [comment]
May not be the same issue, looking back, since their shadows seem a lot clearer than what I'm seeing, so I might just be seeing the vanilla AO.

**Comment by coderbot16** [comment]
I'm pretty sure that this happens on OptiFine too, this is behavior controlled by the shader pack. You should take a screenshot on both Iris and OptiFine at the same spots just to be sure. If everything matches up then this isn't an Iris issue

**Comment by coderbot16** [comment]
This isn't an Iris issue, this is a shader pack issue. Shader packs force there to be shadows where there is low skylight to prevent light from leaking into caves. [While I would like to make this workaround unnecessary](https://github.com/IrisShaders/Iris/issues/317), it is entirely something implemented in the shaderpack, Iris doesn't really have control over it.

Here, it is visible on OptiFine:
![image](https://user-images.githubusercontent.com/22420959/132032936-b7c19071-ca77-4f18-9e84-f676f53009a5.png)
