### ISSUE TITLE
Complementary Shaders don't compile on some systems

### ISSUE THREAD

**Issue by DestinyTheGreat** [IrisShaders/Iris#408]
On Linux and Intel Mac, Complementary Shaders don't compile and fallback to no shader

**Comment by AlsoNiko** [comment]
Please note this is a 1.16.5 bug, and if someone could add logs etc that would be great

**Comment by Rohtea** [comment]
Linux (Pop OS) Ryzen 5600x, 5700xt
[latest.log](https://github.com/IrisShaders/Iris/files/6685934/latest.log)
1.16.5 just crashes when trying to load complementary
[latest.log](https://github.com/IrisShaders/Iris/files/6685947/latest.log)
1.17 didn't crash but fails to compile

**Comment by coderbot16** [comment]
Appears to just be an issue with the shader patching code. Should be feasible to fix but will require some small code restructuring.

**Comment by DestinyTheGreat** [comment]
fixed in latest commit
