### ISSUE TITLE
Minecraft start loop, when Iris combined with Conjuring mod

### ISSUE THREAD

**Issue by hello6557** [IrisShaders/Iris#410]
Hey, stumbled on this while installing Iris on ['All of Fabric', v.2.8.4](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3). Minecraft would load up until title screen, I wouldn't be able to click anything, as if it had frozen up, and then it would load the game (loading screen) again, and repeat.
Isolated this to the [Conjuring](https://www.curseforge.com/minecraft/mc-mods/conjuring) mod.

**Comment by yitzy299** [comment]
Please provide logs and ask for help on the discord
