### ISSUE TITLE
Key binding conflict with litematica

### ISSUE THREAD

**Issue by obp3ter** [IrisShaders/Iris#414]
If you bin the toggleAllRendering option from litematica to the same button as the toggle form Iris (I tied with K), then it doesn't toggle the shaders anymore.

**Comment by AlsoNiko** [comment]
I don't see how this would be considered a bug with Iris, that's just having overlapping keybinds

**Comment by AlsoNiko** [comment]
Closing this because this is not a bug with iris, as you can rebind the K toggle to something else and disable shaders that way

**Comment by obp3ter** [comment]
With other mods if you have the same key binding, it toggles both, but it's fine. I just tought that you might want to know about this.

**Comment by yitzy299** [comment]
Litematica allows configuration for keys, I believe iris does as well
