### ISSUE TITLE
FPS dropping to unplayable levels after ~2hours in game - Iris 1.17 Standalone

### ISSUE THREAD

**Issue by LunaSeashell00** [IrisShaders/Iris#419]
**Describe the bug**
FPS drops to about 3 or 5 FPS after playing in game for about 2 hours. 

**To Reproduce**
1. Load Iris 1.17 standalone
2. Pick a shader to use: I used complementary shaders latest dev 
[texture pack used: Compliance 32x]

**Expected behaviour**
Expecting FPS to stay reasonably stable and playable. 
Please find screenshots attached for:
SS1: When I first entered the world
SS2: After 2 hours, FPS suddenly drops and does not recover (so it is not a sudden drop and then goes back up to normal, but it stays at 3 FPS until I close the game). Note that this issue resolves itself when I relaunch the game. 
SS3: Screenshot of my video settings: note that I am not using crazy render distances and most settings are unchanged.

Please also note that I was not able to reproduce this in vanilla (no mods no shaders), same texture pack. 
![SS1_2021-06-21_11 44 47](https://user-images.githubusercontent.com/86081206/122823260-2103bb80-d2ad-11eb-8795-fae6b2618583.png)
![SS2_2021-06-21_13 14 11](https://user-images.githubusercontent.com/86081206/122823349-3d9ff380-d2ad-11eb-9f42-fb4b6fdada89.png)
![SS3_2021-06-21_16 09 39](https://user-images.githubusercontent.com/86081206/122823370-45f82e80-d2ad-11eb-94aa-c8fb3ab5da9a.png)

**Comment by coderbot16** [comment]
Could you run with something like [Spark](https://spark.lucko.me) and run the profiler a bit when the game starts to get really slow? Run `/spark profiler` to start and then `/spark profiler --stop` after some time (probably a minute). Would be helpful to see what exactly is taking up the time.

Does the issue also go away after a reload (press R) or does it persist?

**Comment by LunaSeashell00** [comment]
I will try with a profiler and report back in 2 hours ....

**Comment by LunaSeashell00** [comment]
Ran same test (forgot to load resource pack this time around but if anything that should help not worsen the problem). 

Please find Spark profiler results:
Log 1: This was capture when game was freshly started, no lag
https://spark.lucko.me/7IU2dOc7PK

Log 2: After 1 hour in game, fps started to become unstable, dipping to 20 or 30 then back to normal. This log was captured during one of such events
https://spark.lucko.me/mvpH0V2Bwg

Log 3: After ~2 hours in game, fps dropped to less than 5 fps and did not recover. This log was captured then. 
https://spark.lucko.me/k6sVzhjLoo

Further notes: 
- Tried to reload shaders by pressing R: didn't have any effect on fps
- Exited world and rejoined without restarting minecraft: didn't have any effect in fps -- fps was unplayable when rejoined the world

**Comment by coderbot16** [comment]
Interesting. It's possible that there's a memory leak related to some of the changes that Iris makes to entity rendering. Would be worth testing if this happens with Iris installed but with shaders disabled, if it does then that would help a lot in pinpointing the issue.

**Comment by LunaSeashell00** [comment]
Alright as per request, here are profiler results for Iris 1.17 standalone without shaders enabled at all:

Log 1: This was capture when game was freshly started, no lag
https://spark.lucko.me/uCzyjN1mEo

Log2: The fps loss started a bit earlier this time around: at 1 hour in game
https://spark.lucko.me/ZZun4trAh1

**Comment by coderbot16** [comment]
This does suggest that it has to do with the buffered entity rendering code leaking memory or not cleaning up after itself fully somehow. Thanks for the testing.

**Comment by mallllllll** [comment]
I have met several similar situation before.

**Comment by griffin4cats** [comment]
I believe I had the same issue in 1.16.5 as well.

**Comment by SpacyHorse01** [comment]
Did anyone manage to solve this for 1.17?

**Comment by IridiumFlareDev** [comment]
Pretty sure this is still the same memory leak issue since once ram is full the game starts dropping frames and eventually will crash.
How long it take for that to happen has to do with how many different chunks and entitys were loaded and how much ram you have.

**Comment by Danonymos** [comment]
hi any update on memory leak issue ? its really unplayable

**Comment by NoComment1105** [comment]
> hi any update on memory leak issue ? its really unplayable

It's being worked on. Do not spam our tracker with "fix when" comments, it's highly unhelpful

**Comment by IMS212** [comment]
This should be fixed by https://github.com/IrisShaders/Iris/commit/2c1c27eee9626f7c75fe6b185ae603a56e1e2994.

**Comment by AdamBrezik** [comment]
Hello, I'm having the exact same issue.
https://spark.lucko.me/Gtz3HaYFK1
If anything else is required, like creating a new issue, please let me know.
Thank you.
