### ISSUE TITLE
"Stripped Warped Hyphae" Blocks Display Artifacts when using Complementary Shaders in Iris 1.17 Standalone

### ISSUE THREAD

**Issue by LunaSeashell00** [IrisShaders/Iris#420]
**Describe the bug**
Stripped Warped Hyphae block has visible artifacts on the lower part of the block texture when placed (see screenshot). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch Iris 1.17 standalone
2. Load Complementary shaders V4.1_dev1
3. Take out some Stripped Warped Hyphae blocks and place them in game, during day time

**System (please complete the following information):**
 - OS: Win10
 - GPU: GTX1660
 - Minecraft Version: 1.17

**Additional context**
- Switched to BSL and problem was not observed. So thus far it only happens with Complementary.
- Tested in Optifine G8 in MC 1.16 and this could not be replicated.

**Screenshots**
![Stripped Warped Hyphae](https://user-images.githubusercontent.com/86081206/122837859-d856fd00-d2c2-11eb-9bfa-4e02e775990a.png)

**Comment by coderbot16** [comment]
This was fixed some time ago and is no longer an issue as of Iris 1.1.2:

![image](https://user-images.githubusercontent.com/22420959/134788397-fae964af-a2e2-4863-9562-3058315f88a1.png)
