### ISSUE TITLE
“BetterNether”模组中的“萤火虫”在iris（sodium）下不显示

### ISSUE THREAD

**Issue by DSRoie** [IrisShaders/Iris#422]
![image](https://user-images.githubusercontent.com/74242244/122864719-b8bde400-d357-11eb-83fc-e91bd90815ef.png)
使用bsl光影，不使用光影下萤火虫不可见

**Comment by DestinyTheGreat** [comment]
which version of BetterNether do you have?

**Comment by junjie1475** [comment]
这是一个已知的bug

**Comment by DSRoie** [comment]
> which version of BetterNether do you have?

5.0.7

**Comment by DSRoie** [comment]
> 这是一个已知的bug

yeah，thanks

**Comment by AlsoNiko** [comment]
Fixed in latest commits

**Comment by DSRoie** [comment]
> 固定在最新的提交

thanks very much.
Although it’s a bit discordant, it’s nice to meet a Oneshot fan.
