### ISSUE TITLE
Streaks on the side of grass when using comp shaders

### ISSUE THREAD

**Issue by AlsoNiko** [IrisShaders/Iris#424]
Streaks in side of grass when using comp shaders
Tested on latest commit
![2021-06-22_13](https://user-images.githubusercontent.com/64978191/122985524-4b687e00-d36c-11eb-89fc-9d05dbd560dd.png)

**Comment by AlsoNiko** [comment]
I was only able to recreate this on latest commits of iris sodium 1.16.5, and not standalone on 1.17.

**Comment by AlsoNiko** [comment]
Update, has been confirmed to happen on 1.17 as well

**Comment by coderbot16** [comment]
But 1.0.2 isn't the latest version, it needs to be reproduced on the latest commit with an affected version of Complementary.

**Comment by AlsoNiko** [comment]
1.0.2 is the latest version you can get threw the installer

**Comment by coderbot16** [comment]
Yes but I need to know whether this is an issue that exists in the current codebase or something that will be fixed just by pushing out a new version

**Comment by AlsoNiko** [comment]
Another update, I have been unable to do so on latest commit of 1.17, only able to do so on 1.16.5 sodium iris, and any report of it being on 1.17 needs to be thrown away for now.

**Comment by AlsoNiko** [comment]
This was fixed but never closed

**Comment by IMS212** [comment]
To be more clear: this was fixed across multiple commits which added separateAo support.
