### ISSUE TITLE
Batch entity rendering is inconsistent with its issues 

### ISSUE THREAD

**Issue by AlsoNiko** [IrisShaders/Iris#427]
![image](https://user-images.githubusercontent.com/64978191/123455246-7b539380-d5af-11eb-8419-a811b4524f56.png)
![image](https://user-images.githubusercontent.com/64978191/123455251-7db5ed80-d5af-11eb-90a8-c21fd9c4ab0e.png)
Loading into a world and looking at a librarian is the best way to see it, restarting the game and going back to the same world will give you a different coat.

**Comment by DestinyTheGreat** [comment]
This issue affects only and all villagers and stays consistent throughout an instance (as in, if we load the game and the villagers are correct, then in that load they will always be correct, no matter which world/server we join)

**Comment by SUPERN00Bthefirst** [comment]
Copy of #325

**Comment by AlsoNiko** [comment]
It's not a dupe of #325, though it is related

**Comment by coderbot16** [comment]
This was fixed with the new batched entity rendering in Iris 1.1.2.
