### ISSUE TITLE
Mob spawners need epilepsy warnings with complementary.

### ISSUE THREAD

**Issue by ruvaldak** [IrisShaders/Iris#435]
**Describe the bug**
Mob spawners have strobe-light white spots when viewed on the sides of the screen while using complementary's integrated pbr.

**To Reproduce**
Steps to reproduce the behaviour:
No idea besides just have a mob spawner on the side of the screen while using complementary and it's integrated pbr.

**Expected behaviour**
Uh. Not to need an epilepsy warning.

**Screenshots**

**System (please complete the following information):**
 - OS: Arch Linux
 - GPU: RTX 2080Ti w/ NVidia Prop drivers
 - Minecraft Version: 1.16.5

**Additional context**
[latest.log](https://github.com/IrisShaders/Iris/files/6720904/latest.log)

No resource packs were enabled. I do have custom settings on Complementary, and can upload my copy of it if necessary. 
I'm using Starline, but I can confirm that this does also happen on trunk. Just happened to be using starline when I grabbed that latest.log

**Comment by CodingRays** [comment]
I was unable to reproduce the issue both with 1.0 and trunk. Can you confirm this also happens when you have no other mods installed besides iris and if so please attach a screenshot?

**Comment by ruvaldak** [comment]
My bad, this seems to have been caused by TexTweaks. When disabling TexTweaks, the flashing goes away. Must be a minor incompatibility there.

**Comment by CodingRays** [comment]
I am still unable to reproduce the issue. This might be some combination of mods and or platform dependant.

**Comment by ruvaldak** [comment]
I'll do some more testing on this, then.

Relevant information:
CPU: i7-9700k @ 4.9ghz
RAM: 16gb @ 4000mhz CL15
GPU: EVGA Black 2080Ti
OS: Arch Linux w/ KDE Plasma 5

**Comment by coderbot16** [comment]
This is/was a Complementary issue when using a non-vanilla-ish resource pack with Integrated PBR enabled. I think it might have been mitigated in Complementary but I'm not sure. In any case, not an Iris issue.
