### ISSUE TITLE
Unsupported Uniform log spam

### ISSUE THREAD

**Issue by ruvaldak** [IrisShaders/Iris#436]
![unknown1](https://user-images.githubusercontent.com/15901769/123531376-f0b78500-d6d1-11eb-918c-314ff5b162f4.png)
![unknown2](https://user-images.githubusercontent.com/15901769/123531378-f3b27580-d6d1-11eb-8bd6-4537a4dbfbb3.png)

**Comment by coderbot16** [comment]
The spurious unsupported uniform spam was fixed in Iris 1.1.2. These warnings are still printed for uniforms that are *actually* not supported, so the log messages are actually useful.
