### ISSUE TITLE
Github Actions artifact upload

### ISSUE THREAD

**Issue by xtexChooser** [IrisShaders/Iris#447]
This repo has an action to build Iris for each commit.

[This](https://github.com/marketplace/actions/upload-a-build-artifact) is an action provided from the Github Official.

You can use it to publish the build result to Github actions page automated.

(I only want to a latest build for Minecraft 1.17

**Comment by IMS212** [comment]
Please read https://github.com/IrisShaders/Iris/pull/247#issuecomment-822603440, we are trying to discourage use of development builds. An official build for 1.17 isn't far off, but you will need to manually build it if you wish to use the latest commit.
