### ISSUE TITLE
Optifine-like Shader options

### ISSUE THREAD

**Issue by CoderStone** [IrisShaders/Iris#449]
**Is your feature request related to a problem? Please describe.**
I find it really frustrating that Iris, which improves shader usage so much, doesn't allow any options for shaders.
I use a 4K display, so without shader options such as render scale, antialiasing, water tint, and more, I am not sure how I'm supposed to adjust those options.

**Describe the solution you'd like**
An in-game shader customization option like found in Optifine.

**Describe alternatives you've considered**
Editing the shaderpack themselves.

**Comment by Shadowevil015** [comment]
Hi! "Shaderpack customisation is being worked on, and will be supported soon" - from the Iris discord. For updates you should join the [discord](https://discord.gg/jQJnav2jPu), and read the latest #public-releases, where Coderbot gives more info on Iris.

**Comment by CoderStone** [comment]
Ay, thank you for all your hard work!
