### ISSUE TITLE
Enchantment Glints broken

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#450]
### What happened?

Enchantment glints are no longer shown in 1.17. Screenshots are in Complementary.

### Screenshots

![Screenshot from 2021-06-29 21-54-41](https://user-images.githubusercontent.com/75493688/123859285-c27db380-d924-11eb-80ed-a55eaa2a8e0e.png)
![Screenshot from 2021-06-29 21-54-47](https://user-images.githubusercontent.com/75493688/123859297-c4e00d80-d924-11eb-9457-3cc275b383ee.png)

### Iris and Minecraft Version

Minecraft 1.17, iris-mc1.17-1.1.0+rev.f06a69d

### Are you running Sodium along with Iris?

Yes

### Operating System

Pop!_OS

### What is your GPU?

NVidia GeForce GTX 950M

### Java Version

AdoptOpenJDK 16

### Additional context

This seems to be shaderpack independent.

**Comment by heymanMC** [comment]
I can also confirm the glint is broken for 1.17, but only in F3:
First person:
![2021-06-29_14 04 00](https://user-images.githubusercontent.com/38384673/123860483-326b4a00-d8e3-11eb-9532-b0f2c3888726.png)

Third person:
![2021-06-29_14 05 49](https://user-images.githubusercontent.com/38384673/123860525-3f883900-d8e3-11eb-83a2-c50a6316563a.png)

I also tested without sodium, so it seems the fault is from Iris.

**Comment by CodingRays** [comment]
This is probably the same issue as in #403 
World glints and lines draw to the same framebuffer and iris doesnt merge it with the final render.

**Comment by IMS212** [comment]
This should be solved as of Iris 1.1.2.
