### ISSUE TITLE
Iris should remove whitespace before the #version directive on macOS

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#451]
If there's a space on the same line as the #version directive before the actual #version directive, the macOS driver fails to compile it. Just a weird Apple driver bug.

**Comment by AlsoNiko** [comment]
Open PR for a fix, should be reviewed soon

**Comment by coderbot16** [comment]
This was fixed by https://github.com/IrisShaders/Iris/pull/452
