### ISSUE TITLE
Framerates drop extremely low after a while, but come back up under various circumstances (reloading shaders, etc.) [1.17 Iris/Sodium 1.1.0]

### ISSUE THREAD

**Issue by DestinyTheGreat** [IrisShaders/Iris#453]
### What happened?

Several users reported their framerates dropping incredibly low (1-2 fps) for seemingly no reason, then coming back to normal once again for either seemingly no reason or because they reloaded shaders. This has been reported with multiple shaderpacks.

### Iris and Minecraft Version

Iris/Sodium 1.1.0 for Minecraft 1.1.7

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows and Linux

### What is your GPU?

several

### Java Version

Java 16

### Additional context

This has been reported both with and without other mods

**Comment by coderbot16** [comment]
Would be helpful to have Spark profiles of this - maybe it can be tracked down to a certain function misbehaving. Or maybe this is another case of the entity rendering memory leak?

**Comment by heymanMC** [comment]
Is this https://github.com/IrisShaders/Iris/issues/419 as well?

**Comment by DestinyTheGreat** [comment]
I do not believe this is identical to #419 since #419 is unfixable in-game. Once it happens, it is permanent unless you leave the world.

**Comment by DestinyTheGreat** [comment]
Screenshots from users who experience the bug

![Minecraft__1 17_-_Multiplayer_3rd-party_Server_2021-06-29_4_02_32_PM](https://user-images.githubusercontent.com/65428450/123875648-e7efca80-d8ee-11eb-8e69-37184fb45724.png)

![unknown](https://user-images.githubusercontent.com/65428450/123875691-f938d700-d8ee-11eb-8278-a73c9f0243da.png)

**Comment by DestinyTheGreat** [comment]
It seems that panning the camera causes extreme issues while using Lithium and Starlight fixes it.

**Comment by DestinyTheGreat** [comment]
Also happens without shaders.

**Comment by coderbot16** [comment]
I wonder if this happens with the Sodium 1.17 branch: https://github.com/CaffeineMC/sodium-fabric/

If it happens without Iris that would help narrow it down.

**Comment by DestinyTheGreat** [comment]
Confirmed Sodium issue inherited from upstream, keep open for monitoring until it is fixed

**Comment by hellosway** [comment]
placing or breaking block really fast causes this for me, along with it happeining a few seconds after joining the world, but it goes waay after 10 seconds

**Comment by hellosway** [comment]
and theres a cpu usage spike sometimes, and gpu is totaly unused

**Comment by rudensdash** [comment]
> Confirmed Sodium issue inherited from upstream, keep open for monitoring until it is fixed

i think is not sodium mod. it was still drop framerate when i use iris without sodium.

**Comment by Kuiriel** [comment]
I did not notice this issue in 1.16.5, across 4 PCs ranging from Windows 8 to 10, GTX 560 to 2080Ti, i3-2320 to i9-9900ks.

In 1.17 this happened without Sodium installed, so I removed it from all PCs. I was very excited by the Sodium release which did run better overall but unfortunately the drop to zero still happens. I ended up removing it rather than disabling it. I am still trying to work out what exactly causes it - I'll take any advice on what I can do to test and help.

**Comment by Lopolin-LP** [comment]
![image](https://user-images.githubusercontent.com/82715586/124751056-7df6a700-df26-11eb-9016-7d0de87e7686.png)
The Ram usage is also EXTREMLY High, as soon as it hits that point of starting to Lag.
So, maybe theres something wrong with the RAM usage/handling?

**Comment by yitzy299** [comment]
> ![image](https://user-images.githubusercontent.com/82715586/124751056-7df6a700-df26-11eb-9016-7d0de87e7686.png)
> The Ram usage is also EXTREMLY High, as soon as it hits that point of starting to Lag.
> So, maybe theres something wrong with the RAM usage/handling?

This is a known memory leak in sodium

**Comment by Lopolin-LP** [comment]
> > ![image](https://user-images.githubusercontent.com/82715586/124751056-7df6a700-df26-11eb-9016-7d0de87e7686.png)
> > The Ram usage is also EXTREMLY High, as soon as it hits that point of starting to Lag.
> > So, maybe theres something wrong with the RAM usage/handling?
> 
> This is a known memory leak in sodium

oh ok.

**Comment by theTyrfing** [comment]
I am also experiencing the same issue with Iris Shaders + Sodium. I am getting similar memory leak issues with the newer implementation of Sodium with the fix provide in build 506 which was implemented in 1.17 fork as well. This crash is very regular and predictable basis. For me this point happens at the 45 minute mark with Iris Shader + Sodium and BSL Shaders. Would guys like the crash reports?

**Comment by DestinyTheGreat** [comment]
Should be fixed in latest commits
