### ISSUE TITLE
"BetterNether" displays an error on shader of iris 1.1.0 

### ISSUE THREAD

**Issue by DSRoie** [IrisShaders/Iris#458]
### What happened?

BSL 8.0.0.1：There is an error as shown in the screenshot
SEUS-V11.0：As above
sildurs：As above

no shader:no error

### Screenshots

![QQ图片20210630123459](https://user-images.githubusercontent.com/74242244/123902617-c00c6f80-d99f-11eb-9f43-38132fdf7208.png)
![QQ图片20210630123517](https://user-images.githubusercontent.com/74242244/123902636-c4d12380-d99f-11eb-9d8d-1a106a4903d8.png)

### Iris and Minecraft Version

iris-mc1.16.5-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 11

### What is your GPU?

GeForce GTX 1060

### Java Version

java 11

**Comment by DestinyTheGreat** [comment]
known issue, not our problem, fixed in the 1.17 release of BetterNether

**Comment by DSRoie** [comment]
> 已知的问题，而不是我们的问题，固定在1.17版本的更好的其他
yes thanks.
