### ISSUE TITLE
Curseforge: mark Sodium as included

### ISSUE THREAD

**Issue by Madis0** [IrisShaders/Iris#459]
I think you should mark Sodium as a dependency ("include" or similar) of Iris in Curseforge in order to give credit where due and potentially author rewards as well.

**Comment by Z-8Bit** [comment]
We have JellySquid's (Sodium's Developer) Patreon on the description of the Iris Curseforge page, Iris in 1.16.5 came with Sodium in the same .jar hence there wouldn't be a dependancy marked to avoid confusion.

**Comment by Madis0** [comment]
I am aware that it is in the description and that a dependency per se wouldn't be correct, however CF offers several options for marking it:
![](https://i.imgur.com/rZzQDmd.jpg)

**Comment by coderbot16** [comment]
I've updated the 1.1.0 files to declare Sodium as an "Embedded Library", we'll need to remember to add Sodium as an "Embedded Library" in the CF metadata for future releases too.
