### ISSUE TITLE
Loading screen loop and log spam in main menu when using Iris + Sodium

### ISSUE THREAD

**Issue by VisualDevelopment** [IrisShaders/Iris#461]
### What happened?

When using Iris with sodium included, my game loads to the main menu, then starts a loading screen loop while simultaneously spamming logs.

### Screenshots

[latest.log.zip](https://github.com/IrisShaders/Iris/files/6742086/latest.log.zip)

### Relevant log output

```shell
See latest.log.zip from the Screenshots section, latest.log is 74MB so I can't paste it here.
```

### Iris and Minecraft Version

iris-mc1.16.5-1.1.0.jar for 1.16.5

### Are you running Sodium along with Iris?

Yes

### Operating System

macOS Catalina 10.15.7

### What is your GPU?

Radeon RX 560 2GB

### Java Version

Java 8

### Additional context

I'm using the "All of Fabric 3" modpack with some added and updated mods. I will give any additional info that may be helpful if asked for.

**Comment by DestinyTheGreat** [comment]
you need Indium for AoF3

**Comment by VisualDevelopment** [comment]
I see, the GitHub repository for Indium does not seem to have any releases. How do I obtain a built jar of it? Do I have to build it myself?

**Comment by DestinyTheGreat** [comment]
join our discord server, we have a build of Indium that works

**Comment by VisualDevelopment** [comment]
Alright.

**Comment by VisualDevelopment** [comment]
That fixed it, thank you.
