### ISSUE TITLE
weird bug with seus renewed water

### ISSUE THREAD

**Issue by humematt190** [IrisShaders/Iris#464]
### What happened?

i'm not sure what exactly caused it maybe because it was raining

### Screenshots

i think it would be easier to see it in a video so here https://youtu.be/35ubhrU5ttI

### Iris and Minecraft Version

iris 1.1.0 + sodium 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

nvidia geforce gtx 1650

### Java Version

java 16

**Comment by Syriker** [comment]
Its happenening the same to me, also the characters bugs with the shader, it happends to the others in multiplayer as well .
![image](https://user-images.githubusercontent.com/46267002/124194459-eb3eae00-dac8-11eb-9880-7a894f9b38ac.png)

**Comment by coderbot16** [comment]
This appears to be caused because Iris does not support custom textures defined through shaders.properties.

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/126747716-55d906ec-2704-4266-9b61-5390f11be8a6.png)

Same thing going on here.

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/126747764-558ece74-f6a2-4bca-97c0-8f340d10dca9.png)

Same thing going on here.

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/126747824-a681ff85-a50b-48b3-abc9-2de6ae8efad7.png)

Happening here too.

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/126751008-1725eeaf-f687-481e-a0a2-038c1ecfa6aa.png)

It also has this weird distortion effect around the edges of the screen.

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/126751590-88ebe6c9-675d-42c0-84c0-094038d11fe8.png)

The sky also likes to just disappear if you look at it in the wrong angle.

![image](https://user-images.githubusercontent.com/57580668/126751654-1c0f4120-e759-4484-9412-3aa0dee47461.png)

And by the way, would you be interested in some home made god rays?

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/126754172-d195077b-a0b2-4a0f-a3b5-390f6e87b4ea.png)

And if you go high enough, some of the water just dips out (if you go higher it just all goes away).

**Comment by coderbot16** [comment]
Fixed in 1.1.3
