### ISSUE TITLE
Water bubbles visible through signs

### ISSUE THREAD

**Issue by tazaraz** [IrisShaders/Iris#468]
### What happened?

Using Sildurs Vibrant Shaders, the redstone particles and water bubbles and droplets are visible through shulkers, chests and signs (not a complete list, these are the ones I have encountered).

### Screenshots

![2021-07-01_15 40 10](https://user-images.githubusercontent.com/31385426/124134047-b871c700-da82-11eb-95d4-f087e47981de.png)
![2021-07-01_15 40 27](https://user-images.githubusercontent.com/31385426/124134055-ba3b8a80-da82-11eb-8729-05e2dece99bf.png)

### Iris and Minecraft Version

iris-mc1.16.5-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

macOS 10.13.6 (High Sierra)

### What is your GPU?

GTX1080

### Java Version

Java 13.0.2

**Comment by coderbot16** [comment]
This does not appear to be an issue in Iris 1.1.2 on either 1.16.5 or 1.17.1 with Sildur's Vibrant Shaders. Maybe it was fixed in the meantime.
