### ISSUE TITLE
Add support to Chocapic13 Toaster Edition

### ISSUE THREAD

**Issue by Wachecheiro** [IrisShaders/Iris#473]
Hello, taking into account that this mod is focused on performance together with sodium, I comment that shaders like "Chocapic13 V7.1.1 Toaster Edition" or its latest version like "Chocapic13_HighPerformance_Toaster" are the ones that offer higher FPS for a **HIGH MARGIN**.

I have tried many shaders with my potato, by comparison "Sildurs Vibrant Shaders v1.29 Lite" runs considerably slower.

It is for you to keep in mind, regards

**Comment by IMS212** [comment]
Support is planned, however iris is missing features currently that are required for chocapic to work. Eventually it should start working, however.
