### ISSUE TITLE
SEUS PTGI Support

### ISSUE THREAD

**Issue by Xenthio** [IrisShaders/Iris#474]
SEUS PTGI is currently broken in a way where ceilings remain dark and torch lighting doesn't work.

**Comment by Xenthio** [comment]
Not only will adding support for this shader fix this shader, but it may fix other shaders that rely on the broken features SEUS PTGI

**Comment by eiglow** [comment]
Not only torch lighting, but any artificial lighting. In addition, water is transparent to the point of being almost invisible, and it flickers when moving the player view.

![2021-07-31_13 16 39](https://user-images.githubusercontent.com/16441870/127727804-90037473-c6ae-4ecc-8495-bb415ae7cca7.png)

**Comment by IMS212** [comment]
The water transparency issues are due to custom textures likely not being supported, but the lighting not working is due to geometry shaders not working in 1.17/with Sodium which should hopefully be solved soon.

**Comment by eiglow** [comment]
As of the 9f9baf4 build from discord, lighting mostly works, but laval doesn't illuminate its surroundings.

![2021-08-16_21 22 19](https://user-images.githubusercontent.com/16441870/129559550-1f3fb4d3-cf66-435f-b765-866d2c0ca182.png)

**Comment by Xenthio** [comment]
other notable issues are
![image](https://user-images.githubusercontent.com/28588188/136636603-603657ff-c0de-4f90-9a04-02b4c12f1b98.png) Weird Reflections 
![image](https://user-images.githubusercontent.com/28588188/136636628-b4e5b37a-4a36-4e8e-bedf-428a0383e141.png) Funky Stripe Shadows

**Comment by CEbbinghaus** [comment]
Very keen to see this Supported.

Is the hindering factor missing features/Changed Implementations compared to Optifine? 

👍🏻 from me

**Comment by AlsoSylv** [comment]
Main issue is things not being implemented, iris 1.1.3 will have PTGI support

**Comment by CEbbinghaus** [comment]
> Main issue is things not being implemented, iris 1.1.3 will have PTGI support

That is what I had thought. It doesn't feel like it's Incompatibility but instead just not enough time. I wonder if I should try to learn java since I already have OpenGL experience.

**Comment by coderbot16** [comment]
Fixed in 1.1.3

**Comment by CEbbinghaus** [comment]
So its fully supported? Love that

**Comment by coderbot16** [comment]
Yep! The shader appears to work for the most part. There may still be bugs, but they should be reported separately.
