### ISSUE TITLE
Please 🙏🏻

### ISSUE THREAD

**Issue by Skyexir** [IrisShaders/Iris#475]
Hello ! your work is amazing.
In 1.16 there are a lot more forge mods than fabric,
To avoid lagging behind with a forged modpack many of us use Sodium Reforged.
I know you didn't have infinite time, but a single port (no update, a beta) would be amazing for us 🙏🏻

Thanks for reading !

**Comment by IMS212** [comment]
We do not plan to support an forge version as of now, please read the readme for details as to why.

**Comment by Skyexir** [comment]
I know, but I was trying to change your mind, 
I've read it before.
Thank you for answering

**Comment by Fauli1221** [comment]
@Skyexir you can just fork it and do it yourself
