### ISSUE TITLE
Can you add 1.17.1 snaps support

### ISSUE THREAD

**Issue by JackTGG** [IrisShaders/Iris#478]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Reeses-Puffs** [comment]
It should just work

**Comment by JackTGG** [comment]
Code works but the Fabric.mod.json requires 1.17 and does not include 1.17.1

**Comment by JackTGG** [comment]
Cold compile myself but don't have good luck with that

**Comment by DestinyTheGreat** [comment]
It does not just work because only 1.17 is specified in the mod. You could change that and see, but no guarantees that it does work.

**Comment by JackTGG** [comment]
il try I guess but I like it and the fork of sodium separate and Have bad luck compiling that too but il try

**Comment by JackTGG** [comment]
Can someone compile a version of the sodium fork?

**Comment by DestinyTheGreat** [comment]
you should be able to now

**Comment by JackTGG** [comment]
> you should be able to now

? I should be able to compile or get a jar??

**Comment by AlsoNiko** [comment]
Compiling should work. We will not provide beta builds for people who can not compile. As for this issue iris requires a small to change to work. You can either join the iris discord to search for how to do it, or you can figure out how it works. As for this issues premise iris does not support snapshots or betas until they release.

**Comment by JackTGG** [comment]
> Compiling should work. We will not provide beta builds for people who can not compile. As for this issue iris requires a small to change to work. You can either join the iris discord to search for how to do it, or you can figure out how it works. As for this issues premise iris does not support snapshots or betas until they release.

I know but I compile and the For Of sodium does not compile not iris itself but the fork Never can compile so? but its okay so nvm.

**Comment by AlsoNiko** [comment]
The compile error was just fixed

**Comment by JackTGG** [comment]
> The compile error was just fixed

It was, I see no new commits to github for the fork so I don't know wher to get an updated version but okay.

**Comment by AlsoNiko** [comment]
It did not require a commit, it was an issue with a Maven being down, not with the branch

**Comment by JackTGG** [comment]
> It did not require a commit, it was an issue with a Maven being down, not with the branch

oh okay

**Comment by JackTGG** [comment]
Oh thx Finally got it to compile because it would not find the dependencies so I manually added them to it.
