### ISSUE TITLE
I know it is for 1.17 and not 1.17.1 pre or 1.17.1 yet but..

### ISSUE THREAD

**Issue by JackTGG** [IrisShaders/Iris#479]
I asked for a new version for the mod I was told that non releases / betas are not given to people (probably non patrons )
But I tried "updating" it myself and what I mean allowing the other version to be able to be used.
I was told that it should just work but then when I ran it I realized that it won't and I think It has to do with the patching of the render glitch from 1.17, so I guess you don't give it out but You can fix it by changing 
something to do with alwaysRenderSky or / from class_315 and it showe dfrom this mixin, mixins.iris.json:MixinWorldRenderer
It failed to inject multiple times so Yeah thx bye.

**Comment by IMS212** [comment]
This is known, a fix will likely be included soon.

**Comment by JackTGG** [comment]
Ah Okay thx, also do you know if the stuff for patrons includes this soon or a build on pre?
