### ISSUE TITLE
Werid block shadow

### ISSUE THREAD

**Issue by Youmiel** [IrisShaders/Iris#483]
### What happened?

The shadow of some blocks is counter-intuitive. e.g.The stained glass and wither skeleton skull in the screenshots below.

### Screenshots

The screenshots are captured with SEUS v11. You can notice that the shadow of white stained glass is much accurate in Optifine, and the shadow of wisky head is rendered in Optifine but not rendered in Iris.
<br>Iris shader:
![iris](https://user-images.githubusercontent.com/70473080/124386835-d2bfd500-dd0e-11eb-818a-74a42d93be8c.png)
<br>Optifine shader(captured with Optifine 1.15.2 because SEUS v11 didn't work under OptiFine_1.17_HD_U_G9_pre24):
![Optifine](https://user-images.githubusercontent.com/70473080/124386841-d94e4c80-dd0e-11eb-98fb-e1796308ca6d.png)

### Relevant log output

```shell
No need to put logs here.
```

### Iris and Minecraft Version

iris-mc1.17-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

NVIDIA Geforce GTX 1050

### Java Version

OpenJDK 16.0.1

### Additional context

The issue of stained glass shadow is also comfirmed in iris-mc1.16.5-1.0.0.

**Comment by AlsoNiko** [comment]
Hi! So the stained glass thing I can't confirm if it's a bug, as the optifine behavior does not look proper either, only having a shadow on the edge when stained glass is supposed to have colored shadows in seus v11. As for the skull, that one is not known

**Comment by Youmiel** [comment]
> Hi! So the stained glass thing I can't confirm if it's a bug, as the optifine behavior does not look proper either, only having a shadow on the edge when stained glass is supposed to have colored shadows in seus v11. As for the skull, that one is not known

 It is not an Optifine bug because the stained glass blocks in the screenshots are white, so...  :)

**Comment by AlsoNiko** [comment]
Yes it has just been confirmed to be an iris issue, we're looking into it
