### ISSUE TITLE
Colored shadows have entirely stopped working in Iris 1.1.0

### ISSUE THREAD

**Issue by DestinyTheGreat** [IrisShaders/Iris#484]
### What happened?

Colored shadows don't work

### Screenshots

see issue #483

### Relevant log output

```shell
N/A
```

### Iris and Minecraft Version

Iris 1.1.0, both in 1.16.5 and 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Several users with multiple OS's

### What is your GPU?

Several users with multiple GPU's

### Java Version

Java 8 and 11 in 1.16.5 and Java 16 in 1.17

### Additional context

Note that while I (and other users) used Sodium for performance, I have tested without Sodium and the issue persists.

**Comment by Justsnoopy30** [comment]
This broke in commit https://github.com/IrisShaders/Iris/commit/fad3ea7b03e5942eaf5c02d2f0986b5004f52b9c

**Comment by IMS212** [comment]
FIxed by https://github.com/IrisShaders/Iris/commit/fe9d18e15d0f2fd21b33d886ca995bf1c43d0a68.
