### ISSUE TITLE
0.11.6 - 1.17

### ISSUE THREAD

**Issue by Julyoso** [IrisShaders/Iris#487]
Is there a newer version of this? i cant get to run 0.11.6 mods in here. Also is there any alternative Shaders for fabric that works on 0.11.6 verisons of fabric mods except for Optifine cause that isnt working on my computer. Minecraft keeps crashing and it wont open saying "unkown issue has occured" something something

**Comment by NoComment1105** [comment]
Iris should work perfectly with the fabric loader version 0.11.6, Try installing the mod from Curseforge or Modrinth and then launching the game with laver v0.11.6

**Comment by Julyoso** [comment]
Whats laver v0.11.6?

**Comment by AlsoNiko** [comment]
This provides no useful information, and is mislabeled as an enhancement? If you're trying to use iris and optifine together, they don't work together. If you're trying to add mods to the "iris-reserverd" folder, don't it's not for other mods. If you're looking for shader recommendations, please do not abuse github issues.

**Comment by Julyoso** [comment]
oh im not using optifine either

**Comment by Julyoso** [comment]
But im still focused on the Iris issue.

**Comment by AlsoNiko** [comment]
You have not provided an iris issue, the original paragraph makes no sense logically

**Comment by Julyoso** [comment]
Im just saying that the iris is not working with the mods i installed from fabric. only the structures were remained (mo structures, castle and dungeons. ) backpacks, roughly enough items, mobs healthbar isnt showing in the game.

**Comment by AlsoNiko** [comment]
Rerun the installer and uncheck the custom loader.

**Comment by Julyoso** [comment]
Okayy!! ill try that. Thanks for the help!

**Comment by Julyoso** [comment]
Thanks! it workss!

> Rerun the installer and uncheck the custom loader.
