### ISSUE TITLE
[Sildur's] Water turns dark at certain camera angles at noon

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#49]
To reproduce, set the time to 6000 and look around near water, you should see some flickering.

![Example](https://user-images.githubusercontent.com/22420959/103320593-ccad0c80-49ea-11eb-8086-069c7766ec84.png)

**Comment by IMS212** [comment]
happens to sky as well

**Comment by coderbot16** [comment]
I'm not seeing it happening to the sky with Sildur's Vibrant Medium v1.281. Can you send a screenshot?

**Comment by IMS212** [comment]
oh nvm, it only happens when looking through translucent objects like glass

**Comment by coderbot16** [comment]
Ah yeah, it happens with all translucent objects, since they all use the `gbuffers_water` render layer.

![2020-12-29_18 21 33](https://user-images.githubusercontent.com/22420959/103325891-bc089080-4a02-11eb-8873-3962c236e041.png)

**Comment by coderbot16** [comment]
I reproduced this with just OptiFine, it appears to be an issue in Sildur's: https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/120

**Comment by coderbot16** [comment]
This doesn't happen in default Sildur's because sunPathRotation is set to a nonzero value by default, however Iris does not implement sunPathRotation.
