### ISSUE TITLE
Crash With Immersive Portals

### ISSUE THREAD

**Issue by SaltSouls** [IrisShaders/Iris#490]
### Iris and Minecraft Version

iris-mc1.17-1.1.0 for Minecraft 1.17

### Are you running Sodium along with Iris?

No

### Operating System

Linux Manjaro KDE

### What is your GPU?

Nvidia Geforce RTX 2080ti

### Java Version

Java 16

### Reproduction Steps

1. install Immersive Portals and Iris
2. Create new world
3. Create a nether portal
4. Lose profits

### Crash Report file and latest.log

- [buggy.txt](https://github.com/IrisShaders/Iris/files/6763198/latest.log)
- [eye_gouge.log](https://github.com/IrisShaders/Iris/files/6763214/crash-2021-07-05_02.26.34-client.txt)

**Comment by Tygoar** [comment]
This is a known issue with IP not working with IRIS and causing crashes. There is a PR #425 that is being worked on to resolve.
