### ISSUE TITLE
A way to configure shader options

### ISSUE THREAD

**Issue by tornadodobird** [IrisShaders/Iris#496]
So far the mod looks and functions great! However, since my device isn't the most powerful, I do still need a way to change shader pack presets.

Currently the shaders menu only has these 5 options:

1. Open Shader Pack Folder...
2. Refresh Shader Packs
3. Cancel
4. Apply
5. Done

I think there needs to be a "Shader Options" button that allows for configuration of shader presets and individual settings. Optifine's shaders selector has a button that takes the user to a menu where they can toggle options on or off. I think something similar needs to be implemented.

I hope this mod combo gains as much traction as Optifine has!

**Comment by AlsoNiko** [comment]
This is a planned feature, and already under enhancement, closing because it's a dupe
