### ISSUE TITLE
Continuum shaders = see through blocks

### ISSUE THREAD

**Issue by Vuroz** [IrisShaders/Iris#498]
### What happened?

Using continuum shaders make stone blocks transparent.
(only seems to effect normal stone and not andesite etc.)

### Screenshots

![2021-07-08_19 37 09](https://user-images.githubusercontent.com/32650126/124966847-0b6bf100-e024-11eb-9b13-a9774dd7acaf.png)
![2021-07-08_19 37 14](https://user-images.githubusercontent.com/32650126/124966850-0c048780-e024-11eb-8eb2-179ba0a5ce34.png)
![2021-07-08_19 37 24](https://user-images.githubusercontent.com/32650126/124966851-0c9d1e00-e024-11eb-832e-93b7aad8d2ec.png)

### Iris and Minecraft Version

Iris: iris-mc1.17-1.1.0+rev.7966919 Minecraft: 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 970

### Java Version

Java 16.0.1

**Comment by Senth** [comment]
Can confirm, also got this bug. Seems to be a few other blocks as well in addition to stone (like Light Blue Wool)

### Screenshots
![2021-07-24_00 49 12](https://user-images.githubusercontent.com/2499370/126848380-41d5adcf-1376-4e03-aecf-2b8c66db6615.png)

### Iris and Minecraft Version
- Iris: 1.1.0
- Minecraft: 1.17.1

### Are you running Sodium along with Iris?
Yes (sodium-fabric-mc1.17-0.3.0+IRIS1-rev.7491e3a)

### Operating System
Windows 10

### What is your GPU?
Nvidia GeForce GTX 3080

### Java Version
Java 16.0.1+9

**Comment by carlni2008** [comment]
I have the same problem, for me, the leaves are broken

**Comment by NoComment1105** [comment]
Continuum is not fully supported by iris *yet*
