### ISSUE TITLE
Disable shaders? No appliance

### ISSUE THREAD

**Issue by shadichy** [IrisShaders/Iris#502]
### What happened?

A bug happened!
When i go to the #Shader Packs...# settings, disable shaders, and apply, it didn't work at all, couldn't press apply, why?
I had to manually disable it in the iris config file

### Iris and Minecraft Version

1.16.5 1.0.0

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch Linux 

### What is your GPU?

Intel HD (i'm pretty sure that's not gpu fault)

### Java Version

8u202

**Comment by DestinyTheGreat** [comment]
update iris

**Comment by shadichy** [comment]
To which version?

**Comment by DestinyTheGreat** [comment]
1.1.0, available through all the methods

**Comment by AlsoNiko** [comment]
All except github releases

**Comment by shadichy** [comment]
Let me try
Anyway, thanks

**Comment by shadichy** [comment]
Can i ask where is the prebuild?

**Comment by IMS212** [comment]
https://irisshaders.net run the installer
