### ISSUE TITLE
Iris on AoF 3 keeps constantly reloading when trying to get into the start menu

### ISSUE THREAD

**Issue by ElldarR** [IrisShaders/Iris#503]
The title says it all really.
I installed AoF 3 through CurseForge launcher and then added some extra mods

Extra Mods:
Iris-mc 1.16.5 + Sodium (It said Sodium came included with this, I don't have a separate Sodium.jar)
Bewitchment
Besmirchment
Pehkui
Somnus
Impersonate
Sodium extras
Hydrogen
Starlight

I am quite sure it has to do with Iris, cause I removed all the mods 1 by 1, and when I removed Iris, it stopped doing it.
I don't wanna have to rely on OptiFabric to use shaders, it's buggy and incompatible.
Any ideas of what causes this?

Is it incompatibility? An Issue with a specific Iris version?
I'll see if I can find anything myself, but any professional assistance is appreciated.
Also it keeps starting in-game music whilost loading then abruptly cuts it off before going to the start-menu and then reloading again.
Also also it should be noted that I put the .jar file into the mods folder, I didn't install it using the Iris installer. No idea id that is even possible with curseforge modpacks.
(Sorry if the issue here is obvious, I haven't had time to read through this Hub. I am also posting about this on the AoF 3 reddit in-case that is what causes the issue with Iris).

Below is an attached clip of exactly what happens. (Imgur cause file sizes on GitHub have to be so tiny)

https://imgur.com/vCDnmyj

**Comment by AlsoNiko** [comment]
You need a mod called indium for sodium to work with AoF3

**Comment by ElldarR** [comment]
> You need a mod called indium for sodium to work with AoF3

Good to be aware of but if you read my post properly I said I already tried removing each mod 1by1 and then starting it, and it only changed after Iris was removed. Which was the last one I removed. Also just now since you commented, I went back and took out sodium and sodium extras but left iris in, and it still happened. Indium is not a solution either, since as it stands there is no place to download a cmpatible file of it. It is a work in progress afaik.

**Comment by DestinyTheGreat** [comment]
@ElldarR join our discord where we can give you compatible .jar files of Indium and Sodium Extras

**Comment by ElldarR** [comment]
> @ElldarR join our discord where we can give you compatible .jar files of Indium and Sodium Extras

Ok sure, I can do that, but I genuinely don't think it has to do with Sodium. Like I said to Niko, it is Iris that is causing the bug. I took away everything but Iris, and it persisted. Then I removed Iris, and it worked.

**Comment by DestinyTheGreat** [comment]
It does have to do with Sodium, we know. We've had multiple reports of this same issue with AoF3. Just try the files on our Discord.

**Comment by ElldarR** [comment]
> It does have to do with Sodium, we know. We've had multiple reports of this same issue with AoF3. Just try the files on our Discord.

Ok I'll join the discord. Where do I find that?
And what is your Discord name so I can contact you?

**Comment by heymanMC** [comment]
The discord link can be found on the readme.

**Comment by DestinyTheGreat** [comment]
The Discord link is on our README.md, but I'll post it [here](https://discord.gg/jQJnav2jPu) too.
Any one of our helpers are knowledgeable with Iris and will be able to help you, but if you're looking for me specifically, I go by FluffyPets in the Iris discord.
