### ISSUE TITLE
Block Outline not visible

### ISSUE THREAD

**Issue by Gamestarplayer41** [IrisShaders/Iris#504]
### What happened?

In the 1.17 Version (both standalone and with the Fabric Mod Loader) I have no block Outline. Also the Outline for Chunk border.

Is this there a fix?

### Screenshots

![2021-07-10_20 14 38](https://user-images.githubusercontent.com/51420498/125172713-7ef43680-e1bb-11eb-9ebe-635d5098bb9a.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Rx 6900 XT

### Java Version

probably 16

**Comment by AlsoNiko** [comment]
Duped bug #403 , known issue
