### ISSUE TITLE
could not find required mod: indium requires {sodium @ [~0.2.0 || 0.2.0+iris_rev.400af47]}

### ISSUE THREAD

**Issue by IloveMinecraftLol** [IrisShaders/Iris#506]
### What happened?

I downloaded the iris 1.1.0 on 
curseforge withe litium and this error came

### Iris and Minecraft Version

Iris v1.1.0 + Sodium pour MC 1.16

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Open GL 4.8

### Java Version

Java 8

### Additional context

X could not find required mod: indium requires {sodium @ [~0.2.0 || 0.2.0+iris_rev.400af47]}

XCreating empty clause ?

                                                                                 Exit

**Comment by yitzy299** [comment]
You downloaded the wrong version of indium. Please use the discord for support in the future, GitHub issues are not for support
