### ISSUE TITLE
Light sources don't work with Prismarine Shaders

### ISSUE THREAD

**Issue by AViewFromTheTop** [IrisShaders/Iris#508]
### What happened?

With Prismarine shaders, only skylight works, and all light from blocks doesn't work.
It's an edit of BSL, but BSL's block lights work fine.
This issue was probably caused by the recent colored shadows commit, I'm pretty sure it didn't happen before that.

### Screenshots

![Uploading NoShadowsPrismarine.png…]()

### Iris and Minecraft Version

Iris 1.1.0+null (most recent commit, with colored shadows)

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3080

### Java Version

Java 16.0.1 64bit

**Comment by AlsoNiko** [comment]
This should be fixed now
