### ISSUE TITLE
The waving animation of flowing water blocks appears to disconnect on Sildur's Vibrant Shaders

### ISSUE THREAD

**Issue by VyKingPyro** [IrisShaders/Iris#509]
### What happened?

The texture of water flow blocks are not staying connected if a shader has waving animation for water.

### Screenshots

I feel like videos show the problem better.

This is Optifine + Sildurs Vibrant Shaders v1.28 High
https://streamable.com/h9xpfp

This is Iris + Sildurs Vibrant Shaders v1.28 High
https://streamable.com/sa9hv0

### Relevant log output

```shell
NA
```

### Iris and Minecraft Version

iris-mc1.16.5-1.1.0 for 1.16.5

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1050

### Java Version

Java 16.0.1

**Comment by coderbot16** [comment]
Applying the following diff to `gbuffers_water.vsh` causes the issue to go away:

```diff
 	#ifdef Waving_Water
-		float fy = fract(worldpos.y + 0.001);
+		float fy = fract(worldpos.y + 0.01);
```

Seems like Sodium's fluid rendering might be breaking expectations of Sildur's Vibrant Shaders.

**Comment by akemin-dayo** [comment]
I can confirm that this issue still occurs as of Minecraft 1.19 + Iris 1.2.5 on Sildur's Vibrant 1.32, and that @coderbot16's workaround for the rounding precision error still works (with no real noticeable side effects for OptiFine, if you're using the same modified shaders for both Iris and OptiFine).

Reproduced on both NVIDIA RTX 2060 (NVGRD 512.95, DCH; Windows 10 19044.1826 21H2) and Apple G13J (macOS 12.4 21F79).
