### ISSUE TITLE
Serious Memory Leak in 1.1.0

### ISSUE THREAD

**Issue by Peakstep233** [IrisShaders/Iris#511]
### What happened?

Memory usage will increase fast until the memory (virtual memory included) is exhausted.

### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar for Minecraft 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Soon.

### What is your GPU?

Soon.

### Java Version

Java 16

### Additional context

This bug was not discovered by me. It was found by HerbertBin and KPuzsQueen on www.mcmod.cn, a Chinese mod wiki and forum. I do not know their operating systems or GPUs, but when I get the exact information, I will add to the above two.

**Comment by NoComment1105** [comment]
Known bug.
