### ISSUE TITLE
Support for 1.17.1

### ISSUE THREAD

**Issue by teddyxlandlee** [IrisShaders/Iris#512]
![Requires 1.17 || 1.17-rc2](https://i.loli.net/2021/07/12/OufjbQJtcg21RMV.png)  
Iris 1.1.0 seems does not compat 1.17.1

**Comment by teddyxlandlee** [comment]
Edit: [Log in MultiMC](https://paste.ubuntu.com/p/zSktjG4Rr8/) when I change `fabric.mod.json` in Iris to make Iris force-compat 1.17.1.  
In fact, there is still differences between the two versions.

**Comment by Sanluli36li** [comment]
Install the new one with the installer
https://github.com/IrisShaders/Iris-Installer-Files/releases
https://github.com/IrisShaders/Iris-Installer/releases

**Comment by yitzy299** [comment]
Download from the installer for an updated version
