### ISSUE TITLE
F3 G (show chunk borders...does not show the chunk borders

### ISSUE THREAD

**Issue by djlawler** [IrisShaders/Iris#513]
### What happened?

With 1.17 and Optifine when you hit F3 and G you can see the chunk borders.  With as similar set up as possible, but removing Optifine and loading Iris and Sodium, no chunk borders are shown.

### Iris and Minecraft Version

Minecraft 1.17, iris-mc1.17-1.1.0.jar and sodium-fabric-mc1.17-0.3.0+IRIS1-rev.7491e3a.jar (but actually any version I've tried with Iris)

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1070

### Java Version

Java 16

**Comment by AlsoNiko** [comment]
Known and duplicate issue
