### ISSUE TITLE
transparent player

### ISSUE THREAD

**Issue by mapleSyrup982** [IrisShaders/Iris#514]
### What happened?

when I use minecraft 1.17 with shaders on iris the player is transparent

### Screenshots

![2021-07-12_21 48 38](https://user-images.githubusercontent.com/86534266/125377827-a84bc880-e35b-11eb-84c2-020efdbebc16.png)
![2021-07-12_21 59 39](https://user-images.githubusercontent.com/86534266/125378294-7be47c00-e35c-11eb-8742-475930497955.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 2070

### Java Version

java 16 (is this default?)

### Additional context

you can't see any entities through the player

**Comment by AlsoNiko** [comment]
Known and reported bug
