### ISSUE TITLE
Iris expecting custom verson name on Sodium

### ISSUE THREAD

**Issue by ObscenityIB** [IrisShaders/Iris#515]
### What happened?

`You do not have a compatible version of Sodium installed! You have 0.3.0+rev.7aa70e5 but 0.3.0+IRIS1 is expected`

Iris is expecting a custom version name, despite being said to be able to be used without the bundled sodium in the release.

### Iris and Minecraft Version

iris-mc1.17-1.1.0+rev.15e94e6 (64c239d9fb1932be7844dbf2982a5ccb90c1ce0f) - MC 1.17.1 - sodium-fabric-mc1.17.1-0.3.0+rev.7aa70e5 (7aa70e59235072767ebd666a23c70bfaee13493c)

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1050

### Java Version

Oracle Java 16 to Build - MC Bundled OpenJDK 16 to Run

**Comment by IMS212** [comment]
The bundled sodium must be used if you wish to use sodium, as Iris includes changes to sodium. (You can also build the fork, from our organization.)

**Comment by ObscenityIB** [comment]
Is there a switch to pass to grade to include sodium?
@IMS212

**Comment by IMS212** [comment]
Sadly, no. If you wish to make a dual (sodium-integrated) jar, you need to build both, then modify the iris jar to include sodium’s jar

**Comment by ObscenityIB** [comment]
Alright, ill run without sodium until the release version is updated

**Comment by IMS212** [comment]
You can manually build sodium, then just add it as a mod if you wish.

**Comment by AlsoNiko** [comment]
The sodium fork also has github actions on

**Comment by ObscenityIB** [comment]
This one?
https://github.com/IrisShaders/sodium-fabric/tree/1.17.x/iris

**Comment by IMS212** [comment]
Yes

**Comment by ObscenityIB** [comment]
last action seems to have a problem

```
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod iris
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:447)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:156)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at me.deftware.client.framework.main.Main.main(Main.java:43)
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:445)
	... 3 more
```

**Comment by IMS212** [comment]
You're attempting to use the -dev jar, when you should use the jar without -dev or -sources.

**Comment by ObscenityIB** [comment]
i used `sodium-fabric-mc1.17.1-0.3.0+IRIS1-build.59.jar` not `sodium-fabric-mc1.17.1-0.3.0+IRIS1-build.59-dev.jar`

**Comment by ObscenityIB** [comment]
oh iris is dev, yeah that was it

**Comment by ObscenityIB** [comment]
so, feedback after trying it for a while.

works  very well, none of the performance loss i get with shaders on OF.
so far only issue is on occasion when rotating the camera, the game will freeze and crash on the render thread

but yeah, whenever thats ironed out, this is definitely going to be my go-to for shaders

**Comment by IMS212** [comment]
Can you try the latest builds of Iris and Sodium, they fix a few memory leak issues.

**Comment by ObscenityIB** [comment]
Looks like it was definitely a memory leak.
Happening on the latest too.

```
14:26:52.897
COM exception querying Win32_VideoController, which might not be on your system. Will not attempt to query it again. Error was -2147217402: (HRESULT: 80041006)
14:26:52.900
COM exception querying Win32_PhysicalMemory, which might not be on your system. Will not attempt to query it again. Error was -2147217402: (HRESULT: 80041006)
```

![image](https://user-images.githubusercontent.com/6983255/125561477-dd19f0ff-8ebd-49ce-886e-1ecfa8aea181.png)
