### ISSUE TITLE
Disabling Sodium text pop-up

### ISSUE THREAD

**Issue by skxrlxt** [IrisShaders/Iris#516]
No matter what I do, I cannot get my modpack to run with Sodium. There's already dashloader so that could be the issue. But I was wondering if I could disable this pop up as this will be streamed SMP. 

![2021-07-13_15 40 13](https://user-images.githubusercontent.com/87355517/125397657-9288e280-e3f1-11eb-87e4-56aff01ef392.png)

**Comment by IMS212** [comment]
I'd recommend joining our discord for more help, as we can't really help through github on modifying the mod to remove warnings. (There is no option to remove it normally.)
