### ISSUE TITLE
the iris or sodium or whatever starts lagging after a while.

### ISSUE THREAD

**Issue by EvuKetsueki** [IrisShaders/Iris#518]
### What happened?

Unsure if its sodium or iris but my game starts lagging randomly, hard after like 15 to an hour of game play, usually getting 100 fps with shaders, 15 minutes later it starts lagging like hell and the fps bouncing from 30 down to 8 back to 17, without shaders i get over 100 but it still lags. is there a fix for this? i really would like to get this fixed.

### Iris and Minecraft Version

1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

Geforce GT or GTX 960

### Java Version

java 16

### Additional context

nothing additional than what i just wrote, it just lags out of no where when using sodium or iris idk which it is

**Comment by AlsoNiko** [comment]
Known already reported issue
