### ISSUE TITLE
Compatibility with 1.17.1

### ISSUE THREAD

**Issue by Emanuele192** [IrisShaders/Iris#522]
The mod can only start with 1.17 and not with the latest version of minecraft.

**Comment by yitzy299** [comment]
The installer supports 1.17

**Comment by taisph** [comment]
I was fooled by this as well. Modules on Modrinth and CurseForge have not been updated. Maybe remove the links from "ALTERNATE DOWNLOADS" if they are not maintained.

**Comment by AlsoNiko** [comment]
They are maintained, but it would have just been a release without a version lock.
