### ISSUE TITLE
Vanilla clouds are invisible in Iris 1.17 (Enhanded Default and Comp RTX-ish) 

### ISSUE THREAD

**Issue by Arbertor** [IrisShaders/Iris#528]
### What happened?

In Sildurs Enhanced Default and Complementry edited (manually in lib / common.glsl) vanilla clouds cannot appear when they would with optifine.

### Iris and Minecraft Version

Iris v1.1.0 + Sodium for MC 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Ubuntu

### What is your GPU?

Nvidia GTX 750 ti

### Java Version

java 16

**Comment by coderbot16** [comment]
This was fixed in https://github.com/IrisShaders/Iris/commit/01d8631f1887a055a8305d9aef3eb93f69e29364, which was included in Iris 1.1.2.
