### ISSUE TITLE
1.18 Snapshot support?

### ISSUE THREAD

**Issue by ExeRhythm** [IrisShaders/Iris#530]
Is it possible to add support for experimental 1.18 snapshot? Thanks in advance

**Comment by boasbakker** [comment]
I made an unofficial version
https://www.mediafire.com/file/a4wpuh97nttukd3/iris-mc1.18_experimental-snapshot-1_updated_by_Boas.jar/file

**Comment by yitzy299** [comment]
Please do not share direct and unofficial jars here. Questions should be on the discord in the future
