### ISSUE TITLE
villager bug

### ISSUE THREAD

**Issue by Vippopper** [IrisShaders/Iris#531]
![2021-07-14_08 22 45](https://user-images.githubusercontent.com/84545121/125649168-23f0affb-d5bb-422c-9b8a-91984b8c3cd9.png)
![2021-07-14_08 22 21](https://user-images.githubusercontent.com/84545121/125649179-a4b22b9a-cce8-446b-b777-dfe08ac2cf46.png)
villagers shouldnt look like this. I have shaders disabled

**Comment by AlsoNiko** [comment]
Known and reported bug
