### ISSUE TITLE
Shaders are not appearing on the "Shader packs" menu

### ISSUE THREAD

**Issue by miditrix** [IrisShaders/Iris#532]
### What happened?

My shader list which was detected by optifine, seems to be not working with Iris

### Screenshots

![unknown](https://user-images.githubusercontent.com/30393526/125652132-a5934e2c-7076-46c7-b438-993a8e1c0b56.png)

### Iris and Minecraft Version

iris-mc1.16.5-1.1.0 for Minecraft 1.16.5

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1050Ti

### Java Version

Java 8

**Comment by AlsoNiko** [comment]
Please join the iris discord for better help

**Comment by dkaloger** [comment]
did you try clicking refresh shaderpacks or exit and reenter the menu?

**Comment by NoComment1105** [comment]
Are there any further experiences of this issue?

**Comment by coderbot16** [comment]
Same issue as https://github.com/IrisShaders/Iris/issues/785, but this report also does not have the needed information to confirm or fix the underlying issue.
