### ISSUE TITLE
frustum.culling is not supported in shaders.properties, causing issues with XorDev's Ortho-Shaderpack

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#54]
Iris:

![Rendering issue example on Iris](https://cdn.discordapp.com/attachments/774352792659820598/793923006464262184/2020-12-30_20.25.48.png)

OptiFine:

![Rendering issue example on OptiFine](https://cdn.discordapp.com/attachments/774352792659820598/793925105578672128/2020-12-30_20.34.01.png)

What it's supposed to be like:

https://www.youtube.com/watch?v=F29dZnuPQwE&feature=emb_logo

It seems like the following option in `shaders.properties` is the critical part:

```
frustum.culling = false
```

**Comment by coderbot16** [comment]
It appears to be fixed with a higher FOV

**Comment by Pepe20129** [comment]
Well I use Quake Pro

**Comment by coderbot16** [comment]
This is also needed for world curvature to work in most shader packs

**Comment by IMS212** [comment]
Added in 1.6.4.

**Comment by atyrode** [comment]
I still get this issue using Iris 1.6.8 regardless of my FOV, or if I try to enable frustum.culling in shaders.properties, on the same shader packs as the original poster.
![image](https://github.com/IrisShaders/Iris/assets/20166883/fab722e1-e4a3-45b6-a121-202d7be49f69)
