### ISSUE TITLE
Iris 1.17.1: Sildur's Vibrant Shaders v1.29 Underwater reflection Issue 

### ISSUE THREAD

**Issue by ClearAspect** [IrisShaders/Iris#542]
### What happened?

Water becomes opaque when using Sildur's Vibrant Shaders and the camera being submerged in water.

*It may not be completely clear in the image but Yes looking up and out the of the water is completely opaque or reflects what you're swimming over*

- There also seems to be an issue of reflection opacity when underwater.

### Screenshots

![2021-07-15_17 00 07](https://user-images.githubusercontent.com/87455484/125857471-f5435b59-ea65-45a2-8a1c-e32e1ea60d38.png)
![2021-07-15_17 00 20](https://user-images.githubusercontent.com/87455484/125857487-79bd9c2f-46a2-4191-b069-32c4101b215f.png)
Iris 1.16.5 Underwater With Sildur's Vibrant Shaders
![2021-07-15_17 02 29](https://user-images.githubusercontent.com/87455484/125857543-a3cfefba-9b3c-4172-a325-0b516af1e819.png)
![2021-07-15_17 02 39](https://user-images.githubusercontent.com/87455484/125857548-10f93d65-bb5c-4d3e-b5f5-65b134b3afe8.png)
Iris 1.17.1 Underwater With Sildur's Vibrant Shaders
![2021-07-15_17 03 15](https://user-images.githubusercontent.com/87455484/125857553-75dbdc34-8a4b-49cf-bd38-408746ce9688.png)
Example of opaque water with no surface visibility | Iris 1.17.1 Underwater With Sildur's Vibrant Shaders

### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar AND sodium-fabric-mc1.17-0.3.0+IRIS1-rev.7491e3a.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 pro

### What is your GPU?

Nvidia Gtx 1060 6gb

### Java Version

Java 16

### Additional context

Using the Iris fabric mod from Curse on 1.16.5 seems to not have the issue.

**Comment by respectablenoob-source** [comment]
Hey there, you can fix this by moving the shader file to optifine to change the settings, then move it back to the iris folder. May I ask how you got Iris shaders for 1.17.1?

**Comment by ClearAspect** [comment]
> Hey there, you can fix this by moving the shader file to optifine to change the settings, then move it back to the iris folder. May I ask how you got Iris shaders for 1.17.1?

I'm not sure you understand, this is not a setting you can change. If you reread my report it mentions that playing on the 1.16.5 version of iris fixes the issue of reflection opacity and water transparency to the surface.
You can get the 1.17.1 version by using the Iris installer on their website.

**Comment by AlsoNiko** [comment]
Can you go back to sildurs 1.27 to test this? I remember the reflection style changed, also please provide a screenshot with f3 of sildurs 1.29 on optifine

**Comment by ClearAspect** [comment]
> Can you go back to sildurs 1.27 to test this? I remember the reflection style changed, also please provide a screenshot with f3 of sildurs 1.29 on optifine

I'm not sure that this will help but I will post more distinctive screenshots

**Comment by ClearAspect** [comment]
Okay, I've relaced and update the images

**Comment by IMS212** [comment]
This is likely related to #9, does this happen without sodium?

**Comment by ClearAspect** [comment]
> This is likely related to #9, does this happen without sodium?

I couldn't say since the 1.17.1 jar requires it and the sodium-less jar isn't on the curse page

**Comment by ClearAspect** [comment]
This still hasn't been fixed in the latest version

**Comment by DiabetoLive** [comment]
Still not fixed.
