### ISSUE TITLE
Stuttering and lag.

### ISSUE THREAD

**Issue by Emanuele192** [IrisShaders/Iris#545]
### What happened?

With the latest version for 1.17.1 the game runs fine for some minutes (maybe 10) but then it starts to stutter. I've also noticed that when the game stutters, in the task manager it appears to be using all my ram (I have 16gb ddr4). Before the game start stuttering it runs flawlessly.

### Iris and Minecraft Version

iris-1.1.1-mc-1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 pro x64

### What is your GPU?

Nvidia Geforce GTX 1060 3gb

### Java Version

Java 16 jdk

**Comment by yitzy299** [comment]
Known issue, but the stuttering is probably the lighting engine
