### ISSUE TITLE
Chocapic13 shaders are not working

### ISSUE THREAD

**Issue by bagerini** [IrisShaders/Iris#548]
### What happened?

When I enable Chocapic13 low and high performance shaders(I haven't tested the other Chocapic shaders), nothing happens. It's just regular minecraft without shaders. Every other shader works fine.

### Iris and Minecraft Version

iris-mc1.17-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

intel integrated graphics 

### Java Version

Java 16

**Comment by GialliDev** [comment]
Those shaderpacks aren't in the officially supported list, so it's expected for them to be buggy or to not work entirely.

**Comment by forkiesassds** [comment]
Reading the console logs outputs this error.
```
[20:53:03] [Render thread/WARN]: Shader compilation log for composite2.fsh: 0(1212) : error C1503: undefined variable "MC_RENDER_QUALITY"
```
It turns out Iris doesn't pass the rendering quality to the compiler.

**Comment by bagerini** [comment]
Sorry. I didn't look at that list. Now I feel dumb

**Comment by Miss-Corruption** [comment]
Update to the latest Iris version and try again. The latest version is 1.1.1.

**Comment by Lystraeus** [comment]
Can confirm none of the release Chocapic13 shaders work, nor the Extreme Beta 5 (Iris 1.1.1). Just a hand and hotbar on a black screen.

**Comment by JonLit** [comment]
Still is not working, I'm using Starline Iris build 596 with sodium IRIS2-build.159 on Garuda Linux with a 1060 6g
I just get a black screen with hotbar and hand, but that's it.

**Comment by IMS212** [comment]
First of all, Starline is not supported. Second, Chocapic versions above 6 will show a black screen, this is known.

**Comment by coderbot16** [comment]
Superseded by https://github.com/IrisShaders/Iris/issues/1030
