### ISSUE TITLE
Bugs with internal shaders

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#55]
* [x] Clouds are black
* [x] No block outline
* [ ] Entities don't turn red when you punch them
* [x] The sun / moon show up behind the skybox

**Comment by IMS212** [comment]
entities don't turn red on sildurs either, and even the optifine internal shaders are known to have issues

**Comment by IMS212** [comment]
Also there is no breaking animation in sildurs

**Comment by coderbot16** [comment]
Entities not turning red is an Iris issue I think, since entityColor isn't currently supported

**Comment by coderbot16** [comment]
* [ ] Z-fighting with the enchantment glint
* [ ] Entities have incorrect lighting

**Comment by coderbot16** [comment]
Closing in favor of #195 and #184
