### ISSUE TITLE
Ability to configure shaders

### ISSUE THREAD

**Issue by TerabyteTB** [IrisShaders/Iris#551]
**Is your feature request related to a problem? Please describe.**
I'm really upset with Iris because it's running at about 11 FPS and there's no way to configure the shaders like Optifine does (like shadow quality and other quality settings) Currently Optifine still runs better on my computer.

**Describe the solution you'd like**
I'm hoping that Iris can add an ability to configure shaders like Optifine does.

**Describe alternatives you've considered**
There are not really any other alternatives.

**Additional context**
Iris: around 11 FPS
Optifine: around 40 FPS

**Comment by AlsoNiko** [comment]
Configuring shaders is being worked on, and this is a duplicate issue.

**Comment by AlsoNiko** [comment]
Also github is not for support about performance, that's what the discord is for
