### ISSUE TITLE
lava not creating light

### ISSUE THREAD

**Issue by Wendys-corp** [IrisShaders/Iris#560]
### What happened?

A bug happened!
lava did not create light using seus ptgi hrr 2.1 on default settings

### Screenshots

![Uploading image.png…]()

### Iris and Minecraft Version

1.16.5 version 2

### Are you running Sodium along with Iris?

No

### Operating System

windows 10

### What is your GPU?

navida rtx 2070

### Java Version

java 8

### Additional context

not sure if im using sodium

**Comment by IMS212** [comment]
This is known, and due to the clear color being set incorrectly to our knowledge.

**Comment by AlsoNiko** [comment]
This is also a duplicate issue #474
