### ISSUE TITLE
Visible chunk borders in water

### ISSUE THREAD

**Issue by supersaiyansubtlety** [IrisShaders/Iris#561]
### What happened?

I noticed strange divisions in water, showed chunk borders, and saw that the divisions were along the chunk borders. 

### Screenshots

![2021-07-16_20 59 16](https://user-images.githubusercontent.com/618276/126024997-88cc903e-7e48-451d-b477-9f53f6d151eb.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar, MC 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1080

### Java Version

Java 16

### Additional context

It only occurs or is only noticeable when there's glass behind the water.

**Comment by coderbot16** [comment]
This is a Sodium bug: https://github.com/CaffeineMC/sodium-fabric/issues/38
