### ISSUE TITLE
No FPS difference after installing Iris + Sodium.

### ISSUE THREAD

**Issue by JoJoMan42** [IrisShaders/Iris#566]
So I installed it today morning and I am getting almost no FPS increase from when I used to use Optifine.

I used SEUS Renewed for my benchmark and I got like 30-40 FPS with Iris, same as with Optifine.
Also, around 110-140 FPS without any shaders at 10 chunks render distance. Any suggestions as to why it is happening?

Just in case, I made my friend do it as well and even he is not getting any FPS boost. He tested in 1.17.1 and I tried in 1.17.1 , 1.17 and 1.16.5. Neither of the versions gave any real difference. 

My Specs: GTX 1050 | 8GB RAM | i5 9300H 
Friend's Specs: MX 230 | 8GB RAM | i5 1035G1

Both Laptops.

Thanks.

**Comment by AlsoNiko** [comment]
Certain shaders like SEUS are very heavy and won't see much of an FPS difference. Another thing is that optifine will not load chunks to maintain performance, sodium will load all chunks it's supposed to, meaning 10 in optifine like about 8 or 7 in vanilla and sodium

**Comment by JoJoMan42** [comment]
> Certain shaders like SEUS are very heavy and won't see much of an FPS difference. Another thing is that optifine will not load chunks to maintain performance, sodium will load all chunks it's supposed to, meaning 10 in optifine like about 8 or 7 in vanilla and sodium

Its like this with every shader and even with no shader. There is literally no FPS decreasing irrespective of wether I use shaders or not.

**Comment by AlsoNiko** [comment]
"Another thing is that optifine will not load chunks to maintain performance, sodium will load all chunks it's supposed to, meaning 10 in optifine like about 8 or 7 in vanilla and sodium"
