### ISSUE TITLE
Inexplicable frame dropping and flashback

### ISSUE THREAD

**Issue by SkyIce0229** [IrisShaders/Iris#567]
### Iris and Minecraft Version

iris-mc1.17-1.1.0forMinecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

windows10

### What is your GPU?

Nvidia GeForce RTX 2070

### Java Version

Java16

### Reproduction Steps

When I play for a period of time, there will be a noticeable reduction of FPS, and then it will drop. Logs points out that it is Iris's problem and pops up this window.It didn't generate crash_ So I will upload lastest. Log and window to you.
![@UQZ$%%4`JHUTE{ %ZAD%$Y](https://user-images.githubusercontent.com/74761160/126042856-e8e8698a-8a50-42bb-827e-a611b0daf43e.png)
[2021-07-17-2.log](https://github.com/IrisShaders/Iris/files/6834962/2021-07-17-2.log)

**Comment by NoComment1105** [comment]
There are some known memory leaks that cause the initial fps drops. The second part of thid issues is odd, please come to the iris discord for further support

**Comment by SkyIce0229** [comment]
Which section should I go to for help
