### ISSUE TITLE
Editing shaderpack options ingame

### ISSUE THREAD

**Issue by kingarthur0975** [IrisShaders/Iris#569]
I seriously LOVE this shaders mod, and my only complaint is that you can't edit a shaderpack's options (i.e. Sildur's Vibrant) ingame. This means if you want to edit some shader options, you have to go through the shaderpack's .txt option file (which only some have) or dig through the shader's .zip file. Once again, I am in love with this mod, and this missing feature is honestly surprising.

**Comment by AlsoNiko** [comment]
dupe issue, being worked on
