### ISSUE TITLE
Strange black screen with windows in the bottom left

### ISSUE THREAD

**Issue by tactlessfish** [IrisShaders/Iris#57]
When I load Complementary Shaders, I get a black screen with windows in the bottom left.
Screenshot:
![2020-12-31_16 50 48](https://user-images.githubusercontent.com/29507110/103427548-c0ae7f80-4b8f-11eb-8ee4-f07d81fc7095.png)

**Comment by IMS212** [comment]
same happens with the woomy shaders

**Comment by coderbot16** [comment]
Complementary is a BSL edit, I'm curious if this happens with BSL too?

**Comment by lucaargolo** [comment]
Yes, I can confirm it happens with the latest BSL release.

**Comment by coderbot16** [comment]
Alright. I think I might know what this is - can you see if it happens with Chocapic too?

**Comment by lucaargolo** [comment]
Chocapic just render a black screen (tested with v9 and v9.1)
![image](https://user-images.githubusercontent.com/49497195/103430426-b649b100-4ba2-11eb-8eba-abcd3a98b044.png)

**Comment by coderbot16** [comment]
Oh, that's even worse! Weird.

In any case these are probably caused by iris not supporting custom uniforms defined in shaders.properties.

**Comment by lucaargolo** [comment]
At least the clouds and water are now "working" with BSL
![image](https://user-images.githubusercontent.com/49497195/103430486-530c4e80-4ba3-11eb-84f3-6a4cd29ec4ae.png)
The reflection is not properly reflecting the world tho, just the sky, and if you look at a certain angle you can see the entire texture atlas. It also completely breaks if you have view bobbing on.
https://user-images.githubusercontent.com/49497195/103430542-fb221780-4ba3-11eb-9585-c018ba712fe4.mp4

**Comment by coderbot16** [comment]
The specific issue with stuff showing up in the corner has been fixed for a while now. While there are other issues when running with BSL / Complementary / etc they deserve separate issues.
