### ISSUE TITLE
The void plane is visible underwater, breaking the fog illusion in oceans

### ISSUE THREAD

**Issue by Detective-Fox** [IrisShaders/Iris#571]
### What happened?

Loading iris-mc1.17-1.1.0 + sodium-fabric-mc.1.17-0.3.0+IRIS1.rev.7491e3a causes ocean chunk loading to be slow, creating visible chunk edges being seen through the game's fog.

This issue is not seen when using the recent Sodium build (sodium-fabric-mc1.17.1-0.3.0+build.5)

### Screenshots

![2021-07-18_17 56 35](https://user-images.githubusercontent.com/42083205/126057421-1a8e7be7-5243-47e8-a1b4-ecc29501d0a2.png)
![2021-07-18_17 56 45](https://user-images.githubusercontent.com/42083205/126057424-832b8095-6e58-4e41-b469-5c3d18471239.png)
![2021-07-18_17 57 01](https://user-images.githubusercontent.com/42083205/126057425-3bfae506-9e6d-4620-9655-b3dda7428fbd.png)

### Log output

[2021-07-18-7.log.gz](https://github.com/IrisShaders/Iris/files/6835744/2021-07-18-7.log.gz)

### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar for Minecraft 1.17 / 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2070 Super

### Java Version

Java 16

**Comment by IMS212** [comment]
Can you not reproduce with vanilla? This doesn't seem like something Iris would affect.

**Comment by Detective-Fox** [comment]
Issue does not persist in Vanilla 1.17.1

![2021-07-22_09 13 46](https://user-images.githubusercontent.com/42083205/126561067-525a7c44-37b0-45d6-ad0c-c0eba9ef7df3.png)
![2021-07-22_09 14 05](https://user-images.githubusercontent.com/42083205/126561073-013b9022-f4de-4a7c-884a-09be28703fa4.png)

**Comment by IMS212** [comment]
This issue seems quite similar to an Sodium issue recently fixed, so an old version of Sodium is likely the cause. If so, the next version of Iris will fix this bug.

**Comment by coderbot16** [comment]
This is caused by the bottom plane of the skybox being rendered as solid black when underwater. It's not caused by slow chunk loading.
