### ISSUE TITLE
MASSIVE lag in servers

### ISSUE THREAD

**Issue by kingarthur0975** [IrisShaders/Iris#578]
### What happened?

Whenever I play on a server, after 10-30 minutes the game just starts seizing up. I don't see a lot of frame drops, but the game just starts stuttering like I'm playing it on my grandma's laptop.

### Iris and Minecraft Version

Iris 1.1.0 for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1660

### Java Version

Java 16

**Comment by kingarthur0975** [comment]
The next time it happens, I'll record it so send here

**Comment by AlsoNiko** [comment]
Known reported bug, will be fixed by next release
