### ISSUE TITLE
Crash on startup says i require minecraft 1.17 am on 1.17.1

### ISSUE THREAD

**Issue by CatGirlCarGirl** [IrisShaders/Iris#580]
### Iris and Minecraft Version

iris-mc1.17-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

Nvidia Geforce RTX 2070 super

### Java Version

Java 16

### Reproduction Steps

1. Place jar in mod folder for curseforge profile
2. Start Minecraft
2. Dialogue box (refer to title)

### Additional context

Using curseforge launcher

**Comment by AlsoNiko** [comment]
use the jars found here instead of CF jars
https://github.com/IrisShaders/Iris-Installer-Files/releases

**Comment by CatGirlCarGirl** [comment]
Thankyou very much

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
