### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Shad0wolf0** [IrisShaders/Iris#581]
### What happened?

Iris Shaders or the modified Sodium mod is creating a memory leak. Spikes up to 12 GBs and makes playing and using the computer unusable. I tested the normal and unmodified Sodium mod and had no problems.
Steps:
1.) Download Iris and modified Sodium mod.
2.) Place in mods folder
3.) Launch game and world and run around until the memory cap.

I do not know if other mods have a problem with Iris or Sodium to create this leak.

### Screenshots

![2021-07-19_01 05 49](https://user-images.githubusercontent.com/62964779/126125783-41d7c192-84ea-4701-a726-9e3b346e20b0.png)
![Screenshot 2021-07-19 010741](https://user-images.githubusercontent.com/62964779/126125790-a1317fa0-35b4-49d3-9751-c7328e3187b8.png)
![Screenshot 2021-07-19 010806](https://user-images.githubusercontent.com/62964779/126125792-1078fd3e-35aa-4ee2-bba4-dc22c2f53a12.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0 & sodium-fabric-mc1.17-0.3.0+IRIS1-rev.7491e3a for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 3060

### Java Version

Java 16

### Additional context

Normal sodium mod does not leak memory.

**Comment by Shad0wolf0** [comment]
Do i shorten the log out

**Comment by NoComment1105** [comment]
Known Issue. In development
