### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by Byllfighter** [IrisShaders/Iris#584]
### What happened?

See in screenshots

### Screenshots

![2021-07-19_12 22 45](https://user-images.githubusercontent.com/60580992/126137000-df989854-13f9-41f8-944f-845853b853e7.png)
![2021-07-19_12 21 58](https://user-images.githubusercontent.com/60580992/126137025-9c9fb04e-7032-44e8-b860-a1401238acd5.png)
![2021-07-19_12 22 25](https://user-images.githubusercontent.com/60580992/126137054-e0336960-71d8-42f9-a9a4-85304336094a.png)
![2021-07-19_12 24 30](https://user-images.githubusercontent.com/60580992/126137118-9fd13fc7-4220-4247-8bd4-5fa660279ecc.png)
![2021-07-19_12 28 43](https://user-images.githubusercontent.com/60580992/126138040-5cd4d12d-93ad-432d-8734-fe3987fbbb5a.png)
![2021-07-19_12 28 52](https://user-images.githubusercontent.com/60580992/126138052-823b087b-01cf-4af2-884b-067aea4557c9.png)
![2021-07-19_12 29 00](https://user-images.githubusercontent.com/60580992/126138054-44d71f7d-eb71-4cc6-a020-2cd17d0cddf3.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0 for minecraft 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 7

### What is your GPU?

Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz 3.10 GHz

### Java Version

Java 16

### Additional context

Mod list:
![mods](https://user-images.githubusercontent.com/60580992/126138516-e631e640-a106-4149-8c3a-63ac0be737da.png)

**Comment by NoComment1105** [comment]
Could you try removing Xaero's Minimap and World map and see if the issue re-occurs?

**Comment by Byllfighter** [comment]
It's not works

**Comment by NoComment1105** [comment]
The issue no-longer appears?

**Comment by Byllfighter** [comment]
its appears

**Comment by NoComment1105** [comment]
try with iris alone

**Comment by Byllfighter** [comment]
its appears i have only fabric api and iris

**Comment by forkiesassds** [comment]
What is your graphics card? Your processor is not enough to know what graphics card you have.

**Comment by coderbot16** [comment]
This is a bug in Sodium: https://github.com/CaffeineMC/sodium-fabric/issues/779
