### ISSUE TITLE
Industrial revolution textures dont work with mod

### ISSUE THREAD

**Issue by AustinBurpee** [IrisShaders/Iris#591]
### What happened?

so when i went to load up the game with iris shaders and industrial revolution 1.17 and the textures just dont exist for some reason. 

### Screenshots

![2021-07-19_20 38 42](https://user-images.githubusercontent.com/69122319/126258281-cb1df3a3-76c0-45a7-bdd0-227bb3c5aeac.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0 for minecraft 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

nvidia 1650 super

### Java Version

java 11

**Comment by IMS212** [comment]
Can you send a log file?

**Comment by AustinBurpee** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/6845325/latest.log)

**Comment by NoComment1105** [comment]
Industrial Revoloution required Indium to function
