### ISSUE TITLE
Is the 1.17.1 standalone jar available somewhere?

### ISSUE THREAD

**Issue by EvandroLucas** [IrisShaders/Iris#593]
The Universal Jar runs fine, but won't work alongside other mods (at least not in TLauncher). 
The standalone jar available on CurseForge, on the other hand, wont't work on 1.17.1, only on 1.17.

**Comment by AlsoNiko** [comment]
They are, but we won't provide support for people using cracked launchers

**Comment by EvandroLucas** [comment]
Thanks anyway
