### ISSUE TITLE
Swamp colors not in settings

### ISSUE THREAD

**Issue by elamea** [IrisShaders/Iris#595]
### What happened?

I always play with swamp colors off yet when I installed this mod they came back on and the custom video settings UI has no option to disable swamp colors. 

### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar for mc 1.17

### Are you running Sodium along with Iris?

No

### Operating System

Mac

### What is your GPU?

Apple M1

### Java Version

16

**Comment by IMS212** [comment]
Swamp colors is an separate optifine feature, and isn't planned to come to Iris
