### ISSUE TITLE
Canvas Shaders

### ISSUE THREAD

**Issue by RocketNinja15** [IrisShaders/Iris#600]
**Is your feature request related to a problem? Please describe.**
I would be cool to have Canvas shaderpacks work with this 

**Describe the solution you'd like**
An extra mod, or a optional toggle that allows you to use Canvas mods with this 

**Describe alternatives you've considered**
A separate mod, that works with Iris.

**Comment by AlsoNiko** [comment]
I feel like this is already handled by canvas...?

**Comment by NoComment1105** [comment]
> https://github.com/IrisShaders/Iris/blob/trunk/README.md#L18
This has been explained in the readme
