### ISSUE TITLE
Excessive RAM Usage with 1.17.1

### ISSUE THREAD

**Issue by JumpyJacko** [IrisShaders/Iris#602]
### What happened?

After 10-30 minutes of playing the game, RAM usage rises past the allocated RAM stated in the java launch options. 

### Screenshots

![Screenshot 2021-07-22 102528](https://user-images.githubusercontent.com/48436180/126575857-9a09f908-0651-420f-8da6-fd555f48a894.png)
![Screenshot 2021-07-22 102655](https://user-images.githubusercontent.com/48436180/126575858-af4d0672-2e97-4c67-92b0-1de0c41072d6.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1060

### Java Version

Java 16

### Additional context

Available RAM (from task manager): 15.8 GB

Happened while using the custom launcher as well as sodium and iris in fabric loader. Additionally, having excessive RAM usage has caused both low frame rates, and for Windows Explorer to crash and restart.

**Comment by AlsoNiko** [comment]
Known reported bug
