### ISSUE TITLE
Weird lines on Sildurs Enhanced Default when lowering Shadow Resolution

### ISSUE THREAD

**Issue by Z-8Bit** [IrisShaders/Iris#603]
### What happened?

If I manually lower the shadow resolution of Sildurs Enhanced Default in shaders\gbuffers_textured.fsh, to anything lower than the default be it 512x (which is actually given in the comments) or 256x, a weird line appears on every block, the line gets more prominent and thicker the lower res it goes.

Only occurs on Sildurs Enhanced Default, have tried it on others like BSL/Complementary/Prismarine/RedHat/Sildurs Vibrant etc.

### Screenshots

![256x](https://user-images.githubusercontent.com/72144072/126588467-df63b413-2584-46cb-af26-3d78f26c63fe.png)
![512](https://user-images.githubusercontent.com/72144072/126588473-6d6f8705-98b3-440c-a513-622cfa7c281e.png)

### Iris and Minecraft Version

Iris 1.1.0 and 1.1.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11

### What is your GPU?

Vega 7 and a Ryzen 4700U

### Java Version

Java 16

### Additional context

No.

**Comment by coderbot16** [comment]
This is shadow acne: https://computergraphics.stackexchange.com/questions/2192/cause-of-shadow-acne

This seems like a shaderpack bug. It's possible that the shadow bias is not being tweaked properly in response to changing the shadow resolution.

It's worth testing on OptiFine, but this doesn't seem like an Iris issue to me. If it doesn't happen on OptiFine, then this is worth further investigation.

**Comment by Z-8Bit** [comment]
![shadows](https://user-images.githubusercontent.com/72144072/126616716-26b1a2ec-65c6-4461-977a-e3aaa184b3f9.png)
![shadowsetting](https://user-images.githubusercontent.com/72144072/126616731-7d3cd964-17e4-4af7-9cae-4774d284bb5a.png)
It is a shader bug, my bad and I'll contact Sildurs about it, it is weird though as I'd have to manually edit the shadow map bias in the shader as it's not present on Optifine's or Starline's settings either, funny to notice how an end user hasn't reported this yet.
