### ISSUE TITLE
memory accumulation when loading a lot of chunks

### ISSUE THREAD

**Issue by kevahu** [IrisShaders/Iris#604]
When loading a lot of chunks, systems memory gets accumulated and doesn't decrease. After a while Minecraft crashes due to "Out of Memory".

I have tested this phenomenon with vanilla mc, just Fabric, Fabric with mods and Fabric with Iris Shaders (Shaders on and off).
But only with Iris Shaders I encountered this problem.

I am able to reproduce this the best when traveling through a nether portal over and over.
Every time I jump between worlds ± 200MB gets accumulated.

My system:
I7 10th gen
16GB DDR4 RAM

Minecraft settings:
JVM Arguments: -Xmx4G
Graphics: Fancy

**Comment by NoComment1105** [comment]
Know reported issue
