### ISSUE TITLE
Merge HyperCubeMC's iris branch

### ISSUE THREAD

**Issue by UltraBlackLinux** [IrisShaders/Iris#607]
Hey there,
please merge https://github.com/HyperCubeMC/Iris into this - It's working perfectly fine for me, and could finally add a shader config system!
Without any shader-config my fps are pretty bad.
Thanks!

**Comment by AlsoNiko** [comment]
It's working good for you doesn't work, we know already of quite a few bugs and flaws with the starline fork of iris. We're working on our implementation of a config system that should not have these issues

**Comment by UltraBlackLinux** [comment]
> It's working good for you doesn't work, we know already of quite a few bugs and flaws with the starline fork of iris. We're working on our implementation of a config system that should not have these issues

But does that really require a complete rework of the config system? Why not take, what already exists and enhance it?

**Comment by AlsoNiko** [comment]
We can't just take the current system and enhance it, it needs to be reworked to properly handle things that it currently doesn't

**Comment by UltraBlackLinux** [comment]
> We can't just take the current system and enhance it, it needs to be reworked to properly handle things that it currently doesn't

Could you at least use starline's system of saving the shader configs? I don't want to port mine over manually, it has taken me quite a lot of time ;)

**Comment by AlsoNiko** [comment]
Starline does not have a unique system for configs, it uses the same system optifine does, it just has issues unrelated to doing so, almost none of the starline code will likely be used, but you won't have to port configs either
