### ISSUE TITLE
Shaders settings (customization)

### ISSUE THREAD

**Issue by Angeryyy** [IrisShaders/Iris#609]
I saw that Iris shaders works very good but i'm missing one thing that is on optifine and i mean shaders setting / customization and i think that this one thing could make IrisShaders even better.

**Comment by NoComment1105** [comment]
It's on the to do list.

**Comment by Drift91** [comment]
According to [this comment](https://github.com/IrisShaders/Iris/issues/542#issuecomment-881004600) on another issue, you can change the settings in OptiFine and then use them in Iris? Is that the case? Because I can't seem to figure out how.

**Comment by AlsoNiko** [comment]
That is not true

**Comment by IMS212** [comment]
> According to [this comment](https://github.com/IrisShaders/Iris/issues/542#issuecomment-881004600) on another issue, you can change the settings in OptiFine and then use them in Iris? Is that the case? Because I can't seem to figure out how.

This isn't the case, Iris doesn't have the code to recognize the shader settings yet.

**Comment by Drift91** [comment]
Ah, alright. Thanks for the quick responses.

As a workaround I changed the default values in the `settings.glsl` to suit my tastes.

I noticed a strange shimmering effect with BSL v8.0.01 once I did, though. Is this a known issue or should I open a new issue? The framerate however is nearly double what I get with OptiFabric in an area with hundreds of torches and possibly thousands of animals.
