### ISSUE TITLE
Iris/Sodium using 10+GB of RAM when only 4GB allocated

### ISSUE THREAD

**Issue by EntangledLabs** [IrisShaders/Iris#616]
### What happened?

Used Iris for the last two days with no shaders and optimized settings for my computer, which is the ASUS Zephyrus G14 2021 w/ Ryzen 9 5900HS and GeForce RTX 3060 and 16GB DDR4-3200.
Using JVM options, I set max and min heap size to 4GB.
Initial RAM usage was ~2GB, after about 30 min to 1 hr RAM usage had slowly climbed up to 10.5GB.

Tried switching JVM's from Hotspot to OpenJ9, did not help.

After trying both latest versions of Optifine and default renderer, no RAM spikes.

### Iris and Minecraft Version

iris-fabric-loader-0.11.5-1.17.1 with Minecraft version 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce RTX 3060 mobile w/ 6GB @60W

### Java Version

Java 16

**Comment by NoComment1105** [comment]
Memory leak is a known issue
