### ISSUE TITLE
[FR] 1.17.1 Sodium

### ISSUE THREAD

**Issue by Romvnly-Gaming** [IrisShaders/Iris#617]
**Is your feature request related to a problem? Please describe.**
Recently, 1.17.1 Sodium has came out with numerous optimizations to the game and I've noticed IrisSodium hasn't updated to it yet, which is causing performance issues for me as I need every drop of FPS I can get when I have shaders on or off. 

**Describe the solution you'd like**
Fetch upstream

**Describe alternatives you've considered**
Not using IRIS

**Additional context**

**Comment by IMS212** [comment]
This has already been done for the next release, and will come soon.

**Comment by luximus-hunter** [comment]
Looking forward to it! Do you have an ETA?

**Comment by IMS212** [comment]
Sadly no, however we are running an open test of it in our discord.
