### ISSUE TITLE
Increase RAM usage

### ISSUE THREAD

**Issue by Shiroomax** [IrisShaders/Iris#623]
### Iris and Minecraft Version

sodium-fabric-mc1.17-0.3.0+IRIS1-rev.7491e3a (1.17.1)

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 21H1

### What is your GPU?

radeon rx 580 8 gb

### Java Version

JDK JAVA 16

### Reproduction Steps

Use Iris+Sodium on 1.17.1
After a couple of minutes crash 
[hs_err_pid5004.log](https://github.com/IrisShaders/Iris/files/6872725/hs_err_pid5004.log)
[latest.log](https://github.com/IrisShaders/Iris/files/6872726/latest.log)
I flew away for a couple of chunks and the RAM consumption only increased until it reached the maximum. (perhaps the textures are not being shipped from ram?). in the end, I got out of memory crash. When I tried to log in to minecraft again I immediately got out of memory crash.
sorry for bad translate (i use google translator)

### Additional context

I flew away for a couple of chunks and the RAM consumption only increased until it reached the maximum. (perhaps the textures are not being shipped from ram?). in the end, I got out of memory crash. When I tried to log in to minecraft again I immediately got out of memory crash.
sorry for bad translate (i use google translator)

**Comment by IMS212** [comment]
This is a known issue, and is already fixed in development builds and will be fixed in the next release.

**Comment by rickiewars** [comment]
When is the next release planned to come out? After one hour of playing, it freezes up my whole system. Luckily Linux recovers after a while when it's able to kill Minecraft but still...

**Comment by NoComment1105** [comment]
Soon:tm:
