### ISSUE TITLE
(1.17.1) Weird underwater reflections when Sodium is present

### ISSUE THREAD

**Issue by jobiandl** [IrisShaders/Iris#625]
### What happened?

I'm currently playing with Fabric 1.17.1 and I have noticed that there weird underwater reflections with Sildurs Vibrant Shaders, where the water would directly mirror the underwater surface. This only appears to happen in Sildurs Vibrant Medium - Extreme VL though, the water in Vibrant lite is completely fine.

**Video Settings:** 

View Distance: 12
Brightness: 50%
Clouds: ON

GUI Scale: 3x
Fullscreen: ON
V - Sync: OFF
FPS Limit: Unlimited

View Bobbing: ON
Attack Indicator: Crosshair 

Graphics Quality: Fancy

Clouds Quality: Default
Weather Quality: Default
Particle Quality: High
Smooth Lighting: ON
Biome Blend: 2 Blocks
Entity Distance: 100%
Entity Shadows: ON
Vignette: ON
*I forgot to turn off vignette. It probably isn't a factor anyway though.

Use Block Face Culling: ON
Use Fog Occlusion: ON
Use Entity Culling: ON
Use Particle Culling: ON
Animate Only Visible Textures: ON

Allow Direct Memory Access: ON

Mipmap Levels: 4x

### Screenshots

Here are the screenshots for the game without shaders.
![No Shaders - Land](https://user-images.githubusercontent.com/68721231/126883951-fdc9f550-a014-45b3-a2f9-ea6d47397ae3.png)
![No Shaders - Underwater](https://user-images.githubusercontent.com/68721231/126883953-14108fbd-222c-4032-b46b-99040a10ff51.png)

These are the screenshots for Sildurs Vibrant Shaders Medium, High, and Volumetric XL. Again, the Sildurs Version used here is v1.29

_Sildurs Vibrant Medium v1.29_:
![Vibrant Medium - Land](https://user-images.githubusercontent.com/68721231/126883975-22222c86-32bd-42b1-a4ec-98089d440f5c.png)
![Vibrant Medium - Underwater](https://user-images.githubusercontent.com/68721231/126883977-3dda134a-0893-4524-82f9-25b716a1136d.png)

_Sildurs Vibrant High v1.29_:
![Vibrant High - Underwater](https://user-images.githubusercontent.com/68721231/126884007-780b777e-57d1-4045-9187-32accb66f6ea.png)
![Vibrant High - Land](https://user-images.githubusercontent.com/68721231/126884010-5a205b50-9c82-4625-ac4f-aef0102b09b0.png)

_Sildurs Vibrant Extreme VL v1.29_:
![Vibrant Extreme VL - Underwater](https://user-images.githubusercontent.com/68721231/126884038-5999e506-7bde-4f25-b2cf-d1e294ad2780.png)
![Vibrant Extreme VL - Land](https://user-images.githubusercontent.com/68721231/126884043-7b0ec5c7-d8a2-405a-9c5f-8e8ea82059a3.png)

_Sildurs Vibrant Lite v1.29_:
Again, the water reflections in these are alright. But they may be of use though.
![Vibrant Lite - Land](https://user-images.githubusercontent.com/68721231/126884068-8ed2ffb3-df45-437c-8240-357144538692.png)
![Vibrant Lite - Underwater](https://user-images.githubusercontent.com/68721231/126884064-6940290a-0c59-4ded-b626-d15035daa1c5.png)

Lastly, here are the logs for each shader profile. In each l would load the game, switch to the selected shader profile, then afk underwater for 15 seconds. After that, I close the game and repeat.
No Shaders: [log_noShaders.log](https://github.com/IrisShaders/Iris/files/6873243/log_noShaders.log)
Vibrant Lite: [log_vibrantLite.log](https://github.com/IrisShaders/Iris/files/6873244/log_vibrantLite.log)
Vibrant Medium: [log_vibrantMedium.log](https://github.com/IrisShaders/Iris/files/6873246/log_vibrantMedium.log)
Vibrant High: [log_vibrantHigh.log](https://github.com/IrisShaders/Iris/files/6873249/log_vibrantHigh.log)
Vibrant Extreme VL: [log_vibrantExtremeXL.log](https://github.com/IrisShaders/Iris/files/6873251/log_vibrantExtremeXL.log)

### Iris and Minecraft Version

iris-mc1.17-1.1.0 for Minecraft 1.17.1 | Fabric 0.11.6-1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 Home

### What is your GPU?

Nvidia GeForce GTX 1650ti

### Java Version

Java 16

**Comment by IMS212** [comment]
The reason for the water reflections being "fine" in Lite is because Lite has no water reflections to begin with. However, this is a known issue, but the cause of it hasn't been identified yet.

**Comment by coderbot16** [comment]
The issue is that Sodium reuses vertices for the top quad and bottom quad of water, but that causes the vertex normal for the top quad of the water to be reused for the bottom quad. That breaks reflections since the shader thinks it's reflecting off of the top of the water instead of the bottom.

**Comment by SenkiDaKitty** [comment]
I have this as well, but for the outside.
![2021-07-25_18 28 25](https://user-images.githubusercontent.com/44231818/126906284-18e82c2a-f148-40c3-bde6-3b3f9853ec97.png)
![2021-07-25_18 28 28](https://user-images.githubusercontent.com/44231818/126906286-41a0b9f7-1630-4d98-bc86-e68c0ed551c6.png)

**Comment by jobiandl** [comment]
> 
> 
> The reason for the water reflections being "fine" in Lite is because Lite has no water reflections to begin with. However, this is a known issue, but the cause of it hasn't been identified yet.

Oh, I didn't know that. I hope that some of my screenshots and logs help provide a fix though.

> 
>

**Comment by jobiandl** [comment]
> 
> 
> The issue is that Sodium reuses vertices for the top quad and bottom quad of water, but that causes the vertex normal for the top quad of the water to be reused for the bottom quad. That breaks reflections since the shader thinks it's reflecting off of the top of the water instead of the bottom.

Oh alright, hopefully, this issue gets resolved soon. For now, I'll be moving to 1.16.5, where the issue doesn't seem to be present.
