### ISSUE TITLE
Shaderpack option do not appear in menu

### ISSUE THREAD

**Issue by madheadltd** [IrisShaders/Iris#631]
### What happened?

There is no Shaderpack option button in the menu, am I suppose to download extra stuff to make it appear? I have already installed the 1.17.1 Iris & Sodium version via Iris universal jar installer 1.1.1.

### Screenshots

![image](https://user-images.githubusercontent.com/85167236/126982556-bba2734b-6bed-40a8-bd23-b37bd615238c.png)

### Iris and Minecraft Version

Iris-Installer-1.1.1.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

RX 590

### Java Version

Java 11

**Comment by NoComment1105** [comment]
Can you send a log please

**Comment by madheadltd** [comment]
> Can you send a log please

[latest.log](https://github.com/IrisShaders/Iris/files/6877812/latest.log)
 Here.

**Comment by NoComment1105** [comment]
According to the log, you arent running Iris. Are you using the iris profile that was created?

**Comment by madheadltd** [comment]
> According to the log, you arent running Iris. Are you using the iris profile that was created?

![image](https://user-images.githubusercontent.com/85167236/126983255-2c74ad1a-8688-483e-b15c-c9ee5f271d9c.png)
If I done correctly, I am using Iris profile created via installer itself.

**Comment by AlsoNiko** [comment]
You changed the game directory manually

**Comment by AlsoNiko** [comment]
You need to change the installer location as well

**Comment by madheadltd** [comment]
> You need to change the installer location as well

![image](https://user-images.githubusercontent.com/85167236/126983912-7c8e0732-2182-4405-a038-db23cf331cc4.png)
So according to your comment, I need to change the installer location in the Iris installer, right?

**Comment by NoComment1105** [comment]
Yes.

**Comment by AlsoNiko** [comment]
Yes, you need to change it from .minecraft to 1.17.1 iris

**Comment by madheadltd** [comment]
> Yes.

I have changed the location, and it ends up well, the option appears with the sodium option panel. I have tried the Iris 1.17 Standalone version a while ago with no location changes and it still has the Shader option shown. I guess that only Iris + sodium needs to change the location.
Thank you for your reply and your patience, I appreciate it.

**Comment by madheadltd** [comment]
> Yes, you need to change it from .minecraft to 1.17.1 iris

I have changed the location, and it ends up well, the option appears with the sodium option panel. I have tried the Iris 1.17 Standalone version a while ago with no location changes and it still has the Shader option shown. I guess that only Iris + sodium needs to change the location.
Thank you for your reply and your patience, I appreciate it.

**Comment by NoComment1105** [comment]
So it's all working now?

**Comment by madheadltd** [comment]
> So it's all working now?

Yes.
![image](https://user-images.githubusercontent.com/85167236/126987197-eaf7fa12-6bac-4002-ae3f-78eabe4a8778.png)
![image](https://user-images.githubusercontent.com/85167236/126987254-f8d6bc12-f09a-4c52-8f08-78b0b1ed7b5f.png)
Thank you.

**Comment by NoComment1105** [comment]
Your welcome
