### ISSUE TITLE
Iris-Installer did not work in China

### ISSUE THREAD

**Issue by Kogasa-touhou** [IrisShaders/Iris#632]
### What happened?

I tried to use the installer.
But it cant find the server.
My internet works well.
I tried to use vpn.
But it didn't work.

### Screenshots

![image](https://user-images.githubusercontent.com/67717065/126986571-c40e78df-2a50-4aac-9e96-17545dab575c.png)

### Relevant log output

```shell
no logs
```

### Iris and Minecraft Version

all version

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

GTX 1060

### Java Version

java 8

**Comment by NoComment1105** [comment]
What version of the iris installer are you using?

**Comment by Kogasa-touhou** [comment]
1.1.1

**Comment by yitzy299** [comment]
This will have been blocked by the CCP's firewall. If it doesn't work with the VPN, it's likely that said VPN has been blocked. I'm afraid there's nothing we can do about this

**Comment by Kogasa-touhou** [comment]
no 
I can visit google by using this vpn.
Everything goes well .
Just this installer didn't work.

**Comment by yitzy299** [comment]
https://github.com/IrisShaders/Iris-Installer-Files

Try downloading from here, the files are in the relevant folders

**Comment by maxigator** [comment]
try going on that site [raw.githubusercontent.com](http://raw.githubusercontent.com)

**Comment by Kogasa-touhou** [comment]
Okay ,it works.

**Comment by maxigator** [comment]
What is the VPN that you usually use (to go on google for example)

**Comment by Kogasa-touhou** [comment]
clash with US ,HK,JP ....servers.
