### ISSUE TITLE
Reflection weirdness

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#635]
### What happened?

specific reflections look how they're definitely not supposed to

### Screenshots

![Screenshot from 2021-07-26 20-16-52](https://user-images.githubusercontent.com/75493688/127038680-f31e3f46-4b37-475a-9609-e2927ef2ee7d.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0+rev.d3beab3

### Are you running Sodium along with Iris?

Yes

### Operating System

Pop!_OS

### What is your GPU?

NVidia GeForce GTX 950M

### Java Version

AdoptOpenJDK 16

### Additional context

I've tested this with both sildur's vibrant and complementary shaders

**Comment by AlsoNiko** [comment]
Please attach a log file

**Comment by coderbot16** [comment]
This seems like a shader pack issue, not an Iris issue. Test with OptiFine and see if it still happens I suppose.

**Comment by edwloef** [comment]
Niko said on Discord that this definitely is an Iris issue, but I'll try nonetheless.

**Comment by AlsoNiko** [comment]
Reflections look to be refracting wrong, and it happens across shaders

**Comment by coderbot16** [comment]
Without an OptiFine reference screenshot, I'm not convinced that this is an Iris issue instead of a shader pack issue. I see similar issues with Sildur's Vibrant Shaders on both Iris and OptiFine.

**Comment by Heath123** [comment]
Maybe related to #117?
