### ISSUE TITLE
Enchantment glow not showing up

### ISSUE THREAD

**Issue by LukeOnuke** [IrisShaders/Iris#638]
### What happened?

Enchantment glow doesnt show up world rendered items, like armour on players and items on the ground.

### Screenshots

![2021-07-27_14 36 11](https://user-images.githubusercontent.com/57074484/127154673-c5aa01db-4c82-498f-9dd8-17666c98d177.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.0.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Win NT 10 (Windows 10)

### What is your GPU?

GTX 1660Super

### Java Version

Default launcher java 16

**Comment by LukeOnuke** [comment]
Also im using slidurs vibrant medium

**Comment by NoComment1105** [comment]
Known bug. There is an open pr for it that will hopefully bee in the next release
