### ISSUE TITLE
changes assigned ram usage as soon as started

### ISSUE THREAD

**Issue by Karlumbus** [IrisShaders/Iris#639]
Hey, 
when I assign a certain ram usage (8G) and start minecraft with iris & sodium, it changes it back to default usage (2G). 
I don't understand why and hope I overlooked something, but maybe it's just a bug.

**Comment by NoComment1105** [comment]
Known issue. Fixed in next release

**Comment by NoComment1105** [comment]
Wait i misread this. Are you sure you're setting the memory in the iris profile, not just the defualt Minecraft or Fabric one?

**Comment by Karlumbus** [comment]
yes in the iris profile. on installations, then iris&sodium (iris-fabric-loader-0.11.5-1.17.1), more options, jvm-arguments "-Xmx2G-" to "-Xmx8G-"

**Comment by IMS212** [comment]
Never set ram to more than 4GB, especially when only using mods like iris,

**Comment by Karlumbus** [comment]
why?

**Comment by IMS212** [comment]
More ram actually slows down your PC and hurts the game after a specific point.

**Comment by Karlumbus** [comment]
doesn't it only slow down the pc because it's using it for mc, therefore mc is "faster" and why does it hurt the game

**Comment by IMS212** [comment]
Java isn't good at utilizing more ram than it needs, thus GC takes longer causing stuttering and overall slowdowns. In any case, what this issue says shouldn't be Iris specific, as Iris shouldn't be able to mess with the profile.

**Comment by Karlumbus** [comment]
ok thanks

I tried it with optifine and vanilla and this doesn't occure with them, so idk
