### ISSUE TITLE
Can't access shader settings.

### ISSUE THREAD

**Issue by Flicks1** [IrisShaders/Iris#642]
### What happened?

Can't access shader settings.

### Iris and Minecraft Version

iris-mc1.17-1.1.0 

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

RX %&)

### Java Version

Java 16

**Comment by IMS212** [comment]
This isn't an issue, shader settings aren't added yet. They will be added in a future release.
