### ISSUE TITLE
Sodium for 1.17 disables sky rendering when underwater and when blind, breaking some shader packs

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#645]
This was caused by https://github.com/CaffeineMC/sodium-fabric/pull/710

I think disabling the "sunset" part when underwater should fix most of the weird visual issues without breaking packs.

**Comment by IMS212** [comment]
Would disabling the PR if a shaderpack is loaded be an adequate fix?

**Comment by TehcJS** [comment]
I am able to reproduce this bug with my test shaderpack. https://github.com/CursedMC/sodium-iris-fog-test
![](https://user-images.githubusercontent.com/18603248/127255210-187fd1d0-87aa-4577-ad99-53671b7a9c1c.png)
***Note:** The blindness status effect is currently broken in the shaderpack. As far as I'm aware, it isn't an iris bug.*

**Comment by coderbot16** [comment]
That would work for now, and I can investigate disabling the sunset effect while underwater / blind later.

**Comment by IMS212** [comment]
Sounds good, I’ll change it.

**Comment by TehcJS** [comment]
> That would work for now, and I can investigate disabling the sunset effect while underwater / blind later.

You may also want to disable clouds while underwater too.

**Comment by TehcJS** [comment]
I've tested the test shader against the latest sodium + iris builds and it appears to be fixed.

**Comment by coderbot16** [comment]
Fixed in https://github.com/IrisShaders/sodium-fabric/commit/f42a255e86acb226048501dc31365b9ac2cfe5b3
