### ISSUE TITLE
Physics Mod flicker

### ISSUE THREAD

**Issue by LizIsTired** [IrisShaders/Iris#646]
### What happened?

Randomly, the game will flicker.

### Screenshots

https://user-images.githubusercontent.com/13466206/127258875-989d8827-3f43-4dde-a44d-a2f94f6b0c20.mp4

![2021-07-27 (2)](https://user-images.githubusercontent.com/13466206/127258903-81511ef2-0d10-498f-b7e8-0510d45cfcaa.png)

https://user-images.githubusercontent.com/13466206/127258990-a599f34e-f958-4d2a-a222-c6cce64ea20e.mp4

### Iris and Minecraft Version

iris-mc1.17-1.1.1-prerev.f7521f3.jar for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD Radeon R9 270X

### Java Version

Java 16

### Additional context

This happens while on [Mineplex](eu.mineplex.com), [McPlayHD](McPlayHd.net) and [The Archon](play.thearchon.net) (these are servers I've tried so far). It doesn't happen on a dedicated server with Physics Mod installed serverside, nor with it not installed serverside. It also doesn't happen in singleplayer. 
It happens with every shaderpack in my list of 16 but doesn't happen when shaders are turned off. 
It also only happens with Physics Mod installed and without it installed, there is no flickering. 
This happens on latest pinned build, pinned build without Sodium and release.

**Comment by Shad0wolf0** [comment]
I remember that happening to me on mineplex with optifine. I thought it was normal

**Comment by LizIsTired** [comment]
still happens in 1.1.1 Iris and 2.4.5 Physics Mod

**Comment by LizIsTired** [comment]
2.5.4 Physics Mod (and 1.17 branch, not sure if that's making a difference) fixes this!
