### ISSUE TITLE
The atlasSize uniform should reflect the currently bound atlas texture

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#648]
Currently it is always set to the size of the block texture atlas. When an atlas isn't bound, it should be set to (0, 0).

**Comment by IMS212** [comment]
Would #549 not fix this?

**Comment by coderbot16** [comment]
It would probably fix it for 1.16 but I don't think it would work on 1.17. Also, it doesn't refer to *any* atlas texture, but rather the texture bound to `texture` / `gtexture` / `tex`, which could end up being an important distinction in modded environments.
