### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by respectablenoob-source** [IrisShaders/Iris#653]
### What happened?

After using Minecraft, the memory use increases over time until it reaches the maximum memory of my computer and crashes it. Possible memory leak. Can anyone reproduce?

### Iris and Minecraft Version

iris 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

gtx 1660 ti

### Java Version

java 16

**Comment by NoComment1105** [comment]
Update Your iris using installer

**Comment by NoComment1105** [comment]
This was fixed in hte latest release

**Comment by respectablenoob-source** [comment]
> This was fixed in hte latest release

Even using latest version, memory leak is encountered.

**Comment by TehcJS** [comment]
Can you show us your logs and Iris version?

**Comment by respectablenoob-source** [comment]
> Can you show us your logs and Iris version?

Iris version is 1.1.0 and here is the log:
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffd362abb44, pid=8056, tid=9688
#
# JRE version: Java(TM) SE Runtime Environment (16.0.1+9) (build 16.0.1+9-24)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (16.0.1+9-24, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0xe5bb44]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows

this happens sometimes or the log will report an out of memory error. Anyway though, memory is always increasing in usage.

**Comment by edwloef** [comment]
Update to Iris version 1.1.1 using the installer.

**Comment by NoComment1105** [comment]
Again Like i said. Fixed in latest release. You iris is outdated.

**Comment by TehcJS** [comment]
Have you tried downloading iris 1.1.1 from modrinth?

**Comment by respectablenoob-source** [comment]
> Have you tried downloading iris 1.1.1 from modrinth? (make sure it matches your minecraft version)

Right, I downloaded from the wrong location. Trying now.

**Comment by TehcJS** [comment]
> > Have you tried downloading iris 1.1.1 from modrinth? (make sure it matches your minecraft version)
> 
> Right, I downloaded from the wrong location. Trying now.

You can also use the Iris installer on the website if you want.

**Comment by respectablenoob-source** [comment]
> > > Have you tried downloading iris 1.1.1 from modrinth? (make sure it matches your minecraft version)
> > 
> > 
> > Right, I downloaded from the wrong location. Trying now.
> 
> You can also use the Iris installer on the website if you want.

Now I get this error :
Caused by: java.lang.IllegalStateException: You do not have a compatible version of Sodium installed! You have 0.3.0+IRIS1-rev.7491e3a but 0.3.0+IRIS1 is expected

**Comment by TehcJS** [comment]
Remove the sodium jar in your mods folder; the latest release on modrinth (Iris + Sodium) comes with sodium

**Comment by respectablenoob-source** [comment]
> Remove the sodium jar in your mods folder; the latest release on modrinth (Iris + Sodium) comes with sodium

For me it is only the iris jar

**Comment by respectablenoob-source** [comment]
> Remove the sodium jar in your mods folder; the latest release on modrinth (Iris + Sodium) comes with sodium

Fixed! Thanks for the help!
