### ISSUE TITLE
support shader config

### ISSUE THREAD

**Issue by Horange321** [IrisShaders/Iris#654]
I can't use "fully ray tracing" in SEUS PTGI, even though I edit txt file. Thanks for adding this

**Comment by AlsoNiko** [comment]
There is already an issue open, and shader config will be supported eventually

**Comment by Horange321** [comment]
> There is already an issue open, and shader config will be supported eventually

Thanks a lot. 😀

**Comment by Mar2ck** [comment]
Where is the open issue?

**Comment by AlsoNiko** [comment]
Just look through github or use the search bar to find it

**Comment by Mar2ck** [comment]
Already did that's why im asking

**Comment by AlsoNiko** [comment]
The issue exists in one of the early early pages, but I won't link it because I do not want people commenting on it, as it is for tracking purposes, not asking for etas.
