### ISSUE TITLE
End gateway beam renders a clone of itself

### ISSUE THREAD

**Issue by CalXee** [IrisShaders/Iris#657]
### What happened?

End gateway beam was rendered twice.

### Screenshots

![2021-07-28_19 23 34](https://user-images.githubusercontent.com/68349758/127527659-45028b5e-7b71-4e9a-96b7-4f9172d1375b.png)

### Iris and Minecraft Version

Iris 1.1.1-pre+null, 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1050 Ti

### Java Version

Java 16

### Additional context

This is NOT a second end gateway in the distance.

**Comment by coderbot16** [comment]
This appears to be related to the shadow pass? I bet that the beam isn't properly being rendered into the shadow map and is instead being rendered into the main framebuffer.

**Comment by coderbot16** [comment]
This will be fixed in 1.1.2.
