### ISSUE TITLE
Bottom face of upwards slabs sometimes unrenders when viewed from below while underwater

### ISSUE THREAD

**Issue by CalXee** [IrisShaders/Iris#659]
### What happened?

Very strangely, in the screenshot below, the chest is visible but F3 tells me I am looking at a purpur slab.

### Screenshots

![2021-07-29_12 15 55](https://user-images.githubusercontent.com/68349758/127531795-901f8ba4-3abb-4f28-969d-5d322c29c3ba.png)
![2021-07-29_12 45 43](https://user-images.githubusercontent.com/68349758/127532238-5e95f349-5d4d-4c2d-b0d1-52d7b3d1ffd9.png)
![2021-07-29_12 45 48](https://user-images.githubusercontent.com/68349758/127532240-8a8285eb-a4b5-4e8d-89fc-33242c141dc6.png)
![2021-07-29_12 49 08](https://user-images.githubusercontent.com/68349758/127532687-53c40e5d-1237-439b-bee2-821b48a2cc9b.png)
![2021-07-29_12 49 14](https://user-images.githubusercontent.com/68349758/127532690-b1c4f0e3-2b41-4517-8106-a0e5db5219bd.png)

Here is what the structure looks like from above:
![2021-07-29_12 44 47](https://user-images.githubusercontent.com/68349758/127532288-4c405228-9e91-4999-a37e-1913f2ec97af.png)
![2021-07-29_12 49 56](https://user-images.githubusercontent.com/68349758/127532780-dde0e4fc-03b8-4e10-aa09-0cbd8b36614d.png)

### Iris and Minecraft Version

1.1.1-pre+null

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1050 Ti

### Java Version

Java 16

### Additional context

There might even be more outcomes with this bug, this report only describes one aspect of it.

**Comment by coderbot16** [comment]
Is this still an issue? I've never seen it myself.

**Comment by coderbot16** [comment]
Closing due to no confirmation in nearly a month
