### ISSUE TITLE
Iris shouldn't spam the log so much

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#664]
Iris has a lot of logspam, making it hard to actually pick out important things. I'd like to make it a lot less spammy. In particular, it shouldn't print out patched shader source code to the console in a development environment, but it could print it to a folder of patched shader files for debugging.

**Comment by IMS212** [comment]
#568 fixes some of this.

**Comment by jammehcow** [comment]
I've been running `AstraLex v24` for the past few days and I've seen a whole lot of console spam. Even more annoying is that the launcher doesn't cut off logs and has caused my 32GB of RAM to fill up - crashing the system.

Usually the game is open for about 6 hours and the RAM usage increases linearly up until 100%. :+1: for getting this in soon.

**Comment by coderbot16** [comment]
This was mostly resolved in Iris 1.1.2. If there are any more specific cases of extreme logspam, please open separate issues.
