### ISSUE TITLE
Vanilla clouds in Sildur's Vibrant Shaders do not render correctly

### ISSUE THREAD

**Issue by heymanMC** [IrisShaders/Iris#666]
### What happened?

Iris version: 1.1.1 (release)

See below for screenshots. They appear to be transparent. 

It should be worth noting the clouds in Enhanced Default work fine.

### Screenshots

![2021-07-30_00 03 29](https://user-images.githubusercontent.com/38384673/127608372-9d77fcec-465a-46b3-9059-afbd3f931ec0.png)

### Iris and Minecraft Version

iris-1.1.1 release

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

RTX 3080

### Java Version

AdoptOpenJDK Java 16

### Additional context

Minecraft version: 1.17.1

**Comment by coderbot16** [comment]
What version of Minecraft is this on? That part is important.

**Comment by heymanMC** [comment]
> What version of Minecraft is this on? That part is important.

Minecraft 1.17.1

**Comment by NoComment1105** [comment]
Does this still happen on 1.1.2?

**Comment by coderbot16** [comment]
What is the behavior with OptiFine?

**Comment by heymanMC** [comment]
No longer an issue in 1.2.0. Initially it happened because iris did not turn off vanilla clouds when shaders are enabled.

**Comment by coderbot16** [comment]
Ah, alright, thanks for checking!
