### ISSUE TITLE
Block Entity and Item Frame rendering bugs with BBOR

### ISSUE THREAD

**Issue by MAX-XiaoKui** [IrisShaders/Iris#668]
### What happened?

Rendering bugs.
1. Other blocks, entities, and selection outline are rendered across block entities.
2. Item Frames are rendered at the wrong place.

### Screenshots

![image](https://user-images.githubusercontent.com/53287753/127655292-3342dbcc-2915-4bea-8b8e-3b8be49c2ffc.png)
![image](https://user-images.githubusercontent.com/53287753/127655313-0db333f5-9355-4681-aa90-725dd57630c0.png)
![image](https://user-images.githubusercontent.com/53287753/127655377-a1210127-5ea8-4559-a6d5-bd10cf99d363.png)
![image](https://user-images.githubusercontent.com/53287753/127655402-4fc16532-4f95-4786-8def-d1da73062d4b.png)
![image](https://user-images.githubusercontent.com/53287753/127661226-fdc15038-feba-44f7-9062-800d0dca5eb4.png)

### Relevant log output

```shell
No relevant logs.
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 750 Ti

### Java Version

AdoptOpenJDK-16-OpenJ9

**Comment by AlsoNiko** [comment]
Release iris 1.1.1 shouldn't have block outlines at all, this looks like it's a PR or a test build, please try with the official release

**Comment by MAX-XiaoKui** [comment]
I downloaded the mod in the release page.

**Comment by AlsoNiko** [comment]
Can you send the log file?

**Comment by MAX-XiaoKui** [comment]
log: https://hastebin.com/ikexirujer.sql

**Comment by AlsoNiko** [comment]
Could be a mod conflict, we'll have to look into it

**Comment by MAX-XiaoKui** [comment]
![image](https://user-images.githubusercontent.com/53287753/127667863-ef5a5efe-abbb-4c38-aee8-82397564d094.png)
The slime's face doesn't render;
Entity's shadow is also rendered across entity

**Comment by AlsoNiko** [comment]
Still can not confirm if this happens with stock iris, also what shader? Or is there none?

**Comment by MAX-XiaoKui** [comment]
emmm, no shader.

**Comment by AlsoNiko** [comment]
Can you try with just iris to confirm this is not a bug with something else?

**Comment by MAX-XiaoKui** [comment]
Ah, this is a bug with other mods.
Let me find out which mod is it.

**Comment by AlsoNiko** [comment]
If/when you find the mod that causes it, if it only happens with iris or if it is a bug with only that mod

**Comment by MAX-XiaoKui** [comment]
It's a bug with Iris and [BBOR](https://www.curseforge.com/minecraft/mc-mods/bounding-box-outline-reloaded).

**Comment by MAX-XiaoKui** [comment]
log: https://hastebin.com/ukemopepeg.sql

**Comment by AlsoNiko** [comment]
Can you confirm this doesn't happen with just BBOR?

**Comment by MAX-XiaoKui** [comment]
Yes.

**Comment by MAX-XiaoKui** [comment]
And With BBOR and sodium, this doesn't happen.

**Comment by MAX-XiaoKui** [comment]
I think it's BBOR's bug.
Nothing is wrong without BBOR.

**Comment by ishland** [comment]
This should be fixed in https://github.com/irtimaled/BoundingBoxOutlineReloaded/pull/133

**Comment by MAX-XiaoKui** [comment]
OK, it's fixed. Thanks.
