### ISSUE TITLE
Iris comes with the fabric loader 0.11.5, not 0.11.6.

### ISSUE THREAD

**Issue by slept3hours** [IrisShaders/Iris#672]
Tried to update my MC to 1.17.1 from 1.16.5 along with ~30 mods I used to play with, and found that upon launch, I kept getting this error message. Looked into my files and saw that in .fabric folder, the fabric loader version was at 0.11.5, not 0.11.6.
![FailedToLaunch](https://user-images.githubusercontent.com/87636397/127723540-113e62f4-d622-4a7f-aa33-43390223ac9e.png)
I tried removing the intermediary-iris-fabric-loader-0.11.5-1.17.1.jar file and putting in a regular fabric loader 0.11.6, but upon launch, the game just created another iris-fabric-loader-0.11.5, crashing again.

**Comment by TehcJS** [comment]
Did you uncheck use custom loader?

**Comment by slept3hours** [comment]
I don't see any check option in the installer I got from the iris website. Am I blind or is the setting hidden somewhere else? xd

**Comment by TheNukeLore** [comment]
it got renamed, it's now "install as a fabric mod"

**Comment by IMS212** [comment]
Install as Fabric mod should be installing 0.11.6. 0.11.5 installing on the custom loader is intended behavior currently, as we haven't updated the loader.

**Comment by slept3hours** [comment]
Ah yes, it works now. Much thanks!
