### ISSUE TITLE
translucency sorting issue with sildurs

### ISSUE THREAD

**Issue by Pyrophany** [IrisShaders/Iris#673]
![2021-07-30_22 06 33](https://user-images.githubusercontent.com/78823434/127725632-042afabe-c40f-4041-8ec7-ce5c5b9aa693.png)
only occurs with sildurs. could not reproduce with no shaders or complementary.
Most recent release of bundled from modrinth, 1.17.1

**Comment by TehcJS** [comment]
This looks like an issue with sodium not supporting translucency sorting.

**Comment by IMS212** [comment]
No, this would happen with Complementary as well if this was the case.

**Comment by TehcJS** [comment]
Sildur's Vibrant Shaders - High
![2021-07-30_22 49 38](https://user-images.githubusercontent.com/18603248/127726464-15c19684-8725-44b2-abd6-cfffabaf5e9d.png)
Sildur's Vibrant Shaders - Medium
![2021-07-30_22 50 25](https://user-images.githubusercontent.com/18603248/127726493-930ccfd5-d209-4003-a046-e16e46e92a44.png)

**Comment by Pyrophany** [comment]
its the glass behind it

**Comment by Pyrophany** [comment]
![2021-07-30_22 57 18](https://user-images.githubusercontent.com/78823434/127726647-7977dfd6-534c-4873-aee1-708daa710cc6.png)
sildurs high
![2021-07-30_22 57 18](https://user-images.githubusercontent.com/78823434/127726657-c6f8df4c-676a-44e1-a75d-56a37892fc5c.png)
sildurs extreme
![2021-07-30_22 58 16](https://user-images.githubusercontent.com/78823434/127726669-31e47eba-ea2a-4005-9bd7-7fe22e0c6d8e.png)
no shaders

**Comment by TheNukeLore** [comment]
does this happen with optifine?

**Comment by Pyrophany** [comment]
on 1.16.5 optifine (only one i have installed) it doesnt.
also it works without the glass, chests behind portal works just fine to reproduce

**Comment by TehcJS** [comment]
try 1.17 optifine too

**Comment by Pyrophany** [comment]
doesnt occur with 1.17.1 optifine

**Comment by TehcJS** [comment]
something must've broken since 1.17. can you restart your game and reproduce it with both sildur's high and extreme then send your `latest.log`?

**Comment by Pyrophany** [comment]
https://paste.ee/p/8zcHw

**Comment by Pyrophany** [comment]
wait my bad there was other stuff including some honey blocks in that world behind the portal

https://paste.ee/p/vK92H
heres one in just a superflat. First with extreme, then high.

**Comment by yitzy299** [comment]
Looks like it's caffeinemc/sodium-fabric#38

**Comment by TheNukeLore** [comment]
No this seems like it might be something else actually, because it only occurs with sildurs and no other shaders
