### ISSUE TITLE
Geometry shaders are not properly patched for Sodium terrain programs on 1.17.1

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#675]
This results in errors like this:

> [00:00:59] [Render thread/WARN]: Shader compilation log for iris:patched_shadow_terrain_for_sodium.gsh: 0:1(10): error: the compatibility profile is not supported

**Comment by coderbot16** [comment]
This was fixed on 1.17.1 in https://github.com/IrisShaders/Iris/commit/56f8be22fa7c801520857127a000d3c8b386f3d5, but not on 1.16.5.

**Comment by IMS212** [comment]
The main issue reported was 1.17 only, due to the compatibility profile seemingly not being supported/automatically activated on Mesa,

**Comment by IMS212** [comment]
This should have been fixed long ago, is this still an issue?

**Comment by coderbot16** [comment]
This was resolved in https://github.com/IrisShaders/Iris/commit/56f8be22fa7c801520857127a000d3c8b386f3d5, which was committed 17 minutes after this issue was created. I guess this was just forgotten about. Thanks for noticing.
