### ISSUE TITLE
[Slidur's] World goes black when looking straight up

### ISSUE THREAD

**Issue by colbiedison** [IrisShaders/Iris#68]
When I face directly upwards, all blocks become black. The sky is not affected.
It happens with all the Slidur's packs except Enhanced Default. It does _**not**_ happen with `(internal)`
 shaders.

Examples:
![image](https://user-images.githubusercontent.com/46203390/103471668-981db580-4d48-11eb-939f-c0667a6816f4.png)  ![image](https://user-images.githubusercontent.com/46203390/103471676-b7b4de00-4d48-11eb-9003-9d18d183d6aa.png)

![image](https://user-images.githubusercontent.com/46203390/103471699-ed59c700-4d48-11eb-8ee3-dc3cb3a9c066.png)  ![image](https://user-images.githubusercontent.com/46203390/103471724-08c4d200-4d49-11eb-97e4-2053537e390e.png)

![image](https://user-images.githubusercontent.com/46203390/103471810-4d9d3880-4d4a-11eb-8bdb-80b85b8ef5a9.png)
When my vertical angle is between -89.0 and -89.9, the world flickers when I look around.
It is completely black when I am facing directly upwards at -90.0.

**Comment by coderbot16** [comment]
That's odd. Does this happen when only Iris is installed, or does it happen with Iris + Sodium?

**Comment by colbiedison** [comment]
It only happens with Iris + Sodium.

**Comment by coderbot16** [comment]
Okay. And when you are using Sodium, does it happen with all render backends, or does it only happen with some (such as multidraw)?

**Comment by colbiedison** [comment]
It happens with all render backends. Oneshot 2.0, 3.0, and multidraw.

**Comment by supsm** [comment]
There seems to be a similar problem with IMS's custom loader. There is some z-fighting there, but I think it's the same bug.

![image](https://user-images.githubusercontent.com/60897356/103471953-f85a2a80-4d3b-11eb-9f58-8abad14d648b.png)
https://discord.com/channels/774352792659820594/774352792659820598/794665848425545808

**Comment by IMS212** [comment]
My loader literally just downloads the sodium fork along with lithium and phosphor, so it has to be.

**Comment by coderbot16** [comment]
This is likely because under Sodium, vertex normals aren't currently supported fully, so Iris just makes them point straight up. For the bottom faces of blocks this is obviously quite wrong, since the vertex normals should be pointing straight down instead. I imagine that is why this issue only happens when you're looking up.

I imagine that there's some sort of dividing by zero or similar happening on the GPU, which would explain the other variant of the issue.

**Comment by IMS212** [comment]
i can try to replicate this, one sec

**Comment by IMS212** [comment]
I can replicate the z-fighting (black flickering) but not OP's type. I am not getting any logs indicating an error either

**Comment by colbiedison** [comment]
I'm also not getting any errors.

**Comment by Pepe20129** [comment]
This is almost cerntanly related to #69

**Comment by coderbot16** [comment]
Can you re-test this? Vertex normals are now fully supported on Iris Standalone and Iris + Sodium.

**Comment by colbiedison** [comment]
I can confirm this is no longer a problem. Everything is rendered properly when looking straight up! :D

**Comment by coderbot16** [comment]
Good to know, thanks!
