### ISSUE TITLE
[Bug] Fluids stop rendering with Iris Shaders

### ISSUE THREAD

**Issue by Desempregago** [IrisShaders/Iris#682]
### What happened?

_[Cross-report requested by REI's maintainer]_

When any shaderpack is enabled, custom fluids stop rendering in REI

### Screenshots

![image](https://user-images.githubusercontent.com/14002834/127760077-4c2d6d68-a1e6-44bb-bf76-bbd8ba4517e8.png)

### Iris and Minecraft Version

Iris 1.1.1 - Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

NVIDIA GTX 1050 (2GB)

### Java Version

Java 16 (AdoptOpenJDK, Hotspot variant)

**Comment by Desempregago** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/590

**Comment by coderbot16** [comment]
This seems like an issue caused by using Sodium (which Iris bundles) with a large modpack without installing Indium.

**Comment by Desempregago** [comment]
The thing is... I'm indeed using Indium (1.0.0, Modrinth Release)
![image](https://user-images.githubusercontent.com/14002834/127770749-ec53759d-c7fa-4ac7-af49-6eece25ea31c.png)

**Comment by mtb-xt** [comment]
@coderbot16 hi, I have the same issue - custom liquids won't render when shaders are enabled.

I *DO* have indium installed.

MC 1.17.1, Iris 1.1.2, Linux

**Comment by xiPakuL** [comment]
I can confirm this still happening in 1.18.1 using:
Fabric api 0.45.2
Modern Industiralization 1.0.4
Sodium 0.4.0 alpha6
Indium 1.0.2 alpha2
Iris 1.2.0

**Comment by coderbot16** [comment]
The issue in this report only affects REI. You probably forgot to install Indium.

**Comment by Panderine** [comment]
> The issue in this report only affects REI. You probably forgot to install Indium.
Sorry I reported this the wrong way (I had indium btw). The issue is in REI. Both the item panel as well as in the recipe  screen (this is what I tried to refer to before)

![image](https://user-images.githubusercontent.com/4042199/154769670-761a11a0-12a9-4920-97a7-19da54e96531.png)

**Comment by coderbot16** [comment]
Issue does not happen on 1.16.5, assuming that this is 1.17+ only:

![image](https://user-images.githubusercontent.com/22420959/162488944-7c3874a7-9764-4131-8a29-bcab2f803fbb.png)

**Comment by coderbot16** [comment]
Seems like this has been fixed for a while now.
