### ISSUE TITLE
Light not rendering from blocks with seus ptgi shaders

### ISSUE THREAD

**Issue by Cwoffle** [IrisShaders/Iris#683]
### What happened?

light is not rendered at all from any light sources making everything look weird

### Screenshots

![2021-08-01_20 34 38](https://user-images.githubusercontent.com/88272354/127767894-65e0c018-e201-45b7-b7f2-021cae49fe51.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1650

### Java Version

Java 16

**Comment by NoComment1105** [comment]
Sue's PTGI is not fully supported on iris yet.
