### ISSUE TITLE
Screens/monitors from Lifts mod turn black with shaders enabled

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [IrisShaders/Iris#686]
### What happened?

When using any shaders with Iris, screens from Lifts mod turn black and their contents move to the bottom left corner in a plain text form.

### Screenshots

How it should be:

![2021-08-02_11 12 52](https://user-images.githubusercontent.com/86702831/127836984-5bcfadcc-9de7-45e1-8deb-76ef3443a96b.png)

How it is while using shaders (here I am using Sildurs Vibrant Lite, but the bug happens with SV Extreme VL, SEUS Renewed and BSL):

![2021-08-02_11 12 16](https://user-images.githubusercontent.com/86702831/127837020-811edc98-3361-4a48-9fc9-4dc75cee42bc.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 980

### Java Version

Java 16

### Additional context

The Lifts mod page on CS: https://www.curseforge.com/minecraft/mc-mods/lifts

**Comment by coderbot16** [comment]
This is caused by Iris getting confused when Lifts renders to a custom render target. I'll look into getting some sort of API added to allow mods to tell Iris to not mess with their rendering when they're rendering to custom render targets.

**Comment by coderbot16** [comment]
I have implemented some code locally that can fix this issue entirely on Iris's side, but it will be some time before I am able to finalize it and push it to GitHub.

**Comment by coderbot16** [comment]
Note: This needs to be ported over to 1.17+, currently the fix is only on 1.16.5.
