### ISSUE TITLE
SEUS PTGI water is bugging

### ISSUE THREAD

**Issue by ubionexd** [IrisShaders/Iris#687]
### What happened?

SEUS PTGI water is not good.

### Screenshots

![2021-08-02_18 47 24](https://user-images.githubusercontent.com/70473378/127896196-fbac107d-2a71-4f84-9881-a0d3ec820550.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 Home

### What is your GPU?

Nvidia GeForce RTX 2060

### Java Version

AdoptOpenJDK's Java 16

### Additional context

It should be look good.

**Comment by AlsoNiko** [comment]
Covered by issue #474
