### ISSUE TITLE
Game crashes when looking at a charged creeper or newly-spawning wither

### ISSUE THREAD

**Issue by GeorgeHK612** [IrisShaders/Iris#689]
### Iris and Minecraft Version

iris 1.11 in minecraft  1.17

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2060

### Java Version

Java 16

### Reproduction Steps

1. Run a wither killer
2. Around 5 wither spawn
3. Game Crashes
[2021-08-03-2.log.gz](https://github.com/IrisShaders/Iris/files/6920756/2021-08-03-2.log.gz)
[crash-2021-08-03_03.36.48-client.txt](https://github.com/IrisShaders/Iris/files/6920759/crash-2021-08-03_03.36.48-client.txt)

**Comment by ginsm** [comment]
This also occurs when encountering Charged Creepers. I'm assuming it has to do with the effect itself.

I tested it in 1.17 and 1.17.1 with only the Iris Shaders mod installed (and without any mods installed, of course).

It also doesn't matter if you have a shader pack enabled or not.

**Comment by AlsoNiko** [comment]
This issue and it's cause are known, and should be fixed in the next release. This crash also happens in 1.16.5

**Comment by coderbot16** [comment]
This was fixed with the new entity batching / buffering code in 1.1.2.
