### ISSUE TITLE
Rendering issue with water in Sildur's

### ISSUE THREAD

**Issue by Pepe20129** [IrisShaders/Iris#69]
When looking straight up to water while the camera is outside of water this happens.

![2021-01-03_17 05 06](https://user-images.githubusercontent.com/72659707/103483513-0a91a280-4de8-11eb-9f55-b57a3cdd414d.png)
![2021-01-03_17 07 24](https://user-images.githubusercontent.com/72659707/103483514-0bc2cf80-4de8-11eb-876b-6b015fb09eff.png)
![2021-01-03_17 14 14](https://user-images.githubusercontent.com/72659707/103483516-0c5b6600-4de8-11eb-8328-66ad622d3c36.png)

**Comment by coderbot16** [comment]
This seems to come down to a vanilla bug. All vertex normals on fluids always point straight up, even when they probably shouldn't.

**Comment by coderbot16** [comment]
Why would this break in this manner, you might wonder? Well, the reflection code is most likely taking the dot product of your view vector with the normal vectors of the water.

Under normal conditions they will never point in the same direction (at least, for things that you can actually see) but in this case they do. That almost certainly results in a division by zero on the GPU, which causes the weird chaos you see here.

**Comment by coderbot16** [comment]
Since this is an issue with vanilla vertex normals, I will further track this issue in #9.
