### ISSUE TITLE
Iris do not increase my FPS, the FPS when I'm using Iris is even lower than using Optifine.

### ISSUE THREAD

**Issue by KyleJKC** [IrisShaders/Iris#690]
### What happened?

As the title said, the FPS deceased. The frame rate is reduced by 5-10 frames, I don't know why.
Here is my computer accessories:
CPU: AMD Ryzen 2700x
GPU: Nvidia GeForce GTX 1660TI
RAM: 16G
I don't load any other mod.
Is this a bug?

### Relevant log output

```shell
N/A
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1 with Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1660TI

### Java Version

Java 16

**Comment by yitzy299** [comment]
Optifine renders around half the number of chunks that iris+sodium does, when on the same render distance. It also utilises the GPU more than optifine

**Comment by yitzy299** [comment]
It's also likely you used shaderpack config to improve performance on optifine, which iris does not yet suppot. We can help try and improve your performance on the discord

**Comment by KyleJKC** [comment]
> It's also likely you used shaderpack config to improve performance on optifine, which iris does not yet suppot. We can help try and improve your performance on the discord

So do you mean I can change the render distance to 4 (I set 8 when using Optifine)?
