### ISSUE TITLE
Chunk unrendering when going down and looking up

### ISSUE THREAD

**Issue by JohnWeak1** [IrisShaders/Iris#693]
### What happened?

when you descend to a lower coord and look up chunks starts to unrender

### Screenshots

![image](https://user-images.githubusercontent.com/42245432/128040394-76ae61ea-09b7-4b8a-96d0-0e275b1bd96f.png)
![image](https://user-images.githubusercontent.com/42245432/128040428-c64dccb1-7a08-4974-85f0-029100351b40.png)
![image](https://user-images.githubusercontent.com/42245432/128040876-1c10c2e3-4f1e-4add-b001-f759d16b8d00.png)

### Iris and Minecraft Version

iris 1.17-1.1.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1050ti

### Java Version

Java 16

### Additional context

I am not running anything else other than iris+sodium

**Comment by coderbot16** [comment]
I'm assuming that this issue still happens if you remove Iris and add Sodium. If so, please ensure that this is reported to Sodium not us. If this issue does not happen with just Sodium but does happen with Iris, please let me know.
