### ISSUE TITLE
Indium incompatibility

### ISSUE THREAD

**Issue by topbun92** [IrisShaders/Iris#703]
### Iris and Minecraft Version

iris - 1.1.2-starline+build.457 , Fabric 11.17.1, MC 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Win10

### What is your GPU?

RTX3080

### Java Version

Java 16

### Reproduction Steps

1. Iris 1.1.1 or Iris starline 1.1.2 w/Sodium 0.3.0 +Iris2 installed
2. install indium-1.0.0-dev.d797129+mc1.17.1
3. stuck in launch loop
![Iris_Indium bug screenshot](https://user-images.githubusercontent.com/87154955/128167692-ba39e065-0d0e-4b3a-bef6-d61835207c7a.png)
[Iris_Indium bug.txt](https://github.com/IrisShaders/Iris/files/6930567/Iris_Indium.bug.txt)

**Comment by AlsoNiko** [comment]
Is this the indium off modrinth?

**Comment by topbun92** [comment]
off of github. i tried the starline sodium fork from github as well as the official sodium .3.0 off modrinth (though I don't think starline works without they're forked version as that threw a different fatal error and just wouldn't launch at all)

**Comment by AlsoNiko** [comment]
You need to try with the official 1.1.1 release of iris and indium off modrinth.

**Comment by topbun92** [comment]
gotcha. will grab the modrinth one. brb

**Comment by topbun92** [comment]
alrighty, exact same problem with official Iris 1.1.1 and indium both off modrinth. removed starline iris as well as starline sodium.

**Comment by topbun92** [comment]
oh lord, okay well it looks like i'm on the hunt for which mod is the problem now lol

**Comment by topbun92** [comment]
which is to say, it worked with just those 3

**Comment by topbun92** [comment]
awe man. it was better end. so hey, very much appreciate your help. also know its not your deal, but would you recommend posting on the better end github or the indium github?

**Comment by AlsoNiko** [comment]
Okay upon taking a closer look this is a conflict with CTMF, they're working on fixing it for the next release iirc
