### ISSUE TITLE
Minecraft Game Output 1.17.1 "OpenGL debug message" Spam

### ISSUE THREAD

**Issue by Type-32** [IrisShaders/Iris#711]
### What happened?

In my Minecraft 1.17.1 Fabric, the Minecraft Output Log spams out messages like this: "[Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'"

This issue is causing FPS lags in my Minecraft, so please help OwO

**My Settings**
![image](https://user-images.githubusercontent.com/87076491/128281564-a798efa0-1913-46c8-bd0f-6b22e38eb8eb.png)
![image](https://user-images.githubusercontent.com/87076491/128281576-9772301b-2f93-4754-9894-57184c28b673.png)
![image](https://user-images.githubusercontent.com/87076491/128281590-218e5509-68e2-4ccf-9911-7e829bf734ce.png)

**Shaders Used**
![image](https://user-images.githubusercontent.com/87076491/128281613-faa64553-cba6-4e96-84f9-a29466721d10.png)

**Mods Used**
![image](https://user-images.githubusercontent.com/87076491/128281649-31ea49b0-b1bb-4d09-a244-baf0c6701a64.png)

Note: No resource packs(except for the Fabric Mod Resources) are loaded when the issue occurred.

**My Entire Output Log**
[latest.log](https://github.com/IrisShaders/Iris/files/6935543/latest.log)

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 860M

### Java Version

Java 16

**Comment by AlsoNiko** [comment]
We're aware and trying to fix it, but these are false errors and this is a dupe issue

**Comment by Type-32** [comment]
Oh and i forgot to mention that this issue happened when I tried to use other shaders(IrisShaders supported shaders) as well.

**Comment by Type-32** [comment]
Ok then.
