### ISSUE TITLE
Memory Leak with Immersive Portals

### ISSUE THREAD

**Issue by Merith-TK** [IrisShaders/Iris#714]
### What happened?

Shaders constantly reload, and minecraft has a heart attack

### Screenshots

https://cdn.merith.tk/assets/minecraft/ip-iris.mp4

### Relevant log output

```shell
https://paste.ee/p/e1C8O
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1, MC 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1060

### Java Version

Java 16

### Additional context

Bug appears to only give nether a heart attack

https://github.com/qouteall/ImmersivePortalsMod/issues/815

**Comment by AlsoNiko** [comment]
Iris and immersive portals are not compatible yet

**Comment by Merith-TK** [comment]
Dont just close it, leave it open so *people can actually find this out* and so devs can actually look at an "Open Issue" and see it, and go "oh hey, this is a problem, lets see how we can fix this!"

**Comment by IMS212** [comment]
This has already been reported under #190 in some form, and there is a pending PR to fix it.

**Comment by DestinyTheGreat** [comment]
https://github.com/IrisShaders/Iris/pull/425
It's already being worked on.
Also, there is such an issue for tracking, which you clearly didn't even attempt to find before making your own:
https://github.com/IrisShaders/Iris/issues/190

**Comment by Merith-TK** [comment]
> This has already been reported under #190 in some form, and there is a pending PR to fix it.

Neat, would be nice to know in the main thing

> #425
> It's already being worked on.z

Oh yay!

> Also, there is such an issue for tracking, which you clearly didn't even attempt to find before making your own:
> #190

This is referencing a crash directly related to Immersive Portals and Iris being together. 

We have found that the End portal works *perfectly fine* when indium is installed, but the nether completely flips its shit with indium, The Portal, when vieweed from overworld, flickers. no big deal right? minor bug.

once your in the nether and your looking at the portal, the nether starts flicking enough for an epileptic warning to become mandatory as the nether lightmap values start getting revealed during these flickers,

This effect happens in reverse if you load into the world in the nether instead of the overworld, 

I would appreciate it if issues would not be closed without even *attempting* to collect more info from the person unless it is obvious. as if you looked at the issue i had linked here, and opened on Immersive Portals, you would see that using the mod "indium" makes it less buggy, but still a problem.

I am opening an issue

**Comment by IMS212** [comment]
I believe the actual issue here is Iris (without said Pr) only creates one pipeline, so the dimensions fight to get control over it and keep remaking it for their own dimension, hence causing the reloading.

**Comment by Merith-TK** [comment]
That does look like the issue, 

Also with Indium, (if you guys would read the issue on immersive portals because it does not seem like you have to me)
It makes it "functional", not good, not release ready, but not immediately killing your game with a black screen or a crash. just revealing the lightmap and dimension/portal flickering

**Comment by drakosoldier298** [comment]
heres something pertaining to this i sent on the immersive portals github https://github.com/qouteall/ImmersivePortalsMod/issues/815#issuecomment-893720513
