### ISSUE TITLE
The TAA in Sildur's Vibrant Shaders breaks on Linux Mesa drivers

### ISSUE THREAD

**Issue by Xyphyn** [IrisShaders/Iris#718]
### What happened?

When using shaders on linux, there is a ghost image overlayed on your screen depending on when shaders were last loaded.

### Screenshots

![image](https://user-images.githubusercontent.com/80978739/128432485-c1c0a805-24de-42bf-be89-0f234def722f.png)

### Iris and Minecraft Version

Iris 1.17.1, 1.1.1

### Are you running Sodium along with Iris?

No

### Operating System

EndeavourOS (Linux kernel 5.13.6)

### What is your GPU?

AMD Radeon RX 570 (XFX Pine Group)

### Java Version

Java 16

**Comment by TheNukeLore** [comment]
What shader is this? Also does it happen with all shaders? I personally haven’t had this issue and I run linux

**Comment by IMS212** [comment]
There have been no reports of issues with Linux so far, this may be driver/software related

**Comment by Miss-Corruption** [comment]
Additionally, please provide a log file so we can narrow down the issue even further. From the couple users that are known to use Linux we have had zero reports like yours so it's most likely Software and/or driver related, as @IMS212 already stated.

**Comment by Rajbir98** [comment]
> What shader is this? Also, does it happen with all shaders? I personally haven’t had this issue and I run Linux

this shader is sildurs vibrant

**Comment by TehcJS** [comment]
I use Ubuntu 20.04 (Mesa, 4.5 core profile), and I can only reproduce this with Sildur's shaders. Have you tried reproducing this on Windows?

**Comment by TehcJS** [comment]
> Additionally, please provide a log file so we can narrow down the issue even further. From the couple users that are known to use Linux we have had zero reports like yours so it's most likely Software and/or driver related, as @IMS212 already stated.

I'm using the default kernel drivers for AMD Radeon provided by Linux. If someone can reproduce this on Nvidia with Linux drivers, then it's probably a driver bug.

As for the lack of Linux bug reports, I'll be sure to look out for Linux-specific bugs, as most people use Windows.

**Comment by RinLovesYou** [comment]
Can't reproduce on Manjaro with nvidia

**Comment by TheNukeLore** [comment]
I use linux mint and am using Mesa drivers for an intel igpu and have not seen this said issue with sildurs

**Comment by AlsoNiko** [comment]
This looks to be the TAA bug with sildurs that affects Linux specifically

**Comment by TheNukeLore** [comment]
That’s the thing. I’ve never seen this before and I’ve used sildurs a good amount

**Comment by coderbot16** [comment]
I've seen this before on my laptop. It only happens with Sildur's Vibrant Shaders Medium or above, only on Linux Mesa drivers, and only with Iris.

**Comment by KayshiAri** [comment]
I get the same thing on my system with AMD graphics
OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.41.0 5.13.5-200.fc34.x86_64 LLVM 12.0.0) v: 4.6 Mesa 21.1.5

**Comment by coderbot16** [comment]
Unless this issue has been fixed, I'm going to keep it open for now so I remember to come back to it later.

**Comment by marcospampi** [comment]
Same here on Vega iGPUs, using Mesa on Fedora 34
[https://youtu.be/6lNr7NgZMrc](video)

**Comment by laclcia** [comment]
OS: Manjaro Linux x86_64 
Host: X470 AORUS ULTRA GAMING 
Kernel: 5.14.1-xanmod1-cacule-1 
DE: Cinnamon 5.0.5 
WM: Mutter (Muffin) 
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: AMD ATI Radeon RX 5500/5500M / Pro 5500M 
Memory: 32026MiB 
Driver: Mesa 21.2.1-1
Sun 05 Sep 2021 07:27:11 PM EDT

same issue here. tested also with a RX 580 and a RX 480 same issue. all of the Sildur's Vibrant shaders have the same problem. none of the other tested shaders tested have the problem. when tested with a GTX 1060 or with a RTX 2060 the problem did not manifest.

**Comment by marcospampi** [comment]
@GlitchSlayed anyway should be investigated on why TAA had this issue, it's working on OptiFine, albeit with chronic frame dropping.

**Comment by pjalsGit** [comment]
for me it happens with (almost) all shaders which are seus, sildur's, or complementary- based

**Comment by Aagame3** [comment]
I'm having this issue with Sildur's vibrant on EndeavourOS with Amd rx6600xt and mesa 21.2.5-1. Disabling TAA did not help.

**Comment by avanishsubbiah** [comment]
I'm running Sildur's vibrant with PopOS, 6800xt, and mesa 21.2.2 and I'm having the same issue of weird TAA flickering. How do does one disable TAA in a minecraft shader?
