### ISSUE TITLE
Z-fighting issue

### ISSUE THREAD

**Issue by JayCeeCreates** [IrisShaders/Iris#719]
### What happened?

Iris causes some flat blocks to render incorrectly, z-fighting occurs especially when said flat block collides with another block. The screenshot exemplifies the issue with stick blocks from my mod EarlyGame.

### Screenshots

![Screenshot_20210806_122022](https://user-images.githubusercontent.com/28774264/128455504-93117209-d624-45f9-ae68-dbc0d1647387.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1 (1.17.1)

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch Linux

### What is your GPU?

GTX 980M

### Java Version

16

**Comment by NoComment1105** [comment]
Can this be re-created without iris?

**Comment by JayCeeCreates** [comment]
Removed Iris and z-fighting doesn't occur

**Comment by NoComment1105** [comment]
Was this fighting seen with shaders on or off? or both

**Comment by JayCeeCreates** [comment]
Both

**Comment by JayCeeCreates** [comment]
The temporary solution I can think of is to raise the flat block by 0.01 units tho soooooo

**Comment by coderbot16** [comment]
This is almost certainly a Sodium issue, not an Iris issue.

**Comment by JayCeeCreates** [comment]
> This is almost certainly a Sodium issue, not an Iris issue.

Well, you convinced me. I tried it with Sodium and it IS a Sodium issue. Gonna be closing it-
