### ISSUE TITLE
With "Iris" mod i can't see the mob hurt red color

### ISSUE THREAD

**Issue by KpauMupa** [IrisShaders/Iris#72]
In a regular game, if i hit the mob it will turn red for a second, but with Iris (im running ./gradlew runclient) they don't turn red! This isn't a big issue, but still feels uncomfortable. This issue is happening with any shaderpack, even with (internal).
Can't record a video, but here is a screenshot =))))
![2021-01-04_21 47 02](https://user-images.githubusercontent.com/76217453/103568580-d8ab3980-4ed6-11eb-9d5d-4ef18e96fbdc.png)

**Comment by IMS212** [comment]
I believe this is due to entities not being rendered with gbuffers_entities yet, however I’m not sure. however can replicate

**Comment by KpauMupa** [comment]
Just noticed that an issue about this already exists, sorry.

**Comment by coderbot16** [comment]
This is a separate issue from gbuffers_entities and happens because entityColor isn't fully supported currently.

**Comment by altrisi** [comment]
While it now works when shaders are on, I still can't see the red flash with shaders off (using Sodium too though that shouldn't matter).

Should this be reopened, or should I open a new issue?

**Comment by AlsoNiko** [comment]
It is that bug being closed on accident, good catch!
