### ISSUE TITLE
无法设置光影&seus ptgi hrr2.1test水面闪烁

### ISSUE THREAD

**Issue by zengyaoqi** [IrisShaders/Iris#720]
rt

**Comment by NoComment1105** [comment]
[for devs, direct google translate] The flickering surface of the water cannot be set to light and shadow sesseus ptgi hrr2.1test

**Comment by IMS212** [comment]
SEUS PTGI is not supported yet.

**Comment by noeru-desu** [comment]
如果你需要设置光影，你可以使用[HyperCubeMC的fork版本](https://github.com/HyperCubeMC/Iris)

**Comment by NoComment1105** [comment]
> 如果你需要设置光影，你可以使用[HyperCubeMC的fork版本](https://github.com/HyperCubeMC/Iris)

No. Dont use this. It is not supported by us and has many bugs

**Comment by Miss-Corruption** [comment]
In summary:

- SEUS PTGI is not supported as of now.
- Shader Options/Configurations are planned but not yet implemented.
- The Starline Fork is unofficial and therefore not supported by us. We do not recommend using it and any issues with it should be reported to the fork's maintainer.
