### ISSUE TITLE
iris mod spams log when font resource pack is applied

### ISSUE THREAD

**Issue by wb1016** [IrisShaders/Iris#722]
### What happened?

when font resource pack is applied, iris spams log with this:
` [Render thread/WARN]: Iris has detected a non-wrapped render layer, it will not be rendered with the correct shader program: text_intensity `
this message should be logged only one time, but it does as much as it can.
this logged 17940 lines in 31 secs, around 578 lines per second.
log spam can be a big issue not only in debugging, even in long-time gameplay.
this problem never happend again after i got rid of font mod.

### Iris and Minecraft Version

sodium@0.3.0+IRIS2-build.94  iris@1.1.1  minecraft@1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10 21H1 x64

### What is your GPU?

Radeon RX 590

### Java Version

AdoptOpenJDK 16.0.1

### Additional context

[nanumsquare-eb.zip](https://github.com/IrisShaders/Iris/files/6948832/nanumsquare-eb.zip)
resource pack file for reproduce.
minecraft client may mark it incompatible due to its `pack.mcmeta` file, but it is compatible with any version since 1.16

**Comment by IMS212** [comment]
Should be fixed with https://github.com/IrisShaders/Iris/commit/834eeee9df0298222a3893e365a20916cdebf827.
