### ISSUE TITLE
Add parallax occlusion mapping 

### ISSUE THREAD

**Issue by HeroRyker** [IrisShaders/Iris#724]
Please add an option for POM it makes the texture packs so much better.

**Comment by ColdIce1605** [comment]
Sorry, but POM is a shader pack feature what your looking for is normal textures and maybe in some weird format a specular texture, also used for PBR in many cases tho isn't strictly needed, (Chronos is a good example or anything the hardcoded IDs)

**Comment by IMS212** [comment]
Duplicate of #130.
