### ISSUE TITLE
name tags turn red when using font and shader

### ISSUE THREAD

**Issue by Buggitt** [IrisShaders/Iris#725]
### What happened?

When using [Fabulously Optimized (beta 2)](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized) with [sildurs shaders](https://sildurs-shaders.github.io/) and then adding this [roboto font](https://www.curseforge.com/minecraft/texture-packs/hd-font-roboto) it makes all nametags (player and animals) red and have a black fill.
If I turn off either the font or the shader it goes back to white.

Brought this issue up with the font pack creator and [they said](https://www.curseforge.com/minecraft/texture-packs/hd-font-roboto?comment=31) it seemed like an iris bug. 

### Screenshots

![image](https://user-images.githubusercontent.com/7709438/128617740-68f3b130-8d6c-4974-b65f-2497719dee36.png)

### Iris and Minecraft Version

Minecraft 1.17.1, Fabric 0.11.6, Iris 1.1.1, Fabulously Optimized-2.1.0-beta.2

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX1070Ti

### Java Version

Java 16

**Comment by NoComment1105** [comment]
Could you try with just iris and robofont please. There could be incompatibility somewhere else

**Comment by Buggitt** [comment]
> 
> 
> Could you try with just iris and robofont please. There could be incompatibility somewhere else

Same behavior with only Iris 1.1.1, shader, font installed on fabric 0.11.6

**Comment by coderbot16** [comment]
This has been fixed in https://github.com/IrisShaders/Iris/commit/76c14427fd7fcf597e56d6cb2df78aa5217bf7a5 and a fix will be pushed out with the next public release.
