### ISSUE TITLE
Using shaders breaks texture on custom armor used on the Origin Realms server.

### ISSUE THREAD

**Issue by CROOT-ROM** [IrisShaders/Iris#728]
### What happened?

When I turned on Complementary Shaders on the Origin Realms server, the textures for the custom armor broke. Turning it off again makes the textures appear normal.

### Screenshots

![image](https://user-images.githubusercontent.com/68515101/128640026-1e3367d1-8280-4f86-bcb5-3df9e34afc46.png)
this is with shaders
![image](https://user-images.githubusercontent.com/68515101/128640078-7b868d28-a299-4751-beac-476bad90ba20.png)
without shaders
![2021-08-08_12 33 21](https://user-images.githubusercontent.com/68515101/128640549-70195705-2d96-404e-ba94-a63927dbc7b3.png)
With Complementary Shaders and Optifine

### Relevant log output

[latest.log](https://github.com/IrisShaders/Iris/files/6951202/latest.log)

### Iris and Minecraft Version

Minecraft 1.17.1, iris-mc1.17-1.1.1.jar

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1660

### Java Version

Java 16

### Additional context

 The issue does not occur with optifine.
 It seems the armor the server uses, relies on the built in 1.17 shaders feature to change the textures.

**Comment by AlsoNiko** [comment]
We need a log file

**Comment by AlsoNiko** [comment]
Also a screenshot with f3 showing the armor doesn't break with optifine would be helpful

**Comment by CROOT-ROM** [comment]
Updated to have a log file during texture failure, and a screenshot with optifine.

**Comment by coderbot16** [comment]
Origin Realms is relying on core shaders for custom armor, which we can't support. Keeping this open for documentation's sake.

**Comment by coderbot16** [comment]
Merging into https://github.com/IrisShaders/Iris/issues/1042
