### ISSUE TITLE
Weird shapes/textures when using Xaero's minimap and Xaero's world map

### ISSUE THREAD

**Issue by labbo-lab** [IrisShaders/Iris#732]
### What happened?

A bug happened! 
Basically glitchy mess
(XaerosWorldMap_1.16.0_Fabric_1.17.1.jar)
(Xaeros_Minimap_21.14.1_Fabric_1.17.1.jar)
(fabric-api-0.37.2+1.17.jar)
(using TLauncher)
(on server)

### Screenshots

![2021-08-08_17 38 49](https://user-images.githubusercontent.com/62490883/128647847-410c47e8-3ead-41d2-ade6-7672c71bd623.png)
![2021-08-08_17 17 12](https://user-images.githubusercontent.com/62490883/128647851-e641d0ce-dc15-47b5-ace4-f48109f863dd.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar for minecraft 1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

windows 10

### What is your GPU?

AMD A9-9425 RADEON R5

### Java Version

Java 16

**Comment by AlsoNiko** [comment]
This is a bug with sodium and we don't support Tlauncher.
