### ISSUE TITLE
Game crashes as soon as a shader is loaded

### ISSUE THREAD

**Issue by rubixcube-614** [IrisShaders/Iris#743]
**Iris and Minecraft Version**

iris-fabric-loader-0.11.5-1.17.1

**Are you running Sodium along with Iris?**

Yes

**Operating System**

Ubuntu 18.04

**What is your GPU?**

NVIDIA GeForce GT 720M/PCIe/SSE2

**Java Version**

Java 16

**Reproduction Steps**

1. Open a minecraft world
2. Select any shader and run it
3. Crash

[crash-2021-08-10_10.50.13-client.txt](https://github.com/IrisShaders/Iris/files/6959122/crash-2021-08-10_10.50.13-client.txt)

**Comment by IMS212** [comment]
Please upload a full log file.

**Comment by rubixcube-614** [comment]
i have put the log file

**Comment by NoComment1105** [comment]
we need the `.log` file. The crash log doesnt provide all the info in this case

**Comment by rubixcube-614** [comment]
okay, wait

**Comment by rubixcube-614** [comment]
[2021-08-10-2.log.gz](https://github.com/IrisShaders/Iris/files/6966009/2021-08-10-2.log.gz)

**Comment by rubixcube-614** [comment]
ig this is the one

**Comment by NoComment1105** [comment]
It is... only  from what i can see it doesnt provide any differing information. Ill need to wait until someone else can identify this.

**Comment by NoComment1105** [comment]
From what we can tell, you are using a shader that is unsupported by Iris at this current moment in time

**Comment by rubixcube-614** [comment]
> From what we can tell, you are using a shader that is unsupported by Iris at this current moment in time

I am using BSL v8, which is clearly stated as supported in the the Iris page

**Comment by AlsoNiko** [comment]
Please try updating your gpu driver to the latest avaliable, you have 340.108, latest should be 442.19

**Comment by rubixcube-614** [comment]
well, i tried that, but for some reason that driver doesnt even use the GPU

**Comment by NoComment1105** [comment]
The game doesnt use the gpu after you install the latest driver?

**Comment by rubixcube-614** [comment]
The OS doesn't detect the GPU

**Comment by 104bytes** [comment]
> The OS doesn't detect the GPU

If you've a Nvidia card, open the Nvidia Control Panel, manage 3D settings, and ensure 'High performance NVIDIA processor' is selected as shown. Not that that'll fix the crashing issues, though. 
![image](https://user-images.githubusercontent.com/37977339/129650742-99b12dd0-77b0-4486-8228-b70297a6f42d.png)

**Comment by IMS212** [comment]
This seems like a recent nvidia OpenGL quirk, according to https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/187711/error-c5121-multiple-bindings-to-output-semantic-c/. Changing the used GPU could definitely change the output in this case.

**Comment by rubixcube-614** [comment]
I found out the the latest nvidia driver (470) doesnt support my GPU, the latest driver that is support is 390

**Comment by rubixcube-614** [comment]
> > The OS doesn't detect the GPU
> 
> If you've a Nvidia card, open the Nvidia Control Panel, manage 3D settings, and ensure 'High performance NVIDIA processor' is selected as shown. Not that that'll fix the crashing issues, though.
> ![image](https://user-images.githubusercontent.com/37977339/129650742-99b12dd0-77b0-4486-8228-b70297a6f42d.png)

umm....that is for windows, i use Linux

**Comment by rubixcube-614** [comment]
I tested with the new driver and it worked perfectly

**Comment by IMS212** [comment]
Then this was likely due to a mismatched driver.
