### ISSUE TITLE
Iris Universal jar installer loads nothing

### ISSUE THREAD

**Issue by NotNocky** [IrisShaders/Iris#747]
### What happened?

Loading the Iris-Installer-2.0.0.jar just shows the blank white box, terminal output shows `Launching installer...` `Launched!`

probably useful info
kernel version 5.10.52, using Xorg, java version 1.8.0_292

### Screenshots

![image](https://user-images.githubusercontent.com/65059771/128967115-2e64b92d-a248-4157-8f5f-47a868c15e68.png)

### Iris and Minecraft Version

Iris-Installer-2.0.0.jar from https://irisshaders.net/download.html

### Are you running Sodium along with Iris?

Yes

### Operating System

Linux

### What is your GPU?

gtx1650

### Java Version

`java -version` gives openjdk version "1.8.0_292" OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10) OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

**Comment by AlsoNiko** [comment]
Are there any errors in console?

**Comment by AlsoNiko** [comment]
Update: please test this https://bbs.archlinux.org/viewtopic.php?id=159016

**Comment by Spydr06** [comment]
> Update: please test this https://bbs.archlinux.org/viewtopic.php?id=159016

Yes, that works perfectly!
So in the end you just need these two commands:
```bash
export _JAVA_AWT_WM_NONREPARENTING=1
```
```bash
java -jar Iris-Installer-2.0.0.jar
```

**Comment by AlsoNiko** [comment]
So my theory about this being a Linux issues and not an installer issues was correct, which well I'm not happy about, is nice to see

**Comment by Spydr06** [comment]
> So my theory about this being a Linux issues and not an installer issues was correct, which well I'm not happy about, is nice to see

Yes, probably. I've added the `export` to my `.bashrc` file, I'll see if it affects other gui applications.

**Comment by NotNocky** [comment]
can confirm, works here as well. thank you Niko
