### ISSUE TITLE
A render bug？

### ISSUE THREAD

**Issue by KizunaAikawa** [IrisShaders/Iris#749]
### What happened?

I built a glass roof for my underwater building，I could see the strange shadow when I look up.

### Screenshots

![8b46c2b001ddc4a8da1a042aee44085](https://user-images.githubusercontent.com/40119466/128998609-93dde086-2756-416f-85fb-dfe6a4f11da9.png)
![90860d85ddf29fea27105b131d6f2fd](https://user-images.githubusercontent.com/40119466/128998629-17fca006-f9fd-475b-b50e-4c1f58b8014f.png)
![a1422de4f4c248e27207be50d73d92c](https://user-images.githubusercontent.com/40119466/128998679-72496672-070f-4280-abc5-0912d15256cc.png)
![76dc00b96c734ce3dbbcefba8e4f36e](https://user-images.githubusercontent.com/40119466/128998649-c5b91031-b994-4eb3-8f38-e00b91eeb16a.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar for minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

RTX 2060

### Java Version

Java 16

**Comment by NoComment1105** [comment]
Known  bug with sodium.
Here is the relevant issue
https://github.com/CaffeineMC/sodium-fabric/issues/38
