### ISSUE TITLE
Crash Before MC Launches

### ISSUE THREAD

**Issue by peterodavies27atgmailcom** [IrisShaders/Iris#75]
MC doesn't start when I press launch. (I am using [MultiMC](https://multimc.org/) but I don't think that's the problem)

[Log](https://paste.ee/p/wieMR)

**Comment by IMS212** [comment]
You need the iris fork of sodium [here](https://github.com/IrisShaders/sodium-fabric) if you wish to use sodium with Iris (note that some things may not work as sodium compatibility is not finished)

**Comment by peterodavies27atgmailcom** [comment]
I tried to get the jar file from actions, but it wasn't there, so I had to compile it and it ended with BUILD FAILED.

[log](https://paste.ee/p/KzYSg)
Also do I call it a log if it's from command prompt?

**Comment by IMS212** [comment]
you need to first build iris, then copy the iris jar (not dev or sources) to sodium-fabric-1.16.x-iris/.gradle/loom-cache/remapped_mods/Iris-0.1.0.jar then try rebuilding sodium

**Comment by peterodavies27atgmailcom** [comment]
ohhhh ok. thank you very much

**Comment by peterodavies27atgmailcom** [comment]
![Screenshot 2021-01-05 184450](https://user-images.githubusercontent.com/69123018/103711785-2763dc80-4f86-11eb-80ad-ebd9782f29f2.jpg)
so now I have these files, do I use the iris-0.1.0.jar or one of the other ones?
(I'm sorry I don't know these things)

**Comment by IMS212** [comment]
no, do gradlew build in sodium again, then go to sodium-fabric-1.16.x-iris/build/libs and use the sodium jar without dev or sources

**Comment by peterodavies27atgmailcom** [comment]
I didn't get a libs folder

**Comment by IMS212** [comment]
Did you build sodium, and did the build succeed?

**Comment by peterodavies27atgmailcom** [comment]
I have to go, sorry, I built sodium-fabric-1.16.x-stable if that's what you meant by sodium, and I'm just confused, but anyways, I have to go, so I'll ask another time

**Comment by supsm** [comment]
It would probably be easier for us if you asked for help on discord instead. https://discord.gg/jQJnav2jPu
