### ISSUE TITLE
More Shader Performance

### ISSUE THREAD

**Issue by SirPytan** [IrisShaders/Iris#754]
I am using all kind of performance mods, to increase my fps and so on to be able to play with a high render distance.

I am using this mod in the sodium edition and the following mods:
- Lithium
- Starlight (rewrite of the Light Engine)
- Dynamic FPS
- LazyDFU
- Hydrogen
- Krypton
- Sodium Extra
- Indium (to be able to use other mods that use the Fabric Rendering API)

My Specs:
Gigabyte Aorus RTX 2080 Ti
i7-7820X 3.6Ghz - 4.5Ghz, 8 Cores, 16 Threads
32GB 3200Mhz DDR4 Ram (4-20GB for Java)
SSD with Minecraft: WD Black SN750 1TB
Screen: 4K Native resolution

And I would like to play with 32 chunks render distance, with Complementary, Continuum or SEUS PTGI Shaders, while using Patrix PBR 128px Texture Pack, but I can't play completely fluently. I had to reduce my render distance to 16 chunks to have an acceptable refresh rate of min 30fps but more about 45-60 fps in VSync mode.

The most performance impact have still the shaders and the render distance.

I also try to use structure and cave and world generating mods, with all those + a few quality of live mods I can be happy if I have 30 fps at max.

So one feature request would be to be able to maybe render at a lower resolution and scale the image up or to improve the performance of the shaders even more.

**Comment by yitzy299** [comment]
You can turn down the settings of shaders if you want, and 128x resource packs are very intensive in terms of vram. Either use a less demanding shader, or a less demanding resource pack. 32 chunks is also a very intensive setting

**Comment by SirPytan** [comment]
I know, I am also fine with 20 chunks render distance, but I have a very capable machine, so I wonder where the bottleneck is, also how do I change the shader settings? There is no menu.

**Comment by SirPytan** [comment]
@yitzy299 Also why did you close this, after not even waiting for an answer from me?

**Comment by yitzy299** [comment]
Support is provided on the discord, if your hardware cannot keep up with a 128x resource pack, intensive shaders and 32 render distance it isn't an iris bug

**Comment by AlsoNiko** [comment]
More shader performance is not a vallid issue, and also settings are not fully implemented yet. Finally running very high end shaders at the highest render distance, at 4k, with a 128x pack is a lot, even for high end systems. (Also PBR is not yet supported)

**Comment by SirPytan** [comment]
I don't consider it a bug either, I mean it would just be nice to be able to reduce the render resolution by half or something like this.

**Comment by AlsoNiko** [comment]
Press Shift+P in video settings to access the menu for it

**Comment by yitzy299** [comment]
Or via an option in the vanilla launcher.

**Comment by SirPytan** [comment]
Yes, thanks found it.
