### ISSUE TITLE
Strange flickering and shadows with postprocessing

### ISSUE THREAD

**Issue by marcospampi** [IrisShaders/Iris#755]
### What happened?

Using Sildur's vibrant shaders with medium quality and up presents some strange visual effects, such as image's flickering and abnormal shadows where shouldn't be any.
I'm using a Vega 8 coupled with a Ryzen 5700U, I decided to shot a short screen cast as the flickering is very visible as I switch from Lite config to Medium and up.

### Screenshots

[https://youtu.be/6lNr7NgZMrc](https://youtu.be/6lNr7NgZMrc)

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Fedora Workstation 34

### What is your GPU?

AMD Renoir / Vega 8 1.9GHz

### Java Version

Java 16

### Additional context

[log file](https://github.com/IrisShaders/Iris/files/6983229/latest.log)

**Comment by AlsoNiko** [comment]
please add a log file, and if you're on windows or linux

**Comment by marcospampi** [comment]
[latest.log](https://github.com/IrisShaders/Iris/files/6983229/latest.log)
it is A GIANT LOG, after few lines there are mourns about unsupported stuff

**Comment by AlsoNiko** [comment]
That's normal, Linux or windows matters as well

**Comment by marcospampi** [comment]
Duplicate [https://github.com/IrisShaders/Iris/issues/718]( issue #718 )
