### ISSUE TITLE
Shader change upon entering a new dimension

### ISSUE THREAD

**Issue by just-chubbyfoxx** [IrisShaders/Iris#756]
Make it so you can set it to change your shaders automatically upon entering a new dimension
(For example, comp in the overworld. Sildurs in the end, etc)

**Comment by just-chubbyfoxx** [comment]
Addition because IMS had a fucking great idea to this
Shader settings change to snow mode when it snows

**Comment by IMS212** [comment]
This one wouldn’t realistically be possible right now, but the first issue stands.

**Comment by coderbot16** [comment]
Superseded by https://github.com/IrisShaders/Iris/issues/1216.
