### ISSUE TITLE
Item rendering | Folder structure | Crash

### ISSUE THREAD

**Issue by UltraBlackLinux** [IrisShaders/Iris#76]
Hey, there,
I just discovered this project via [this](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) gist, and I have to say, I am very happy, that somebody is working on an alternative to Optifine. 
Firstly, I just started up my client, and my first question is: How and do I have to put the shaders in a folder? Just extract the shader zip or copy the "shaders" folder out?
Next: Items/Player(s) aren't rendered correctly. The Player's hand is invisible, the Player iself and many items are kinda seethrough.

![Screenshot_20210106_214247](https://user-images.githubusercontent.com/62404294/103818682-48e9c480-5069-11eb-89d7-2e75ac72d35e.png)
![Screenshot_20210106_214304](https://user-images.githubusercontent.com/62404294/103818684-49825b00-5069-11eb-8a12-f13657270761.png)
![Screenshot_20210106_214621](https://user-images.githubusercontent.com/62404294/103818688-4ab38800-5069-11eb-8809-b9c7a4a835a8.png)

The red screenshot is from the Limbo (to demonstrate the translucency), don't ask me why.
The few seconds, it actually worked, I tried to use the Complementary shaders. - More or less as a joke. 
After this I always get this fancy crash here: [log.txt](https://github.com/IrisShaders/Iris/files/5778155/log.txt) so I couldn't test any other shaders... 

Thanks for this project!

**Comment by coderbot16** [comment]
> Just extract the shader zip or copy the "shaders" folder out?

No need to extract the ZIP with the latest commits, just put it in shaderpacks and edit iris.properties accordingly.

> Items/Player(s) aren't rendered correctly. The Player's hand is invisible, the Player iself and many items are kinda seethrough.

I assume that happens on internal shaders? Does this happen with *just* Iris installed?

> After this I always get this fancy crash here: log.txt so I couldn't test any other shaders...

That crash seems to be related to https://bugs.mojang.com/browse/MC-31618. I wonder if this is because NoiseTexture uses the RGB internal format, perhaps AMD drivers have issues when converting this to RGBA? It's hard to test this without having a machine with AMD hardware running windows, but I will do a bit of digging.

> Thanks for this project!

You're welcome!

**Comment by UltraBlackLinux** [comment]
That actually were the Internal shaders, I didn't notice, there was a config file ;)
I hope there will be a setting for the modmenu at some point.
The crash, I talked about happens when starting up the game, when the main menu fades in.

**Comment by coderbot16** [comment]
Can you verify if any of the issues here are still relevant with the latest commits? The issues here should have been fixed afaik.

**Comment by UltraBlackLinux** [comment]
> Can you verify if any of the issues here are still relevant with the latest commits? The issues here should have been fixed afaik.

Works now :)

**Comment by UltraBlackLinux** [comment]
should propably consider closing this XD
