### ISSUE TITLE
Shader settings

### ISSUE THREAD

**Issue by Unimatrix36** [IrisShaders/Iris#760]
When I used Optifine I could enter the settings/options for the shaders in the video menu.
Like changing color of the light and water. Disable the waving effects on leaves and such.
I can't do that with the Iris Shaders.

It would be nice to have a settings feature for the shaders because I find the orange color of the light at night and when you are in caves are a bit annoying.

![1](https://user-images.githubusercontent.com/64376926/129485873-b4493d09-8e84-40cf-9208-83730412181f.png)
![2](https://user-images.githubusercontent.com/64376926/129485874-30e7bf84-8080-4e65-a2d7-288e72cf0c91.png)
![3](https://user-images.githubusercontent.com/64376926/129485875-417d669d-1bed-4742-9701-0bbd8647a9cf.png)
![4](https://user-images.githubusercontent.com/64376926/129485876-6d599a7a-d116-428c-81b4-2c7e97c91bf9.png)

**Comment by IMS212** [comment]
This is already being tracked in #663.

**Comment by NoComment1105** [comment]
This is in development.
