### ISSUE TITLE
Missing Chunks

### ISSUE THREAD

**Issue by Add1ctG2** [IrisShaders/Iris#763]
### What happened?

many chunks is invisible

### Screenshots

![Screenshot_168](https://user-images.githubusercontent.com/85035925/129745468-72b2ed7f-3807-4b40-a486-a21d245f78a0.png)

### Iris and Minecraft Version

iris 1.1.1 for 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

1060 6gb

### Java Version

1.17

**Comment by Rajbir98** [comment]
which shader pack you are using

**Comment by coderbot16** [comment]
This should have been mostly fixed in 1.1.2 with the update to Sodium 0.3.2. If this issue still occurs, let us know.
