### ISSUE TITLE
Iris shouldn't render things in the shadow pass if the shadow distance is zero

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#764]
If the shadow distance is zero, then nothing can possibly show up in the shadow map (unless the shader pack is doing really weird things).

**Comment by IMS212** [comment]
Could we easily fix this with a 0 check at the beginning of renderShadows?

**Comment by coderbot16** [comment]
Sorta - the shadow textures should still be properly cleared, but rendering terrain / entities / etc shouldn't be necessary.

**Comment by IMS212** [comment]
Going to look into a major refractor of ShadowRenderer later today, having everything in renderShadows isn't too ideal.

**Comment by IMS212** [comment]
Fixed in b73958628.
