### ISSUE TITLE
Add a shader settings button.

### ISSUE THREAD

**Issue by matte0s** [IrisShaders/Iris#767]
**Is your feature request related to a problem? Please describe.**
No not at all but optifine has a shader option button to change shadersettings. Iris doesnt have this. Shaders like BSL can be heavily customized if this was added to Iris

**Describe the solution you'd like**
Stated in the first line

**Describe alternatives you've considered**
I have states these in the first question.

**Additional context**
![image](https://user-images.githubusercontent.com/63752298/129972836-85ca80f3-bdf6-4b03-b1c9-e064bb155fb4.png) No options button, would be great to see in the future :)

**Comment by AlsoNiko** [comment]
Issue #663 the pinned issue, covers this already.
