### ISSUE TITLE
Weird iron bars texture

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#770]
### What happened?

I didn't do anything to trigger the bugs, just put glasses on the side.
It is not reproducible in vanilla

https://user-images.githubusercontent.com/68275908/130038864-3add5608-a938-411d-92d2-578c81e16a4b.mp4

### Screenshots

![2021-08-19_10 47 33](https://user-images.githubusercontent.com/68275908/130039046-82c57cdb-7248-4663-9ccf-19ba6a5e2c2e.png)
![2021-08-19_10 47 31](https://user-images.githubusercontent.com/68275908/130039047-a1cef80b-4d3f-42d5-93ee-044ce1ce7730.png)

### Iris and Minecraft Version

iris-fabric-loader-0.11.5-1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 16 and 17

**Comment by NoComment1105** [comment]
As far as I am aware this is a vanilla bug, but since you say it's not reproducable it will need further checkz

**Comment by Lolothepro** [comment]
It seems to me that it has been solved

**Comment by NoComment1105** [comment]
I know vanilla tweaks has a resource pack that fixes this, are you running it?

**Comment by Lolothepro** [comment]
No i will try

**Comment by Lolothepro** [comment]
That works !!

**Comment by NoComment1105** [comment]
Cool. I'm personally convinced this is a vanilla bug but I'm glad that works

**Comment by Lolothepro** [comment]
But I'm sure the vanilla bug was patched, surely the vanilla patch doesn't work

**Comment by NoComment1105** [comment]
Yeah, tis odd. I'll look into it later when I'm home, unless someone else does before

**Comment by Lolothepro** [comment]
https://bugs.mojang.com/browse/MC-192420
That's it

**Comment by NoComment1105** [comment]
Interesting
