### ISSUE TITLE
Support loading the gbuffers_lines program

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#772]
This program was added as part of OptiFine's attempts to get lines to render properly with 1.17's new line rendering methods. While we now have a way of patching gbuffers_basic to work properly with line rendering, it's possible that some shaderpacks might want to provide their own program.

In addition, it would make sense to give access to the proper variables and inputs needed for shader packs to handle the new line rendering themselves.

**Comment by IMS212** [comment]
This should be quite easy in retrospect, just skip loading and patching basic if lines exists and use lines instead
