### ISSUE TITLE
Crashing related to reentrant entity rendering and mod compat?

### ISSUE THREAD

**Issue by KyleUltimate** [IrisShaders/Iris#777]
### Iris and Minecraft Version

iris-1.1.2-pre+rev.dcc1352+sodium 0.3.0+IRIS2-rev.6a84168

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch linux

### What is your GPU?

MSI RX5700xt+mesa

### Java Version

adoptoopenjdk java 16

### Reproduction Steps

The problem is I can't reproduce it, since this happens on a build server that is constantly changing.

### Crash Report file and latest.log

```shell
log:https://paste.ee/p/DxLou
crash report:https://gist.github.com/KyleUltimate/b9986c01f13d9737d67dd1ce8b0d8c6b
```

### Additional context

server is `hypercubemc.tk` -- plots
sorry for not being able to provide reproduction steps
mods:
![image](https://user-images.githubusercontent.com/68589851/130314734-83537792-3538-44c1-ae32-84b2c9409b10.png)

**Comment by coderbot16** [comment]
Is this crash still occurring?

**Comment by KyleUltimate** [comment]
Nothing similar has happened since 1.1.2 release.
