### ISSUE TITLE
Iris+sodium on AMD = that...

### ISSUE THREAD

**Issue by KpauMupa** [IrisShaders/Iris#78]
![2021-01-08_20 42 11](https://user-images.githubusercontent.com/76217453/104047124-2e8f2280-51f2-11eb-9d50-a41ceed187f7.png)
I understand that mod doesn't support sodium now, but i've seen ppl using it with sodium and having almost 0 problems =)

**Comment by KpauMupa** [comment]
![2021-01-08_20 45 24](https://user-images.githubusercontent.com/76217453/104047277-744beb00-51f2-11eb-9fe4-35ff6208514f.png)
biqq hole... it's the end of the world...

**Comment by coderbot16** [comment]
Ensure that you're on the Iris sodium-compatibility branch and the Sodium 1.16.x/iris branch, then try switching to the Multidraw renderer and see what happens.

**Comment by KpauMupa** [comment]
> 
> 
> Ensure that you're on the Iris sodium-compatibility branch and the Sodium 1.16.x/iris branch, then try switching to the Multidraw renderer and see what happens.

Excuse me, but where is the sodium 1.16.x/iris branch?
![изображение](https://user-images.githubusercontent.com/76217453/104052846-5afb6c80-51fb-11eb-9c91-2dfc63db215b.png)

**Comment by KpauMupa** [comment]
> 
> 
> Ensure that you're on the Iris sodium-compatibility branch and the Sodium 1.16.x/iris branch, then try switching to the Multidraw renderer and see what happens.

if i try to run minecraft with only iris sodium-compatibility+sodium 0.1.0 the game can't even load

**Comment by OverlordsIII** [comment]
You need the custom [fork of sodium for iris](https://github.com/IrisShaders/sodium-fabric) and the sodium compatibility branch jars that you can get [here](https://github.com/IrisShaders/Iris/suites/1741623309/artifacts/33058446)

**Comment by KpauMupa** [comment]
> 
> 
> You need the custom [fork of sodium for iris](https://github.com/IrisShaders/sodium-fabric) and the sodium compatibility branch jars that you can get [here](https://github.com/IrisShaders/Iris/suites/1741623309/artifacts/33058446)

Thank you! Im new to github and don't really understand where to find needed files =)

**Comment by KpauMupa** [comment]
> 
> 
> You need the custom [fork of sodium for iris](https://github.com/IrisShaders/sodium-fabric) and the sodium compatibility branch jars that you can get [here](https://github.com/IrisShaders/Iris/suites/1741623309/artifacts/33058446)

![изображение](https://user-images.githubusercontent.com/76217453/104053681-bda13800-51fc-11eb-933a-cf362068cbfd.png)
i can't compile the sodium mod

**Comment by OverlordsIII** [comment]
you need to put the sodium compatibility iris jar inside `.gradle/loom-cache/1.16.4-whatever` of the sodium fork project

**Comment by OverlordsIII** [comment]
Or you can compile the sodium compatibility iris jar and run `gradlew publishToMavenLocal`

**Comment by KpauMupa** [comment]
> 
> 
> You need the custom [fork of sodium for iris](https://github.com/IrisShaders/sodium-fabric) and the sodium compatibility branch jars that you can get [here](https://github.com/IrisShaders/Iris/suites/1741623309/artifacts/33058446)

![изображение](https://user-images.githubusercontent.com/76217453/104053681-bda13800-51fc-11eb-933a-cf362068cbfd.png)
i can't compile the sodium mod

> 
> 
> Or you can compile the sodium compatibility iris jar and run `gradlew publishToMavenLocal`

![изображение](https://user-images.githubusercontent.com/76217453/104054380-0ad1d980-51fe-11eb-81a8-3ab80cb52f35.png)
im sorry, but what's wrong?

**Comment by KpauMupa** [comment]
> 
> 
> Or you can compile the sodium compatibility iris jar and run `gradlew publishToMavenLocal`

OOOF my head ran into a problem, initiating emergency shutdown...

**Comment by OverlordsIII** [comment]
Tou need fabric api as well

**Comment by KpauMupa** [comment]
> 
> 
> Tou need fabric api as well

bRUH how could i forget about fabric api... thank you! Now i can run iris with sodium. Unfortunately, the perfomance is not that good as i expected, but when the optimisation comes out it'll be super. I hope=) Ty very much for help!

**Comment by KpauMupa** [comment]
> 
> 
> Tou need fabric api as well

Yay, finally cool shaders with 60 fps!!! Even fully complete optifine can't run sildur's vibrant lite on my pc so smooth... Amazing mod!
![2021-01-08_23 22 56](https://user-images.githubusercontent.com/76217453/104084246-8bbcbf80-5256-11eb-841d-7a412227d8a1.png)
And i think i should close this issue, cuz it isn't even an issue, i just picked the wrong mod version.

**Comment by coderbot16** [comment]
Good to hear, the performance numbers are definitely promising!
