### ISSUE TITLE
There is no Uninstall Button! Trash GUI Trash Mod so far. 

### ISSUE THREAD

**Issue by Calloffury** [IrisShaders/Iris#780]
### Iris and Minecraft Version

1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD Radeon R5 M330 and intel HD Graphics 620, Dual integrated Graphics

### Java Version

Jdk 8.0.302.8

### Reproduction Steps

1. Place iris in downlods
2. Launch iris with java and sodium with mc 1.17.1 compatible tested mods
3. Unintentionally install iris with sodium
4. Find out sodium replaces optifine and messes with shaders and
 mostly conflicts with optifabric mod along with optifine custom mod setup
5.Uninstall Sodium by deleting files since there is no uninstall button in crappy gui
6.not being surprised at how clunky and cracppy java can be
7.Smashing keyboard trying to unsintall sodium and replace it with the more optimal graphics settings of Optifine for my  current setup.
8.Iris Sodium is a crap software. My laptop does prefer optifabric and optifine over sodium and iris. performance wise.
9999999999999999. Game Crashes permanently and I will not uninstall minecraft folder undoing all the mods., please make Uninstall button in iris or make Optifabric and Optifine Compatible with iris! I dont care, this shouldnt be an issue in the first place we should have the choice for compatibillity to picking either or sodium-iris or optifine-optifabric I will not touch minecraft 1.17.1 until then i will not want to play minecraft ever again and stick it to these crap devs for not making an uninstall button....

changing any grphics settings for performance while sodium and shaders or textures are active results in a Laggy crappy Experimental minecraft that is unresponsive!

### Crash Report file and latest.log

Crashlogs broken for this error, gui crashlog states that iris mc is incompatible with optifabric

**Comment by AlsoNiko** [comment]
To delete iris and sodium, you remove it from your mods folder, there is no point in adding an uninstall button for that.

**Comment by RDKRACZ** [comment]
> I will not touch minecraft 1.17.1 until then i will not want to play minecraft ever again and stick it to these crap devs for not making an uninstall button....

Okay then, bye

>Unintentionally install iris with sodium

![Screenshot from 2021-08-21 19-45-25](https://user-images.githubusercontent.com/43277609/130330644-c4753ad1-3c3d-457b-9501-913e6594b886.png)

**Comment by Calloffury** [comment]
Tested doing this does not function peroperly. My computers test shows that sodiums optimization is complete garbage if it is used with sodium plus shaders

**Comment by CoderStone** [comment]
Tested doing this does not function peroperly. My computers test shows that your PC is bad, your english is bad, and you can't read things like "NOT COMPATIBLE WITH OPTIFINE"

**Comment by Calloffury** [comment]
integrated installer makes installing/uninstalling this mod a pain

**Comment by Calloffury** [comment]
grammer nazi 
i typed too fast lool

**Comment by AlsoNiko** [comment]
if you're using the iris sodium profile, you just delete the profile. if you installed iris as a fabric mod, you just delete the iris and sodium jar from your mods folder.

**Comment by Calloffury** [comment]
Also I read that part....

**Comment by ShadowHacker110** [comment]
Iris is a performance-oriented fabric mod designed to be compatible with Sodium. Optifine is an optimization mod, mainly for forge, but it can be used on fabric by using Optifabric. They are two different mods, for two different audiences. All systems are different, and if yours runs better with Optifine and Optifabric, then you can use that. There should be no need for Iris if you are using Optifine, because they run the same shaders. There is no way to make an uninstall button in-game for a mod, it's just not possible. You can delete it from the mod folder. Please do not insult the mod developers, they work hard on providing and updating this mod, at no cost to us.

**Comment by CoderStone** [comment]
> Also I read that part....

"Find out sodium replaces optifine and messes with shaders and
mostly conflicts with optifabric mod along with optifine custom mod setup"

**Comment by AlsoNiko** [comment]
Please stop commenting on github issues and let people who are not being rude to users handle this.

**Comment by Calloffury** [comment]
removing iris from mod folder does nothing is the main issue why!!?

**Comment by AlsoNiko** [comment]
> removing iris from mod folder does nothing is the main issue why!!?

This makes 0 sense

**Comment by Calloffury** [comment]
Ive been optimizing my game for hours now trying to remove iris after this problem occurred

**Comment by AlsoNiko** [comment]
To delete iris and sodium, you remove it from your mods folder or delete the profile.

**Comment by Calloffury** [comment]
internals of my minecraft folder is fucked lol thanks to iris leaving behind unremovable mod files in my launchers code
after removing mod zip from mods folder

**Comment by Calloffury** [comment]
will try

**Comment by IMS212** [comment]
Iris _cannot_ leave unremovable files, and to stop using Iris just don't select it as your profile. If you need support with uninstalling please ask on our discord.
