### ISSUE TITLE
All Apologies to the Wonderful Developers(Problem Solved!)

### ISSUE THREAD

**Issue by Calloffury** [IrisShaders/Iris#781]
### Iris and Minecraft Version

1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD and intel Dual integrated Graphics

### Java Version

Jdk 8.0.302.8

### Reproduction Steps

the problem was due to something completely unrelated, I solved my issue with something else
probably a conflicting plugin im still rooting out the cause and will still give an update on the cause of the issue soon as long as you all would like know... also the performance of iris sodium without any textures is actually quite good in my opinion
ive been doing thorough testing of 1.17.1 mods and would appreciate you all accepting my sincere apologies. I will never insult a hard working dev again as i plan on potentially becoming one someday.... thank you all for your hard work
it was an incredibly weird minecraft issue ive never seen before Honestly.....pro PC-PS4 gamer here lmao
████████████████████████████████████████
████████████████████████████████████████
██████▀░░░░░░░░▀████████▀▀░░░░░░░▀██████
████▀░░░░░░░░░░░░▀████▀░░░░░░░░░░░░▀████
██▀░░░░░░░░░░░░░░░░▀▀░░░░░░░░░░░░░░░░▀██
██░░░░░░░░░░░░░░░░░░░▄▄░░░░░░░░░░░░░░░██
██░░░░░░░░░░░░░░░░░░█░█░░░░░░░░░░░░░░░██
██░░░░░░░░░░░░░░░░░▄▀░█░░░░░░░░░░░░░░░██
██░░░░░░░░░░████▄▄▄▀░░▀▀▀▀▄░░░░░░░░░░░██
██▄░░░░░░░░░████░░░░░░░░░░█░░░░░░░░░░▄██
████▄░░░░░░░████░░░░░░░░░░█░░░░░░░░▄████
██████▄░░░░░████▄▄▄░░░░░░░█░░░░░░▄██████
████████▄░░░▀▀▀▀░░░▀▀▀▀▀▀▀░░░░░▄████████
██████████▄░░░░░░░░░░░░░░░░░░▄██████████
████████████▄░░░░░░░░░░░░░░▄████████████
██████████████▄░░░░░░░░░░▄██████████████
████████████████▄░░░░░░▄████████████████
██████████████████▄▄▄▄██████████████████
████████████████████████████████████████
████████████████████████████████████████

### Crash Report file and latest.log

```shell
.
```

### Additional context

.

**Comment by Calloffury** [comment]
*to know

**Comment by IMS212** [comment]
Thanks, but please don't create new issues for things like this.
