### ISSUE TITLE
Block outlines when using shaders

### ISSUE THREAD

**Issue by DJAruun** [IrisShaders/Iris#783]
### What happened?

When using shaders the block outlines, chunk outlines and hitboxes are all invisible

### Iris and Minecraft Version

iris-mc1.17-1.1.0

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidida GeForce GTX 1660

### Java Version

Java 16

**Comment by IMS212** [comment]
This has already been fixed in development builds, and will be fixed in Iris 1.1.2.

**Comment by DJAruun** [comment]
Nice!
