### ISSUE TITLE
Cannot toggle or change shaders if an invalid .zip file is in the shaderpacks directory

### ISSUE THREAD

**Issue by CredixYt** [IrisShaders/Iris#785]
### What happened?

Iris fails to load available shaders when one of them is an invalid .zip file (in the .minecraft/shaderpacks directory). Furthermore, shaders cannot be enabled/disabled

### Screenshots

![Untitled](https://user-images.githubusercontent.com/28508211/130356419-d9b9fba1-1cd0-4c4b-934d-cc991c91ccd6.png)

### Iris and Minecraft Version

iris-mc1.16.5-1.1.1 for Minecraft 1.16.5

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1060

### Java Version

Java 16

### Additional context

**Operating System**: Windows 10 Pro x64 (Version: 20H2. Build: 19042.1165)
**GPU**: Nvidia GeForce GTX 1060 6GB
**GPU Driver**: GeForce Game Ready Driver 471.41
**Java**: Eclipse Temurin JDK with Hotspot 16.0.2+7 (x64)

**Comment by felDL1994** [comment]
Same issue running MACOS 10.15.7 running CPU 2,5 GHz Intel Core i7 quatre cœurs and AMD Radeon R9 M370X 2 Go
(GPU) using JAVA 16

**Comment by coderbot16** [comment]
Could you send an example of an invalid zip file? I cannot reproduce this issue on the 1.16.5 development version of Iris with an invalid ZIP file I tried to create.

**Comment by coderbot16** [comment]
I tried a number of invalid ZIP files and couldn't reproduce this. If you're still experiencing this, please open a new issue, and make sure you attach a log file with a relevant stack trace, because we can't go anywhere with this issue report as is.
