### ISSUE TITLE
Very stange shadows with enhanced default (mesa)

### ISSUE THREAD

**Issue by KyleUltimate** [IrisShaders/Iris#786]
### What happened?

![image](https://user-images.githubusercontent.com/68589851/130357680-20a22075-7f81-47e6-9673-6fcc25e2fef3.png)
the sword and the player shadow are strange

### Iris and Minecraft Version

iris-1.1.2-pre+rev.dcc1352+sodium 0.3.0+IRIS2-rev.6a84168

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch linux

### What is your GPU?

MSI RX5700xt+mesa

### Java Version

adoptoopenjdk java 16

**Comment by KyleUltimate** [comment]
log files: https://paste.ee/p/d0Ms5

**Comment by coderbot16** [comment]
Original reporter says that this was fixed on discord
