### ISSUE TITLE
Vanilla clouds are invisible in Iris 1.17 (Enhanded Default)

### ISSUE THREAD

**Issue by KyleUltimate** [IrisShaders/Iris#787]
### What happened?

the title

### Iris and Minecraft Version

iris-1.1.2-pre+rev.dcc1352+sodium 0.3.0+IRIS2-rev.6a84168

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch linux

### What is your GPU?

MSI RX5700xt+mesa

### Java Version

adoptoopenjdk java 16

### Additional context

this was supposed to be fixed in 1.1.1 and so on, so this is the bug report

**Comment by IMS212** [comment]
Can't replicate with latest dev build, can you send an F3 screenshot

**Comment by KyleUltimate** [comment]
ok
![image](https://user-images.githubusercontent.com/68589851/130362986-09a95b02-d155-4b3a-be77-399d29f2dcfc.png)

**Comment by IMS212** [comment]
Please send a log file as well, I'm having trouble replicating this issue at all.

**Comment by KyleUltimate** [comment]
![image](https://user-images.githubusercontent.com/68589851/130363046-3a2d6d63-1eef-4d2b-86f9-2f05a77948d2.png)
this is with no mods but iris's

**Comment by KyleUltimate** [comment]
https://paste.ee/p/gvgoG
log file

**Comment by coderbot16** [comment]
Are you absolutely sure that you have clouds enabled in the vanilla video settings?

**Comment by KyleUltimate** [comment]
oh wait, I didn't enable it, dumb me, closing it now
