### ISSUE TITLE
Iris should support CIT

### ISSUE THREAD

**Issue by en1gma713** [IrisShaders/Iris#788]
**Is your feature request related to a problem? Please describe.**
Custom Item Textures and Custom Entity Models are Optifine options for texture packs that allow resource pack creators to add custom changes textures based on a text file.

**Describe the solution you'd like**
It would be nice if CIT and CEM could be implemented in Iris

**Describe alternatives you've considered**
Optifine has a working CIT implementation, but Optifine is slow and not open-source.

**Additional context**
The main reason Optifine is valued by map and resource pack creators is for its implementation of CIT.

**Comment by NoComment1105** [comment]
This is achieved by other mods and outside iris' scope

**Comment by dorianpb** [comment]
If you want CEM, you can [check out my mod](https://github.com/dorianpb/cem)
