### ISSUE TITLE
SEUS PTGI HRR 2.1

### ISSUE THREAD

**Issue by UltraHayden06** [IrisShaders/Iris#790]
### What happened?

Many errors with reflection and water and translucent blocks/items could have to do with path tracing?

### Screenshots

![2021-08-22_19 22 07](https://user-images.githubusercontent.com/70444889/130373273-9e97860f-73d2-493c-b868-9c79d7ff14e1.png)
![2021-08-21_22 45 59](https://user-images.githubusercontent.com/70444889/130373275-49788ae4-b270-4f51-a7d0-7ba1d761501e.png)
![2021-08-21_22 47 10](https://user-images.githubusercontent.com/70444889/130373276-6b654818-510d-4d92-967b-7fe2c35ba647.png)

### Iris and Minecraft Version

1.1.1 For 1.17.1 (Via Curseforge)

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1660

### Java Version

Java 16

**Comment by UltraHayden06** [comment]
the issues seen in the ocean screenshot are third person only I am using a mod that renders third person in first

**Comment by AlsoNiko** [comment]
This is already known and tracked by other issues
