### ISSUE TITLE
Weird glass texture, rails, bamboo and iron bars have z-fighting.

### ISSUE THREAD

**Issue by SierraRay53** [IrisShaders/Iris#796]
### What happened?

Hello! My first bug report on GitHub. 

**I found an issue with 3 textures:**
- Glass Pane (just regular glass pane, no stained)
- Iron Bars
- Rails
- Bamboo

1. Glass pane looks awful. It has that 3D thing and it makes z-fighting textures. Enabling shaders goes away.
2. Iron Bars and Rails both have z-fighting as well.

Tried the following:

- No extra mods. Just Iris and Sodium.
- Default resource pack

Still has the same issue.

### Screenshots

![image](https://user-images.githubusercontent.com/81502335/130949591-c8a65abd-26a3-4e95-bbbc-620b7b13be16.png)
(w/o shaders)
![image](https://user-images.githubusercontent.com/81502335/130949609-57ecf545-1019-4dbd-8787-cb72391d8b8b.png)
(w/ Sildurs' Enhanced Default)
![image](https://user-images.githubusercontent.com/81502335/130948896-8bdc4bd2-0a9a-4c5e-a01f-921d7a04b72c.png)
(w/o shaders)
![image](https://user-images.githubusercontent.com/81502335/130948941-ab49ea6f-6afe-460a-969c-01a1726d506f.png)
(w/ Sildurs' Enhanced Default)
![image](https://user-images.githubusercontent.com/81502335/130950718-2c455f72-fb15-4178-ac14-a87f4e7e8b81.png)
(w/o shaders)
![image](https://user-images.githubusercontent.com/81502335/130950651-3234b9fd-6d2d-4584-94b0-2054b9d52e45.png)
(w/ Sildurs' Enhanced Default)

### Iris and Minecraft Version

iris-mc1.17-1.1.1 for Minecraft 1.17/1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 650

### Java Version

Java 16.0.1 64 bit

**Comment by coderbot16** [comment]
Does this still happen with the latest versions of Iris and Sodium?

**Comment by coderbot16** [comment]
Closing until we can confirm that this is still an issue - I don't think I've observed this on recent versions of Iris and Sodium.

**Comment by maximumpower55** [comment]
The z fighting issue with iron bars is still observed with the most recent version of sodium with and without iris

**Comment by maximumpower55** [comment]
Due to the compat vertex format not giving enough precision for the vertex positions

**Comment by coderbot16** [comment]
Well in that case it's still not an Iris issue then

**Comment by maximumpower55** [comment]
Yep
