### ISSUE TITLE
Spider eyes don't render quite right on Sildur's Vibrant Shaders

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#80]
On trunk they don't use the right render layer, and on my local testing branch making spider eyes render properly causes the rest of the spider to turn black.

This appears to result from the fact that the spider eyes renderer actually renders the whole spider model, but normally only the eyes part should show up.

This might be related to issues with transparency in general that I've noticed with faraway leaves as well.

**Comment by thedocruby** [comment]
I know for a fact that this is not just a problem with Iris. Using OptiFabric with some shaders, notably Continuum 2, this problem also presents itself in the same manner. I remember noticing this for a few other similar texture bits, possibly endermen eyes, but I don't remember where else I saw it for sure.

**Comment by coderbot16** [comment]
This should be fixed for the most part (at least, up to parity with OF) on the render-layer-experiments branch

**Comment by coderbot16** [comment]
This has been fixed for the most part with the merge of the render layer experiments branch into trunk.
