### ISSUE TITLE
Animal leads are connected

### ISSUE THREAD

**Issue by MeLionLord** [IrisShaders/Iris#802]
### What happened?

I have tied my animals to different fences, but the leads were rendered as connected.

I tried it with different shaders and it happened every time.

After removing Iris the problem didn't repeat.

### Screenshots

with Iris

![2021-08-28_19 48 52](https://user-images.githubusercontent.com/68869938/131226753-4822e202-af70-479b-8a50-bfdeb9d2c089.png)

without Iris

![2021-08-28_20 16 04](https://user-images.githubusercontent.com/68869938/131227248-ce6b7d24-157e-4eae-94b5-f9f9b8ab3590.png)

### Iris and Minecraft Version

iris-mc 1.17-1.1.1 for minecraft 1.17 and 1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1070

### Java Version

Java version 8 update 301

**Comment by AlsoNiko** [comment]
We need an f3 screenshot for both, as well as logs

**Comment by coderbot16** [comment]
This seems like it might be an issue with the line strip draw mode in the Iris batched entity rendering code. I'd have to verify for sure but this would cause different line strips to connect together like what is being observed here.

**Comment by coderbot16** [comment]
Logs and F3 screenshot probably aren't needed for this particular issue since I already think I know what's going on.

**Comment by MeLionLord** [comment]
Okay :)
How do I get into my logs?

**Comment by coderbot16** [comment]
This appears to be related to a vanilla bug, but it seems like Iris intensifies it: https://bugs.mojang.com/browse/MC-212629

While in vanilla it only happens with leads connected to invisible entities, it happens with all leads in Iris. Fixing this issue in Iris will also fix the related vanilla bug.

**Comment by MeLionLord** [comment]
Very cool. Good job :)

**Comment by coderbot16** [comment]
This should be fixed as of https://github.com/IrisShaders/Iris/commit/df9a93293c3c0132da50d0aba82d1c07c4e07e9d, this fix will be included in Iris 1.1.2 which will come out soon.
