### ISSUE TITLE
Sodium 0.31 released please combine

### ISSUE THREAD

**Issue by red2blue** [IrisShaders/Iris#803]
Please combine IRIS for 1.17.1 Fabric with the latest sodium or release a standalone of iris so we can use the latest sodium.

Thank you! Love the mod

**Comment by IMS212** [comment]
We’re already working on this, join our discord for progress/test builds. This will be officially coming in Iris 1.1.2.

**Comment by AlsoNiko** [comment]
This is already being worked on, but iris needs to make changes to itself before its next release.
