### ISSUE TITLE
[Immersive portals] Mirrors not working above water when shaders are enabled

### ISSUE THREAD

**Issue by KyleUltimate** [IrisShaders/Iris#807]
### What happened?

mirrors are not working
shaders enabled:
![image](https://user-images.githubusercontent.com/68589851/131238175-79c463fc-16a8-4117-badc-2e564919c89d.png)
shades disabled:
![image](https://user-images.githubusercontent.com/68589851/131238179-0cae2b78-8e33-4b8a-b825-c860ef89b219.png)
shader: comp 4.2 dev5

### Iris and Minecraft Version

iris-1.1.2-pre+rev.5142946+sodium 0.3.0+IRIS2-rev.7eab2e4

### Are you running Sodium along with Iris?

Yes

### Operating System

Arch linux

### What is your GPU?

MSI RX5700xt+mesa

### Java Version

adoptoopenjdk java 16

**Comment by coderbot16** [comment]
This is unfixable because portals have to be rendered into the scene after translucent things like water have already been rendered, when using shaders.
