### ISSUE TITLE
Easy shader options GUI

### ISSUE THREAD

**Issue by IntoTheVoid-900** [IrisShaders/Iris#808]
**Is your feature request related to a problem? Please describe.**
You are unable to edit shader setting, unlike Optifine.
**Describe the solution you'd like**
I want a button added to the shader selection menu that lets you access the shader options menu seen on Optifine.

![Add pls](https://user-images.githubusercontent.com/74509183/131269914-cce40137-d7e7-4ccf-acd2-6ab2e0fc6ef5.png)

**Comment by AlsoNiko** [comment]
Issue #663, pinned
