### ISSUE TITLE
Graphics settings show Fancy even when graphics is on Fabulous

### ISSUE THREAD

**Issue by Waoweens** [IrisShaders/Iris#810]
### What happened?

When you set the graphics to _Fabulous!_ (using the vanilla options menu) the sodium options menu still says Fancy.
This does not happen without Iris.

I am using the bundled version of sodium that is included with Iris.

### Steps to reproduce:
- Disable shaders
- Press Shift+P to go to the vanilla options menu
- Set graphics to _Fabulous!_
- Go back into the sodium options menu
- Go into the quality tab
- See that the graphics is set to Fancy

### Screenshots

![vanillaoptions](https://user-images.githubusercontent.com/30313089/131353486-03547282-1b7c-4bea-b9ff-20d49cee05db.png)

![sodiumoptions](https://user-images.githubusercontent.com/30313089/131353519-87d0e079-a40d-4001-9028-b9cd92a98e86.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.1 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11 Insider Beta Preview

### What is your GPU?

Nvidia GeForce RTX 3060

### Java Version

OpenJDK 16

**Comment by AlsoNiko** [comment]
This is fixed in Dev builds.
