### ISSUE TITLE
The "off" in "Toggled shaders to off!" is not localized

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#813]
This should probably be a separate message, we could word it a bit differently too.

**Comment by JackTGG** [comment]
like %s to another lang?

**Comment by coderbot16** [comment]
This was fixed by IMS a while back in https://github.com/IrisShaders/Iris/commit/2ca694243f047e16b3a1c391fa89d4c282dd29c2.

When toggling shaders off, instead of printing "Toggling shaders to (off)", we print "Shaders disabled!"
