### ISSUE TITLE
[1.17, 1.1.2] Block outlines and transparent parts of entities on Sildur's Vibrant Shaders 1.281 - 1.283 are very colorful

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#819]
![image](https://user-images.githubusercontent.com/22420959/131918972-a4bd5772-0276-424d-bbe9-93f305d2ec57.png)

This seems to be caused by Iris for 1.17 not supporting blend mode overrides properly.

This issue cannot be observed on Sildur's Vibrant Shaders v1.29 since it handles block outlines differently, and does not use blend mode overrides as much.

**Comment by respectablenoob-source** [comment]
How did you get block outlines? My iris installation doesn't show them.

**Comment by AlsoNiko** [comment]
This was taken on a dev build, which will be in the 1.1.2 iris release.

**Comment by respectablenoob-source** [comment]
> This was taken on a dev build, which will be in the 1.1.2 iris release.

Thank you very much.

**Comment by respectablenoob-source** [comment]
> This was taken on a dev build, which will be in the 1.1.2 iris release.

Is it on the code yet? Because I tried building it and it produced an unfunctional iris mod.

**Comment by AlsoNiko** [comment]
Yes it is in the code, we have test builds and support in our discord

**Comment by coderbot16** [comment]
The same issues affect parts of the player as well:
![image](https://user-images.githubusercontent.com/22420959/134788694-02a7a277-7c36-490b-9391-5f48239a4a52.png)

**Comment by coderbot16** [comment]
Fixed in 1.1.3
