### ISSUE TITLE
Chunk borders now fade in

### ISSUE THREAD

**Issue by CalXee** [IrisShaders/Iris#820]
### What happened?

Chunk borders fade in with shaders instead of instantly appearing. It kind of ruins the debug or technical vibe of the feature. It might also apply to hitboxes.

### Screenshots

https://user-images.githubusercontent.com/68349758/131926106-daf5a587-7b13-4f71-b294-232c70da5254.mp4

### Iris and Minecraft Version

Minecraft 1.17.1, Iris commit a04c99e

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1050 Ti

### Java Version

Java 16

**Comment by coderbot16** [comment]
This is a natural consequence of Iris making these features fullbright and how shaders render bright things. I don't think this can be fixed without making chunk borders and hitboxes dark again.
