### ISSUE TITLE
I need this without sodium or a version that supports FREX Flawless Frames API

### ISSUE THREAD

**Issue by CatMaster8232** [IrisShaders/Iris#822]
I'm trying to made a ODS replay mod video because replay mod requires iris mod. But, with the version of sodium, it cannot render with sodium. So, can you remove or update the sodium?

**Comment by AlsoNiko** [comment]
You can use iris 1.1.1, replay mod, and there sodium together and it works.

**Comment by AlsoNiko** [comment]
https://www.replaymod.com/download/sodium-fabric-mc1.17.1-0.3.0+IRIS2-rev.5eb1e8e.jar

**Comment by CatMaster8232** [comment]
Tysm! :D

**Comment by galaxyentity904** [comment]
This should be pinned! I had this problem yesterday and couldn't find a solution so I had to get rid of sodium all together which drastically lowered framerates and kept a persistent error from iris when playing

**Comment by galaxyentity904** [comment]
Do you have the version for 1.16.5 by chance @AlsoNiko ? That's the version I'm using but I can't find it on the replay mod website

**Comment by IMS212** [comment]
https://www.replaymod.com/download/sodium-fabric-mc1.16.5-0.2.0+IRIS3-rev.2ef7982.jar

**Comment by galaxyentity904** [comment]
Thanks so much! Works perfectly with replay!
