### ISSUE TITLE
Iris installer wont start

### ISSUE THREAD

**Issue by Karmorak** [IrisShaders/Iris#841]
### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Radeon 7

### Java Version

16

### Reproduction Steps

start the installer

### Crash Report file and latest.log

```shell
no main manifest attribute, in iris-and-sodium-mc1.17-1.1.2+build.9.jar
```

### Additional context

the iris installer wonmt launch when i try to run it over the console it says:
no main manifest attribute, in iris-and-sodium-mc1.17-1.1.2+build.9.jar

**Comment by yitzy299** [comment]
You are trying to run a mod jar directly. Place it in your mods folder or use the installer. Future support should be on the discord rather than GitHub issues
