### ISSUE TITLE
Text on signs is not visible using Silders Vibrant Shaders v1.281 Extreme-VL

### ISSUE THREAD

**Issue by redstonefreak589** [IrisShaders/Iris#843]
### What happened?

When using Silders Vibrant Shaders v1.281 Extreme-VL, there are some graphical glitches; One of them being the outlines of blocks are in a rainbow, but that's not what this issue raises.

Text on signs is invisible while using this Shader, as seen in the [screenshot here](https://imgur.com/DCeRE5m) (compared to [vanilla here](https://imgur.com/Q4pE8bR)). Apologies for the particle effects.

Using a different shader, such as BSL v8.1, it's fine ([screenshot here](https://imgur.com/2Sp2cIL))

### Screenshots

Silders Vibrant Shaders - https://imgur.com/DCeRE5m
Vanilla - https://imgur.com/Q4pE8bR
BSL (Working example) - https://imgur.com/2Sp2cIL

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9 for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce 1650 Super

### Java Version

Java 16

**Comment by CoderStone** [comment]
Sildurs 1.28.1 is outdated anyways, try on 1.29.
Additionally, from what I can tell on 1.28.1, it works fine?

![image](https://user-images.githubusercontent.com/34324909/132992351-64da0376-37fb-4947-a508-f6ed789e26db.png)

**Comment by redstonefreak589** [comment]
1.29 works, didn't know there was an update. Thanks! Note to self: don't use outdated shaders
