### ISSUE TITLE
Flat strips of texture around trees and foliage

### ISSUE THREAD

**Issue by Oakstar519** [IrisShaders/Iris#845]
### What happened?

There are large strips of what seems to be a texture atlas appearing in forests. They appear only at certain angles and in some cases can be removed by breaking nearby blocks. Reloading the chunks with F3+A removes them and seems to regenerate them at a different location or angle.

This seems to happen with all shaders and without shaders. I attached several screenshots of this occurring as well as two videos.

The logs for the past several minutes or so have just been `[16:01:04] [Render thread/INFO]: [STDOUT]: DFinal: 0.0 === 0.0` over and over again (with different times.)

### Screenshots

![2021-09-06_15 33 11](https://user-images.githubusercontent.com/57008396/132256115-3562c3bb-ef8d-4389-9516-b84f1d7cc26a.png)
![2021-09-06_15 26 21](https://user-images.githubusercontent.com/57008396/132256118-b74aa087-1008-451b-9ee2-361b76d7b2c8.png)
![2021-09-06_15 32 17](https://user-images.githubusercontent.com/57008396/132256121-44bab0eb-6fa2-483f-b6ad-cef6df424c42.png)
![2021-09-06_15 32 25](https://user-images.githubusercontent.com/57008396/132256122-9be662b2-0844-48f4-ae80-df9a1dd789ff.png)
![2021-09-06_15 32 31](https://user-images.githubusercontent.com/57008396/132256123-82cbe2a5-85a3-4efd-b1ab-50a6b84689ef.png)
![2021-09-06_15 42 53](https://user-images.githubusercontent.com/57008396/132256619-e2f63bb7-6324-43dd-a7c5-64a54021de2e.png)
![2021-09-06_15 42 42](https://user-images.githubusercontent.com/57008396/132256621-a3d9a752-9696-490d-b897-8d0e5963f2fa.png)
![2021-09-06_15 46 21](https://user-images.githubusercontent.com/57008396/132256798-cc0499ef-1f07-4b44-8128-6c763a664db2.png)

https://drive.google.com/file/d/1kCZ4bMcG3FBwVRYY8-RfrYVq6932dhMX/view?usp=sharing https://drive.google.com/file/d/1uuRr6F9j0dqjLfc70YRDM-W_JsUJ0xfk/view?usp=sharing

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 7

### What is your GPU?

Radeon R7 200 series

### Java Version

Java 16

**Comment by coderbot16** [comment]
I'm assuming that this issue still happens if you remove Iris and add Sodium. If so, please ensure that this is reported to Sodium not us. If this issue does not happen with just Sodium but does happen with Iris, please let me know.
