### ISSUE TITLE
[Complementary Shaders] Copper is very bright regardless of ambient lighting

### ISSUE THREAD

**Issue by napmouse** [IrisShaders/Iris#846]
### What happened?

When using complementary shaders on 1.17.1, copper ore sticks out like crazy. It's a shame, because that shader seems to work nearly perfectly otherwise. Shown here with two different texture packs; vanilla and Jicklus. 

### Screenshots

![javaw_dW68NBjgmn](https://user-images.githubusercontent.com/84947008/132262299-95e8faf6-184e-4e04-8549-67698e808d3b.jpg)
![javaw_eQ2yzMPp5n](https://user-images.githubusercontent.com/84947008/132262412-ab257801-d864-4fff-af85-49e90aeaa554.jpg)

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9.jar for minecraft 1.17.1 

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

MSI Nvidia RTX 2080

### Java Version

Java 16

**Comment by AlsoNiko** [comment]
Does this happen with the same texture pack on optifine?
As for vanilla brightness, we can't change that, as its part of complementary

**Comment by napmouse** [comment]
> Does this happen with the same texture pack on optifine?
> As for vanilla brightness, we can't change that, as its part of complementary
On optifine, it can be disabled through the shader config menu. Guess it's intentional, if weird.
