### ISSUE TITLE
Include a version with FREX Flawless frames api

### ISSUE THREAD

**Issue by galaxyentity904** [IrisShaders/Iris#847]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when

Iris version 1.1.2 includes a sodium version without support for FREX Flawless frames api required for replay, and when removing it and adding a supported fork iris gives an error, even when putting the jar in /META-INF/jars/ and replacing the entry of fabric.mod.json

**Describe the solution you'd like**

Add a version of 1.1.2 with support for the FREX Flawless frames api, even if it downgrades the sodium version

**Describe alternatives you've considered**

All alternatives I tried did not work

**Additional context**

N/A

**Comment by galaxyentity904** [comment]
To be clear, there isn't an error screen in 1.1.1 so it works in that version

**Comment by AlsoNiko** [comment]
We can not downgrade the sodium version, replays sodium is designed for iris 1.1.1, we don't know if they'll update it, as for why we don't merge the PR ourselves, we're waiting for mainstream sodium to do so first. 
Leaving open as it is useful

**Comment by galaxyentity904** [comment]
Alright! I'll watch for anything happening

**Comment by coderbot16** [comment]
Iris 1.1.3 will no longer bundle a build of Sodium, so it should be much easier to add ReplayMod's forked Sodium in until the FREX Flawless Frames PR to Sodium is merged.
