### ISSUE TITLE
Holes in Blocks or complete chunks are invisible

### ISSUE THREAD

**Issue by SirPytan** [IrisShaders/Iris#851]
### What happened?

Sometimes blocks have holes or complete chunks are seethrough.

### Screenshots

![2021-09-07_22 25 19](https://user-images.githubusercontent.com/38554289/132428003-d2d91275-8a8d-4ebb-b7f6-f159cf639020.jpg)

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9

### Are you running Sodium along with Iris?

Yes

### Operating System

Win10

### What is your GPU?

Nvidia RTX 2080 Ti

### Java Version

Java 16.0.2

### Additional context

I am using Indium, NTCM, Complementary Shaders and Patrix Texture Pack 64px. I still use a lot more mods, but I thinks these are the most relevant ones.

**Comment by AlsoNiko** [comment]
What indium version?

**Comment by AlsoSylv** [comment]
Can you update on this/add a log file if it has continued to happen?

**Comment by coderbot16** [comment]
Can you test with just Sodium and without Iris and see if the issue still occurs?

**Comment by coderbot16** [comment]
I'm assuming that this issue still happens if you remove Iris and add Sodium. If so, please ensure that this is reported to Sodium not us. If this issue does not happen with just Sodium but does happen with Iris, please let me know.
