### ISSUE TITLE
Max Shadow Distance resetting on each boot

### ISSUE THREAD

**Issue by Apprisco** [IrisShaders/Iris#852]
### What happened?

I use sildurs EVL 1.29 Shaders, and I noticed that the max-shadow distance is always set to 32.
It isn't greyed out, so I always drop it down to 8/9, but each boot, this value resets to 32.
This is honestly very annoying, lol

### Screenshots

![image](https://user-images.githubusercontent.com/34324909/132623866-88439b55-2f93-4c4d-8210-01f5e9f7689b.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.2.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1070

### Java Version

16

**Comment by FoundationGames** [comment]
Does this happen if you change the option in the vanilla video settings screen (Access via shift+p)

**Comment by CoderStone** [comment]
> Does this happen if you change the option in the vanilla video settings screen (Access via shift+p)

Doesn't seem to be, it's also inconsistent with the sodium menu.

**Comment by coderbot16** [comment]
Reopened & tagged as fixed in dev until we push the release fixing this
