### ISSUE TITLE
Vanilla-Like Settings GUI

### ISSUE THREAD

**Issue by milkev** [IrisShaders/Iris#854]
**Is your feature request related to a problem? Please describe.**
Just my own irritation that the iris menu is inconsistent compared to other minecraft menu's. The shaders menu even goes back to vanilla gui style! Its inconsistent even within itself.

**Describe the solution you'd like**
A more vanilla-like gui option, so that the menu fits with the other settings gui's. It will just seem more coherent and a bit easier to get around, rather than learning a new arbitrary menu type that only one mod (afaik) uses. Its not like the current menu is hard to get around / learn, but rather is something that shouldn't have to be done in the first place.
Id be happy with even just keeping the general layout you currently have, but replace the buttons with minecraft buttons and sliders.

**Describe alternatives you've considered**
No reasonable alternatives.

**Additional context**
The menu I would like to be more in line with vanilla menu's (as well as the other sub menu's; Quality and Advanced)
![image](https://user-images.githubusercontent.com/22010128/132774417-3c0c266c-efc7-47eb-882a-0a75a095b44a.png)

**Comment by AlsoNiko** [comment]
General, Quality, and Advanced are sodium menus.

**Comment by TheNukeLore** [comment]
this menu is from sodium, you can see the vanilla settings by pressing shift plus P

**Comment by LizIsTired** [comment]
This menu has nothing to do with Iris (except from the shader packs button). The change of menu is caused by Sodium, a mod made by jellysquid3, Iris depends on Sodium for performance.

**Comment by milkev** [comment]
Shift + P hides most of the functionality and options of sodium/iris unfortunately

Ok, i assumed it was from iris since i installed iris. I'll go talk to sodium then, sorry bout that.

**Comment by TheNukeLore** [comment]
there is also a reason for this gui, some of vanilla's options dont work correctly with sodium, so the can cause massive issues

**Comment by IMS212** [comment]
@milkev from discord:
**Why doesn't Sodium use the vanilla settings menu?**
- Functionality. The existing vanilla menu updates game settings in real time as you change options, leading to huge pauses. The sliders in Minecraft are next to impossible to control on older machines. Sodium changes the entire menu to only apply the minimum number of changes once you click "Apply", and it doesn't close the GUI so you can continue inspecting the world in the background.

- Clutter. The vanilla menu is a giant list of buttons. Optifine takes this a step further and removes most of the padding, turning it into an even bigger mess of buttons. It's extremely difficult to navigate for new users, and not well organized.

- Accessibility. Sodium implements a lot of different controls and features which make it easier to understand what kind of option you're dealing with. From slider controls, to toggle boxes, to selection boxes. We also need to pack a lot of information in a small space, and the current layout has proven the most effective at doing so.

- Extensibility. Eventually, other mods (maybe even things like resource/shader packs) will be able to add options to Sodium's menu. The vanilla GUIs are limited and don't provide much in the realm of customization, and furthermore, would require a lot of overhead that Sodium just abstracts away. We're a simple list broken into groups and categories. It's functional out of the box with minimal tinkering.

- Branding. I want Sodium to stand out in the crowd and for users to be able to easily identify its presence.

**Comment by TheNukeLore** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/655 here is a link to a closed issue
