### ISSUE TITLE
Chocapic13's shaders doesn't work 

### ISSUE THREAD

**Issue by Grim-Amble** [IrisShaders/Iris#855]
### What happened?

when i try and run Chocapic13's shaders it gives me a black screen i doesn't crash i just can't see 

### Iris and Minecraft Version

newest

### Are you running Sodium along with Iris?

No

### Operating System

windows 10

### What is your GPU?

intel uhd

### Java Version

java 16

**Comment by sid314** [comment]
me too

**Comment by mlgimposter** [comment]
Chocapic13's Shaders use some features still not in Iris, like custom uniforms.
It will be supported in the future, meanwhile you could attempt:

1) Use the V6 of Chocapic13
2) Use edits of Chocapic13 like RedHat, Conquest of the Sun and others
3) Try to find a similar shaderpack

**Comment by coderbot16** [comment]
Superseded by https://github.com/IrisShaders/Iris/issues/1030
