### ISSUE TITLE
Brixel texturepack looks 2d

### ISSUE THREAD

**Issue by sid314** [IrisShaders/Iris#862]
### What happened?

I used Brixel(texturepack) in which textures are supposed to be 3d, but all the textures from brixel were 2d

### Iris and Minecraft Version

iris-mc1.17-1.1.2-starline+build.464.jar , minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

radeon integrated graphics

### Java Version

Java 16

**Comment by IMS212** [comment]
First of all, we do not support starline, however the underlying issue is covered in #130.
