### ISSUE TITLE
Shaderpacks that do not provide their own skies break in Iris for 1.17

### ISSUE THREAD

**Issue by Endstarky** [IrisShaders/Iris#867]
### What happened?

these are some of my skies issue-
![javaw_guQGclYK3R](https://user-images.githubusercontent.com/67501470/133074638-02ea2434-5350-4678-918b-f1f34f73d4a4.png)

videos-
https://streamable.com/y95wip
These are of stereos default 1.17 as example,
and there is also a skybox type issue in sildurs default that doesnt mix with all the sky parts!

And here are some armor lightning issues or i should see weird reflection-
![javaw_2CBWwHtEDA](https://user-images.githubusercontent.com/67501470/133075271-3e77b4f5-b5d1-4732-a068-66d90c4adae7.png)
![javaw_VR8P1PyfvI](https://user-images.githubusercontent.com/67501470/133075281-57f56ca4-7ad0-4c30-ab68-bb93113472ff.png)
both the pics are of sildurs default!

### Screenshots

umm sry i didnt see this section xD!
those are above!

### Relevant log output

```shell
sry im reporting this, days later if u need very much comment me i will provide!
```

### Iris and Minecraft Version

1.1.2  mc ver-1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

windows 10

### What is your GPU?

Intel HD graphics 630

### Java Version

Java 16

### Additional context

Help, this needed to be fixed!

**Comment by Endstarky** [comment]
https://streamable.com/ricqsn
Here is another cloud skybox thingy hope u understand!

**Comment by Fuzlop** [comment]
When I disabled skybox of Complementary shaders pack vanilla clouds were gone. Optifine renders them just right.
