### ISSUE TITLE
Missing Textures on Mod "Industrial Revolution"

### ISSUE THREAD

**Issue by Lemmskii** [IrisShaders/Iris#873]
### What happened?

Installed Iris alongside Industrial Revolution and beforehand there were no missing textures and now there is.

### Screenshots

![2021-09-15_22 51 09_2](https://user-images.githubusercontent.com/90742617/133437432-2b11940f-1cb6-485f-92fe-c319825371e1.png)

### Iris and Minecraft Version

iris-and-sodium-mc1.16.5-1.1.2+build.4

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1080Ti

### Java Version

Java 8

**Comment by fwolle30** [comment]
I can confirm. It hapens to all Mods, that uses custom rendering code for rendering pipes machine frames etc

**Comment by edwloef** [comment]
Have you tried adding indium?
https://modrinth.com/mod/indium

**Comment by fwolle30** [comment]
Adding indium completly resolves this issue, at least for me.

**Comment by coderbot16** [comment]
This is caused by Sodium not supporting the Fabric Rendering API without Indium. Please install Indium.

https://github.com/CaffeineMC/sodium-fabric/issues/5
