### ISSUE TITLE
JVM hard crash on world load "EXCEPTION_ACCESS_VIOLATION (0xc0000005)"

### ISSUE THREAD

**Issue by Project579** [IrisShaders/Iris#874]
### Iris and Minecraft Version

iris-and-sodium-mc1.16.5-1.1.2+build.4 for Minecraft 1.16.5

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10 21H1 Build 19043

### What is your GPU?

Nvidia GeForce RTX Titan

### Java Version

Java 8, Java 11, Java 16

### Reproduction Steps

1. Install Fabric;
2. Install Iris;
3. Try loading a world;
3. Game Crashes.

### Crash Report file and latest.log

```shell
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001b875412303, pid=1808, tid=0x0000000000002d80
#
# JRE version: OpenJDK Runtime Environment (8.0_302-b07) (build 1.8.0_302-b07)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (25.302-b07-jvmci-21.2-b08 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0x000001b875412303
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# F:\MultiMC\instances\Iris\minecraft\hs_err_pid1808.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.
```

### Additional context

This issues should have been resolved before looking at previous issues but it seems to still be there at least for Minecraft 1.16.5, on 1.17.1 with iris-and-sodium-mc1.17-1.1.2+build.9 it works fine.

JVM Crash log:
[REMOVED]

Game log (on Java8 but tested also on 11 and 16 no change):
[latest.log](https://github.com/IrisShaders/Iris/files/7176267/latest.log)

**Comment by coderbot16** [comment]
Does this still happen in 1.1.3? Also, could you post a JVM crash log with your accessToken removed (to prevent people from accessing your account)?

**Comment by coderbot16** [comment]
Sorry, but as-is we can't do much to solve this issue. Closing for now since this will otherwise just remain open forever.
