### ISSUE TITLE
Incompatibility with Light Overlay and BSL shaders 

### ISSUE THREAD

**Issue by alexnode** [IrisShaders/Iris#876]
### What happened?

Really good work with the new patch . Thank you for fixing animal leads. I am seeing great performance improvements on my heavy redstone world.   I am running a mainly vanilla fabric server with just a few mods. One of them is the  "light overlay" and it stopped working with shaders enabled. It requires cloth and architectury libraries but the mod works with shaders disabled. It will be nice if you could have a look at a certain stage. It worked on the previous version.  

### Iris and Minecraft Version

Latest iris 1.1.2 build 9 and minecraft 1.17.1 

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

RTX 2080 laptop 

### Java Version

Java 16

### Additional context

I am running Sodium from your installer

**Comment by coderbot16** [comment]
This should be fixed in the next Iris release, I will confirm once https://github.com/IrisShaders/Iris/commit/4ba30d226d84f200c5d04431639b519d8e63cf84 is merged forward.
