### ISSUE TITLE
Shaders obtions ?

### ISSUE THREAD

**Issue by dubalot** [IrisShaders/Iris#882]
Hello,

I love iris, it´s really powerful for low computers ( and big one want good refresh rate ). But the 3 possible shaders are not editable like optifine menu. Is it in the works? or there is an fan made alternative while waiting for a next update ( because bts shaders cause me little lags and I want to discrase some obtions ).

Thank you in advance, continue on this launch (*^^*)♡

**Comment by IMS212** [comment]
Duplicate of #663.
