### ISSUE TITLE
BSL sun path rotation rotates on wrong axis

### ISSUE THREAD

**Issue by BluSkyu** [IrisShaders/Iris#883]
### What happened?

When using BSL with Optifine, the sun path rotation setting rotates the sun on the Y-axis. When using BSL with Iris, the sun path rotation setting rotates the sun on the X-axis.

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9.jar, minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce GTX 1650

### Java Version

Java 16

**Comment by AlsoNiko** [comment]
What BSL version?

**Comment by coderbot16** [comment]
Testing with OptiFine, the sun path rotation setting rotates the sun on the X-axis, which is consistent with what Iris is doing. If the sun were tilted on the Y axis, it would be directly overhead at noon by default on BSL, which is not what happens.
