### ISSUE TITLE
会不会有 1.18-21w37a版本（用于实验快照）

### ISSUE THREAD

**Issue by bluejt** [IrisShaders/Iris#887]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IMS212** [comment]
是的，我们在 discord 上有针对 21w37a 的构建，并且在 Github 上的一个单独分支上有源代码。

**Comment by bluejt** [comment]
我要怎么在 discord 上查找到 21w37a 的构建
我要怎么联系到单独分支

IMS212 ***@***.***> 于2021年9月22日周三 上午9:15写道：

**Comment by IMS212** [comment]
无法在这里发送，请 ping 我@IMS#7902，以便我可以通过 Discord 向您发送链接

**Comment by bluejt** [comment]
已经关注了

IMS212 ***@***.***> 于2021年9月22日周三 上午11:00写道：

**Comment by IMS212** [comment]
?

**Comment by bluejt** [comment]
[image: 68f0fdb11de9580d160387838e33c71.png]我好像无法添加你

IMS212 ***@***.***> 于2021年9月22日周三 上午11:26写道：

**Comment by bluejt** [comment]
你可以试试添加一下我 看看能不能成功
Warm sun#8633

Zhi Yang ***@***.***> 于2021年9月22日周三 上午11:30写道：
