### ISSUE TITLE
A little bug?

### ISSUE THREAD

**Issue by zhrylpa** [IrisShaders/Iris#889]
Sorry, I don’t understand English, this is a passage I translated with google.
Iris is a very powerful light and shadow component. It has improved my frame rate a lot. Now I will not freeze no matter how I fly, but when I use the iris shader with the Fresh Animations resource pack, the eyes of creatures They have all turned into white eyes. I don’t know what caused this problem. Maybe you can solve this problem in a future update. Thank you, and I wish you a happy life.

**Comment by IMS212** [comment]
Fresh animations doesn’t work with iris, it’ll be supportrd in a future unrelated mod
