### ISSUE TITLE
Sildurs Vibrant: Water Reflections not rendering properly.

### ISSUE THREAD

**Issue by thedocruby** [IrisShaders/Iris#89]
- [x] Dark Rings & "Shadow"
- [x] Vertical Reflections
- [x] Horizon Artifacts

In Sidlurs Vibrant High, with no Sodium, water reflections appear to have multiple problems. The first I noticed is these dark bands in the reflections, which appear to move with the player's viewpoint:
![2021-01-21_11 01 26](https://user-images.githubusercontent.com/76263371/105387622-bb1ee500-5be3-11eb-98de-1cb8e6861928.png)
The rings seem to close in around the player as he flies farther from the surface. Their shape also seems to be dependent on the viewing angle and field of view. This includes a dark spot, what I am calling a "shadow", which appears with enough altitude when looking straight down:
![2021-01-21_11 01 38](https://user-images.githubusercontent.com/76263371/105387964-151faa80-5be4-11eb-8f9c-71cc4f7d81d3.png)
As I travel farther from the surface, the shadow grows larger and persists at more shallow viewing angles. Also, with enough altitude, the rings start to bend in front of the shadow:
![2021-01-21_11 01 48](https://user-images.githubusercontent.com/76263371/105388176-5a43dc80-5be4-11eb-98f0-38f5aaa389b0.png)

In addition to these rings, In certain situations, reflections can be seen on vertical surfaces of scenes from behind the surface. For example, I found a shipwreck with the back half missing and viewed the nearby coral reef from inside the door. the reflection on the surface of the water is a flipped and poorly rendered image of the reef and the sky above:
![2021-01-21_10 58 55](https://user-images.githubusercontent.com/76263371/105388629-e229e680-5be4-11eb-9916-fc5feff0e957.png)
The door:
![2021-01-21_10 59 27](https://user-images.githubusercontent.com/76263371/105388704-fb329780-5be4-11eb-8b93-081786d6ac01.png)
The reef from just outside the door:
![2021-01-21_10 59 05](https://user-images.githubusercontent.com/76263371/105388768-0c7ba400-5be5-11eb-9ca8-e56c7a3ce256.png)
This also happens with flowing water, and can view scenes through adjacent blocks:
![2021-01-21_11 52 59](https://user-images.githubusercontent.com/76263371/105388850-25845500-5be5-11eb-8e91-1b33c2a254b4.png)
The block behind:
![2021-01-21_11 53 12](https://user-images.githubusercontent.com/76263371/105388891-2e752680-5be5-11eb-9981-f80c63340d1a.png)

As a final note, there are many grainy artifacts on the horizon of a large body of water when viewed from the surface. Also note the spots in the bottom right quadrant of the image where the coral reef below can be viewed through the surface without hinderance:
![2021-01-21_10 59 14](https://user-images.githubusercontent.com/76263371/105389141-7eec8400-5be5-11eb-8a3d-8914056b0ece.png)
Whether this is related to the rings I am not entirely sure.

**Comment by coderbot16** [comment]
Another issue, noticed on all current versions of iris:
![image](https://user-images.githubusercontent.com/22420959/105650473-ac952f80-5e68-11eb-9792-fbd6d9f0b113.png)
(the iron ore is being reflected weirdly)

It would be helpful to determine which of these issues also happen on OptiFine, and which do not.

**Comment by Mithos23** [comment]
the last one seems to happen on optifine as well.
![2021-01-28_01 58 09](https://user-images.githubusercontent.com/54249738/106074617-724bbc80-610c-11eb-8f42-fae48c150adc.png)

**Comment by coderbot16** [comment]
The broken reflections when looking at the sides of water are known, and are fixed with the vertex format extensions with sodium.

However, the rings are something else. I wonder if it's something to do with shadows?

**Comment by coderbot16** [comment]
The issues with rings, shadows, and similar have been fixed. However, the issue with weird reflections when looking at the side or bottom of water still exist.

**Comment by magneticflux-** [comment]
I'm getting some interesting patterns in my water... I'm using the latest commit of Iris and the Sodium fork for support. I'm also using Sildur's Vibrant shaders v1.283 Lite.

Can you see the GUI textures in the water?
![image](https://user-images.githubusercontent.com/9124288/109376009-2f097880-7887-11eb-9d5f-d27b7023111b.png)
It looks like buttons and inventory textures (or something, I can't exactly make out what) are being applied underneath the waves.

**Comment by coderbot16** [comment]
The remaining issues in the original report here (weird reflections) are tracked in #9.

@magneticflux- Could you open a separate issue for that, and include a log + F3 screenshot? It's most likely related to issues with the noise texture, which is a somewhat separate issue from this (since Lite doesn't have water reflections at all)

**Comment by GTBScript** [comment]
Moreover, I noticed some weird behaviour in this screenshot.
![2024-01-27_17 39 32](https://github.com/IrisShaders/Iris/assets/145546623/d5a7f0aa-6fd0-454f-b3ed-e4fff2617f2a)

**Comment by Lolothepro** [comment]
> Moreover, I noticed some weird behaviour in this screenshot. ![2024-01-27_17 39 32](https://private-user-images.githubusercontent.com/145546623/300191723-d5a7f0aa-6fd0-454f-b3ed-e4fff2617f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzQyMzIsIm5iZiI6MTcwNjM3MzkzMiwicGF0aCI6Ii8xNDU1NDY2MjMvMzAwMTkxNzIzLWQ1YTdmMGFhLTZmZDAtNDU0Zi1iM2VkLWU0ZmZmMjYxN2YyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNjQ1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2EwZTRiMjYxNGJiNDkxOGQyM2U2NGIzNjk4MjA4ZGVhNTRmOTE1YTUwODNkYjliMmMyMTczYTRlZGM3YmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.axxwh84uwZbTcrk8u_b3kLIDEqhOUz0tv4bysxrHn4w)

No?

**Comment by GTBScript** [comment]
Or this one:

It more looks like the magma cubes are very big and located very far away, although they are very close to me.
![Uploading 2024-01-27_17.45.59.png…]()

**Comment by Lolothepro** [comment]
> Or this one:
> 
> It more looks like the magma cubes are very big and located very far away, although they are very close to me. ![2024-01-27_17 45 59](https://private-user-images.githubusercontent.com/145546623/300192478-39ab1642-c70a-4fc6-b955-031841162e1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODIwMjEsIm5iZiI6MTcwNjM4MTcyMSwicGF0aCI6Ii8xNDU1NDY2MjMvMzAwMTkyNDc4LTM5YWIxNjQyLWM3MGEtNGZjNi1iOTU1LTAzMTg0MTE2MmUxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxODU1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2VlZWVjZjI5YWY0MTYwMzlkMWUwZDY3Nzk1YjlmMDhiODA1ZjhjYjJmNzUxYWE2MDM1ODQ0OTc0N2NkZTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jqGujEfZf0TC4Yu3jqfolj9llilex7rT68edEtyUbxU) ![Screenshot 2024-01-27 175530](https://private-user-images.githubusercontent.com/145546623/300192483-c4439e20-0968-49ef-86f8-96e5f6e7ebf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODIwMjEsIm5iZiI6MTcwNjM4MTcyMSwicGF0aCI6Ii8xNDU1NDY2MjMvMzAwMTkyNDgzLWM0NDM5ZTIwLTA5NjgtNDllZi04NmY4LTk2ZTVmNmU3ZWJmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxODU1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDg1YjE2N2UzOGEyM2Y1YzY2NmRmM2M2ZjkyNTE3YWUwMzU0M2FmNGU2ZjNjMTVkNDQyMDU2MjhhNTk5NzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GDkLbzTArrV6W_Uxh8zZxYw3WJashjvP3hP34Au1Q_o)

oh, yeap, it's a fixed Iris bug
