### ISSUE TITLE
Dimension overrides are not supported

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#90]
Shaders can put dimension-level overrides in world0 (overworld), world1 (end), world-1 (nether), and so on.

`ShaderPack` should be able to load all of the relevant dimension overrides contained in a shaderpack, provide convenience methods for loading the shaders for a given dimension with proper overrides, and `ShaderPipeline` should be able to use them properly.

Also, shaders need to be compiled for the proper dimension, and switched when the player changes dimensions. Or, in the case of Immersive Portals, loaded at the same time.

**Comment by OverlordsIII** [comment]
If a shaderpack has files loaded in `world0` but also has some files directly under the `shaders` (and not under any `world` dir), would these files take precedence over files under world0 for overworld shaders?

**Comment by coderbot16** [comment]
Dimension overrides always take precedence over the shaders dir, even for world0. So shaders/world0/gbuffers_basic.fsh would be loaded instead of shaders/gbuffers_basic.fsh in the overworld.

One thing I'm not sure of is if dimension overrides apply to other files, like shaders.properties or the language definitions. I don't think they do, but it's something to check for.

**Comment by OverlordsIII** [comment]
According to optifine docs [lang](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L193) and properties (`[block.properties](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt#L609)`, `[shader.properties](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.properties#L7)`) are hardcoded to the shaders dir

**Comment by coderbot16** [comment]
Good to know.

In that case, maybe it would be good to have a PackPrograms / ProgramSet / similarly named class whose purpose is to hold the shader programs in a given directory. So there would be a ProgramSet for shaders/, for shaders/world0, and so on.

Then, when it's time to actually compile the pipeline, the overrides program set could be merged with the baseline program set.

This would probably be the most elegant way of going about things for now.
