### ISSUE TITLE
Sides of slabs and and stairs show water texture on its sides underwater.

### ISSUE THREAD

**Issue by boerdereinar** [IrisShaders/Iris#908]
### What happened?

The sides of stairs and slabs show the water texture on its sides underwater. This only happens further away from a slab not if you are standing next to it. (See screenshots)

### Screenshots

Further away from slabs:
![image](https://user-images.githubusercontent.com/54003172/135682286-ecbb5f41-07be-4604-84c9-6fccbc4e9bba.png)
Close to slabs:
![image](https://user-images.githubusercontent.com/54003172/135682340-4de79c95-509e-4fac-8026-3d95e1af9dbd.png)
Test setup:
![image](https://user-images.githubusercontent.com/54003172/135682388-10640c43-273e-48bd-aec4-eaf624829192.png)

### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce GTX 1070

### Java Version

16

**Comment by IMS212** [comment]
Please confirm the issue does not occur with just sodium.

**Comment by boerdereinar** [comment]
Same happens with sodium 0.3.2. Probably sodium issue then

**Comment by IMS212** [comment]
Sodium has likely fixed it in their dev builds already.
