### ISSUE TITLE
Add A Feature for "Emissive Textures" For Optifine Parity

### ISSUE THREAD

**Issue by BluePhoenixLOL** [IrisShaders/Iris#912]
**Is your feature request related to a problem? Please describe.**
So Optifine, one of the best Shader client mods with one problem: Performance
and as we all know Iris aims to solve that problem, but so far, It has way less features than Optifine has. 
Optifine has a feature for Vanilla Shaders, to make some textures be able to have a glowing effect, an effect like Enderman's eyes, but for blocks, the fire in the furnace has a glow, separate than the rest of the texture. it also adds support with it for resource packs and mods. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What ARE Emissive Textures Exactly?**
Emissive textures are overlay textures that glow in the dark. They can be added to basically any texture using Optifine. Resource pack creators can choose to make an entire texture emissive, or just elements of a texture.

**Iron Ore Files in assets\minecraft\textures**
![image](https://user-images.githubusercontent.com/80720298/135737048-300ec333-5534-4add-baf2-b1241a42f50e.png)
**iron_ore_glow.png**
![image](https://user-images.githubusercontent.com/80720298/135737082-e4a12bcf-6289-432e-84c7-551c4e20154a.png)
**iron_ore_glow.png.mcmeta**
![image](https://user-images.githubusercontent.com/80720298/135737110-56f04521-9683-4d4e-b03a-739226afd976.png)
**In Game**
![image](https://user-images.githubusercontent.com/80720298/135736910-eed3e47d-ac7e-4d2b-8a58-a489f2cb6137.png)
**emissive.properties (don't know what this is for)**
![image](https://user-images.githubusercontent.com/80720298/135736969-da9fa50a-7dcc-4f4a-83b8-3c6067ea7abc.png)

**Comment by IMS212** [comment]
This is out of scope for iris, sadly.

**Comment by BluePhoenixLOL** [comment]
> This is out of scope for iris, sadly.

![crying-emoji-dies](https://user-images.githubusercontent.com/80720298/135778335-32431e83-9a0a-481d-a1db-c363d49e66b0.gif)

**Comment by PepperCode1** [comment]
The emissives format seen in the third screenshot is the Chisel/CTM format, which is provided by CTMF on Fabric. This mod is compatible with Iris. The last screenshot shows the emissive file name configuration for Optifine format emissives, but it is a different format so this file is not used by CTMF. There is no Fabric mod for Optifine style emissives yet, but I may make one eventually.

**Comment by Continous** [comment]
Most shaderpacks that use labPBR already define an emissive texture as laid out in that standard; so having an entirely separate texture for it is superfluous.

**Comment by felizey** [comment]
![image](https://user-images.githubusercontent.com/77927393/135838716-85f09d0a-7dfb-4616-a401-71fa5d144c58.png)
using shaders you can do this

**Comment by AkashiiKun** [comment]
That's Complementary's integrated PBR and emissives (through code)
