### ISSUE TITLE
It may rendering wrongly?

### ISSUE THREAD

**Issue by ElinM-Challenge** [IrisShaders/Iris#918]
### What happened?

A bug happened!

### Screenshots

At first everything is fine.
![Minecraft 1 16 5 2021_10_5 7_02_24](https://user-images.githubusercontent.com/91921730/135937012-c466af89-e110-4e93-bcbd-31c7296a9cc6.png)

But once i enter my saves,Iris will rendeing wrongly like this:
![Minecraft 1 16 5 2021_10_5 7_06_02](https://user-images.githubusercontent.com/91921730/135937120-bea18155-8053-4ac3-b2b1-3bed3964c979.png)

(My skin is black XD)

![Minecraft 1 16 5 2021_10_5 7_06_10](https://user-images.githubusercontent.com/91921730/135937180-bd4fe041-d626-402c-bbc2-fa2f867fddf5.png)
![Minecraft 1 16 5 2021_10_5 7_06_20](https://user-images.githubusercontent.com/91921730/135937193-86b98946-3e77-4225-a2f3-43afcfd5aace.png)

### Iris and Minecraft Version

iris-and-sodium-mc1.16.5-1.1.2+build.4

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX3050 Laptop GPU

### Java Version

Java 8

**Comment by coderbot16** [comment]
You have an ancient version of Xaero's World Map installed. Update it and the issue will be resolved.

Also, please don't report bugs with cheats enabled.

**Comment by ElinM-Challenge** [comment]
Thank you！I'll not report bugs with cheats enabled.
