### ISSUE TITLE
Use Canvas materialmaps to automatically infer additional mappings for block.properties

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#92]
Shader packs have a `block.properties` file that has rough purpose of defining materials. For example, a shader pack may link `minecraft:oak_leaves` and the other leaf blocks to a given ID, such as `block.18`. Then, the given block ID (or, more properly, a material ID), is used to selectively apply certain affects. For example, leaf and foliage blocks generally wave, water generally takes on completely different rendering, and lava has some general wavy effects.

Unfortunately, few shaderpacks include support for mods. This means that your Terrestria sakura leaves won't wave with most shaderpacks, for example. And, even when shaderpacks support mods, often they only support popular mods, and even then only partially.

Canvas has a similar system in the form of materialmaps. Materialmaps are designed in a much better way and fully support mods. Since many mods include built-in support for Canvas materialmaps, Iris could read these files in order to automatically apply affects such as leaf waving to modded blocks. It should be fairly easy to reverse-engineer materials from block ID groupings: for example if all vanilla leaf blocks map to `block.18`, it's safe to say that `block.18` is the render material for leaves.

Ironically, this could mean that installing something like [More Canvas Compat](https://github.com/TeamMidnightDust/MoreCanvasCompat) would also help with Iris compatibility.

**Comment by ColdIce1605** [comment]
Ha maybe renamed to More Mod Compat?

**Comment by IMS212** [comment]
This would be interesting, mods being able to control shader settings easily without intervention from the shaderpack

**Comment by OverlordsIII** [comment]
Would it be worth looking into some common tags or something like that as well for something like this?
Like doing the same thing by figuring out `block.18` is for leaves and then add entries for everything in `c:leaves` to `block.18` in the properties map?

Also somewhat similar, but supporting tags for block, item, and entity.properties?

**Comment by Motschen** [comment]
Well, if this happens I will definitely rename More Canvas Compat to "More Renderer Compat"

**Comment by FoundationGames** [comment]
Really like this idea, being able to plug-n-play OptiFine shaders with mods that have canvas materialmaps

**Comment by IMS212** [comment]
Finally closing this. This has been mostly achieved with support for tags in block.properties (using tags such as `%leaves`).
