### ISSUE TITLE
Add Support For Conduit Power Vision

### ISSUE THREAD

**Issue by captainharrie** [IrisShaders/Iris#93]
Currently optifine doesn't let shader packs check if the player has conduit power, so the underwater night vision effect is broken.
Just wanted to make sure you guys didnt miss this in your testing, since obviously sildurs can't support something optifine doesn't allow and its easy to miss. Apologies if you're already aware!

**Comment by coderbot16** [comment]
It appears that OptiFine doesn't support anything like this, but I've added support for it using the same uniform as night vision, since when you're underwater it has the same effect as night vision. Hope this helps!
