### ISSUE TITLE
entity with renderGlowingArmorMixin crashes the game

### ISSUE THREAD

**Issue by T3mp3lis** [IrisShaders/Iris#931]
### Iris and Minecraft Version

Iris 1.1.2+build.9 for mc1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Radeon RX590

### Java Version

java 16

### Reproduction Steps

1. either adventurez or eldritch mobs mod present
2. night tme
3. wait for entity to spawn with enchanted armor (trigger the renderGlowingArmorMixin)
4. game crashes

### Crash Report file and latest.log

```shell
https://gist.github.com/T3mp3lis/722f40a556983821f59ad4258910eb6f
```

### Additional context

Not sure if it's tied to the armor at all, but maybe the glowing effect itself, since I had a crash where the rendered player entity was the issue, and I had a enchanted effect on an item in my hotbar inventory (see crashlog from 8:21 pm)

**Comment by coderbot16** [comment]
Closing due to no response.
