### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by AmonRay** [IrisShaders/Iris#934]
### Iris and Minecraft Version

iris-and-sodium-mc1.17-1.1.2+build.9.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

win 10

### What is your GPU?

RX 570

### Java Version

Java 16

### Reproduction Steps

idk, crashes is absolutelly random

### Additional context

We are playing via RadminVPN, the issue is not reproduced for me, everything works as expected (im a host), but not for my friend his game crashes periodically, I don't know how to reproduce this for 100%. This is his crashlog and his specifications. I hope u have any idea about this :(

**Comment by NoComment1105** [comment]
If you could acquire some logs or crash reports from your freind that would be ideal for diagnosing this issue
