### ISSUE TITLE
Seus Hrr 2.1 Doesn't load

### ISSUE THREAD

**Issue by carricktoupe** [IrisShaders/Iris#953]
### What happened?

Loaded Iris for 1.17 with fabric, hit apply for the shader, but when I left the settings menu, the shader hadn't worked. Minecraft still had the default look.

### Screenshots

![2021-10-31_11 03 00](https://user-images.githubusercontent.com/66084314/139589807-ad5f3c3d-bf24-4cf1-9628-2ed6992a9225.png)

### Iris and Minecraft Version

iris-mc1.17-1.1.3-starline+build.596.jar

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD 5600 xt

### Java Version

Java 16

**Comment by coderbot16** [comment]
Starline isn't supported.
