### ISSUE TITLE
Sky disappears when using ProjectLuma shaders

### ISSUE THREAD

**Issue by kingarthur0975** [IrisShaders/Iris#960]
### What happened?

When using the shaderpack ProjectLuma (the successor to KUDA) everything seems to work perfectly, except that the sky doesn't render. An image is attached:

### Screenshots

![2021-11-06_20 53 10](https://user-images.githubusercontent.com/61174908/140630652-44f1d385-8db0-40c8-8257-995fac37eb70.png)

### Iris and Minecraft Version

Iris 1.1.2 for 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1660

### Java Version

Java 16

**Comment by AlsoSylv** [comment]
This is a known bug, it should ideally be fixed by next iris release

**Comment by AlsoSylv** [comment]
Similar to #736, but leaving open as this is for Luma specifically

**Comment by kingarthur0975** [comment]
Alright, thank you. It's nice to know that it'll be fixed soon, because Luma is one of my favorite shaderpacks.

**Comment by coderbot16** [comment]
Fixed in 1.1.3
