### ISSUE TITLE
Sodium creates a strange symmetry in water (with Shaders) (only in 1.17.1)

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#961]
### What happened?

first bug:
Seed: 933314485498261191
/execute in minecraft:overworld run tp @s 679.58 80.13 -257.36 2.04 88.20

second bug:
Seed: 933314485498261191
/execute in minecraft:overworld run tp @s 679.58 80.13 -259.57 0.39 42.30

Sodium creates a strange symmetry in water (with Shaders)
#625

### Screenshots

Iris with sodium: 
![2021-11-07_11 53 41](https://user-images.githubusercontent.com/68275908/140645912-85fd27ff-9285-40e1-bcfa-b50cc66b4c5f.png)

Iris without sodium:
![2021-11-07_11 55 57](https://user-images.githubusercontent.com/68275908/140645938-1f9e90cf-0f9b-4322-baa4-1c566d76a229.png)

Optifine:
![2021-11-07_11 57 30](https://user-images.githubusercontent.com/68275908/140645951-086c021b-bf60-419a-b4b5-20d189a6d0cf.png)

### Iris and Minecraft Version

fabric-loader-1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Ubuntu 20.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by edwloef** [comment]
This might be another instance of #625

**Comment by Lolothepro** [comment]
A similar bug occurs on the reflection of the dirt

Iris with sodium:
![2021-11-07_16 18 01](https://user-images.githubusercontent.com/68275908/140652205-2400384c-b313-41ce-8a2a-036c5e50bf46.png)

Iris without sodium:
![2021-11-07_16 16 50](https://user-images.githubusercontent.com/68275908/140652237-f5cb04f0-5f9e-4e02-8542-b2c91c5dbc3f.png)

Optifine:
![2021-11-07_16 19 06](https://user-images.githubusercontent.com/68275908/140652247-c7e61b2c-e8e8-433f-95f9-aea736a74370.png)

**Comment by Lolothepro** [comment]
(complementary shaders)

**Comment by natrixdev** [comment]
> (complementary shaders)

oh loïc
