### ISSUE TITLE
Items in my hand won't work with shaderpacks.

### ISSUE THREAD

**Issue by Heeemit** [IrisShaders/Iris#966]
### What happened?

When first loading up Iris on 1.17.1, I loaded up BSL Shaders. Everything seemed to be fine, except for my hand. and the items in my hand.
I've also used Complimentary Shaders, and the same problem occurs.

### Screenshots

![image](https://user-images.githubusercontent.com/94023339/141026058-a5a8bbc3-29a6-4645-bf28-fdaa8510c5ce.png)
![image](https://user-images.githubusercontent.com/94023339/141025835-2e7b7e00-e9e5-4d6c-8378-3fd37cd63826.png)

### Iris and Minecraft Version

iris-mc1.17.1-2.0.1.jar for Minecraft 1.16.5

### Are you running Sodium along with Iris?

No

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 970

### Java Version

Java 16

**Comment by maximumpower55** [comment]
known issue will be fixed in the next release if this gets #909 merged

**Comment by coderbot16** [comment]
Fixed with the merge of https://github.com/IrisShaders/Iris/pull/909
