### ISSUE TITLE
BSL Aurora not working because Custom Uniforms are unsupported

### ISSUE THREAD

**Issue by ghost** [IrisShaders/Iris#973]
### What happened?

When changing options in BSL shaders, Aurora is not working, the first picture is from optifine and the second from Iris.

### Screenshots

![image](https://user-images.githubusercontent.com/89903758/141683223-9867d676-9238-4761-b3cb-36750e661185.png)
![image](https://user-images.githubusercontent.com/89903758/141683231-32b9c125-9d78-4ea4-81a4-3008d088e564.png)

### Iris and Minecraft Version

iris-mc1.17.1-1.1.2.jar for Minecraft 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11 Home

### What is your GPU?

Nvidia GeForce GTX 1650 Ti

### Java Version

Minecraft running on Java 16 + Iris installed with Java 8

**Comment by coderbot16** [comment]
This is caused by https://github.com/IrisShaders/Iris/issues/1027
