### ISSUE TITLE
Strange stretched and discolored texture groups that look like the tentacles of some lovecraftian abomination.

### ISSUE THREAD

**Issue by Corvus20** [IrisShaders/Iris#976]
### What happened?

Very strange stretched and discolored groups of textures from seemingly random places. Not sure if there is a specific term for it. They just appear in the world at random.

### Screenshots

![2021-11-15_18 13 47](https://user-images.githubusercontent.com/75586106/141868007-1d8bb42b-5a03-4773-83c7-961f98031949.png)
![2021-11-15_18 22 31](https://user-images.githubusercontent.com/75586106/141868384-e7634505-eaee-4a17-a840-b90f6f1b2d79.png)
![2021-11-15_18 23 10](https://user-images.githubusercontent.com/75586106/141868387-9d917818-854e-4159-81a0-55d87e1d0ea1.png)
![2021-11-15_18 23 21](https://user-images.githubusercontent.com/75586106/141868389-fe1ffef7-0980-4fba-a954-91a3d09f19e1.png)
![2021-11-15_18 22 20](https://user-images.githubusercontent.com/75586106/141868391-813fd3e6-1680-40d2-a245-9c51995f7abf.png)

### Iris and Minecraft Version

 Iris v1.1.2 + Sodium for MC 1.17.1, Fabric 0.12.5

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

AMD Radeon R7 200 Series

### Java Version

Java 16

### Additional context

I tried remove all other mods that could possibly have an effect on the rendering. These weird stretchy things only vanished once I tried removing Iris+Sodium.

**Comment by NoComment1105** [comment]
Switch the memory allocator in the video settings advanced tab to SWAP and see if the issue Re occurs

**Comment by coderbot16** [comment]
I'm assuming that this issue happens with just Sodium too - please report this to Sodium, not us.
