### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by deadlyfalc** [IrisShaders/Iris#977]
Error code 1 when enabling it with sodium and linquitum when shaders aare turned on

**Comment by NoComment1105** [comment]
We need a crash report and way mroe information

**Comment by deadlyfalc** [comment]
ok wait

**Comment by deadlyfalc** [comment]
![Console window for 1 17 1 - MultiMC 5 16-11-2021 13_47_38](https://user-images.githubusercontent.com/93069349/141947156-6d72faa5-feb0-4393-bd2d-e562c67b7c50.png)
![Console window for 1 17 1 - MultiMC 5 16-11-2021 13_47_53](https://user-images.githubusercontent.com/93069349/141947159-633cc4e9-7e64-420c-8201-df2469baa3e5.png)

**Comment by deadlyfalc** [comment]
this is the error whilr loading shaders

**Comment by deadlyfalc** [comment]
and i am using this mods and chocopatic13 medium beta shaders

**Comment by NoComment1105** [comment]
I need a text file of the log so I can actually see what happened

**Comment by deadlyfalc** [comment]
[log file.txt](https://github.com/IrisShaders/Iris/files/7544562/log.file.txt)

**Comment by deadlyfalc** [comment]
this is the log file

**Comment by deadlyfalc** [comment]
i think its the shaders

**Comment by NoComment1105** [comment]
You crashed with an out of memory error, please allocate more start up memory (-Xms) and see if the crash Re occurs

**Comment by deadlyfalc** [comment]
ok

**Comment by deadlyfalc** [comment]
nope not fixed

**Comment by NoComment1105** [comment]
Try with Iris alone and see if the issue still occurs, if not, then this is a matter for another place, once the issue is tracked down
