### ISSUE TITLE
Remaining things to implement with forkless Sodium compatibility

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#983]
- 1.16.5 issues
    - [X] Make 1.16.5 link to https://www.curseforge.com/minecraft/mc-mods/sodium/files/3488820 instead.
- 1.17.1+ issues
    - [x] MixinWorldRenderer: Do not cancel skybox rendering if shaders are enabled
    - [x] #990
    - [x] ~~Check if https://github.com/IrisShaders/Iris/issues/792 was fixed~~ Edit: not fixed
    - [x] Figure out how to deal with the Shadow remapping issue in dev other than by disabling `mixin.features.texture_tracking` and `mixin.features.texture_updates`
- Common issues
    - [x] ~~Loosen Sodium version locks with SemVer~~ Sodium doesn't use SemVer

**Comment by IMS212** [comment]
I have a PR #986 to fix the alpha cutoff.

**Comment by coderbot16** [comment]
- [ ] Lock the Sodium version to an exact version to stop people from running with the wrong Sodium version, because 0.3 is too loose.

**Comment by coderbot16** [comment]
https://github.com/IrisShaders/Iris/issues/792 is confirmed to *not* be fixed.

**Comment by IMS212** [comment]
Everything here should be fixed as of now,
