### ISSUE TITLE
Burning texture doesn't draw in first person with shaders enabled when player is on fire

### ISSUE THREAD

**Issue by Zero-MF** [IrisShaders/Iris#998]
### What happened?

Use Flint and Steel to create fire, step into fire, notice no burning texture.

### Screenshots

Shaders disabled:
![2021-11-22_22 44 20](https://user-images.githubusercontent.com/90244203/142939928-8a0b4936-9928-4e64-b09e-8a080539b089.png)
Shaders enabled:
![2021-11-22_22 44 01](https://user-images.githubusercontent.com/90244203/142939950-8b91bbfe-2fbf-4921-87dd-ce0b9a2bd7ab.png)

### Iris and Minecraft Version

iris-mc1.18-pre4-1.1.3-pre+rev.9e69d42-dirty

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce GTX 1060

### Java Version

Java 17.0.1

**Comment by coderbot16** [comment]
@maximumpower55 This is because GameRenderer#renderItemInHand is used for rendering the fire texture as well, so we have to cancel that specific part of the method instead of cancelling the whole method.
